'use strict';
const B6References={token:null,rows:[],at:0,pending:false,error:''};
function b6PriceReferences(){
 if(!document.querySelector('[data-cost-sources]')||Team.loaded&&(!Team.permissions.costs||!Team.permissions.sections?.includes('materials')))return;
 const token=Team.loaded?Team.csrf:'local';if(B6References.token!==token)Object.assign(B6References,{token,rows:[],at:0,pending:false,error:''});
 const paint=()=>{for(const row of TPCostInput.view(db.quote)){
  if(!/^(material:|rate:|rate-option:)/.test(row.key))continue;
  const box=[...document.querySelectorAll('[data-cost-inline]')].find(el=>el.dataset.costInline===row.key);if(!box)continue;
  let panel=box.querySelector('[data-price-references]');if(!panel){panel=document.createElement('details');panel.dataset.priceReferences='';box.cells[0].append(panel);}
  const ref=B6References.rows.find(r=>r.identity===row.identity&&r.unit===row.unit),prices=ref?.prices||[],disabled=box.querySelector('[name=sourceValue]').disabled;
  const html='<summary>Giá tham khảo · tối đa 3 lần cập nhật</summary><p class="help-text">Danh mục chung đã lưu; chỉ tham khảo. Tự rà điều kiện thuế và căn cứ trước khi xác nhận.</p>'+(B6References.error?'<p>'+esc(B6References.error)+'</p>':prices.length?prices.map((r,i)=>`<div><strong>${num(r.value,6)} đ/${esc(row.unit)}</strong><small class="subtext">${esc(r.at?new Date(r.at).toLocaleString('vi-VN'):'Danh mục trên máy')} ${r.version?' · phiên bản '+esc(r.version):''}</small><button type="button" class="button small" data-reference-pick="${i}" ${disabled?'disabled':''}>Dùng giá này để rà soát</button></div>`).join(''):'<p>Chưa có giá danh mục cùng quy cách / cách tính và đơn vị.</p>');
  if(panel._html!==html){panel.innerHTML=html;panel._html=html;}
  panel.onclick=e=>{const b=e.target.closest('[data-reference-pick]');if(!b||b.disabled)return;try{inWritable();if(!deviceEditable()||box.querySelector('[name=sourceValue]').disabled)throw Error('Bản đang khóa');box.querySelector('[name=sourceValue]').value=prices[Number(b.dataset.referencePick)].value;b6SourceDirty(box);box.querySelector('[name=sourceValue]').focus({preventScroll:true});}catch(error){toast(error.message);}};
 }};
 paint();if(B6References.pending||Date.now()-B6References.at<15000)return;B6References.pending=true;
 const request=Team.loaded?teamApi('intake/cost-price-references'):Promise.resolve(TPCostInput.referenceHistory([{document:db}]));
 request.then(rows=>{if(B6References.token!==token)return;B6References.rows=rows;B6References.error='';}).catch(error=>{if(B6References.token===token)B6References.error='Chưa tải được giá tham khảo: '+error.message;}).finally(()=>{if(B6References.token===token){B6References.pending=false;B6References.at=Date.now();paint();}});
}
function b6CostPrices(){const rows=TPCostInput.view(db.quote),link=teamCurrent(),locked=['submitted','approved'].includes(link?.status||db.quote.status),editHint=locked?`<div class="notice">Đã xác nhận nguồn giá vẫn có thể sửa trên bản nháp. Báo giá này ${link?.status==='submitted'||db.quote.status==='submitted'?'đang chờ duyệt':'đã duyệt'} nên các ô bị khóa. ${Team.permissions?.reopen&&!link?.readOnly?teamButton('Tạo bản sửa để chỉnh giá','reopen'):'Nhờ quản trị hoặc người có quyền mở sửa tạo bản sửa; tài khoản hiện tại chưa thể mở sửa bản này.'}</div>`:'';return `<section class="panel intake-panel" data-cost-sources><div class="section-toolbar"><div><h3>Khai nguồn giá chi phí</h3><p>Tab: ô kế tiếp · Enter: xuống cùng cột dòng sau · Ctrl+Enter: xác nhận và chuyển dòng. Lưu báo giá lên máy chủ để chia sẻ.</p><strong>${rows.filter(r=>r.known).length}/${rows.length} dòng đã xác nhận nguồn giá</strong></div><button class="button" data-b6="cost-history">Lịch sử nguồn giá</button></div>${editHint}<div class="table-scroll"><table class="b6-source-grid"><thead><tr><th>Đầu vào / nơi sử dụng</th><th>ĐVT</th><th>Giá đang tính</th><th>Trạng thái</th><th>Giá nguồn</th><th>Thuế trong giá</th><th>Thuế suất (%)</th><th>Căn cứ / tài liệu</th><th>Xác nhận</th></tr></thead><tbody>${rows.map(r=>{const old=r.known?r.record:null,disabled=!deviceEditable()||(Team.loaded&&!Team.permissions.factors&&r.key.startsWith('tmc:')),attr=disabled?'disabled':'';return `<tr data-cost-known="${r.known?'true':'false'}" data-cost-inline="${esc(r.key)}" data-expected="${esc(TPCostInput.signature([r.identity,r.value]))}"><td>${esc(r.label)}</td><td>${esc(r.unit)}</td><td>${num(r.value,6)}</td><td><strong data-cost-status>${r.known?'✓ Đã xác nhận':r.record?'! Cần xác nhận lại':'○ Chưa xác nhận'}</strong></td><td><input aria-label="Giá nguồn" name="sourceValue" type="number" min="0" step="any" required value="${esc(old?.original??r.value)}" ${attr}></td><td><select aria-label="Thuế trong giá" name="sourceStatus" ${attr}>${[['unknown','Chưa khai'],['excluded','Chưa gồm thuế'],['included','Đã gồm thuế']].map(([v,l])=>`<option value="${v}" ${(old?.status||'unknown')===v?'selected':''}>${l}</option>`).join('')}</select></td><td><input aria-label="Thuế suất trong giá" name="sourceRate" type="number" min="0" max="100" step="any" value="${esc(old?.rate??'')}" ${attr}></td><td><input aria-label="Căn cứ tài liệu" name="sourceReason" required maxlength="1000" value="${esc(old?.reason||'')}" ${attr}></td><td><button type="button" class="button small" data-b6="cost-inline-save" ${attr}>Xác nhận ↓</button></td></tr>`;}).join('')}</tbody></table></div><p class="help-text">Xác nhận cập nhật đúng dòng; không sửa danh mục. Chỉ nhập thuế suất khi giá nguồn đã gồm thuế.</p></section>`;}
function b6SourceDirty(box){box.dataset.costKnown='false';const status=box.querySelector('[data-cost-status]');if(status)status.textContent='✎ Đang sửa, chưa xác nhận';}
function b6CostInlineSave(box){inWritable();if(!deviceEditable())throw Error('Bản đang khóa');const key=box.dataset.costInline;if(Team.loaded&&!Team.permissions.factors&&key.startsWith('tmc:'))throw Error('Tài khoản không được sửa bảng TMC');for(const el of box.querySelectorAll('input,select'))if(!el.reportValidity())return;const get=name=>box.querySelector('[name="'+name+'"]').value;if(get('sourceStatus')==='unknown')throw Error('Chọn giá đã gồm thuế hoặc chưa gồm thuế trước khi xác nhận');const update={key,expected:box.dataset.expected,original:get('sourceValue'),status:get('sourceStatus'),rate:get('sourceRate')},reason=get('sourceReason');TPCostInput.apply(C.copy(db.quote),[update],reason);const ordered=[...document.querySelectorAll('[data-cost-inline]')],nextKey=ordered.slice(ordered.indexOf(box)+1).find(el=>!el.querySelector('input').disabled)?.dataset.costInline,scrollX=window.scrollX,scrollY=window.scrollY;const drafts=[...document.querySelectorAll('[data-cost-inline]')].filter(el=>el!==box).map(el=>({key:el.dataset.costInline,expected:el.dataset.expected,dirty:el.querySelector('[data-cost-status]')?.textContent.startsWith('✎'),values:[...el.querySelectorAll('input,select')].map(input=>[input.name,input.value])}));mutation(()=>TPCostInput.apply(db.quote,[update],reason));for(const draft of drafts){const el=[...document.querySelectorAll('[data-cost-inline]')].find(el=>el.dataset.costInline===draft.key&&el.dataset.expected===draft.expected);if(el){for(const [name,value] of draft.values)el.querySelector('[name="'+name+'"]').value=value;if(draft.dirty)b6SourceDirty(el);}}const target=[...document.querySelectorAll('[data-cost-inline]')].find(el=>el.dataset.costInline===(nextKey||key));window.scrollTo(scrollX,scrollY);if(target){const input=target.querySelector('input');input.focus({preventScroll:true});target.scrollIntoView({block:'nearest',inline:'nearest',behavior:'instant'});}toast('Đã xác nhận nguồn giá dòng này. Lưu báo giá lên máy chủ để chia sẻ.');}
function b6CostEdit(key){inWritable();if(Team.loaded&&!Team.permissions.factors&&key.startsWith('tmc:'))throw Error('Tài khoản không được sửa bảng TMC');const row=TPCostInput.rows(db.quote).find(r=>r.key===key);if(!row)throw Error('Dòng giá đã thay đổi');const s=TPCostInput.state(db.quote,row),old=s.known?s.record:null,expected=TPCostInput.signature([row.identity,row.value]);
 openDialog('Khai nguồn giá chi phí',`<p>${esc(row.label)} · ${esc(row.unit)}</p><p>Giá đang tính: <strong>${num(row.value,6)}</strong>. Chỉ cập nhật đầu vào này của báo giá.</p>${field('Giá trên tài liệu nguồn','sourceValue',old?.original??row.value,'number','min="0" step="any" required')}${select('Thuế trong giá nguồn','sourceStatus',[['unknown','Chưa xác nhận — chỉ để thử tính'],['excluded','Chưa gồm thuế'],['included','Đã gồm thuế']],old?.status||'unknown')}${field('Thuế suất đã nằm trong giá (%)','sourceRate',old?.rate??'','number','min="0" max="100" step="any"')}${field('Căn cứ / tài liệu nguồn','sourceReason',old?.reason||'','text','required maxlength="1000"')}<output id="cost-net-preview" class="notice" aria-live="polite"></output><label class="device-confirm"><input name="confirmSource" type="checkbox" required> Xác nhận giá nguồn, điều kiện thuế và cập nhật giá đang tính của đúng dòng này.</label><p class="help-text">Sau khi đổi giá chi phí, rà và xác nhận lại mặt bằng giá/thuế toàn báo giá trước phát hành. Bản đã duyệt không bị sửa.</p>`,'Quy đổi và lưu',f=>{if(!f.has('confirmSource'))throw Error('Xác nhận cập nhật');const update={key,expected,original:f.get('sourceValue'),status:f.get('sourceStatus'),rate:f.get('sourceRate')},trial=C.copy(db.quote);TPCostInput.apply(trial,[update],f.get('sourceReason'));saveAndClose(()=>TPCostInput.apply(db.quote,[update],f.get('sourceReason')),'Đã giữ nguồn và cập nhật giá chi phí');});
 const preview=()=>{const f=new FormData($('#dialog-form')),trial=C.copy(db.quote);try{const change=TPCostInput.apply(trial,[{key,original:f.get('sourceValue'),status:f.get('sourceStatus'),rate:f.get('sourceRate')}],'Xem trước')[0];$('#cost-net-preview').textContent=(f.get('sourceStatus')==='unknown'?'Chưa xác nhận, số thử tính: ':'Giá chưa thuế sẽ áp dụng: ')+num(change.after.net,6)+' / '+row.unit;}catch(e){$('#cost-net-preview').textContent=e.message;}};$('#dialog-form').addEventListener('input',preview);$('#dialog-form').addEventListener('change',preview);preview();
}
function b6History(){openDialog('Lịch sử nguồn giá và danh mục',`<p>Giữ số trước/sau, thuế nguồn và căn cứ. Danh tính trình duyệt chưa xác thực; máy chủ giữ phiên bản/người thực hiện riêng.</p><h3>Nguồn giá trong báo giá</h3>${(db.quote.costPriceHistory||[]).slice().reverse().map(x=>`<details><summary>${esc(x.label)} · ${esc(x.at)}</summary><pre>${esc(JSON.stringify(x,null,2))}</pre></details>`).join('')||'<p>Chưa khai nguồn giá.</p>'}<h3>Thay đổi giá / đơn vị / hãng trong đơn</h3>${(db.quote.inputPriceAudit||[]).slice().reverse().map(x=>`<details><summary>${esc(x.at)} · ${esc(x.actor)}</summary><pre>${esc(JSON.stringify(x.changes,null,2))}</pre></details>`).join('')||'<p>Chưa có thay đổi.</p>'}<h3>Danh mục làm việc</h3>${(db.catalogPriceHistory||[]).slice().reverse().map(x=>`<details><summary>${esc(x.at)} · ${esc(x.actor)}</summary><pre>${esc(JSON.stringify(x.changes,null,2))}</pre></details>`).join('')||'<p>Chưa có thay đổi. Danh mục máy chủ có lịch sử phát hành riêng.</p>'}`);$('#dialog').classList.add('wide-dialog');}
function b6TermsPanel(){const errors=TPOfferTerms.errors(db.quote);return `<section class="panel intake-panel" data-offer-terms><div class="section-toolbar"><div><h3>Mẫu ký và điều kiện phát hành</h3><p>${errors.length?errors.map(esc).join(' · '):'Đã chọn và xác nhận mẫu/nội dung cho bản này; vẫn cần duyệt giá để phát hành.'}</p></div><button class="button primary" data-b6="terms" ${deviceEditable()?'':'disabled'}>Chọn mẫu và điều kiện</button></div><p class="help-text">Không tự coi mẫu một bên ký là quy định của Trường Phát. Khai theo từng báo giá; đây là bố cục phần ký, không phải chữ ký số.</p></section>`;}
function b6TermsEdit(){inWritable();if(Team.loaded&&!Team.permissions.commercial)throw Error('Tài khoản không được sửa bản chào giá');const q=db.quote,s=q.offerTerms||{};openDialog('Mẫu ký và điều kiện bản chào',`<p>Thông tin khách, công trình và đơn vị chào lấy từ báo giá. Chưa khai hoặc chưa xác nhận thì chỉ là bản làm việc.</p><div class="form-grid">${select('Bố cục phần ký','signature',[['','Chưa chọn'],['issuer','Bên chào ký'],['both','Bên chào và bên nhận'],['none','Không bố trí phần ký']],s.signature||'')}${field('Chức danh bên chào','signerTitle',s.signerTitle||'')}${field('Tên người ký bên chào','signer',q.issuer?.signer||'')}${field('Nhãn phần ký bên nhận','customerTitle',s.customerTitle||'')}${field('Tên bên nhận (có thể để trống chờ ký)','customerSigner',s.customerSigner||'')}</div>${[['delivery','Điều kiện giao hàng'],['installation','Phạm vi lắp đặt'],['payment','Điều kiện thanh toán'],['warranty','Bảo hành'],['scope','Các khoản / phạm vi đã gồm trong giá']].map(([key,label])=>`<label class="field"><span>${label}</span><textarea name="${key}" rows="2" maxlength="2000">${esc(s[key]||'')}</textarea></label>`).join('')}${field('Căn cứ cho phép dùng mẫu / nội dung này','termsReason',s.reason||'','text','maxlength="1000"')}<label class="device-confirm"><input name="confirmTerms" type="checkbox"> Xác nhận mẫu ký và điều kiện này được phép dùng cho báo giá; đã rà ghi chú không mâu thuẫn giá/thuế/phạm vi.</label><p class="help-text">Ghi “Không áp dụng” nếu thực tế không có, không để hệ thống tự suy. Mọi khoản phân rã đã gồm trong giá không được cộng thêm lần nữa. Có thể lưu chưa xác nhận để bổ sung sau.</p>`,'Lưu mẫu và điều kiện',f=>{const trial=C.copy(q);trial.issuer??={};trial.issuer.signer=String(f.get('signer')||'').trim();const data=Object.fromEntries(['delivery','installation','payment','warranty','scope','signature','signerTitle','customerTitle','customerSigner'].map(k=>[k,f.get(k)]));data.reason=f.get('termsReason');TPOfferTerms.save(trial,data,f.has('confirmTerms'));saveAndClose(()=>{q.issuer=trial.issuer;TPOfferTerms.save(q,data,f.has('confirmTerms'));},'Đã lưu theo báo giá này');});$('#dialog').classList.add('wide-dialog');b6TermsTemplatesMount();}
function b6TermsTemplatesMount(){
 const form=$('#dialog-form'),keys=['delivery','installation','payment','warranty','scope','signature','signerTitle','customerTitle','signer'];
 form.querySelector('.dialog-body').insertAdjacentHTML('afterbegin',`<section class="notice"><label class="field"><span>Mẫu đã lưu</span><select data-terms-template><option value="">Chọn mẫu để điền vào bản này</option></select></label><label class="field"><span>Tên mẫu dùng lại</span><input data-terms-template-name maxlength="120" placeholder="Ví dụ: Giao tại xưởng, thanh toán 30/70"></label><button type="button" class="button" data-terms-template-save>Lưu nội dung hiện tại thành mẫu</button><p class="help-text">Mẫu dùng chung cho bộ phận chào giá. Chọn mẫu rồi sửa riêng theo đơn; không đổi báo giá cũ. Không sao chép tên khách nhận ký hoặc xác nhận của đơn trước.</p><p data-terms-template-status role="status"></p></section>`);
 const picker=form.querySelector('[data-terms-template]'),status=form.querySelector('[data-terms-template-status]'),button=form.querySelector('[data-terms-template-save]');let rows=[];
 const localKey='tp-offer-term-templates',shared=!!Team.user,generation=Team.sessionGeneration,quote=db.quote;
 const active=()=>form.isConnected&&$('#dialog')?.open&&db.quote===quote&&Team.sessionGeneration===generation;
 let edited=false;form.addEventListener('input',()=>{edited=true;});form.addEventListener('change',()=>{edited=true;});
 const blank=()=>['delivery','installation','payment','warranty','scope','signature','signerTitle','customerTitle'].every(k=>!form.elements[k].value.trim());
 async function load(prefill=false){const result=shared?await teamApi('intake/offer-templates'):JSON.parse(localStorage.getItem(localKey)||'[]');if(!active())return;rows=result;picker.innerHTML='<option value="">Chọn mẫu để điền vào bản này</option>'+rows.map((r,i)=>`<option value="${i}">${esc(r.name)} · ${esc(r.at?new Date(r.at).toLocaleString('vi-VN'):'')}</option>`).join('');if(prefill&&!edited&&blank()&&rows.length){picker.value='0';picker.onchange();status.textContent='Đã điền mẫu đã lưu gần nhất: '+rows[0].name+'. Có thể chọn mẫu khác hoặc chỉnh sửa; rà soát rồi lưu cho đơn này.';}else if(!rows.length)status.textContent='Chưa có mẫu dùng lại. Điền nội dung rồi bấm Lưu nội dung hiện tại thành mẫu.';}
 picker.onchange=()=>{if(picker.value==='')return;const row=rows[Number(picker.value)];for(const key of keys)form.elements[key].value=row.data[key]||'';form.elements.confirmTerms.checked=false;form.querySelector('[data-terms-template-name]').value=row.name;status.textContent='Đã điền mẫu. Có thể chỉnh nội dung rồi lưu cho báo giá này.';};
 button.onclick=async()=>{if(!active())return;button.disabled=true;try{const nameInput=form.querySelector('[data-terms-template-name]'),name=nameInput.value.trim()||'Mẫu điều kiện '+new Date().toLocaleString('vi-VN');const data=Object.fromEntries(keys.map(k=>[k,form.elements[k].value.trim()]));if(!['delivery','installation','payment','warranty','scope','signature'].some(k=>data[k]))throw Error('Điền nội dung trước khi lưu thành mẫu.');if(shared)await teamApi('intake/offer-templates','POST',{name,data});else{const saved=JSON.parse(localStorage.getItem(localKey)||'[]');saved.unshift({name,data,at:new Date().toISOString()});localStorage.setItem(localKey,JSON.stringify(saved.slice(0,200)));}await load();if(!active())return;nameInput.value=name;const index=rows.findIndex(r=>r.name===name&&keys.every(k=>(r.data[k]||'')===data[k]));if(index>=0)picker.value=String(index);status.textContent='Đã lưu mẫu '+name+'. Đơn mới sẽ được gợi ý mẫu gần nhất; bấm Lưu điều kiện cho đơn này để lưu nội dung đang sửa.';}catch(error){if(active())status.textContent=error.message;}finally{button.disabled=false;}};
 form.querySelector('button[type=submit]').textContent='Lưu điều kiện cho đơn này';
 load(true).catch(error=>{if(active())status.textContent='Chưa tải được mẫu: '+error.message;});
}
function b6TermsHtml(s,issuer){return `<div class="paper-terms b6-public-terms">${TPOfferTerms.lines(s).map(([k,v])=>`<p><strong>${esc(k)}:</strong> ${esc(v).replace(/\n/g,'<br>')}</p>`).join('')}</div>`;}
function b6Sign(s,issuer){if(!s?.signature)return '<p class="notice warning">Chưa chọn mẫu phần ký</p>';if(s.signature==='none')return '';return `<div class="signatures b6-signatures">${s.signature==='both'?`<div><strong>${esc(s.customerTitle)}</strong><small>${esc(s.customerSigner||'Ký, ghi rõ họ tên')}</small></div>`:''}<div><strong>${esc(s.signerTitle)}</strong><small>${esc(issuer?.signer||'Ký, ghi rõ họ tên')}</small></div></div>`;}
function installBatchSixUI(){
 document.addEventListener('input',e=>{const box=e.target.closest('[data-cost-inline]');if(box)b6SourceDirty(box);});
 document.addEventListener('keydown',e=>{const box=e.target.closest('[data-cost-inline]');if(!box||e.isComposing||e.key!=='Enter')return;if(e.target.tagName==='BUTTON')return;e.preventDefault();try{if(e.ctrlKey||e.metaKey){b6CostInlineSave(box);return;}const rows=[...document.querySelectorAll('[data-cost-inline]')],index=rows.indexOf(box),next=rows[index+(e.shiftKey?-1:1)],target=next?.querySelector('[name="'+e.target.name+'"]');if(target&&!target.disabled){target.focus({preventScroll:true});next.scrollIntoView({block:'nearest',inline:'nearest'});}}catch(err){toast(err.message);}});

 const prices=renderQuotePrices;renderQuotePrices=()=>{queueMicrotask(b6PriceReferences);return prices()+b6CostPrices();};const preview=renderPreview;renderPreview=()=>b6TermsPanel()+preview();
 const paper=renderAdvancedPaper;renderAdvancedPaper=()=>{let html=paper();if(db.quote.documentMode==='official'&&TPOfferTerms.errors(db.quote).length)return '<div class="notice warning">Chưa xác nhận mẫu ký / điều kiện phát hành; tạo bản sửa để bổ sung.</div>';html=html.replace(/<div class="pa-paper-sign">[\s\S]*?<\/div>/,()=>b6Sign(db.quote.offerTerms,db.quote.issuer));html=html.replace(/<p class="pa-paper-scope">[\s\S]*?<\/p>/,()=>b6TermsHtml(db.quote.offerTerms,db.quote.issuer));return html;};
 const sales=salesPaper;salesPaper=o=>sales(o).replace(/<div class="pa-paper-sign">[\s\S]*?<\/div>/,()=>b6TermsHtml(o.offerTerms,o.issuer)+b6Sign(o.offerTerms,o.issuer));
 const sheets=exportSheets;exportSheets=internal=>{if(db.quote.documentMode==='official'&&TPOfferTerms.errors(db.quote).length)throw Error('Chưa xác nhận mẫu ký / điều kiện phát hành');const out=sheets(internal),s=db.quote.offerTerms||{};out[0].rows=out[0].rows.filter(r=>r[0]!=='Phạm vi');out[0].rows.push(...TPOfferTerms.lines(s),['Bố cục ký',s.signature||'Chưa chọn'],['Chức danh bên chào',s.signerTitle||''],['Người ký bên chào',db.quote.issuer?.signer||''],['Bên nhận',s.signature==='both'?[s.customerTitle,s.customerSigner].filter(Boolean).join(' — '):'']);if(internal)out.push({name:'Nguon gia chi phi',widths:[65,18,20,20,20,18,55],rows:[['Đầu vào','ĐVT','Đang tính chưa thuế','Giá nguồn','Tình trạng','Thuế suất trong giá','Căn cứ'],...TPCostInput.view(db.quote).map(r=>[r.label,r.unit,r.value,r.known?r.record.original:'',r.status,r.known?r.record.rate??'':'',r.known?r.record.reason:'Chưa xác nhận / đã đổi'])]});return out;};
 const mutate=mutation;mutation=(action,options={})=>mutate(()=>{const q=db.quote,prices=Object.fromEntries(TPCostInput.view(q).map(r=>[r.key,{value:r.value,identity:r.identity,unit:r.unit}])),catalog=TPCostInput.catalogPrices(db);action();const actor=Team.loaded?Team.user.name:'Phiên trình duyệt (chưa xác thực)',at=new Date().toISOString(),changes=TPCostInput.differences(catalog,TPCostInput.catalogPrices(db));if(changes.length){db.catalogPriceHistory??=[];db.catalogPriceHistory.push({at,actor,changes});}if(q===db.quote&&q.status!=='approved'){const changes=TPCostInput.differences(prices,Object.fromEntries(TPCostInput.view(q).map(r=>[r.key,{value:r.value,identity:r.identity,unit:r.unit}])));if(changes.length){q.inputPriceAudit??=[];q.inputPriceAudit.push({at,actor,changes});}}},options);
 document.addEventListener('click',e=>{const b=e.target.closest('[data-b6]');if(!b)return;try{if(b.dataset.b6==='cost-inline-save')b6CostInlineSave(b.closest('[data-cost-inline]'));if(b.dataset.b6==='cost')b6CostEdit(b.dataset.key);if(b.dataset.b6==='cost-history')b6History();if(b.dataset.b6==='terms')b6TermsEdit();}catch(err){toast(err.message);}});
}
