/* Batch 2: tree dimension formulas and explicit per-operation work policy. */
'use strict';
function b2Dimensions(id){inWritable();const n=C.findNode(db.quote.products,id);if(!n)return;const path=C.nodePath(db.quote.products,id),fields=TPDimensions.fields(n).filter(f=>!f.fixed);if(!fields.length)return toast('Mã này chỉ có quy cách cố định.');
  openDialog('Công thức kích thước · '+esc(n.name),`<p>SELF: chính dòng; PARENT: cấp cha trực tiếp; PRODUCT: sản phẩm chứa dòng; A1, A2…: tổ tiên theo số cấp. Các chiều dài dùng mm. Số trừ 20 trong ví dụ là 20 mm.</p><section class="dimension-product-links"><h3>Liên kết với kích thước sản phẩm</h3>${path.slice(0,-1).reverse().find(x=>x.kind==='product')?`<p>Chọn biến để chèn vào công thức. Ví dụ: PRODUCT_L - 20.</p><div class="dimension-variable-buttons">${TPDimensions.variables(path).filter(v=>v.name.startsWith('PRODUCT_')).map(v=>`<button type="button" class="button small" data-dimension-variable="${esc(v.name)}"><strong>${esc(v.name)}</strong> · ${esc(productParamLabels[v.key]||v.key)}: ${v.node.params?.[v.key]==null?'chưa khai':num(v.node.params[v.key])+' '+esc(v.unit)}</button>`).join('')}</div>`:'<p>Đây là kích thước chung của sản phẩm. Các vật tư bên dưới có thể tham chiếu bằng PRODUCT_L, PRODUCT_W, PRODUCT_H.</p>'}</section>${select('Thông số cần cấu hình','dimensionKey',fields.map(f=>[f.key,f.key+' ('+f.unit+')']),fields[0].key)}<div id="b2-dimension-fields"></div><output id="b2-dimension-result" class="work-live-result"></output><details><summary>Biến được phép tham chiếu</summary><div class="table-scroll"><table><tbody>${TPDimensions.variables(path).map(v=>`<tr><td><code>${esc(v.name)}</code></td><td>${esc(v.node.name)} / ${v.key}</td><td>${esc(v.unit)}</td></tr>`).join('')}</tbody></table></div></details><p class="help-text">Lưu công thức và lịch sử sửa trong chính báo giá. Quy cách cố định của mã vật tư không bị đổi; dữ liệu danh mục và báo giá khác giữ nguyên.</p>`, 'Lưu kích thước',()=>{
    inWritable();const {key,entry}=b2ReadDimension();const trial=C.copy(db.quote.products);TPDimensions.set(trial,id,key,entry);saveAndClose(()=>TPDimensions.set(db.quote.products,id,key,entry,typeof Team!=='undefined'&&Team.user?Team.user.name+' ('+Team.user.id+')':undefined),'Đã lưu công thức và tính lại lượng, diện tích, giá');
  });$('#dialog').classList.add('wide-dialog');
  const fieldsUI=()=>{const key=$('[name=dimensionKey]').value,link=n.dimensionLinks?.[key]||{mode:n.paramLinks?.[key]?'formula':'manual',expression:n.paramLinks?.[key]?'PRODUCT_'+n.paramLinks[key]:''};$('#b2-dimension-fields').innerHTML=`${select('Cách xác định','dimensionMode',[['manual','Nhập tay'],['fixed','Giữ cố định tại dòng'],['formula','Theo công thức']],link.mode)}${field('Công thức','dimensionExpression',link.expression||'','text','maxlength="500"')}${field('Giá trị nhập tay / cố định','dimensionValue',link.value??TPDimensions.data(n)[key]??'','number','min="0" step="any"')}<p class="help-text">${n.dimensionHistory?.length?'Đã lưu '+n.dimensionHistory.length+' lần cấu hình. Lần cuối: '+esc(n.dimensionHistory.at(-1).actor):'Chưa có lịch sử cấu hình công thức.'}</p>`;preview();};
  const preview=()=>{const {key,entry}=b2ReadDimension(),formula=entry.mode==='formula';$('[name=dimensionExpression]').disabled=!formula;$('[name=dimensionValue]').disabled=formula;try{const trial=C.copy(db.quote.products);TPDimensions.set(trial,id,key,entry);const target=C.findNode(trial,id),value=TPDimensions.data(target)[key];$('#b2-dimension-result').textContent=key+' = '+value+' '+fields.find(f=>f.key===key).unit+(formula?' ← '+entry.expression:'');}catch(e){$('#b2-dimension-result').textContent=e.message;}};
  $('#dialog-form').addEventListener('click',e=>{const button=e.target.closest('[data-dimension-variable]');if(!button)return;const input=$('[name=dimensionExpression]'),wasFormula=$('[name=dimensionMode]').value==='formula';$('[name=dimensionMode]').value='formula';input.disabled=false;if(!wasFormula)input.value='';const start=input.selectionStart??input.value.length,end=input.selectionEnd??start;input.setRangeText(button.dataset.dimensionVariable,start,end,'end');input.focus();preview();});
  $('[name=dimensionKey]').onchange=fieldsUI;$('#dialog-form').addEventListener('input',preview);$('#dialog-form').addEventListener('change',e=>{if(e.target.name!=='dimensionKey')preview();});fieldsUI();
}
function b2ReadDimension(){const key=$('[name=dimensionKey]').value,mode=$('[name=dimensionMode]').value;return {key,entry:mode==='formula'?{mode,expression:$('[name=dimensionExpression]').value.trim()}:{mode,value:$('[name=dimensionValue]').value===''?null:Number($('[name=dimensionValue]').value)}};}
function b2ThicknessScope(id){
  inWritable();const product=C.findNode(db.quote.products,id);if(!product)return;
  const rows=C.scopedLeaves(product).filter(n=>TPDimensions.fields(n).some(f=>f.key==='T'&&f.fixed&&f.unit==='mm')),check=TPDimensions.resolve(C.copy(db.quote.products));
  openDialog('Đối chiếu Dày · '+esc(product.name),`<p>Chọn rõ dòng phải khớp Dày chung. Vật tư qua cấu kiện vẫn thuộc sản phẩm này; sản phẩm con dùng Dày riêng của nó. Bu lông và vật tư không có Dày cố định không nhận liên kết.</p><div class="notice">Liên kết ở đây là yêu cầu đối chiếu <code>T mã = PRODUCT_T</code>, không ghi đè quy cách danh mục. Khi lệch, phải chọn mã phù hợp hoặc khai độ dày riêng có lý do; không tự đổi mã, giá hay hãng. Dày chung: <strong>${product.params?.T==null?'chưa khai':num(product.params.T,3)+' mm'}</strong>.</div>${rows.length?rows.map(n=>{const item=check.thickness.find(x=>x.nodeId===n.id);return `<section class="panel panel-body" data-thickness-row="${esc(n.id)}"><strong>${esc(n.materialId)} · ${esc(n.name)}</strong><p>${esc((C.nodePath(db.quote.products,n.id)||[]).map(x=>x.name).join(' → '))}</p><p>Quy cách đang chọn: ${num(n.spec.props.T,3)} mm${n.spec.brand?' · '+esc(n.spec.brand):''}</p>${select('Phạm vi Dày','thickness-mode-'+n.id,[['','Chưa liên kết — giữ quy cách mã'],['product','Phải khớp Dày chung của sản phẩm'],['independent','Dùng độ dày riêng của mã']],n.thicknessRequirement?.mode||'')}${field('Căn cứ / lý do chọn phạm vi','thickness-reason-'+n.id,n.thicknessRequirement?.reason||'','text','maxlength="500"')}<p class="${item?.valid===false?'cell-error':'help-text'}" data-thickness-status="${esc(n.id)}">${esc(item?.error||(item?.valid?(item.mode==='product'?'Đã khớp Dày chung':'Đã khai dùng độ dày riêng'):'Chưa gán yêu cầu Dày chung; giá vẫn theo quy cách mã.'))}</p><button type="button" class="button small" data-action="swap-material" data-id="${esc(n.id)}">Chọn lại mã vật tư</button></section>`;}).join(''):'<p>Không có dòng vật tư cần đối chiếu Dày tại sản phẩm này.</p>'}`,'Lưu phạm vi Dày',f=>{
    inWritable();const trial=C.copy(db.quote),changes=[];for(const n of rows){const mode=f.get('thickness-mode-'+n.id),reason=String(f.get('thickness-reason-'+n.id)||'').trim();if(!mode){if(n.thicknessRequirement)throw Error('Để bỏ liên kết, chọn dùng độ dày riêng và ghi lý do');continue;}if(mode===n.thicknessRequirement?.mode&&reason===n.thicknessRequirement?.reason)continue;const entry={mode,reason};TPDimensions.setThicknessRequirement(trial,n.id,entry);changes.push([n.id,entry]);}
    saveAndClose(()=>{for(const [nodeId,entry]of changes)TPDimensions.setThicknessRequirement(db.quote,nodeId,entry,Team.user?Team.user.name+' ('+Team.user.id+')':undefined);},'Đã lưu phạm vi Dày. Dòng lệch quy cách bị chặn tính/phát hành cho đến khi xử lý.');
  });$('#dialog').classList.add('wide-dialog');
}
function b2Decorate(){if(page!=='quote')return;for(const title of document.querySelectorAll('.panel h2'))if(title.textContent==='Vật tư hoàn thiện tự tính')title.closest('.panel').remove();if(['bom','operations','waste','mass','prices'].includes(tab)&&!$('#b2-generated'))$('#content').insertAdjacentHTML('beforeend',b2Generated());
  for(const n of C.flatten(db.quote.products)){
    const escaped=CSS.escape(n.id),row=document.querySelector('[data-b1-node="'+escaped+'"]'),quick=document.querySelector('[data-qid="'+escaped+'"]')?.closest('tr'),head=document.querySelector('[data-param-product="'+escaped+'"]')?.closest('.quick-product');
    const anchor=row?.querySelector('.b1-identity > div')||row?.querySelector('th')||quick?.querySelector('.quick-identity > span:last-child')||head?.querySelector('.quick-product-title');
    if(anchor&&!anchor.querySelector('.b2-node-meta')){anchor.insertAdjacentHTML('beforeend',`<div class="b2-node-meta">${TPDimensions.fields(n).some(f=>!f.fixed)?`<button type="button" class="button small quiet" data-b2-dim="${esc(n.id)}">ƒ Kích thước</button>`:''}<small class="subtext">Lượng: ${(C.nodePath(db.quote.products,n.id)||[]).map(x=>num(x.qty)).join(' × ')} = ${num(result.nodes[n.id]?.count)} · theo cây</small></div>`);}
    for(const [key,link]of Object.entries(n.dimensionLinks||{})){
      const input=document.querySelector(`[data-qid="${escaped}"][data-qkey="${CSS.escape(key)}"], [data-param-product="${escaped}"][data-param-key="${CSS.escape(key)}"]`);if(selected===n.id){const detail=document.querySelector('[data-dimension="'+CSS.escape(key)+'"]');if(detail)detail.readOnly=link.mode!=='manual';}if(input){input.readOnly=link.mode!=='manual';input.value=TPDimensions.data(n)[key]??'';input.title=link.mode==='formula'?link.expression:link.mode==='fixed'?'Giữ cố định':'Nhập tay';if(!input.parentElement.querySelector('.b2-formula'))input.parentElement.insertAdjacentHTML('beforeend',`<small class="b2-formula">${esc(key)} = ${esc(TPDimensions.data(n)[key]??'Lỗi')} ${link.mode==='formula'?'← '+esc(link.expression):'· '+esc(link.mode==='fixed'?'Cố định':'Nhập tay')}</small>`);}
    }
  }
}
function b2Identity(){if(db.quote.status!=='draft')return;for(const n of C.flatten(db.quote.products))for(const op of n.ops||[])op.instanceId??=C.uid();for(const rate of db.quote.ratesSnapshot||[])for(const recipe of TPWork.recipes(rate))recipe.id??=C.uid();}
function b2Generated(){const rows=[...(result.generated||[]),...(result.includedGenerated||[])],purchases=new Map();for(const g of result.generated||[]){const key=JSON.stringify([g.materialId,g.unit,g.brand||'',g.price]);const total=purchases.get(key)||{...g,quantity:0,cost:0};total.quantity+=g.quantity;total.cost+=g.cost;purchases.set(key,total);}return `<section id="b2-generated" class="panel"><div class="panel-head"><div><h2>Nhu cầu vật tư hoàn thiện</h2><p>Cùng dữ liệu xuyên năm bước; không phải vật tư thêm lần nữa vào cấu thành. Giá đã gồm trong gói thuê chỉ hiển thị tham chiếu, không cộng vào tiền mua hoặc vận chuyển nhập.</p></div></div>${rows.length?`<div class="table-scroll"><table><thead><tr><th>Đối tượng / nguyên công</th><th>Mã vật tư / hãng</th><th>Lượng cần dùng</th><th>Giá đã chọn</th><th>Tiền tính thêm</th><th>Trạng thái</th></tr></thead><tbody>${rows.map(g=>`<tr data-b2-generated="${esc(g.id||g.ownerId)}"><td>${esc(C.findNode(db.quote.products,g.ownerId)?.name)}<small class="subtext">${esc(g.rateName)}</small></td><td>${esc(g.materialId)}<small class="subtext">${esc(g.name)}${g.brand?' · '+esc(g.brand):''}</small></td><td>${g.error?esc(g.error):num(g.quantity,4)+' '+esc(g.unit)}<small class="subtext">${num(g.norm,4)} / ${esc(g.basis)} × ${num(g.layers)} lớp × (1 + ${num(g.loss)}%)</small></td><td>${money(g.price)} / ${esc(g.unit)}</td><td>${money(g.cost)} đ</td><td>${g.included?esc(g.reason||'Đã gồm trong gói thuê'):'Cần mua · đã tính một lần vào vật tư hoàn thiện'}</td></tr>`).join('')}</tbody></table></div>`:'<p class="muted-row">Chưa khai định mức vật tư hoàn thiện. Khai tại bảng đơn giá nguyên công / bề mặt.</p>'}${purchases.size?`<div class="panel-head"><div><h3>Tổng vật tư hoàn thiện cần mua</h3><p>Gộp nhu cầu mua cùng mã/đơn vị/hãng/giá; không gộp số lượng để tra hệ số nguyên công.</p>${[...purchases.values()].map(g=>`<p data-b2-purchase="${esc(g.materialId)}"><strong>${esc(g.materialId)}</strong> · ${num(g.quantity,4)} ${esc(g.unit)} · ${money(g.cost)} đ</p>`).join('')}</div></div>`:''}</section>`;}
function installBatchTwoUI(){
  document.addEventListener('click',e=>{const el=e.target.closest('[data-thickness-scope]');if(!el)return;e.preventDefault();try{b2ThicknessScope(el.dataset.thicknessScope);}catch(error){toast(error.message);}});
  const oldRender=render;render=()=>{b2Identity();if(C.flatten(db.quote.products).some(n=>Object.keys(n.dimensionLinks||{}).length))TPDimensions.resolve(db.quote.products);oldRender();b2Decorate();};
  const oldRefresh=refreshQuickUI;refreshQuickUI=()=>{if(C.flatten(db.quote.products).some(n=>Object.keys(n.dimensionLinks||{}).length)){render();return;}oldRefresh();b2Decorate();};
  const oldActions=nodeActions;nodeActions=id=>{oldActions(id);const menu=$('.row-action-menu');if(menu)menu.insertAdjacentHTML('afterbegin',`<button type="button" data-b2-dim="${esc(id)}">ƒ Công thức kích thước</button>`);};
  const oldDetail=renderNode;renderNode=(...args)=>{const html=oldDetail(...args),n=args[0];return html+(n&&TPDimensions.fields(n).some(f=>!f.fixed)?`<button type="button" class="button" data-b2-dim="${esc(n.id)}">ƒ Công thức kích thước</button>`:'');};
  document.addEventListener('click',e=>{const el=e.target.closest('[data-b2-dim]');if(!el)return;e.preventDefault();try{if(typeof inWritable==='function')inWritable();}catch(error){toast(error.message);return;}closeDialog();b2Dimensions(el.dataset.b2Dim);});
}
