/* Contract 27.01: internal direct/group chat and captured/cropped images. */
'use strict';
const TPChat={rooms:[],users:[],active:null,items:[],drafts:new Map(),epoch:0,busy:false,open:false,more:false,sending:false};
async function chatApi(route,method='GET',data){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);try{const response=await fetch('/api/'+route,{method,credentials:'same-origin',signal:controller.signal,headers:{...(data!==undefined?{'Content-Type':'application/json'}:{}),...(method!=='GET'?{'X-CSRF-Token':Team.csrf}:{})},body:data===undefined?undefined:JSON.stringify(data)});const raw=await response.json(),value=window.TPFormulaAccess?TPFormulaAccess.unwrap(raw):raw;if(!response.ok){const error=Error(value.error||'Không kết nối được máy chủ');error.status=response.status;throw error;}return value;}catch(e){if(e.name==='AbortError')throw Error('Kết nối quá thời gian chờ');throw e;}finally{clearTimeout(timeout);}}
const chatEscape=s=>esc(String(s??''));
function chatName(r){return r.kind==='group'?r.title:r.members.filter(m=>m.id!==Team.user?.id).map(m=>m.name).join(', ');}
function chatTime(s){return new Date(s).toLocaleString('vi-VN',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'});}
function chatDraft(){if(!TPChat.drafts.has(TPChat.active))TPChat.drafts.set(TPChat.active,{text:'',image:null,pending:null});return TPChat.drafts.get(TPChat.active);}
function chatStatus(text,error=false){const e=document.querySelector('#chat-status');if(e){e.textContent=text;e.classList.toggle('chat-error',error);}}
function chatList(){const query=(document.querySelector('#chat-search')?.value||'').toLocaleLowerCase('vi'),el=document.querySelector('#chat-room-list');if(!el)return;el.innerHTML=TPChat.rooms.filter(r=>chatName(r).toLocaleLowerCase('vi').includes(query)).map(r=>`<button type="button" class="chat-room ${r.id===TPChat.active?'selected':''}" data-chat-room="${r.id}" aria-pressed="${r.id===TPChat.active}"><span class="chat-avatar">${r.kind==='group'?'N':chatEscape(chatName(r).trim().slice(0,1))}</span><span class="chat-room-copy"><strong>${chatEscape(chatName(r))}</strong><small>${r.last?chatEscape((r.last.sender===Team.user.id?'Bạn: ':'')+(r.last.body||(r.last.hasImage?'Hình ảnh':''))):'Bắt đầu cuộc trò chuyện'}</small></span>${r.unread?`<span class="chat-unread" aria-label="${r.unread} tin chưa đọc">${r.unread}</span>`:''}</button>`).join('')||'<p class="chat-empty-list">Chưa có hội thoại phù hợp. Chọn “Nhắn riêng” hoặc “Tạo nhóm” để bắt đầu.</p>';}
function chatMessage(m){return `<article class="chat-message ${m.sender===Team.user.id?'mine':''}" data-chat-seq="${m.seq}"><div class="chat-message-meta">${chatEscape(m.name)} <time>${chatTime(m.at)}</time></div><div class="chat-bubble">${m.body?`<p>${chatEscape(m.body)}</p>`:''}${m.hasImage?`<button type="button" class="chat-image-button" data-chat-image="${m.seq}" aria-label="Xem ảnh từ ${chatEscape(m.name)}"><img src="/api/chat/images/${m.seq}" alt="Ảnh trong hội thoại" loading="lazy"></button>`:''}</div></article>`;}
function chatPaintMessages(reset=false){const el=document.querySelector('#chat-messages');if(!el)return;const bottom=el.scrollHeight-el.scrollTop-el.clientHeight<90,oldHeight=el.scrollHeight,oldTop=el.scrollTop;el.innerHTML=`${TPChat.more?'<button type="button" class="button small chat-older" data-chat-action="older">Xem tin cũ hơn</button>':''}${TPChat.items.map(chatMessage).join('')||'<div class="chat-empty"><h3>Bắt đầu cuộc trò chuyện</h3><p>Gửi lời nhắn đầu tiên hoặc chia sẻ ảnh với đồng nghiệp.</p></div>'}`;if(reset||bottom)el.scrollTop=el.scrollHeight;else el.scrollTop=oldTop+(TPChat.prepending?el.scrollHeight-oldHeight:0);TPChat.prepending=false;el.querySelectorAll('img').forEach(i=>i.addEventListener('load',()=>{if(reset||bottom)el.scrollTop=el.scrollHeight;},{once:true}));}
function chatThread(){const pane=document.querySelector('#chat-main'),r=TPChat.rooms.find(r=>r.id===TPChat.active);if(!pane)return;if(!r){pane.innerHTML='<div class="chat-empty"><span class="chat-empty-mark">Trao đổi nội bộ</span><h2>Cùng làm việc, cùng trao đổi</h2><p>Chọn đồng nghiệp hoặc tạo nhóm để trao đổi công việc.<br>Tin nhắn và ảnh được lưu trên máy chủ.</p></div>';return;}const d=chatDraft();pane.innerHTML=`<header class="chat-thread-head"><div><h3>${chatEscape(chatName(r))}</h3><p>${r.kind==='group'?r.members.length+' thành viên':'Hội thoại riêng'}</p></div><button type="button" class="button small" data-chat-action="members">Thành viên</button></header><div id="chat-messages" role="log" aria-label="Tin nhắn" aria-live="polite"></div><form id="chat-compose"><div class="chat-compose-tools"><button type="button" class="chat-tool" data-chat-action="stickers" aria-expanded="false" aria-controls="chat-stickers" title="Chọn sticker">${CHAT_ICONS.sticker}<span>Sticker</span></button><button type="button" class="chat-tool" data-chat-action="attach" title="Chọn ảnh từ máy tính">${CHAT_ICONS.image}<span>Thêm ảnh</span></button><button type="button" class="chat-tool" data-chat-action="capture" title="Chọn màn hình hoặc cửa sổ, rồi cắt vùng cần gửi">${CHAT_ICONS['scan-line']}<span>Chụp / cắt màn hình</span></button><span>Hoặc dán ảnh bằng Ctrl+V</span><input id="chat-file" type="file" accept="image/png,image/jpeg,image/webp" hidden></div><section id="chat-stickers" aria-label="Chọn sticker" hidden></section><div id="chat-attachment"></div><label class="chat-compose-label" for="chat-text">Tin nhắn</label><div class="chat-compose-row"><textarea id="chat-text" placeholder="Nhập tin nhắn…" maxlength="5000" rows="2" ${d.pending?'readonly':''}>${chatEscape(d.text)}</textarea><button class="button primary" type="submit" id="chat-send">${d.pending?'Thử gửi lại':'Gửi'}</button></div><div class="chat-compose-hint">Enter để gửi · Shift+Enter xuống dòng · Ảnh tối đa 3 MB</div></form>`;chatAttachment();chatPaintMessages(true);document.querySelector('#chat-text').focus();}
function chatAttachment(){const e=document.querySelector('#chat-attachment'),d=chatDraft();if(e)e.innerHTML=d.image?`<img src="${d.image}" alt="Ảnh chuẩn bị gửi"><span>${chatEscape(d.imageLabel||'Ảnh đã sẵn sàng')}</span><button type="button" class="button small" data-chat-action="recrop" ${d.pending?'disabled':''}>Cắt lại</button><button type="button" class="button small" data-chat-action="remove-image" ${d.pending?'disabled':''}>Bỏ ảnh</button>`:'';}
async function chatMarkRead(){if(!TPChat.open||document.hidden||!document.hasFocus()||!TPChat.items.length)return;const log=document.querySelector('#chat-messages');if(!log||log.scrollHeight-log.scrollTop-log.clientHeight>90)return;const id=TPChat.active,seq=TPChat.items.at(-1).seq;if(TPChat.readKey===id+':'+seq)return;await chatApi('chat/rooms/'+id+'/read','POST',{seq});TPChat.readKey=id+':'+seq;}
async function chatSelect(id){TPChat.active=id;TPChat.items=[];TPChat.more=false;TPChat.readKey='';const epoch=++TPChat.epoch;chatList();chatThread();chatStatus('Đang tải tin nhắn…');try{const data=await chatApi('chat/rooms/'+id+'/messages');if(epoch!==TPChat.epoch)return;TPChat.items=data.items;TPChat.more=data.more;chatPaintMessages(true);chatStatus('Đã kết nối');await chatMarkRead();}catch(e){if(epoch===TPChat.epoch)chatStatus(e.message,true);}}
async function chatPoll(){if(!Team.user||!Team.available||TPChat.busy||document.hidden)return;TPChat.busy=true;const generation=Team.sessionGeneration,epoch=TPChat.epoch;try{const rooms=await chatApi('chat/rooms');if(generation!==Team.sessionGeneration)return;TPChat.rooms=rooms;const total=rooms.reduce((n,r)=>n+r.unread,0);document.querySelectorAll('[data-chat-count]').forEach(e=>{e.textContent=total?String(total):'';e.hidden=!total;});if(!TPChat.open)return;chatList();if(TPChat.active&&!rooms.some(r=>r.id===TPChat.active)){TPChat.drafts.delete(TPChat.active);TPChat.active=null;TPChat.items=[];TPChat.epoch++;chatThread();chatStatus('Bạn không còn trong hội thoại này.',true);return;}if(TPChat.active&&document.querySelector('#chat-messages')){const current=rooms.find(r=>r.id===TPChat.active),head=document.querySelector('#chat-main>.chat-thread-head');if(head&&current){head.querySelector('h3').textContent=chatName(current);head.querySelector('p').textContent=current.kind==='group'?current.members.length+' thành viên':'Hội thoại riêng';}const id=TPChat.active,data=await chatApi('chat/rooms/'+id+'/messages'+(TPChat.items.length?'?after='+TPChat.items.at(-1).seq:''));if(epoch!==TPChat.epoch||generation!==Team.sessionGeneration)return;if(data.items.length){const keys=new Set(TPChat.items.map(m=>m.seq));TPChat.items.push(...data.items.filter(m=>!keys.has(m.seq)));chatPaintMessages();}await chatMarkRead();}chatStatus(TPChat.active&&chatDraft().pending?'Tin chưa xác nhận gửi — bấm Thử gửi lại.':'Đã kết nối',!!(TPChat.active&&chatDraft().pending));}catch(e){if(generation!==Team.sessionGeneration)return;if(e.status===401){teamSession({user:null,permissions:null,csrf:''});toast('Phiên đăng nhập đã hết. Đăng nhập lại để dùng chat.');return;}if(e.status===404&&TPChat.active){TPChat.active=null;TPChat.items=[];TPChat.epoch++;chatThread();}chatStatus('Mất kết nối — đang thử lại. Nội dung chưa gửi vẫn được giữ.',true);}finally{TPChat.busy=false;}}
function chatReset(){TPChat.epoch++;TPChat.rooms=[];TPChat.users=[];TPChat.active=null;TPChat.items=[];TPChat.drafts.clear();TPChat.open=false;TPChat.sending=false;document.querySelector('#team-chat')?.close();document.querySelector('#team-chat')?.remove();document.querySelectorAll('.chat-viewer').forEach(e=>e.remove());document.querySelectorAll('[data-chat-count]').forEach(e=>e.hidden=true);}
async function chatOpen(){if(!Team.user)return teamLogin();let d=document.querySelector('#team-chat');if(!d){d=document.createElement('dialog');d.id='team-chat';d.setAttribute('aria-labelledby','chat-title');d.innerHTML=`<header class="chat-top"><div><h2 id="chat-title">Chat nội bộ</h2><span id="chat-status" role="status">Đang kết nối…</span></div><button type="button" class="button" data-chat-action="close" aria-label="Đóng chat">Đóng</button></header><div class="chat-layout"><aside class="chat-sidebar"><div class="chat-new"><button class="button primary" type="button" data-chat-action="direct">Nhắn riêng</button><button class="button" type="button" data-chat-action="group">Tạo nhóm</button></div><label class="chat-search-label" for="chat-search">Tìm hội thoại</label><input id="chat-search" placeholder="Tên đồng nghiệp hoặc nhóm…"><nav id="chat-room-list" aria-label="Hội thoại"></nav></aside><section id="chat-main"></section></div>`;document.body.append(d);d.addEventListener('close',()=>{TPChat.open=false;TPChat.epoch++;});}TPChat.open=true;d.showModal();chatList();chatThread();await chatPoll();if(TPChat.active)await chatSelect(TPChat.active);}
async function chatPeople(mode){const epoch=++TPChat.epoch,id=TPChat.active;chatStatus('Đang tải danh sách…');try{const users=await chatApi('chat/users');if(epoch!==TPChat.epoch||!TPChat.open)return;TPChat.users=users;const room=TPChat.rooms.find(r=>r.id===id),editing=mode==='members',canEdit=!editing||room.kind==='group'&&room.owner===Team.user.id;const choices=editing?users.filter(u=>u.id!==Team.user.id||canEdit):users.filter(u=>u.id!==Team.user.id);document.querySelector('#chat-main').innerHTML=`<section class="chat-people"><div class="chat-thread-head"><h3>${editing?'Thành viên hội thoại':mode==='direct'?'Nhắn riêng với đồng nghiệp':'Tạo nhóm trao đổi'}</h3><button class="button small" data-chat-action="back" type="button">Quay lại</button></div><form id="chat-people-form" data-mode="${mode}">${mode!=='direct'&&(!editing||room.kind==='group')?`<label>Tên nhóm<input name="title" maxlength="80" required value="${chatEscape(editing?room.title:'')}" ${!canEdit?'readonly':''}></label>`:''}<p>${editing?'Thành viên mới có thể xem lịch sử trò chuyện của nhóm.':'Chọn '+(mode==='direct'?'một đồng nghiệp':'ít nhất hai đồng nghiệp')+'.'}</p><input id="chat-person-search" aria-label="Tìm đồng nghiệp" placeholder="Tìm tên đồng nghiệp…"><div class="chat-person-list">${(canEdit?choices:room.members).map(u=>`<label data-person-name="${chatEscape(u.name.toLocaleLowerCase('vi'))}"><input type="${mode==='direct'?'radio':'checkbox'}" name="person" value="${u.id}" ${editing&&room.members.some(m=>m.id===u.id)?'checked':''} ${!canEdit||u.id===Team.user.id?'disabled':''}><span>${chatEscape(u.name)}${u.id===Team.user.id?' (Bạn)':''}</span></label>`).join('')}</div>${canEdit?`<button type="submit" class="button primary">${editing?'Lưu thành viên':mode==='direct'?'Bắt đầu nhắn tin':'Tạo nhóm'}</button>`:''}<p id="chat-people-error" role="alert"></p></form></section>`;chatStatus('Đã kết nối');}catch(e){chatStatus(e.message,true);}}
async function chatSend(){if(TPChat.sending||!TPChat.active)return;const id=TPChat.active,d=chatDraft(),generation=Team.sessionGeneration;if(!d.pending){const text=document.querySelector('#chat-text').value;d.text=text;if(!text.trim()&&!d.image)return;d.pending={clientId:crypto.randomUUID(),body:text,image:d.image};}TPChat.sending=true;const button=document.querySelector('#chat-send'),input=document.querySelector('#chat-text');button.disabled=true;input.readOnly=true;chatStatus('Đang gửi…');try{const item=await chatApi('chat/rooms/'+id+'/messages','POST',d.pending);if(generation!==Team.sessionGeneration)return;d.pending=null;d.text='';d.image=null;d.imageLabel='';if(id===TPChat.active){if(!TPChat.items.some(m=>m.seq===item.seq))TPChat.items.push(item);TPChat.items.sort((a,b)=>a.seq-b.seq);input.value='';input.readOnly=false;chatAttachment();chatPaintMessages(true);}chatStatus('Đã gửi');await chatPoll();}catch(e){if(generation===Team.sessionGeneration){chatStatus('Chưa xác nhận gửi: '+e.message+'. Bấm Thử gửi lại.',true);if(e.status&&e.status<500){d.pending=null;input.readOnly=false;}}}finally{TPChat.sending=false;if(button.isConnected){button.disabled=false;button.textContent=d.pending?'Thử gửi lại':'Gửi';}}}
async function chatCrop(source){if(!TPChat.open)return;if(!TPChat.active||chatDraft().pending)throw Error('Hoàn tất gửi tin đang chờ trước khi thêm ảnh');const id=TPChat.active,epoch=++TPChat.epoch,img=new Image();img.src=source;await img.decode();if(epoch!==TPChat.epoch)return;const scale=Math.min(1,1400/img.naturalWidth,1000/img.naturalHeight),w=Math.round(img.naturalWidth*scale),h=Math.round(img.naturalHeight*scale);const main=document.querySelector('#chat-main');main.innerHTML=`<section class="chat-crop"><h3>Cắt ảnh trước khi gửi</h3><p>Kéo chuột trên ảnh để chọn vùng cần gửi. Chỉ vùng đã chọn được đính kèm.</p><div class="chat-crop-stage"><canvas id="chat-crop-canvas" width="${w}" height="${h}" aria-label="Kéo chọn vùng ảnh"></canvas></div><div class="chat-crop-fields">${['x','y','w','h'].map((k,i)=>`<label>${['Trái','Trên','Rộng','Cao'][i]}<input type="number" data-crop-field="${k}" min="${i<2?0:1}" value="${i<2?0:i===2?w:h}"></label>`).join('')}</div><div class="actions"><button class="button" type="button" id="chat-crop-cancel">Hủy</button><button class="button" type="button" id="chat-crop-reset">Toàn ảnh</button><button class="button" type="button" id="chat-crop-use">Dùng ảnh này</button><button class="button primary" type="button" id="chat-crop-send">Cắt và gửi</button></div><p id="chat-crop-error" role="alert"></p></section>`;
 const canvas=document.querySelector('#chat-crop-canvas'),ctx=canvas.getContext('2d');let rect={x:0,y:0,w,h},start=null;const paint=()=>{ctx.clearRect(0,0,w,h);ctx.drawImage(img,0,0,w,h);ctx.fillStyle='rgba(15,23,42,.48)';ctx.fillRect(0,0,w,h);ctx.drawImage(img,rect.x/scale,rect.y/scale,rect.w/scale,rect.h/scale,rect.x,rect.y,rect.w,rect.h);ctx.strokeStyle='#1681ef';ctx.lineWidth=3;ctx.strokeRect(rect.x,rect.y,rect.w,rect.h);for(const e of main.querySelectorAll('[data-crop-field]'))e.value=Math.round(rect[e.dataset.cropField]);};const point=e=>{const b=canvas.getBoundingClientRect();return {x:Math.max(0,Math.min(w,(e.clientX-b.left)*w/b.width)),y:Math.max(0,Math.min(h,(e.clientY-b.top)*h/b.height))};};canvas.onpointerdown=e=>{start=point(e);canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!start)return;const p=point(e);rect={x:Math.min(start.x,p.x),y:Math.min(start.y,p.y),w:Math.max(1,Math.abs(p.x-start.x)),h:Math.max(1,Math.abs(p.y-start.y))};paint();};canvas.onpointerup=canvas.onpointercancel=()=>{start=null;};main.querySelectorAll('[data-crop-field]').forEach(e=>e.onchange=()=>{rect[e.dataset.cropField]=Number(e.value)||0;rect.x=Math.max(0,Math.min(w-1,rect.x));rect.y=Math.max(0,Math.min(h-1,rect.y));rect.w=Math.max(1,Math.min(w-rect.x,rect.w));rect.h=Math.max(1,Math.min(h-rect.y,rect.h));paint();});document.querySelector('#chat-crop-reset').onclick=()=>{rect={x:0,y:0,w,h};paint();};document.querySelector('#chat-crop-cancel').onclick=()=>{TPChat.epoch++;chatThread();};const finish=async send=>{if(epoch!==TPChat.epoch||id!==TPChat.active||!TPChat.open||TPChat.sending||chatDraft().pending)return;const out=document.createElement('canvas');out.width=Math.round(rect.w);out.height=Math.round(rect.h);out.getContext('2d').drawImage(img,rect.x/scale,rect.y/scale,rect.w/scale,rect.h/scale,0,0,out.width,out.height);const data=out.toDataURL('image/png');if(data.length>4100000){document.querySelector('#chat-crop-error').textContent='Ảnh quá 3 MB. Chọn vùng nhỏ hơn.';return;}if(id!==TPChat.active)return;chatDraft().image=data;chatDraft().imageLabel='Ảnh đã cắt';TPChat.epoch++;chatThread();if(send)await chatSend();};document.querySelector('#chat-crop-use').onclick=()=>finish(false);document.querySelector('#chat-crop-send').onclick=()=>finish(true);paint();}
async function chatFile(file){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>15*1024*1024)throw Error('Chọn ảnh PNG, JPEG hoặc WebP tối đa 15 MB để cắt');const url=URL.createObjectURL(file);try{await chatCrop(url);}finally{URL.revokeObjectURL(url);}}
async function chatCapture(){if(TPChat.capturing)return;const id=TPChat.active,epoch=TPChat.epoch;if(chatDraft().pending)throw Error('Gửi lại tin đang chờ trước khi chụp ảnh');if(!navigator.mediaDevices?.getDisplayMedia)throw Error('Trình duyệt chưa hỗ trợ chụp màn hình. Dùng Win+Shift+S rồi Ctrl+V vào ô chat.');TPChat.capturing=true;let stream;try{stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});if(epoch!==TPChat.epoch||id!==TPChat.active||!TPChat.open)return;const video=document.createElement('video');video.srcObject=stream;video.muted=true;await video.play();await new Promise(r=>setTimeout(r,150));const canvas=document.createElement('canvas');canvas.width=video.videoWidth;canvas.height=video.videoHeight;canvas.getContext('2d').drawImage(video,0,0);stream.getTracks().forEach(t=>t.stop());if(epoch===TPChat.epoch&&id===TPChat.active&&TPChat.open)await chatCrop(canvas.toDataURL('image/png'));}finally{stream?.getTracks().forEach(t=>t.stop());TPChat.capturing=false;}}

function chatStickerPicker(show){
 const pane=document.querySelector('#chat-stickers');if(!pane)return;
 const visible=show===undefined?pane.hidden:show;
 pane.hidden=!visible;
 document.querySelector('[data-chat-action="stickers"]')?.setAttribute('aria-expanded',String(visible));
 if(!visible){document.querySelector('[data-chat-action="stickers"]')?.focus();return;}
 pane.innerHTML=`<header><div><strong>Sticker</strong><small>Chọn để xem trước, bấm Gửi khi sẵn sàng.</small></div><button type="button" class="chat-tool" data-chat-action="close-stickers" aria-label="Đóng bộ sticker">${CHAT_ICONS.x}</button></header><div class="chat-sticker-grid">${CHAT_STICKERS.map(a=>`<button type="button" data-chat-sticker="${a.id}" title="${chatEscape(a.label)}">${a.svg}<span>${chatEscape(a.label)}</span></button>`).join('')}</div><footer>Hình: <a href="https://github.com/jdecked/twemoji" target="_blank" rel="noopener noreferrer">Twemoji — Twitter và cộng tác viên</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">CC BY 4.0</a></footer>`;
 pane.querySelector('[data-chat-sticker]')?.focus();
}
async function chatChooseSticker(id){
 const art=CHAT_STICKERS.find(a=>a.id===id);if(!art||!TPChat.active||TPChat.sending||chatDraft().pending)return;
 const room=TPChat.active,epoch=TPChat.epoch,generation=Team.sessionGeneration;
 const img=new Image();img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(art.svg);await img.decode();
 if(room!==TPChat.active||epoch!==TPChat.epoch||generation!==Team.sessionGeneration||!TPChat.open||TPChat.sending||chatDraft().pending)return;
 const canvas=document.createElement('canvas');canvas.width=canvas.height=160;canvas.getContext('2d').drawImage(img,8,8,144,144);
 chatDraft().image=canvas.toDataURL('image/png');chatDraft().imageLabel='Sticker · '+art.label;
 chatStickerPicker(false);chatAttachment();document.querySelector('#chat-text')?.focus();
}

function installChatUI(){
 window.addEventListener('beforeunload',e=>{if([...TPChat.drafts.values()].some(d=>d.text.trim()||d.image||d.pending)){e.preventDefault();e.returnValue='';}});
 document.addEventListener('keydown',e=>{if(e.target.closest('#team-chat,.chat-viewer')&&(e.ctrlKey||e.metaKey)&&['z','y','s'].includes(e.key.toLowerCase())){e.stopImmediatePropagation();if(e.key.toLowerCase()==='s')e.preventDefault();}},true);
 const nav=document.querySelector('#sidebar nav');nav.insertAdjacentHTML('beforeend','<button type="button" data-chat-launch><span class="nav-symbol">▤</span> Chat nội bộ <span class="nav-count" data-chat-count hidden></span></button>');
 const oldSession=teamSession;teamSession=v=>{chatReset();return oldSession(v);};
 document.addEventListener('click',async e=>{const launch=e.target.closest('[data-chat-launch]');if(launch){await chatOpen();return;}const el=e.target.closest('#team-chat button');if(!el)return;try{if(el.dataset.chatRoom){await chatSelect(el.dataset.chatRoom);return;}if(el.dataset.chatImage){const image=document.createElement('dialog');image.className='chat-viewer';image.innerHTML=`<button type="button" class="button">Đóng ảnh</button><img src="/api/chat/images/${el.dataset.chatImage}" alt="Ảnh phóng lớn">`;document.body.append(image);image.querySelector('button').onclick=()=>image.close();image.onclose=()=>image.remove();image.showModal();return;}if((TPChat.sending||TPChat.active&&chatDraft().pending)&&(['stickers','attach','capture','recrop','remove-image'].includes(el.dataset.chatAction)||el.dataset.chatSticker)){chatStatus('Hoàn tất gửi tin đang chờ trước khi thay ảnh.',true);return;}if(el.dataset.chatSticker){await chatChooseSticker(el.dataset.chatSticker);return;}switch(el.dataset.chatAction){case 'stickers':chatStickerPicker();break;case 'close-stickers':chatStickerPicker(false);break;case 'recrop':if(chatDraft().image)await chatCrop(chatDraft().image);break;case 'close':document.querySelector('#team-chat').close();break;case 'direct':case 'group':case 'members':await chatPeople(el.dataset.chatAction);break;case 'back':TPChat.epoch++;chatThread();break;case 'attach':if(chatDraft().pending)throw Error('Gửi lại tin đang chờ trước khi thêm ảnh');document.querySelector('#chat-file').click();break;case 'capture':await chatCapture();break;case 'remove-image':if(!chatDraft().pending&&!TPChat.sending){chatDraft().image=null;chatDraft().imageLabel='';chatAttachment();}break;case 'older':{const id=TPChat.active,epoch=TPChat.epoch;el.disabled=true;const data=await chatApi('chat/rooms/'+id+'/messages?before='+TPChat.items[0].seq);if(epoch!==TPChat.epoch)return;TPChat.items=[...data.items,...TPChat.items];TPChat.more=data.more;TPChat.prepending=true;chatPaintMessages();break;}}}catch(error){el.disabled=false;chatStatus(error.name==='NotAllowedError'?'Đã hủy chụp màn hình. Có thể dán ảnh bằng Ctrl+V.':error.message,true);}});
 document.addEventListener('input',e=>{if(e.target.id==='chat-search')chatList();if(e.target.id==='chat-text')chatDraft().text=e.target.value;if(e.target.id==='chat-person-search'){const q=e.target.value.toLocaleLowerCase('vi');document.querySelectorAll('[data-person-name]').forEach(l=>l.hidden=!l.dataset.personName.includes(q));}});
 document.addEventListener('change',e=>{if(e.target.id==='chat-file'){chatFile(e.target.files[0]).catch(err=>chatStatus(err.message,true));e.target.value='';}});
 document.addEventListener('paste',e=>{if(!e.target.closest('#chat-compose'))return;const image=[...e.clipboardData.items].find(i=>i.type.startsWith('image/'));if(image){e.preventDefault();chatFile(image.getAsFile()).catch(err=>chatStatus(err.message,true));}});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.querySelector('#chat-stickers:not([hidden])')){e.preventDefault();e.stopPropagation();chatStickerPicker(false);return;}if(e.target.id==='chat-text'&&e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();chatSend();}});
 document.addEventListener('submit',async e=>{if(e.target.id==='chat-compose'){e.preventDefault();await chatSend();}if(e.target.id==='chat-people-form'){e.preventDefault();const form=e.target,button=form.querySelector('[type=submit]'),mode=form.dataset.mode,generation=Team.sessionGeneration,epoch=TPChat.epoch;button.disabled=true;try{const members=[...form.querySelectorAll('[name=person]:checked')].map(e=>e.value),title=form.elements.title?.value||'';const room=await chatApi(mode==='members'?'chat/rooms/'+TPChat.active+'/members':'chat/rooms',mode==='members'?'PUT':'POST',{kind:mode,title,members});if(generation!==Team.sessionGeneration||epoch!==TPChat.epoch)return;const rooms=await chatApi('chat/rooms');if(generation!==Team.sessionGeneration||epoch!==TPChat.epoch)return;TPChat.rooms=rooms;await chatSelect(room.id);}catch(err){form.querySelector('[role=alert]').textContent=err.message;}finally{button.disabled=false;}}});
 document.addEventListener('scroll',e=>{if(e.target.id==='chat-messages')chatMarkRead().catch(()=>{});},true);
 let ticks=0;setInterval(()=>{if(TPChat.open||++ticks%3===0)chatPoll();},2000);
}
