'use strict';
const cvButton=(label,action,kind='',name='')=>`<button type="button" class="button small" data-convention="${action}" data-kind="${kind}" data-name="${esc(name)}">${label}</button>`;
function cvList(kind='parameters'){const rows=TPConventions.entries(db,kind);openDialog('Danh mục quy ước · '+TPConventions.KINDS[kind],`<div class="actions cv-actions">${Object.entries(TPConventions.KINDS).map(([k,label])=>cvButton(label,'list',k)).join('')}${cvButton('+ Thêm giá trị','edit',kind)}${kind==='complexity'?cvButton('Dùng bảng cho công đoạn','apply-complexity'):''}</div><p>Giá trị có nơi dùng không được xóa. Quy cách/giá của báo giá đã duyệt giữ nguyên. Vật liệu/mác mới tự có dòng giá tham chiếu; chọn Áp dụng giá mới khi muốn tính lại.</p><div class="table-scroll"><table><thead><tr><th>Tên / ký hiệu</th><th>Thông số</th><th>Nơi dùng</th><th></th></tr></thead><tbody>${rows.map(x=>{const uses=TPConventions.references(db,kind,x);return `<tr><td>${esc(x.name)}</td><td>${esc(x.parent||x.unit||'')}${x.density?' · '+num(x.density)+' kg/m³':''}${x.price!==undefined?' · '+money(x.price)+' đ/kg':''}${x.percent!==undefined?' · '+num(x.percent)+'%':''}</td><td>${uses.length}<small>${uses.slice(0,2).map(esc).join('; ')}</small></td><td>${cvButton('Sửa','edit',kind,x.name)}${cvButton('Xóa','remove',kind,x.name)}</td></tr>`;}).join('')}</tbody></table></div><p class="help-text">Kiểu dáng và công thức tiết diện được xem tại Quy ước & công thức. Hoàn thiện bề mặt/công việc dùng chung danh mục công đoạn, có giá xưởng và giá thuê riêng.</p>`);$('#dialog').classList.add('wide-dialog');}
function cvEdit(kind,name){const item=TPConventions.entries(db,kind).find(x=>x.name===name)||{name:'',density:7850,unit:'mm',price:0,percent:0,reserve:0};openDialog((name?'Sửa ':'Thêm ')+TPConventions.KINDS[kind],`${field(kind==='parameters'?'Ký hiệu dùng trong công thức':'Tên giá trị','name',item.name,'text','required')}${kind==='materialGroups'?'<label><input type="checkbox" name="stock" '+(item.stock?'checked':'')+'> Nhóm phôi gia công — dùng hình dạng và quy ước kích thước</label>':''}${kind==='parameters'?field('Tên / diễn giải thông số','label',item.label||'','text','required maxlength="120"')+field('Đơn vị','unit',item.unit||'mm','text','required'):''}${kind==='substances'?field('Khối lượng riêng (kg/m³)','density',item.density,'number','min="0.001" step="any" required'):''}${kind==='grades'?select('Vật liệu gốc','parent',TPConventions.entries(db,'substances').map(x=>x.name),item.parent):''}${['substances','grades'].includes(kind)?field('Giá tham chiếu (đ/kg)','price',item.price||0,'number','min="0" step="any" required'):''}${['customers','complexity'].includes(kind)?field('Hệ số (%) — số cấu hình, không nhân số phân loại','percent',item.percent||0,'number','min="-99.99" step="any" required'):''}${kind==='customers'?field('Dự phòng giảm giá (%)','reserve',item.reserve||0,'number','min="-99.99" step="any" required'):''}${kind==='units'?'<p>Đơn vị bổ sung dùng cho vật tư theo số lượng. Công đoạn có đơn vị riêng phải khai lượng tính phí; không quy đổi ngầm sang kg/m².</p>':''}`, 'Lưu giá trị', f=>{const x={name:String(f.get('name')).trim()};if(kind==='materialGroups')x.stock=f.has('stock');for(const k of ['density','price','percent','reserve'])if(f.has(k))x[k]=Number(f.get(k));for(const k of ['unit','parent','label'])if(f.has(k))x[k]=String(f.get(k));const trial=C.copy(db);TPConventions.save(trial,kind,x,name);dfCatalogWrite(()=>TPConventions.save(db,kind,x,name));closeDialog();cvList(kind);});}
function cvGroups(){const rows=TPConventions.entries(db,'customers');openDialog('Nhóm khách hàng & dự phòng',`${select('Nhóm khách hàng','customerGroup',[['','Không chọn nhóm'],...rows.map(x=>[x.name,x.name+' · hệ số '+num(x.percent)+'% / dự phòng '+num(x.reserve||0)+'%'])],db.quote.customerGroup||'')}<p>Chọn nhóm sẽ điền hệ số khách hàng và dự phòng tương ứng trong báo giá này. Không thay các báo giá cũ khi sửa danh mục nhóm. Mã nhóm 2/3/4 không được tự hiểu là nhân giá 2/3/4 lần.</p>${cvButton('Khai nhóm khách hàng','list','customers')}`, 'Áp dụng nhóm', f=>{const group=rows.find(x=>x.name===f.get('customerGroup'));saveAndClose(()=>{db.quote.customerGroup=group?.name||'';db.quote.pricing.customer=group?.percent||0;db.quote.pricing.reserve=group?.reserve||0;});});}
function cvSheets(){return [{name:'Kieu dang',rows:[['Mã','Hình dạng','Tiết diện cố định (mm)','Kích thước phôi bổ sung (mm)'],...Object.entries(C.shapes).map(([id,s])=>[id,s.name,s.fixed.join(', '),s.input.join(', ')])],widths:[20,38,40,40]},...Object.entries(TPConventions.KINDS).map(([kind,label])=>({name:({materialGroups:'Nhom vat tu',productGroups:'Nhom san pham',parameters:'Thong so',substances:'Vat lieu',grades:'Mac',characteristics:'Dac tinh',units:'Don vi',customers:'Nhom khach',complexity:'Phuc tap'})[kind],widths:[30,45,20],rows:[['Danh mục',label],['Tên','Thông số','Nơi dùng'],...TPConventions.entries(db,kind).map(x=>[x.name,JSON.stringify(x),TPConventions.references(db,kind,x).length])]}))];}
function installConventionsUI(){const old=renderRules;renderRules=()=>`<div class="actions cv-actions">${cvButton('Danh mục giá trị & nơi dùng','list','parameters')}</div>`+old();const rates=renderRates;renderRates=()=>rates()+`<div class="actions cv-actions">${cvButton('Vật liệu & khối lượng riêng','list','substances')}${cvButton('Mác vật liệu','list','grades')}${cvButton('Đơn vị tính','list','units')}</div>`;const pricing=renderCostAnalysis;renderCostAnalysis=()=>pricing()+`<div class="actions">${cvButton('Nhóm khách hàng & dự phòng','groups')}</div>`;
 let formulaInput;document.addEventListener('focusin',e=>{if(e.target.matches('#dialog [name=length],#dialog [name=width],#dialog [name=mass-formula],#dialog [name=weightFormula],#dialog [name=areaFormula]'))formulaInput=e.target;});
 const oldRule=mfgEditRule;mfgEditRule=(...args)=>{oldRule(...args);$('#formula-test').insertAdjacentHTML('beforebegin',`<p class="help-text">Chọn ô công thức rồi chèn biến:</p><div class="actions cv-actions">${[...TPConventions.entries(db,'parameters').map(x=>x.name),'BW','SA','RHO','CW','CA'].map(name=>`<button type="button" class="button small" data-insert-var="${name}">${name}</button>`).join('')}</div>`);};actions['new-rule']=()=>mfgEditRule();actions['edit-rule']=el=>mfgEditRule(el.dataset.id);document.addEventListener('click',e=>{const b=e.target.closest('[data-insert-var]');if(b&&formulaInput?.isConnected){const start=formulaInput.selectionStart,end=formulaInput.selectionEnd;formulaInput.setRangeText(b.dataset.insertVar,start,end,'end');formulaInput.dispatchEvent(new Event('input',{bubbles:true}));formulaInput.focus();}});
 const oldEdit=editMaterial;editMaterial=(...args)=>{oldEdit(...args);for(const [key,kind]of [['substance','substances'],['grade','grades']]){const input=$('[name='+key+']'),id='cv-list-'+key;input.setAttribute('list',id);input.insertAdjacentHTML('afterend',`<datalist id="${id}">${TPConventions.entries(db,kind).map(x=>`<option value="${esc(x.name)}">`).join('')}</datalist>`);}const input=$('[name=substance]');input.addEventListener('change',()=>{const x=TPConventions.entries(db,'substances').find(x=>x.name===input.value);if(x)$('[name=density]').value=x.density;});};
 const source=sourceEdit;sourceEdit=(id)=>{source(id);const input=$('[name=complexity]');if(input){input.setAttribute('list','cv-complexity');input.insertAdjacentHTML('afterend',`<datalist id="cv-complexity">${TPConventions.entries(db,'complexity').map(x=>`<option value="${esc(x.name)}">`).join('')}</datalist>`);}};
 document.addEventListener('click',e=>{const b=e.target.closest('[data-convention]');if(!b)return;const {convention:a,kind,name}=b.dataset;try{if(a==='list')cvList(kind);else if(a==='edit')cvEdit(kind,name);else if(a==='groups')cvGroups();else if(a==='apply-complexity')cvComplexity();else if(a==='remove'){const uses=TPConventions.references(db,kind,{name,...TPConventions.entries(db,kind).find(x=>x.name===name)});if(uses.length)return openDialog('Giá trị đang sử dụng',`<p>${uses.length} vị trí:</p>${uses.map(x=>'<p>'+esc(x)+'</p>').join('')}`);openDialog('Xóa giá trị không dùng?',`<p>${esc(name)} sẽ bỏ khỏi danh mục lựa chọn. Có thể Hoàn tác.</p>`,'Xóa',()=>{dfCatalogWrite(()=>TPConventions.remove(db,kind,name));closeDialog();cvList(kind);});}}catch(e){toast(e.message);}});
}
function cvComplexity(){const entries=TPConventions.entries(db,'complexity');openDialog('Áp bảng độ phức tạp vào danh mục công đoạn',`<p>Mỗi nhóm có hệ số riêng, không dùng mã 1/2/3/4 để nhân trực tiếp. Báo giá cũ giữ nguyên đến khi chủ động Áp dụng đơn giá.</p>${db.rates.map(r=>`<label class="pa-checkbox"><input type="checkbox" name="rate" value="${esc(r.id)}"> ${esc(r.name)}</label>`).join('')}`, 'Lưu yếu tố cho công đoạn', f=>{const ids=f.getAll('rate');if(!ids.length)throw Error('Chọn công đoạn');dfCatalogWrite(()=>{for(const r of db.rates.filter(x=>ids.includes(x.id))){r.factors=(r.factors||[]).filter(x=>x.id!=='cv-complexity');r.factors.push({id:'cv-complexity',name:'Độ phức tạp cấu kiện',param:'complexity',enabled:true,kind:'category',categories:entries.map(x=>({key:x.name,percent:Number(x.percent)||0}))});}});closeDialog();cvList('complexity');});}

let cvProductFilter='';
function cvProductOptions(current=''){const rows=TPConventions.entries(db,'productGroups').map(x=>[x.name,x.name]);if(current&&!rows.some(x=>x[0]===current))rows.push([current,current+' (đã lưu)']);return [['','Chưa phân nhóm'],...rows];}
function cvProductButton(n,library=false){return `<button type="button" class="button small" data-cv-product="${esc(n.id)}" data-cv-library="${library}">Nhóm: ${esc(n.productGroup||'Chưa phân nhóm')}</button>`;}
function cvEditProductGroup(id,library=false,onSaved){
 const n=C.findNode(library?db.library:db.quote.products,id);if(!n||!(n.kind==='product'||library&&n.kind==='component'))return;
 const writable=()=>{if(!library){inWritable();if(Team.loaded&&!Team.permissions?.sections?.includes('bom'))throw Error('Cần quyền Cấu thành sản phẩm để đổi nhóm');if(['approved','submitted'].includes(db.quote.status))throw Error('Bản đã khóa; tạo bản sửa trước');}};writable();
 const master=TPInputPrices.defaults(db).tmcTables||[],saved=library?[]:db.quote.pricing.tmcTables||[];
 openDialog('Nhóm sản phẩm · '+esc(n.name),select('Nhóm sản phẩm','productGroup',cvProductOptions(n.productGroup),n.productGroup||'')+'<p>Danh sách được khai tại Danh mục quy ước → Nhóm sản phẩm.</p><section data-cv-tmc>'+select('Bảng giá thang máng cáp','tmcTable',[['','Chưa chọn / giữ cấu hình chi tiết'],...saved.map(t=>['saved:'+t.id,t.name+' · giá đã lưu']),...master.map(t=>['master:'+t.id,t.name+' · đơn giá đầu vào'])],n.tmcKind&&!n.tmcBreakdown?.length?(saved.some(t=>t.id===n.tmcKind)?'saved:':'master:')+n.tmcKind:'')+'<p>Nhóm Thang máng cáp mở phương án tính giá tương ứng trong báo giá. Chọn bảng giá để áp dụng cho sản phẩm; khổ rộng và chiều dài lấy từ thông số sản phẩm, có thể sửa ở phần đầu vào phương án. Phương án chào giá vẫn do người lập chọn.</p></section>','Lưu nhóm',f=>{
   writable();const group=TPConventions.productGroup(db,f.get('productGroup'),n.productGroup),choice=String(f.get('tmcTable')||'');
   const update=()=>{const prior=TPGroupPrice.resolve(db.quote,n),wasTmc=prior.scope==='tmc';n.productGroup=group;if(n.kind==='product'&&group==='Thang máng cáp'){n.priceGroupId='tmc';n.tmcScope='tmc';if(!library&&Array.isArray(db.quote.pricing.comparisonMethods)&&!db.quote.pricing.comparisonMethods.includes('tmc'))db.quote.pricing.comparisonMethods.push('tmc');if(choice){const source=choice.startsWith('master:')?master:saved,table=source.find(t=>t.id===choice.slice(choice.indexOf(':')+1));if(!table)throw Error('Bảng giá không còn tồn tại');if(n.tmcBreakdown?.length)throw Error('Sản phẩm đang có bảng giá theo cấu thành; sửa ở phần cấu thành TMC hoặc giữ cấu hình chi tiết.');n.tmcKind=table.id;if(!library&&choice.startsWith('master:')){const tables=db.quote.pricing.tmcTables,existing=tables.find(t=>t.id===table.id);if(existing&&JSON.stringify(existing)!==JSON.stringify(table)){const copy=C.copy(table);copy.id=table.id+'-'+C.uid();tables.push(copy);n.tmcKind=copy.id;}else if(!existing)tables.push(C.copy(table));}}}else if(n.kind==='product'&&group&&(wasTmc||!prior.known)){n.priceGroupId='detail';n.tmcScope='detail';}};
   if(library){dfCatalogWrite(update);closeDialog();onSaved?.();}else if(saveAndClose(update))onSaved?.();
 });const show=()=>{$('[data-cv-tmc]').hidden=n.kind!=='product'||$('[name=productGroup]').value!=='Thang máng cáp';};$('[name=productGroup]').addEventListener('change',show);show();
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-cv-product]');if(b)try{cvEditProductGroup(b.dataset.cvProduct,b.dataset.cvLibrary==='true');}catch(error){toast(error.message);}});
document.addEventListener('change',e=>{if(e.target.id==='cv-product-filter'){cvProductFilter=e.target.value;render();}});
