'use strict';
const Crm={selected:'',detail:null,owners:[],policy:{},status:'',type:'',rating:'',owner:''};
const crmButton=(label,action,id='',extra='')=>`<button type="button" class="button small" data-crm="${action}" data-id="${esc(id)}" ${extra}>${label}</button>`;
const crmAdmin=()=>!inRemoteCustomers()||Team.permissions?.users;
const crmOwner=id=>Crm.owners.find(u=>u.id===id)?.name||(id?'Tài khoản không còn trong danh sách':'Chưa giao');
async function crmLoad(){if(inRemoteCustomers()){const user=Team.user?.id;if(!user||!Team.permissions?.costs)return;const [owners,policy]=await Promise.all([teamApi('intake/owners'),teamApi('intake/policy')]);if(Team.user?.id!==user)return;Crm.owners=owners;Crm.policy=policy;}else {Crm.policy=db.customerPolicy||{};Crm.owners=db.customerOwners||[];}if(page==='customers')render();}
async function crmOpen(id){const c=inCustomers().find(c=>c.id===id);if(!c)throw Error('Không tìm thấy khách hàng');let detail;
 if(inRemoteCustomers())detail=await teamApi('intake/customers/'+encodeURIComponent(id));
 else {const quotes=[...new Map([...(db.savedQuotes||[]).map(x=>x.quote),db.quote].filter(q=>q.customerInfo?.id===id).map(q=>[q.workspaceKey||q.id,q])).values()].map(q=>({id:q.workspaceKey||q.id,code:q.id,status:q.status,total:null,opportunityId:q.opportunityId||''}));detail={customer:c,quotes,orders:[],orderCount:null};}
 Crm.selected=id;Crm.detail=detail;page='customers';render();
}
async function crmUpdate(action,data){const c=Crm.detail.customer;let next;
 if(inRemoteCustomers())next=await teamApi('intake/customers/'+encodeURIComponent(c.id)+'/'+action,'POST',{...data,expectedVersion:c.version});
 else {next=TPCrm.update(c,action,data,{name:'Người dùng trên máy'});mutation(()=>{db.customers=(db.customers||[]).map(x=>x.id===c.id?next:x);},{preserveQuote:true});}
 if(inRemoteCustomers())Intake.customers=Intake.customers.map(x=>x.id===next.id?next:x);closeDialog();await crmOpen(c.id);
}
function crmProfile(){const d=Crm.detail;if(!d)return '';const c=d.customer,a=TPCrm.assessment(c,Crm.policy,d),opps=c.opportunities||[],events=c.events||[],edit=inCanEditCustomers();return `<section class="panel intake-panel crm-profile"><div class="section-toolbar"><div><h2>${esc(c.name)}</h2><p>${esc(TPCrm.STATUS[c.status||'active'])} · ${esc(TPCrm.TYPES[c.type||'unknown'])} · Phụ trách: ${esc(crmOwner(c.ownerId))}</p></div><div class="actions">${crmButton('Đóng hồ sơ','close')}${edit?inButton('Sửa hồ sơ','customer',`data-id="${esc(c.id)}"`):''}${edit&&crmAdmin()?crmButton('Điều chuyển','assign'):''}</div></div><dl class="b1-record"><dt>Liên hệ</dt><dd>${esc([c.contact,c.phone,c.email].filter(Boolean).join(' · ')||'Chưa khai')}</dd><dt>Địa chỉ / MST</dt><dd>${esc([c.address,c.taxId].filter(Boolean).join(' · ')||'Chưa khai')}</dd><dt>Ngành / nguồn khách</dt><dd>${esc([c.industry,c.source].filter(Boolean).join(' · ')||'Chưa khai')}</dd><dt>Đánh giá</dt><dd>${esc(TPCrm.RATINGS[c.rating||'unrated'])} — ${esc(c.ratingReason||'Chưa ghi căn cứ')}</dd><dt>Ghi chú</dt><dd class="crm-text">${esc(c.notes||'—')}</dd><dt>Chăm sóc gần nhất</dt><dd>${esc(a.lastCare||'Chưa ghi nhận')} · Hẹn tiếp: ${esc(c.nextCareDate||'Chưa hẹn')}${a.overdue?' · <strong class="cell-error">Quá hạn chăm sóc</strong>':''}</dd><dt>Đơn hàng thực tế</dt><dd>${d.orderCount===null?'Chỉ thống kê trên máy chủ':num(d.orderCount)}${a.suggested?' · Gợi ý theo số đơn: '+esc(TPCrm.RATINGS[a.suggested]):''}</dd><dt>Hệ số khách hàng</dt><dd>${a.factor===null?'Chưa cấu hình':num(a.factor)+'%'} ${db.quote.customerInfo?.id===c.id&&db.quote.pricing&&(!inRemoteCustomers()||Team.permissions?.factors)&&a.factor!==null?crmButton('Áp vào báo giá đang mở','factor'):''}</dd></dl><p class="help-text">Số đơn là đơn hàng đã chuyển từ báo giá, không phải số báo giá hay cơ hội. Gợi ý không tự thay đánh giá hoặc hệ số.</p>
 <div class="section-toolbar"><h3>Lịch sử trao đổi & chăm sóc (${events.length})</h3>${edit?crmButton('+ Ghi trao đổi','interaction'):''}</div><div class="crm-timeline">${events.length?[...events].reverse().map(e=>`<article><strong>${esc(e.occurredOn||e.at?.slice(0,10)||'')} · ${esc(e.actor||'')}</strong><p class="crm-text">${esc(e.content)}</p>${e.reason?`<p>${esc(e.reason)}</p>`:''}${e.kind==='assign'?`<small>${esc(crmOwner(e.from))} → ${esc(crmOwner(e.to))}</small>`:''}${e.kind==='profile'?`<details><summary>Thông tin thay đổi</summary><p class="crm-text">${Object.keys(e.after||{}).filter(k=>JSON.stringify(e.before?.[k])!==JSON.stringify(e.after[k])).map(k=>esc(({name:'Tên',status:'Trạng thái',rating:'Đánh giá',ratingReason:'Căn cứ',ownerId:'Người phụ trách',type:'Phân loại',nextCareDate:'Hẹn chăm sóc',notes:'Ghi chú'})[k]||k)+': '+esc(e.before?.[k]??'—')+' → '+esc(e.after[k])).join('<br>')}</p></details>`:''}</article>`).join(''):'<p>Chưa có lịch sử trao đổi.</p>'}</div>
 <div class="section-toolbar"><h3>Cơ hội (${opps.length})</h3>${edit?crmButton('+ Cơ hội','opportunity'):''}</div><div class="table-scroll"><table><thead><tr><th>Cơ hội</th><th>Trạng thái / hạn</th><th>Giá trị dự kiến</th><th></th></tr></thead><tbody>${opps.map(o=>`<tr><td><strong>${esc(o.title)}</strong><small class="subtext crm-text">${esc(o.description)}</small></td><td>${esc(TPCrm.STAGES[o.stage])}<small class="subtext">${esc(o.dueDate||'Chưa hẹn')}</small></td><td>${o.value==null?'Chưa khai':money(o.value)+' đ'}</td><td><div class="actions">${edit?crmButton('Sửa','opportunity',o.id):''}${!inRemoteCustomers()||Team.permissions?.manage?crmButton('Lập báo giá','start-opportunity',o.id):''}</div></td></tr>`).join('')||'<tr><td colspan="4">Chưa có cơ hội.</td></tr>'}</tbody></table></div>
 <h3>Báo giá liên quan (${d.quotes.length})</h3><div class="table-scroll"><table><thead><tr><th>Mã báo giá</th><th>Cơ hội</th><th>Trạng thái</th><th>Tổng</th><th></th></tr></thead><tbody>${d.quotes.map(q=>`<tr><td>${esc(q.code)}</td><td>${esc(opps.find(o=>o.id===q.opportunityId)?.title||'Chưa gắn cơ hội')}</td><td>${esc(({draft:'Nháp',submitted:'Chờ duyệt',approved:'Đã duyệt'})[q.status]||q.status)}</td><td>${q.total==null?'—':money(q.total)}</td><td>${crmButton('Mở báo giá','quote',q.id)}</td></tr>`).join('')||'<tr><td colspan="5">Chưa có báo giá gắn mã khách hàng này.</td></tr>'}</tbody></table></div><p class="help-text">Báo giá cũ chỉ có tên cần chọn lại hồ sơ khách trong bản nháp để liên kết đúng; không tự ghép khách trùng tên.</p><h3>Đơn hàng (${d.orders.length})</h3>${d.orders.map(o=>`<p>${esc(o.code)} · ${esc(o.at?.slice(0,10))}</p>`).join('')||'<p>Chưa có đơn hàng liên kết.</p>'}</section>`;}
function crmCustomers(){const rows=inCustomers().filter(c=>foldText([c.name,c.contact,c.phone,c.taxId,c.email].join(' ')).includes(foldText(Intake.query))&&(!Crm.status||(c.status||'active')===Crm.status)&&(!Crm.type||(c.type||'unknown')===Crm.type)&&(!Crm.rating||(c.rating||'unrated')===Crm.rating)&&(!Crm.owner||(c.ownerId||'none')===Crm.owner));
 return heading('Khách hàng','Hồ sơ, chăm sóc, cơ hội và báo giá.',`${crmAdmin()?crmButton('Tiêu chí & hệ số','policy'):''}${inCanEditCustomers()?inButton('+ Khách hàng','customer','','primary'):''}`)+`<section class="panel intake-panel"><label class="field"><span>Tìm khách hàng</span><input data-intake-search value="${esc(Intake.query)}" placeholder="Tên, liên hệ, điện thoại, email, mã số thuế"></label><div class="form-grid crm-filters">${[['status','Trạng thái',TPCrm.STATUS],['type','Phân loại',TPCrm.TYPES],['rating','Đánh giá',TPCrm.RATINGS],['owner','Phụ trách',Object.fromEntries([['none','Chưa giao'],...Crm.owners.map(o=>[o.id,o.name])])]].map(([key,label,values])=>select(label,'crm-filter-'+key,[['','Tất cả'],...Object.entries(values)],Crm[key])).join('')}</div><div class="table-scroll"><table><thead><tr><th>Khách hàng</th><th>Liên hệ</th><th>Trạng thái / loại</th><th>Phụ trách</th><th>Đánh giá / chăm sóc</th><th></th></tr></thead><tbody>${rows.map(c=>{const a=TPCrm.assessment(c,Crm.policy);return `<tr><td><strong>${esc(c.name)}</strong><small class="subtext">${esc(c.taxId?'MST '+c.taxId:c.address)}</small></td><td>${esc(c.contact)}<small class="subtext">${esc([c.phone,c.email].filter(Boolean).join(' · '))}</small></td><td>${esc(TPCrm.STATUS[c.status||'active'])}<small class="subtext">${esc(TPCrm.TYPES[c.type||'unknown'])}</small></td><td>${esc(crmOwner(c.ownerId))}</td><td>${esc(TPCrm.RATINGS[c.rating||'unrated'])}<small class="subtext ${a.overdue?'cell-error':''}">${a.overdue?'Quá hạn · ':''}${esc(c.nextCareDate||'Chưa hẹn chăm sóc')}</small></td><td><div class="actions">${crmButton('Hồ sơ','open',c.id)}${inCanEditCustomers()?inButton('Sửa','customer',`data-id="${esc(c.id)}"`,'small'):''}${!inRemoteCustomers()||Team.permissions?.manage?inButton('Lập báo giá','start',`data-id="${esc(c.id)}"`,'small primary'):''}</div></td></tr>`;}).join('')||'<tr><td colspan="6">Chưa có khách hàng phù hợp.</td></tr>'}</tbody></table></div><p class="help-text">Danh bạ và lịch sử dùng chung trên máy chủ. Sửa hồ sơ không thay thông tin trong báo giá đã lưu.</p></section>${Crm.selected?crmProfile():''}`;
}
function crmInteraction(){teamDialog('Ghi nhận trao đổi với khách',`${select('Kênh trao đổi','channel',[['call','Điện thoại'],['meeting','Gặp trực tiếp'],['email','Email'],['message','Tin nhắn'],['other','Khác']],'call')}${field('Ngày trao đổi','occurredOn',TPComplete.todayVN(),'date','required')}${b1Area('Nội dung / kết quả trao đổi','content','',10000)}${field('Ngày chăm sóc tiếp','nextCareDate',Crm.detail.customer.nextCareDate||'','date')}`,'Lưu trao đổi',f=>crmUpdate('interaction',Object.fromEntries(f)));}
function crmOpportunity(id){const o=Crm.detail.customer.opportunities?.find(x=>x.id===id)||{};teamDialog(o.id?'Cập nhật cơ hội':'Tạo cơ hội',`${field('Tên cơ hội / dự án','title',o.title||'','text','required maxlength="200"')}${select('Giai đoạn','stage',Object.entries(TPCrm.STAGES),o.stage||'new')}${field('Giá trị dự kiến (đ)','value',o.value??'','number','min="0" step="any"')}${field('Hạn dự kiến','dueDate',o.dueDate||'','date')}${b1Area('Nhu cầu / phạm vi / kết quả làm việc','description',o.description||'',5000)}`,'Lưu cơ hội',f=>crmUpdate('opportunity',{...Object.fromEntries(f),id:o.id}));}
function crmAssign(){if(!crmAdmin())throw Error('Chỉ quản trị được điều chuyển');teamDialog('Điều chuyển khách hàng',`${select('Người tiếp nhận','ownerId',[['','Chưa giao'],...Crm.owners.filter(u=>u.active!==0).map(u=>[u.id,u.name])],Crm.detail.customer.ownerId||'')}${b1Area('Lý do điều chuyển','reason')}<p>Ghi lại người chuyển, người cũ, người mới và thời điểm. Lịch sử chăm sóc được giữ nguyên.</p>`,'Điều chuyển',f=>crmUpdate('assign',Object.fromEntries(f)));}
function crmPolicy(){if(!crmAdmin())throw Error('Chỉ quản trị cấu hình chính sách');const p=Crm.policy;teamDialog('Tiêu chí đánh giá và chăm sóc khách hàng',`<p>Để trống các ngưỡng chưa thống nhất. Hệ thống chỉ gợi ý đánh giá và báo quá hạn; quản lý quyết định điều chuyển. Hệ số chỉ áp vào báo giá khi người có quyền xác nhận.</p>${field('Từ bao nhiêu đơn hàng thì gợi ý VIP','vipOrders',p.vipOrders??'','number','min="1" step="1"')}${field('Số ngày không chăm sóc thì báo quá hạn','careDays',p.careDays??'','number','min="1" step="1"')}${b1Area('Tiêu chí đánh giá rủi ro','riskCriteria',p.riskCriteria||'',4000)}<h3>Hệ số theo đánh giá (%)</h3><p>Nhập 0 nếu không điều chỉnh, số âm để giảm, số dương để tăng.</p><div class="form-grid">${Object.entries(TPCrm.RATINGS).map(([key,label])=>field(label,'factor-'+key,p.factors?.[key]??'','number','min="-99.99" max="1000" step="any"')).join('')}</div>`,'Lưu cấu hình',async f=>{const value=TPCrm.policy({...Object.fromEntries(f),factors:Object.fromEntries(Object.keys(TPCrm.RATINGS).map(k=>[k,f.get('factor-'+k)]))});if(inRemoteCustomers())Crm.policy=await teamApi('intake/policy','POST',{policy:value,expectedVersion:p.version||0});else mutation(()=>{db.customerPolicy=value;Crm.policy=value;},{preserveQuote:true});closeDialog();render();});}
function crmFactor(){inWritable();if(inRemoteCustomers()&&(!Team.loaded||!Team.permissions?.factors))throw Error('Không có quyền đổi hệ số');const c=Crm.detail.customer,percent=TPCrm.assessment(c,Crm.policy).factor;if(db.quote.customerInfo?.id!==c.id||percent===null)throw Error('Mở báo giá đúng khách và cấu hình hệ số trước');teamDialog('Áp hệ số khách hàng',`<p>${esc(c.name)} · ${esc(TPCrm.RATINGS[c.rating])}: ${num(db.quote.pricing.customer)}% → <strong>${num(percent)}%</strong></p><p>Chỉ thay hệ số khách hàng trong báo giá đang mở. Cần rà lại giá và căn cứ thuế sau khi thay.</p>${field('Lý do áp dụng','reason',c.ratingReason||'','text','required')}`,'Áp hệ số',f=>{inWritable();mutation(()=>{db.quote.pricing.customer=percent;db.quote.pricing.customerFactorReview={customerId:c.id,rating:c.rating,percent,policyVersion:Crm.policy.version||0,at:new Date().toISOString(),reason:String(f.get('reason')).trim()};},{quoteMutation:true});closeDialog();page='quote';tab='pricing';render();});}
function crmQuoteChoices(){const form=$('#dialog-form');if(!form?.elements.customerId)return;const c=inCustomers().find(c=>c.id===form.elements.customerId.value);let box=form.querySelector('[data-crm-quote-choice]');if(!box){box=document.createElement('div');box.dataset.crmQuoteChoice='';form.elements.customerId.closest('.field').after(box);}const current=box.querySelector('select')?.value||'';box.innerHTML=select('Cơ hội liên quan','opportunityId',[['','Chưa gắn cơ hội'],...(c?.opportunities||[]).map(o=>[o.id,o.title])],current);}
function crmCareOwnerField(c){
 const current=c.id?(c.ownerId||''):(Team.user?.id||''),editable=!c.id&&crmAdmin();
 const owners=Crm.owners.filter(u=>u.active!==0||u.id===current).map(u=>[u.id,u.name+(u.active===0?' (đã khóa)':'')]);
 if(current&&!owners.some(([id])=>id===current))owners.unshift([current,Team.user?.id===current?Team.user.name:crmOwner(current)]);
 if(!current)owners.unshift(['','Chưa giao']);
 return select('Nhân viên chăm sóc','ownerId',owners,current).replace('<select ',`<select ${editable?'':'disabled '} `);
}
async function crmRefreshCareOwners(c){
 const el=$('#dialog [name=ownerId]');if(!el||c.id||!crmAdmin()||!inRemoteCustomers())return;
 const value=el.value;el.disabled=true;
 try{const owners=await teamApi('intake/owners');if(!el.isConnected)return;Crm.owners=owners;const active=owners.filter(u=>u.active!==0);el.innerHTML=active.map(u=>`<option value="${esc(u.id)}">${esc(u.name)}</option>`).join('');el.value=active.some(u=>u.id===value)?value:(Team.user?.id||'');el.disabled=false;}
 catch(e){if(el.isConnected)inError(e);}
}
function installCrmUI(){
 renderCustomers=crmCustomers;
 const load=inLoadCustomers;inLoadCustomers=async()=>{await load();await crmLoad();if(Crm.selected&&page==='customers')await crmOpen(Crm.selected);};
 const session=teamSession;teamSession=value=>{if(value.user?.id!==Team.user?.id){Crm.selected='';Crm.detail=null;Crm.owners=[];Crm.policy={};Crm.owner='';}session(value);};
 const edit=inEditCustomer;inEditCustomer=(id='',choose=false)=>{edit(id,choose);const c=inCustomers().find(x=>x.id===id)||{};$('#dialog .dialog-body').insertAdjacentHTML('beforeend',`<h3>Quản lý khách hàng</h3><div class="form-grid">${select('Trạng thái','status',Object.entries(TPCrm.STATUS),c.status||'active')}${select('Loại khách','type',Object.entries(TPCrm.TYPES),c.type||'unknown')}${select('Đánh giá','rating',Object.entries(TPCrm.RATINGS),c.rating||'unrated')}${field('Căn cứ đánh giá','ratingReason',c.ratingReason||'')}${field('Ngành nghề','industry',c.industry||'')}${field('Nguồn khách','source',c.source||'')}${field('Ngày chăm sóc tiếp','nextCareDate',c.nextCareDate||'','date')}${crmCareOwnerField(c)}</div>${b1Area('Ghi chú khách hàng','notes',c.notes||'',10000)}${Crm.policy.riskCriteria?`<p>Tiêu chí rủi ro: ${esc(Crm.policy.riskCriteria)}</p>`:''}${c.id?'<p>Quản trị dùng “Điều chuyển” trong hồ sơ để đổi nhân viên chăm sóc và lưu lý do.</p>':'<p>Nhân viên chăm sóc là người phụ trách khách hàng. Quản trị có thể giao ngay khi tạo hồ sơ.</p>'}`);$('#dialog').classList.add('wide-dialog');crmRefreshCareOwners(c);};
 const quoteDialog=b1QuoteDialog;b1QuoteDialog=(...args)=>{quoteDialog(...args);crmQuoteChoices();for(const name of ['customerId','customer'])$('#dialog-form').elements[name].addEventListener('change',crmQuoteChoices);};
 document.addEventListener('change',e=>{if(e.target.name?.startsWith('crm-filter-')){Crm[e.target.name.slice(11)]=e.target.value;render();}});
 document.addEventListener('click',e=>{const el=e.target.closest('[data-crm]');if(!el)return;e.preventDefault();Promise.resolve().then(async()=>{const a=el.dataset.crm,id=el.dataset.id;if(a==='open')await crmOpen(id);if(a==='close'){Crm.selected='';Crm.detail=null;render();}if(a==='interaction')crmInteraction();if(a==='opportunity')crmOpportunity(id);if(a==='assign')crmAssign();if(a==='policy')crmPolicy();if(a==='factor')crmFactor();if(a==='quote'){if(inRemoteCustomers()){if(Team.dirty)throw Error('Lưu báo giá đang sửa trước khi chuyển');await teamLoad(id);}else {const q=[db.quote,...(db.savedQuotes||[]).map(x=>x.quote)].find(q=>(q.workspaceKey||q.id)===id);if(!q)throw Error('Không tìm thấy báo giá');quoteSwitch(q);}page='quote';tab='intake';render();}if(a==='start-opportunity'){const c=Crm.detail.customer,o=c.opportunities.find(o=>o.id===id);if(inRemoteCustomers())await teamNewDocument();else quoteNew();const form=$('#dialog-form');form.elements.customerId.value=c.id;form.elements.customerId.dispatchEvent(new Event('change',{bubbles:true}));form.elements.opportunityId.value=id;form.elements.project.value=o.title;form.elements.requestNotes.value=o.description||'';}}).catch(inError);});
 if(!inRemoteCustomers())crmLoad().catch(inError);
}
