'use strict';
function quoteSpecificationFull(n){const details=[C.quoteSpecification(n)],nodes=C.flatten([n]);const materials=[...new Set(nodes.filter(x=>x.kind==='material'&&x.spec.shape!=='piece').map(x=>[x.spec.substance,x.spec.grade,x.spec.props.T?'dày '+num(x.spec.props.T)+' mm':''].filter(Boolean).join(' ')))];details.push(...materials);const finishes=[...new Set(nodes.flatMap(x=>(x.ops||[]).filter((op,i)=>!result.nodes[x.id]?.ownOps?.[i]?.skipped).map(op=>db.quote.ratesSnapshot.find(r=>r.id===op.id)).filter(r=>r&&(TPWork.recipes(r).length||r.finishing||r.id==='galvanize')).map(r=>r.name)))];details.push(...finishes);return [...new Set(details.filter(Boolean))].join('; ');}
function exportSheets(internal){const q=db.quote,t=result.total;
  const sheets=[{name:'Chao gia',widths:[8,42,58,10,10,20,22,40],filter:false,rows:[['STT','Sản phẩm','Thông số kỹ thuật','ĐVT','Số lượng','Đơn giá (đ)','Thành tiền (đ)','Ghi chú'],...offerSheetRows(),['','','','','','Cộng trước thuế',t.beforeTax??t.sell],...(t.taxBreakdown||[{rate:q.vat,vat:t.vat}]).map(g=>['','','','','','Thuế '+g.rate+'%',g.vat]),['','','','','','Tổng thanh toán',t.grand],[],['Mã báo giá',q.id],['Khách hàng',q.customer],['Công trình',q.project],['Ngày',q.date],['Hiệu lực',q.valid+' ngày'],['Điều kiện',q.notes],['Phạm vi','Giá đã gồm vận chuyển, lắp đặt khai báo; không cộng lại ngoài tổng.'],['Trạng thái','Bản làm việc; cần xác nhận trước khi giao dịch']]}];
  if(!internal)return sheets;
  sheets.push({name:'Ghi chu cau thanh',widths:[30,45,20,65],rows:[['Sản phẩm','Dòng cấu thành','Loại dòng','Ghi chú báo giá / sản xuất'],...q.products.flatMap(p=>C.flatten([p]).map(n=>[p.name,n.name,n.kind,n.lineNote||'']))]});
  sheets.push({name:'Luong gia phuong an',widths:[30,36,32,28,20,55,65],rows:[['Phương án','Sản phẩm','Đầu mục','Cách tính','Chi phí (đ)','Căn cứ / đã gồm','Tính chi tiết'],...Object.values(result.alternatives).filter(a=>a.applicable&&!['kg','competitor'].includes(a.id)).flatMap(a=>a.products.flatMap(p=>[...(p.costFlow||[]).map(r=>[a.name,p.node.name,r.label,TPCostFlow.MODES.find(([k])=>k===r.mode)?.[1],r.amount,r.reason+(r.includedIn?' / '+r.includedIn:''),r.calculation?JSON.stringify(r.calculation):'']),[a.name,p.node.name,'Giá gốc',paSequenceText(),p.cost,'',''],[a.name,p.node.name,'Giá chào trước thuế','Làm tròn đơn giá × số lượng',p.sell,'',p.suggestedUnit+' × '+p.node.qty]])),[],['Lưu ý','Công thức giá tổng cũ: đầu mục là tham khảo. Phương án theo đầu mục: chi phí dẫn tới giá gốc và giá chào; mỗi khoản cộng một lần.']]});
  sheets.push({name:'Luong tinh vat tu',widths:[30,40,20,36,18,18,14,20,16,18,18,20],rows:[['Sản phẩm','Vật tư / đường dẫn','Mã','Cách tính','KL tính tiền (kg)','Lượng tính tiền','ĐVT','Tiền vật tư chính','Vật tư phụ (%)','KL phụ quy đổi (kg)','Lượng phụ quy đổi','Tiền vật tư phụ'],...result.rows.map(r=>{const v=TPPrice.materialValuation(r,result,q);return [r.productName,r.path.join(' / '),r.spec.id,v.error||v.method,v.weight??'',v.basis??'',v.unit||r.spec.unit,v.cost??'',v.percent??'',v.auxiliaryWeight??'',v.auxiliaryBasis??'',v.auxiliaryCost??''];}),[],['Lưu ý','Theo phương án tính toán chi tiết. Lượng phụ chỉ quy đổi để tính tiền; không cộng vào khối lượng thực hiện hoặc vận chuyển.']]});
  const alternatives=result.comparisonIds.map(id=>result.alternatives[id]),line=(label,get)=>[label,...alternatives.map(get)],part=k=>line(paNames[k],a=>a.total.parts[k]);
  const analysis=[['NỘI BỘ — không gửi người mua',...alternatives.map(a=>a.name)],['1. Hệ số và cách tính'],line('Chi phí chung / quản lý / đặc thù SX',a=>a.products.map(p=>p.node.name+': '+[p.policyRates.overhead,p.policyRates.management,p.policyRates.special].map(v=>num(v,2)+'%').join(' / ')).join('; ')),line('Hệ số bán',a=>['kg','competitor'].includes(a.id)?'Trong giá trọn gói':a.products.map(p=>p.node.name+': '+p.saleSteps.map(f=>f.name+' '+f.percent+'%').join(' → ')).join('; ')),['2. Khối lượng, diện tích → vật tư'],line('Khối lượng phôi (kg)',a=>a.total.weight),line('Diện tích bề mặt (m²)',a=>a.total.area),...['stock','ancillary','allowance','finishing'].map(part),line('Tổng chi phí vật tư',a=>a.total.material),['Lượng tính tiền và vật tư phụ','Xem bảng Luong tinh vat tu; lượng phụ không cộng vào khối lượng thực hiện'],['3. Nguyên công → chi phí'],...['factory','outside'].map(part),['Lượng và đơn giá từng công việc','Xem bảng Cong doan; gói thuê và TMC có phân rã riêng'],['4. Chi phí khác và giá gốc'],...['tmcCommon','incoming','outgoing'].map(part),...['direct',...(!TPPrice.currentFlow(q)?['overhead','management']:[]),'special','productionExtras','production'].map(k=>line(({direct:'Chi phí trực tiếp',overhead:'Chi phí chung',management:'Quản lý',special:'Đặc thù SX',productionExtras:'Yếu tố SX bổ sung',production:'Giá sản xuất'})[k],a=>a.total[k])),...['delivery','install'].map(part),...(TPPrice.currentFlow(q)?[line('Chi phí chung',a=>a.total.overhead),line('Quản lý',a=>a.total.management)]:[]),line('Giá gốc',a=>a.total.cost),line('Khoản xử lý',a=>a.total.processing),['5. Giá chào và phần còn lại'],line('Phạm vi giá kg / đối thủ',a=>['kg','competitor'].includes(a.id)?a.products.map(p=>p.node.name+': '+paScopeSummary(p.node,a.id)).join('; '):'—'),line('Phí chưa gồm — cộng từ tính toán',a=>a.products.reduce((sum,p)=>sum+(p.benchmarkSupplement?.amount||0),0)),...['sell','vat','grand','profit'].map(k=>line(({sell:'Giá chào trước thuế',vat:'Thuế',grand:'Tổng sau thuế',profit:'Phần còn lại sau giá gốc — dự tính, không phải lãi ròng'})[k],a=>a.ready&&result.tax.methods[a.id].comparable&&(k!=='profit'||result.tax.costKnown)&&(!['vat','grand'].includes(k)||result.tax.outputKnown)?a.total[k]:'Chưa đủ căn cứ giá/thuế')),line('Phần còn lại sau giá gốc và xử lý',a=>a.ready&&result.tax.costKnown&&result.tax.methods[a.id].comparable?a.total.profit-a.total.processing:'Chưa đủ căn cứ giá/thuế'),['Phương án đang chọn',result.alternatives[result.pricing.selected].name],['Tổng giá chốt hiện tại',t.grand],['Lưu ý','Kg/đối thủ/công thức nhóm: cơ cấu chi phí chi tiết là tham khảo, không cộng lại vào giá trọn gói.']];
  sheets.push({name:'Phan tich gia',widths:[48,...alternatives.map(()=>28)],rows:analysis});
  const groupMethods=result.comparisonIds.filter(id=>id.startsWith('group:'));
  if(groupMethods.length)sheets.push({name:'Cong thuc nhom',widths:[30,36,60,60,55,22,20,22],rows:[['Phương án đối chiếu','Sản phẩm','Công thức / nhánh','Biến đã dùng (Q/KG/AREA: tổng; L/W/H/T: mm)','Căn cứ và phạm vi đã gồm','Tổng trước làm tròn','Đơn giá làm tròn','Thành tiền đề xuất'],...groupMethods.flatMap(id=>result.alternatives[id].products.map(p=>[result.alternatives[id].name,p.node.name,p.groupCalculation?.formula||(p.groupBranch==='components'?'Luồng theo đầu mục':'Chi tiết (ngoài nhóm)'),p.groupCalculation?JSON.stringify(p.groupCalculation.vars):'',p.groupCalculation?.source||'',p.groupCalculation?.total??'',p.suggestedUnit,p.sell])),[],['Lưu ý','Các dòng cơ cấu chi phí chi tiết ở bảng phân tích là tham khảo; công thức nhóm chỉ dùng những biến khai trong công thức.']]});
  sheets.push({name:'Cau thanh',widths:[24,38,22,40,13,17,17,17,18,18,18],rows:[['Sản phẩm','Đường dẫn','Mã VT','Tên','SL toàn BG','Dài KT (mm)','Rộng KT (mm)','Kg phôi','m² bề mặt','Tiền VT','Nguồn mua'],...result.rows.map(r=>[r.productName,r.path.join(' / '),r.spec.id,r.node.name,r.count,r.geometry.length,r.geometry.width,r.geometry.weight,r.geometry.area,r.cost,r.node.supplier||r.spec.supplier||''])]});
  sheets.push({name:'Cong doan',widths:[40,28,20,24,20,14,18,18,48],rows:[['Nơi thực hiện','Công đoạn','Nơi làm','Cách tính','Lượng','ĐVT','Đơn giá','Thành tiền','Tra hệ số'],...Object.values(result.nodes).flatMap(r=>(r.ownOps||[]).map(op=>[r.node.name,op.name,op.mode==='outside'?'Thuê ngoài':'Tại xưởng',({factors:'Nhân hệ số',catalog:'Danh mục',direct:'Nhập riêng',fixed:'Trọn gói'})[op.method]||'Danh mục',op.basis,op.unit,op.rate,op.cost,(op.factors||[]).map(f=>f.name+': '+f.input+' → '+f.value+'%').join('; ')]))]});
  sheets.push({name:'Vat tu hoan thien',widths:[38,22,36,14,12,12,12,16,12,18],rows:[['Nơi sử dụng','Mã VT','Vật tư','Định mức','Theo','Số lớp','Hao hụt (%)','Lượng VT','ĐVT','Thành tiền'],...result.generated.map(g=>[C.findNode(q.products,g.ownerId)?.name,g.materialId,g.name,g.norm,g.basis,g.layers||1,g.loss||0,g.quantity,g.unit,g.cost])]});
  sheets.push({name:'Van chuyen lap dat',widths:[35,26,22,18,18,20,40,25,25,16,14,18,45],rows:[['Khoản chi','Đầu mục','Phương pháp','Lượng','ĐVT','Thành tiền','Phân bổ','Điểm đi','Điểm đến','Chiều','Số lượt','Đơn giá áp dụng','Yếu tố riêng'],...result.logistics.items.map(e=>[e.name,paNames[e.category],TPWork.METHODS.find(m=>m[0]===e.method)?.[1],e.basis,e.unit,e.cost,(e.detail||[]).map(d=>d.name+': '+money(d.cost)).join('; '),e.from||'',e.to||'',e.direction||'',e.repeats||1,e.rate,(e.factorsApplied||[]).map(f=>f.name+': '+f.input+' → '+f.value+'%').join('; ')]) ]});
  sheets.push({name:'He so va cong thuc',widths:[35,22,80],rows:[['Thông số','Giá trị (%)','Cơ sở / ý nghĩa'],['Chi phí chung',q.pricing.overhead,TPPrice.currentFlow(q)?'Giá sản xuất + giao hàng + lắp đặt':'Chi phí trực tiếp sản xuất (bản cũ)'],['Quản lý',q.pricing.management,'Sau chi phí chung'],['Đặc thù SX',q.pricing.special,TPPrice.currentFlow(q)?'Chi phí trực tiếp sản xuất':'Sau quản lý (bản cũ)'],...(q.pricing.productionFactors||[]).map(f=>[f.name,f.percent,'Nhân nối tiếp trong SX, bật: '+(f.enabled!==false)+'; '+(f.reason||'Chưa ghi căn cứ')]),['Lợi nhuận',q.pricing.profit,paSequenceText()],['Xử lý',q.pricing.processing,'Sau lợi nhuận'],['Đơn hàng',q.pricing.order,'Sau xử lý'],['Khách hàng',q.pricing.customer,'Sau đơn hàng'],...(q.pricing.salesFactors||[]).map(f=>[f.name,f.percent,'Nhân nối tiếp, bật: '+(f.enabled!==false)]),['Nguyên tắc','(1+hs1)*(1+hs2)*…','Hệ số nhập theo %, chia 100 khi tính'],['Lưu ý','Bảng kết quả tại thời điểm xuất','Sửa dữ liệu trong phần mềm rồi xuất lại. Không phải workbook tự tính thay ứng dụng.']]});
  return sheets;
}
function exportWorkbook(internal=true){if(!db.quote.pricing)return toast('Dùng luồng mới để xuất bảng Excel chi tiết');if(result.errors.length)return toast('Xử lý cảnh báo trước khi xuất Excel');
  const save=()=>{closeDialog();const data=TPXlsx.make(exportSheets(internal));download(db.quote.id+(internal?'-NOI-BO':'-CHAO-GIA')+'.xlsx',data,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');};
  if(internal)openDialog('Xuất bảng Excel nội bộ',`<p>Gồm giá gốc, hệ số, nguyên công, vật tư và phân bổ vận chuyển. <strong>Không gửi file này cho người mua.</strong></p><p>Muốn gửi khách, dùng “Excel gửi khách” ở Bản chào giá. Dữ liệu xuất là kết quả tại thời điểm này, không tự tính lại khi sửa ô trong Excel.</p>`,'Xuất Excel nội bộ',save);else save();
}
function installExportUI(){
  const oldPreview=renderPreview;renderPreview=()=>{const html=oldPreview();return db.quote.pricing?`<div class="actions export-customer-action">${workButton('Excel gửi khách','export-customer-xlsx')}</div>`+html:html;};
  document.addEventListener('click',e=>{const el=e.target.closest('[data-work]');if(el?.dataset.work==='export-workbook')exportWorkbook(true);else if(el?.dataset.work==='export-customer-xlsx')exportWorkbook(false);});
}
