'use strict';
const Intake={query:'',priceTab:'materials',customers:[],remoteLoaded:false};
const inButton=(label,action,attrs='',style='')=>`<button type="button" class="button ${style}" data-intake="${action}" ${attrs}>${label}</button>`;
const inError=e=>{const el=$('#dialog-error');if($('#dialog').open&&el){el.hidden=false;el.textContent=e.message;}else toast(e.message);};
const inRequest=()=>db.quote.request||{code:'',notes:'',items:[],files:[]};
const inCustomers=()=>Team.loaded?Intake.customers:(db.customers||[]);
function inWritable(){if(Quotes.conflict)throw Error('Có thay đổi ở thẻ khác. Sao lưu và tải lại trước khi sửa.');if(Team.loaded&&(!Team.permissions?.edit||teamCurrent()?.status!=='draft'||teamCurrent()?.readOnly))throw Error('Bản đang khóa. Tạo bản sửa trước khi thay đổi.');}
function renderCustomers(){const rows=inCustomers().filter(c=>foldText([c.name,c.contact,c.phone,c.taxId].join(' ')).includes(foldText(Intake.query)));return heading('Đầu vào khách hàng','Lưu thông tin một lần, chọn lại khi lập báo giá.',inButton('+ Khách hàng','customer','','primary'))+`<section class="panel intake-panel"><label class="field"><span>Tìm khách hàng</span><input data-intake-search value="${esc(Intake.query)}" placeholder="Tên công ty, người liên hệ, số điện thoại"></label><div class="table-scroll"><table><thead><tr><th>Khách hàng</th><th>Người liên hệ</th><th>Điện thoại / email</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr><td><strong>${esc(c.name)}</strong><small class="subtext">${esc(c.taxId?'MST '+c.taxId:c.address)}</small></td><td>${esc(c.contact||'Chưa khai')}</td><td>${esc(c.phone)}<small class="subtext">${esc(c.email)}</small></td><td><div class="actions">${inButton('Sửa','customer',`data-id="${esc(c.id)}"`,'small')}${inButton('Lập báo giá','start',`data-id="${esc(c.id)}"`,'small primary')}</div></td></tr>`).join('')||'<tr><td colspan="4">Chưa có khách hàng phù hợp. Bấm “+ Khách hàng” để bắt đầu.</td></tr>'}</tbody></table></div><p class="help-text">${Team.loaded?'Danh bạ dùng chung trên máy chủ.':'Danh bạ lưu trên trình duyệt này, có trong tệp Sao lưu dữ liệu.'} Thông tin đã đưa vào báo giá được giữ riêng, không tự đổi khi sửa danh bạ.</p></section>`;}
function inEditCustomer(id='',choose=false){const c=inCustomers().find(x=>x.id===id)||(choose?{name:db.quote.customer}:{});teamDialog(c.id?'Thông tin khách hàng':'Thêm khách hàng',`<div class="form-grid">${field('Tên công ty / khách hàng','name',c.name||'','text','required maxlength="200"')}${field('Mã số thuế','taxId',c.taxId||'')}${field('Người liên hệ','contact',c.contact||'')}${field('Điện thoại','phone',c.phone||'','tel')}${field('Email','email',c.email||'','email')}${field('Địa chỉ','address',c.address||'')}</div>`,choose?'Lưu và chọn':'Lưu khách hàng',async f=>{const value=TPIntake.customer({...Object.fromEntries(f),id:c.id});if(Team.loaded){if(!Team.permissions.edit)throw Error('Không có quyền sửa danh bạ');const saved=await teamApi('intake/customers','POST',{customer:value,expectedVersion:c.version||0});Intake.customers=Intake.customers.filter(x=>x.id!==value.id).concat(saved);}else mutation(()=>{db.customers=(db.customers||[]).filter(x=>x.id!==value.id).concat(value);},{preserveQuote:true});if(choose){inWritable();mutation(()=>{db.quote.customerInfo=C.copy(value);db.quote.customer=value.name;});}closeDialog();render();});}
function inChooseCustomer(){openDialog('Chọn khách hàng',`${select('Khách hàng','customerId',[['','Chọn khách hàng'],...inCustomers().map(c=>[c.id,c.name+(c.contact?' / '+c.contact:'')])],db.quote.customerInfo?.id||'','required')}${inButton('+ Khách hàng mới','customer-choose')}<p class="help-text">Lấy thông tin hiện tại từ danh bạ vào báo giá này. Không thay báo giá khác.</p>`,'Dùng thông tin này',f=>{inWritable();const c=inCustomers().find(x=>x.id===f.get('customerId'));if(!c)throw Error('Chọn khách hàng trước');saveAndClose(()=>{db.quote.customerInfo=C.copy(c);db.quote.customer=c.name;});});}
function renderIntake(){const q=db.quote,r=inRequest(),c=q.customerInfo?.name===q.customer?q.customerInfo:null;return `<section class="panel intake-panel"><div class="section-toolbar"><div><h2>Khách hàng nhận báo giá</h2><p>${esc(c?.name||q.customer||'Chưa chọn khách hàng')}</p></div>${inButton(c?'Đổi / cập nhật khách hàng':'Chọn khách hàng','choose-customer','','primary')}</div>${c?`<div class="intake-contact"><span>${esc(c.contact||'Chưa có người liên hệ')}</span><span>${esc(c.phone)}</span><span>${esc(c.email)}</span><span>${esc(c.address)}</span></div>`:'<p class="help-text">Tên khách từ bản cũ vẫn được giữ. Chọn hoặc tạo hồ sơ để bổ sung thông tin liên hệ.</p>'}</section><section class="panel intake-panel"><div class="section-toolbar"><div><h2>Yêu cầu chào giá</h2><p>${esc(r.code||'Ghi nhận nội dung và tài liệu khách gửi để làm căn cứ bóc tách.')}</p></div>${inButton('Sửa yêu cầu','request')}</div>${r.notes?`<p class="intake-notes">${esc(r.notes)}</p>`:''}<div class="intake-files">${r.files.map(f=>`<div><span>${esc(f.name)} <small>${f.size<1024?f.size+' byte':num(f.size/1024,1)+' KB'}</small></span>${inButton('Tải tệp','file-download',`data-id="${esc(f.id)}"`,'small')}</div>`).join('')}</div><div class="actions">${inButton('Đính kèm ảnh / PDF / Excel','attach')}<span class="help-text">Tối đa 10 MB/tệp. Lưu tệp gốc, chưa tự đọc bằng AI.</span></div></section><section class="panel intake-panel"><div class="section-toolbar"><div><h2>Sản phẩm khách cần chào</h2><p>Ghi yêu cầu một lần, đưa các dòng đã chọn sang cấu thành.</p></div><div class="actions">${inButton('Dán từ Excel','paste-request')}${inButton('+ Sản phẩm yêu cầu','request-item')}</div></div><div class="table-scroll"><table><thead><tr><th>Sản phẩm / thông số yêu cầu</th><th>SL</th><th>ĐVT</th><th>Cấu thành</th><th></th></tr></thead><tbody>${r.items.map(i=>{const linked=q.products.filter(p=>p.requestLineId===i.id);return `<tr><td><strong>${esc(i.name)}</strong><small class="subtext">${esc(i.specification)}</small></td><td>${num(i.qty)}</td><td>${esc(i.unit)}</td><td>${linked.length?'Đã đưa vào báo giá':'Chưa bóc tách'}</td><td>${inButton('Sửa','request-item',`data-id="${esc(i.id)}"`,'small')}</td></tr>`;}).join('')||'<tr><td colspan="5">Thêm sản phẩm hoặc dán các dòng từ Excel.</td></tr>'}</tbody></table></div><div class="intake-bottom">${inButton('Đưa vào cấu thành','request-products',r.items.length?'':'disabled','primary')}<button class="button" data-intake="goto" data-id="bom">Đến cấu thành sản phẩm →</button></div></section>`;}
function inEditRequest(){const r=inRequest();openDialog('Nội dung yêu cầu chào giá',`${field('Mã yêu cầu / số bản vẽ','code',r.code)}<label class="field"><span>Nội dung khách yêu cầu</span><textarea name="notes" rows="5" maxlength="20000">${esc(r.notes)}</textarea></label>`,'Lưu yêu cầu',f=>{inWritable();saveAndClose(()=>db.quote.request={...C.copy(r),code:String(f.get('code')).trim(),notes:String(f.get('notes')).trim()});});}
function inEditRequestItem(id){const r=inRequest(),x=r.items.find(x=>x.id===id)||{qty:1,unit:'bộ'};openDialog('Sản phẩm khách yêu cầu',`${field('Tên sản phẩm','name',x.name||'','text','required')}<label class="field"><span>Thông số kỹ thuật / yêu cầu</span><textarea name="specification" rows="3" maxlength="2000">${esc(x.specification)}</textarea></label><div class="form-grid">${field('Số lượng','qty',x.qty,'number','min="0.001" max="5000" step="any" required')}${field('Đơn vị tính','unit',x.unit,'text','required')}</div>${db.quote.products.some(p=>p.requestLineId===id)?'<p class="notice warning">Dòng này đã có cấu thành. Sửa yêu cầu không tự thay kích thước hoặc số lượng đã bóc tách; cần rà lại cấu thành.</p>':''}`,'Lưu sản phẩm',f=>{inWritable();const item=TPIntake.requestLine({...Object.fromEntries(f),id:x.id});saveAndClose(()=>{db.quote.request={...C.copy(r),items:r.items.filter(i=>i.id!==item.id).concat(item)};});});}
function inPasteRequest(){openDialog('Dán danh sách sản phẩm từ Excel','<p>Sao chép 4 cột theo thứ tự: <strong>Tên sản phẩm · Thông số kỹ thuật · Số lượng · Đơn vị</strong>. Không lấy dòng tiêu đề.</p><label class="field"><span>Các dòng từ Excel</span><textarea name="rows" rows="7" required placeholder="Máng cáp&#9;300 × 50, dài 2000 mm&#9;10&#9;cái"></textarea></label>','Thêm vào yêu cầu',f=>{inWritable();const rows=String(f.get('rows')).trim().split(/\r?\n/).filter(Boolean).map((line,i)=>{const cells=line.split('\t');if(cells.length!==4)throw Error('Dòng '+(i+1)+': cần đủ 4 cột');return TPIntake.requestLine({name:cells[0],specification:cells[1],qty:cells[2].trim().replace(',','.'),unit:cells[3]});});const r=inRequest();if(rows.length+r.items.length>500)throw Error('Tối đa 500 sản phẩm');saveAndClose(()=>db.quote.request={...C.copy(r),items:r.items.concat(rows)});});}
function inRequestProducts(){const rows=inRequest().items.filter(i=>!db.quote.products.some(p=>p.requestLineId===i.id));if(!rows.length)return toast('Các dòng đã được đưa vào cấu thành, không thêm trùng.');openDialog('Đưa yêu cầu vào cấu thành',`<p>Chọn mẫu khi sản phẩm có cấu hình tương tự. Mẫu được sao chép độc lập; kiểm tra và chỉnh kích thước thực tế ở bước tiếp theo.</p>${rows.map(i=>`<div class="intake-transfer"><label><input type="checkbox" name="item" value="${esc(i.id)}" checked> <strong>${esc(i.name)}</strong> (${num(i.qty)} ${esc(i.unit)})</label>${select('Cấu hình ban đầu','template-'+i.id,[['','Sản phẩm trống'],...db.library.filter(t=>t.templateKind==='product').map(t=>[t.id,t.name])],'')}</div>`).join('')}`,'Tạo cấu thành',f=>{inWritable();const ids=f.getAll('item');if(!ids.length)throw Error('Chọn ít nhất một dòng');saveAndClose(()=>{const added=TPIntake.addRequestProducts(db,ids,Object.fromEntries(ids.map(id=>[id,f.get('template-'+id)])));selected=added[0];tab='bom';page='quote';});});}
// Binary files live outside localStorage so undo history and quotes stay small.
async function inFileStore(mode,id,value){const connection=await new Promise((resolve,reject)=>{const req=indexedDB.open('truongphat-source-files',1);req.onupgradeneeded=()=>req.result.createObjectStore('files');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(Error('Không mở được bộ nhớ tệp trên trình duyệt'));});try{return await new Promise((resolve,reject)=>{const tx=connection.transaction('files',mode==='put'?'readwrite':'readonly'),store=tx.objectStore('files'),request=mode==='put'?store.put(value,id):store.get(id);let result;request.onsuccess=()=>result=request.result;tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Chưa lưu được tệp'));});}finally{connection.close();}}
function inAttach(){inWritable();openDialog('Đính kèm tài liệu nguồn','<label class="field"><span>Chọn ảnh, PDF hoặc Excel</span><input type="file" name="source" accept=".png,.jpg,.jpeg,.webp,.pdf,.xlsx,.xls,.csv" required></label><p class="help-text">Tệp được lưu nguyên bản, tối đa 10 MB. Trong chế độ trên máy, tệp nằm trong bộ nhớ tệp của trình duyệt; khi chuyển máy cần tải tệp gốc theo. Sao lưu JSON chỉ chứa danh sách tệp, không chứa nội dung tệp.</p>','Lưu tệp vào yêu cầu',()=>{const file=$('#dialog [name=source]').files[0],button=$('#dialog button[type=submit]');if(!file)throw Error('Chọn tệp');if(file.size>10*1024*1024)throw Error('Tệp vượt 10 MB');if(!/\.(png|jpe?g|webp|pdf|xlsx|xls|csv)$/i.test(file.name))throw Error('Chỉ nhận ảnh, PDF và Excel/CSV');if(inRequest().files.length>=30)throw Error('Tối đa 30 tệp');button.disabled=true;const quote=db.quote;Promise.resolve().then(async()=>{const meta={id:C.uid(),name:file.name,size:file.size,type:file.type,storage:Team.loaded?'server':'local'};if(Team.loaded){const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});await teamApi('intake/files','POST',{...meta,data});}else await inFileStore('put',meta.id,file);inWritable();if(db.quote!==quote)throw Error('Đã chuyển báo giá; tệp chưa gắn vào yêu cầu.');saveAndClose(()=>db.quote.request={...C.copy(inRequest()),files:inRequest().files.concat(meta)},'Đã lưu tệp nguồn');}).catch(inError).finally(()=>{button.disabled=false;});});}
async function inDownload(id){const file=inRequest().files.find(f=>f.id===id);if(!file)throw Error('Không tìm thấy tệp nguồn');let blob;if(file.storage==='server'){const record=await teamApi('intake/files/'+file.id);blob=new Blob([Uint8Array.from(atob(record.data),c=>c.charCodeAt(0))],{type:'application/octet-stream'});}else blob=await inFileStore('get',id);if(!blob)throw Error('Tệp gốc không có trên trình duyệt này. Lấy lại từ máy đã đính kèm hoặc đính kèm lại.');download(file.name,blob,'application/octet-stream');}
function inMaterialForm(){const original=editMaterial;editMaterial=(...args)=>{original(...args);const form=$('#dialog-form');function replace(name,options,value){const old=form.querySelector(`[name="${name}"]`),el=document.createElement('select');el.name=name;el.required=name==='substance';el.innerHTML=options.map(x=>`<option value="${esc(x)}" ${x===value?'selected':''}>${esc(x||'Không áp dụng')}</option>`).join('');old.replaceWith(el);return el;}
 const substance=replace('substance',TPConventions.entries(db,'substances').map(x=>x.name),form.elements.substance.value);replace('grade',['',...TPIntake.materialChoices(db,'grades',substance.value).map(x=>x.name)],form.elements.grade.value);replace('characteristic',['',...TPIntake.materialChoices(db,'characteristics',substance.value).map(x=>x.name)],form.elements.characteristic.value);
 form.querySelector('[name=name]').closest('label').insertAdjacentHTML('afterend',`<div class="intake-name-suggestion"><span>Tên gợi ý</span><strong id="intake-name-preview"></strong>${inButton('Dùng tên này','material-name','','small')}</div>`);
 const read=()=>{const shape=form.elements.shape.value,props={};for(const key of C.shapes[shape].fixed)props[key]=form.elements[key]?.value;return {substance:substance.value,grade:form.elements.grade.value,characteristic:form.elements.characteristic.value,shape,props};};const suggestion=()=>{$('#intake-name-preview').textContent=TPIntake.materialName(read());};
 form.addEventListener('change',e=>{if(e.target===substance){for(const [name,kind]of [['grade','grades'],['characteristic','characteristics']])replace(name,['',...TPIntake.materialChoices(db,kind,substance.value).map(x=>x.name)],'');const ref=TPConventions.entries(db,'substances').find(x=>x.name===substance.value);if(ref)form.elements.density.value=ref.density;}suggestion();});form.addEventListener('input',suggestion);form.addEventListener('click',e=>{if(e.target.closest('[data-intake=material-name]')){form.elements.name.value=TPIntake.materialName(read());form.elements.name.dispatchEvent(new Event('input',{bubbles:true}));}});const submit=form.onsubmit;form.onsubmit=e=>{try{TPIntake.validateMaterial(db,read());submit(e);}catch(err){e.preventDefault();inError(err);}};suggestion();};
 const edit=cvEdit;cvEdit=(kind,name)=>{if(kind!=='characteristics')return edit(kind,name);const old=TPConventions.entries(db,kind).find(x=>x.name===name)||{};openDialog(name?'Sửa đặc tính vật liệu':'Thêm đặc tính vật liệu',`${select('Vật liệu gốc','parent',TPConventions.entries(db,'substances').map(x=>x.name),old.parent)}${field('Tên đặc tính','name',old.name||'','text','required maxlength="80"')}`,'Lưu đặc tính',f=>{const item=Object.fromEntries(f);const trial=C.copy(db);TPConventions.save(trial,kind,item,name);saveAndClose(()=>TPConventions.save(db,kind,item,name));cvList(kind);});};
 const rules=renderRules;renderRules=()=>`<section class="panel intake-panel"><h2>Danh mục dùng khi khai vật tư</h2><p>Chọn vật liệu trước; mác và đặc tính được lọc theo vật liệu đó.</p><div class="actions">${cvButton('Vật liệu','list','substances')}${cvButton('Mác vật liệu','list','grades')}${cvButton('Đặc tính','list','characteristics')}${cvButton('Đơn vị tính','list','units')}</div></section>`+rules();
}
function installIntakeUI(){db.customers??=[];inMaterialForm();
 const origNew=quoteNew;quoteNew=(...args)=>{origNew(...args);const input=$('#dialog [name=customer]');if(input){input.setAttribute('list','intake-customers');input.insertAdjacentHTML('afterend',`<datalist id="intake-customers">${inCustomers().map(c=>`<option value="${esc(c.name)}">${esc(c.contact)}</option>`).join('')}</datalist>`);}};
 const oldQuoteInfo=actions['quote-info'];actions['quote-info']=()=>{oldQuoteInfo();const input=$('#dialog [name=customer]');input?.closest('label')?.insertAdjacentHTML('beforeend','<small>Thông tin liên hệ được chọn ở bước Khách hàng & yêu cầu.</small>');};
 const oldPrice=renderPricing;renderPricing=()=>db.quote.pricing?`<div class="intake-analysis-link"><button class="button" data-intake="goto" data-id="prices">← Chọn / cập nhật giá & hệ số</button><span>So sánh một phương án chung cho toàn báo giá</span></div>`+oldPrice():inLegacyPanel()+oldPrice();
 const oldIntro=paIntro;paIntro=()=>oldIntro()+((db.legacyArchives||[]).length?`<div class="intake-archive">${inButton('Bản lưu trước khi đổi công thức','legacy-archive','','small')}</div>`:'');
 const oldSpec=quoteSpecificationFull;quoteSpecificationFull=n=>[n.requestSpecification,oldSpec(n)].filter(Boolean).join('; ');
 const oldPaper=renderAdvancedPaper;renderAdvancedPaper=()=>{let html=oldPaper();const c=db.quote.customerInfo;if(c&&c.name===db.quote.customer)html=html.replace('<div class="table-scroll"><table class="paper-table">',`<p class="intake-paper-contact">${esc([c.contact,c.phone,c.email,c.address,c.taxId?'MST '+c.taxId:''].filter(Boolean).join(' · '))}</p><div class="table-scroll"><table class="paper-table">`);return html;};
 const oldSheets=exportSheets;exportSheets=internal=>{const sheets=oldSheets(internal),c=db.quote.customerInfo;if(c&&c.name===db.quote.customer)sheets[0].rows.push(['Người nhận',c.contact],['Điện thoại khách',c.phone],['Email khách',c.email],['Địa chỉ khách',c.address],['MST khách',c.taxId]);if(internal){const r=inRequest();sheets.push({name:'Yeu cau khach',widths:[35,65,18,16],rows:[['Mã yêu cầu',r.code],['Nội dung',r.notes],['Sản phẩm','Thông số','SL','ĐVT'],...r.items.map(i=>[i.name,i.specification,i.qty,i.unit]),[],['Tệp gốc (lưu riêng)','Dung lượng'],...r.files.map(f=>[f.name,f.size])]});}return sheets;};
 const oldLoad=teamLoad;teamLoad=async(...args)=>{await oldLoad(...args);if(Team.loaded&&Team.permissions.costs){Intake.customers=await teamApi('intake/customers');Intake.remoteLoaded=true;render();}};
 actions['refresh-prices']=()=>{page='quote';tab='prices';Intake.priceTab='materials';render();};
 const guide=actions.guide;actions.guide=()=>{guide();$('#dialog .dialog-body').insertAdjacentHTML('afterbegin','<p class="notice">Luồng từ đầu: Đầu vào khách hàng → Lập báo giá → Khách hàng & yêu cầu → Đưa sản phẩm vào cấu thành → Công đoạn, khai triển, khối lượng → Giá & hệ số → So sánh 4 phương án → Bản chào giá.</p>');};
 document.addEventListener('click',e=>{const b=e.target.closest('[data-pa=enable]');if(b){e.preventDefault();e.stopImmediatePropagation();try{inLegacyDialog();}catch(err){inError(err);}}},true);
 document.addEventListener('click',e=>{if(e.target.closest('[data-page=customers]')&&Team.loaded)teamApi('intake/customers').then(rows=>{Intake.customers=rows;if(page==='customers')render();}).catch(inError);});
 document.addEventListener('input',e=>{if(e.target.hasAttribute('data-intake-search')){const pos=e.target.selectionStart;Intake.query=e.target.value;render();const input=$('[data-intake-search]');input.focus();input.setSelectionRange(pos,pos);}});
 document.addEventListener('click',e=>{const b=e.target.closest('[data-intake]');if(!b)return;e.preventDefault();const a=b.dataset.intake,id=b.dataset.id;Promise.resolve().then(async()=>{
 if(a==='customer'||a==='customer-choose')inEditCustomer(id,a==='customer-choose');else if(a==='choose-customer')inChooseCustomer();else if(a==='start'){const c=inCustomers().find(x=>x.id===id);if(Team.loaded){await teamNewDocument();const f=$('#dialog [name=customer]');if(f)f.value=c.name;}else{quoteNew();$('#dialog [name=customer]').value=c.name;}}
 else if(a==='goto'){tab=id;page='quote';render();}else if(a==='request')inEditRequest();else if(a==='request-item')inEditRequestItem(id);else if(a==='paste-request')inPasteRequest();else if(a==='request-products')inRequestProducts();else if(a==='attach')inAttach();else if(a==='file-download')await inDownload(id);
 else if(a==='price-tab'){Intake.priceTab=id;render();}else if(a==='price-reference'||a==='price-all'){const rows=TPIntake.priceRows(db);for(const [i,r]of rows.entries()){if(a==='price-reference'&&i!==Number(b.dataset.index)||r.reference==null)continue;const el=$(`[name="price-${i}"]`);el.value=r.reference;el.dataset.priceSource='catalog';$(`[name=price-selected][value="${i}"]`).checked=true;}}
 else if(a==='rate-reference'){inWritable();const current=db.quote.ratesSnapshot.find(r=>r.id===id),ref=db.rates.find(r=>r.id===id);if(!ref)throw Error('Danh mục không còn công đoạn này');openDialog('Cập nhật giá công đoạn '+esc(current.name),`<p>Giá xưởng ${money(current.inside)} → <strong>${money(ref.inside)} đ/${esc(ref.insideUnit||ref.unit)}</strong></p><p>Giá thuê ${money(current.outside)} → <strong>${money(ref.outside)} đ/${esc(ref.outsideUnit||ref.unit)}</strong></p><p>Chỉ lấy giá và đơn vị. Giữ nguyên hệ số, định mức, vật tư hoàn thiện và công việc đã khai.</p>`,'Lấy giá cho báo giá',()=>saveAndClose(()=>{for(const key of ['unit','inside','outside','insideUnit','outsideUnit']){if(ref[key]!==undefined)current[key]=C.copy(ref[key]);else delete current[key];}}));}
 else if(a==='legacy')inLegacyDialog();else if(a==='legacy-archive')inLegacyArchive();else if(a==='legacy-download'){const item=db.legacyArchives[Number(b.dataset.index)];download(item.quote.id+'-TRUOC-DOI-CONG-THUC.json',JSON.stringify({...C.copy(db),quote:item.quote,legacyArchives:[]},null,2),'application/json');}
 }).catch(inError);});
}
