'use strict';
function mfgPolicy(){
 inWritable();if(Team.loaded&&!Team.permissions.factors)throw Error('Tài khoản không được sửa hệ số');
 const p=db.quote.pricing,x=p.tmcPolicy||{},labels={overhead:'SX bổ sung ngoài chi phí chung theo bảng',management:'Quản lý',special:'Khác trong SX',profit:'Lợi nhuận',processing:'Xử lý',order:'Đơn hàng',customer:'Khách hàng'};
 openDialog('Chuỗi giá riêng TMC',`<p>Chỉ dùng cho nhóm thang máng cáp. Sản phẩm cơ khí khác giữ nguyên toàn bộ phương án chi tiết. Các hệ số này lưu riêng, không tự lấy theo hệ số của cột tính toán.</p><div class="notice">Phôi × (1 + hao hụt nhóm) + linh kiện/vật tư phụ + công TMC + công chưa được thay + hoàn thiện + VC nhập/thuê ngoài + chi phí chung nhóm → nhân lần lượt hệ số SX, quản lý, khác → cộng giao hàng/lắp đặt → nhân lần lượt hệ số bán. Không cộng lại các khoản tham chiếu sau khi đã ra giá đầy đủ.</div><p class="help-text">Giá vật tư, công hoàn thiện, thuê ngoài và vận chuyển đang khai là đầu vào thực sự dùng chung; đổi chúng sẽ tính lại. Công lắp thiết bị mới và yếu tố SX/bán bổ sung của cột chi tiết chỉ dùng đối chiếu tại nhánh TMC. Chi phí chung đã nằm trong bảng nhóm thì không khai lại cùng khoản qua hệ số SX dưới đây. Số 0 phải được nhập rõ nếu không áp dụng.</p><div class="form-grid">${TPMfg.policyKeys.map(k=>field(labels[k]+' (%)','tmcp-'+k,x[k]??'','number','min="-99.99" max="10000" step="any" required')).join('')}</div>${field('Căn cứ chuỗi giá / nguồn hệ số','tmcp-reason',x.reason||'','text','required')}<label class="device-confirm"><input type="checkbox" name="tmcp-confirm" required> Đã rà đầu vào thực sự, khoản đã gồm và chuỗi hệ số của phương án này</label><p class="help-text">Bảng nhân công và khoản tiền riêng TMC còn phải khai nguồn/thuế tại bảng giá nguồn. Đây không phải xác nhận thuế tự động.</p>`,'Lưu chuỗi TMC',f=>{
  inWritable();if(Team.loaded&&!Team.permissions.factors)throw Error('Tài khoản không được sửa hệ số');if(!f.has('tmcp-confirm'))throw Error('Cần rà chuỗi giá');const data={reason:f.get('tmcp-reason')};for(const k of TPMfg.policyKeys)data[k]=f.get('tmcp-'+k);const trial=C.copy(db.quote);TPMfg.setPolicy(trial,data);saveAndClose(()=>{db.quote.pricing.tmcPolicy=trial.pricing.tmcPolicy;},'Đã lưu chuỗi riêng TMC; rà nguồn giá và thuế trước khi phát hành');
 });$('#dialog').classList.add('wide-dialog');
}
const mfgButton=(text,action,attrs='',style='small')=>`<button type="button" class="button ${style}" data-mfg="${action}" ${attrs}>${text}</button>`;
function mfgNodeActions(n){return `<div class="mfg-node-actions">${n.kind!=='material'?mfgButton(result.nodes[n.id]?.coveredBy?'Gói thuê':'Thuê trọn','package',`data-id="${n.id}"`):''}${mfgButton('Công thức KL / DT','measure',`data-id="${n.id}"`)}</div>`;}
function mfgNodePanel(n){const r=result.nodes[n.id];return `<section class="panel mfg-node-panel"><div><strong>Phương thức thực hiện & lượng công việc</strong><p>${r.coveredBy?'Thuộc gói thuê: '+esc(C.findNode(db.quote.products,r.coveredBy)?.name)+'. Chỉ công đoạn đánh dấu “Sau khi nhận về” được tính thêm.':'Các công đoạn khai báo tại cấp này được tính riêng.'}</p><small>Phôi ${num(r.weight,3)} kg · lượng thực hiện ${num(r.workWeight??r.weight,3)} kg / ${num(r.workArea??r.area,3)} m²</small></div>${mfgNodeActions(n)}</section>`;}
function mfgPackage(id){const n=C.findNode(db.quote.products,id),r=result.nodes[id];if(!n||n.kind==='material')return;if(r.coveredBy&&r.coveredBy!==id){openDialog('Phạm vi gói thuê',`<p>Dòng này đang thuộc gói thuê của <strong>${esc(C.findNode(db.quote.products,r.coveredBy)?.name)}</strong>. Gói ở cấp trên được áp dụng một lần; các cấu hình cấp dưới vẫn giữ để dùng lại khi bỏ gói cấp trên.</p>${mfgButton('Mở gói cấp trên','package',`data-id="${r.coveredBy}"`)}`);return;}
  const x=n.outsource||{enabled:false,materialSupply:'vendor',unit:'cái',price:'',supplier:'',output:''};
  openDialog('Phương thức thực hiện: '+esc(n.name),`<label class="pa-checkbox"><input type="checkbox" name="enabled" ${x.enabled?'checked':''}> Thuê trọn phần này</label><p class="help-text">Bật gói sẽ thay công việc đang khai tại dòng này và các cấp con. Cấu thành vẫn giữ để kiểm tra hình, kích thước và khối lượng. Công đoạn làm sau khi nhận về phải đánh dấu riêng.</p><div class="form-grid">${field('Đơn vị nhận gia công','supplier',x.supplier)}${field('Đầu ra / mức hoàn thiện phải bàn giao','output',x.output)}${select('Ai cấp vật tư trong cấu thành?','materialSupply',[['vendor','Bên nhận gia công cấp — đã nằm trong giá thuê'],['company','Trường Phát cấp — vẫn tính vật tư cần mua']],x.materialSupply)}${select('Đơn vị tính gói thuê','unit',[['cái','Cho 1 sản phẩm / cấu kiện ở cấp này'],['gói','Trọn toàn bộ số lượng ở dòng này'],['kg','Theo kg thực hiện (có công thức riêng)'],['kg_phoi','Theo kg phôi'],['m²','Theo diện tích thực hiện']],x.unit)}${field('Đơn giá / giá gói (đ)','price',x.price,'number','min="0" step="any"')}${field('Lượng tính phí riêng — trống để tự tính','quantity',x.quantity??'','number','min="0.001" step="any"')}</div><div class="notice">Gói thuê không tự bao gồm các khoản vận chuyển và lắp đặt đang khai riêng. Khi đổi bên cấp vật tư, cần rà lại phương án cắt, phần dư và các khoản nhập vật tư.</div>${r.packageCharge?`<p>Giá gói hiện tại: <strong>${money(r.packageCharge.cost)} đ</strong></p>`:''}`, 'Lưu phương thức', f=>{
    const next={enabled:f.has('enabled'),supplier:String(f.get('supplier')).trim(),output:String(f.get('output')).trim(),materialSupply:f.get('materialSupply'),unit:f.get('unit'),price:f.get('price')===''?null:Number(f.get('price'))};if(f.get('quantity')!=='')next.quantity=Number(f.get('quantity'));if(next.enabled)TPMfg.packageCost({...n,outsource:next},r);saveAndClose(()=>n.outsource=next,'Đã tính lại gói thuê và vật tư cần mua');
  });$('#dialog').classList.add('wide-dialog');
}
function mfgVariableRow(key='',value=''){return `<div class="mfg-variable-row">${field('Tên biến riêng','variable-key',key)}${field('Giá trị','variable-value',value,'number','step="any"')}${mfgButton('×','remove-row','aria-label="Xóa biến"','square quiet')}</div>`;}
function mfgMeasureFields(rules={}){return `<div class="notice">Công thức trả về lượng cho <strong>1 đơn vị ở cấp đang chọn</strong>; hệ thống tự nhân số lượng. Không thay kg phôi, số tấm/thanh mua hoặc hình 3D.</div><div class="form-grid">${field('Khối lượng thực hiện (kg/đơn vị)','weightFormula',rules.weight||'','text','placeholder="Để trống: cộng lượng từ các thành phần"')}${field('Diện tích thực hiện (m²/đơn vị)','areaFormula',rules.area||'','text','placeholder="Để trống: cộng diện tích thành phần"')}</div><p class="help-text">BW: kg phôi/đơn vị; SA: diện tích hình học/đơn vị; CW, CA: lượng thực hiện từ cấp con/đơn vị. L, W, H, T, D, F: kích thước mm nếu dòng có khai báo; RHO: khối lượng riêng. Dùng + − * / và ngoặc. Ví dụ <code>BW - LO</code>, <code>CA * 0.8</code>; khai LO ở dưới.</p><div id="mfg-variables">${Object.entries(rules.vars||{}).map(([k,v])=>mfgVariableRow(k,v)).join('')}</div>${mfgButton('+ Thêm biến riêng','add-variable')}<output id="mfg-measure-preview" class="work-live-result"></output>`;}
function mfgReadMeasure(f){const vars=Object.create(null);const keys=f.getAll('variable-key'),values=f.getAll('variable-value');keys.forEach((key,i)=>{key=String(key).trim();if(!key&&!values[i])return;if(!key||Object.hasOwn(vars,key)||values[i]==='')throw Error('Biến riêng cần tên không trùng và giá trị');vars[key]=Number(values[i]);});return {weight:String(f.get('weightFormula')||'').trim(),area:String(f.get('areaFormula')||'').trim(),vars};}
function mfgEditRule(id){const old=db.rules.find(r=>r.id===id),rule=old||{id:C.uid(),name:'',shape:'sheet',length:'L',width:'W'};
  openDialog('Khai báo công thức khai triển và lượng thực hiện',`${field('Tên quy tắc','name',rule.name,'text','required')}${select('Dạng phôi','shape',[['sheet','Tấm'],['bar','Thanh']],rule.shape)}<div class="form-grid">${field('Dài khai triển (mm)','length',rule.length,'text','required')}${field('Rộng khai triển (mm)','width',rule.width,'text','required')}</div><details><summary>Công thức khối lượng / diện tích dùng lại</summary>${mfgMeasureFields(rule.measurementRules)}</details><h3>Thử công thức trước khi lưu</h3><div class="form-grid three">${[...TPConventions.entries(db,'parameters').map(x=>[x.name,({L:2000,W:300,H:50,T:1.5,D:60,F:15,W1:100,H1:50,P:100,TF:4})[x.name]||1]),['BW',10],['SA',2],['RHO',7850]].map(([k,v])=>field(k+(k==='BW'?' (kg phôi thử)':k==='SA'?' (m² hình học thử)':''),'test'+k,v,'number','min="0" step="any" required')).join('')}</div><output id="formula-test" class="work-live-result"></output>`, 'Lưu công thức', f=>{const v=evaluate(f),updated={id:rule.id,name:String(f.get('name')).trim(),shape:f.get('shape'),length:String(f.get('length')).trim(),width:String(f.get('width')).trim(),measurementRules:v.rules};saveAndClose(()=>{if(old)Object.assign(old,updated);else db.rules.push(updated);},'Đã lưu quy tắc; chọn lại ở vật tư để áp vào báo giá');});$('#dialog').classList.add('wide-dialog');
  function evaluate(f){const vars=Object.fromEntries([...TPConventions.entries(db,'parameters').map(x=>x.name),'BW','SA','RHO'].map(k=>[k,Number(f.get('test'+k))])),l=C.formula(f.get('length'),vars),w=C.formula(f.get('width'),vars);if(!(l>0)||f.get('shape')==='sheet'&&!(w>0))throw Error('Khai triển phải lớn hơn 0');const rules=mfgReadMeasure(f),n={kind:'material',params:Object.fromEntries(TPConventions.entries(db,'parameters').map(x=>x.name).map(k=>[k,vars[k]])),spec:{density:vars.RHO},measurementRules:rules},measured=TPMfg.measure(n,{count:1,weight:vars.BW,area:vars.SA},{});return {l,w,rules,measured};}
  const preview=()=>{try{const v=evaluate(new FormData($('#dialog-form')));$('#formula-test').textContent=num(v.l)+' × '+num(v.w)+' mm · Lượng thực hiện thử: '+num(v.measured.workWeight,4)+' kg / '+num(v.measured.workArea,4)+' m²';}catch(e){$('#formula-test').textContent=e.message;}};$('#dialog-form').addEventListener('input',preview);preview();
}
function mfgMeasure(id){const n=C.findNode(db.quote.products,id),r=result.nodes[id];if(!n)return;const inherited=n.ruleSpec?.measurementRules;openDialog('Công thức lượng thực hiện: '+esc(n.name),mfgMeasureFields(n.measurementRules||inherited)+`<p>Toàn báo giá có ${num(r.count)} đơn vị ở cấp này. Công đoạn theo kg/m² và định mức hoàn thiện dùng lượng thực hiện; giá theo kg phôi vẫn dùng phôi.</p>${inherited?'<label class="pa-checkbox"><input type="checkbox" name="inherit"> Bỏ công thức riêng, dùng lại công thức trong quy tắc vật tư</label>':''}`, 'Lưu và tính lại', f=>{const rules=mfgReadMeasure(f);TPMfg.measure({...n,measurementRules:rules},r,result.nodes);saveAndClose(()=>{if(f.has('inherit'))delete n.measurementRules;else n.measurementRules=rules;});});$('#dialog').classList.add('wide-dialog');const preview=()=>{try{const v=TPMfg.measure({...n,measurementRules:mfgReadMeasure(new FormData($('#dialog-form')))},r,result.nodes);$('#mfg-measure-preview').textContent='Một đơn vị: '+num(v.measurement.unitWeight,4)+' kg / '+num(v.measurement.unitArea,4)+' m² · Toàn dòng: '+num(v.workWeight,4)+' kg / '+num(v.workArea,4)+' m²';}catch(e){$('#mfg-measure-preview').textContent=e.message;}};$('#dialog-form').addEventListener('input',preview);preview();}
function mfgExtraFields(id,key,title,value={kind:'fixed',value:0,basis:'material'}){return `<h4>${title}</h4><div class="form-grid three">${select('Cách tính',key+'-kind-'+id,[['fixed','Số tiền / ĐVT nhân công'],['percent','Tỷ lệ %']],value.kind)}${field('Số tiền hoặc tỷ lệ',key+'-value-'+id,value.value??0,'number','min="0" step="any" required')}${select('Nếu là %, tính trên',key+'-basis-'+id,[['material','Vật tư phôi nhóm này'],['labor','Nhân công nhóm này'],['direct','Phôi + nhân công nhóm này']],value.basis||'material')}</div>`;}
function mfgTmcGroup(t){return `<section class="pa-tmc-editor mfg-tmc-group" data-tmc-id="${esc(t.id)}"><div class="form-grid">${field('Tên nhóm','name-'+t.id,t.name,'text','required')}${select('Đơn vị nhân công','unit-'+t.id,['m','cái','kg','m²'],t.unit)}${field('Hao hụt nhóm (%) — trống dùng chung','loss-'+t.id,t.loss??'','number','min="0" step="any"')}${select('Cách hiểu mốc kích thước','threshold-'+t.id,[['upper','Khoảng liên tiếp đến hết mốc'],['exact','Đúng kích thước mốc; dòng cuối là vượt mốc']],t.thresholdMode||'upper')}</div><div class="pa-tier-head"><span>Khổ rộng mm; để trống ở dòng cuối = vượt mốc</span><span>Giá nhân công (đ/ĐVT)</span></div>${t.tiers.map(s=>paTierRow(s,'price')).join('')}${paButton('+ Thêm bậc','add-tier','','small')}${mfgExtraFields(t.id,'aux','Vật tư phụ ước tính TMC',t.ancillary)}${mfgExtraFields(t.id,'common','Chi phí chung riêng nhóm TMC',t.common)}${mfgButton('Bỏ nhóm','remove-tmc',`data-id="${esc(t.id)}"`,'small quiet')}</section>`;}
function mfgTmcTables(){const p=db.quote.pricing;openDialog('Bảng nhân công & hao hụt TMC',`${field('Hao hụt mặc định TMC (%)','loss',p.tmcLoss,'number','min="0" step="any" required')}<p class="help-text">Mỗi nhóm có đơn vị, bậc kích thước và hao hụt riêng. Số tiền phụ/chung cố định được nhân với lượng nhân công; tỷ lệ % có cơ sở chọn rõ. Đây là chi phí ước tính riêng của phương án TMC.</p><div id="mfg-tmc-groups">${p.tmcTables.map(mfgTmcGroup).join('')}</div><div class="actions">${mfgButton('+ Thêm nhóm','add-tmc')}${mfgButton('Bổ sung nhóm nối / kẹp / U-V','tmc-presets')}</div>`, 'Lưu bảng TMC', f=>{
    const tables=[...document.querySelectorAll('[data-tmc-id]')].map(section=>{const id=section.dataset.tmcId,tiers=readTiers(section,'price');TPPrice.tier(0,tiers,'price');const x={id,name:String(f.get('name-'+id)).trim(),unit:f.get('unit-'+id),thresholdMode:f.get('threshold-'+id),tiers};if(f.get('loss-'+id)!=='')x.loss=Number(f.get('loss-'+id));for(const [key,prefix]of [['ancillary','aux'],['common','common']])x[key]={kind:f.get(prefix+'-kind-'+id),value:Number(f.get(prefix+'-value-'+id)),basis:f.get(prefix+'-basis-'+id)};return x;});if(!tables.length)throw Error('Cần ít nhất một nhóm TMC');saveAndClose(()=>{p.tmcLoss=Number(f.get('loss'));p.tmcTables=tables;});
  });$('#dialog').classList.add('wide-dialog');}
function mfgAssignmentRow(p,x={id:C.uid(),nodeId:p.id,tableId:db.quote.pricing.tmcTables[0]?.id,factor:1}){const nodes=C.flatten([p]);return `<section class="mfg-assignment" data-assignment-id="${esc(x.id)}"><div class="form-grid">${select('Phần cấu thành áp bảng','target-'+x.id,nodes.map(n=>[n.id,(C.nodePath([p],n.id)||[]).map(c=>c.name).join(' / ')]),x.nodeId)}${select('Bảng nhân công','table-'+x.id,db.quote.pricing.tmcTables.map(t=>[t.id,t.name]),x.tableId)}${field('Khổ rộng riêng (mm), trống kế thừa','width-'+x.id,x.width??'','number','min="0.001" step="any"')}${field('Chiều dài riêng (mm), trống kế thừa','length-'+x.id,x.length??'','number','min="0.001" step="any"')}${field('Số lần áp đơn giá cho phần này','factor-'+x.id,x.factor??1,'number','min="0.001" step="any" required')}</div><label><input type="checkbox" name="labor-'+x.id" ${x.laborOnly?'checked':''}> Chỉ thêm nhân công/phụ phí, không áp lại hao hụt vật tư</label>${mfgButton('Bỏ dòng','remove-row','','small quiet')}</section>`;}
function mfgTmcBreakdown(id){inWritable();const p=C.findNode(db.quote.products,id);if(!db.quote.products.includes(p))return;const entries=p.tmcBreakdown?.length?p.tmcBreakdown:[{id:C.uid(),nodeId:p.id,tableId:p.tmcKind,width:p.tmcWidth,length:p.tmcLength,factor:1}];openDialog('TMC theo cấu thành: '+esc(p.name),`<p>Chọn thân, nắp, phụ kiện và bảng giá tương ứng. Một phạm vi vật tư chỉ nhận hao hụt một lần; phần đã thuê trọn giữ giá thuê. Để áp một bảng cho cả sản phẩm, chỉ giữ dòng sản phẩm gốc.</p><div id="mfg-tmc-breakdown" data-product-id="${p.id}">${entries.map(x=>mfgAssignmentRow(p,x)).join('')}</div>${mfgButton('+ Thêm phần cấu thành','add-assignment')}`, 'Lưu phân nhóm', f=>{
    const items=[...document.querySelectorAll('[data-assignment-id]')].map(el=>{const id=el.dataset.assignmentId,x={id,nodeId:f.get('target-'+id),tableId:f.get('table-'+id),factor:Number(f.get('factor-'+id)),laborOnly:f.has('labor-'+id)};for(const k of ['width','length'])if(f.get(k+'-'+id)!=='')x[k]=Number(f.get(k+'-'+id));return x;});if(!items.length)throw Error('Cần ít nhất một phần cấu thành');const trial=C.copy(db);C.findNode(trial.quote.products,p.id).tmcBreakdown=items;C.findNode(trial.quote.products,p.id).tmcScope='tmc';const computed=C.calculate(trial);const issues=computed.alternatives.tmc.errors.filter(e=>e.startsWith(p.name+':'));if(issues.length)throw Error(issues.join('; '));saveAndClose(()=>{p.tmcBreakdown=items;p.tmcScope='tmc';});
  });$('#dialog').classList.add('wide-dialog');}
function mfgSummary(){const nodes=Object.values(result.nodes),packages=nodes.filter(r=>r.packageCharge);return `<section class="panel mfg-summary"><div class="panel-head"><div><h2>Gói thuê và lượng thực hiện</h2><p>Phôi để tính vật tư; lượng thực hiện để tính công đoạn và hoàn thiện.</p></div></div><div class="table-scroll"><table><thead><tr><th>Phần cấu thành</th><th>Phương thức</th><th>Kg phôi</th><th>Kg thực hiện</th><th>m² thực hiện</th><th></th></tr></thead><tbody>${nodes.filter(r=>r.node.kind!=='material'||r.measurement?.custom).map(r=>`<tr><td>${esc(r.node.name)}</td><td>${r.coveredBy?'Gói thuê '+esc(C.findNode(db.quote.products,r.coveredBy)?.name):'Theo công đoạn'}${r.packageCharge?'<small class="subtext">'+esc(r.packageCharge.supplier||'')+' · '+money(r.packageCharge.cost)+' đ</small>':''}</td><td>${num(r.weight,3)}</td><td>${num(r.workWeight,3)}</td><td>${num(r.workArea,3)}</td><td>${mfgNodeActions(r.node)}</td></tr>`).join('')}</tbody></table></div></section>`;}
function installManufacturingUI(){paNames.tmcCommon='Chi phí chung riêng TMC';paTmc=mfgTmcTables;
  const oldMatrix=renderOperationMatrix;renderOperationMatrix=()=>oldMatrix()+(db.quote.pricing?mfgSummary():'');
  const oldMass=renderMass;renderMass=()=>oldMass()+(db.quote.pricing?mfgSummary():'');
  const oldPricing=renderPricing;renderPricing=()=>{const html=oldPricing();if(!db.quote.pricing)return html;return html+`<section class="panel mfg-tmc-overview"><div class="panel-head"><div><h2>TMC theo từng phần cấu thành</h2><p>Một sản phẩm có thể gồm thân, nắp, nối, kẹp và nhiều loại phụ kiện.</p></div></div>${db.quote.products.map(n=>`<div class="mfg-tmc-product"><div><strong>${esc(n.name)}</strong><small>${(result.alternatives.tmc.products.find(p=>p.node.id===n.id)?.tmc.items||[]).map(i=>esc(i.table)+': '+num(i.basis)+' '+esc(i.unit)).join(' · ')||(TPMfg.scope(n)==='detail'?'Cơ khí khác → giữ giá tính toán chi tiết':'Chưa phân nhóm / đang thuê trọn')}</small></div>${mfgButton('Phân nhóm TMC','breakdown',`data-id="${n.id}"`)}</div>`).join('')}</section>`;};
  const oldNode=renderNode;renderNode=n=>oldNode(n)+(db.quote.pricing?mfgNodePanel(n):'');
  const oldEditRule=editRule;editRule=id=>db.quote.pricing?mfgEditRule(id):oldEditRule(id);
  document.addEventListener('click',e=>{const el=e.target.closest('[data-mfg]');if(!el)return;e.preventDefault();const action=el.dataset.mfg,id=el.dataset.id;
    if(action==='package')mfgPackage(id);else if(action==='policy'){try{mfgPolicy();}catch(err){toast(err.message);}}else if(action==='measure')mfgMeasure(id);else if(action==='breakdown')mfgTmcBreakdown(id);
    else if(action==='add-variable')$('#mfg-variables').insertAdjacentHTML('beforeend',mfgVariableRow());
    else if(action==='remove-row')el.closest('.mfg-variable-row,.mfg-assignment').remove();
    else if(action==='add-tmc')$('#mfg-tmc-groups').insertAdjacentHTML('beforeend',mfgTmcGroup({id:C.uid(),name:'Nhóm mới',unit:'cái',tiers:[{max:null,price:0}]}));
    else if(action==='remove-tmc'){if(C.flatten(db.quote.products).some(n=>n.tmcKind===id||(n.tmcBreakdown||[]).some(x=>x.tableId===id)))return toast('Nhóm đang dùng trong báo giá; đổi phân nhóm trước khi bỏ');el.closest('.mfg-tmc-group').remove();}
    else if(action==='tmc-presets'){for(const t of TPMfg.presets())if(!document.querySelector(`[data-tmc-id="${t.id}"]`))$('#mfg-tmc-groups').insertAdjacentHTML('beforeend',mfgTmcGroup(t));toast('Đã thêm nhóm mẫu; số giá/đơn vị cần rà trước khi sử dụng');}
    else if(action==='add-assignment'){const p=C.findNode(db.quote.products,$('#mfg-tmc-breakdown').dataset.productId);$('#mfg-tmc-breakdown').insertAdjacentHTML('beforeend',mfgAssignmentRow(p));}
    else if(action==='rule-measure'){const rule=db.rules.find(x=>x.id===id);openDialog('Công thức lượng dùng lại: '+esc(rule.name),mfgMeasureFields(rule.measurementRules)+`<p>Chỉ cập nhật quy tắc danh mục. Chọn lại quy tắc tại vật tư để áp vào bản đang làm; báo giá cũ giữ bản công thức đã chọn.</p>`, 'Lưu quy tắc', f=>{const rules=mfgReadMeasure(f),trial={id:'trial',kind:'material',qty:1,params:{L:2000,W:300,H:50,T:1.5,D:60,F:15},measurementRules:rules};TPMfg.measure(trial,{count:1,weight:10,area:2},{});saveAndClose(()=>rule.measurementRules=rules);});}
  });
}
