/* Stock arrangement belongs to the quotation's waste step. */
function meNestingList(){openDialog('Sắp xếp phôi · Khai triển & hao hụt',`<p>Chọn nhóm vật tư để xoay/ghép tự động hoặc chỉnh vị trí từng phôi. Lựa chọn chỉ áp dụng cho báo giá này.</p>${result.groups.map((g,i)=>`<p><strong>${esc(g.spec.id)} · ${esc(g.spec.name)}</strong> ${meButton('Sắp xếp phôi','nesting',i)}${g.error?'<small class="cell-error">'+esc(g.error)+'</small>':''}</p>`).join('')||'<p>Chưa có phôi đủ kích thước để sắp xếp.</p>'}`);}
function meNesting(gi){
 inWritable();const g=result.groups[gi];if(!g)return;const rows=g.rows,spec=g.spec,sheet=spec.shape==='sheet',N=TPNestingPlan,kerf=Number(db.quote.kerf),rowIds=N.ids(rows),old=(db.quote.nestingPlans||[]).find(p=>p.rowIds.some(id=>rowIds.includes(id))),count=rows.reduce((s,r)=>s+r.count,0),stale=old&&old.fingerprint!==N.fingerprint(rows,spec,kerf);
 let positions=old?.placements&&!stale?C.copy(old.placements):null;
 const options=sheet?[['bounding','Khổ bao chữ nhật — cho phép xoay'],['bounding-fixed','Khổ bao — giữ nguyên hướng'],['circle','Tấm tròn — hàng thẳng / so le'],['right-triangle','Tam giác vuông — ghép cặp']]:[['bounding','Thanh — theo chiều dài']];
 openDialog('Sắp xếp phôi · '+esc(spec.id),`<p>${count} phôi cùng nhóm trong toàn báo giá. Khổ ${num(spec.stockL)}${sheet?' × '+num(spec.stockW):''} mm; mạch cắt ${num(kerf)} mm.</p><p>Hình dạng và diện tích lấy từ quy ước. Chọn cách xoay/ghép tại đây; hình tự khai dùng khổ bao. Xếp tự động là gợi ý bằng thuật toán, chưa bảo đảm tối ưu toàn cục.</p>${stale?'<p class="notice error">Phương án cũ không còn khớp dữ liệu. Tính lại và kiểm tra trước khi lưu.</p>':''}<div class="form-grid">${select('Cách xoay / ghép','npMode',options,old?.mode||spec.shapeDefinition?.nesting||'bounding')}${select('Bố trí phôi','npEditing',[['auto','Gợi ý xếp tự động'],['manual','Chỉnh vị trí thủ công']],positions?'manual':'auto')}</div><p>Chỉnh tay: nhập số tấm/thanh, tọa độ X/Y (mm) và xoay 90°. Hệ thống kiểm tra đủ phôi, nằm trong khổ, không chồng nhau và đủ mạch cắt. Tối đa 500 phôi khi chỉnh tay; tam giác chỉnh tay theo khổ bao riêng.</p><div class="actions"><button type="button" class="button" id="np-seed">Lấy gợi ý làm bản chỉnh tay</button><button type="button" class="button" id="np-reset">Bỏ lựa chọn riêng của nhóm</button></div><div id="np-positions" class="table-scroll"></div><p id="np-result" class="notice" role="status"></p><div id="np-diagrams"></div><p>Hao hụt gợi ý = (lượng mua / phôi thực − 1) × 100%. Lưu cách xếp chỉ cập nhật tổ hợp mua; để dùng tỷ lệ này tính giá dự tính, chọn “Dùng %” tại Chọn cách / %. Phần dư đã chọn trước đó cần đối chiếu lại nếu sơ đồ đổi.</p>`, 'Lưu cách xếp',()=>{
  inWritable();const plan=current();saveAndClose(()=>{db.quote.nestingPlans=[...(db.quote.nestingPlans||[]).filter(p=>!p.rowIds.some(id=>rowIds.includes(id))),plan];},'Đã lưu cách xếp cho báo giá; đối chiếu hao hụt trước khi áp dụng %');
 });$('#dialog').classList.add('wide-dialog');const form=$('#dialog-form'),mode=form.elements.npMode,editing=form.elements.npEditing;
 function current(){if(editing.value==='manual'&&!positions)throw Error('Bấm Lấy gợi ý làm bản chỉnh tay trước');return N.make(rows,spec,kerf,mode.value,editing.value==='manual'?positions:undefined);}
 function drawInputs(){$('#np-positions').innerHTML=editing.value==='manual'&&positions?`<table><thead><tr><th>Phôi</th><th>${sheet?'Tấm':'Thanh'} số</th><th>X (mm)</th>${sheet?'<th>Y (mm)</th><th>Xoay 90°</th>':''}</tr></thead><tbody>${positions.map((p,i)=>`<tr><td>${esc(rows.find(r=>r.id===p.rowId).label)} · ${p.index+1}</td><td><input aria-label="Khổ phôi ${i+1}" type="number" min="1" max="${count}" step="1" value="${p.stock+1}" data-np-index="${i}" data-np-field="stock"></td><td><input aria-label="X phôi ${i+1}" type="number" min="0" step="any" value="${p.x}" data-np-index="${i}" data-np-field="x"></td>${sheet?`<td><input aria-label="Y phôi ${i+1}" type="number" min="0" step="any" value="${p.y}" data-np-index="${i}" data-np-field="y"></td><td><input aria-label="Xoay phôi ${i+1}" type="checkbox" ${p.rotate?'checked':''} data-np-index="${i}" data-np-field="rotate"></td>`:''}</tr>`).join('')}</tbody></table>`:'';}
 function preview(){try{const plan=current(),layout=N.apply(rows,spec,kerf,plan),scale=sheet?1e6:1000,net=sheet?rows.reduce((s,r)=>s+r.geometry.blankArea,0):rows.reduce((s,r)=>s+r.geometry.length*r.count/1000,0),loss=(layout.purchased/scale/net-1)*100;$('#np-result').textContent=`${layout.stocks.length} ${sheet?'tấm':'thanh'}; phôi thực ${num(net,6)} ${sheet?'m²':'m'}; mua ${num(layout.purchased/scale,6)} ${sheet?'m²':'m'}. Hao hụt gợi ý ${num(loss,4)}%.`;$('#np-result').dataset.valid='true';$('#np-diagrams').innerHTML=layout.stocks.slice(0,20).map((s,i)=>stockMap({...g,layout,remnants:[]},s,i)).join('')+(layout.stocks.length>20?'<p>Hiển thị 20 khổ đầu.</p>':'');$('#dialog button[type=submit]').disabled=false;}catch(e){$('#np-result').textContent=e.message;$('#np-result').dataset.valid='false';$('#np-diagrams').innerHTML='';$('#dialog button[type=submit]').disabled=true;}}
 $('#np-seed').onclick=()=>{try{if(count>500)throw Error('Chỉnh tay tối đa 500 phôi; dùng xếp tự động cho nhóm lớn hơn');if(mode.value==='right-triangle')mode.value='bounding';positions=N.draft(rows,spec,kerf,mode.value);editing.value='manual';drawInputs();preview();}catch(e){$('#np-result').textContent=e.message;}};
 $('#np-reset').onclick=()=>{inWritable();saveAndClose(()=>{db.quote.nestingPlans=(db.quote.nestingPlans||[]).filter(p=>!p.rowIds.some(id=>rowIds.includes(id)));},'Đã bỏ lựa chọn riêng; dùng cách xếp trước đó');};
 mode.onchange=preview;editing.onchange=()=>{drawInputs();preview();};form.addEventListener('input',e=>{const el=e.target;if(el.dataset.npField){const key=el.dataset.npField;positions[Number(el.dataset.npIndex)][key]=key==='rotate'?el.checked:el.value===''?NaN:Number(el.value)-(key==='stock'?1:0);preview();}});drawInputs();preview();
}
