/* Quotation-owned stock layout: preview first, persist only on Save. */
function meNestingList(){openDialog('Sắp xếp phôi · Khai triển & hao hụt',`<p>Chọn vật tư để xoay, ghép hoặc di chuyển phôi.</p>${result.groups.map((g,i)=>`<p><strong>${esc(g.spec.id)} · ${esc(g.spec.name)}</strong> ${meButton('Xoay / sắp xếp phôi','nesting',i)}</p>`).join('')||'<p>Chưa có phôi để sắp xếp.</p>'}`);}
const meNestingLabels={'bounding':'Xếp riêng, cho phép xoay','bounding-fixed':'Xếp thẳng, giữ hướng','circle':'Tấm tròn: thẳng / so le','right-triangle':'Tam giác vuông: quay đầu ghép cặp'};
function meNestingPresets(g,gi){
 if(g.spec.shape!=='sheet')return '';
 const allowed=TPNestingPlan.available(g.rows,g.spec),ids=TPNestingPlan.ids(g.rows),old=(db.quote.nestingPlans||[]).find(p=>p.rowIds.some(id=>ids.includes(id))),mode=old?.mode||g.spec.shapeDefinition?.nesting||'bounding',stale=old&&!TPNestingPlan.matches(g.rows,g.spec,Number(db.quote.kerf),old);
 return `<section class="nesting-presets" data-nesting-presets="${gi}"><strong>Cách xếp có sẵn</strong><p>Đang dùng: ${stale?'Cần chọn lại vì kích thước đã đổi':old?.placements?'Vị trí riêng đã lưu':esc(meNestingLabels[mode]||'Xếp theo khổ bao')}.</p><div class="actions">${allowed.map(value=>`<button type="button" class="button small" data-me="nesting-preset" data-id="${gi}" data-mode="${value}" aria-pressed="${!stale&&!old?.placements&&mode===value}">${esc(meNestingLabels[value])}</button>`).join('')}</div><p>Chọn để xem hình trước khi áp dụng. Sau khi xếp lại, tích phần dư muốn tận dụng để tính lại hao hụt.</p></section>`;
}
function meNesting(gi,preset){
 inWritable();const g=result.groups[gi];if(!g)return;const rows=g.rows,spec=g.spec,sheet=spec.shape==='sheet',N=TPNestingPlan,kerf=Number(db.quote.kerf),rowIds=N.ids(rows),old=(db.quote.nestingPlans||[]).find(p=>p.rowIds.some(id=>rowIds.includes(id))),count=rows.reduce((s,r)=>s+r.count,0),stale=old&&!N.matches(rows,spec,kerf,old);
 let positions=!preset&&old?.placements&&!stale?C.copy(old.placements):null,selectedPiece=0,drag=null;
 const options=sheet?[['bounding','Xếp từng phôi, cho phép xoay'],['bounding-fixed','Giữ nguyên hướng phôi'],['circle','Tấm tròn — xếp thẳng / so le'],['right-triangle','Tam giác vuông — quay đầu ghép cặp']]:[['bounding','Thanh — theo chiều dài']];
 openDialog('Xoay / sắp xếp phôi · '+spec.id,`<p>${count} phôi · Khổ ${num(spec.stockL)}${sheet?' × '+num(spec.stockW):''} mm · Mạch cắt ${num(kerf)} mm.</p>${stale?'<p class="notice error">Kích thước hoặc số lượng đã đổi. Cần sắp xếp lại.</p>':''}<div class="form-grid">${select('Cách xếp','npMode',options,preset||old?.mode||spec.shapeDefinition?.nesting||'bounding')}${select('Bố trí','npEditing',[['auto','Gợi ý tự động'],['manual','Tự xoay và di chuyển']],positions?'manual':'auto')}</div><div class="actions"><button type="button" class="button" id="np-seed">Lấy gợi ý để chỉnh</button><button type="button" class="button" id="np-reset">Bỏ cách xếp riêng</button></div><p data-np-manual-help>Chọn phôi trên hình rồi kéo để di chuyển. Có thể nhập vị trí, đổi tấm và xoay bằng các nút bên dưới. Phôi phải nằm trong khổ, không chồng nhau và đủ khoảng cắt. Chỉnh tay tối đa 500 phôi.</p><div id="np-controls"></div><p id="np-result" class="notice" role="status"></p><div id="np-diagrams"></div><p>Hao hụt = phần còn lại / (phôi + phần còn lại) × 100%. Sau khi lưu cách xếp, chọn các phần dư tận dụng để trừ khỏi hao hụt. Tỷ lệ dự tính đã lưu chỉ đổi khi anh bấm áp dụng tỷ lệ mới.</p>`,'Áp dụng cách xếp',()=>{inWritable();const plan=current();saveAndClose(()=>{db.quote.nestingPlans=[...(db.quote.nestingPlans||[]).filter(p=>!p.rowIds.some(id=>rowIds.includes(id))),plan];},'Đã lưu cách xếp; rà phần dư tận dụng trên sơ đồ mới');});
 $('#dialog').classList.add('wide-dialog');const form=$('#dialog-form'),mode=form.elements.npMode,editing=form.elements.npEditing;if(preset)form.classList.add('np-preset-preview');
 function current(){if(editing.value==='manual'&&!positions)throw Error('Bấm “Lấy gợi ý để chỉnh” trước');return N.make(rows,spec,kerf,mode.value,editing.value==='manual'?positions:undefined);}
 function controls(){const p=positions?.[selectedPiece];$('#np-controls').innerHTML=editing.value==='manual'&&p?`<div class="panel panel-body"><strong>Phôi ${selectedPiece+1}: ${esc(rows.find(r=>r.id===p.rowId).label)}</strong><div class="form-grid">${select('Chọn phôi','npSelected',positions.map((p,i)=>[i,'Phôi '+(i+1)+' · '+rows.find(r=>r.id===p.rowId).label]),selectedPiece)}${field(sheet?'Tấm số':'Thanh số','npStock',p.stock+1,'number','min="1" step="1"')}${field('Vị trí ngang X (mm)','npX',p.x,'number','min="0" step="any"')}${sheet?field('Vị trí dọc Y (mm)','npY',p.y,'number','min="0" step="any"')+field('Góc xoay (độ)','npAngle',p.angle??(p.rotate?90:0),'number','step="any"'):''}</div>${sheet?'<div class="actions"><button type="button" class="button" data-np-turn="90">Xoay 90°</button><button type="button" class="button" data-np-turn="180">Xoay 180°</button></div>':''}<small>Các số đo tính từ góc trên bên trái tấm. Góc xoay giữ nguyên hình phôi.</small></div>`:'';}
 function diagram(layout){if(editing.value!=='manual')return layout.stocks.slice(0,20).map((s,i)=>stockMap({...g,layout,remnants:[]},s,i)).join('')+(layout.stocks.length>20?'<p>Hiển thị 20 khổ đầu.</p>':'');return layout.stocks.map((s,si)=>{const h=sheet?layout.stockW:Math.max(100,layout.stockL*.08),indices=positions.map((p,i)=>p.stock===si?i:-1).filter(i=>i>=0);return `<section><h3>${sheet?'Tấm':'Thanh'} ${si+1}</h3><svg data-np-stock="${si}" aria-label="Sơ đồ ${sheet?'tấm':'thanh'} ${si+1}" viewBox="0 0 ${layout.stockL} ${h}" style="width:100%;max-height:480px;display:block;background:#f5f7fa;border:1px solid #a8b8c8;touch-action:none">${s.placements.map((p,j)=>{const i=indices[j],stroke=i===selectedPiece?'#e47913':'#fff',attrs=`data-np-piece="${i}" tabindex="0" role="button" aria-label="Chọn phôi ${i+1}" fill="${esc(p.color||'#5879ad')}" stroke="${stroke}" stroke-width="${i===selectedPiece?3:1}" vector-effect="non-scaling-stroke" style="cursor:grab"`;return `<g data-np-group="${i}">${p.circle?`<circle ${attrs} cx="${p.x+p.l/2}" cy="${p.y+p.w/2}" r="${p.l/2}"/>`:sheet?`<polygon ${attrs} points="${p.polygon.map(v=>v.join(',')).join(' ')}"/>`:`<rect ${attrs} x="${p.x}" y="0" width="${p.l}" height="${h}"/>`}<text pointer-events="none" x="${p.polygon?p.polygon.reduce((s,v)=>s+v[0],0)/p.polygon.length:p.x+p.l/2}" y="${p.polygon?p.polygon.reduce((s,v)=>s+v[1],0)/p.polygon.length:sheet?p.y+p.w/2:h/2}" font-size="${Math.max(10,layout.stockL/90)}" text-anchor="middle" fill="#fff">${i+1}</text></g>`;}).join('')}</svg></section>`;}).join('');}
 function preview(){try{const layout=N.apply(rows,spec,kerf,current()),scale=sheet?1e6:1000,net=sheet?rows.reduce((s,r)=>s+r.geometry.blankArea,0):rows.reduce((s,r)=>s+r.geometry.length*r.count/1000,0),loss=(layout.purchased/scale-net)/(layout.purchased/scale)*100;const reusable=sheet?layout.stocks.reduce((sum,stock)=>sum+stock.free.reduce((a,r)=>a+r.l*r.w,0),0)/scale:0;$('#np-result').textContent=`${layout.stocks.length} ${sheet?'tấm':'thanh'} · Phôi ${num(net,6)} ${sheet?'m²':'m'} · Hao hụt trước khi chọn tận dụng: ${num(loss,4)}%.${layout.pairCount?' Quay đầu ghép '+layout.pairCount+' cặp, còn '+layout.singleCount+' phôi lẻ.':''}${sheet?' Phần dư chữ nhật có thể chọn tận dụng: '+num(reusable,6)+' m².':''}`;$('#np-result').dataset.valid='true';$('#np-diagrams').innerHTML=diagram(layout);form.querySelector('button[type=submit]').disabled=false;return true;}catch(e){$('#np-result').textContent=e.message;$('#np-result').dataset.valid='false';form.querySelector('button[type=submit]').disabled=true;return false;}}
 function seed(){try{if(count>500)throw Error('Chỉnh tay tối đa 500 phôi');positions=N.draft(rows,spec,kerf,mode.value);editing.value='manual';selectedPiece=0;controls();preview();}catch(e){$('#np-result').textContent=e.message;}}
 $('#np-seed').onclick=seed;$('#np-reset').onclick=()=>{inWritable();saveAndClose(()=>{db.quote.nestingPlans=(db.quote.nestingPlans||[]).filter(p=>!p.rowIds.some(id=>rowIds.includes(id)));},'Đã bỏ cách xếp riêng');};
 mode.onchange=()=>{controls();preview();};editing.onchange=()=>{if(editing.value==='manual'&&!positions)seed();else{controls();preview();}};
 form.addEventListener('change',e=>{const p=positions?.[selectedPiece];if(!p)return;if(e.target.name==='npSelected'){selectedPiece=Number(e.target.value);controls();preview();return;}const key={npStock:'stock',npX:'x',npY:'y',npAngle:'angle'}[e.target.name];if(key){p[key]=e.target.value===''?NaN:Number(e.target.value)-(key==='stock'?1:0);preview();}});
 form.addEventListener('click',e=>{const b=e.target.closest('[data-np-turn]');if(b&&positions){const p=positions[selectedPiece];p.angle=((p.angle??(p.rotate?90:0))+Number(b.dataset.npTurn))%360;controls();preview();}});
 form.addEventListener('keydown',e=>{const target=e.target.closest('[data-np-piece]');if(target&&['Enter',' '].includes(e.key)){e.preventDefault();selectedPiece=Number(target.dataset.npPiece);controls();preview();}});
 function coord(svg,e,matrix){const p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(matrix||svg.getScreenCTM().inverse());}
 form.addEventListener('pointerdown',e=>{const target=e.target.closest('[data-np-piece]');if(!target||editing.value!=='manual'||e.button!==0)return;e.preventDefault();selectedPiece=Number(target.dataset.npPiece);const svg=target.closest('svg'),start=coord(svg,e);drag={svg,start,matrix:svg.getScreenCTM().inverse(),index:selectedPiece,original:{...positions[selectedPiece]},group:target.closest('g'),target,pointer:e.pointerId};target.setPointerCapture(e.pointerId);});
 form.addEventListener('pointermove',e=>{if(!drag)return;const p=coord(drag.svg,e,drag.matrix);drag.dx=p.x-drag.start.x;drag.dy=sheet?p.y-drag.start.y:0;drag.group.setAttribute('transform',`translate(${drag.dx} ${drag.dy})`);});
 form.addEventListener('pointerup',()=>{if(!drag)return;const d=drag;drag=null;positions[d.index]={...d.original,x:Math.max(0,Math.round((d.original.x+(d.dx||0))*1000)/1000),y:Math.max(0,Math.round((d.original.y+(d.dy||0))*1000)/1000)};try{current();}catch(error){positions[d.index]=d.original;toast(error.message+'; đã giữ vị trí trước khi kéo');}controls();preview();});
 form.addEventListener('pointercancel',()=>{drag=null;controls();preview();});controls();preview();
}
