'use strict';
const Notices={items:[],unread:0,state:null,quoteId:null,error:''};
const noticeLabel=stage=>stage==='technical'?'Kỹ thuật đã xác nhận hoàn tất — cần cập nhật giá vật tư':'Vật tư đã cập nhật giá — cần phê duyệt giá';
const noticeTechnical=()=>Team.permissions?.edit&&Team.permissions.sections.some(s=>['bom','operations'].includes(s));
const noticeMaterials=()=>Team.permissions?.edit&&Team.permissions.costs&&Team.permissions.sections.includes('materials');
function noticePanel(){const link=teamCurrent();if(!Team.user||!link||link.readOnly||page!=='quote'||!(Team.permissions?.costs||Team.permissions?.technical))return '';const state=Notices.quoteId===link.id?Notices.state:null,editable=link.status==='draft',line=(s,label)=>`<div><strong>${label}</strong><span>${s?`${s.current?'Đã xác nhận':'Dữ liệu đã đổi — cần xác nhận lại'} · ${esc(s.actor)} · v${s.quoteVersion} · ${esc(new Date(s.at).toLocaleString('vi-VN'))}`:'Chưa xác nhận'}</span></div>`;
 return `<section class="panel notification-handoff" data-notice-panel><div><h3>Xác nhận & bàn giao</h3><p>Xác nhận phần việc đã hoàn tất để báo cho bộ phận tiếp theo. Việc duyệt báo giá vẫn thực hiện riêng.</p></div>${state?line(state.technical,'Kỹ thuật')+line(state.materials,'Giá vật tư'):'<p>Đang tải trạng thái bàn giao…</p>'}${state&&state.quoteVersion!==link.version?'<p class="cell-error">Máy chủ có phiên bản mới. Tải lại báo giá trước khi xác nhận.</p>':''}${Notices.error?`<p class="cell-error">${esc(Notices.error)} ${noticeButton('Tải lại','refresh')}</p>`:''}<div class="actions">${editable&&noticeTechnical()?noticeButton('Xác nhận hoàn tất kỹ thuật','confirm','technical'):''}${editable&&noticeMaterials()?noticeButton('Xác nhận đã cập nhật giá vật tư','confirm','materials'):''}</div><p class="help-text">Kỹ thuật → tài khoản phụ trách giá vật tư và người duyệt. Vật tư → người duyệt. Thông báo lưu trong mục Thông báo ở thanh trên.</p></section>`;
}
function noticeButton(label,action,stage=''){return `<button type="button" class="button small" data-notice="${action}" data-stage="${stage}">${label}</button>`;}
function noticePaint(){let button=document.querySelector('[data-notice=inbox]');if(!Team.user){button?.remove();document.querySelector('[data-notice-panel]')?.remove();return;}if(!button){button=document.createElement('button');button.type='button';button.className='button small';button.dataset.notice='inbox';document.querySelector('.top-actions')?.prepend(button);}button.textContent='Thông báo'+(Notices.unread?' ('+Notices.unread+')':'');button.setAttribute('aria-label','Thông báo, '+Notices.unread+' chưa đọc');
 const panel=document.querySelector('[data-notice-panel]'),html=noticePanel();if(panel)panel.outerHTML=html;else document.querySelector('.team-banner')?.insertAdjacentHTML('afterend',html);
}
async function noticeRefresh(){if(!Team.user)return;const generation=Team.sessionGeneration,id=teamCurrent()?.id;try{const [inbox,state]=await Promise.all([teamApi('notifications'),id&&(!Team.permissions?.costs&&!Team.permissions?.technical)?null:id?teamApi('quotes/'+id+'/handoff'):null]);if(generation!==Team.sessionGeneration)return;Notices.items=inbox.items;Notices.unread=inbox.unread;Notices.error='';if(id===teamCurrent()?.id){Notices.quoteId=id;Notices.state=state;}noticePaint();}catch(e){if(generation===Team.sessionGeneration){Notices.error=e.message;noticePaint();}}}
async function noticeInbox(){await noticeRefresh();openDialog('Thông báo công việc',`${Notices.error?`<p class="cell-error">${esc(Notices.error)}</p>`:''}<p>${Notices.unread} thông báo chưa đọc. Hiển thị tối đa 200 thông báo gần nhất.</p><div class="notification-list">${Notices.items.map(n=>`<article class="${n.readAt?'':'notification-unread'}"><strong>${esc(n.code)} · ${esc(noticeLabel(n.stage))}</strong><p>${esc(n.actor)} · ${esc(new Date(n.at).toLocaleString('vi-VN'))} · phiên bản ${n.quoteVersion}</p>${n.note?`<p>${esc(n.note)}</p>`:''}<div class="actions"><button type="button" class="button small" data-notice="open" data-id="${n.id}">Mở báo giá</button>${!n.readAt?`<button type="button" class="button small" data-notice="read" data-id="${n.id}">Đánh dấu đã đọc</button>`:'<span>Đã đọc</span>'}</div></article>`).join('')||'<p>Chưa có thông báo.</p>'}</div><p class="help-text">Thông báo ghi nhận thời điểm bàn giao. Mở báo giá sẽ lấy bản hiện tại và kiểm tra lại trạng thái xác nhận.</p>`);$('#dialog').classList.add('wide-dialog');}
function noticeConfirm(stage){const link=teamCurrent();if(!link||link.readOnly||link.status!=='draft')throw Error('Mở bản nháp hiện tại trước khi xác nhận');if(Team.dirty)throw Error('Bấm Lưu máy chủ trước, sau đó xác nhận phần việc');if(!(stage==='technical'?noticeTechnical():noticeMaterials()))throw Error('Chưa có quyền xác nhận phần này');const generation=Team.sessionGeneration;
 teamDialog(stage==='technical'?'Xác nhận hoàn tất kỹ thuật':'Xác nhận đã cập nhật giá vật tư',`<p>${stage==='technical'?'Xác nhận cấu thành, kích thước, công đoạn và định mức đã khai xong. Hệ thống sẽ báo cho người phụ trách giá vật tư và người duyệt.':'Xác nhận giá vật tư trên bản đã lưu đã được rà và cập nhật xong. Hệ thống sẽ báo cho người duyệt giá.'}</p><p>Báo giá ${esc(db.quote.id)} · phiên bản ${link.version}. Xác nhận không tự duyệt báo giá.</p>${b1Area('Ghi chú bàn giao','note')}`,'Xác nhận và gửi thông báo',async f=>{if(generation!==Team.sessionGeneration||teamCurrent()?.id!==link.id)throw Error('Phiên làm việc đã đổi');const response=await teamApi('quotes/'+link.id+'/handoff/'+stage,'POST',{expectedVersion:link.version,note:f.get('note')});closeDialog();await noticeRefresh();toast(response.duplicate?'Phần này đã xác nhận; không gửi trùng':'Đã xác nhận và gửi thông báo cho '+response.recipients+' tài khoản');});
}
function installNotificationsUI(){
 const renderBefore=render;render=()=>{renderBefore();noticePaint();};
 const load=teamLoad;teamLoad=async(...args)=>{await load(...args);await noticeRefresh();};const save=teamSave;teamSave=async(...args)=>{await save(...args);await noticeRefresh();};
 const session=teamSession;teamSession=value=>{session(value);Notices.items=[];Notices.unread=0;Notices.state=null;Notices.quoteId=null;Notices.error='';noticePaint();if(Team.user)noticeRefresh();};
 setInterval(()=>{if(Team.user&&!document.hidden)noticeRefresh();},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Team.user)noticeRefresh();});
 document.addEventListener('click',e=>{const el=e.target.closest('[data-notice]');if(!el)return;e.preventDefault();Promise.resolve().then(async()=>{const action=el.dataset.notice;if(action==='inbox')await noticeInbox();if(action==='refresh')await noticeRefresh();if(action==='confirm')noticeConfirm(el.dataset.stage);if(action==='read'){await teamApi('notifications/'+el.dataset.id+'/read','POST',{});await noticeInbox();}if(action==='open'){const n=Notices.items.find(n=>n.id===el.dataset.id);if(!n)throw Error('Tải lại danh sách thông báo');if(Team.dirty)throw Error('Lưu báo giá đang sửa trước khi mở thông báo');await teamLoad(n.quoteId);page='quote';tab=n.stage==='technical'?'prices':'pricing';Intake.priceTab='materials';render();await teamApi('notifications/'+n.id+'/read','POST',{});await noticeRefresh();}}).catch(e=>toast(e.message));});
}
