'use strict';
async function noticeTeams(){
 const data=await teamApi('work-teams');if(!data.canConfigure)throw Error('Chỉ Admin được phân cấp');
 const labels={sales:'Kinh doanh',technical:'Kỹ thuật',materials:'Cập nhật giá'};
 teamDialog('Vai trò giao việc theo bộ phận','<p>Chọn Quản lý hoặc Nhân viên cho từng tài khoản. Một bộ phận có thể có nhiều quản lý. Quản lý giao việc cho chính mình hoặc nhân viên cùng bộ phận; Admin có toàn quyền. Vai trò này không tự mở quyền xem giá hoặc sửa dữ liệu.</p>'+Object.entries(labels).map(([stage,label])=>{const t=data.teams[stage]||{},users=data.users.filter(u=>u.stages.includes(stage));return `<fieldset><legend>${label}</legend>${users.map(u=>{const role=t.managers?.includes(u.id)?'manager':t.members?.includes(u.id)?'member':'';return `<label class="field"><span>${esc(u.name)}</span><select name="work-role-${stage}-${esc(u.id)}"><option value="" ${!role?'selected':''}>Không thuộc bộ phận</option><option value="manager" ${role==='manager'?'selected':''}>Quản lý</option><option value="member" ${role==='member'?'selected':''}>Nhân viên</option></select></label>`;}).join('')||'<p>Chưa có tài khoản đủ quyền cho bộ phận này.</p>'}</fieldset>`;}).join(''),'Lưu vai trò',async f=>{const teams=Object.fromEntries(Object.keys(labels).map(stage=>[stage,{managers:data.users.filter(u=>f.get('work-role-'+stage+'-'+u.id)==='manager').map(u=>u.id),members:data.users.filter(u=>f.get('work-role-'+stage+'-'+u.id)==='member').map(u=>u.id)}]));await teamApi('work-teams','PUT',{expectedVersion:data.version,teams});closeDialog();await noticeRefresh();toast('Đã lưu vai trò giao việc');});
}
async function noticeMyWork(){
 const rows=await teamApi('my-quote-work');openDialog('Công việc báo giá',`<p>Hiển thị việc được giao cho bạn; phụ trách bộ phận xem được việc của cấp dưới. Hoàn thành khi xác nhận bàn giao hợp lệ.</p><div class="table-scroll"><table><thead><tr><th>Báo giá</th><th>Phần việc</th><th>Người thực hiện</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${esc(r.code)}</td><td>${r.stage==='technical'?'Kỹ thuật':'Cập nhật giá'}</td><td>${esc(r.assignee)}</td><td>${esc(noticeWorkLabels[r.status])}</td><td><button class="button small" data-my-work-open="${i}">Mở báo giá</button>${r.status==='not-started'&&r.canStart?`<button class="button small" data-my-work-start="${i}">Bắt đầu làm</button>`:''}</td></tr>`).join('')||'<tr><td colspan="5">Chưa có công việc được giao.</td></tr>'}</tbody></table></div>`,'Đóng',closeDialog);$('#dialog').classList.add('wide-dialog');
 document.querySelectorAll('[data-my-work-open]').forEach(el=>el.onclick=async()=>{try{if(Team.dirty)throw Error('Lưu thay đổi đang làm trước khi chuyển báo giá');const r=rows[Number(el.dataset.myWorkOpen)];await teamLoad(r.quoteId);closeDialog();page='quote';tab=r.stage==='technical'?'operations':'prices';render();}catch(e){toast(e.message);}});
 document.querySelectorAll('[data-my-work-start]').forEach(el=>el.onclick=async()=>{try{const r=rows[Number(el.dataset.myWorkStart)];await teamApi('quotes/'+r.quoteId+'/work-start/'+r.stage,'POST',{expectedRevision:r.revision});await noticeRefresh();await noticeMyWork();}catch(e){toast(e.message);}});
}
document.addEventListener('click',e=>{const el=e.target.closest('[data-work-tools]');if(el)(el.dataset.workTools==='teams'?noticeTeams():noticeMyWork()).catch(e=>toast(e.message));});
const Notices={items:[],unread:0,state:null,quoteId:null,error:'',seen:null,request:0,applied:0};
// Sound stays in this browser; no microphone, OS notification or external audio permission.
const NoticeSound={context:null,enabled:true,key:''};
function noticeSoundPreference(){NoticeSound.key='tp-notice-sound:'+String(Team.user?.id??Team.user?.username??'');try{NoticeSound.enabled=localStorage.getItem(NoticeSound.key)!=='off';}catch(_){NoticeSound.enabled=true;}}
function noticeSoundReady(){return NoticeSound.enabled&&NoticeSound.context?.state==='running';}
async function noticeSoundUnlock(){
 if(!Team.user||!NoticeSound.enabled)return false;
 try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return false;if(!NoticeSound.context||NoticeSound.context.state==='closed'){NoticeSound.context=new Audio();NoticeSound.context.onstatechange=()=>noticePaint();}if(NoticeSound.context.state!=='running')await NoticeSound.context.resume();return noticeSoundReady();}catch(_){return false;}
}
function noticeSoundPlay(){
 if(!Team.user||!noticeSoundReady())return false;
 try{const ctx=NoticeSound.context,now=ctx.currentTime;for(const [offset,hz] of [[0,880],[.2,1174.66]]){const oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.type='sine';oscillator.frequency.value=hz;gain.gain.setValueAtTime(0,now+offset);gain.gain.linearRampToValueAtTime(.16,now+offset+.02);gain.gain.exponentialRampToValueAtTime(.001,now+offset+.35);oscillator.connect(gain);gain.connect(ctx.destination);oscillator.start(now+offset);oscillator.stop(now+offset+.38);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();};}document.dispatchEvent(new CustomEvent('tp-notification-chime'));return true;}catch(_){return false;}
}
async function noticeSoundToggle(test=false){
 const generation=Team.sessionGeneration;
 if(!test&&noticeSoundReady()){NoticeSound.enabled=false;try{localStorage.setItem(NoticeSound.key,'off');}catch(_){}noticePaint();return;}
 NoticeSound.enabled=true;try{localStorage.setItem(NoticeSound.key,'on');}catch(_){}
 const ready=await noticeSoundUnlock();if(generation!==Team.sessionGeneration)return;noticePaint();if(ready)noticeSoundPlay();else toast('Chưa phát được âm thanh. Bấm Bật chuông và kiểm tra âm lượng hoặc trạng thái tắt tiếng của tab.');
}
function noticeNewItems(items){
 const ids=items.map(n=>String(n.id));if(Notices.seen===null){Notices.seen=new Set(ids);return;}
 const fresh=items.filter(n=>!n.readAt&&!Notices.seen.has(String(n.id)));for(const id of ids)Notices.seen.add(id);if(Notices.seen.size>600)Notices.seen=new Set([...Notices.seen].slice(-400));if(!fresh.length)return;
 // Share only notification IDs across tabs, to avoid duplicate rings on the same browser.
 const key=NoticeSound.key+':alerted';let alerted=[];try{const saved=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(saved))alerted=saved.map(String);}catch(_){}
 const unseen=fresh.filter(n=>!alerted.includes(String(n.id)));if(!unseen.length)return;
 try{localStorage.setItem(key,JSON.stringify([...alerted,...unseen.map(n=>String(n.id))].slice(-400)));}catch(_){}
 noticeSoundPlay();toast('Có '+unseen.length+' thông báo công việc mới. Mở Thông báo để xem.');
 const button=document.querySelector('[data-notice=inbox]');if(button){button.classList.remove('notice-arrived');void button.offsetWidth;button.classList.add('notice-arrived');}
}
const noticeLabel=stage=>stage.startsWith('offer-')?({'offer-send':'Báo giá đã duyệt — cần gửi khách','offer-assign':'Cần phân công người gửi báo giá','offer-care':'Theo dõi và chăm sóc sau gửi','offer-care-due':'Đến hạn chăm sóc báo giá'}[stage]||'Theo dõi chào giá'):stage==='price-review'?'Cập nhật phương án tính giá':stage.startsWith('assigned-')?'B\u1ea1n \u0111\u01b0\u1ee3c giao '+(stage==='assigned-technical'?'k\u1ef9 thu\u1eadt':'c\u1eadp nh\u1eadt gi\u00e1'): stage==='intake'?'Đầu vào báo giá đã xác nhận — cần kỹ thuật xử lý':stage==='created'?'Báo giá mới — cần kỹ thuật nhập dữ liệu':stage==='technical'?'Kỹ thuật đã xác nhận hoàn tất — cần cập nhật giá vật tư':'Vật tư đã cập nhật giá — cần phê duyệt giá';
const noticeIntake=()=>Team.permissions?.edit&&Team.permissions.sections.includes('customer');
const noticeTechnical=()=>Team.permissions?.edit&&Team.permissions.sections.some(s=>['bom','operations'].includes(s));
const noticeMaterials=()=>Team.permissions?.edit&&Team.permissions.costs&&Team.permissions.sections.includes('materials');
function noticePanel(){const link=teamCurrent();if(!Team.user||!link||link.readOnly||page!=='quote'||!(Team.permissions?.costs||Team.permissions?.technical))return '';const state=Notices.quoteId===link.id?Notices.state:null,editable=link.status==='draft',line=(s,label)=>`<div><strong>${label}</strong><span>${s?`${s.current?'Đã xác nhận':'Dữ liệu đã đổi — cần xác nhận lại'} · ${esc(s.actor)} · v${s.quoteVersion} · ${esc(new Date(s.at).toLocaleString('vi-VN'))}${s.changeReason?' · Lý do mở sửa: '+esc(s.changeReason):''}`:'Chưa xác nhận'}</span></div>`;
 return `<section class="panel notification-handoff" data-notice-panel><div><h3>Xác nhận & bàn giao</h3><p>Xác nhận phần việc đã hoàn tất để báo cho bộ phận tiếp theo. Việc duyệt báo giá vẫn thực hiện riêng.</p></div>${state?line(state.intake,'Đầu vào báo giá')+line(state.technical,'Kỹ thuật')+line(state.materials,'Giá vật tư'):'<p>Đang tải trạng thái bàn giao…</p>'}${state&&state.quoteVersion!==link.version?'<p class="cell-error">Máy chủ có phiên bản mới. Tải lại báo giá trước khi xác nhận.</p>':''}${Notices.error?`<p class="cell-error">${esc(Notices.error)} ${noticeButton('Tải lại','refresh')}</p>`:''}<div class="actions">${editable&&noticeIntake()?((state?.intake&&!state.intake.unlocked)?noticeButton('Mở sửa đầu vào','reopen','intake'):noticeButton('Xác nhận dữ liệu đầu vào','confirm','intake')):''}${editable&&noticeTechnical()?((state?.technical&&!state.technical.unlocked)?noticeButton('Mở sửa kỹ thuật','reopen','technical'):noticeButton('Xác nhận hoàn tất kỹ thuật','confirm','technical')):''}${editable&&noticeMaterials()?((state?.materials&&!state.materials.unlocked)?noticeButton('Mở sửa giá vật tư','reopen','materials'):noticeButton('Xác nhận đã cập nhật giá vật tư','confirm','materials')):''}</div><p class="help-text">Tạo báo giá → kỹ thuật nhập dữ liệu. Kỹ thuật → tài khoản phụ trách giá vật tư và người duyệt. Vật tư → người duyệt. Thông báo lưu trong mục Thông báo ở thanh trên.</p></section>`;
}
function noticeButton(label,action,stage=''){return `<button type="button" class="button small" data-notice="${action}" data-stage="${stage}">${label}</button>`;}
const noticeWorkLabels={'not-started':'Chưa làm','in-progress':'Đang làm',completed:'Đã xong',cancelled:'Đã hủy'};
function noticeWorkPanel(){const link=teamCurrent();if(!Team.user||!link||page!=='quote'||tab!=='intake')return '';const w=Notices.quoteId===link.id?Notices.state?.work:null;const person=(p,stage)=>p?esc(p.name)+(p.active?'':' · Ngừng hoạt động')+(w.tasks?.[stage]?' · '+esc(noticeWorkLabels[w.tasks[stage]]):''):'Chưa giao riêng';return `<div class="notice-work" data-notice-work><div class="section-toolbar"><h3>Giao việc & tình trạng đơn hàng</h3>${noticeButton('Công việc báo giá','my-work')}${!link.readOnly&&(w?.canEdit??(Team.permissions.manage||noticeIntake()))?noticeButton('Giao việc / cập nhật tình trạng','work'):''}</div>${w?`<dl class="b1-record"><dt>Tình trạng đơn hàng</dt><dd><strong class="order-state order-${esc(w.status)}">${esc(noticeWorkLabels[w.status]||'Chưa làm')}</strong></dd><dt>Phụ trách kỹ thuật</dt><dd>${person(w.technical,'technical')}</dd><dt>Phụ trách cập nhật giá</dt><dd>${person(w.materials,'materials')}</dd></dl>${w.statusReason?`<p class="help-text">${esc(w.statusReason)}</p>`:''}${w.updated?`<p class="help-text">${esc(w.actor)} · ${esc(new Date(w.updated).toLocaleString('vi-VN'))}</p>`:''}`:'<p>Đang tải giao việc…</p>'}<p class="help-text">Xác nhận đầu vào để báo Admin và quản lý kinh doanh, kỹ thuật, giá; xác nhận kỹ thuật để báo người cập nhật giá và người duyệt. Chưa giao riêng thì thông báo đến các tài khoản phụ trách phần việc đó.</p></div>`;}
async function noticeWorkEdit(){const link=teamCurrent(),generation=Team.sessionGeneration;if(!link||link.readOnly)throw Error('Mở báo giá hiện tại để giao việc');const w=await teamApi('quotes/'+link.id+'/work');if(generation!==Team.sessionGeneration||teamCurrent()?.id!==link.id)return;if(!w.canEdit)throw Error('Chưa có quyền giao việc');const select=(label,key,selected,choices)=>`<label class="field"><span>${label}</span><select name="${key}" ${choices.length?'':'disabled'}><option value="">Chưa giao riêng</option>${selected&&!choices.some(u=>u.id===selected.id)?`<option value="${esc(selected.id)}" selected>${esc(selected.name)} · Cần chọn lại</option>`:''}${choices.map(u=>`<option value="${esc(u.id)}" ${u.id===selected?.id?'selected':''}>${esc(u.name)}</option>`).join('')}</select></label>`;
 teamDialog('Giao việc & tình trạng đơn hàng',`<div class="form-grid">${select('Phụ trách kỹ thuật','technicalId',w.technical,w.candidates.technical)}${select('Phụ trách cập nhật giá','materialsId',w.materials,w.candidates.materials)}</div><label class="field"><span>Tình trạng đơn hàng</span><select name="workStatus" ${w.canStatus===false?'disabled':''}>${Object.entries(noticeWorkLabels).map(([id,label])=>`<option value="${id}" ${w.status===id?'selected':''}>${label}</option>`).join('')}</select></label><p class="help-text">Khi đã xác nhận bàn giao hoặc gửi duyệt, tình trạng tự chuyển sang Đang làm. Đã xong và Đã hủy do người phụ trách cập nhật. Lưu giao việc sẽ gửi thông báo ngay cho người được giao.</p>`,'Lưu giao việc',async f=>{if(generation!==Team.sessionGeneration||teamCurrent()?.id!==link.id)throw Error('Phiên làm việc đã đổi');await teamApi('quotes/'+link.id+'/work','PUT',{expectedRevision:w.revision,technicalId:w.candidates.technical.length?f.get('technicalId')||null:w.technical?.id||null,materialsId:w.candidates.materials.length?f.get('materialsId')||null:w.materials?.id||null,status:f.get('workStatus')||w.status});closeDialog();await noticeRefresh();if(typeof WorkspaceHome!=='undefined')WorkspaceHome.at=0;toast('Đã lưu giao việc và tình trạng đơn hàng');});
}
function noticePaint(){if(!Team.user)document.querySelectorAll('[data-work-tools]').forEach(e=>e.remove());if(Team.user&&!document.querySelector('[data-work-tools]'))document.querySelector('.top-actions')?.insertAdjacentHTML('beforeend','<button type="button" class="button small" data-work-tools="mine">C\u00f4ng vi\u1ec7c b\u00e1o gi\u00e1</button>'+(Team.user.role==='admin'?'<button type="button" class="button small" data-work-tools="teams">Nh\u00e2n s\u1ef1 & ph\u00f2ng ban</button>':''));let button=document.querySelector('[data-notice=inbox]');if(!Team.user){document.querySelector('[data-notice=sound]')?.remove();button?.remove();document.querySelector('[data-notice-panel]')?.remove();return;}if(!button){button=document.createElement('button');button.type='button';button.className='button small';button.dataset.notice='inbox';document.querySelector('.top-actions')?.prepend(button);}button.textContent='Thông báo'+(Notices.unread?' ('+Notices.unread+')':'');button.setAttribute('aria-label','Thông báo, '+Notices.unread+' chưa đọc');
 let sound=document.querySelector('.top-actions [data-notice=sound]');if(!sound){sound=document.createElement('button');sound.type='button';sound.className='button small notice-sound';sound.dataset.notice='sound';button.insertAdjacentElement('afterend',sound);}sound.textContent=noticeSoundReady()?'Chuông: bật':NoticeSound.enabled?'Bật chuông':'Chuông: tắt';sound.setAttribute('aria-pressed',String(noticeSoundReady()));sound.title=noticeSoundReady()?'Tắt âm thanh thông báo':'Bật và nghe thử âm thanh thông báo';
 const workPanel=document.querySelector('[data-notice-work]'),workHtml=noticeWorkPanel();if(workPanel){if(workPanel._noticeHtml!==workHtml)workPanel.outerHTML=workHtml;}else document.querySelector('.b1-request-summary')?.insertAdjacentHTML('beforeend',workHtml);const currentWork=document.querySelector('[data-notice-work]');if(currentWork)currentWork._noticeHtml=workHtml;
 const panel=document.querySelector('[data-notice-panel]'),html=noticePanel();if(panel){if(panel._noticeHtml!==html)panel.outerHTML=html;}else document.querySelector('.team-banner')?.insertAdjacentHTML('afterend',html);const currentPanel=document.querySelector('[data-notice-panel]');if(currentPanel)currentPanel._noticeHtml=html;
}
async function noticeRefresh(){if(!Team.user)return;const generation=Team.sessionGeneration,id=teamCurrent()?.id,request=++Notices.request;try{const [inbox,state]=await Promise.all([teamApi('notifications'),id&&(!Team.permissions?.costs&&!Team.permissions?.technical)?null:id?teamApi('quotes/'+id+'/handoff'):null]);if(generation!==Team.sessionGeneration||request<Notices.applied)return;Notices.applied=request;Notices.items=inbox.items;Notices.unread=inbox.unread;Notices.error='';if(id===teamCurrent()?.id){Notices.quoteId=id;Notices.state=state;}noticePaint();if(typeof reviewTasks==='function')reviewTasks();noticeNewItems(inbox.items);}catch(e){if(generation===Team.sessionGeneration&&request>=Notices.applied){Notices.error=e.message;noticePaint();}}}
async function noticeInbox(){await noticeRefresh();openDialog('Thông báo công việc',`${Notices.error?`<p class="cell-error">${esc(Notices.error)}</p>`:''}<div class="notice"><p>Chuông báo khi có thông báo mới trong lúc đang mở web. Thông báo cũ không reo lại khi tải trang. Trình duyệt có thể yêu cầu bấm Bật chuông trước.</p><div class="actions">${noticeButton('Nghe thử / bật chuông','test-sound')}<button type="button" class="button" data-chat-desktop>Bật thông báo thiết bị</button></div></div><p>${Notices.unread} thông báo chưa đọc. Hiển thị tối đa 200 thông báo gần nhất.</p><div class="notification-list">${Notices.items.map(n=>`<article class="${n.readAt?'':'notification-unread'}"><strong>${esc(n.code)} · ${esc(n.note?.startsWith('Mở sửa ')?'Yêu cầu rà và xác nhận lại':noticeLabel(n.stage))}</strong><p>${esc(n.actor)} · ${esc(new Date(n.at).toLocaleString('vi-VN'))} · phiên bản ${n.quoteVersion}</p>${n.note?`<p>${esc(n.note)}</p>`:''}<div class="actions"><button type="button" class="button small" data-notice="open" data-id="${n.id}">Mở báo giá</button>${!n.readAt?`<button type="button" class="button small" data-notice="read" data-id="${n.id}">Đánh dấu đã đọc</button>`:'<span>Đã đọc</span>'}</div></article>`).join('')||'<p>Chưa có thông báo.</p>'}</div><p class="help-text">Thông báo ghi nhận thời điểm bàn giao. Mở báo giá sẽ lấy bản hiện tại và kiểm tra lại trạng thái xác nhận.</p>`);$('#dialog').classList.add('wide-dialog');chatAlertsPaint();}
function noticeConfirm(stage){const link=teamCurrent();if(!link||link.readOnly||link.status!=='draft')throw Error('Mở bản nháp hiện tại trước khi xác nhận');if(Team.dirty)throw Error('Bấm Lưu báo giá lên máy chủ trước, sau đó xác nhận phần việc');if(!(stage==='intake'?noticeIntake():stage==='technical'?noticeTechnical():noticeMaterials()))throw Error('Chưa có quyền xác nhận phần này');const generation=Team.sessionGeneration;
 teamDialog(stage==='intake'?'Xác nhận đầu vào báo giá':stage==='technical'?'Xác nhận hoàn tất kỹ thuật':'Xác nhận đã cập nhật giá vật tư',`<p>${stage==='intake'?'Xác nhận thông tin khách hàng, yêu cầu và tài liệu đầu vào đã được rà để kỹ thuật làm việc. Hệ thống sẽ báo Admin và quản lý kinh doanh, kỹ thuật, giá để phân công.':stage==='technical'?'Xác nhận cấu thành, kích thước, công đoạn và định mức đã khai xong. Hệ thống sẽ báo cho người phụ trách giá vật tư và người duyệt.':'Xác nhận giá vật tư trên bản đã lưu đã được rà và cập nhật xong. Hệ thống sẽ báo cho người duyệt giá.'}</p><p>Báo giá ${esc(db.quote.id)} · phiên bản ${link.version}. Xác nhận sẽ khóa phần việc này. Muốn sửa cần mở sửa và ghi lý do; xác nhận không tự duyệt báo giá.</p>${b1Area('Ghi chú bàn giao','note')}`,'Xác nhận và gửi thông báo',async f=>{if(generation!==Team.sessionGeneration||teamCurrent()?.id!==link.id)throw Error('Phiên làm việc đã đổi');const response=await teamApi('quotes/'+link.id+'/handoff/'+stage,'POST',{expectedVersion:link.version,note:f.get('note')});closeDialog();await noticeRefresh();toast(response.duplicate?'Phần này đã xác nhận; không gửi trùng':'Đã xác nhận và gửi thông báo cho '+response.recipients+' tài khoản');});
}
function noticeReopen(stage){const link=teamCurrent(),generation=Team.sessionGeneration;
 if(!link||link.readOnly||link.status!=='draft')throw Error('Bản đã khóa. Người có quyền cần tạo bản sửa trước.');
 if(Team.dirty)throw Error('Lưu hoặc hoàn tác thay đổi đang làm trước khi mở sửa.');
 teamDialog('Mở khóa để sửa phần đã xác nhận',`<p>Phần này và các phần phía sau sẽ cần xác nhận lại. Lý do được ghi vào lịch sử và thông báo đến người phụ trách.</p>${b1Area('Lý do thay đổi (bắt buộc)','reason')}`,'Mở sửa và thông báo',async f=>{
  const reason=String(f.get('reason')||'').trim();if(!reason)throw Error('Nhập lý do thay đổi');
  if(generation!==Team.sessionGeneration||teamCurrent()?.id!==link.id)throw Error('Phiên làm việc đã đổi');
  await teamApi('quotes/'+link.id+'/handoff/'+stage+'/reopen','POST',{expectedVersion:link.version,reason});closeDialog();await noticeRefresh();render();toast('Đã mở sửa và ghi nhận lý do. Các phần liên quan cần xác nhận lại.');
 });
}
function installNotificationsUI(){
 document.addEventListener('pointerdown',e=>{if(!e.isTrusted||e.target.closest('[data-notice=sound],[data-notice=test-sound]'))return;if(Team.user&&NoticeSound.enabled&&!noticeSoundReady())noticeSoundUnlock().then(()=>noticePaint());},{passive:true});
 document.addEventListener('keydown',e=>{if(e.isTrusted&&Team.user&&NoticeSound.enabled&&!noticeSoundReady()&&!e.target.closest('[data-notice=sound],[data-notice=test-sound]'))noticeSoundUnlock().then(()=>noticePaint());});
 window.addEventListener('storage',e=>{if(e.key===NoticeSound.key){noticeSoundPreference();noticePaint();}});
 const renderBefore=render;render=()=>{renderBefore();noticePaint();};
 const load=teamLoad;teamLoad=async(...args)=>{await load(...args);await noticeRefresh();};const save=teamSave;teamSave=async(...args)=>{await save(...args);await noticeRefresh();};
 const session=teamSession;teamSession=value=>{session(value);Notices.items=[];Notices.unread=0;Notices.state=null;Notices.quoteId=null;Notices.error='';Notices.seen=null;Notices.request=0;Notices.applied=0;noticeSoundPreference();noticePaint();if(Team.user)noticeRefresh();};
 setInterval(()=>{if(Team.user)noticeRefresh();},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Team.user)noticeRefresh();});
 document.addEventListener('click',e=>{const el=e.target.closest('[data-notice]');if(!el)return;e.preventDefault();Promise.resolve().then(async()=>{const action=el.dataset.notice;if(action==='my-work')await noticeMyWork();if(action==='work')await noticeWorkEdit();if(action==='sound')await noticeSoundToggle();if(action==='test-sound')await noticeSoundToggle(true);if(action==='inbox')await noticeInbox();if(action==='refresh')await noticeRefresh();if(action==='reopen')noticeReopen(el.dataset.stage);if(action==='confirm')noticeConfirm(el.dataset.stage);if(action==='read'){await teamApi('notifications/'+el.dataset.id+'/read','POST',{});await noticeInbox();}if(action==='open'){const n=Notices.items.find(n=>n.id===el.dataset.id);if(!n)throw Error('Tải lại danh sách thông báo');if(Team.dirty)throw Error('Lưu báo giá đang sửa trước khi mở thông báo');if(n.stage.startsWith('offer-')){await offerFollowupOpen(n.quoteId,n.quoteVersion);await teamApi('notifications/'+n.id+'/read','POST',{});await noticeRefresh();return;}await teamLoad(n.quoteId);page='quote';tab=['created','intake','assigned-technical'].includes(n.stage)?'intake':['technical','assigned-materials','price-review'].includes(n.stage)?'prices':'pricing';Intake.priceTab=n.stage==='price-review'?'operations':'materials';render();await teamApi('notifications/'+n.id+'/read','POST',{});await noticeRefresh();}}).catch(e=>toast(e.message));});
}
