'use strict';
const Notices={items:[],unread:0,state:null,quoteId:null,error:'',seen:null,request:0,applied:0};
// Sound stays in this browser; no microphone, OS notification or external audio permission.
const NoticeSound={context:null,enabled:true,key:''};
function noticeSoundPreference(){NoticeSound.key='tp-notice-sound:'+String(Team.user?.id??Team.user?.username??'');try{NoticeSound.enabled=localStorage.getItem(NoticeSound.key)!=='off';}catch(_){NoticeSound.enabled=true;}}
function noticeSoundReady(){return NoticeSound.enabled&&NoticeSound.context?.state==='running';}
async function noticeSoundUnlock(){
 if(!Team.user||!NoticeSound.enabled)return false;
 try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return false;if(!NoticeSound.context||NoticeSound.context.state==='closed'){NoticeSound.context=new Audio();NoticeSound.context.onstatechange=()=>noticePaint();}if(NoticeSound.context.state!=='running')await NoticeSound.context.resume();return noticeSoundReady();}catch(_){return false;}
}
function noticeSoundPlay(){
 if(!Team.user||!noticeSoundReady())return false;
 try{const ctx=NoticeSound.context,now=ctx.currentTime;for(const [offset,hz] of [[0,880],[.2,1174.66]]){const oscillator=ctx.createOscillator(),gain=ctx.createGain();oscillator.type='sine';oscillator.frequency.value=hz;gain.gain.setValueAtTime(0,now+offset);gain.gain.linearRampToValueAtTime(.16,now+offset+.02);gain.gain.exponentialRampToValueAtTime(.001,now+offset+.35);oscillator.connect(gain);gain.connect(ctx.destination);oscillator.start(now+offset);oscillator.stop(now+offset+.38);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();};}document.dispatchEvent(new CustomEvent('tp-notification-chime'));return true;}catch(_){return false;}
}
async function noticeSoundToggle(test=false){
 const generation=Team.sessionGeneration;
 if(!test&&noticeSoundReady()){NoticeSound.enabled=false;try{localStorage.setItem(NoticeSound.key,'off');}catch(_){}noticePaint();return;}
 NoticeSound.enabled=true;try{localStorage.setItem(NoticeSound.key,'on');}catch(_){}
 const ready=await noticeSoundUnlock();if(generation!==Team.sessionGeneration)return;noticePaint();if(ready)noticeSoundPlay();else toast('Chưa phát được âm thanh. Bấm Bật chuông và kiểm tra âm lượng hoặc trạng thái tắt tiếng của tab.');
}
function noticeNewItems(items){
 const ids=items.map(n=>String(n.id));if(Notices.seen===null){Notices.seen=new Set(ids);return;}
 const fresh=items.filter(n=>!n.readAt&&!Notices.seen.has(String(n.id)));for(const id of ids)Notices.seen.add(id);if(Notices.seen.size>600)Notices.seen=new Set([...Notices.seen].slice(-400));if(!fresh.length)return;
 // Share only notification IDs across tabs, to avoid duplicate rings on the same browser.
 const key=NoticeSound.key+':alerted';let alerted=[];try{const saved=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(saved))alerted=saved.map(String);}catch(_){}
 const unseen=fresh.filter(n=>!alerted.includes(String(n.id)));if(!unseen.length)return;
 try{localStorage.setItem(key,JSON.stringify([...alerted,...unseen.map(n=>String(n.id))].slice(-400)));}catch(_){}
 noticeSoundPlay();toast('Có '+unseen.length+' thông báo công việc mới. Mở Thông báo để xem.');
 const button=document.querySelector('[data-notice=inbox]');if(button){button.classList.remove('notice-arrived');void button.offsetWidth;button.classList.add('notice-arrived');}
}
const noticeLabel=stage=>stage==='intake'?'Đầu vào báo giá đã xác nhận — cần kỹ thuật xử lý':stage==='created'?'Báo giá mới — cần kỹ thuật nhập dữ liệu':stage==='technical'?'Kỹ thuật đã xác nhận hoàn tất — cần cập nhật giá vật tư':'Vật tư đã cập nhật giá — cần phê duyệt giá';
const noticeIntake=()=>Team.permissions?.edit&&Team.permissions.sections.includes('customer');
const noticeTechnical=()=>Team.permissions?.edit&&Team.permissions.sections.some(s=>['bom','operations'].includes(s));
const noticeMaterials=()=>Team.permissions?.edit&&Team.permissions.costs&&Team.permissions.sections.includes('materials');
function noticePanel(){const link=teamCurrent();if(!Team.user||!link||link.readOnly||page!=='quote'||!(Team.permissions?.costs||Team.permissions?.technical))return '';const state=Notices.quoteId===link.id?Notices.state:null,editable=link.status==='draft',line=(s,label)=>`<div><strong>${label}</strong><span>${s?`${s.current?'Đã xác nhận':'Dữ liệu đã đổi — cần xác nhận lại'} · ${esc(s.actor)} · v${s.quoteVersion} · ${esc(new Date(s.at).toLocaleString('vi-VN'))}`:'Chưa xác nhận'}</span></div>`;
 return `<section class="panel notification-handoff" data-notice-panel><div><h3>Xác nhận & bàn giao</h3><p>Xác nhận phần việc đã hoàn tất để báo cho bộ phận tiếp theo. Việc duyệt báo giá vẫn thực hiện riêng.</p></div>${state?line(state.intake,'Đầu vào báo giá')+line(state.technical,'Kỹ thuật')+line(state.materials,'Giá vật tư'):'<p>Đang tải trạng thái bàn giao…</p>'}${state&&state.quoteVersion!==link.version?'<p class="cell-error">Máy chủ có phiên bản mới. Tải lại báo giá trước khi xác nhận.</p>':''}${Notices.error?`<p class="cell-error">${esc(Notices.error)} ${noticeButton('Tải lại','refresh')}</p>`:''}<div class="actions">${editable&&noticeIntake()?noticeButton('Xác nhận dữ liệu đầu vào','confirm','intake'):''}${editable&&noticeTechnical()?noticeButton('Xác nhận hoàn tất kỹ thuật','confirm','technical'):''}${editable&&noticeMaterials()?noticeButton('Xác nhận đã cập nhật giá vật tư','confirm','materials'):''}</div><p class="help-text">Tạo báo giá → kỹ thuật nhập dữ liệu. Kỹ thuật → tài khoản phụ trách giá vật tư và người duyệt. Vật tư → người duyệt. Thông báo lưu trong mục Thông báo ở thanh trên.</p></section>`;
}
function noticeButton(label,action,stage=''){return `<button type="button" class="button small" data-notice="${action}" data-stage="${stage}">${label}</button>`;}
function noticePaint(){let button=document.querySelector('[data-notice=inbox]');if(!Team.user){document.querySelector('[data-notice=sound]')?.remove();button?.remove();document.querySelector('[data-notice-panel]')?.remove();return;}if(!button){button=document.createElement('button');button.type='button';button.className='button small';button.dataset.notice='inbox';document.querySelector('.top-actions')?.prepend(button);}button.textContent='Thông báo'+(Notices.unread?' ('+Notices.unread+')':'');button.setAttribute('aria-label','Thông báo, '+Notices.unread+' chưa đọc');
 let sound=document.querySelector('.top-actions [data-notice=sound]');if(!sound){sound=document.createElement('button');sound.type='button';sound.className='button small notice-sound';sound.dataset.notice='sound';button.insertAdjacentElement('afterend',sound);}sound.textContent=noticeSoundReady()?'Chuông: bật':NoticeSound.enabled?'Bật chuông':'Chuông: tắt';sound.setAttribute('aria-pressed',String(noticeSoundReady()));sound.title=noticeSoundReady()?'Tắt âm thanh thông báo':'Bật và nghe thử âm thanh thông báo';
 const panel=document.querySelector('[data-notice-panel]'),html=noticePanel();if(panel)panel.outerHTML=html;else document.querySelector('.team-banner')?.insertAdjacentHTML('afterend',html);
}
async function noticeRefresh(){if(!Team.user)return;const generation=Team.sessionGeneration,id=teamCurrent()?.id,request=++Notices.request;try{const [inbox,state]=await Promise.all([teamApi('notifications'),id&&(!Team.permissions?.costs&&!Team.permissions?.technical)?null:id?teamApi('quotes/'+id+'/handoff'):null]);if(generation!==Team.sessionGeneration||request<Notices.applied)return;Notices.applied=request;Notices.items=inbox.items;Notices.unread=inbox.unread;Notices.error='';if(id===teamCurrent()?.id){Notices.quoteId=id;Notices.state=state;}noticePaint();noticeNewItems(inbox.items);}catch(e){if(generation===Team.sessionGeneration&&request>=Notices.applied){Notices.error=e.message;noticePaint();}}}
async function noticeInbox(){await noticeRefresh();openDialog('Thông báo công việc',`${Notices.error?`<p class="cell-error">${esc(Notices.error)}</p>`:''}<div class="notice"><p>Chuông báo khi có thông báo mới trong lúc đang mở web. Thông báo cũ không reo lại khi tải trang. Trình duyệt có thể yêu cầu bấm Bật chuông trước.</p><div class="actions">${noticeButton('Nghe thử / bật chuông','test-sound')}</div></div><p>${Notices.unread} thông báo chưa đọc. Hiển thị tối đa 200 thông báo gần nhất.</p><div class="notification-list">${Notices.items.map(n=>`<article class="${n.readAt?'':'notification-unread'}"><strong>${esc(n.code)} · ${esc(noticeLabel(n.stage))}</strong><p>${esc(n.actor)} · ${esc(new Date(n.at).toLocaleString('vi-VN'))} · phiên bản ${n.quoteVersion}</p>${n.note?`<p>${esc(n.note)}</p>`:''}<div class="actions"><button type="button" class="button small" data-notice="open" data-id="${n.id}">Mở báo giá</button>${!n.readAt?`<button type="button" class="button small" data-notice="read" data-id="${n.id}">Đánh dấu đã đọc</button>`:'<span>Đã đọc</span>'}</div></article>`).join('')||'<p>Chưa có thông báo.</p>'}</div><p class="help-text">Thông báo ghi nhận thời điểm bàn giao. Mở báo giá sẽ lấy bản hiện tại và kiểm tra lại trạng thái xác nhận.</p>`);$('#dialog').classList.add('wide-dialog');}
function noticeConfirm(stage){const link=teamCurrent();if(!link||link.readOnly||link.status!=='draft')throw Error('Mở bản nháp hiện tại trước khi xác nhận');if(Team.dirty)throw Error('Bấm Lưu máy chủ trước, sau đó xác nhận phần việc');if(!(stage==='intake'?noticeIntake():stage==='technical'?noticeTechnical():noticeMaterials()))throw Error('Chưa có quyền xác nhận phần này');const generation=Team.sessionGeneration;
 teamDialog(stage==='intake'?'Xác nhận đầu vào báo giá':stage==='technical'?'Xác nhận hoàn tất kỹ thuật':'Xác nhận đã cập nhật giá vật tư',`<p>${stage==='intake'?'Xác nhận thông tin khách hàng, yêu cầu và tài liệu đầu vào đã được rà để kỹ thuật làm việc. Hệ thống sẽ báo cho bộ phận kỹ thuật.':stage==='technical'?'Xác nhận cấu thành, kích thước, công đoạn và định mức đã khai xong. Hệ thống sẽ báo cho người phụ trách giá vật tư và người duyệt.':'Xác nhận giá vật tư trên bản đã lưu đã được rà và cập nhật xong. Hệ thống sẽ báo cho người duyệt giá.'}</p><p>Báo giá ${esc(db.quote.id)} · phiên bản ${link.version}. Xác nhận không tự duyệt báo giá.</p>${b1Area('Ghi chú bàn giao','note')}`,'Xác nhận và gửi thông báo',async f=>{if(generation!==Team.sessionGeneration||teamCurrent()?.id!==link.id)throw Error('Phiên làm việc đã đổi');const response=await teamApi('quotes/'+link.id+'/handoff/'+stage,'POST',{expectedVersion:link.version,note:f.get('note')});closeDialog();await noticeRefresh();toast(response.duplicate?'Phần này đã xác nhận; không gửi trùng':'Đã xác nhận và gửi thông báo cho '+response.recipients+' tài khoản');});
}
function installNotificationsUI(){
 document.addEventListener('pointerdown',e=>{if(!e.isTrusted||e.target.closest('[data-notice=sound],[data-notice=test-sound]'))return;if(Team.user&&NoticeSound.enabled&&!noticeSoundReady())noticeSoundUnlock().then(()=>noticePaint());},{passive:true});
 document.addEventListener('keydown',e=>{if(e.isTrusted&&Team.user&&NoticeSound.enabled&&!noticeSoundReady()&&!e.target.closest('[data-notice=sound],[data-notice=test-sound]'))noticeSoundUnlock().then(()=>noticePaint());});
 window.addEventListener('storage',e=>{if(e.key===NoticeSound.key){noticeSoundPreference();noticePaint();}});
 const renderBefore=render;render=()=>{renderBefore();noticePaint();};
 const load=teamLoad;teamLoad=async(...args)=>{await load(...args);await noticeRefresh();};const save=teamSave;teamSave=async(...args)=>{await save(...args);await noticeRefresh();};
 const session=teamSession;teamSession=value=>{session(value);Notices.items=[];Notices.unread=0;Notices.state=null;Notices.quoteId=null;Notices.error='';Notices.seen=null;Notices.request=0;Notices.applied=0;noticeSoundPreference();noticePaint();if(Team.user)noticeRefresh();};
 setInterval(()=>{if(Team.user)noticeRefresh();},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&Team.user)noticeRefresh();});
 document.addEventListener('click',e=>{const el=e.target.closest('[data-notice]');if(!el)return;e.preventDefault();Promise.resolve().then(async()=>{const action=el.dataset.notice;if(action==='sound')await noticeSoundToggle();if(action==='test-sound')await noticeSoundToggle(true);if(action==='inbox')await noticeInbox();if(action==='refresh')await noticeRefresh();if(action==='confirm')noticeConfirm(el.dataset.stage);if(action==='read'){await teamApi('notifications/'+el.dataset.id+'/read','POST',{});await noticeInbox();}if(action==='open'){const n=Notices.items.find(n=>n.id===el.dataset.id);if(!n)throw Error('Tải lại danh sách thông báo');if(Team.dirty)throw Error('Lưu báo giá đang sửa trước khi mở thông báo');await teamLoad(n.quoteId);page='quote';tab=['created','intake'].includes(n.stage)?'intake':n.stage==='technical'?'prices':'pricing';Intake.priceTab='materials';render();await teamApi('notifications/'+n.id+'/read','POST',{});await noticeRefresh();}}).catch(e=>toast(e.message));});
}
