'use strict';
const OpsERP={tab:'jobs',data:null,job:null,epoch:0};
function opsRemnantFields(i){return '<fieldset><legend>Mảnh dư '+(i+1)+'</legend>'+field('Số lượng','quantity'+i,0,'number','min="0" step="1"')+field('Khối lượng mỗi mảnh kg','unitWeight'+i,0,'number','min="0" step="any"')+['length','width','thickness'].map((k,n)=>field(['Dài mm','Rộng mm','Dày mm'][n],k+i,0,'number','min="0" step="any"')).join('')+'</fieldset>';}
function opsReturnDialog(id){let count=1;teamDialog('Hoàn dư và cân đối khối lượng',field('Khối lượng sản phẩm kg','productWeight',0,'number','min="0" step="any"')+field('Phế kg','scrapWeight',0,'number','min="0" step="any"')+'<div id="ops-remnant-rows">'+opsRemnantFields(0)+'</div><button type="button" id="ops-add-remnant">+ Kích thước mảnh dư khác</button>','Quyết toán',async f=>{const b=Object.fromEntries(f),remnants=[];for(let i=0;i<count;i++)if(Number(b['quantity'+i]))remnants.push(Object.fromEntries(['quantity','unitWeight','length','width','thickness'].map(k=>[k,Number(b[k+i])])));await opsSave('return',{holdId:id,productWeight:Number(b.productWeight),scrapWeight:Number(b.scrapWeight),remnants});});$('#ops-add-remnant').onclick=()=>{if(count<100)$('#ops-remnant-rows').insertAdjacentHTML('beforeend',opsRemnantFields(count++));};}
const opsLabels={jobs:'Lệnh & vật tư',board:'Điều hành xưởng',material:'Vật tư',lot:'Kho tấm / lô',movement:'Nhập xuất tồn',supplier:'Nhà cung cấp',purchase:'Mua hàng',operation:'Công đoạn',machine:'Máy / năng lực',task:'Giao việc',report:'Báo cáo ngày',pending:'Chờ duyệt',approved:'Đã duyệt',rejected:'Từ chối',ordered:'Đã đặt',shipping:'Đang giao',received:'Đã nhận',stocked:'Đã nhập kho',reserved:'Đang giữ',issued:'Đã cấp',settled:'Đã quyết toán',released:'Đã bỏ giữ'};
const opsScope={jobs:'production',board:'workshop',material:'inventory',lot:'inventory',movement:'inventory',supplier:'purchasing',purchase:'purchasing',operation:'workshop',machine:'workshop',task:'dailyWork',report:'dailyWork'};
function opsApplyFilters(){const query=($('#ops-filter')?.value||'').toLocaleLowerCase('vi'),from=$('#ops-from')?.value||'',to=$('#ops-to')?.value||'';for(const r of document.querySelectorAll('[data-ops-row]')){const day=r.textContent.match(/\d{4}-\d{2}-\d{2}/)?.[0]||'';r.hidden=!r.textContent.toLocaleLowerCase('vi').includes(query)||(from&&(!day||day<from))||(to&&(!day||day>to));}const count=$('#ops-visible-count');if(count)count.textContent=document.querySelectorAll('[data-ops-row]:not([hidden])').length+' dòng phù hợp';}
const oe=x=>esc(String(x??'')),on=x=>Number(x||0).toLocaleString('vi-VN',{maximumFractionDigits:3});
const ob=(label,action,id='')=>`<button type="button" class="button" data-ops="${action}" data-id="${oe(id)}">${label}</button>`;
const opCan=(scope,action)=>Team.user?.role==='admin'||OpsERP.data?.permissions?.[scope]?.[action];
const opSelect=(label,name,rows,value='',optional=true)=>select(label,name,[...(optional?[['','Chọn']]:[]),...rows.map(r=>[r.id,r.name||r.code])],value,optional?'':'required');
async function opsOpen(tab=OpsERP.tab,id){const epoch=++OpsERP.epoch,generation=Team.sessionGeneration;const data=await teamApi('ops/state');if(epoch!==OpsERP.epoch||generation!==Team.sessionGeneration)return;OpsERP.data=data;OpsERP.tab=tab;OpsERP.job=id?await teamApi('ops/job/'+id):null;if(epoch!==OpsERP.epoch||generation!==Team.sessionGeneration)return;page='operationsERP';render();$('#sidebar').classList.remove('open');}
async function opsSave(route,body){const form=document.querySelector('#dialog[open] form');const requestId=form?(form.dataset.opsRequest||(form.dataset.opsRequest=crypto.randomUUID())):crypto.randomUUID();await teamApi('ops/'+route,'POST',{requestId,...body});closeDialog();await opsOpen(OpsERP.tab,OpsERP.job?.jobId);toast('Đã lưu lên máy chủ');}
function opsTable(headers,rows){return '<div class="table-scroll"><table><thead><tr>'+headers.map(h=>'<th>'+oe(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr data-ops-row>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function opsRender(){const d=OpsERP.data;if(!d)return heading('Sản xuất, kho & mua hàng','Đang tải');const tab=OpsERP.tab,can=a=>opCan(opsScope[tab],a),nav=Object.keys(opsScope).filter(k=>k==='jobs'?actionCan('production','view'):opCan(opsScope[k],'view')).map(k=>ob(opsLabels[k],'tab',k)).join('');let body='',actions='';
 const names=(rows,id)=>rows?.find(r=>r.id===id)?.name||id,people=id=>names(d.people,id),jobName=id=>d.jobs?.find(j=>j.id===id)?.code||id;
 if(OpsERP.job)return heading('Vật tư & công việc · '+OpsERP.job.code,'Kiểm tra nhu cầu → giữ kho → cấp khi bắt đầu sản xuất → quyết toán phần dư/phế')+'<div class="actions">'+ob('← Danh sách','tab','jobs')+ob('Mở lệnh sản xuất','production',OpsERP.job.jobId)+ob('In đối chiếu','print')+'</div>'+opsJobRender();
 if(tab==='jobs')body=opsTable(['Lệnh / sản phẩm','Trạng thái / hạn','Xưởng','Thao tác'],(d.jobs||[]).map(j=>['<strong>'+oe(j.code)+'</strong><br>'+oe(j.product),oe(productionStatus[j.state])+'<br>'+oe(j.deadline)+(j.deadline&&j.deadline<TPComplete.todayVN()&&j.state!=='completed'?' <strong>⚠ Trễ hạn</strong>':''),oe(j.workshop),ob('Vật tư & công việc','job',j.id)+ob('Mở lệnh','production',j.id)]));
 if(tab==='material'){actions=can('create')?ob('+ Vật tư','edit','material'):'';body=opsTable(['Mã / tên','Nhóm / vị trí','Đơn vị','Tồn / tối thiểu','Trạng thái','Thao tác'],(d.materials||[]).map(m=>{const q=d.lots.filter(l=>l.materialId===m.id).reduce((s,l)=>s+l.quantity,0);return ['<strong>'+oe(m.code)+'</strong><br>'+oe(m.name),oe(m.group)+' / '+oe(m.warehouse),oe(m.unit),on(q)+' / '+on(m.minimum),q<=0?'🔴 Hết hàng':q<=m.minimum?'⚠ Sắp hết':'✓ Đủ tồn',ob('Chi tiết','material-detail',m.id)+(can('edit')?ob('Sửa','edit','material:'+m.id):'')+(can('delete')?ob('Xóa','delete','material:'+m.id):'')];}));}
 if(tab==='lot'){actions=can('create')?ob('+ Nhập kho','receipt'):'';body=opsTable(['Lô / nguồn','Vật tư / kho','Kích thước mm','Số lượng / giữ / khả dụng','Khối lượng kg','Thao tác'],(d.lots||[]).map(l=>[oe(l.id.slice(0,8))+'<br>Gốc: '+oe(l.rootLotId.slice(0,8))+(l.sourceLotId?'<br>Từ: '+oe(l.sourceLotId.slice(0,8)):''),oe(l.materialName)+'<br>'+oe(l.warehouse),[l.length,l.width,l.thickness].map(on).join(' × '),[l.quantity,l.reserved,l.available].map(on).join(' / ')+' '+oe(l.unit),on(l.quantity*l.unitWeight),can('edit')?ob('Xuất thủ công','issue',l.id):'']));}
 if(tab==='movement'){actions=can('create')?ob('+ Nhập kho','receipt'):'';const warehouses=[...new Set((d.lots||[]).map(l=>l.warehouse))];body=opsTable(['Kho','Số mã / dưới mức tối thiểu','Giá trị tồn'],warehouses.map(w=>{const ls=d.lots.filter(l=>l.warehouse===w),ids=[...new Set(ls.map(l=>l.materialId))];return [oe(w),ids.length+' / '+ids.filter(id=>ls.filter(l=>l.materialId===id).reduce((s,l)=>s+l.quantity,0)<=(d.materials.find(m=>m.id===id)?.minimum||0)).length,ls.some(l=>l.unitCost===undefined)?'Theo quyền':on(ls.reduce((s,l)=>s+l.quantity*l.unitCost,0))];}))+opsTable(['Ngày','Loại / chứng từ','Vật tư / kho','Lượng','Khối lượng','Giá trị','Nguồn / người'],(d.movements||[]).map(m=>[oe(m.at.slice(0,10)),oe(m.kind)+'<br>'+oe(m.reference),oe(m.materialId)+' / '+oe(m.warehouse),on(m.quantity),on(m.weight),m.value===undefined?'—':on(m.value),oe(jobName(m.jobId||''))+'<br>'+oe(m.actorName)]));}
 if(tab==='supplier'){actions=can('create')?ob('+ Nhà cung cấp','edit','supplier'):'';body=opsTable(['Mã / nhà cung cấp','MST / địa chỉ','Liên hệ','Bảng giá / lịch sử','Thao tác'],(d.suppliers||[]).map(s=>[oe(s.code)+'<br><strong>'+oe(s.name)+'</strong>',oe(s.taxId)+'<br>'+oe(s.address),oe(s.contact)+'<br>'+oe(s.phone),ob('Giá & mua hàng','supplier-detail',s.id),(can('edit')?ob('Sửa','edit','supplier:'+s.id):'')+(can('delete')?ob('Xóa','delete','supplier:'+s.id):'')]));}
 if(tab==='purchase'){body=opsTable(['Yêu cầu / nguồn','Nhà cung cấp','Trạng thái','Giá trị','Thao tác'],(d.purchases||[]).map(p=>[oe(p.code)+'<br>'+oe(jobName(p.jobId)),oe(p.supplierName)+'<br>'+oe(p.created.slice(0,10)),oe(opsLabels[p.state]),p.lines.some(l=>l.unitCost===undefined)?'—':on(p.lines.reduce((s,l)=>s+l.quantity*l.unitCost,0)),ob('Chi tiết / xử lý','purchase-detail',p.id)]));actions='<p>Tạo yêu cầu mua từ màn Vật tư & công việc của lệnh để tính phần thiếu, trừ các yêu cầu đang mua.</p>';}
 if(tab==='operation'||tab==='machine'){const rows=tab==='operation'?d.operations:d.machines;actions=can('create')?ob('+ '+opsLabels[tab],'edit',tab):'';body=opsTable(['Mã / tên','Xưởng','Thông tin','Đang sử dụng','Thao tác'],(rows||[]).map(o=>[oe(o.code)+'<br>'+oe(o.name),oe(o.workshop),tab==='machine'?on(o.hoursPerDay)+' giờ/ngày':oe(names(d.machines,o.machineId))+(can('edit')&&o.hourRate!==undefined?'<input type="number" min="0" step="any" aria-label="Giá giờ máy" data-ops-rate="'+o.id+'" value="'+o.hourRate+'">'+ob('Lưu giá','quick-rate',o.id):'<br>'+on(o.hourRate))+' đ/giờ',new Set([...(d.jobs||[]).filter(j=>j.state!=='completed'&&j.operations.some(p=>tab==='operation'?(p.catalogId===o.id||o.rateId&&p.rateId===o.rateId):p.machine===o.id)).map(j=>j.id),...(d.tasks||[]).filter(t=>(tab==='machine'?t.machineId:t.operationId)===o.id&&t.state!=='done').map(t=>t.jobId)]).size,(can('edit')?ob('Sửa','edit',tab+':'+o.id):'')+(tab==='operation'?ob('Hệ số','factors',o.id):'')+(can('delete')?ob('Xóa','delete',tab+':'+o.id):'')]));}
 if(tab==='board'){body=opsTable(['Máy / xưởng','Ngày','Giờ đã dùng / công suất','Cảnh báo'],(d.machines||[]).flatMap(m=>[...new Set((d.reports||[]).filter(r=>r.machineId===m.id).map(r=>r.date).concat(TPComplete.todayVN()))].map(day=>{const h=d.reports.filter(r=>r.machineId===m.id&&r.date===day).reduce((s,r)=>s+r.hours,0);return [oe(m.name)+' / '+oe(m.workshop),oe(day),on(h)+' / '+on(m.hoursPerDay),h>m.hoursPerDay?'⚠ Quá tải':'✓ Trong năng lực'];})))+opsTable(['Lệnh','Xưởng / hạn','Công đoạn','Tiến độ'],(d.jobs||[]).filter(j=>j.state!=='completed').flatMap(j=>(j.operations||[]).map(o=>[oe(j.code),oe(j.workshop)+' / '+oe(j.deadline)+(j.deadline&&j.deadline<TPComplete.todayVN()?' ⚠ Trễ hạn':''),oe(o.name||o.id)+'<br>'+oe(people(o.assignee)),oe(productionStatus[o.status])+' / '+on(o.output)])));}
 if(tab==='task'){actions=can('assign')?ob('+ Giao công việc','edit','task'):'';body=opsTable(['Đầu mục / lệnh','Người / máy','Bắt đầu / hạn','Trạng thái','Thao tác'],(d.tasks||[]).map(t=>[oe(t.name)+'<br>'+oe(jobName(t.jobId)),oe(people(t.assignee))+' / '+oe(names(d.machines,t.machineId)),oe(t.startDate)+' / '+oe(t.dueDate),oe(productionStatus[t.state]||t.state),(can('assign')?ob('Sửa','edit','task:'+t.id):'')+(can('edit')&&(Team.user.id===t.assignee||Team.user.role==='admin')?ob('Báo cáo ngày','report',t.id):'')]));}
 if(tab==='report')body=opsTable(['Ngày / người','Lệnh / công việc','Giờ / sản lượng','Nội dung','Vướng mắc / xử lý'],(d.reports||[]).map(r=>[oe(r.date)+'<br>'+oe(r.actorName),oe(jobName(r.jobId))+'<br>'+oe(names(d.tasks,r.taskId)),on(r.hours)+' / '+on(r.output),oe(r.content),oe(r.issue)+(r.resolved?'<br>✓ '+oe(r.resolution):r.issue&&can('edit')?ob('Xử lý','resolve',r.id):'')]));
 return heading('Sản xuất · Kho · Mua hàng','Chứng từ và tiến độ từ dữ liệu vận hành thực tế')+'<div class="actions">'+nav+'</div><section class="panel business-panel"><h2>'+opsLabels[tab]+'</h2><div class="actions">'+actions+(can('export')?ob('Xuất Excel bảng đang lọc','export'):'')+ob('In','print')+'</div><label>Lọc tên, mã, xưởng, kho, người hoặc tháng (YYYY-MM)<input id="ops-filter" placeholder="Nhập từ khóa"></label>'+body+'</section>';
}
function opsJobRender(){const j=OpsERP.job,d=OpsERP.data;return '<section class="panel business-panel"><h2>Nhu cầu vật tư</h2>'+opsTable(['Vật tư','Nhu cầu / đơn vị','Kích thước tối thiểu','Đã giữ / cấp','Khả dụng / thiếu','Thao tác'],j.requirements.map(r=>[oe(r.materialId)+'<br>'+oe(r.name),on(r.quantity)+' '+oe(r.unit),[r.length,r.width,r.thickness].map(on).join(' × '),on(r.assigned),on(r.available)+' / <strong>'+on(r.missing)+'</strong>',(opCan('inventory','edit')?ob('Giữ vật tư','reserve',r.materialId):'')+(opCan('inventory','create')&&!d.materials?.some(m=>m.id===r.materialId)?ob('Khai vật tư kho','demand-material',r.materialId):'')]))+'<div class="actions">'+(opCan('purchasing','create')?ob('Đề nghị mua phần thiếu','purchase'):'' )+'</div><h2>Giữ, cấp và quyết toán</h2>'+opsTable(['Lô / vật tư','Số lượng','Trạng thái','Cân đối kg','Thao tác'],j.holds.map(h=>[oe(h.lotId.slice(0,8))+' / '+oe(h.materialId),on(h.quantity),oe(opsLabels[h.state]),h.state==='settled'?on(h.productWeight)+' sản phẩm + '+on(h.remnantWeight)+' dư + '+on(h.scrapWeight)+' phế':'Chưa quyết toán',opCan('inventory','edit')?(h.state==='reserved'?ob('Bỏ giữ','release',h.id):h.state==='issued'?ob('Hoàn dư / phế','return',h.id):''):'' ]))+(j.costs?'<h2>Chi phí thực tế của lệnh</h2>'+opsTable(['Chứng từ','Ngày','Nội dung','Giá trị'],j.costs.map(c=>[oe(c.reference),oe(c.date),oe(c.note),on(c.amount)])):'')+'<h2>Công việc của lệnh</h2>'+opsTable(['Đầu mục','Phụ trách','Hạn','Trạng thái'],j.tasks.map(t=>[oe(t.name),oe(d.people.find(p=>p.id===t.assignee)?.name),oe(t.dueDate),oe(t.state)]))+(opCan('dailyWork','assign')?ob('+ Giao việc','edit','task'):'')+'</section>';}
function opsForm(title,html,save){teamDialog(title,html,'Lưu',async f=>{const b=Object.fromEntries(f);await save(b,f);});}
function opsEdit(kind,id,initial={}){const d=OpsERP.data,key={material:'materials',supplier:'suppliers',operation:'operations',machine:'machines',task:'tasks'}[kind],v=d[key]?.find(x=>x.id===id)||initial;let html='';
 if(kind!=='task')html=field('Mã','code',v.code||'','text','required')+field('Tên','name',v.name||'','text','required');
 if(kind==='material')html+=field('Mã liên kết vật tư báo giá','id',v.id||'','text',v.id?'readonly':'required')+field('Nhóm','group',v.group||'')+field('Đơn vị (tấm / thanh / kg / …)','unit',v.unit||'kg')+select('Dạng','form',[['bulk','Khối lượng / vật tư khác'],['sheet','Tấm'],['bar','Thanh']],v.form||'bulk')+field('Kho / vị trí mặc định','warehouse',v.warehouse||'')+field('Tồn tối thiểu','minimum',v.minimum||0,'number','min="0" step="any"')+field('Giá nhập tham khảo / đơn vị','unitCost',v.unitCost||0,'number','min="0" step="any"');
 if(kind==='supplier')html+=field('Mã số thuế','taxId',v.taxId||'')+field('Địa chỉ','address',v.address||'')+field('Liên hệ','contact',v.contact||'')+field('Điện thoại','phone',v.phone||'');
 if(kind==='machine'||kind==='operation')html+=field('Phân xưởng','workshop',v.workshop||'','text','required');
 if(kind==='machine')html+=field('Năng lực giờ/ngày','hoursPerDay',v.hoursPerDay||8,'number','min="0.1" max="24" step="any"');
 if(kind==='operation')html+=opSelect('Máy','machineId',d.machines||[],v.machineId)+field('Đơn giá giờ máy','hourRate',v.hourRate||0,'number','min="0" step="any"')+field('Mã công đoạn trong báo giá','rateId',v.rateId||'')+b1Area('Thông tin / hướng dẫn','instructions',v.instructions||'',3000);
 if(kind==='task')html+=field('Đầu mục công việc','name',v.name||'','text','required')+opSelect('Lệnh sản xuất','jobId',d.jobs,v.jobId||OpsERP.job?.jobId,false)+opSelect('Người phụ trách','assignee',d.people,v.assignee,false)+opSelect('Công đoạn','operationId',d.operations||[],v.operationId)+opSelect('Máy','machineId',d.machines||[],v.machineId)+field('Ngày bắt đầu','startDate',v.startDate||TPComplete.todayVN(),'date','required')+field('Hạn hoàn thành','dueDate',v.dueDate||TPComplete.todayVN(),'date','required')+field('Giờ dự kiến','plannedHours',v.plannedHours||0,'number','min="0" step="any"');
 if(kind!=='task')html+=select('Trạng thái','active',[['true','Đang sử dụng'],['false','Ngừng sử dụng']],v.active===false?'false':'true');
 opsForm('Khai báo '+opsLabels[kind],html,b=>{if('active' in b)b.active=b.active==='true';for(const k of ['minimum','unitCost','hoursPerDay','hourRate','plannedHours'])if(k in b)b[k]=Number(b[k]);return opsSave(kind==='task'?'task':'master',{kind,expectedVersion:v.version||0,document:{...v,...b}});});}
async function opsAction(action,id){const d=OpsERP.data;if(action==='tab')return opsOpen(id);if(action==='job')return opsOpen('jobs',id);if(action==='production'){productionShell().showModal();Production.people=await chatApi('production/people');await productionLoad();return productionLoad(id);}if(action==='edit'){const [k,i]=id.split(':');return opsEdit(k,i);}if(action==='demand-material'){const r=OpsERP.job.requirements.find(x=>x.materialId===id);return opsEdit('material','',{id:r.materialId,code:r.materialId,name:r.name,unit:r.unit,form:r.unit==='tấm'?'sheet':r.unit==='thanh'?'bar':'bulk'});}
 if(action==='cost')return opsForm('Chi phí thực tế của lệnh',field('Ngày','date',TPComplete.todayVN(),'date','required')+field('Số chứng từ','reference','','text','required')+field('Nhóm chi phí','category','','text','required')+field('Số tiền','amount',0,'number','min="0.01" step="any"')+b1Area('Nội dung','note','',3000),b=>opsSave('cost',{...b,jobId:OpsERP.job.jobId,amount:Number(b.amount)}));
 if(action==='quick-rate'){const o=d.operations.find(x=>x.id===id);return opsSave('master',{kind:'operation',expectedVersion:o.version,document:{...o,hourRate:Number(document.querySelector('[data-ops-rate="'+id+'"]').value)}});}
 if(action==='print'){const clone=(document.querySelector('#dialog[open]')||$('#content')).cloneNode(true);clone.querySelectorAll('button,input,select,textarea').forEach(e=>e.remove());return bsPrint(opsLabels[OpsERP.tab]||'San xuat',clone.innerHTML);}if(action==='export'){const tables=[...document.querySelectorAll('#content table')];return download('san-xuat-kho-'+OpsERP.tab+'.xlsx',TPXlsx.make(tables.map((t,i)=>({name:'Bang '+(i+1),rows:[...t.rows].filter(r=>!r.hidden).map(r=>[...r.cells].map(c=>c.innerText))}))),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');}
 if(action==='delete'){const [kind,key]=id.split(':'),v=d[{material:'materials',supplier:'suppliers',machine:'machines',operation:'operations'}[kind]].find(x=>x.id===key);return opsForm('Xóa '+oe(v.name),'<p>Chỉ xóa danh mục chưa có phát sinh.</p>',()=>opsSave('delete',{kind,id:key,expectedVersion:v.version}));}
 if(action==='receipt')return opsForm('Nhập kho thực tế',opSelect('Vật tư','materialId',d.materials||[],'',false)+field('Kho','warehouse','','text','required')+field('Số lượng','quantity',1,'number','min="0.001" step="any"')+field('Khối lượng mỗi đơn vị (kg)','unitWeight','','number','required min="0.001" step="any"')+field('Giá nhập mỗi đơn vị','unitCost',0,'number','min="0" step="any"')+['length','width','thickness'].map((k,i)=>field(['Dài mm','Rộng mm','Dày mm'][i],k,0,'number','min="0" step="any"')).join('')+field('Số chứng từ','reference','','text','required'),b=>opsSave('receipt',{...b,...Object.fromEntries(['quantity','unitWeight','unitCost','length','width','thickness'].map(k=>[k,Number(b[k])]))}));
 if(action==='issue')return opsForm('Xuất kho thủ công',field('Số lượng','quantity',1,'number','min="0.001" step="any"')+field('Chứng từ','reference','','text','required')+field('Lý do / nơi nhận','note','','text','required'),b=>opsSave('issue',{...b,lotId:id,quantity:Number(b.quantity)}));
 if(action==='reserve'){const r=OpsERP.job.requirements.find(r=>r.materialId===id);return opsForm('Giữ vật tư cho lệnh',opSelect('Lô đủ kích thước','lotId',r.lots.map(l=>({...l,name:l.id.slice(0,8)+' / '+l.warehouse+' / còn '+l.available})),'',false)+field('Số lượng','quantity',r.unassigned,'number','min="0.001" step="any"'),b=>opsSave('reserve',{...b,jobId:OpsERP.job.jobId,quantity:Number(b.quantity)}));}
 if(action==='release')return opsForm('Bỏ giữ vật tư','<p>Trả số lượng đã giữ về tồn khả dụng.</p>',()=>opsSave('release',{id}));
 if(action==='return')return opsReturnDialog(id);
 if(action==='purchase')return opsForm('Đề nghị mua phần thiếu',field('Số yêu cầu','code','','text','required')+opSelect('Nhà cung cấp có bảng giá','supplierId',d.suppliers||[],'',false)+field('Dự phòng thêm %','reservePercent',0,'number','min="0" max="100" step="any"'),b=>opsSave('purchase',{...b,jobId:OpsERP.job.jobId,reservePercent:Number(b.reservePercent)}));
 if(action==='purchase-detail'){const p=d.purchases.find(p=>p.id===id),next={pending:['approved','rejected'],approved:['ordered'],ordered:['shipping'],shipping:['received'],received:['stocked']}[p.state]||[];openDialog('Yêu cầu mua '+oe(p.code),'<p>'+oe(p.supplierName)+' · '+oe(opsLabels[p.state])+'</p>'+opsTable(['Vật tư','Số lượng','Đơn giá'],p.lines.map(l=>[oe(l.name),on(l.quantity)+' '+oe(l.unit),l.unitCost===undefined?'—':on(l.unitCost)]))+'<div class="actions">'+next.filter(s=>opCan('purchasing',['approved','rejected'].includes(s)?'approve':'edit')&&(s!=='stocked'||opCan('inventory','create'))).map(s=>ob(opsLabels[s],'purchase-step',p.id+':'+s)).join('')+ob('In yêu cầu / đơn đặt','print')+'</div>'+p.history.map(h=>'<p>'+oe(h.at)+' · '+oe(h.actor)+' · '+oe(opsLabels[h.state])+' '+oe(h.note)+'</p>').join(''));return;}
 if(action==='purchase-step'){const [key,state]=id.split(':'),p=d.purchases.find(p=>p.id===key);return opsForm(opsLabels[state],b1Area('Ghi chú / lý do','note','',2000)+(state==='received'?p.lines.map((l,i)=>'<h3>'+oe(l.name)+' · '+on(l.quantity)+'</h3>'+field('Kho','warehouse'+i,'','text','required')+field('Khối lượng mỗi đơn vị kg','unitWeight'+i,'','number','required min="0.001" step="any"')+['length','width','thickness'].map(k=>field(k+' (mm)',k+i,l[k]||0,'number','min="0" step="any"')).join('')).join(''):''),b=>opsSave('transition',{id:key,state,expectedVersion:p.version,note:b.note,receipts:state==='received'?p.lines.map((l,i)=>({materialId:l.materialId,quantity:l.quantity,warehouse:b['warehouse'+i],...Object.fromEntries(['unitWeight','length','width','thickness'].map(k=>[k,Number(b[k+i])]))})):undefined}));}
 if(action==='supplier-detail'){const s=d.suppliers.find(x=>x.id===id);openDialog('Nhà cung cấp '+oe(s.name),opsTable(['Vật tư','Giá / đơn vị','Ngày giao'],(s.prices||[]).map(p=>[oe(p.materialId),on(p.unitCost),on(p.leadDays)]))+(opCan('purchasing','edit')?ob('Khai / cập nhật giá vật tư','supplier-price',id):'')+'<h3>Lịch sử mua</h3>'+opsTable(['Số yêu cầu','Trạng thái','Ngày'],d.purchases.filter(p=>p.supplierId===id).map(p=>[oe(p.code),oe(opsLabels[p.state]),oe(p.created)])));return;}
 if(action==='supplier-price'){const s=d.suppliers.find(x=>x.id===id);return opsForm('Giá nhà cung cấp',field('Mã vật tư liên kết','materialId','','text','required')+field('Giá mỗi đơn vị','unitCost',0,'number','min="0" step="any"')+field('Số ngày giao','leadDays',1,'number','min="0" max="365"'),b=>opsSave('master',{kind:'supplier',expectedVersion:s.version,document:{...s,prices:[...(s.prices||[]).filter(p=>p.materialId!==b.materialId),{materialId:b.materialId,unitCost:Number(b.unitCost),leadDays:Number(b.leadDays)}]}}));}
 if(action==='material-detail'){const m=d.materials.find(x=>x.id===id);openDialog(oe(m.name),opsTable(['Ngày','Loại','Số lượng','Chứng từ'],d.movements.filter(x=>x.materialId===id).map(x=>[oe(x.at),oe(x.kind),on(x.quantity),oe(x.reference)]))+'<h3>Lệnh sử dụng</h3>'+d.holds.filter(h=>h.materialId===id).map(h=>'<p>'+oe(d.jobs.find(j=>j.id===h.jobId)?.code)+' · '+oe(opsLabels[h.state])+'</p>').join(''));return;}
 if(action==='factors'){const o=d.operations.find(x=>x.id===id);openDialog('Hệ số · '+oe(o.name),opsTable(['Tên','Hệ số'],(o.factors||[]).map(f=>[oe(f.name),on(f.value)]))+(opCan('workshop','edit')?ob('Thêm / sửa hệ số','factor-edit',id):'')+ob('Ma trận hệ số báo giá','quote-factors'));return;}
 if(action==='quote-factors')return fmMatrix();
 if(action==='factor-edit'){const o=d.operations.find(x=>x.id===id);return opsForm('Hệ số công đoạn',field('Tên hệ số','name','','text','required')+field('Giá trị (0 để xóa)','value',1,'number','min="0" step="any"'),b=>opsSave('master',{kind:'operation',expectedVersion:o.version,document:{...o,factors:[...(o.factors||[]).filter(f=>f.name!==b.name),...(Number(b.value)?[{name:b.name,value:Number(b.value)}]:[])]}}));}
 if(action==='report')return opsForm('Báo cáo công việc trong ngày',field('Ngày','date',TPComplete.todayVN(),'date','required')+field('Giờ thực hiện','hours',0,'number','min="0" max="24" step="any"')+field('Sản lượng đạt','output',0,'number','min="0" step="any"')+select('Tiến độ','state',[['running','Đang làm'],['done','Hoàn thành']],'running')+b1Area('Nội dung','content','',3000)+b1Area('Vướng mắc (nếu có)','issue','',3000),b=>opsSave('report',{...b,taskId:id,hours:Number(b.hours),output:Number(b.output)}));
 if(action==='resolve')return opsForm('Xử lý vướng mắc',b1Area('Kết quả xử lý','resolution','',3000),b=>opsSave('resolve',{id,...b}));
}
function installOperationsERP(){const old=render;render=()=>{if(page==='operationsERP'){$('#content').innerHTML=opsRender();$('#page-label').textContent='Sản xuất · Kho · Mua hàng';}else old();let b=$('#ops-nav');if(!b){b=document.createElement('button');b.id='ops-nav';b.textContent='Sản xuất · Kho · Mua hàng';b.onclick=()=>opsOpen().catch(inError);$('#sidebar nav').append(b);}b.hidden=!Team.user||!['inventory','purchasing','workshop','dailyWork'].some(k=>actionCan(k,'view',false));b.style.display=b.hidden?'none':'';};const prior=teamSession;teamSession=v=>{OpsERP.epoch++;OpsERP.data=null;OpsERP.job=null;if(page==='operationsERP')page='quote';return prior(v);};document.addEventListener('click',e=>{const b=e.target.closest('[data-ops]');if(b)opsAction(b.dataset.ops,b.dataset.id).catch(inError);});document.addEventListener('input',e=>{if(e.target.id==='ops-filter'){opsApplyFilters();}});}

const opsBaseJobRender=opsJobRender;opsJobRender=function(){const j=OpsERP.job;return opsBaseJobRender()+(j.baseline?'<section class="panel business-panel"><h2>Dự toán công đoạn từ bản báo giá nguồn</h2>'+opsTable(['Công đoạn','Đối tượng','Định mức','Đơn vị','Giá trị'],j.baseline.map(o=>[oe(o.name),oe(o.object),on(o.quantity),oe(o.unit),on(o.cost)]))+'</section>':'')+(actionCan('costs','create',false)?ob('+ Chi phí thực tế','cost'):'');};

function opsTotals(){const d=OpsERP.data;if(OpsERP.tab==='report'){const groups=new Map();for(const r of d.reports){const key=r.actor+'|'+r.date.slice(0,7);if(!groups.has(key))groups.set(key,{name:r.actorName,month:r.date.slice(0,7),days:new Set(),hours:0,issues:0,open:0});const g=groups.get(key);g.days.add(r.date);g.hours+=r.hours;if(r.issue){g.issues++;if(!r.resolved)g.open++;}}return '<section class="panel business-panel"><h3>Tổng hợp tháng theo nhân sự</h3>'+opsTable(['Nhân sự','Tháng','Ngày báo cáo','Giờ','Số vướng mắc','Chưa xử lý'],[...groups.values()].map(g=>[oe(g.name),oe(g.month),g.days.size,on(g.hours),g.issues,g.open]))+'</section>';}if(OpsERP.tab==='board'){const today=TPComplete.todayVN(),shops=[...new Set(d.machines.map(m=>m.workshop))];return '<section class="panel business-panel"><h3>Năng lực xưởng hôm nay</h3>'+opsTable(['Xưởng','Giờ đã dùng','Công suất giờ','Cảnh báo'],shops.map(w=>{const ms=d.machines.filter(m=>m.workshop===w),cap=ms.reduce((s,m)=>s+m.hoursPerDay,0),hours=d.reports.filter(r=>r.date===today&&ms.some(m=>m.id===r.machineId)).reduce((s,r)=>s+r.hours,0);return [oe(w),on(hours),on(cap),hours>cap?'Quá tải':'Trong năng lực'];}))+'</section>';}if(OpsERP.tab==='movement'&&d.movements.every(m=>m.value!==undefined)){const incoming=d.movements.filter(m=>m.value>0).reduce((s,m)=>s+m.value,0),outgoing=-d.movements.filter(m=>m.value<0).reduce((s,m)=>s+m.value,0);return '<section class="panel business-panel"><strong>Giá trị toàn bộ chứng từ: Nhập / hoàn '+on(incoming)+' - Xuất '+on(outgoing)+' = Tồn '+on(incoming-outgoing)+'</strong></section>';}return '';}
const opsBeforeInstall=installOperationsERP;installOperationsERP=function(){opsBeforeInstall();const prior=render;render=()=>{prior();if(page==='operationsERP'&&!OpsERP.job&&$('#ops-filter')){$('#content').insertAdjacentHTML('beforeend',opsTotals());document.querySelectorAll('#content [data-ops=tab]').forEach(b=>b.classList.toggle('primary',b.dataset.id===OpsERP.tab));if(['jobs','movement','purchase','task','report','board'].includes(OpsERP.tab))$('#ops-filter').parentElement.insertAdjacentHTML('afterend','<div class="form-grid">'+field('Từ ngày','ops-from','','date').replace('name="ops-from"','id="ops-from"')+field('Đến ngày','ops-to','','date').replace('name="ops-to"','id="ops-to"')+'</div><p id="ops-visible-count"></p>');}const low=OpsERP.data?.materials?.filter(m=>OpsERP.data.lots.filter(l=>l.materialId===m.id).reduce((s,l)=>s+l.quantity,0)<=m.minimum).length||0;if($('#ops-nav'))$('#ops-nav').textContent='Sản xuất / Kho / Mua hàng'+(low?' ('+low+' mã sắp hết)':'');};document.addEventListener('change',e=>{if(['ops-from','ops-to'].includes(e.target.id))opsApplyFilters();});};

opsScope.stage='inventory';opsLabels.stage='Phôi / bán thành phẩm / thành phẩm';
const stageOpsRender=opsRender;opsRender=function(){if(OpsERP.tab!=='stage'||!OpsERP.data||OpsERP.job)return stageOpsRender();const d=OpsERP.data;return heading('Kho công đoạn','Phiếu nhập/xuất theo lệnh; số lượng vật lý, chưa định giá thành phẩm')+'<div class="actions">'+ob('Kho vật tư','tab','lot')+ob('Chứng từ kho','tab','movement')+ob('In','print')+'</div><section class="panel business-panel"><h2>Đang lưu kho</h2>'+opsTable(['Lệnh','Loại','Sản phẩm / chi tiết','Kho','Số lượng','ĐVT','Khối lượng kg'],(d.stageStocks||[]).filter(s=>!s.consumedBy).map(s=>[oe(d.jobs.find(j=>j.id===s.jobId)?.code||s.jobId),oe(flowLabel[s.kind]),oe(s.name),oe(s.warehouse),on(s.quantity),oe(s.unit),on(s.weight)]))+'<h2>Phiếu nhập – xuất</h2>'+opsTable(['Ngày','Lệnh','Loại','Kho','Số lượng','ĐVT','Khối lượng kg','Người'],(d.stageMovements||[]).map(m=>[oe(m.at),oe(m.code),m.kind==='issue'?'Xuất':'Nhập',oe(m.warehouse),on(m.quantity),oe(m.unit),on(m.weight),oe(m.actor)]))+'</section>';};
