'use strict';
let OrgData=null,OrgTab='employees';
const orgKinds={department:'Phòng ban',division:'Bộ phận',team:'Tổ',factory:'Nhà máy',board:'Ban'};
function orgPath(id){const out=[],seen=new Set();while(id&&!seen.has(id)){seen.add(id);const d=OrgData.departments.find(d=>d.id===id);if(!d)break;out.unshift(d.name);id=d.parentId;}return out.join(' / ');}
function orgUnits(){const out=[];function visit(parentId,depth){for(const d of OrgData.departments.filter(d=>(d.parentId||null)===parentId)){out.push({...d,depth});visit(d.id,depth+1);}}visit(null,0);return out;}
function orgDescendant(id,parent){const seen=new Set();while(id&&!seen.has(id)){if(id===parent)return true;seen.add(id);id=OrgData.departments.find(d=>d.id===id)?.parentId;}return false;}
function orgUnitActive(id){const seen=new Set();while(id){if(seen.has(id))return false;seen.add(id);const d=OrgData.departments.find(d=>d.id===id);if(!d||!d.active)return false;id=d.parentId;}return true;}
const orgButton=(label,action,id='')=>`<button type="button" class="button small" data-org="${action}" data-id="${esc(id)}">${esc(label)}</button>`;
const orgStages={sales:'Kinh doanh',technical:'Kỹ thuật',materials:'Cập nhật giá',other:'Khác'};
const orgPositions=e=>e.positionIds.map(id=>{const p=OrgData.positions.find(p=>p.id===id),d=OrgData.departments.find(d=>d.id===p?.departmentId);return p?`${orgPath(d?.id)} · ${p.name}${p.manager?' (Quản lý)':''}${!p.active||!orgUnitActive(d?.id)?' — Ngừng áp dụng':''}`:'';}).filter(Boolean);
async function orgOpen(tab=OrgTab){OrgTab=tab;OrgData=await teamApi('organization');const data=OrgData,tools=`<div class="actions">${tab==='employees'?orgButton('Tài khoản đăng nhập','accounts'):orgButton('Phòng ban / tổ / bộ phận','departments')+orgButton('Vị trí làm việc','positions')}</div>`,label={employees:'Nhân sự',departments:'Phòng ban',positions:'Vị trí làm việc'}[tab];
 let rows,headers;
 if(tab==='employees'){headers=['Nhân sự','Phòng ban · Vị trí','Tài khoản / trạng thái',''];rows=data.employees.map(e=>`<tr><td><strong>${esc(e.name)}</strong><small class="subtext">${esc(e.code)}</small><small>${esc([e.phone,e.email].filter(Boolean).join(' · '))}</small></td><td>${orgPositions(e).map(x=>'<div>'+esc(x)+'</div>').join('')||'Chưa bố trí vị trí'}${e.managed?'':'<small class="subtext">Giữ quyền cũ đến khi phân vị trí</small>'}</td><td>${esc(data.users.find(u=>u.id===e.userId)?.username||'Chưa có tài khoản')}<small class="subtext">${e.active?'Đang làm việc':'Ngừng làm việc'}${e.userId&&!data.users.find(u=>u.id===e.userId)?.active?' · Tài khoản đang khóa':''}</small></td><td>${orgButton('Hồ sơ / bố trí','edit',e.id)}${!e.userId&&e.active&&e.positionIds.length?orgButton('Tạo tài khoản','account',e.id):''}</td></tr>`);}
 else if(tab==='departments'){headers=['Phòng ban','Luồng công việc','Trạng thái',''];rows=orgUnits().map(d=>`<tr><td><strong>${esc("\u2014 ".repeat(d.depth))}${esc(d.name)}</strong><small class="subtext">${esc(orgKinds[d.kind]||orgKinds.department)} / ${esc(orgPath(d.parentId))}</small></td><td>${esc(orgStages[d.stage])}</td><td>${d.active?'Đang sử dụng':'Ngừng sử dụng'}</td><td>${orgButton('Sửa','edit',d.id)}${orgButton('Xóa','delete',d.id)}</td></tr>`);}
 else{headers=['Vị trí','Phòng ban','Bộ quyền / phạm vi giao việc',''];rows=data.positions.map(p=>`<tr><td><strong>${esc(p.name)}</strong><small class="subtext">${p.active?'Đang sử dụng':'Ngừng sử dụng'}</small></td><td>${esc(orgPath(p.departmentId))}</td><td>${p.roleIds.map(id=>esc(data.roles.find(r=>r.id===id)?.name||'')).join(', ')}<small class="subtext">${p.manager?'Quản lý: giao việc trong đơn vị và các đơn vị trực thuộc cùng luồng':'Nhân viên'}</small></td><td>${orgButton('Sửa','edit',p.id)}${orgButton('Xóa','delete',p.id)}</td></tr>`);}
 openDialog(tab==='employees'?'Nhân sự':'Cơ cấu tổ chức',tools+`<p>Khai phòng ban và vị trí tại mục Cơ cấu tổ chức. Tạo bộ quyền tại mục Vai trò & phân quyền, gán cho vị trí rồi bố trí nhân sự. Một người có thể kiêm nhiệm nhiều vị trí.</p><div class="panel-head"><h3>${label}</h3>${orgButton('+ Thêm '+label.toLowerCase(),'edit')}</div><div class="table-scroll"><table class="organization-table"><thead><tr>${headers.map(h=>'<th>'+h+'</th>').join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="4">Chưa khai báo. Bấm Thêm để bắt đầu.</td></tr>`}</tbody></table></div><p class="help-text">Thay vị trí hoặc bộ quyền sẽ cập nhật quyền tài khoản liên quan và yêu cầu đăng nhập lại. Nhân sự có tài khoản được giữ lịch sử khi ngừng làm việc.</p>`);$('#dialog').classList.add('wide-dialog');for(const row of document.querySelectorAll('.organization-table tbody tr'))Array.from(row.cells).forEach((cell,i)=>cell.dataset.label=headers[i]);
}
async function orgSave(document,createAccount){const saved=await teamApi('organization','PUT',{expectedVersion:OrgData.version,document,createAccount});if(saved.reauthenticate){closeDialog();teamSession({user:null,permissions:null,csrf:''});render();toast('Quyền đã cập nhật. Đăng nhập lại để sử dụng.');return;}await orgOpen();toast('Đã lưu cơ cấu và cập nhật quyền liên quan');}
function orgDocument(){return C.copy({departments:OrgData.departments,positions:OrgData.positions,employees:OrgData.employees});}
function orgEdit(id){const type=OrgTab,record=OrgData[type].find(x=>x.id===id),x=record||{id:crypto.randomUUID(),name:'',active:true,code:'',phone:'',email:'',positionIds:[],roleIds:[],departmentId:OrgData.departments.find(d=>d.active)?.id||'',stage:'other',manager:false};let fields=field(type==='employees'?'Họ và tên':'Tên '+(type==='departments'?'phòng ban':'vị trí'),'name',x.name,'text','required maxlength="100"');
 if(type==='departments')fields+=select('Loại đơn vị','kind',Object.entries(orgKinds),x.kind||'department')+select('Đơn vị cấp trên','parentId',[['','Cấp cao nhất'],...orgUnits().filter(d=>!orgDescendant(d.id,x.id)).map(d=>[d.id,orgPath(d.id)])],x.parentId||'')+select('Luồng giao việc','stage',Object.entries(orgStages),x.stage);
 if(type==='positions'){fields+=select('Phòng ban','departmentId',orgUnits().map(d=>[d.id,orgPath(d.id)+(d.active?'':' (ngừng sử dụng)')]),x.departmentId,'required')+`<label><input type="checkbox" name="manager" ${x.manager?'checked':''}> Vị trí quản lý phòng ban — được giao việc trong đơn vị và cấp dưới cùng luồng</label><fieldset><legend>Bộ quyền áp dụng</legend>${OrgData.roles.map(r=>`<label class="pa-checkbox"><input type="checkbox" name="roleIds" value="${esc(r.id)}" ${x.roleIds.includes(r.id)?'checked':''}> ${esc(r.name)}</label>`).join('')||'<p>Chưa có bộ quyền. Quay lại và chọn Bộ quyền để khai báo trước.</p>'}</fieldset>`;}
 if(type==='employees')fields=field('Mã nhân sự','code',x.code,'text','required maxlength="100"')+fields+field('Điện thoại','phone',x.phone,'tel','maxlength="40"')+field('Email','email',x.email,'email','maxlength="160"')+`<fieldset><legend>Phòng ban và vị trí kiêm nhiệm</legend>${OrgData.departments.map(d=>`<div><strong>${esc(orgPath(d.id))}</strong>${OrgData.positions.filter(p=>p.departmentId===d.id).map(p=>`<label class="pa-checkbox"><input type="checkbox" name="positionIds" value="${esc(p.id)}" ${x.positionIds.includes(p.id)?'checked':''}> ${esc(p.name)}${p.manager?' · Quản lý':''}${!p.active||!orgUnitActive(d.id)?' · Ngừng áp dụng':''}</label>`).join('')||'<small class="subtext">Chưa khai vị trí</small>'}</div>`).join('')||'<p>Khai phòng ban và vị trí trước khi bố trí nhân sự.</p>'}</fieldset><p>${x.userId?'Tài khoản: '+esc(OrgData.users.find(u=>u.id===x.userId)?.username||'Đã ngừng'):'Có thể lưu hồ sơ trước; tạo tài khoản sau khi đã bố trí vị trí.'}</p>`;
 fields+=`<label class="pa-checkbox"><input type="checkbox" name="active" ${x.active?'checked':''}> ${type==='employees'?'Đang làm việc':'Đang sử dụng'}</label><p class="help-text">Bỏ trạng thái hoạt động sẽ ngừng áp dụng các quyền tương ứng. Thay đổi được lưu cùng phiên bản cơ cấu.</p>`;
 teamDialog((id?'Sửa ':'Thêm ')+({employees:'nhân sự',positions:'vị trí',departments:'phòng ban'}[type]),fields,'Lưu và áp dụng',async f=>{const d=orgDocument(),v={...x,name:String(f.get('name')),active:f.has('active')};if(type==='departments')Object.assign(v,{stage:f.get('stage'),parentId:f.get('parentId')||null,kind:f.get('kind')});if(type==='positions')Object.assign(v,{departmentId:f.get('departmentId'),roleIds:f.getAll('roleIds'),manager:f.has('manager')});if(type==='employees')Object.assign(v,{code:f.get('code'),email:f.get('email'),phone:f.get('phone'),positionIds:f.getAll('positionIds')});if(record)d[type]=d[type].map(a=>a.id===id?v:a);else d[type].push(v);await orgSave(d);});
}
function installOrganizationUI(){
 const session=teamSession;teamSession=value=>{session(value);orgNavigation();};
 function orgNavigation(){for(const [id,action,label] of [['personnel-nav','employees','Nhân sự'],['organization-nav','departments','Cơ cấu tổ chức'],['permissions-nav','roles','Vai trò & phân quyền']]){let b=document.getElementById(id);if(!b){b=document.createElement('button');b.id=id;document.querySelector('#sidebar nav').append(b);}b.dataset.org=action;b.textContent=label;b.hidden=Team.user?.role!=='admin';b.style.display=b.hidden?'none':'';}}

 orgNavigation();
noticeTeams=()=>orgOpen();teamCreateUser=async()=>{await orgOpen('employees');orgEdit();};const buttons=arButtons;arButtons=()=>orgButton('Nhân sự & phòng ban','employees')+buttons();const users=teamUsers;teamUsers=async()=>{await users();const d=await teamApi('organization');for(const e of d.employees.filter(e=>e.managed)){const b=$('#dialog [data-access="edit-user"][data-id="'+e.userId+'"]');if(b){b.removeAttribute('data-access');b.dataset.org='employee-link';b.dataset.id=e.id;b.textContent='Vị trí & quyền';}}};
 document.addEventListener('click',e=>{const b=e.target.closest('[data-org]');if(!b)return;Promise.resolve().then(async()=>{const {org:a,id}=b.dataset;document.getElementById('sidebar')?.classList.remove('open');if(['employees','departments','positions'].includes(a))return orgOpen(a);if(a==='roles')return arRoles();if(a==='accounts')return teamUsers();if(a==='employee-link'){await orgOpen('employees');return orgEdit(id);}if(a==='edit')return orgEdit(id);if(a==='delete'){const type=OrgTab,x=OrgData[type].find(x=>x.id===id);teamDialog('Xóa khai báo','<p>Xóa '+esc(x.name)+'? Khai báo đang được sử dụng sẽ không xóa được.</p>','Xóa',async()=>{const d=orgDocument();d[type]=d[type].filter(x=>x.id!==id);await orgSave(d);});}if(a==='account'){const person=OrgData.employees.find(x=>x.id===id);teamDialog('Tạo tài khoản · '+person.name,field('Tài khoản đăng nhập','username','','text','required minlength="3" maxlength="64"')+field('Mật khẩu ban đầu','password','','password','required minlength="12" autocomplete="new-password"')+'<p>Quyền được lấy từ các vị trí đã bố trí cho nhân sự này.</p>','Tạo tài khoản',async f=>orgSave(orgDocument(),{employeeId:id,username:f.get('username'),password:f.get('password')}));}}).catch(err=>toast(err.message));});
}
