'use strict';
let OrgData=null,OrgTab='employees';
const orgButton=(label,action,id='')=>`<button type="button" class="button small" data-org="${action}" data-id="${esc(id)}">${esc(label)}</button>`;
const orgStages={sales:'Kinh doanh',technical:'Kỹ thuật',materials:'Cập nhật giá',other:'Khác'};
const orgPositions=e=>e.positionIds.map(id=>{const p=OrgData.positions.find(p=>p.id===id),d=OrgData.departments.find(d=>d.id===p?.departmentId);return p?`${d?.name||''} · ${p.name}${p.manager?' (Quản lý)':''}${!p.active||!d?.active?' — Ngừng áp dụng':''}`:'';}).filter(Boolean);
async function orgOpen(tab=OrgTab){OrgTab=tab;OrgData=await teamApi('organization');const data=OrgData,tools=`<div class="actions">${orgButton('Nhân sự','employees')}${orgButton('Phòng ban','departments')}${orgButton('Vị trí & quyền','positions')}${orgButton('Bộ quyền','roles')}${orgButton('Tài khoản đăng nhập','accounts')}</div>`,label={employees:'Nhân sự',departments:'Phòng ban',positions:'Vị trí & quyền'}[tab];
 let rows,headers;
 if(tab==='employees'){headers=['Nhân sự','Phòng ban · Vị trí','Tài khoản / trạng thái',''];rows=data.employees.map(e=>`<tr><td><strong>${esc(e.name)}</strong><small class="subtext">${esc(e.code)}</small><small>${esc([e.phone,e.email].filter(Boolean).join(' · '))}</small></td><td>${orgPositions(e).map(x=>'<div>'+esc(x)+'</div>').join('')||'Chưa bố trí vị trí'}${e.managed?'':'<small class="subtext">Giữ quyền cũ đến khi phân vị trí</small>'}</td><td>${esc(data.users.find(u=>u.id===e.userId)?.username||'Chưa có tài khoản')}<small class="subtext">${e.active?'Đang làm việc':'Ngừng làm việc'}${e.userId&&!data.users.find(u=>u.id===e.userId)?.active?' · Tài khoản đang khóa':''}</small></td><td>${orgButton('Hồ sơ / bố trí','edit',e.id)}${!e.userId&&e.active&&e.positionIds.length?orgButton('Tạo tài khoản','account',e.id):''}</td></tr>`);}
 else if(tab==='departments'){headers=['Phòng ban','Luồng công việc','Trạng thái',''];rows=data.departments.map(d=>`<tr><td><strong>${esc(d.name)}</strong></td><td>${esc(orgStages[d.stage])}</td><td>${d.active?'Đang sử dụng':'Ngừng sử dụng'}</td><td>${orgButton('Sửa','edit',d.id)}${orgButton('Xóa','delete',d.id)}</td></tr>`);}
 else{headers=['Vị trí','Phòng ban','Bộ quyền / phạm vi giao việc',''];rows=data.positions.map(p=>`<tr><td><strong>${esc(p.name)}</strong><small class="subtext">${p.active?'Đang sử dụng':'Ngừng sử dụng'}</small></td><td>${esc(data.departments.find(d=>d.id===p.departmentId)?.name||'')}</td><td>${p.roleIds.map(id=>esc(data.roles.find(r=>r.id===id)?.name||'')).join(', ')}<small class="subtext">${p.manager?'Quản lý: giao việc cho mình và nhân viên cùng phòng':'Nhân viên'}</small></td><td>${orgButton('Sửa','edit',p.id)}${orgButton('Xóa','delete',p.id)}</td></tr>`);}
 openDialog('Nhân sự & phòng ban',tools+`<p>Khai báo phòng ban → vị trí và bộ quyền → bố trí nhân sự. Một người có thể kiêm nhiệm nhiều vị trí; quyền được tổng hợp từ các vị trí đang hoạt động.</p><div class="panel-head"><h3>${label}</h3>${orgButton('+ Thêm '+label.toLowerCase(),'edit')}</div><div class="table-scroll"><table class="organization-table"><thead><tr>${headers.map(h=>'<th>'+h+'</th>').join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="4">Chưa khai báo. Bấm Thêm để bắt đầu.</td></tr>`}</tbody></table></div><p class="help-text">Thay vị trí hoặc bộ quyền sẽ cập nhật quyền tài khoản liên quan và yêu cầu đăng nhập lại. Nhân sự có tài khoản được giữ lịch sử khi ngừng làm việc.</p>`);$('#dialog').classList.add('wide-dialog');for(const row of document.querySelectorAll('.organization-table tbody tr'))Array.from(row.cells).forEach((cell,i)=>cell.dataset.label=headers[i]);
}
async function orgSave(document,createAccount){const saved=await teamApi('organization','PUT',{expectedVersion:OrgData.version,document,createAccount});if(saved.reauthenticate){closeDialog();teamSession({user:null,permissions:null,csrf:''});render();toast('Quyền đã cập nhật. Đăng nhập lại để sử dụng.');return;}await orgOpen();toast('Đã lưu cơ cấu và cập nhật quyền liên quan');}
function orgDocument(){return C.copy({departments:OrgData.departments,positions:OrgData.positions,employees:OrgData.employees});}
function orgEdit(id){const type=OrgTab,record=OrgData[type].find(x=>x.id===id),x=record||{id:crypto.randomUUID(),name:'',active:true,code:'',phone:'',email:'',positionIds:[],roleIds:[],departmentId:OrgData.departments.find(d=>d.active)?.id||'',stage:'other',manager:false};let fields=field(type==='employees'?'Họ và tên':'Tên '+(type==='departments'?'phòng ban':'vị trí'),'name',x.name,'text','required maxlength="100"');
 if(type==='departments')fields+=select('Luồng giao việc','stage',Object.entries(orgStages),x.stage);
 if(type==='positions'){fields+=select('Phòng ban','departmentId',OrgData.departments.map(d=>[d.id,d.name+(d.active?'':' (ngừng sử dụng)')]),x.departmentId,'required')+`<label><input type="checkbox" name="manager" ${x.manager?'checked':''}> Vị trí quản lý phòng ban — được giao việc cho nhân viên thuộc phòng</label><fieldset><legend>Bộ quyền áp dụng</legend>${OrgData.roles.map(r=>`<label class="pa-checkbox"><input type="checkbox" name="roleIds" value="${esc(r.id)}" ${x.roleIds.includes(r.id)?'checked':''}> ${esc(r.name)}</label>`).join('')||'<p>Chưa có bộ quyền. Quay lại và chọn Bộ quyền để khai báo trước.</p>'}</fieldset>`;}
 if(type==='employees')fields=field('Mã nhân sự','code',x.code,'text','required maxlength="100"')+fields+field('Điện thoại','phone',x.phone,'tel','maxlength="40"')+field('Email','email',x.email,'email','maxlength="160"')+`<fieldset><legend>Phòng ban và vị trí kiêm nhiệm</legend>${OrgData.departments.map(d=>`<div><strong>${esc(d.name)}</strong>${OrgData.positions.filter(p=>p.departmentId===d.id).map(p=>`<label class="pa-checkbox"><input type="checkbox" name="positionIds" value="${esc(p.id)}" ${x.positionIds.includes(p.id)?'checked':''}> ${esc(p.name)}${p.manager?' · Quản lý':''}${!p.active||!d.active?' · Ngừng áp dụng':''}</label>`).join('')||'<small class="subtext">Chưa khai vị trí</small>'}</div>`).join('')||'<p>Khai phòng ban và vị trí trước khi bố trí nhân sự.</p>'}</fieldset><p>${x.userId?'Tài khoản: '+esc(OrgData.users.find(u=>u.id===x.userId)?.username||'Đã ngừng'):'Có thể lưu hồ sơ trước; tạo tài khoản sau khi đã bố trí vị trí.'}</p>`;
 fields+=`<label class="pa-checkbox"><input type="checkbox" name="active" ${x.active?'checked':''}> ${type==='employees'?'Đang làm việc':'Đang sử dụng'}</label><p class="help-text">Bỏ trạng thái hoạt động sẽ ngừng áp dụng các quyền tương ứng. Thay đổi được lưu cùng phiên bản cơ cấu.</p>`;
 teamDialog((id?'Sửa ':'Thêm ')+({employees:'nhân sự',positions:'vị trí',departments:'phòng ban'}[type]),fields,'Lưu và áp dụng',async f=>{const d=orgDocument(),v={...x,name:String(f.get('name')),active:f.has('active')};if(type==='departments')v.stage=f.get('stage');if(type==='positions')Object.assign(v,{departmentId:f.get('departmentId'),roleIds:f.getAll('roleIds'),manager:f.has('manager')});if(type==='employees')Object.assign(v,{code:f.get('code'),email:f.get('email'),phone:f.get('phone'),positionIds:f.getAll('positionIds')});if(record)d[type]=d[type].map(a=>a.id===id?v:a);else d[type].push(v);await orgSave(d);});
}
function installOrganizationUI(){noticeTeams=()=>orgOpen();teamCreateUser=async()=>{await orgOpen('employees');orgEdit();};const buttons=arButtons;arButtons=()=>orgButton('Nhân sự & phòng ban','employees')+buttons();const users=teamUsers;teamUsers=async()=>{await users();const d=await teamApi('organization');for(const e of d.employees.filter(e=>e.managed)){const b=$('#dialog [data-access="edit-user"][data-id="'+e.userId+'"]');if(b){b.removeAttribute('data-access');b.dataset.org='employee-link';b.dataset.id=e.id;b.textContent='Vị trí & quyền';}}};
 document.addEventListener('click',e=>{const b=e.target.closest('[data-org]');if(!b)return;Promise.resolve().then(async()=>{const {org:a,id}=b.dataset;if(['employees','departments','positions'].includes(a))return orgOpen(a);if(a==='roles')return arRoles();if(a==='accounts')return teamUsers();if(a==='employee-link'){await orgOpen('employees');return orgEdit(id);}if(a==='edit')return orgEdit(id);if(a==='delete'){const type=OrgTab,x=OrgData[type].find(x=>x.id===id);teamDialog('Xóa khai báo','<p>Xóa '+esc(x.name)+'? Khai báo đang được sử dụng sẽ không xóa được.</p>','Xóa',async()=>{const d=orgDocument();d[type]=d[type].filter(x=>x.id!==id);await orgSave(d);});}if(a==='account'){const person=OrgData.employees.find(x=>x.id===id);teamDialog('Tạo tài khoản · '+person.name,field('Tài khoản đăng nhập','username','','text','required minlength="3" maxlength="64"')+field('Mật khẩu ban đầu','password','','password','required minlength="12" autocomplete="new-password"')+'<p>Quyền được lấy từ các vị trí đã bố trí cho nhân sự này.</p>','Tạo tài khoản',async f=>orgSave(orgDocument(),{employeeId:id,username:f.get('username'),password:f.get('password')}));}}).catch(err=>toast(err.message));});
}
