'use strict';
const HR={data:null,tab:'employees',allowed:false};
const hrButton=(label,action,id='')=>`<button type="button" class="button small" data-hr="${action}" data-id="${esc(id)}">${esc(label)}</button>`;
const hrStatus={pending:'Chờ duyệt',approved:'Đã duyệt',rejected:'Từ chối'};
const hrPositions=e=>(e.positionIds||[]).map(id=>{const p=HR.data.positions.find(p=>p.id===id),d=HR.data.departments.find(d=>d.id===p?.departmentId);return p?(d?.name||'')+' · '+p.name:'';}).filter(Boolean).join('; ');
async function hrOpen(tab=HR.tab){const generation=Team.sessionGeneration,data=await teamApi('personnel');if(generation!==Team.sessionGeneration)return;HR.data=data;HR.tab=tab;hrList();}
function hrList(){const d=HR.data,pending=d.requests.filter(r=>r.status==='pending'),tabs=[['employees','Nhân viên'],['users','Người dùng'],['pending','Chờ duyệt ('+pending.filter(r=>r.kind==='profile').length+')'],['activation','Yêu cầu kích hoạt ('+pending.filter(r=>r.kind==='activation').length+')'],['history','Lịch sử hồ sơ']];
 openDialog('Nhân sự',`<div class="actions">${tabs.map(([k,l])=>hrButton(l,'tab',k)).join('')}</div><p>Khai báo hồ sơ → gửi duyệt → vào danh sách nhân viên. Tạo tài khoản sử dụng phần mềm theo yêu cầu kích hoạt riêng.</p><div class="actions">${hrButton('+ Khai báo nhân sự','new')}${hrButton('Xuất Excel danh sách','export-list')}${d.canApprove?hrButton('Phân công người khai báo','editors'):''}</div><div class="form-grid">${field('Tìm mã, họ tên, điện thoại','hrQuery','')}${select('Phòng ban','hrDepartment',[['','Tất cả'],...d.departments.map(x=>[x.id,x.name])],'')}${select('Trạng thái lao động','hrActive',[['','Tất cả'],['active','Đang làm việc'],['inactive','Ngừng làm việc']],'')}</div><div class="table-scroll"><table><thead><tr><th>Mã / nhân sự</th><th>Phòng ban · vị trí</th><th>Trạng thái / người gửi</th><th>Thao tác</th></tr></thead><tbody data-hr-rows></tbody></table></div><p data-hr-count></p>`);$('#dialog').classList.add('wide-dialog');$('#dialog-form').addEventListener('input',hrRows);$('#dialog-form').addEventListener('change',hrRows);hrRows();}
function hrMatches(e){const f=$('#dialog-form'),q=(f.elements.hrQuery?.value||'').toLocaleLowerCase('vi'),dept=f.elements.hrDepartment?.value,active=f.elements.hrActive?.value;return [e.code,e.name,e.phone,e.email].join(' ').toLocaleLowerCase('vi').includes(q)&&(!dept||(e.positionIds||[]).some(id=>HR.data.positions.some(p=>p.id===id&&p.departmentId===dept)))&&(!active||(e.active!==false)===(active==='active'));}
function hrRows(){const d=HR.data,list=['employees','users'].includes(HR.tab),rows=list?d.employees.filter(e=>hrMatches(e)&&(HR.tab!=='users'||e.userId)):d.requests.filter(r=>HR.tab==='history'?r.status!=='pending':r.status==='pending'&&r.kind===(HR.tab==='activation'?'activation':'profile')).filter(r=>hrMatches(r.employee||d.employees.find(e=>e.id===r.employeeId)||{}));
 $('[data-hr-rows]').innerHTML=rows.map(x=>{const e=list?x:x.employee||d.employees.find(e=>e.id===x.employeeId)||{},account=d.users.find(u=>u.id===e.userId);return `<tr><td><strong>${esc(e.name)}</strong><small class="subtext">${esc(e.code)}</small></td><td>${esc(hrPositions(e))}</td><td>${list?(e.active!==false?'Đang làm việc':'Ngừng làm việc')+'<small class="subtext">'+esc(account?account.username+(account.active?'':' · Khóa'):e.userId?'Đã có tài khoản':'Chưa có tài khoản')+'</small>':esc(hrStatus[x.status])+' · '+esc(x.actor)+'<small class="subtext">'+esc(x.at)+' '+esc(x.reason||'')+'</small>'}</td><td>${list?hrButton('Hồ sơ / sửa','edit',e.id)+hrButton('Xuất hồ sơ','export',e.id)+(!e.userId&&e.active!==false?hrButton('Yêu cầu kích hoạt','activation',e.id):''):hrButton('Xem hồ sơ','request',x.id)+(x.status==='rejected'&&x.kind==='profile'?hrButton('Sửa và gửi lại','retry',x.id):'')+(d.canApprove&&x.status==='pending'?hrButton('Duyệt','approve',x.id)+hrButton('Từ chối','reject',x.id):'')}</td></tr>`;}).join('')||'<tr><td colspan="4">Chưa có dữ liệu trong mục này.</td></tr>';$('[data-hr-count]').textContent=rows.length+' mục';}
function hrHistoryRow(x={}){return `<tr data-hr-work>${['from','to','department','position','manager','indirectManager'].map(k=>`<td><input aria-label="${esc(k)}" data-work-key="${k}" type="${['from','to'].includes(k)?'date':'text'}" maxlength="200" value="${esc(x[k]||'')}"></td>`).join('')}<td>${hrButton('Xóa dòng','remove-work')}</td></tr>`;}
function hrEdit(id,request,editable=false){const e=request?.employee||HR.data.employees.find(e=>e.id===id)||{positionIds:[],active:true,profile:{},workHistory:[]},readOnly=!!request&&!editable,groups=[...new Set(TPPersonnel.fields.map(f=>f.group))];
 const content=`${groups.map((g,i)=>`<details ${i===0?'open':''}><summary><strong>${esc(g)}</strong></summary><div class="form-grid">${TPPersonnel.fields.filter(f=>f.group===g).map(f=>field(f.label,'hr:'+f.key,(f.base?e[f.key]:e.profile?.[f.key])||'',f.type,(f.key==='code'||f.key==='name'?'required ':'')+(f.type==='number'?'min="0" step="any"':'maxlength="2000"'))).join('')}</div></details>`).join('')}<details open><summary><strong>BỐ TRÍ CÔNG VIỆC</strong></summary>${field('Ngày vào làm','startDate',e.startDate||'','date')}<label class="pa-checkbox"><input name="active" type="checkbox" ${e.active!==false?'checked':''}> Đang làm việc</label><fieldset><legend>Phòng ban / vị trí (quyền chỉ thay đổi sau khi duyệt)</legend>${HR.data.positions.map(p=>`<label class="pa-checkbox"><input type="checkbox" name="positions" value="${esc(p.id)}" ${(e.positionIds||[]).includes(p.id)?'checked':''}> ${esc(HR.data.departments.find(d=>d.id===p.departmentId)?.name)} · ${esc(p.name)}</label>`).join('')||'Chưa khai vị trí trong Cơ cấu tổ chức.'}</fieldset><label class="field"><span>Công đoạn / nội dung phụ trách</span><textarea name="duties" maxlength="2000">${esc(e.duties||'')}</textarea></label></details><details open><summary><strong>QUÁ TRÌNH CÔNG TÁC</strong></summary><div class="table-scroll"><table><thead><tr>${['Từ ngày','Đến ngày','Đơn vị công tác','Vị trí','Quản lý trực tiếp','Quản lý gián tiếp',''].map(s=>'<th>'+s+'</th>').join('')}</tr></thead><tbody data-hr-history>${(e.workHistory||[]).map(hrHistoryRow).join('')}</tbody></table></div>${readOnly?'':hrButton('+ Thêm quá trình','add-work')}</details>`;
 teamDialog(readOnly?'Hồ sơ đề nghị · '+esc(e.name||''):e.id?'Cập nhật hồ sơ nhân sự':'Khai báo nhân sự',content,readOnly?'Quay lại':'Gửi duyệt hồ sơ',async f=>{if(readOnly)return hrOpen();const employee={...e,profile:{},positionIds:f.getAll('positions'),startDate:f.get('startDate'),duties:f.get('duties'),active:f.has('active')};for(const field of TPPersonnel.fields){const v=String(f.get('hr:'+field.key)||'');if(field.base)employee[field.key]=v;else employee.profile[field.key]=v;}employee.workHistory=[...document.querySelectorAll('[data-hr-work]')].map(row=>Object.fromEntries([...row.querySelectorAll('[data-work-key]')].map(el=>[el.dataset.workKey,el.value])));await teamApi('personnel/submit','POST',{expectedVersion:HR.data.version,employeeId:HR.data.employees.some(x=>x.id===id)?id:undefined,employee});await hrOpen('pending');toast('Đã gửi hồ sơ chờ duyệt.');});$('#dialog').classList.add('wide-dialog');if(readOnly)$('#dialog .dialog-body').querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=true);
}
function hrExport(id){const e=HR.data.employees.find(e=>e.id===id),rows=[['HỒ SƠ NHÂN VIÊN',e.code+' - '+e.name]];let group='';for(const f of TPPersonnel.fields){if(group!==f.group){group=f.group;rows.push([group]);}rows.push([f.label,(f.base?e[f.key]:e.profile?.[f.key])||'']);}rows.push(['Ngày vào làm',e.startDate||''],['Phòng ban / vị trí',hrPositions(e)],['Công đoạn phụ trách',e.duties||''],['Trạng thái',e.active?'Đang làm việc':'Ngừng làm việc'],['QUÁ TRÌNH CÔNG TÁC'],['Từ ngày','Đến ngày','Đơn vị','Vị trí','QL trực tiếp','QL gián tiếp'],...(e.workHistory||[]).map(r=>[r.from,r.to,r.department,r.position,r.manager,r.indirectManager]));download('HO-SO-'+String(e.code).replace(/[^a-zA-Z0-9_-]/g,'_')+'.xlsx',TPXlsx.make([{name:'Ho so nhan vien',rows}]),reviewMime);}
function hrReview(id,action){const r=HR.data.requests.find(r=>r.id===id),activation=r.kind==='activation'&&action==='approve';teamDialog(action==='reject'?'Từ chối yêu cầu':activation?'Duyệt và tạo tài khoản':'Duyệt hồ sơ nhân sự',`<p>${esc(r.employee?.name||HR.data.employees.find(e=>e.id===r.employeeId)?.name)} · Người gửi: ${esc(r.actor)}</p>${activation?field('Tên đăng nhập','username','','text','required minlength="3" maxlength="64"')+field('Mật khẩu ban đầu','password','','password','required minlength="12" maxlength="200" autocomplete="new-password"'):''}${field('Ghi chú / lý do','reason','','text',(action==='reject'?'required ':'')+'maxlength="1000"')}`,'Xác nhận',async f=>{await teamApi('personnel/review','POST',{expectedVersion:HR.data.version,id,action,reason:f.get('reason'),...(activation?{username:f.get('username'),password:f.get('password')}:{})});await hrOpen();});}
function installPersonnelUI(){
 teamCreateUser=async()=>{await hrOpen('employees');hrEdit();};
 document.addEventListener('click',e=>{const b=e.target.closest('[data-org="employees"],[data-org="employee-link"]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();hrOpen('employees').then(()=>{if(b.dataset.org==='employee-link')hrEdit(b.dataset.id);}).catch(error=>toast(error.message));},true);
 const nav=()=>{const b=$('#personnel-nav');if(b){b.removeAttribute('data-org');b.dataset.hr='open';b.hidden=!(Team.user?.role==='admin'||HR.allowed);b.style.display=b.hidden?'none':'';}};
 const oldSession=teamSession;teamSession=value=>{oldSession(value);HR.allowed=false;HR.data=null;nav();if(Team.user){const generation=Team.sessionGeneration;teamApi('personnel/access').then(r=>{if(generation===Team.sessionGeneration){HR.allowed=r.allowed;nav();}}).catch(()=>{});}};
 const oldRender=render;render=()=>{oldRender();nav();};
 document.addEventListener('click',e=>{const b=e.target.closest('[data-hr]');if(!b)return;Promise.resolve().then(async()=>{const a=b.dataset.hr,id=b.dataset.id;if(a==='open')return hrOpen('employees');if(a==='tab')return hrOpen(id);if(a==='new')return hrEdit();if(a==='retry'){const r=HR.data.requests.find(r=>r.id===id);return hrEdit(r.employeeId,r,true);}if(a==='edit')return hrEdit(id);if(a==='request'){const r=HR.data.requests.find(r=>r.id===id);return hrEdit(r.employeeId,{...r,employee:r.employee||HR.data.employees.find(x=>x.id===r.employeeId)});}if(a==='add-work')return $('[data-hr-history]').insertAdjacentHTML('beforeend',hrHistoryRow());if(a==='remove-work')return b.closest('tr').remove();if(a==='export')return hrExport(id);if(a==='approve'||a==='reject')return hrReview(id,a);if(a==='activation'){await teamApi('personnel/activation','POST',{expectedVersion:HR.data.version,employeeId:id});return hrOpen('activation');}if(a==='export-list'){const rows=HR.data.employees.filter(hrMatches);return download('NHAN-SU.xlsx',TPXlsx.make([{name:'Nhan su',rows:[['Mã','Họ tên','Phòng ban / vị trí',...TPPersonnel.fields.filter(f=>!['code','name'].includes(f.key)).map(f=>f.label)],...rows.map(e=>[e.code,e.name,hrPositions(e),...TPPersonnel.fields.filter(f=>!['code','name'].includes(f.key)).map(f=>(f.base?e[f.key]:e.profile?.[f.key])||'')])]}]),reviewMime);}if(a==='editors')teamDialog('Phân công người khai báo nhân sự','<p>Người được chọn được xem và khai hồ sơ đầy đủ, gửi cập nhật và yêu cầu kích hoạt. Quyền duyệt thuộc quản trị.</p>'+HR.data.users.filter(u=>u.active).map(u=>`<label class="pa-checkbox"><input name="editors" type="checkbox" value="${esc(u.id)}" ${HR.data.personnelEditors?.includes(u.id)?'checked':''}> ${esc(u.name)} · ${esc(u.username)}</label>`).join(''),'Lưu phân công',async f=>{await teamApi('personnel/editors','POST',{expectedVersion:HR.data.version,ids:f.getAll('editors')});await hrOpen();});}).catch(error=>toast(error.message));});nav();
}
