/* Customer workflow: shared operation grid, explainable rates and four alternatives. */
'use strict';
const PA={query:'',costDetails:true};
const paNames={stock:'Phôi gia công',ancillary:'Linh kiện & vật tư phụ',allowance:'Dự tính vật tư phụ theo % phôi',tmcCommon:'Chi phí chung riêng TMC',finishing:'Vật tư hoàn thiện theo định mức',factory:'Sản xuất tại xưởng',outside:'Sản xuất thuê ngoài',incoming:'Vận chuyển nhập phôi / vật tư',outgoing:'Vận chuyển thuê ngoài',install:'Lắp đặt',delivery:'Vận chuyển giao hàng'};
function paButton(text,action,attrs='',style=''){return `<button type="button" class="button ${style}" data-pa="${action}" ${attrs}>${text}</button>`;}
function paSequenceText(){return TPPrice.currentFlow(db.quote)?'Giá sản xuất + giao hàng + lắp đặt → nhân (1 + chi phí chung) → nhân (1 + quản lý) → giá gốc. Phần đã gồm trong gói chỉ tính một lần.':'Bản cũ: hệ số chung/quản lý áp trong giá sản xuất; giao hàng/lắp đặt cộng sau. Giữ cách tính đã lưu.';}
function paFlowNotice(){return `<div class="notice" data-flow-sequence><span>${paSequenceText()}</span>${!TPPrice.currentFlow(db.quote)?paButton('Áp dụng luồng đã chốt 19/09','adopt-flow',(['submitted','approved'].includes(db.quote.status)||Team.loaded&&!Team.permissions.factors)?'disabled':'','primary'):''}</div>`;}
const paFreightLabels={incoming:'Nhập phôi / vật tư',outgoing:'Vận chuyển gia công thuê ngoài',delivery:'Giao hàng',install:'Lắp đặt công trình'};
function paScopeFields(n,method){return `<fieldset><legend>${method==='kg'?'Giá kg':'Giá đối thủ'} đã gồm những khoản nào?</legend><p class="help-text">Khoản chưa gồm lấy đúng chi phí chưa thuế của PA tính toán theo sản phẩm, không nhân lại hệ số giá bán.</p><div class="form-grid">${Object.entries(paFreightLabels).map(([k,label])=>select(label,'scope-'+method+'-'+k+'-'+n.id,[['','Chưa xác nhận'],['included','Đã gồm trong giá'],['detail','Chưa gồm — cộng từ tính toán'],['none','Không áp dụng']],n.benchmarkScope?.[method]?.[k]??(TPPrice.currentFlow(db.quote)?'':'included'))).join('')}</div></fieldset>`;}
function paReadScope(f,n,method){n.benchmarkScope??={};n.benchmarkScope[method]=Object.fromEntries(Object.keys(paFreightLabels).map(k=>[k,String(f.get('scope-'+method+'-'+k+'-'+n.id)||'')]));}
function paScopeSummary(n,method){return Object.entries(paFreightLabels).map(([k,label])=>label+': '+({included:'đã gồm',detail:'cộng từ tính toán',none:'không áp dụng'}[n.benchmarkScope?.[method]?.[k]]||(TPPrice.currentFlow(db.quote)?'chưa xác nhận':'đã gồm (bản cũ)'))).join(' · ');}
function paIntro(){return `<div class="pa-intro"><div><strong>${db.quote.pricing?'Báo giá theo nhóm sản phẩm':'Đang giữ cách tính của báo giá cũ'}</strong><span>${db.quote.pricing?'Số và hệ số minh họa. Một lựa chọn áp dụng cho toàn báo giá.':'Chuyển sang luồng mới có thể thay đổi giá. Cấu thành hiện có được giữ nguyên.'}</span></div><div class="actions">${!db.quote.pricing?paButton('Dùng luồng mới','enable','','primary'):''}${paButton('Mở ca mẫu để thử','sample')}</div></div>`;}
function paMoney(n){return Number.isFinite(n)?money(n):'Chưa có';}
function paErrors(list){return list.length?`<div class="notice error"><strong>Cần kiểm tra</strong><span>${list.map(esc).join('<br>')}</span></div>`:'';}
function renderCostAnalysis(){
  if(!db.quote.pricing)return renderPriceMatrix();
  const chosen=result.pricing.selected,alternatives=result.comparisonIds.map(id=>result.alternatives[id]),t=result.total;
  const row=(label,get,{className='',explain=''}={})=>`<tr class="${className}"><th scope="row">${label}${explain?`<small>${explain}</small>`:''}</th>${alternatives.map(a=>`<td class="mono right ${chosen===a.id?'pa-chosen':''}">${get(a)}</td>`).join('')}</tr>`;
  const section=(title)=>`<tr class="pa-section-row"><th colspan="${alternatives.length+1}">${title}</th></tr>`,cash=(a,k)=>a.id==='tmc'&&!a.ready?'…':paMoney(a.total.parts[k]);
  const values=result.rows.map(r=>TPPrice.materialValuation(r,result,db.quote)),quantity=k=>values.some(v=>v.error)?'Cần kiểm tra':num(values.reduce((s,v)=>s+(v[k]||0),0),3);
  let rows=section('1. Hệ số và cách tính');
  rows+=row('Thứ tự hình thành giá',()=>esc(paSequenceText()));
  rows+=row('Nhánh tính của từng sản phẩm',a=>a.products.map(p=>esc(p.node.name)+': '+(a.id==='special'?esc(p.sourceMethodName):a.id==='tmc'?(p.tmc?.scope==='detail'?'Chi tiết (ngoài TMC)':'Thang máng cáp'):a.id.startsWith('group:')?(['formula','components'].includes(p.groupBranch)?esc(a.name):'Chi tiết (ngoài nhóm)'):esc(a.name))).join('<br>'));
  rows+=row('Chi phí chung / quản lý / đặc thù SX',a=>a.products.map(p=>esc(p.node.name)+': '+[p.policyRates.overhead,p.policyRates.management,p.policyRates.special].map(v=>num(v,2)+'%').join(' / ')).join('<br>'),{explain:'Hệ số nhân lần lượt. Kg/đối thủ/công thức nhóm: chi phí này chỉ là tham khảo.'});
  rows+=row('Hệ số lợi nhuận / xử lý / đơn hàng / khách hàng',a=>['kg','competitor'].includes(a.id)?'Đã nằm trong giá trọn gói':a.products.map(p=>esc(p.node.name)+': '+(p.saleSteps||[]).map(x=>esc(x.name||x.key)+': '+num(x.percent)+'%').join(' → ')).join('<br>'));
  rows+=row('Yếu tố SX bổ sung',()=> (result.pricing.productionFactors||[]).filter(f=>f.enabled!==false).map(f=>esc(f.name)+': '+num(f.percent)+'%').join(' → ')||'—');
  rows+=row('Công thức nhóm',a=>a.products.filter(p=>p.groupCalculation).map(p=>esc(p.node.name)+': '+esc(p.groupCalculation.formula)).join('<br>')||'—');
  if(PA.costDetails){
   rows+=section('2. Khối lượng, diện tích → chi phí vật tư');
   rows+=row('Khối lượng phôi (kg)',a=>num(a.total.weight,3));
   rows+=row('Diện tích bề mặt (m²)',a=>num(a.total.area,3));
   rows+=row('KL vật tư tính tiền (kg) — chi tiết',()=>quantity('weight'),{explain:'Phôi + hao hụt đã khai; dòng cũ theo khổ mua. TMC đối chiếu lượng phôi và hao hụt riêng ở bảng phân rã TMC.'});
   rows+=row('Diện tích vật tư tính tiền (m²) — chi tiết',()=>quantity('area'));
   rows+=row('KL vật tư phụ quy đổi (kg) — chi tiết',()=>quantity('auxiliaryWeight'),{explain:'Chỉ để tính giá trị vật tư phụ; không cộng vào khối lượng thực hiện hoặc vận chuyển.'});
   for(const k of ['stock','ancillary','allowance','finishing'])rows+=row(paNames[k],a=>cash(a,k));
   rows+=row('Tổng chi phí vật tư',a=>paMoney(a.total.material),{className:'pa-subtotal'});
   rows+=section('3. Nguyên công thực hiện → chi phí nguyên công');
   const operations=Object.values(result.nodes).flatMap(r=>(r.ownOps||[]).filter(o=>!o.skipped).map(o=>({r,o})));
   for(const {r,o} of operations)rows+=row(esc(r.node.name)+' / '+esc(o.name),a=>o.error?esc(o.error):num(o.basis,3)+' '+esc(o.unit)+' × '+money(o.rate)+' đ → '+money(o.cost)+' đ'+(a.id==='tmc'||a.id.startsWith('group:')?' (tham khảo chi tiết)':''),{explain:o.mode==='outside'?'Thuê ngoài':'Tại xưởng'});
   for(const pkg of result.packages||[])rows+=row('Gói thuê: '+esc(pkg.output),()=>num(pkg.basis,3)+' '+esc(pkg.unit)+' × '+money(pkg.rate)+' đ → '+money(pkg.cost)+' đ');
   rows+=row('Nhân công TMC theo khổ rộng',a=>!['tmc','special'].includes(a.id)?'—':a.products.flatMap(p=>(p.tmc?.items||[]).map(i=>esc(p.node.name)+' / '+esc(i.name)+': '+num(i.basis,3)+' '+esc(i.unit)+' → '+money(i.labor)+' đ')).join('<br>')||'—');
   for(const k of ['factory','outside'])rows+=row(paNames[k],a=>cash(a,k),{className:'pa-subtotal'});
   rows+=section('4. Chi phí khác và giá gốc');
   for(const k of ['tmcCommon','incoming','outgoing'])rows+=row(paNames[k],a=>cash(a,k));
   rows+=row('Chi phí trực tiếp sản xuất',a=>paMoney(a.total.direct),{className:'pa-subtotal'});
   const factorRows=()=>{for(const [k,label] of [['overhead','Chi phí chung'],['management','Chi phí quản lý']])rows+=row(label,a=>paMoney(a.total[k]));};
   if(!TPPrice.currentFlow(db.quote))factorRows();
   for(const [k,label] of [['special','Chi phí đặc thù sản xuất'],['productionExtras','Yếu tố SX bổ sung']])rows+=row(label,a=>paMoney(a.total[k]));
   rows+=row('Giá sản xuất',a=>paMoney(a.total.production),{className:'pa-subtotal'});
   for(const k of ['delivery','install'])rows+=row(paNames[k],a=>cash(a,k));
   if(TPPrice.currentFlow(db.quote)){rows+=row('Cơ sở trước chi phí chung / quản lý',a=>paMoney(a.products.reduce((sum,p)=>sum+p.baseBeforeCommon,0)));factorRows();}
   rows+=row('Giá gốc',a=>paMoney(a.total.cost),{className:'pa-subtotal',explain:'Tổng vật tư + nguyên công + chi phí khác. Kg/đối thủ/công thức nhóm dùng giá gốc chi tiết làm tham khảo.'});
   for(const [k,label] of [['profitMarkup','Khoản cộng theo hệ số lợi nhuận'],['processing','Khoản xử lý'],['order','Khoản đơn hàng'],['customer','Khoản khách hàng'],['saleExtras','Yếu tố bán bổ sung']])rows+=row(label,a=>['kg','competitor'].includes(a.id)?'Trong giá trọn gói':paMoney(a.total[k]),{explain:'Khoản cấu thành giá bán; không cộng lại vào tổng giá gốc.'});
  }
  rows+=section('5. Giá chào và phần còn lại');
  rows+=row('Phạm vi giá kg / đối thủ',a=>['kg','competitor'].includes(a.id)?a.products.map(p=>esc(p.node.name)+': '+esc(paScopeSummary(p.node,a.id))).join('<br>'):'—');
  rows+=row('Phí chưa gồm — cộng từ tính toán',a=>['kg','competitor'].includes(a.id)?paMoney(a.products.reduce((sum,p)=>sum+(p.benchmarkSupplement?.amount||0),0)):'—');
  rows+=row('Giá chào trước thuế',a=>a.ready&&result.tax.methods[a.id].comparable?paMoney(a.total.sell):'Chưa đủ căn cứ giá/thuế',{className:'pa-selling'});
  rows+=row('Thuế đầu ra',a=>a.ready&&result.tax.methods[a.id].comparable&&result.tax.outputKnown?a.total.taxBreakdown.map(g=>num(g.rate)+'%: '+money(g.vat)).join('<br>'):'Chưa xác nhận');
  rows+=row('Tổng chào sau thuế',a=>a.ready&&result.tax.methods[a.id].comparable&&result.tax.outputKnown?paMoney(a.total.grand):'Chưa xác nhận',{className:'pa-grand'});
  rows+=row('Phần còn lại sau giá gốc',a=>a.ready&&result.tax.costKnown&&result.tax.methods[a.id].comparable?paMoney(a.total.profit):'Chưa xác nhận',{explain:'Giá chào trước thuế − giá gốc. Là số dự tính để đối chiếu; chưa phải lợi nhuận ròng thực tế.'});
  rows+=row('Phần còn lại sau giá gốc và xử lý',a=>a.ready&&result.tax.costKnown&&result.tax.methods[a.id].comparable?paMoney(a.total.profit-a.total.processing):'Chưa xác nhận',{explain:'Khoản xử lý chỉ trừ một lần. Không trừ lại vật tư/nguyên công đã nằm trong giá gốc.'});
  const taxRows=taxComparisonRows(row);
  return `<div class="section-toolbar"><div><h2>So sánh và chọn giá chào</h2><p>Nhìn cùng một bảng, chọn một phương án cho tất cả sản phẩm.</p></div><div class="actions">${paButton('Giá kg / đối thủ','product-inputs')}${gpButton('Cài đặt theo nhóm','configure')}${TPGroupPrice.applicability(db.quote,'tmc').applicable?mfgButton('Chuỗi giá riêng TMC','policy'):''}${paButton('Hệ số & chi phí','policy')}${btn('↶ Hoàn tác','ux-undo',`data-undo-button ${UX.undo.length?'':'disabled'}`)}</div></div>`+
    paFlowNotice()+
    cfPanel()+gpComparisonPanel()+`<div class="panel pa-comparison ${alternatives.length===1?'pa-single':''} table-scroll" data-pa-scroll ${alternatives.length?'':'hidden'}><table><thead><tr><th>Toàn báo giá<small>${db.quote.products.length} sản phẩm · VNĐ</small></th>${alternatives.map(a=>`<th class="${chosen===a.id?'pa-chosen':''}"><span class="pa-method-name">${esc(a.name)}</span><small>${chosen===a.id?'Đang dùng làm giá chào':'Chỉ đối chiếu'}</small>${a.errors.length?`<small class="pa-missing">${esc(a.errors[0])}</small>`:''}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`+
    `<div class="pa-under-table">${paButton(PA.costDetails?'Thu gọn cơ cấu chi phí':'Xem cơ cấu chi phí','toggle-costs')}<span>Cách tính nhóm dùng để đối chiếu giá, không thay chi phí sản xuất thực tế.</span></div>`+
    `<details class="pa-tax-detail"><summary>Đối chiếu giá, nguồn và điều kiện thuế</summary><div class="table-scroll"><table><thead><tr><th>Nội dung</th>${alternatives.map(a=>`<th>${esc(a.name)}</th>`).join('')}</tr></thead><tbody>${taxRows}</tbody></table></div></details>`+gpFinalChoice()+renderFinalPrices()+
    (result.warnings.length?`<div class="notice warning"><strong>Giá chào dưới giá gốc</strong><span>${result.warnings.map(esc).join('<br>')}</span></div>`:'')+
    `<div class="pa-checkout"><div><span>Giá cuối sau thuế · ${esc(result.alternatives[chosen].name)}</span><small>${result.tax.releaseErrors.length?'THỬ TÍNH — CHƯA ĐỦ CĂN CỨ GIÁ/THUẾ':''}</small><strong data-pa-grand>${result.errors.length?'Cần kiểm tra dữ liệu':money(t.grand)+' ₫'}</strong><small>${Object.keys(db.quote.pricing.overrides||{}).length?'Có giá chốt riêng. Bản so sánh phía trên vẫn giữ các giá đề xuất.':'Đang dùng đơn giá đề xuất.'}</small></div>${btn('Xem bản chào giá →','preview','','primary')}</div>`;
}
function renderFinalPrices(){return `<section class="panel pa-final"><div class="panel-head"><div><h2>Giá chốt từng sản phẩm</h2><p>Áp chung phương án; chỉ sửa riêng đơn giá cuối khi có lý do.</p></div></div><div class="table-scroll"><table><thead><tr><th>Sản phẩm</th><th class="right">Kg phôi / SP</th><th class="right">Giá đề xuất / SP</th><th class="right">Giá chốt / SP</th><th class="right">Thành tiền</th><th></th></tr></thead><tbody>${result.products.map(p=>`<tr><td><strong>${esc(p.node.name)}</strong><small class="subtext">${num(p.node.qty)} ${esc(p.node.unit||'bộ')}${p.override?' · '+esc(p.override.reason):''}</small></td><td class="right mono">${num(p.weight/p.node.qty,3)}</td><td class="right mono">${money(p.suggestedUnit)}</td><td class="right mono">${money(p.unitSell)}${p.override?'<small class="subtext">Chốt riêng</small>':''}</td><td class="right mono">${money(p.sell)}</td><td>${paButton(p.override?'Rà lại giá chốt':'Chốt giá riêng','final-price',`data-id="${p.node.id}"`,'small')}${p.override?paButton('Về đề xuất','clear-price',`data-id="${p.node.id}"`,'small quiet'):''}</td></tr>`).join('')}</tbody></table></div></section>`;}
function renderOperationMatrix(){
  if(!db.quote.pricing)return paIntro()+`<div class="notice">Bật luồng mới để khai công đoạn trên bảng tổng và xem hệ số tác động.</div>`;
  const rates=db.quote.ratesSnapshot.filter(r=>r.operationType!=='package'||C.flatten(db.quote.products).some(n=>n.ops?.some(op=>op.id===r.id))),nodes=C.flatten(db.quote.products).filter(n=>foldText(n.name+' '+(n.materialId||'')).includes(foldText(PA.query)));
  return `<div class="section-toolbar"><div><h2>Công đoạn thực hiện</h2><p>Tích ngay tại dòng cần làm. Chi phí chỉ tính tại đúng cấp được khai báo.</p></div><div class="actions"><button type="button" class="button" data-operation-density>${PA.expandedMatrix?'Thu gọn bảng':'Hiện chi tiết'}</button>${paButton('Đơn giá & định mức','quote-rates')}${btn('+ Chọn công đoạn','new-rate')}</div></div>`+
    `<div class="pa-operation-tools"><label class="searchbox"><input aria-label="Tìm dòng công đoạn" data-pa-search value="${esc(PA.query)}" placeholder="Tìm sản phẩm, cấu kiện hoặc mã vật tư..."></label><span>Xưởng là mặc định. Thuê ngoài chỉ đổi ở công việc cần thuê.</span></div>`+
    `<div class="panel table-scroll pa-operations ${PA.expandedMatrix?'':'pa-compact'}" data-pa-scroll><table><thead><tr><th>Sản phẩm / cấu kiện / vật tư</th>${rates.map(rate=>`<th>${esc(rate.name)}<small>${rate.tmcReplace?'Giá thang máng cáp thay tiền công tại xưởng':TPWork.recipes(rate).length?'Có vật tư theo định mức':'Công đoạn riêng'}</small></th>`).join('')}</tr></thead><tbody>${nodes.map(n=>{
      const r=result.nodes[n.id],depth=(C.nodePath(db.quote.products,n.id)||[]).length-1;
      return `<tr><th scope="row"><div style="padding-left:${Math.min(depth,3)*12}px"><span class="pa-node-kind">${n.kind==='product'?'SP':n.kind==='component'?'CK':'VT'}</span><strong>${esc(n.kind==='material'?n.materialId:n.name)}</strong><small>${n.kind==='material'?esc(n.name)+' · ':''}SL toàn báo giá: ${num(r.count)}</small>${paButton('Chi phí riêng','node-costs',`data-id="${n.id}"`,'small quiet')}${mfgNodeActions(n)}<button type="button" class="button small pa-row-open" data-ux="row-actions" data-id="${n.id}" aria-label="Chi tiết ${esc(n.name)}">⋯</button></div></th>${rates.map(rate=>{
        const index=(n.ops||[]).findIndex(op=>op.id===rate.id),op=n.ops?.[index],computed=r.ownOps?.[index];
        return `<td><label class="pa-op-check"><input type="checkbox" data-pa-op-toggle data-id="${n.id}" data-rate="${rate.id}" ${op?'checked':''} aria-label="${esc(rate.name)} tại ${esc(n.name)}"><span>${op?'Đã chọn':'Chọn'}</span></label>${computed?.skipped?`<div class="mfg-skip">Đã gồm trong gói thuê</div>`:''}${op?`<select aria-label="Nơi làm ${esc(rate.name)} tại ${esc(n.name)}" data-pa-op-mode data-id="${n.id}" data-index="${index}"><option value="inside" ${op.mode==='inside'?'selected':''}>Tại xưởng</option><option value="outside" ${op.mode==='outside'?'selected':''}>Thuê ngoài</option></select><button type="button" class="button small pa-op-quantity" data-pa="op-detail" data-id="${n.id}" data-index="${index}">${op.basisMode==='manual_total'?'Tổng lượng: '+num(op.workQuantity)+' '+esc(computed?.unit||''):['kg','tấn','m²','m³'].includes(computed?.unit)&&op.basisMode!=='manual_unit'?'Lượng theo '+esc(computed.unit):num(op.basisMode==='manual_unit'?op.workQuantity:(op.amount??1))+' '+esc(computed?.unit||'lần')+' / đơn vị'} · sửa</button>${paButton(`${computed?.error?'Cần kiểm tra':money(computed?.cost)+' ₫'}<small>${num(computed?.basis)} ${esc(computed?.unit||'')} · xem / sửa</small>`,'op-detail',`data-id="${n.id}" data-index="${index}"`,'pa-op-total')}${TPWork.recipes(rate).length?`<button type="button" class="button small" data-qoc-recipes="${esc(n.id)}" data-index="${index}">Vật tư định mức (${TPWork.recipes(rate).length})</button>`:''}`:''}</td>`;
      }).join('')}</tr>`;
    }).join('')||`<tr><td colspan="${rates.length+1}">Không có dòng phù hợp.</td></tr>`}</tbody></table></div>`+
    `<div class="notice">Thêm ở cấp sản phẩm là một công việc bổ sung, không tự thay công đoạn cùng tên ở cấu kiện. Rà bảng này để tránh khai cùng một công việc ở cả cha và con.</div>`+
    `<section class="panel"><div class="panel-head"><div><h2>Vật tư hoàn thiện tự tính</h2><p>Sinh từ công đoạn đã chọn; thay diện tích hoặc định mức sẽ tính lại.</p></div></div>${result.generated.length?`<div class="table-scroll"><table><thead><tr><th>Nơi sử dụng</th><th>Mã vật tư</th><th>Định mức</th><th class="right">Lượng</th><th class="right">Thành tiền</th></tr></thead><tbody>${result.generated.map(g=>`<tr><td>${esc(C.findNode(db.quote.products,g.ownerId)?.name)}<small class="subtext">${esc(g.rateName)}</small></td><td>${esc(g.materialId)}<small class="subtext">${esc(g.name)}</small></td><td>${num(g.norm,4)} ${esc(g.unit)}/${esc(g.basis)} × ${num(g.layers||1)} lớp${g.loss?' + '+num(g.loss)+'% hao hụt':''}</td><td class="right mono">${num(g.quantity,4)} ${esc(g.unit)}</td><td class="right mono">${money(g.cost)}</td></tr>`).join('')}</tbody></table></div>`:`<p class="muted-row">Chưa phát sinh vật tư hoàn thiện. Giá thuê đã gồm vật tư thì không cộng lại tại đây.</p>`}</section>`;
}
function renderRatebookAdvanced(){return heading('Đơn giá đầu vào','Giá gốc, yếu tố tác động và định mức dùng lại cho các báo giá.',btn('+ Nguyên công','new-rate')+btn('Áp dụng vào báo giá','refresh-prices','','primary'))+
  `<div class="filter-tabs"><button data-rate-tab="materials">Đơn giá vật tư</button><button data-rate-tab="operations" class="active">Nguyên công & hệ số</button></div><div class="notice">Đây là danh mục chung. Sửa xong bấm “Áp dụng vào báo giá” để cập nhật bản đang làm; các phiên bản đã lưu không tự đổi.</div>`+paRateTable(db.rates,true);}
function paRateTable(rates,catalog){return `<div class="panel table-scroll"><table class="pa-ratebook"><thead><tr><th>Công đoạn</th><th>Tại xưởng</th><th>Thuê ngoài</th><th>Yếu tố tác động</th><th>Định mức vật tư</th><th></th></tr></thead><tbody>${rates.map(rate=>`<tr><td><strong>${esc(rate.name)}</strong><small class="subtext">${rate.tmcReplace?'Công tại xưởng được thay bằng giá TMC':''}</small></td><td class="mono">${money(rate.inside)} đ/${esc(rate.insideUnit||rate.unit)}</td><td class="mono">${money(rate.outside)} đ/${esc(rate.outsideUnit||rate.unit)}</td><td>${(rate.factors||[]).map(f=>`<span class="pa-factor-chip ${f.enabled===false?'off':''}">${esc(f.name)}${f.enabled===false?' · tắt':''}</span>`).join('')||'<span class="muted">Giá cố định</span>'}</td><td>${TPWork.recipes(rate).length?TPWork.recipes(rate).map(r=>`${esc(r.spec?.id)}<small class="subtext">${num(r.norm,4)} ${esc(r.spec?.unit)}/${esc(r.basis)} × ${num(r.layers||1)} lớp</small>`).join(''):'Không khai riêng'}</td><td>${paButton('Sửa đơn giá / hệ số','edit-rate',`data-id="${rate.id}" ${catalog?'data-catalog="1"':''}`,'small')}</td></tr>`).join('')}</tbody></table></div>`;}
function paSalesFactor(f){return `<div class="pa-sales-factor" data-factor-id="${esc(f.id)}">${field('Tên yếu tố bổ sung','extra-name-'+f.id,f.name,'text','required')}${field('Hệ số (%)','extra-value-'+f.id,f.percent,'number','min="-99.99" step="any" required')}${field('Căn cứ / giải thích','extra-reason-'+f.id,f.reason||'','text','required')}${paButton('×','remove-sales-factor','aria-label="Xóa yếu tố bán"','square')}</div>`;}
function paPolicy(){const q=db.quote,p=q.pricing;
  openDialog('Hệ số và chi phí của báo giá',`<p class="help-text">Thứ tự theo công thức khách gửi. Số hệ số là minh họa, có thể thay đổi.</p><h3>1. Hệ số chi phí</h3><div class="form-grid three">${[['Chi phí chung (%)','overhead'],['Quản lý (%)','management'],['Khác trong sản xuất (%)','special']].map(([s,k])=>field(s,k,p[k],'number','min="-99.99" step="any" required')).join('')}</div><p class="help-text">${paSequenceText()} Đặc thù SX và yếu tố SX bổ sung vẫn thuộc chi phí sản xuất.</p><p class="help-text">Yếu tố SX bổ sung dưới đây thuộc phương án tính toán, không tự áp sang TMC/kg/đối thủ.</p><div id="pa-production-factors">${(p.productionFactors||[]).filter(f=>f.enabled!==false).map(paSalesFactor).join('')}</div><button type="button" class="button" data-b3="add-production-factor">+ Thêm yếu tố sản xuất</button><h3>2. Khai khoản chi (phân lớp theo nhãn)</h3><div class="form-grid">${[['VC nhập phôi / vật tư (đ)','incoming'],['VC thuê ngoài (đ)','outgoing'],['Giao hàng (đ)','delivery'],['Lắp đặt (đ)','install']].map(([s,k])=>field(s,k,p[k],'number','min="0" step="1" required')).join('')}</div><p class="help-text">Nhập tổng chi phí của toàn báo giá; demo phân bổ theo kg phôi, nếu không có phôi thì theo số lượng. Các khoản riêng ở từng cấp cộng thêm. Đây là số tiền, không phải đơn giá vận chuyển.</p><h3>3. Tính giá bán từ giá gốc</h3><div class="form-grid">${[['Lợi nhuận (%)','profit'],['Xử lý (%)','processing'],['Đơn hàng (%)','order'],['Khách hàng (%)','customer']].map(([s,k])=>field(s,k,p[k]??0,'number','min="-99.99" step="any" required')).join('')}</div><div class="formula-explainer"><p>Giá gốc × (1 + lợi nhuận) × (1 + xử lý) × (1 + đơn hàng) × (1 + khách hàng) × các yếu tố bổ sung.<br>Ví dụ tăng 10% nhập 10; giảm 5% nhập −5. Không cộng gộp các hệ số.</p></div><div id="pa-sales-factors">${[...(p.reserve?[{id:'old-reserve',name:'Dự phòng bổ sung',percent:p.reserve}]:[]),...(p.salesFactors||[])].filter(f=>f.enabled!==false).map(paSalesFactor).join('')}</div>${paButton('+ Thêm yếu tố giá bán','add-sales-factor')}${field('Thuế thử tính (%)','vat',q.vat,'number','min="0" max="100" step="any" required')}`, 'Lưu và tính lại', f=>{
    const values=Object.fromEntries(['overhead','management','special','profit','processing','order','customer','incoming','outgoing','install','delivery'].map(k=>[k,Number(f.get(k))]));
    const factors=[...document.querySelectorAll('#pa-sales-factors .pa-sales-factor')].map(el=>({id:el.dataset.factorId,name:String(f.get('extra-name-'+el.dataset.factorId)).trim(),percent:Number(f.get('extra-value-'+el.dataset.factorId)),reason:String(f.get('extra-reason-'+el.dataset.factorId)||'').trim(),enabled:true}));
    const productionFactors=[...document.querySelectorAll('#pa-production-factors .pa-sales-factor')].map(el=>({id:el.dataset.factorId,name:String(f.get('extra-name-'+el.dataset.factorId)||'').trim(),percent:Number(f.get('extra-value-'+el.dataset.factorId)),reason:String(f.get('extra-reason-'+el.dataset.factorId)||'').trim(),enabled:true}));
    saveAndClose(()=>{Object.assign(p,values,{reserve:0,salesFactors:factors,productionFactors});q.vat=Number(f.get('vat'));},'Đã tính lại từ giá sản xuất → giá gốc → giá bán');
  });$('#dialog').classList.add('wide-dialog');
}
function paProductInputs(){openDialog('Giá đầu vào của các phương án',`<div class="notice">Giá kg và đối thủ cần khai phạm vi đã gồm. Chỉ cộng khoản chưa gồm từ tính toán. Khai đã/chưa gồm thuế tại “Khai giá và điều kiện thuế”. Nếu đổi giá tại đây, phải rà lại điều kiện thuế tương ứng. Khối lượng dùng là kg phôi, không phải kg mua.</div>${db.quote.products.map(n=>`<section class="pa-input-product"><h3>${esc(n.name)}</h3><div class="form-grid">${field('Đơn giá/kg phôi (đ/kg)','kg-'+n.id,n.pricePerKg??'','number','min="0" step="1"')}${field('Giá đối thủ (đ/'+(n.unit||'bộ')+')','competitor-'+n.id,n.competitorPrice??'','number','min="0" step="1"')}${select('Nhóm áp dụng cách tính giá','scope-'+n.id,[['unknown','Chưa xác định'],...TPGroupPrice.groups(db.quote).map(g=>[g.id,g.name])],TPGroupPrice.resolve(db.quote,n).id)}${select('Chủng loại dùng bảng TMC','tmc-'+n.id,[['','Chưa chọn bảng nhân công'],...db.quote.pricing.tmcTables.map(t=>[t.id,t.name])],n.tmcKind||'')}${field('Khổ rộng tra TMC (mm)','width-'+n.id,n.tmcWidth??n.params?.W??'','number','min="1" step="any"')}${field('Chiều dài tra TMC (mm)','length-'+n.id,n.tmcLength??n.params?.L??'','number','min="1" step="any"')}</div>${paScopeFields(n,'kg')}${paScopeFields(n,'competitor')}<p class="help-text">Khổ và dài đang kế thừa kích thước sản phẩm. Nhập số khác sẽ dùng giá trị riêng; nhập lại bằng kích thước chung để nối lại.</p></section>`).join('')}`,'Lưu đầu vào',f=>saveAndClose(()=>{
    for(const n of db.quote.products){paReadScope(f,n,'kg');paReadScope(f,n,'competitor');n.pricePerKg=f.get('kg-'+n.id)===''?null:Number(f.get('kg-'+n.id));n.competitorPrice=f.get('competitor-'+n.id)===''?null:Number(f.get('competitor-'+n.id));n.tmcKind=f.get('tmc-'+n.id);TPGroupPrice.assign(db.quote,n.id,f.get('scope-'+n.id));
      for(const [field,key,param] of [['width','tmcWidth','W'],['length','tmcLength','L']]){const v=f.get(field+'-'+n.id);if(v===''||Number(v)===n.params?.[param])delete n[key];else n[key]=Number(v);}}
  }));$('#dialog').classList.add('wide-dialog');}
function paTmc(){const p=db.quote.pricing;
  openDialog('Bảng nhân công & hao hụt TMC',`${field('Hao hụt riêng TMC (%)','loss',p.tmcLoss,'number','min="0" max="1000" step="any" required')}<p class="help-text">Phôi × (1 + hao hụt TMC). Nhân công bên dưới thay đúng các công việc tại xưởng đã đánh dấu “TMC thay thế” trong đơn giá; hoàn thiện và thuê ngoài vẫn tính riêng.</p>${p.tmcTables.map(t=>`<section class="pa-tmc-editor" data-tmc-id="${t.id}"><h3>${esc(t.name)}</h3>${select('Đơn vị nhân công','unit-'+t.id,['m','cái'],t.unit)}<div class="pa-tier-head"><span>Đến khổ rộng (mm), để trống = lớn hơn tất cả</span><span>Giá (đ/ĐVT)</span></div>${t.tiers.map(s=>paTierRow(s,'price')).join('')}${paButton('+ Thêm bậc','add-tier','','small')}</section>`).join('')}`,'Lưu bảng TMC',f=>{
    const tables=p.tmcTables.map(t=>{const section=$(`[data-tmc-id="${t.id}"]`);const tiers=readTiers(section,'price');TPPrice.tier(0,tiers,'price');return {...t,unit:f.get('unit-'+t.id),tiers};});
    saveAndClose(()=>{p.tmcLoss=Number(f.get('loss'));p.tmcTables=tables;});
  });$('#dialog').classList.add('wide-dialog');
}
function paTierRow(s,key='percent'){return `<div class="pa-tier-row"><input class="pa-max" aria-label="Mốc bậc" type="number" min="0" step="any" value="${s.max===null?'':esc(s.max)}" placeholder="Không giới hạn"><input class="pa-tier-value" aria-label="${key==='price'?'Đơn giá bậc':'Hệ số bậc (%)'}" type="number" min="${key==='price'?0:-99.99}" step="any" value="${esc(s[key])}" required>${paButton('×','remove-tier','aria-label="Xóa bậc"','square quiet')}</div>`;}
function readTiers(section,key='percent'){return [...section.querySelectorAll('.pa-tier-row')].map(row=>({max:row.querySelector('.pa-max').value===''?null:Number(row.querySelector('.pa-max').value),[key]:Number(row.querySelector('.pa-tier-value').value)}));}
function paFactorGroup(f){return `<section class="pa-factor-editor" data-factor-id="${esc(f.id)}"><div class="form-grid">${field('Tên yếu tố','factor-name-'+f.id,f.name,'text','required')}${select('Giá trị dùng để tra','factor-param-'+f.id,[['T','Chiều dày T (mm)'],['W','Khổ rộng W (mm)'],['L','Chiều dài L (mm)'],['H','Chiều cao H (mm)'],['count','Số lượng toàn báo giá tại cấp này'],['weight','Kg phôi tại cấp này'],['area','Diện tích bề mặt (m²)']],f.param)}</div><div class="pa-factor-actions"><label><input type="checkbox" name="factor-enabled-${f.id}" ${f.enabled!==false?'checked':''}> Áp dụng yếu tố này</label>${paButton('Xóa yếu tố','remove-factor','','small quiet')}</div><div class="pa-tier-head"><span>Đến mức, trống ở dòng cuối = không giới hạn</span><span>Tăng/giảm (%)</span></div>${f.tiers.map(s=>paTierRow(s)).join('')}${paButton('+ Thêm bậc','add-tier','','small')}</section>`;}
function paEditRate(id,catalog){const rates=catalog?db.rates:db.quote.ratesSnapshot,rate=rates.find(r=>r.id===id);if(!rate)return;
  openDialog(`${catalog?'Danh mục':'Báo giá này'}: ${esc(rate.name)}`,`<div class="notice">Đơn giá áp dụng = giá gốc × (1 + hs1) × (1 + hs2) × …; mỗi yếu tố tra theo giá trị ở cấp đang làm. Các khoảng nối tiếp: trên mốc trước đến hết mốc hiện tại.</div><div class="form-grid">${field('Giá gốc tại xưởng','inside',rate.inside,'number','min="0" step="any" required')}${select('Cơ sở tại xưởng','insideUnit',['kg','tấn','m²','m³','m','lần','bộ','cái','gói'],rate.insideUnit||rate.unit)}${field('Giá thuê ngoài','outside',rate.outside,'number','min="0" step="any" required')}${select('Cơ sở thuê ngoài','outsideUnit',['kg','tấn','m²','m³','m','lần','bộ','cái','gói'],rate.outsideUnit||rate.unit)}</div><div class="pa-factor-actions"><label><input type="checkbox" name="tmcReplace" ${rate.tmcReplace?'checked':''}> Dùng bảng giá thang máng cáp thay tiền công tại xưởng của công đoạn này</label><label><input type="checkbox" name="outsideFactors" ${rate.outsideFactors?'checked':''}> Giá thuê ngoài cũng áp hệ số</label></div><h3>Yếu tố tác động</h3><div id="pa-factor-list">${(rate.factors||[]).map(paFactorGroup).join('')}</div>${paButton('+ Thêm yếu tố','add-factor')}<h3>Vật tư phát sinh khi hoàn thiện</h3><div class="form-grid">${select('Mã vật tư','finishMaterial',[['','Không khai riêng'],...db.materials.filter(m=>m.shape==='piece').map(m=>[m.id,m.id+' / '+m.name])],rate.consumption?.spec?.id||'')}${select('Định mức theo','finishBasis',['m²','kg'],rate.consumption?.basis||'m²')}${field('Lượng vật tư / một đơn vị cơ sở','finishNorm',rate.consumption?.norm??0,'number','min="0" step="any" required')}</div><p class="help-text">Tại xưởng: vật tư và tiền công tách riêng. Thuê ngoài mặc định giá đã gồm vật tư, không cộng lại; thay lựa chọn ở chi tiết công đoạn nếu bên mình cấp vật tư.</p>`,'Lưu và tính lại',f=>{
    const factors=[...document.querySelectorAll('.pa-factor-editor')].map(s=>{const fid=s.dataset.factorId,tiers=readTiers(s);TPPrice.tier(0,tiers);return {id:fid,name:String(f.get('factor-name-'+fid)).trim(),param:f.get('factor-param-'+fid),enabled:f.has('factor-enabled-'+fid),tiers};});
    const m=db.materials.find(m=>m.id===f.get('finishMaterial'));
    const changes={inside:Number(f.get('inside')),outside:Number(f.get('outside')),insideUnit:f.get('insideUnit'),outsideUnit:f.get('outsideUnit'),factors,tmcReplace:f.has('tmcReplace'),outsideFactors:f.has('outsideFactors')};
    saveAndClose(()=>{Object.assign(rate,changes);if(m)rate.consumption={basis:f.get('finishBasis'),norm:Number(f.get('finishNorm')),spec:C.copy(m)};else delete rate.consumption;},catalog?'Đã lưu danh mục. Áp dụng vào báo giá khi muốn cập nhật.':'Đã tính lại công đoạn và vật tư hoàn thiện');
  });$('#dialog').classList.add('wide-dialog');
}
function paOperationDetail(id,index){const n=C.findNode(db.quote.products,id),op=n?.ops?.[index],r=result.nodes[id]?.ownOps[index];if(!op||!r)return;const rate=db.quote.ratesSnapshot.find(x=>x.id===op.id);
  openDialog(`${esc(rate?.name||'Công đoạn')} / ${esc(n.name)}`,`${paErrors(r.error?[r.error]:[])}<div class="pa-calculation"><span>Giá gốc ${money(r.base??r.rate)} đ/${esc(r.unit)}</span>${r.factors.map(f=>`<div><strong>${esc(f.name)}</strong><span>${num(f.input,3)} → ${f.max===null?'trên '+num(f.min):num(f.min)+' < giá trị ≤ '+num(f.max)} → ${num(f.value)}%</span></div>`).join('')}<strong>Giá áp dụng: ${money(r.rate)} đ/${esc(r.unit)}</strong><strong>${num(r.basis,4)} ${esc(r.unit)} × ${money(r.rate)} = ${money(r.cost)} đồng</strong></div>${['kg','m²'].includes(r.unit)?'<p class="help-text">Lượng công việc lấy từ khối lượng/diện tích tại cấp này, không nhập lại.</p>':field('Định mức / một cấp này','amount',op.amount,'number','min="0" step="any" required')}${op.mode==='outside'?`<label class="pa-checkbox"><input name="included" type="checkbox" ${op.suppliesIncluded!==false?'checked':''}> Giá thuê đã gồm vật tư hoàn thiện</label><p class="help-text">Bỏ chọn chỉ khi bên mình cấp vật tư hoàn thiện và đơn giá thuê chưa có khoản này.</p>`:''}<div class="actions">${paButton('Sửa đơn giá & hệ số','edit-rate',`data-id="${op.id}"`)}</div>`,'Lưu công đoạn',f=>saveAndClose(()=>{if(f.has('amount'))op.amount=Number(f.get('amount'));if(op.mode==='outside')op.suppliesIncluded=f.has('included');}));
}
function paFinalPrice(id){const p=result.products.find(p=>p.node.id===id);if(!p)return;
  openDialog('Chốt giá riêng: '+esc(p.node.name),`<p>Phương án chung: <strong>${esc(result.alternatives[result.pricing.selected].name)}</strong>. Giá đề xuất ${money(p.suggestedUnit)} đ/${esc(p.node.unit||'bộ')}.</p>${field('Giá chốt trước thuế (đ/ĐVT)','value',p.unitSell,'number','min="0" step="1" required')}${field('Lý do điều chỉnh / xác nhận lại','reason',p.override?.reason||'','text','required')}<p class="help-text">Đổi khối lượng, giá gốc hoặc giá đề xuất sẽ yêu cầu rà lại giá chốt tay. Giá dưới gốc có cảnh báo, không âm thầm bị thay.</p>`,'Xác nhận giá chốt',f=>{const reason=String(f.get('reason')).trim();if(!reason)throw Error('Nhập lý do');saveAndClose(()=>{db.quote.pricing.overrides[id]={mode:result.pricing.selected,value:Number(f.get('value')),reason,signature:p.priceSignature};});});
}
function paRenderPreserve(){const scrolls=[...document.querySelectorAll('[data-pa-scroll]')].map(el=>[el.scrollLeft,el.scrollTop]);const y=scrollY;render();document.querySelectorAll('[data-pa-scroll]').forEach((el,i)=>{el.scrollLeft=scrolls[i]?.[0]||0;el.scrollTop=scrolls[i]?.[1]||0;});window.scrollTo(0,y);}
function paNodeCosts(id){const n=C.findNode(db.quote.products,id);if(!n)return;const r=result.nodes[id];
  openDialog('Chi phí riêng: '+esc(n.name),`<p>Nhập chi phí cho <strong>1 đơn vị ở cấp này</strong>. Toàn báo giá nhân ${num(r.count)}; không nhập lại chi phí đã có ở cấp con hoặc phần chung.</p><div class="form-grid">${[['Nhập vật tư (đ/đơn vị)','freightIn'],['Vận chuyển thuê ngoài (đ/đơn vị)','freightOut'],['Giao hàng (đ/đơn vị)','transport'],['Lắp đặt (đ/đơn vị)','install']].map(([name,key])=>field(name,key,n[key]||0,'number','min="0" step="any" required')).join('')}</div><p class="help-text">Nhập vật tư và vận chuyển thuê ngoài thuộc giá sản xuất. ${paSequenceText()}</p>`,'Lưu chi phí',f=>saveAndClose(()=>{for(const k of ['freightIn','freightOut','transport','install'])n[k]=Number(f.get(k));}));
}
function renderAdvancedPaper(){const q=db.quote,t=result.total;
  if(result.errors.length)return `<div class="panel panel-body"><h2>Chưa thể xuất bản chào giá</h2><p>Rà lại các cảnh báo trước khi tạo bản gửi khách.</p>${btn('Về phân tích giá','pa-pricing','','primary')}</div>`;
  return `<article class="paper"><div class="paper-head"><div class="paper-brand">${companyLogo()}<div><strong>TRƯỜNG PHÁT GROUP</strong><small>SẢN XUẤT & GIA CÔNG CƠ KHÍ</small></div></div><div class="paper-meta"><strong>${esc(q.id)}</strong><span>Ngày ${esc(q.date.split('-').reverse().join('/'))}</span></div></div><div class="paper-title"><h2>BẢNG CHÀO GIÁ</h2><p>${esc(q.project)}</p></div><div class="paper-customer"><span>Kính gửi</span><strong>${esc(q.customer)}</strong></div><div class="table-scroll"><table class="paper-table"><thead><tr><th>STT</th><th>Sản phẩm / thông số kỹ thuật</th><th>ĐVT</th><th class="right">SL</th><th class="right">Đơn giá</th><th class="right">Thành tiền</th></tr></thead><tbody>${result.products.map((p,i)=>`<tr><td>${i+1}</td><td><strong>${esc(p.node.name)}</strong><small class="subtext">${esc(quoteSpecificationFull(p.node))}${q.outputTax?.scope==='product'?' · Thuế GTGT '+num(TPTax.outputRate(q,p.node))+'%':''}</small></td><td>${esc(p.node.unit||'bộ')}</td><td class="right">${num(p.node.qty)}</td><td class="right mono">${money(p.unitSell)}</td><td class="right mono">${money(p.sell)}</td></tr>`).join('')}</tbody></table></div><div class="paper-totals"><div><span>Cộng trước thuế</span><strong>${money(t.beforeTax)} ₫</strong></div>${(t.taxBreakdown||[{rate:q.vat,vat:t.vat}]).map(g=>`<div><span>Thuế GTGT (${num(g.rate)}%)</span><strong>${money(g.vat)} ₫</strong></div>`).join('')}<div class="paper-grand"><span>TỔNG THANH TOÁN</span><strong>${money(t.grand)} ₫</strong></div></div><p class="pa-paper-scope">Đơn giá đã bao gồm vật tư, gia công, hoàn thiện, vận chuyển giao hàng và lắp đặt trong phạm vi khai báo của báo giá này. Thông số, phạm vi và điều kiện cụ thể cần thống nhất trước khi đặt hàng.</p><div class="paper-terms"><strong>Điều kiện chào giá</strong><p>Hiệu lực: ${num(q.valid,0)} ngày kể từ ngày báo giá.</p><p>${esc(q.notes||'').replace(/\n/g,'<br>')}</p></div><div class="pa-paper-sign"><strong>ĐẠI DIỆN TRƯỜNG PHÁT</strong><small>Ký, ghi rõ họ tên</small></div><div class="paper-demo">BẢN MINH HỌA NGHIỆP VỤ · Chưa phải báo giá giao dịch chính thức.</div></article>`;
}
function paMutation(action){const scrolls=[...document.querySelectorAll('[data-pa-scroll]')].map(el=>[el.scrollLeft,el.scrollTop]),y=scrollY;mutation(action);document.querySelectorAll('[data-pa-scroll]').forEach((el,i)=>{el.scrollLeft=scrolls[i]?.[0]||0;el.scrollTop=scrolls[i]?.[1]||0;});window.scrollTo(0,y);}
function installPricingUI(){
  const oldRefresh=actions['refresh-prices'];
  actions['refresh-prices']=()=>{if(!db.quote.pricing)return oldRefresh();openDialog('Cập nhật đơn giá cho báo giá?',`<p>Cập nhật giá vật tư theo mã / đơn vị, bảng nguyên công, vật tư hoàn thiện, bảng TMC và các khoản vận chuyển / lắp đặt đã chọn từ đơn giá đầu vào.</p><p>Giữ kích thước và cấu thành. Thay đơn giá/hệ số đã chỉnh riêng ở báo giá này bằng danh mục mới; báo giá trở về nháp để rà lại.</p>`,'Cập nhật và tính lại',()=>saveAndClose(()=>TPPrice.refreshPrices(db),'Đã cập nhật cả vật tư hoàn thiện. Rà lại giá trước khi duyệt.'));};
  actions['pa-pricing']=()=>{page='quote';tab='pricing';render();};
  const oldGuide=actions.guide,oldApprove=actions.approve;
  actions.guide=()=>{if(!db.quote.pricing)return oldGuide();openDialog('Thử một báo giá từ đầu đến cuối',`<ol class="pa-guide"><li><strong>Cấu thành sản phẩm:</strong> xem hai máng cáp mẫu, sửa số lượng hoặc kích thước chung.</li><li><strong>Công đoạn & định mức:</strong> tích công việc tại đúng dòng, chọn tại xưởng/thuê ngoài; bấm số tiền để xem cách tính. Vật tư sơn tự sinh ở bảng dưới.</li><li><strong>Khai triển & hao hụt:</strong> kiểm tra phần dư, chọn phần còn tận dụng. Nếu kích thước vừa đổi thì rà lại lựa chọn cũ.</li><li><strong>Phân tích giá:</strong> sửa hệ số hoặc đầu vào, chọn các cách đối chiếu phù hợp rồi chọn một phương án giá chào chung. Muốn sửa riêng đơn giá cuối, dùng Chốt giá riêng.</li><li><strong>Bản chào giá:</strong> kiểm tra tổng, duyệt thử và In / Lưu PDF. Bản in không có giá gốc hoặc hệ số nội bộ.</li></ol><p class="help-text">Số liệu minh họa, lưu trên trình duyệt; chưa có tài khoản hoặc phân quyền thật.</p><div class="actions">${paButton('Nạp lại ca mẫu','sample')}${btn('Khôi phục từ sao lưu','restore')}</div>`);};
  actions.approve=()=>{if(!db.quote.pricing||!result.warnings?.length)return oldApprove();if(result.errors.length)return toast('Xử lý các cảnh báo trước khi duyệt');openDialog('Xác nhận báo giá dưới giá gốc',`<div class="notice warning">${result.warnings.map(esc).join('<br>')}</div><p>Tổng sau thuế: <strong>${money(result.total.grand)} ₫</strong>. Đây là duyệt thử trên trình duyệt, chưa có phân quyền người duyệt.</p>`,'Vẫn duyệt bản minh họa',()=>{if(Quotes.conflict)return toast('Dữ liệu đã đổi ở thẻ khác; tải lại trước khi duyệt');closeDialog();db.quote.status='approved';quoteArchive();persist();render();});};
  document.addEventListener('click',event=>{const el=event.target.closest('[data-pa]');if(!el)return;event.preventDefault();const action=el.dataset.pa,id=el.dataset.id;
    if(action==='enable')openDialog('Chuyển báo giá này sang luồng mới?',`<p>Giữ toàn bộ sản phẩm, vật tư và kích thước. Cách tính giá sẽ chuyển từ biên lợi nhuận sang chuỗi hệ số; đơn giá có thể thay đổi và báo giá về nháp.</p><p>Vận chuyển đã khai ở từng cấp được đưa vào giao hàng tách riêng; cần rà lại đúng đầu mục. Giá kg, giá đối thủ và nhóm TMC chưa có phải bổ sung.</p><p class="help-text">Có thể Hoàn tác; nên sao lưu nếu cần giữ bản cũ độc lập.</p>`,'Chuyển và rà giá',()=>saveAndClose(()=>{TPPrice.enable(db);tab='pricing';}));
    else if(action==='sample')openDialog('Mở ca mẫu để tự thử?',`<p>Nạp hai máng cáp có sơn tại xưởng và mạ thuê ngoài, đủ bốn phương án để thử. Thay dữ liệu demo đang mở trên máy này.</p><p class="help-text">Sao lưu trước nếu cần giữ dữ liệu đang làm. Có thể Hoàn tác ngay sau khi nạp.</p>`,'Nạp ca mẫu',()=>saveAndClose(()=>{db=TPPrice.demoSeed();selected=db.quote.products[0].id;page='quote';tab='pricing';PA.query='';}));
    else if(action==='choose'){
      const mode=el.dataset.method;if(mode===db.quote.pricing.selected)return;
      if(!result.alternatives[mode]?.ready)return toast('Bổ sung dữ liệu trước khi chọn phương án này');
      const choose=()=>{db.quote.pricing.selected=mode;db.quote.pricing.overrides={};};
      if(Object.keys(db.quote.pricing.overrides||{}).length)openDialog('Đổi phương án và bỏ giá chốt riêng?',`<p>Toàn bộ sản phẩm chuyển sang phương án mới. Các giá chốt tay hiện tại sẽ được bỏ; có thể Hoàn tác.</p>`,'Đổi phương án',()=>saveAndClose(choose));else paMutation(choose);
    }
    else if(action==='toggle-costs'){PA.costDetails=!PA.costDetails;paRenderPreserve();}
    else if(action==='adopt-flow'){
      if(Team.loaded&&!Team.permissions.factors)return toast('Cần quyền sửa hệ số để đổi luồng giá');
      openDialog('Áp dụng luồng giá đã chốt 19/09?',`<p>Cộng giao hàng/lắp đặt trước chi phí chung và quản lý. Giữ lượng, đơn giá và phạm vi đặc thù. Giá chốt tay và xác nhận thuế cũ được bỏ để rà lại. Bản đã trình/duyệt phải mở bản sửa trước.</p>`,'Áp dụng và rà giá',()=>saveAndClose(()=>TPPrice.adoptFlow(db.quote)));
    }
    else if(action==='policy')paPolicy();
    else if(action==='product-inputs')paProductInputs();
    else if(action==='tmc')paTmc();
    else if(action==='quote-rates'){openDialog('Đơn giá & hệ số trong báo giá',`<p>Chỉnh ở đây chỉ áp dụng báo giá này. Muốn dùng lại cho báo giá khác, chỉnh tại Đơn giá đầu vào.</p>${paRateTable(db.quote.ratesSnapshot,false)}<div class="actions">${paButton('Bảng nhân công & hao hụt TMC','tmc')}</div>`);$('#dialog').classList.add('wide-dialog');}
    else if(action==='edit-rate')paEditRate(id,!!el.dataset.catalog);
    else if(action==='add-factor')$('#pa-factor-list').insertAdjacentHTML('beforeend',paFactorGroup({id:C.uid(),name:'Yếu tố mới',param:'T',enabled:true,tiers:[{max:null,percent:0}]}));
    else if(action==='remove-factor')el.closest('.pa-factor-editor').remove();
    else if(action==='add-tier')el.insertAdjacentHTML('beforebegin',paTierRow({max:null,percent:0,price:0},el.closest('.pa-tmc-editor')?'price':'percent'));
    else if(action==='remove-tier')el.closest('.pa-tier-row').remove();
    else if(action==='op-detail')paOperationDetail(id,Number(el.dataset.index));
    else if(action==='final-price')paFinalPrice(id);
    else if(action==='clear-price')paMutation(()=>delete db.quote.pricing.overrides[id]);
    else if(action==='add-sales-factor')$('#pa-sales-factors').insertAdjacentHTML('beforeend',paSalesFactor({id:C.uid(),name:'',percent:0}));
    else if(action==='remove-sales-factor')el.closest('.pa-sales-factor').remove();
    else if(action==='node-costs')paNodeCosts(id);
  });
  document.addEventListener('change',event=>{const el=event.target,d=el.dataset;
    if(el.hasAttribute('data-pa-op-toggle'))paMutation(()=>{const n=C.findNode(db.quote.products,d.id);n.ops??=[];if(el.checked&&!n.ops.some(op=>op.id===d.rate))n.ops.push({id:d.rate,mode:'inside',amount:1});else if(!el.checked)n.ops=n.ops.filter(op=>op.id!==d.rate);});
    else if(el.hasAttribute('data-pa-op-mode'))paMutation(()=>{const op=C.findNode(db.quote.products,d.id).ops[Number(d.index)];op.mode=el.value;});
  });
  document.addEventListener('input',event=>{if(!event.target.hasAttribute('data-pa-search'))return;const pos=event.target.selectionStart;PA.query=event.target.value;paRenderPreserve();const input=$('[data-pa-search]');input.focus({preventScroll:true});input.setSelectionRange(pos,pos);});
}
