/* Local quote workspace: independent documents, immutable approved snapshots. */
'use strict';
const Quotes={conflict:false,lastStored:null};
function quoteCheckpoint(){db.savedQuotes??=[];db.quote.workspaceKey??=C.uid();const key=db.quote.workspaceKey,index=db.savedQuotes.findIndex(x=>x.key===key),previous=db.savedQuotes[index];
  if(previous&&JSON.stringify(previous.quote)===JSON.stringify(db.quote))return;
  const record={key,revision:(previous?.revision||0)+1,updated:new Date().toISOString(),quote:C.copy(db.quote)};
  if(index<0)db.savedQuotes.push(record);else db.savedQuotes[index]=record;
}
function quoteList(){quoteCheckpoint();openDialog('Danh sách báo giá trên máy này',`<div class="actions">${workButton('+ Báo giá mới','new-quote','','primary')}${workButton('Nhân bản báo giá đang mở','copy-quote')}${workButton('Xuất Excel chi tiết','export-workbook')}</div><p class="help-text">Mỗi báo giá giữ cấu thành, đơn giá và hệ số riêng. Danh mục chung được dùng để tạo mới; giá đã lưu chỉ đổi khi chủ động cập nhật. Đây là dữ liệu trên trình duyệt, chưa phải dữ liệu dùng chung của nhiều người.</p><label class="field"><span>Tìm mã / khách hàng / công trình</span><input data-quote-list-search placeholder="Gõ để lọc danh sách"></label><div class="table-scroll"><table class="quotes-list"><thead><tr><th>Báo giá / khách hàng</th><th>Công trình</th><th>Trạng thái</th><th>Cập nhật</th><th></th></tr></thead><tbody>${db.savedQuotes.slice().sort((a,b)=>b.updated.localeCompare(a.updated)).map(x=>`<tr data-quote-list-row data-search="${esc(foldText(x.quote.id+' '+x.quote.customer+' '+x.quote.project))}"><td><strong>${esc(x.quote.id)}</strong><small class="subtext">${esc(x.quote.customer)}</small></td><td>${esc(x.quote.project)}</td><td>${x.quote.status==='approved'?'Đã duyệt nội bộ':'Nháp'}${x.key===db.quote.workspaceKey?'<small class="subtext">Đang mở</small>':''}</td><td>${esc(TPDisplay.date(x.updated,true))}</td><td>${workButton('Mở','open-quote',`data-id="${x.key}"`,'small')}</td></tr>`).join('')}</tbody></table></div><div class="notice">Bản đã duyệt được giữ trong lịch sử. Chỉnh tiếp đưa báo giá về nháp, không ghi đè phiên bản đã duyệt. Nên sao lưu định kỳ.</div>`);$('#dialog').classList.add('wide-dialog');}
function quoteSwitch(quote){closeDialog();quoteCheckpoint();db.quote=C.copy(quote);db.quote.workspaceKey??=C.uid();selected=db.quote.products[0]?.id;page='quote';tab='bom';UX.undo=[];UX.redo=[];UX.checked.clear();PA.query='';initUX();persist();render();window.scrollTo(0,0);}
function quoteNew(copyCurrent=false,source=null){const base=source||db.quote,day=new Date().toLocaleDateString('en-CA');
  openDialog(copyCurrent?'Nhân bản báo giá':'Tạo báo giá mới',`<div class="form-grid">${field('Mã báo giá','id',(copyCurrent?base.id+'-COPY':'BG-'+day.replaceAll('-','')+'-'+String((db.savedQuotes?.length||0)+1).padStart(3,'0')),'text','required')}${field('Ngày','date',day,'date','required')}</div>${field('Khách hàng','customer',copyCurrent?base.customer:'','text','required')}${field('Công trình / nội dung','project',copyCurrent?base.project:'','text','required')}<p class="help-text">${copyCurrent?'Giữ cấu thành, giá và hệ số thành bản độc lập; bỏ trạng thái duyệt và giá chốt tay để rà lại.':'Bắt đầu báo giá trống, sử dụng danh mục vật tư và công đoạn hiện có.'}</p>`,copyCurrent?'Tạo bản sao':'Tạo báo giá',f=>{
    const id=String(f.get('id')).trim();if(db.savedQuotes?.some(x=>x.quote.id===id))throw Error('Mã báo giá đã tồn tại trên máy này');
    const q=copyCurrent?C.copy(base):{...C.copy(base),products:[],ratesSnapshot:C.copy(db.rates),pricing:{...TPInputPrices.defaults(db),costSequence:TPPrice.FLOW_SEQUENCE},expenses:[],remnantSelections:{},remnantMode:'all'};
    Object.assign(q,{id,date:f.get('date'),customer:String(f.get('customer')).trim(),project:String(f.get('project')).trim(),status:'draft',commercial:{status:'draft',version:0,events:[]},workspaceKey:C.uid()});
    for(const key of ['approvedOffer','approvedBaseline','revisionNotes'])delete q[key];if(q.pricing)q.pricing.overrides={};if(!copyCurrent){delete q.deviceInstallations;delete q.deviceHistory;delete q.deviceWorkHistory;delete q.customerInfo;delete q.request;delete q.legacySource;delete q.approvedOffer;delete q.approvedBaseline;delete q.offerTerms;delete q.offerTermsHistory;delete q.costPriceSources;delete q.costPriceHistory;delete q.inputPriceAudit;}const contact=inCustomers().find(c=>c.name===q.customer);if(contact)q.customerInfo=C.copy(contact);quoteSwitch(q);if(!copyCurrent){tab='intake';render();}
  });
}
function quoteVersions(q=db.quote){return (db.history||[]).map((h,index)=>({...h,index})).filter(h=>h.quote.workspaceKey?h.quote.workspaceKey===q.workspaceKey:h.quote.id===q.id).map((h,i)=>({...h,version:i+1}));}
function quoteArchive(){
  db.quote.workspaceKey??=C.uid();
  const {history,savedQuotes,...document}=db;
  const h={at:new Date().toISOString(),total:result.total.grand,quote:C.copy(db.quote),document:C.copy(document),offerHtml:paper(),offerSheets:C.copy(exportSheets(false)),internalSheets:C.copy(exportSheets(true))};
  db.history.push(h);UX.undo=[];UX.redo=[];undoState=null;
}
function quoteHistory(){const history=quoteVersions(),events=db.quote.commercial?.events||[];
  openDialog('Phiên bản và lần gửi · '+esc(db.quote.id),`<div class="actions">${clButton('Lịch sử gửi / khách chốt','workflow')}${db.quote.status==='approved'?workButton('Tạo bản sửa','revise-quote'):''}</div>`+(history.length?`<p class="help-text">Mỗi bản duyệt giữ riêng dữ liệu, giá và hệ số. Các lần gửi gắn với đúng phiên bản; sửa tiếp vẫn cùng mã báo giá.</p>${history.slice().reverse().map(h=>{const log=events.filter(e=>e.offerVersion===h.version);return `<div class="history-row quote-version-row"><div><strong>${esc(h.quote.id)} · V${h.version}</strong><small>${esc(TPDisplay.date(h.at,true))} · ${esc(h.quote.pricing?TPGroupPrice.methods(h.quote).find(x=>x[0]===h.quote.pricing.selected)?.[1]||'':'Cách tính cũ')}</small><p>${log.length?log.map(e=>esc((e.resend?'Gửi lại':TPComplete.STATES.find(s=>s[0]===e.to)?.[1]||e.to)+' · '+TPDisplay.date(e.at,true))).join('<br>'):'Chưa ghi nhận gửi khách'}</p></div><strong>${money(h.total)} đ</strong>${workButton('Xem bản chào','view-version',`data-index="${h.index}"`,'small')}${h.offerSheets?workButton('Excel bản chào','export-version',`data-index="${h.index}"`,'small'):''}${h.internalSheets?workButton('Dữ liệu tính giá','version-data',`data-index="${h.index}"`,'small'):''}${workButton('Dùng làm bản mới','copy-version',`data-index="${h.index}"`,'small')}</div>`;}).join('')}`:empty('Chưa có phiên bản duyệt','Duyệt nội bộ tại Bản chào giá để lưu một phiên bản.')));$('#dialog').classList.add('wide-dialog');}
function quoteViewVersion(index){const h=db.history[index];if(!h)return;const activeDb=db,activeResult=result;let html=h.offerHtml;
  if(!html)try{db=h.document?C.copy(h.document):{...db,quote:C.copy(h.quote)};result=C.calculate(db);html=paper();}finally{db=activeDb;result=activeResult;}
  openDialog('Chỉ xem · '+esc(h.quote.id),`<div class="notice">Phiên bản lưu lúc ${esc(TPDisplay.date(h.at,true))}; không thay báo giá đang làm.${!h.document?' Bản cũ chưa lưu đủ danh mục tại thời điểm duyệt; phần trình bày được dựng lại từ dữ liệu còn lưu.':''}</div>${quoteSafePaper(html)}`);$('#dialog').classList.add('wide-dialog');
}
// Backups are user data. Historical markup can only contribute inert paper tags/classes.
function quoteSafePaper(html){const doc=new DOMParser().parseFromString(html,'text/html'),allowed=new Set(['ARTICLE','DIV','SPAN','STRONG','SMALL','H1','H2','H3','H4','P','BR','TABLE','THEAD','TBODY','TFOOT','TR','TH','TD','UL','OL','LI','B','I','EM','SUP','SUB']);for(const el of [...doc.body.querySelectorAll('*')]){if(!allowed.has(el.tagName)){el.remove();continue;}for(const attr of [...el.attributes])if(!['class','colspan','rowspan'].includes(attr.name))el.removeAttribute(attr.name);}return doc.body.innerHTML;}
function quoteRevise(){if(Quotes.conflict)return toast('Dữ liệu đã đổi ở thẻ khác; tải lại trước khi sửa');if(db.quote.status!=='approved')return toast('Đang có bản nháp để sửa');const version=quoteVersions().length;openDialog('Tạo bản sửa · '+esc(db.quote.id),`${field('Lý do sửa','reason','','text','required')}<p>Giữ V${version} trong lịch sử. Bản sửa dùng cùng mã báo giá và cần duyệt lại trước khi gửi.</p>`,'Tạo bản sửa',f=>{const reason=String(f.get('reason')||'').trim();if(!reason)throw Error('Nhập lý do sửa');saveAndClose(()=>{db.quote.revisionNotes??=[];db.quote.revisionNotes.push({fromVersion:version,reason,at:new Date().toISOString()});delete db.quote.approvedOffer;delete db.quote.approvedBaseline;});});}
function quoteExportVersion(index,internal=false){const h=db.history[index],sheets=internal?h?.internalSheets:h?.offerSheets;if(!sheets)return toast('Bản này chưa lưu tệp xuất tại thời điểm duyệt');const v=quoteVersions(h.quote).find(x=>x.index===index)?.version;download(h.quote.id+'-V'+v+(internal?'-NOI-BO':'-CHAO-GIA')+'.xlsx',TPXlsx.make(sheets),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');}
function installQuotesUI(){
  const oldPersist=persist,oldMutation=mutation;
  persist=()=>{if(Quotes.conflict){$('#save-status').textContent='Tab khác vừa thay dữ liệu — cần tải lại';return;}quoteCheckpoint();oldPersist();try{Quotes.lastStored=localStorage.getItem(STORE);}catch{}};
  mutation=(action,options={})=>{if(Quotes.conflict)return toast('Một tab khác vừa thay dữ liệu. Sao lưu bản đang mở trước, rồi tải lại trang.');return oldMutation(action,options);};
  actions['quote-list']=quoteList;
  actions.history=quoteHistory;
  const originalIntro=paIntro;paIntro=()=>originalIntro()+`<div class="quotes-tools">${btn('Danh sách báo giá','quote-list')}${workButton('+ Báo giá mới','new-quote')}${workButton('Nhân bản','copy-quote')}${workButton('Phiên bản / lần gửi','quote-history')}${workButton('Xuất Excel chi tiết','export-workbook')}<span>Lưu riêng từng báo giá · giữ phiên bản đã duyệt</span></div>`;
  window.addEventListener('storage',e=>{if(e.key===STORE&&e.newValue!==Quotes.lastStored){Quotes.conflict=true;$('#save-status').textContent='Dữ liệu vừa thay đổi ở tab khác';toast('Tab khác vừa lưu dữ liệu. Sao lưu bản đang làm rồi tải lại để tránh ghi đè.');}});
  document.addEventListener('input',e=>{if(e.target.hasAttribute('data-quote-list-search')){const value=foldText(e.target.value);document.querySelectorAll('[data-quote-list-row]').forEach(row=>row.hidden=!row.dataset.search.includes(value));}});
  document.addEventListener('click',event=>{const el=event.target.closest('[data-work]');if(!el)return;const action=el.dataset.work;if(['new-quote','copy-quote','open-quote','copy-version'].includes(action)&&Quotes.conflict)return toast('Sao lưu và tải lại trước khi đổi báo giá.');
    if(action==='quote-history')actions.history();else if(action==='new-quote')quoteNew();else if(action==='copy-quote')quoteNew(true);else if(action==='open-quote'){const record=db.savedQuotes.find(x=>x.key===el.dataset.id);if(record)quoteSwitch(record.quote);}
    else if(action==='revise-quote')quoteRevise();else if(action==='export-version')quoteExportVersion(Number(el.dataset.index));else if(action==='version-data')quoteExportVersion(Number(el.dataset.index),true);else if(action==='view-version')quoteViewVersion(Number(el.dataset.index));else if(action==='copy-version')quoteNew(true,db.history[Number(el.dataset.index)].quote);
  });
}
