'use strict';
const RateLab={};
function rateLabRows(f){return f.kind==='category'?(f.categories||[]).map(t=>({label:t.key,value:t.key})):(f.tiers||[]).map((t,i)=>({label:f.boundary==='lower'?'Từ '+num(t.max):f.boundary==='exact'?'Đúng '+num(t.max):(i?'Trên '+num(f.tiers[i-1].max)+' – ':'')+(t.max===null?'không giới hạn':num(t.max)),value:t.max===null?Number(f.tiers[i-1]?.max||0)+1:Number(t.max)}));}
function rateLabRead(){const rate=RateLab.rate,f=new FormData($('#dialog-form')),context=Object.fromEntries([...new Map((rate.factors||[]).filter(x=>x.enabled!==false).map(x=>[x.param,x])).values()].map(x=>[x.param,x.kind==='category'?String(f.get('ctx-'+x.param)):Number(f.get('ctx-'+x.param))]));return {rate,context,mode:f.get('mode'),x:f.get('axis-x'),y:f.get('axis-y')};}
function rateLabResult(){const {rate,context,mode,x,y}=rateLabRead(),a=(rate.factors||[]).find(f=>f.id===x),b=(rate.factors||[]).find(f=>f.id===y),price=ctx=>TPWork.price(rate,{mode,pricingMethod:'factors'},ctx,TPPrice.tier),sample=price(context);let rows=[];
  if(a&&b){if(a.param===b.param)throw Error('Hai trục cần dùng hai tham số khác nhau');const xs=rateLabRows(a),ys=rateLabRows(b);if(xs.length*ys.length>400)throw Error('Chọn hai yếu tố có tối đa 400 ô kết hợp');rows=[[a.name+' / '+b.name,...ys.map(v=>v.label)],...xs.map(v=>[v.label,...ys.map(w=>price({...context,[a.param]:v.value,[b.param]:w.value}).value)])];}
  return {sample,rows,mode,unit:rate[mode+'Unit']||rate.unit};
}
function rateLabPreview(){try{const r=rateLabResult();$('#rate-lab-result').innerHTML=`<div class="work-live-result"><strong>${money(r.sample.value)} đ/${esc(r.unit)}</strong><p>Giá gốc ${money(r.sample.base)} đ ${r.sample.factors.map(f=>' × (1 '+(f.value<0?'−':'+')+' '+num(Math.abs(f.value))+'%)').join('')}</p>${r.sample.factors.map(f=>`<small class="subtext">${esc(f.name)}: ${esc(f.input)} → ${num(f.value)}%${f.kind==='category'?' · '+esc(f.label):' · '+(f.max===null?'trên '+num(f.min):'đến '+num(f.max))}</small>`).join('')}</div>${r.rows.length?`<h3>Đơn giá kết hợp hai yếu tố (đ/${esc(r.unit)})</h3><p class="help-text">Các yếu tố còn lại giữ theo tình huống nhập ở trên. Đây là bảng thử, không tự đổi giá đang lưu.</p><div class="table-scroll"><table>${r.rows.map((row,i)=>`<${i?'tr':'thead><tr'}>${row.map((v,j)=>i&&j?`<td class="right mono">${money(v)}</td>`:`<th>${esc(v)}</th>`).join('')}</tr>${i?'':'</thead>'}`).join('')}</table></div>`:''}`;}catch(e){$('#rate-lab-result').innerHTML=`<div class="notice error">${esc(e.message)}</div>`;}}
function rateLabOpen(id,catalog){const rate=(catalog?db.rates:db.quote.ratesSnapshot).find(r=>r.id===id);RateLab.rate=rate;const factors=(rate.factors||[]).filter(f=>f.enabled!==false),unique=[...new Map(factors.map(f=>[f.param,f])).values()],axes=[['','Không chọn'],...factors.map(f=>[f.id,f.name])];
  openDialog('Thử đơn giá: '+esc(rate.name),`<p>Thay đầu vào để thấy đơn giá, bậc hệ số và bảng kết hợp. Không sửa dữ liệu công đoạn hoặc báo giá.</p>${select('Nơi thực hiện','mode',[['inside','Tại xưởng'],['outside','Thuê ngoài']],'inside')}<div class="form-grid three">${unique.map(f=>f.kind==='category'?select(f.name,'ctx-'+f.param,(f.categories||[]).map(c=>[c.key,c.key]),f.categories?.[0]?.key):field(f.name+' ('+f.param+')','ctx-'+f.param,rateLabRows(f)[0]?.value??1,'number','min="0" step="any" required')).join('')}</div><div class="form-grid">${select('Yếu tố theo hàng','axis-x',axes,factors[0]?.id||'')}${select('Yếu tố theo cột','axis-y',axes,factors.find(f=>f.param!==factors[0]?.param)?.id||'')}</div><div id="rate-lab-result"></div>`, 'Xuất Excel bảng thử',()=>{const r=rateLabResult();download('THU-DON-GIA.xlsx',TPXlsx.make([{name:'Tinh huong',widths:[36,24,24],rows:[['Công đoạn',rate.name],['Nơi thực hiện',r.mode==='inside'?'Tại xưởng':'Thuê ngoài'],['Giá gốc',r.sample.base],['Đơn giá áp dụng',r.sample.value],['Đơn vị',r.unit],[],['Yếu tố','Giá trị tra','Hệ số %'],...r.sample.factors.map(f=>[f.name,f.input,f.value])]},{name:'Ma tran 2 yeu to',widths:[30,...Array(Math.max(1,(r.rows[0]?.length||1)-1)).fill(22)],rows:r.rows.length?r.rows:[['Cần chọn hai yếu tố khác tham số']]}]),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');});$('#dialog').classList.add('wide-dialog');$('#dialog-form').addEventListener('input',rateLabPreview);$('#dialog-form').addEventListener('change',rateLabPreview);rateLabPreview();
}
function exportRatebook(){const sheets=[{name:'Don gia',widths:[22,34,20,16,20,16],rows:[['Mã','Công đoạn','Giá xưởng','ĐVT','Giá thuê','ĐVT'],...db.rates.map(r=>[r.id,r.name,r.inside,r.insideUnit||r.unit,r.outside,r.outsideUnit||r.unit])]},{name:'He so',widths:[25,30,24,12,36,18],rows:[['Công đoạn','Yếu tố','Tham số','Bật','Bậc / nhóm','Hệ số %'],...db.rates.flatMap(r=>(r.factors||[]).flatMap(f=>rateLabRows(f).map((t,i)=>[r.name,f.name,f.param,f.enabled!==false,t.label,f.valueMode==='multiplier'?((f.kind==='category'?f.categories[i].percent:f.tiers[i].percent)-1)*100:(f.kind==='category'?f.categories[i].percent:f.tiers[i].percent)])))]}];download('BANG-DON-GIA-NOI-BO.xlsx',TPXlsx.make(sheets),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');}
function installRateLabUI(){const oldTable=paRateTable,oldRatebook=renderRatebookAdvanced;paRateTable=(rates,catalog)=>{let html=oldTable(rates,catalog);for(const rate of rates){const original=paButton('Sửa đơn giá / hệ số','edit-rate',`data-id="${rate.id}" ${catalog?'data-catalog="1"':''}`,'small');html=html.replace(original,original+`<button class="button small" data-rate-lab="${esc(rate.id)}" data-catalog="${catalog?'1':''}">Thử giá / ma trận</button>`);}return html;};renderRatebookAdvanced=()=>oldRatebook()+`<div class="actions"><button class="button" data-rate-export>Excel đơn giá và hệ số nội bộ</button></div>`;document.addEventListener('click',e=>{const lab=e.target.closest('[data-rate-lab]');if(lab)rateLabOpen(lab.dataset.rateLab,lab.dataset.catalog==='1');if(e.target.closest('[data-rate-export]'))exportRatebook();});}
