/* Remnant choices belong to this quotation, not to inventory. */
const RemnantUI={limits:new Map(),expanded:new Set()};
function remnantBatches(g){
  const batches=new Map();
  for(const r of g.remnants){const key=r.l+'|'+r.w;if(!batches.has(key))batches.set(key,{l:r.l,w:r.w,parts:[]});batches.get(key).parts.push(r);}
  return [...batches.values()].sort((a,b)=>(g.spec.shape==='sheet'?b.l*b.w-a.l*a.w:b.l-a.l));
}
function remnantSize(g,r){return num(r.l)+(g.spec.shape==='sheet'?' × '+num(r.w):'')+' mm';}
function setRemnantParts(g,ids,checked){
  db.quote.remnantSelections??={};const chosen=new Set(db.quote.remnantSelections[g.signature]||[]);
  ids.forEach(id=>checked&&g.remnants.find(r=>r.id===id)?.eligible!==false?chosen.add(id):chosen.delete(id));
  if(chosen.size)db.quote.remnantSelections[g.signature]=[...chosen];else delete db.quote.remnantSelections[g.signature];
}
function remnantMutation(action,focusSelector){
  const y=scrollY;let reset=false;mutation(()=>{action();reset=normalizeRemnantMode();});window.scrollTo(0,y);if(focusSelector)$(focusSelector)?.focus({preventScroll:true});if(reset)toast('Không còn phần dư được chọn. Báo giá trở về tính toàn bộ vật tư mua.');
}
function normalizeRemnantMode(){if(db.quote.remnantMode!=='exclude')return false;const r=C.calculate(db).reuse;if(!r.selectedCount&&!r.staleCount){db.quote.remnantMode='all';return true;}return false;}
function remnantOverlay(g,index){
  if(!g.remnants)return '';const gi=result.groups.indexOf(g),sheet=g.spec.shape==='sheet';
  return g.remnants.filter(r=>r.stockIndex===index).map(r=>`<button type="button" class="remnant-piece ${r.selected?'kept':''}" ${r.eligible===false?'disabled':''} data-remnant="piece" data-gi="${gi}" data-rid="${r.id}" aria-pressed="${r.selected}" aria-label="${r.selected?'Bỏ chọn':'Giữ lại'} phần dư ${remnantSize(g,r)}, ${sheet?'tấm':'thanh'} ${index+1}" title="${remnantSize(g,r)} · ${r.selected?'Đã chọn tận dụng':'Bấm để chọn tận dụng'}" style="left:${r.x/g.layout.stockL*100}%;top:${sheet?r.y/g.layout.stockW*100:0}%;width:${r.l/g.layout.stockL*100}%;height:${sheet?r.w/g.layout.stockW*100:100}%"><span>${r.selected?'✓ ':''}${num(r.l)}${sheet?' × '+num(r.w):''}</span></button>`).join('');
}
function remnantCostNote(){const r=result.reuse;return `<div class="remnant-price-note"><span>${db.quote.pricing?'Phương án tính toán chi tiết · ':''}Vật tư mua${db.quote.pricing?' và hoàn thiện':''}: <strong>${money(r.chargeAll.material)} ₫</strong> · Phần dư đã chọn: <strong>${money(r.credit)} ₫</strong><br>Đang ${r.mode==='exclude'?'không tính phần dư đã chọn':'tính cả phần dư'} vào ${db.quote.pricing?'phương án chi tiết':'báo giá'}. Khối lượng mua không đổi.${db.quote.pricing?'<br>TMC dùng hệ số hao hụt riêng; bảng này không phải giá chốt của phương án kg/đối thủ.':''}</span><button class="button small" data-remnant="open-waste">Xem phần dư & so giá</button></div>`;}
function renderRemnantWaste(){
  const r=result.reuse,hasGroups=result.groups.some(g=>!g.error),discount=r.chargeAll.grand-r.excludeSelected.grand;
  queueMicrotask(()=>document.querySelectorAll('[data-remnant-mixed]').forEach(el=>{el.indeterminate=true;}));
  return `<div class="section-toolbar"><div><h2>Chọn phần dư tận dụng, rồi quyết định giá chào</h2><p>Chọn phần tấm/thanh còn dùng được ở bên dưới. Mạch cắt không được tính là phần tận dụng.</p></div>${btn('↶ Hoàn tác','ux-undo',UX.undo.length?'':'disabled')}</div>
    ${r.staleCount?`<div class="notice error remnant-stale" role="alert"><strong>${r.staleCount} lựa chọn cũ không còn khớp phương án cắt.</strong><span>Kích thước, số lượng hoặc khổ mua đã đổi. Các lựa chọn này không được trừ vào giá; hãy bỏ lựa chọn cũ và kiểm tra lại phần dư bên dưới.</span><button class="button" data-remnant="review">Bỏ lựa chọn không còn khớp</button></div>`:''}
    <fieldset class="remnant-comparison"><legend>${db.quote.pricing?'Phần dư trong phương án tính toán chi tiết':'Cách tính phần dư vào báo giá này'}</legend>${db.quote.pricing?'<p class="remnant-comparison-note">Hai mức dưới đây tính theo phương án chi tiết, chưa áp giá chốt riêng. TMC có hệ số hao hụt riêng; chọn giá chung tại Phân tích giá.</p>':''}<div class="remnant-options">
      <label class="remnant-option ${r.mode==='all'?'active':''}"><input type="radio" name="remnant-mode" value="all" ${r.mode==='all'?'checked':''}><span><strong>Tính cả phần dư</strong><small>Đơn hàng chịu toàn bộ vật tư mua theo khổ.</small><b data-remnant-grand="all">${money(r.chargeAll.grand)} ₫</b><small>Tổng chào sau thuế</small></span></label>
      <label class="remnant-option ${r.mode==='exclude'?'active':''}"><input type="radio" name="remnant-mode" value="exclude" ${r.mode==='exclude'?'checked':''} ${!r.selectedCount||r.staleCount?'disabled':''}><span><strong>Không tính phần tận dụng</strong><small>${r.selectedCount?'Giữ lại phần đã chọn cho công việc khác.':'Chọn phần dư bên dưới để so sánh giá.'}</small><b data-remnant-grand="exclude">${r.selectedCount?money(r.excludeSelected.grand)+' ₫':'Chưa chọn phần dư'}</b><small>${r.selectedCount?'Tổng chào sau thuế · giảm '+money(discount)+' ₫':'Không tự động coi mọi phần dư là tận dụng được'}</small></span></label>
    </div><p class="remnant-comparison-note">Hai phương án dùng cùng số tấm/thanh cần mua. Giá trị phần giữ lại tính theo tỷ lệ diện tích/chiều dài và đơn giá mua; đây không phải tiền bán phế liệu hay giảm tiền phải trả nhà cung cấp.</p></fieldset>
    <div class="remnant-work-head"><div><strong>${r.selectedCount?num(r.selectedCount)+' phần dư đã chọn · '+money(r.credit)+' ₫ giá trị vật tư':'Bắt đầu: chọn phần dư có thể dùng lại'}</strong><p>Các phần cùng kích thước được gom một dòng. Có thể chọn từng phần nếu chỉ giữ lại một số.</p></div><label class="inline-field">Mạch cắt <input type="number" min="0" max="20" step="0.1" data-quote-field="kerf" value="${db.quote.kerf}"> mm</label></div>
    ${result.groups.map((g,gi)=>g.error?`<div class="panel error-panel"><h3>${esc(g.spec.id)} / ${esc(g.spec.name)}</h3><p>${esc(g.error)}</p>${btn('Chỉnh khổ mua','edit-stock',`data-id="${esc(g.spec.id)}"`)}</div>`:renderRemnantGroup(g,gi)).join('')}
    ${!hasGroups?empty('Chưa có phôi gia công','Thêm mã vật tư tấm hoặc thanh tại Cấu thành sản phẩm.'):''}
    <div class="remnant-final"><span>Giá chào đang áp dụng <strong>${money(result.total.grand)} ₫</strong><small>${r.mode==='exclude'?'Không tính phần tận dụng đã chọn':'Tính cả phần dư'} · Sau thuế${result.errors.length?' · Còn nội dung cần kiểm tra':''}</small></span><button class="button primary" data-remnant="open-pricing">Tiếp: kiểm tra chi phí →</button></div>`;
}
function renderRemnantGroup(g,gi){
  const sheet=g.spec.shape==='sheet',batches=remnantBatches(g),limit=RemnantUI.limits.get(g.signature)||12,unit=sheet?'tấm':'thanh',selected=g.remnants.filter(r=>r.selected).length;
  const remain=g.layout.purchased-(g.layout.netUsed??g.layout.used)-g.reusableMeasure,weight=v=>g.purchasedWeight*v/g.layout.purchased;
  return `<section class="panel nesting-panel remnant-panel" data-remnant-group="${gi}"><div class="panel-head"><div><span class="overline mono">${esc(g.spec.id)}</span><h2>${esc(g.spec.name)}</h2><p>Khổ mua ${num(g.layout.stockL)}${sheet?' × '+num(g.layout.stockW):''} mm · ${money(g.spec.price)} ₫/${esc(g.spec.unit)}</p></div><div class="remnant-buy"><strong>${g.layout.stocks.length} ${unit} cần mua</strong><span>${num(g.purchasedWeight)} kg · ${money(g.purchaseCost)} ₫</span>${btn('Chỉnh khổ mua','edit-stock',`data-id="${esc(g.spec.id)}"`,'small')}</div></div>
    <div class="remnant-balance"><div><span>Phôi đưa vào sản phẩm</span><strong>${num(g.totalWeight)} kg</strong></div><div class="reuse-balance"><span>Phần dư chọn tận dụng</span><strong>${num(weight(g.reusableMeasure))} kg</strong></div><div><span>Chưa tận dụng & mạch cắt</span><strong>${num(weight(remain))} kg <small>(${num(remain/g.layout.purchased*100,1)}%)</small></strong></div></div>
    <div class="remnant-layout"><div class="remnant-diagrams"><div class="remnant-map-key"><span class="key-used">Chi tiết</span><span class="key-free">Phần dư</span><span class="key-kept">Chọn tận dụng ✓</span></div><div class="stock-grid">${g.layout.stocks.slice(0,2).map((s,i)=>stockMap(g,s,i)).join('')}</div>${g.layout.stocks.length>2?`<details class="remnant-stocks" data-remnant-expanded="${gi}" ${RemnantUI.expanded.has(g.signature)?'open':''}><summary>Xem thêm sơ đồ ${unit} (${g.layout.stocks.length-2})</summary><div class="stock-grid">${g.layout.stocks.slice(2,30).map((s,i)=>stockMap(g,s,i+2)).join('')}</div>${g.layout.stocks.length>30?'<p>Sơ đồ hiển thị 30 khổ đầu. Bảng chọn bên cạnh bao gồm phần dư của tất cả các khổ.</p>':''}</details>`:''}<details class="remnant-cut-details"><summary>Chi tiết cần cắt</summary>${g.rows.map(row=>`<div class="cut-legend"><i style="background:${row.color}"></i><span><strong>${esc(row.path.at(-1)||row.label)}</strong><small>${num(row.geometry.length)}${sheet?' × '+num(row.geometry.width):''} mm</small></span><b>× ${num(row.count)}</b></div>`).join('')}<p>${g.layout.manual?'Phần chưa phân loại dư / khe cắt':g.layout.mode==='right-triangle'?'Khe cắt và đệm bố trí':'Mạch cắt theo phương án'}: ${num(weight(g.kerfMeasure))} kg.${g.layout.mode==='right-triangle'?` Phần tam giác lẻ còn dư: ${num(weight(g.layout.triangleOffcut))} kg, chưa nằm trong danh sách dư chữ nhật có thể chọn.`:''}${g.layout.mode==='circle'&&!g.layout.manual?` Phần ngoài biên tròn: ${num(weight(g.layout.circleOffcut))} kg, chưa đưa vào danh sách dư chữ nhật.`:''} Phần dư còn lại chưa được chọn không mặc định là phế liệu.</p></details></div>
    <div class="remnant-selection"><div class="remnant-selection-head"><div><h3>Phần dư có thể chọn</h3><p>${selected} / ${g.remnants.length} phần đã chọn</p></div><button class="button small" data-remnant="threshold" data-gi="${gi}" ${!g.remnants.length?'disabled':''}>Chọn theo kích thước…</button></div>${batches.length?`<div class="remnant-table-scroll"><table class="remnant-table"><thead><tr><th>Giữ lại / Kích thước</th><th class="right">Số phần</th><th class="right">Giá trị</th><th></th></tr></thead><tbody>${batches.slice(0,limit).map((batch,bi)=>{const count=batch.parts.filter(r=>r.selected).length;return `<tr class="${count?'has-kept':''}"><td><label><input type="checkbox" ${batch.parts.every(r=>r.eligible===false)?'disabled title="Dưới ngưỡng phần dư đã khai"':''} data-remnant-batch="${bi}" data-gi="${gi}" aria-label="Giữ lại ${remnantSize(g,batch)}, ${batch.parts.length} phần" ${count===batch.parts.length?'checked':''} ${count&&count<batch.parts.length?'data-remnant-mixed':''}><span>${remnantSize(g,batch)}</span></label></td><td class="right mono">${count?count+' / ':''}${batch.parts.length}</td><td class="right mono">${money(batch.parts.reduce((s,r)=>s+r.value,0))} ₫</td><td><button class="text-button" data-remnant="individual" data-gi="${gi}" data-bi="${bi}">Từng phần</button></td></tr>`;}).join('')}</tbody></table></div>${batches.length>limit?`<button class="button small" data-remnant="more" data-gi="${gi}">Xem thêm kích thước (${batches.length-limit})</button>`:''}<p class="remnant-table-help">Giá trị hiển thị cho tất cả các phần trên dòng. Tích chọn = xác nhận phần đó còn dùng được; không phải tự động nhập kho.</p>`:'<div class="muted-row">'+(g.layout.triangleOffcut>0?'Còn phần dư tam giác chưa hỗ trợ chọn tận dụng; không còn dư chữ nhật.':g.layout.mode==='circle'?'Phần dư cong giữa các phôi chưa hỗ trợ chọn tận dụng; không còn dư chữ nhật.':'Không còn phần dư ngoài mạch cắt.')+'</div>'}
    <div class="remnant-group-cost"><span>Tiền mua theo khổ <b>${money(g.purchaseCost)} ₫</b></span><span>Phần đã chọn giữ lại <b>${money(g.recoverableCredit)} ₫</b></span><span class="active-cost">Vật tư tính vào báo giá <b>${money(g.cost)} ₫</b></span></div>${selected?'<button class="button small remnant-compare-link" data-remnant="compare">So sánh 2 phương án giá ↑</button>':''}</div></div></section>`;
}
function remnantThreshold(g){
  const sheet=g.spec.shape==='sheet';openDialog('Chọn phần dư theo kích thước',`<p>${esc(g.spec.id)} · Chỉ chọn phần dư đạt kích thước do anh xác nhận, không chọn mạch cắt. Lựa chọn hiện có vẫn được giữ.</p><div class="form-grid">${field(sheet?'Cạnh dài tối thiểu (mm)':'Chiều dài tối thiểu (mm)','minL',sheet?500:300,'number','min="1" max="100000" required')}${sheet?field('Cạnh ngắn tối thiểu (mm)','minW',200,'number','min="1" max="100000" required'):''}</div><p id="threshold-preview" class="notice"></p><p>Đây là ngưỡng thử, không phải tiêu chuẩn của nhà máy. Hãy chỉnh theo khả năng sử dụng thực tế.</p>`,'Chọn các phần đạt kích thước',f=>{const ids=matches(Number(f.get('minL')),Number(f.get('minW'))||0).map(r=>r.id);if(!ids.length)throw Error('Không có phần dư đạt kích thước này');saveAndClose(()=>setRemnantParts(g,ids,true),'Đã chọn '+ids.length+' phần dư. Bấm “So sánh 2 phương án giá” để rà giá chào.');});
  function matches(l,w){return g.remnants.filter(r=>sheet?Math.max(r.l,r.w)>=Math.max(l,w)&&Math.min(r.l,r.w)>=Math.min(l,w):r.l>=l);}
  const preview=()=>{const parts=matches(Number($('[name=minL]').value),Number($('[name=minW]')?.value)||0);$('#threshold-preview').textContent=parts.length+' phần đạt kích thước · Giá trị '+money(parts.reduce((s,r)=>s+r.value,0))+' ₫';};
  $('#dialog [name=minL]').oninput=preview;if(sheet)$('#dialog [name=minW]').oninput=preview;preview();
}
function individualRemnants(g,bi){
  const batch=remnantBatches(g)[bi];openDialog('Chọn từng phần dư · '+remnantSize(g,batch),`<p>${esc(g.spec.id)} · Chọn đúng những phần muốn giữ lại.</p><div class="remnant-individual">${batch.parts.map(r=>`<label><input type="checkbox" name="part" value="${r.id}" ${r.eligible===false?'disabled':''} ${r.selected?'checked':''}><span>${g.spec.shape==='sheet'?'Tấm':'Thanh'} ${r.stockIndex+1} · ${remnantSize(g,r)}</span><strong>${money(r.value)} ₫</strong></label>`).join('')}</div>`,'Áp dụng lựa chọn',f=>{const ids=f.getAll('part');saveAndClose(()=>{setRemnantParts(g,batch.parts.map(r=>r.id),false);setRemnantParts(g,ids,true);normalizeRemnantMode();},'Đã cập nhật phần dư giữ lại');});
}
document.addEventListener('change',e=>{
  const el=e.target;
  if(el.name==='remnant-mode'){if(el.disabled)return;remnantMutation(()=>{db.quote.remnantMode=el.value;},'[name="remnant-mode"][value="'+el.value+'"]');}
  if(el.hasAttribute('data-remnant-batch')){const g=result.groups[Number(el.dataset.gi)],batch=remnantBatches(g)[Number(el.dataset.remnantBatch)],checked=el.checked;remnantMutation(()=>setRemnantParts(g,batch.parts.map(r=>r.id),checked),'[data-remnant-batch="'+el.dataset.remnantBatch+'"][data-gi="'+el.dataset.gi+'"]');}
});
document.addEventListener('click',e=>{
  const el=e.target.closest('[data-remnant]');if(!el)return;e.preventDefault();const g=result.groups[Number(el.dataset.gi)];
  if(el.dataset.remnant==='compare'){const box=$('.remnant-comparison');box?.scrollIntoView({block:'start'});$('.remnant-option.active input')?.focus({preventScroll:true});}
  else if(el.dataset.remnant==='open-waste'||el.dataset.remnant==='open-pricing'){tab=el.dataset.remnant==='open-waste'?'waste':'pricing';render();window.scrollTo(0,0);}
  else if(el.dataset.remnant==='piece'){const part=g.remnants.find(r=>r.id===el.dataset.rid);remnantMutation(()=>setRemnantParts(g,[part.id],!part.selected),'[data-remnant="piece"][data-gi="'+el.dataset.gi+'"][data-rid="'+el.dataset.rid+'"]');}
  else if(el.dataset.remnant==='threshold')remnantThreshold(g);
  else if(el.dataset.remnant==='individual')individualRemnants(g,Number(el.dataset.bi));
  else if(el.dataset.remnant==='more'){RemnantUI.limits.set(g.signature,(RemnantUI.limits.get(g.signature)||12)+20);const y=scrollY;render();window.scrollTo(0,y);}
  else if(el.dataset.remnant==='review')remnantMutation(()=>{const kept={};for(const group of result.groups.filter(g=>!g.error)){const ids=group.remnants.filter(r=>r.selected).map(r=>r.id);if(ids.length)kept[group.signature]=ids;}db.quote.remnantSelections=kept;});
});
document.addEventListener('toggle',e=>{if(e.target.hasAttribute('data-remnant-expanded')){const g=result.groups[Number(e.target.dataset.remnantExpanded)];if(g)e.target.open?RemnantUI.expanded.add(g.signature):RemnantUI.expanded.delete(g.signature);}},true);
