/* Remnant choices belong to this quotation, not to inventory. */
const RemnantUI={limits:new Map(),expanded:new Set()};
function remnantBatches(g){
  const batches=new Map();
  for(const r of g.remnants){const key=r.l+'|'+r.w;if(!batches.has(key))batches.set(key,{l:r.l,w:r.w,parts:[]});batches.get(key).parts.push(r);}
  return [...batches.values()].sort((a,b)=>(g.spec.shape==='sheet'?b.l*b.w-a.l*a.w:b.l-a.l));
}
function remnantSize(g,r){return num(r.l)+(g.spec.shape==='sheet'?' × '+num(r.w):'')+' mm';}
function setRemnantParts(g,ids,checked){
  db.quote.remnantSelections??={};const chosen=new Set(db.quote.remnantSelections[g.signature]||[]);
  ids.forEach(id=>checked&&g.remnants.find(r=>r.id===id)?.eligible!==false?chosen.add(id):chosen.delete(id));
  if(chosen.size)db.quote.remnantSelections[g.signature]=[...chosen];else delete db.quote.remnantSelections[g.signature];
}
function remnantMutation(action,focusSelector){
  const y=scrollY;let reset=false;mutation(()=>{action();reset=normalizeRemnantMode();});window.scrollTo(0,y);if(focusSelector)$(focusSelector)?.focus({preventScroll:true});if(reset)toast('Không còn phần dư được chọn. Báo giá trở về tính toàn bộ vật tư mua.');
}
function normalizeRemnantMode(){if(db.quote.remnantMode!=='exclude')return false;const r=C.calculate(db).reuse;if(!r.selectedCount&&!r.staleCount){db.quote.remnantMode='all';return true;}return false;}
function remnantOverlay(g,index){
  if(!g.remnants)return '';const gi=result.groups.indexOf(g),sheet=g.spec.shape==='sheet';
  return g.remnants.filter(r=>r.stockIndex===index).map(r=>`<button type="button" class="remnant-piece ${r.selected?'kept':''}" ${r.eligible===false?'disabled':''} data-remnant="piece" data-gi="${gi}" data-rid="${r.id}" aria-pressed="${r.selected}" aria-label="${r.selected?'Bỏ chọn':'Giữ lại'} phần dư ${remnantSize(g,r)}, ${sheet?'tấm':'thanh'} ${index+1}" title="${remnantSize(g,r)} · ${r.selected?'Đã chọn tận dụng':'Bấm để chọn tận dụng'}" style="left:${r.x/g.layout.stockL*100}%;top:${sheet?r.y/g.layout.stockW*100:0}%;width:${r.l/g.layout.stockL*100}%;height:${sheet?r.w/g.layout.stockW*100:100}%"><span>${r.selected?'✓ ':''}${num(r.l)}${sheet?' × '+num(r.w):''}</span></button>`).join('');
}
function remnantCostNote(){const r=result.reuse;return `<div class="remnant-price-note"><span>${db.quote.pricing?'Phương án tính toán chi tiết · ':''}Vật tư mua${db.quote.pricing?' và hoàn thiện':''}: <strong>${money(r.chargeAll.material)} ₫</strong> · Phần dư đã chọn: <strong>${money(r.credit)} ₫</strong><br>Đang ${r.mode==='exclude'?'không tính phần dư đã chọn':'tính cả phần dư'} vào ${db.quote.pricing?'phương án chi tiết':'báo giá'}. Khối lượng mua không đổi.${db.quote.pricing?'<br>TMC dùng hệ số hao hụt riêng; bảng này không phải giá chốt của phương án kg/đối thủ.':''}</span><button class="button small" data-remnant="open-waste">Xem phần dư & so giá</button></div>`;}
function renderRemnantWaste(){
  const r=result.reuse,hasGroups=result.groups.some(g=>!g.error),discount=r.chargeAll.grand-r.excludeSelected.grand;
  queueMicrotask(()=>document.querySelectorAll('[data-remnant-mixed]').forEach(el=>{el.indeterminate=true;}));
  return `<div class="section-toolbar"><div><h2>Chọn phần dư tận dụng, rồi quyết định giá chào</h2><p>Chọn phần tấm/thanh còn dùng được ở bên dưới. Mạch cắt không được tính là phần tận dụng.</p></div>${btn('↶ Hoàn tác','ux-undo',UX.undo.length?'':'disabled')}</div>
    ${r.staleCount?`<div class="notice error remnant-stale" role="alert"><strong>${r.staleCount} lựa chọn cũ không còn khớp phương án cắt.</strong><span>Kích thước, số lượng hoặc khổ mua đã đổi. Các lựa chọn này không được trừ vào giá; hãy bỏ lựa chọn cũ và kiểm tra lại phần dư bên dưới.</span><button class="button" data-remnant="review">Bỏ lựa chọn không còn khớp</button></div>`:''}
    <fieldset class="remnant-comparison"><legend>${db.quote.pricing?'Phần dư trong phương án tính toán chi tiết':'Cách tính phần dư vào báo giá này'}</legend>${db.quote.pricing?'<p class="remnant-comparison-note">Hai mức dưới đây tính theo phương án chi tiết, chưa áp giá chốt riêng. TMC có hệ số hao hụt riêng; chọn giá chung tại Phân tích giá.</p>':''}<div class="remnant-options">
      <label class="remnant-option ${r.mode==='all'?'active':''}"><input type="radio" name="remnant-mode" value="all" ${r.mode==='all'?'checked':''}><span><strong>Tính cả phần dư</strong><small>Đơn hàng chịu toàn bộ vật tư mua theo khổ.</small><b data-remnant-grand="all">${money(r.chargeAll.grand)} ₫</b><small>Tổng chào sau thuế</small></span></label>
      <label class="remnant-option ${r.mode==='exclude'?'active':''}"><input type="radio" name="remnant-mode" value="exclude" ${r.mode==='exclude'?'checked':''} ${!r.selectedCount||r.staleCount?'disabled':''}><span><strong>Không tính phần tận dụng</strong><small>${r.selectedCount?'Giữ lại phần đã chọn cho công việc khác.':'Chọn phần dư bên dưới để so sánh giá.'}</small><b data-remnant-grand="exclude">${r.selectedCount?money(r.excludeSelected.grand)+' ₫':'Chưa chọn phần dư'}</b><small>${r.selectedCount?'Tổng chào sau thuế · giảm '+money(discount)+' ₫':'Không tự động coi mọi phần dư là tận dụng được'}</small></span></label>
    </div><p class="remnant-comparison-note">Hai phương án dùng cùng số tấm/thanh cần mua. Giá trị phần giữ lại tính theo tỷ lệ diện tích/chiều dài và đơn giá mua; đây không phải tiền bán phế liệu hay giảm tiền phải trả nhà cung cấp.</p></fieldset>
    <div class="remnant-work-head"><div><strong>${r.selectedCount?num(r.selectedCount)+' phần dư đã chọn · '+money(r.credit)+' ₫ giá trị vật tư':'Bắt đầu: chọn phần dư có thể dùng lại'}</strong><p>Các phần cùng kích thước được gom một dòng. Có thể chọn từng phần nếu chỉ giữ lại một số.</p></div><label class="inline-field">Mạch cắt <input type="number" min="0" max="20" step="0.1" data-quote-field="kerf" value="${db.quote.kerf}"> mm</label></div>
    ${result.groups.map((g,gi)=>g.error?`<div class="panel error-panel"><h3>${esc(g.spec.id)} / ${esc(g.spec.name)}</h3><p>${esc(g.error)}</p>${meButton('Xoay / sắp xếp phôi','nesting',gi)} ${btn('Chỉnh khổ mua','edit-stock',`data-id="${esc(g.spec.id)}"`)}</div>`:renderRemnantGroup(g,gi)).join('')}
    ${!hasGroups?empty('Chưa có phôi gia công','Thêm mã vật tư tấm hoặc thanh tại Cấu thành sản phẩm.'):''}
    <div class="remnant-final"><span>Giá chào đang áp dụng <strong>${money(result.total.grand)} ₫</strong><small>${r.mode==='exclude'?'Không tính phần tận dụng đã chọn':'Tính cả phần dư'} · Sau thuế${result.errors.length?' · Còn nội dung cần kiểm tra':''}</small></span><button class="button primary" data-remnant="open-mass">Tiếp: Khối lượng & diện tích →</button></div>`;
}
function renderRemnantGroup(g,gi){
  const sheet=g.spec.shape==='sheet',batches=remnantBatches(g),limit=RemnantUI.limits.get(g.signature)||12,unit=sheet?'tấm':'thanh',selected=g.remnants.filter(r=>r.selected).length;
  const weight=v=>g.purchasedWeight*v/g.layout.purchased,loss=TPMaterialEstimate.comparisons({groups:[g]},g.rows.map(r=>r.id))[0],remainingWeight=loss.error?NaN:loss.remainingWeight;
  return `<section class="panel nesting-panel remnant-panel" data-remnant-group="${gi}"><div class="panel-head"><div><span class="overline mono">${esc(g.spec.id)}</span><h2>${esc(g.spec.name)}</h2><p>Khổ mua ${num(g.layout.stockL)}${sheet?' × '+num(g.layout.stockW):''} mm · ${money(g.spec.price)} ₫/${esc(g.spec.unit)}</p></div><div class="remnant-buy"><strong>${g.layout.stocks.length} ${unit} cần mua</strong><span>${num(g.purchasedWeight)} kg · ${money(g.purchaseCost)} ₫</span>${meButton('Xoay / sắp xếp phôi','nesting',gi)} ${btn('Chỉnh khổ mua','edit-stock',`data-id="${esc(g.spec.id)}"`,'small')}</div></div>
    <div class="remnant-balance"><div><span>Phôi đưa vào sản phẩm</span><strong>${num(g.totalWeight)} kg</strong></div><div class="reuse-balance"><span>Phần dư chọn tận dụng</span><strong>${num(weight(g.reusableMeasure))} kg</strong></div><div><span>Chưa tận dụng & mạch cắt</span><strong>${Number.isFinite(remainingWeight)?num(remainingWeight):"Chưa tính được"} kg <small>(${loss.error?"—":num(loss.stockPercent,1)}% lượng mua)</small></strong></div></div>
    <div class="notice" data-remnant-loss>${loss.error?esc(loss.error):`Hao hụt sau khi trừ phần tận dụng: ${num(loss.remaining,4)} / (${num(loss.used,4)} + ${num(loss.remaining,4)}) × 100 = <strong>${num(loss.lossPercent,4)}%</strong>. Phần còn lại ${num(loss.remainingWeight,4)} kg gồm mạch cắt và phần chưa chọn tận dụng. <button type="button" class="button small" data-me="group-estimate" data-id="${gi}">Khai % hao hụt theo gợi ý</button>`}</div>
    ${meNestingPresets(g,gi)}<div class="remnant-layout"><div class="remnant-diagrams"><div class="remnant-map-key"><span class="key-used">Chi tiết</span><span class="key-free">Phần dư</span><span class="key-kept">Chọn tận dụng ✓</span></div><div class="stock-grid">${g.layout.stocks.slice(0,2).map((s,i)=>stockMap(g,s,i)).join('')}</div>${g.layout.stocks.length>2?`<details class="remnant-stocks" data-remnant-expanded="${gi}" ${RemnantUI.expanded.has(g.signature)?'open':''}><summary>Xem thêm sơ đồ ${unit} (${g.layout.stocks.length-2})</summary><div class="stock-grid">${g.layout.stocks.slice(2,30).map((s,i)=>stockMap(g,s,i+2)).join('')}</div>${g.layout.stocks.length>30?'<p>Sơ đồ hiển thị 30 khổ đầu. Bảng chọn bên cạnh bao gồm phần dư của tất cả các khổ.</p>':''}</details>`:''}<details class="remnant-cut-details"><summary>Chi tiết cần cắt</summary>${g.rows.map(row=>`<div class="cut-legend"><i style="background:${row.color}"></i><span><strong>${esc(row.path.at(-1)||row.label)}</strong><small>${row.geometry.sideLengths?row.geometry.sideLengths.map((x,i)=>'C0'+(i+1)+' = '+num(x)).join('; '):num(row.geometry.length)+(sheet?' × '+num(row.geometry.width):'')} mm</small></span><b>× ${num(row.count)}</b>${rowPolygonButton(row.node)}</div>`).join('')}<p>${g.layout.manual?'Phần chưa phân loại dư / khe cắt':g.layout.mode==='right-triangle'?'Khe cắt và đệm bố trí':'Mạch cắt theo phương án'}: ${num(weight(g.kerfMeasure))} kg.${g.layout.mode==='right-triangle'?` Phần tam giác lẻ còn dư: ${num(weight(g.layout.triangleOffcut))} kg, chưa nằm trong danh sách dư chữ nhật có thể chọn.`:''}${g.layout.mode==='circle'&&!g.layout.manual?` Phần ngoài biên tròn: ${num(weight(g.layout.circleOffcut))} kg, chưa đưa vào danh sách dư chữ nhật.`:''} Phần dư còn lại chưa được chọn không mặc định là phế liệu.</p></details></div>
    <div class="remnant-selection"><div class="remnant-selection-head"><div><h3>Phần dư có thể chọn</h3><p>${selected} / ${g.remnants.length} phần đã chọn</p></div><button class="button small" data-remnant="threshold" data-gi="${gi}" ${!g.remnants.length?'disabled':''}>Chọn theo kích thước…</button></div>${batches.length?`<div class="remnant-table-scroll"><table class="remnant-table"><thead><tr><th>Giữ lại / Kích thước</th><th class="right">Số phần</th><th class="right">Giá trị</th><th></th></tr></thead><tbody>${batches.slice(0,limit).map((batch,bi)=>{const count=batch.parts.filter(r=>r.selected).length;return `<tr class="${count?'has-kept':''}"><td><label><input type="checkbox" ${batch.parts.every(r=>r.eligible===false)?'disabled title="Dưới ngưỡng phần dư đã khai"':''} data-remnant-batch="${bi}" data-gi="${gi}" aria-label="Giữ lại ${remnantSize(g,batch)}, ${batch.parts.length} phần" ${count===batch.parts.length?'checked':''} ${count&&count<batch.parts.length?'data-remnant-mixed':''}><span>${remnantSize(g,batch)}</span></label></td><td class="right mono">${count?count+' / ':''}${batch.parts.length}</td><td class="right mono">${money(batch.parts.reduce((s,r)=>s+r.value,0))} ₫</td><td><button class="text-button" data-remnant="individual" data-gi="${gi}" data-bi="${bi}">Từng phần</button></td></tr>`;}).join('')}</tbody></table></div>${batches.length>limit?`<button class="button small" data-remnant="more" data-gi="${gi}">Xem thêm kích thước (${batches.length-limit})</button>`:''}<p class="remnant-table-help">Giá trị hiển thị cho tất cả các phần trên dòng. Tích chọn = xác nhận phần đó còn dùng được; không phải tự động nhập kho.</p>`:'<div class="muted-row">'+(g.layout.triangleOffcut>0?'Còn phần dư tam giác chưa hỗ trợ chọn tận dụng; không còn dư chữ nhật.':g.layout.mode==='circle'?'Phần dư cong giữa các phôi chưa hỗ trợ chọn tận dụng; không còn dư chữ nhật.':'Không còn phần dư ngoài mạch cắt.')+'</div>'}
    <div class="remnant-group-cost"><span>Tiền mua theo khổ <b>${money(g.purchaseCost)} ₫</b></span><span>Phần đã chọn giữ lại <b>${money(g.recoverableCredit)} ₫</b></span><span class="active-cost">Vật tư tính vào báo giá <b>${money(g.cost)} ₫</b></span></div>${selected?'<button class="button small remnant-compare-link" data-remnant="compare">So sánh 2 phương án giá ↑</button>':''}</div></div></section>`;
}
function remnantThreshold(g){
  const sheet=g.spec.shape==='sheet';openDialog('Chọn phần dư theo kích thước',`<p>${esc(g.spec.id)} · Chỉ chọn phần dư đạt kích thước do anh xác nhận, không chọn mạch cắt. Lựa chọn hiện có vẫn được giữ.</p><div class="form-grid">${field(sheet?'Cạnh dài tối thiểu (mm)':'Chiều dài tối thiểu (mm)','minL',sheet?500:300,'number','min="1" max="100000" required')}${sheet?field('Cạnh ngắn tối thiểu (mm)','minW',200,'number','min="1" max="100000" required'):''}</div><p id="threshold-preview" class="notice"></p><p>Đây là ngưỡng thử, không phải tiêu chuẩn của nhà máy. Hãy chỉnh theo khả năng sử dụng thực tế.</p>`,'Chọn các phần đạt kích thước',f=>{const ids=matches(Number(f.get('minL')),Number(f.get('minW'))||0).map(r=>r.id);if(!ids.length)throw Error('Không có phần dư đạt kích thước này');saveAndClose(()=>setRemnantParts(g,ids,true),'Đã chọn '+ids.length+' phần dư. Bấm “So sánh 2 phương án giá” để rà giá chào.');});
  function matches(l,w){return g.remnants.filter(r=>sheet?Math.max(r.l,r.w)>=Math.max(l,w)&&Math.min(r.l,r.w)>=Math.min(l,w):r.l>=l);}
  const preview=()=>{const parts=matches(Number($('[name=minL]').value),Number($('[name=minW]')?.value)||0);$('#threshold-preview').textContent=parts.length+' phần đạt kích thước · Giá trị '+money(parts.reduce((s,r)=>s+r.value,0))+' ₫';};
  $('#dialog [name=minL]').oninput=preview;if(sheet)$('#dialog [name=minW]').oninput=preview;preview();
}
function individualRemnants(g,bi){
  const batch=remnantBatches(g)[bi];openDialog('Chọn từng phần dư · '+remnantSize(g,batch),`<p>${esc(g.spec.id)} · Chọn đúng những phần muốn giữ lại.</p><div class="remnant-individual">${batch.parts.map(r=>`<label><input type="checkbox" name="part" value="${r.id}" ${r.eligible===false?'disabled':''} ${r.selected?'checked':''}><span>${g.spec.shape==='sheet'?'Tấm':'Thanh'} ${r.stockIndex+1} · ${remnantSize(g,r)}</span><strong>${money(r.value)} ₫</strong></label>`).join('')}</div>`,'Áp dụng lựa chọn',f=>{const ids=f.getAll('part');saveAndClose(()=>{setRemnantParts(g,batch.parts.map(r=>r.id),false);setRemnantParts(g,ids,true);normalizeRemnantMode();},'Đã cập nhật phần dư giữ lại');});
}
document.addEventListener('change',e=>{
  const el=e.target;
  if(el.name==='remnant-mode'){if(el.disabled)return;remnantMutation(()=>{db.quote.remnantMode=el.value;},'[name="remnant-mode"][value="'+el.value+'"]');}
  if(el.hasAttribute('data-remnant-batch')){const g=result.groups[Number(el.dataset.gi)],batch=remnantBatches(g)[Number(el.dataset.remnantBatch)],checked=el.checked;remnantMutation(()=>setRemnantParts(g,batch.parts.map(r=>r.id),checked),'[data-remnant-batch="'+el.dataset.remnantBatch+'"][data-gi="'+el.dataset.gi+'"]');}
});
document.addEventListener('click',e=>{
  const el=e.target.closest('[data-remnant]');if(!el)return;e.preventDefault();const g=result.groups[Number(el.dataset.gi)];
  if(el.dataset.remnant==='compare'){const box=$('.remnant-comparison');box?.scrollIntoView({block:'start'});$('.remnant-option.active input')?.focus({preventScroll:true});}
  else if(['open-waste','open-pricing','open-mass'].includes(el.dataset.remnant)){tab=el.dataset.remnant==='open-waste'?'waste':el.dataset.remnant==='open-mass'?'mass':'pricing';render();window.scrollTo(0,0);}
  else if(el.dataset.remnant==='piece'){const part=g.remnants.find(r=>r.id===el.dataset.rid);remnantMutation(()=>setRemnantParts(g,[part.id],!part.selected),'[data-remnant="piece"][data-gi="'+el.dataset.gi+'"][data-rid="'+el.dataset.rid+'"]');}
  else if(el.dataset.remnant==='threshold')remnantThreshold(g);
  else if(el.dataset.remnant==='individual')individualRemnants(g,Number(el.dataset.bi));
  else if(el.dataset.remnant==='more'){RemnantUI.limits.set(g.signature,(RemnantUI.limits.get(g.signature)||12)+20);const y=scrollY;render();window.scrollTo(0,y);}
  else if(el.dataset.remnant==='review')remnantMutation(()=>{const kept={};for(const group of result.groups.filter(g=>!g.error)){const ids=group.remnants.filter(r=>r.selected).map(r=>r.id);if(ids.length)kept[group.signature]=ids;}db.quote.remnantSelections=kept;});
});
document.addEventListener('toggle',e=>{if(e.target.hasAttribute('data-remnant-expanded')){const g=result.groups[Number(e.target.dataset.remnantExpanded)];if(g)e.target.open?RemnantUI.expanded.add(g.signature):RemnantUI.expanded.delete(g.signature);}},true);

function rowPolygonButton(n){return n?.kind==='material'&&n.spec?.shape==='sheet'?`<button type="button" class="button small" data-row-polygon="${esc(n.id)}">${n.spec.shapeDefinition?.polygon?'Sửa đa giác · '+n.spec.shapeDefinition.polygon.sides.length+' cạnh':'Khai đa giác'}</button>`:'';}
function editRowPolygon(id){
 inWritable();if(Team.loaded&&Team.permissions.canFormulaEdit===false)throw Error('Tài khoản chưa được sửa quy ước hình dạng');const n=C.findNode(db.quote.products,id);if(!n||n.spec?.shape!=='sheet')throw Error('Chọn một dòng vật tư tấm');const old=n.spec.shapeDefinition?.polygon;let initial={};
 if(old)try{const g=DFC().geometry(n,1),angles=TPPolygon.interiorAngles(g.polygon);old.sides.forEach((k,i)=>initial['C'+(i+1)]=g.unfolded[k]);for(let i=0;i<old.sides.length-3;i++)initial['A'+(i+1)]=angles[i+1];if(old.sides.length>3){initial.branch=old.branch||0;initial.checkAngle=old.checkAngle??(old.kind==='interior'?'':angles[old.sides.length-2]);}}catch(_){}
 openDialog('Khai đa giác · '+n.name,`<p>Nhập các cạnh theo thứ tự quanh hình. Tam giác chỉ cần 3 cạnh. Tứ giác cần 4 cạnh và 1 góc giữa hai cạnh; các góc còn lại được tính để khép hình. Có thể nhập thêm một góc để kiểm tra.</p>${field('Số cạnh (3–10)','edgeCount',old?.sides.length||3,'number','min="3" max="10" step="1" required')}<div data-edge-inputs></div><div data-edge-drawing></div><p data-edge-preview role="status"></p><p>Chỉ cập nhật dòng phôi này. Kiểm tra hình xem trước rồi lưu; danh mục quy ước giữ nguyên.</p>`,'Lưu biên dạng cho dòng này',()=>{const value=read();inWritable();saveAndClose(()=>{n.spec=value.spec;n.dims=value.dims;n.paramLinks={};n.dimensionLinks={};db.quote.nestingPlans=(db.quote.nestingPlans||[]).filter(p=>!p.rowIds.includes(id));},'Đã cập nhật biên dạng và tính lại phôi');});const form=$('#dialog-form');let entered={...initial};
 function draw(){for(const input of form.querySelectorAll('[data-edge-inputs] input,[data-edge-inputs] select'))entered[input.name]=input.value;const count=Number(form.elements.edgeCount.value);if(!Number.isInteger(count)||count<3||count>10){form.querySelector('[data-edge-inputs]').innerHTML='';preview();return;}form.querySelector('[data-edge-inputs]').innerHTML='<div class="form-grid">'+Array.from({length:count},(_,i)=>field('Cạnh '+(i+1)+' (mm)','C'+(i+1),entered['C'+(i+1)]??'','number','min="0.000001" step="any" required')).join('')+Array.from({length:count-3},(_,i)=>field('Góc giữa cạnh '+(i+1)+' và '+(i+2)+' (độ)','A'+(i+1),entered['A'+(i+1)]??'','number','min="0.000001" max="359.999999" step="any" required')).join('')+(count>3?field('Góc giữa cạnh '+(count-2)+' và '+(count-1)+' — kiểm tra thêm, có thể bỏ trống','checkAngle',entered.checkAngle??'','number','step="any"')+select('Nếu có hai hình khép kín, chọn hình đúng','branch',[[0,'Hình 1'],[1,'Hình 2']],entered.branch||0):'')+'</div>';preview();}
 function read(){const count=Number(form.elements.edgeCount.value);if(!Number.isInteger(count)||count<3||count>10)throw Error('Số cạnh từ 3 đến 10');const d={id:'QUOTE-POLYGON-'+id,name:'Phôi '+count+' cạnh',...DFC().polygonPreset(count===3?'triangle':'interior',count)},dims={};for(const f of d.fields.filter(f=>f.mode==='input')){const raw=form.elements[f.key]?.value;if(raw===undefined||raw==='')throw Error('Nhập đủ chiều dài cạnh và các góc bắt buộc');dims[f.key]=Number(raw);}if(count>3){d.polygon.branch=Number(form.elements.branch.value);if(form.elements.checkAngle.value!=='')d.polygon.checkAngle=Number(form.elements.checkAngle.value);}const spec=DFC().applyShape(n.spec,d,{T:n.spec.props.T}),g=DFC().geometry({...n,spec,dims},1);return {spec,dims,g};}
 function preview(){const el=form.querySelector('[data-edge-preview]'),drawing=form.querySelector('[data-edge-drawing]');drawing.innerHTML='';try{const {g}=read(),pad=Math.max(g.length,g.width)*.18,angles=TPPolygon.interiorAngles(g.polygon);drawing.innerHTML=`<svg data-polygon-preview role="img" aria-label="Biên dạng đa giác đã khai" viewBox="${-pad} ${-pad} ${g.length+2*pad} ${g.width+2*pad}" style="display:block;width:100%;height:220px"><polygon points="${g.polygon.map(p=>p.join(',')).join(' ')}" fill="#dceaf4" stroke="#285b84" stroke-width="2" vector-effect="non-scaling-stroke"/>${g.polygon.map(([x,y],i)=>{const b=g.polygon[(i+1)%g.polygon.length];return `<text x="${(x+b[0])/2}" y="${(y+b[1])/2}" dy="${-pad*.12}" font-size="${pad*.4}" text-anchor="middle">Cạnh ${i+1}</text>`;}).join('')}</svg>`;el.textContent='Diện tích: '+num(g.blankArea,6)+' m² · Khối lượng: '+num(g.weight,4)+' kg. '+angles.map((a,i)=>'Góc cạnh '+(i===0?angles.length:i)+'–'+(i+1)+': '+num(a,3)+'°').join('; ');form.querySelector('button[type=submit]').disabled=false;}catch(error){el.textContent=error.message;form.querySelector('button[type=submit]').disabled=true;}}
 form.elements.edgeCount.addEventListener('input',draw);form.addEventListener('input',preview);form.addEventListener('change',preview);draw();
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-row-polygon]');if(b)try{editRowPolygon(b.dataset.rowPolygon);}catch(error){toast(error.message);}});
