'use strict';
// Read-only reporting: monetary figures are rounded only at aggregation boundaries.
const round=n=>Math.round((Number(n)||0)*100)/100,number=n=>Number(n)||0;
function day(value){if(!value)return '';if(/^\d{4}-\d{2}-\d{2}$/.test(value))return value;const n=Date.parse(value);return Number.isFinite(n)?new Date(n+7*3600000).toISOString().slice(0,10):'';}
const sum=(rows,key)=>round(rows.reduce((s,r)=>s+number(r[key]),0));
function table(id,title,columns,rows,note=''){return {id,title,columns:columns.map(([key,label,type])=>({key,label,type:type||'text'})),rows:rows.map(r=>({...Object.fromEntries(columns.map(([k])=>[k,r[k]??null])),...(r.source?{source:r.source}:{})})),note};}
function group(rows,key,keys){const m=new Map();for(const row of rows){const k=key(row);if(!m.has(k))m.set(k,{...row,source:undefined,...Object.fromEntries(keys.map(n=>[n,0]))});const r=m.get(k);for(const n of keys)r[n]+=number(row[n]);}return [...m.values()].map(r=>({...r,...Object.fromEntries(keys.map(k=>[k,(/revenue|vat|grand|Value/.test(k)?round(r[k]):Math.round(r[k]*1e6)/1e6)]))}));}
function build(data,filter,rights){
 const {from,to,kind}=filter,inPeriod=x=>{const d=day(x);return !!d&&d>=from&&d<=to;},until=x=>{const d=day(x);return !!d&&d<=to;},tables=[],cards=[],notes=['Ngày chứng từ theo giờ Việt Nam. Chỉ tính chứng từ còn hiệu lực hiện tại; dữ liệu sửa/hủy sau kỳ có thể làm thay đổi báo cáo kỳ cũ.'],options={customers:[],workshops:[],warehouses:[]};
 const include=k=>kind==='overview'||kind===k,card=(label,value,unit='')=>cards.push({label,value,unit});
 if(rights.revenue&&include('revenue')){
  const orders=data.orders.filter(o=>!o.meta.cancelledAt),delivered=orders.filter(o=>o.meta.deliveredAt&&inPeriod(o.meta.deliveryDate||o.meta.deliveredAt)&&(!filter.customer||o.customerKey===filter.customer));
  options.customers=[...new Map(orders.map(o=>[o.customerKey,{id:o.customerKey,name:o.customer}])).values()];
  const rows=delivered.map(o=>({id:o.id,code:o.code,date:day(o.meta.deliveryDate||o.meta.deliveredAt),customer:o.customer,customerKey:o.customerKey,revenue:number(o.offer?.totals?.beforeTax),vat:number(o.offer?.totals?.vat),grand:number(o.offer?.totals?.grand),source:{type:'order',id:o.id}}));
  card('Doanh thu đơn đã giao (chưa thuế)',sum(rows,'revenue'),'đ');card('Đơn đã giao',rows.length,'đơn');
  const money=[['revenue','Chưa thuế','money'],['vat','Thuế','money'],['grand','Sau thuế','money']];
  tables.push(table('revenue-month','Doanh thu theo tháng',[['month','Tháng'],...money],group(rows.map(r=>({...r,month:r.date.slice(0,7)})),r=>r.month,['revenue','vat','grand']).sort((a,b)=>a.month.localeCompare(b.month))));
  tables.push(table('revenue-customer','Doanh thu theo khách hàng',[['customer','Khách hàng'],...money],group(rows,r=>r.customerKey,['revenue','vat','grand'])));
  const products=delivered.flatMap(o=>{const rows=(o.offer?.products||[]).map(p=>({product:p.name,specification:p.specification||'',unit:p.unit||'',quantity:number(p.qty),revenue:number(p.total)})),delta=round(number(o.offer?.totals?.beforeTax)-sum(rows,'revenue'));if(delta)rows.push({product:'Điều chỉnh cấp đơn hàng',specification:'Chênh lệch giữa tổng đơn và các dòng sản phẩm',unit:'',quantity:0,revenue:delta});return rows;});
  tables.push(table('revenue-product','Doanh thu theo sản phẩm',[['product','Sản phẩm'],['specification','Quy cách'],['unit','ĐVT'],['quantity','Số lượng','number'],['revenue','Chưa thuế','money']],group(products,r=>JSON.stringify([r.product,r.specification,r.unit]),['quantity','revenue'])));
  tables.push(table('revenue-source','Đơn hàng nguồn',[['code','Đơn hàng'],['date','Ngày giao'],['customer','Khách hàng'],...money],rows));
  notes.push('Doanh thu báo cáo = giá chốt chưa thuế của đơn đã xác nhận giao trong kỳ; không cộng báo giá chưa chuyển đơn, đơn hủy hoặc tiền ứng trước. Đây là chỉ tiêu vận hành, chưa thay thế sổ doanh thu kế toán.');
  if(rights.debt){const contracts=data.contracts.filter(c=>['active','completed'].includes(c.status)&&until(c.startDate||c.at)&&(!filter.customer||c.customerId===filter.customer||orders.find(o=>o.id===c.orderId)?.customerKey===filter.customer));const debt=contracts.map(c=>{const paid=sum(data.payments.filter(p=>!p.voidedAt&&p.contractId===c.id&&until(p.date)),'amount'),remaining=round(c.value-paid);return {id:c.id,code:c.code,customer:c.customerName||c.customer||orders.find(o=>o.id===c.orderId)?.customer||c.customerId,value:c.value,paid,remaining,due:c.dueDate||'',overdue:remaining>0&&c.dueDate&&c.dueDate<to?'Quá hạn':'',source:{type:'contract',id:c.id}};});card('Phải thu đến cuối kỳ',sum(debt,'remaining'),'đ');tables.push(table('receivable','Công nợ hợp đồng đến cuối kỳ',[['code','Hợp đồng'],['customer','Khách hàng'],['value','Giá trị','money'],['paid','Đã thu','money'],['remaining','Còn phải thu','money'],['due','Hạn thanh toán'],['overdue','Tình trạng']],debt,'Không giới hạn ngày bắt đầu kỳ: công nợ bao gồm hợp đồng từ các kỳ trước. Giá trị/hạn hợp đồng dùng bản hiện hành.'));}
 }
 if(rights.production&&include('production')){
  const jobs=data.jobs.filter(j=>until(j.created)&&(!filter.workshop||(j.progress.workshop||'Chưa phân xưởng')===filter.workshop));options.workshops=[...new Set(data.jobs.map(j=>j.progress.workshop||'Chưa phân xưởng'))].map(id=>({id,name:id}));
  const qc=jobs.filter(j=>inPeriod(j.progress.qc?.at)).map(j=>({id:j.id,code:j.code,product:j.packet.product.name,unit:j.packet.product.unit||'',date:day(j.progress.qc.at),passed:number(j.progress.qc.passed),rejected:number(j.progress.qc.rejected),source:{type:'job',id:j.id}}));
  const output=group(qc,r=>JSON.stringify([r.product,r.unit]),['passed','rejected']);card('Lệnh có QC trong kỳ',qc.length,'lệnh');
  tables.push(table('production-output','Sản lượng được QC trong kỳ',[['product','Sản phẩm'],['unit','ĐVT'],['passed','Đạt','number'],['rejected','Không đạt','number']],output,'Mỗi lệnh lấy lần QC đang có hiệu lực, không cộng sản lượng lặp qua các công đoạn.'));
  tables.push(table('production-qc','Chi tiết QC',[['code','Lệnh'],['date','Ngày QC'],['product','Sản phẩm'],['unit','ĐVT'],['passed','Đạt','number'],['rejected','Không đạt','number'],['ratio','Tỷ lệ đạt (%)','number']],qc.map(r=>({...r,ratio:r.passed+r.rejected?round(r.passed/(r.passed+r.rejected)*100):null}))));
  const unitQC=group(qc,r=>r.unit,['passed','rejected']).map(r=>({unit:r.unit,passed:r.passed,rejected:r.rejected,ratio:r.passed+r.rejected?round(r.passed/(r.passed+r.rejected)*100):null}));tables.push(table('production-quality','Tỷ lệ QC theo đơn vị',[['unit','ĐVT'],['passed','Đạt','number'],['rejected','Không đạt','number'],['ratio','Tỷ lệ đạt (%)','number']],unitQC));
  const progress=jobs.filter(j=>inPeriod(j.created)||j.state!=='completed'||inPeriod(j.updated)).map(j=>{const ops=j.progress.operations||[],total=ops.length,done=ops.filter(o=>o.status==='done').length;return {id:j.id,code:j.code,product:j.packet.product.name,unit:j.packet.product.unit,quantity:j.quantity,workshop:j.progress.workshop||'Chưa phân xưởng',state:({ready:'Chuẩn bị',running:'Đang sản xuất',qc:'Chờ QC',completed:'Hoàn thành'})[j.state],done,total,ratio:total?round(done/total*100):null,deadline:j.progress.deadline||'',late:j.state!=='completed'&&j.progress.deadline&&j.progress.deadline<day(data.now)?'Quá hạn':'',source:{type:'job',id:j.id}};});
  tables.push(table('production-progress','Tiến độ hiện tại của các lệnh liên quan kỳ',[['code','Lệnh'],['product','Sản phẩm'],['quantity','Số lượng','number'],['unit','ĐVT'],['workshop','Xưởng'],['state','Trạng thái'],['done','Công đoạn xong','number'],['total','Tổng công đoạn','number'],['ratio','Hoàn thành (%)','number'],['deadline','Hạn'],['late','Cảnh báo']],progress,'Tiến độ là trạng thái hiện tại, không giả lập trạng thái lịch sử cuối kỳ. Lệnh không có công đoạn hiển thị —.'));
  const workshops=group(jobs.flatMap(j=>(j.progress.operations||[]).filter(o=>o.status==='done'&&inPeriod(o.finishedAt)).map(o=>{const norm=j.packet.operations.find(n=>n.id===o.id);return {workshop:j.progress.workshop||'Chưa phân xưởng',operations:1,actual:number(o.hours),planned:/(^h$|hour|giờ)/i.test(norm?.unit||'')?number(norm.workQuantity):0,known:/(^h$|hour|giờ)/i.test(norm?.unit||'')&&number(o.hours)>0?1:0};})),r=>r.workshop,['operations','actual','planned','known']).map(r=>({...r,efficiency:r.actual&&r.known===r.operations?round(r.planned/r.actual*100):null}));
  tables.push(table('production-workshops','Hiệu suất theo phân xưởng',[['workshop','Xưởng'],['operations','Công đoạn hoàn tất trong kỳ','number'],['planned','Giờ định mức đã khai','number'],['actual','Giờ thực tế đã khai','number'],['efficiency','Định mức / thực tế (%)','number']],workshops,'Chỉ tính hiệu suất khi mọi công đoạn trong nhóm có định mức giờ và giờ thực tế; thiếu căn cứ hiển thị —, không tự đổi kg/lần sang giờ.'));
  notes.push('QC theo ngày xác nhận; hiệu suất theo ngày hoàn tất công đoạn. Không cộng số lượng khác đơn vị thành một tổng sản lượng.');
 }
 if(rights.inventory&&include('inventory')){
  const lots=new Map(data.lots.map(l=>[l.id,l])),materials=new Map(data.materials.map(m=>[m.id,m]));options.warehouses=[...new Set(data.lots.map(l=>l.warehouse))].map(id=>({id,name:id}));const map=new Map();
  for(const m of data.movements){if(!['receipt','return','issue','manual-issue'].includes(m.kind)||!until(m.at)||filter.warehouse&&m.warehouse!==filter.warehouse)continue;const l=lots.get(m.lotId),material=materials.get(m.materialId),key=JSON.stringify([m.materialId,m.warehouse,l?.unit||material?.unit]);if(!map.has(key))map.set(key,{materialId:m.materialId,name:material?.name||l?.materialName||m.materialId,warehouse:m.warehouse,unit:l?.unit||material?.unit||'',opening:0,incoming:0,outgoing:0,openingValue:0,inValue:0,outValue:0,minimum:material?.minimum||0});const r=map.get(key),q=number(m.quantity),v=number(m.value);if(day(m.at)<from){r.opening+=q;r.openingValue+=v;}else if(q>=0){r.incoming+=q;r.inValue+=v;}else{r.outgoing-=q;r.outValue-=v;}}
  const rows=[...map.values()].map(r=>({...r,closing:Math.round((r.opening+r.incoming-r.outgoing)*1e6)/1e6,closingValue:round(r.openingValue+r.inValue-r.outValue)}));
  const cols=[['materialId','Mã vật tư'],['name','Vật tư'],['warehouse','Kho'],['unit','ĐVT'],['opening','Tồn đầu','number'],['incoming','Nhập','number'],['outgoing','Xuất','number'],['closing','Tồn cuối','number']];if(rights.inventoryValue)cols.push(['openingValue','Giá trị đầu','money'],['inValue','Giá trị nhập','money'],['outValue','Giá trị xuất','money'],['closingValue','Giá trị cuối','money']);
  const publicRows=rows.map(r=>rights.inventoryValue?r:Object.fromEntries(Object.entries(r).filter(([k])=>!['openingValue','inValue','outValue','closingValue'].includes(k))));
  tables.push(table('inventory-balance','Nhập – xuất – tồn theo kỳ',cols,publicRows,'Tồn đầu + nhập − xuất = tồn cuối. Hoàn dư là nhập lại; phế không cộng tồn lần nữa. Không cộng số tấm, thanh và kg thành một lượng.'));
  const totals=group(rows,r=>JSON.stringify([r.materialId,r.unit]),['closing']);const low=totals.filter(r=>r.closing<=r.minimum).map(r=>({materialId:r.materialId,name:r.name,unit:r.unit,closing:r.closing,minimum:r.minimum}));
  for(const m of data.materials)if(m.active!==false&&!totals.some(r=>r.materialId===m.id))low.push({materialId:m.id,name:m.name,unit:m.unit,closing:0,minimum:m.minimum||0});
  card('Mã vật tư đến ngưỡng tối thiểu',low.length,'mã');if(rights.inventoryValue)card('Giá trị tồn cuối kỳ',sum(rows,'closingValue'),'đ');
  tables.push(table('inventory-low','Vật tư sắp hết cuối kỳ',[['materialId','Mã'],['name','Vật tư'],['unit','ĐVT'],['closing','Tồn cuối','number'],['minimum','Mức tối thiểu hiện hành','number']],low,'So sánh tổng tồn trong phạm vi kho được chọn với ngưỡng danh mục hiện hành; không trừ phần đang giữ cho lệnh.'));
  const movements=data.movements.filter(m=>inPeriod(m.at)&&(!filter.warehouse||m.warehouse===filter.warehouse)).map(m=>({reference:m.reference,date:day(m.at),kind:({receipt:'Nhập',return:'Hoàn dư',issue:'Cấp sản xuất','manual-issue':'Xuất thủ công',scrap:'Phế'})[m.kind]||m.kind,materialId:m.materialId,warehouse:m.warehouse,quantity:m.quantity,...(rights.inventoryValue?{value:m.value}:{}),source:m.jobId&&rights.production?{type:'job',id:m.jobId}:null}));tables.push(table('inventory-source','Chứng từ kho trong kỳ',[['reference','Chứng từ'],['date','Ngày'],['kind','Loại'],['materialId','Mã vật tư'],['warehouse','Kho'],['quantity','Lượng tăng/giảm','number'],...(rights.inventoryValue?[['value','Giá trị','money']]:[])],movements));
 }
 if(rights.finance&&include('overview')){const ledger=[...data.payments.filter(p=>!p.voidedAt).map(p=>({...p,direction:'in'})),...data.cash.filter(c=>!c.voidedAt)].filter(c=>inPeriod(c.date));card('Tiền thực thu trong kỳ',sum(ledger.filter(c=>c.direction==='in'),'amount'),'đ');card('Tiền thực chi trong kỳ',sum(ledger.filter(c=>c.direction==='out'),'amount'),'đ');notes.push('Tiền thực thu/chi lấy từ phiếu thu hợp đồng và sổ tiền; chi phí phát sinh chưa thanh toán không được tính thành tiền đã chi.');}
 return {kind,from,to,generatedAt:data.now,cards,tables,notes,options};
}
module.exports={build,day};
