'use strict';
function sourceSheets(){const rows=TPSource.rows(db,result),methods=TPSource.visibleMethods(result);return [{name:'Dau vao 38 cot',rows:[TPSource.FIELDS,...rows.map(r=>r.values)],widths:TPSource.FIELDS.map((_,i)=>[1,2,15,37].includes(i)?36:20)},{name:'Phan tich dong kg',rows:[['Chỉ tiêu','Đơn vị',...methods.flatMap(a=>[a.name+' / Mức hoặc đ/kg',a.name+' / giá trị'])],...TPSource.visibleSummary(result).flatMap((r,i,rows)=>[...(i===0||rows[i-1].section!==r.section?[[r.section]]:[]),[r.name,r.unit,...r.values.flatMap(x=>[x.rate??x.perKg??'',x.amount??''])]])],widths:[48,14,...methods.flatMap(()=>[23,23])]},{name:'Cach doc',rows:[['Nội dung','Diễn giải'],['Nguồn đối chiếu','Input Info B:AM: 38 cột trong bảng khách cung cấp. Cột S:Z hiển thị lượng, đơn vị và giá công theo cấp khai báo. Không cộng lại các ô công đoạn lặp theo cấp.'],['Khối lượng','AE/AF là kg vật tư mua / kg phôi toàn số lượng ở dòng. AG nhận diện phần phôi có thuê ngoài, không thay thế lượng tính phí của từng công đoạn.'],['Phôi đặc thù','AK của mẫu thanh là kg/m, không phải kg toàn bộ. Tấm được ghi rõ kg/m². AL là m² cho một chi tiết, không phải tổng diện tích.'],['Hao hụt','R là cân đối vật lý mua/phôi, có thể chứa phần dư thu hồi. Chi phí hao hụt và phần thu hồi xem tab Hao hụt. TMC dùng hệ số bảng nhóm riêng, không dùng R để nhân lại.'],['Vật tư phụ','AI là khoản dự tính bổ sung trên chi phí phôi của dòng. Mặc định 0. Nếu đã khai đủ mã hoặc định mức thì không nhập thêm tỷ lệ cho cùng vật tư.'],['Công thức','Bảng phân tích dùng công thức 3 lớp khách xác nhận mới nhất, không sao chép công thức cũ trong Excel. Các dòng tổng và dòng thành phần không cộng gộp lần nữa.'],['Kg / đối thủ','Giá trọn gói, các khoản cộng riêng được để trống. Cột phương án đang chọn phản ánh giá chốt tay; các cột còn lại là giá đề xuất.'],['Phân quyền','Bảng này có chi phí nội bộ, không gửi người mua. Bản chào khách chỉ lấy giá bán đã duyệt.']],widths:[26,110]}];}
function sourceTable(){const rows=TPSource.rows(db,result);openDialog('Bảng đầu vào đầy đủ · 38 cột',`<p>Dùng để đối chiếu biểu mẫu. Nhập hàng ngày vẫn dùng Bảng nhập nhanh. Chọn Sửa dòng để khai kích thước bổ sung, công thức hoặc mức vật tư phụ.</p><div class="actions">${clButton('Excel đầu vào + phân tích đ/kg','source-export')}${select('Lọc sản phẩm','source-product',[['','Tất cả'],...db.quote.products.map(p=>[p.id,p.name])],'')}</div><div class="table-scroll source-scroll"><table class="source-table"><thead><tr><th>Thao tác</th>${TPSource.FIELDS.map((h,i)=>`<th>${i+1}. ${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr data-source-product="${r.productId}"><td>${clButton('Sửa dòng','source-edit',`data-id="${r.id}"`)}</td>${r.values.map(v=>`<td>${typeof v==='number'?num(v,4):esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p class="help-text">AK: thanh kg/m, tấm kg/m². Cột công đoạn ghi rõ cấp thực hiện; dùng bảng Công đoạn để rà toàn bộ cấp. AG nhận diện phần phôi có thuê ngoài, lượng tính phí theo từng nguyên công có thể khác. AI mặc định 0, không nhập lại phần vật tư đã có mã/định mức.</p>`);$('#dialog').classList.add('wide-dialog');$('[name=source-product]').onchange=e=>document.querySelectorAll('[data-source-product]').forEach(row=>row.hidden=!!e.target.value&&row.dataset.sourceProduct!==e.target.value);}
function sourceEdit(id){const n=C.findNode(db.quote.products,id);if(!n)return;const keys=[...new Set(['L','W','H','D','W1','H1','P','T','F',...TPConventions.entries(db,'parameters').map(x=>x.name),...Object.keys(n.dims||{})])],physical=n.spec.shape!=='piece';openDialog('Thông số dòng · '+esc(n.materialId),`${field('Tên chi tiết','name',n.name,'text','required')}<div class="form-grid three">${field('Số lượng / cấp cha','qty',n.qty,'number','min="0.001" max="5000" step="any" required')}${field('Độ phức tạp','complexity',n.complexity||'')}${field('Ghi chú','notes',n.notes||'')}${physical?keys.map(k=>field(k==='P'?'Bước P (mm)':k+' (mm)','dim-'+k,n.spec.props[k]??n.dims[k]??0,'number',`min="0" max="100000" step="any" ${Object.hasOwn(n.spec.props,k)?'readonly title="Quy cách từ mã vật tư"':''}`)).join(''):''}</div>${physical?`${select('Quy tắc khai triển','rule',db.rules.filter(r=>r.shape===(n.spec.shape==='sheet'?'sheet':'bar')).map(r=>[r.id,r.name]),n.rule)}${field('Vật tư phụ dự tính thêm (% giá phôi dòng này)','auxiliaryPercent',n.auxiliaryPercent||0,'number','min="0" max="100" step="any" required')}<p class="help-text">Tỷ lệ tính trên giá phôi đã chọn của phương án, không tính trên nhân công. Không nhập nếu vật tư đó đã khai bằng mã / định mức. Kích thước liên kết sản phẩm vẫn đồng bộ. W1/H1/P chỉ tác động khi công thức sử dụng biến tương ứng.</p><div class="actions">${clButton('Kg phôi đặc thù','mass',`data-id="${id}"`)}${mfgButton('Công thức lượng thực hiện / bề mặt','measure',`data-id="${id}"`)}</div>`:''}`, 'Lưu thông số', f=>{const trial=C.copy(db),x=C.findNode(trial.quote.products,id);x.name=String(f.get('name')).trim();x.qty=Number(f.get('qty'));x.notes=String(f.get('notes'));x.complexity=String(f.get('complexity'));if(physical){for(const k of keys)if(!Object.hasOwn(n.spec.props,k))C.setDimension(trial,id,k,Number(f.get('dim-'+k)));x.auxiliaryPercent=Number(f.get('auxiliaryPercent'));x.rule=String(f.get('rule'));x.ruleSpec=C.copy(db.rules.find(r=>r.id===x.rule));C.geometry(x,1);}const changed=C.calculate(trial),original=new Set(result.errors),added=changed.errors.filter(e=>!original.has(e)&&!e.includes('phần dư')&&!e.includes('giá chốt tay'));if(added.length)throw Error(added.join('; '));saveAndClose(()=>{db.quote.products=trial.quote.products;});sourceTable();});$('#dialog').classList.add('wide-dialog');}
function sourceAnalysis(){if(!db.quote.pricing)return '';const methods=TPSource.visibleMethods(result),rows=TPSource.visibleSummary(result);return `<section class="panel source-analysis" data-overall-analysis><div class="panel-head"><div><h2>Phân tích cơ cấu giá tổng thể</h2><p>Mỗi phương án: mức hệ số hoặc đơn giá/kg phôi và thành tiền toàn đơn. ${result.tax?.releaseErrors.length?'Số thử tính — còn thiếu xác nhận giá/thuế.':'Giá và thuế đã đủ căn cứ.'}</p></div>${clButton('Xuất Excel phân tích','source-export')}</div><div class="table-scroll"><table><thead><tr><th rowspan="2">Nội dung chi phí</th>${methods.map(a=>`<th colspan="2">${esc(a.name)}<small class="subtext">${a.id===result.pricing.selected?'Đang chọn · gồm giá chốt riêng':'Đối chiếu · giá đề xuất'}${!a.ready?' · Chưa đủ đầu vào':''}</small></th>`).join('')}<th rowspan="2">Nơi khai báo</th></tr><tr>${methods.map(()=>'<th>Mức / đơn giá (đ/kg)</th><th>Thành tiền (đ)</th>').join('')}</tr></thead><tbody>${rows.map((r,i)=>`${i===0||rows[i-1].section!==r.section?`<tr class="analysis-section"><th colspan="${2+methods.length*2}">${esc(r.section)}</th></tr>`:''}<tr class="${r.name==='Lợi nhuận còn lại dự kiến'?'analysis-profit':''}"><th>${esc(r.name)}${['kg','m²'].includes(r.unit)?' ('+r.unit+')':''}</th>${r.values.map(x=>`<td class="right mono">${x.rate!==null?esc(x.rate):x.perKg===null?'—':num(x.perKg,2)}</td><td class="right mono">${x.amount===null?'—':num(x.amount,['đ','%'].includes(r.unit)?0:3)}</td>`).join('')}<td>${TPSource.destination(r)?`<button type="button" class="button small" data-source-jump="${i}" aria-label="Nơi khai báo: ${esc(r.name)}">Khai báo / xem →</button>`:'<span class="muted">Tự tính</span>'}</td></tr>`).join('')}</tbody></table></div><p class="help-text">Kg/đối thủ và công thức tổng dùng chi phí để tham khảo, không cộng lại vào giá trọn gói. Hệ số có nhiều mức hiển thị các mức đang dùng; thành tiền lấy từ từng sản phẩm. Lợi nhuận còn lại dự kiến = giá chào trước thuế − giá gốc − xử lý, chưa phải lợi nhuận ròng. Các dòng tổng và thành phần không cộng gộp lần nữa.</p></section>`;}
function installSourceUI(){const old=renderQuickBOM;renderQuickBOM=()=>`<div class="actions source-toolbar">${clButton('Bảng đầy đủ · 38 cột','source-table')}</div>`+old();document.addEventListener('click',e=>{const b=e.target.closest('[data-close-gap]');if(!b)return;try{if(b.dataset.closeGap==='source-table')sourceTable();else if(b.dataset.closeGap==='source-edit')sourceEdit(b.dataset.id);else if(b.dataset.closeGap==='source-export')download('NOI-BO-DAU-VAO-PHAN-TICH.xlsx',TPXlsx.make(sourceSheets()),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');}catch(e){toast(e.message);}});}

// Navigate through the normal render/permission gates. Never unlock an approved quote.
document.addEventListener('click',event=>{
 const button=event.target.closest('[data-source-jump]');if(!button)return;
 const row=TPSource.visibleSummary(result)[Number(button.dataset.sourceJump)],target=row&&TPSource.destination(row);if(!target)return;
 if(row.name==='Phân loại khách hàng'&&Team.user&&teamCurrent()?.id){sourceCustomerClassification().catch(error=>toast(error.message));return;}
 page='quote';tab=target.tab;if(target.group)Intake.priceTab=target.group;render();
 const anchor=target.focus&&document.querySelector(target.focus)||document.querySelector('[data-quote-price-selector]')||document.querySelector('#content');
 anchor?.scrollIntoView({block:'center',behavior:'smooth'});anchor?.focus?.({preventScroll:true});
 if(['submitted','approved'].includes(db.quote.status))toast('Bản đã trình/duyệt đang khóa. Cần người có quyền mở bản sửa trước khi bổ sung.');
});

async function sourceCustomerClassification(){
 const link=teamCurrent(),id=link?.id,generation=Team.sessionGeneration;
 if(!id)return;
 const data=await teamApi('quotes/'+id+'/customer-classification');
 if(teamCurrent()?.id!==id||Team.sessionGeneration!==generation)return;
 const writable=data.canDeclare&&!link.readOnly;
 teamDialog('Phân loại khách hàng',`<p>Chọn loại khách từ danh mục đã phát hành. Hệ thống áp dụng hệ số tương ứng cho báo giá này.</p><p>Đang áp dụng: <strong>${esc(data.selection||'Chưa khai')}</strong></p>${select('Loại khách hàng','classification',[['','Chọn loại khách hàng'],...data.choices.map(x=>[x.name,x.name+(x.description?' · '+x.description:'')])],data.selection,`required ${writable?'':'disabled'}`)}${!data.choices.length?'<p class="notice">Chưa có loại khách trong danh mục đã phát hành. Người quản lý danh mục cần khai và phát hành trước.</p>':''}${!writable?'<p class="notice">Chỉ xem. Cần quyền khai báo và bản nháp được mở sửa để cập nhật.</p>':''}`,'Lưu phân loại',async f=>{
  if(!writable)throw Error('Không có quyền khai báo hoặc báo giá đang khóa');
  if(teamCurrent()?.id!==id||Team.sessionGeneration!==generation)throw Error('Báo giá hoặc phiên đăng nhập đã thay đổi; mở lại khai báo');
  if(Team.dirty)throw Error('Báo giá có thay đổi chưa lưu. Đóng cửa sổ, lưu báo giá rồi chọn lại phân loại.');
  await teamApi('quotes/'+id+'/customer-classification','POST',{name:String(f.get('classification')),expectedVersion:link.version});
  closeDialog();await teamLoad(id);tab='pricing';render();toast('Đã lưu phân loại khách hàng và tính lại báo giá');
 });
 if(!writable||!data.choices.length)$('#dialog-form button[type="submit"]')?.setAttribute('disabled','');
}
