/* Verified source: Input Info B:AM, 38 columns. Units and calculation versions stay explicit. */
(function(root){'use strict';
const C=typeof module!=='undefined'?require('./core.js'):root.TP;
const FIELDS=['STT','Tên sản phẩm','Thông số cấu kiện','Vật liệu','Kiểu dáng','Đặc tính / mác','Hoàn thiện bề mặt','L (mm)','W (mm)','H (mm)','Đường kính (mm)','W1 (mm)','H1 (mm)','Bước (mm)','Dày (mm)','Mã / quy cách vật tư','Hao hụt vật lý (%)','Cắt tấm','Cắt ống','Chấn','Uốn','Hàn','Mài','Làm sạch','Khác','SL / cấp cha','Độ phức tạp cấu kiện','SL sản phẩm','Đơn vị','KL vật tư mua (kg)','KL phôi sản phẩm (kg)','KL thuê ngoài (kg)','S thực hiện (m²)','Vật tư phụ (%)','Kiểm tra khai báo','Phôi đặc thù (kg/m; tấm kg/m²)','S bề mặt riêng (m²/cái)','Ghi chú'];
function rows(db,result){return result.rows.map((row,i)=>{const n=row.node,r=result.nodes[n.id],p=C.findNode(db.quote.products,row.productId),ancestor=C.flatten([p]).filter(x=>x.kind!=='material'&&C.findNode([x],n.id)),parent=ancestor.at(-1)||p,pr=result.nodes[parent.id];const names=['Cắt tấm','Cắt ống','Chấn','Uốn','Hàn','Mài','Làm sạch'];const ops=(r.ownOps||[]).filter(o=>!o.skipped),scope=[...ancestor,n].map(x=>x.finishType).filter(Boolean).join(' / ');const own=(name,other=false)=>[...ancestor,n].flatMap(owner=>(result.nodes[owner.id].ownOps||[]).filter(o=>!o.skipped&&(other?!names.includes(o.name):o.name===name)).map(o=>owner.name+' → '+o.name+': '+o.basis+' '+o.unit+' × '+o.rate+(o.mode==='outside'?' (thuê)':' (xưởng)'))).join('; ');return {id:n.id,productId:p.id,values:[i+1,p.name,parent===p?n.name:parent.name+' / '+n.name,n.spec.substance,C.shapes[n.spec.shape]?.name,[n.spec.characteristic,n.spec.grade].filter(Boolean).join(' / '),scope||ancestor.flatMap(x=>(result.nodes[x.id].ownOps||[]).filter(o=>/sơn|mạ/i.test(o.name)).map(o=>o.name)).join('; '),...['L','W','H','D','W1','H1','P','T'].map(k=>n.spec.props[k]??n.dims[k]??''),n.materialId+' / '+n.spec.name,row.geometry.weight?((row.purchasedWeight||0)/row.geometry.weight-1)*100:0,...names.map(name=>own(name)),own('',true),n.qty,n.complexity||parent.complexity||'',p.qty,p.unit||'bộ',row.purchasedWeight||0,row.geometry.weight,r.coveredBy||ops.some(o=>o.mode==='outside')||ancestor.some(x=>(result.nodes[x.id].ownOps||[]).some(o=>o.mode==='outside'&&!o.skipped))?r.weight:0,r.workArea??r.area,n.auxiliaryPercent||0,result.errors.filter(e=>e.includes(n.name)).join('; ')||'Đã tính',n.spec.massOverride?C.materialMass(n.spec):'',(r.workArea??r.area)/r.count,n.notes||'']};});}
function analysis(result){const values=Object.values(result.alternatives);return [
 ['Khối lượng vật tư mua',a=>result.rows.reduce((s,r)=>s+(r.purchasedWeight||0),0),'kg'],['Khối lượng phôi sản phẩm',a=>a.total.weight,'kg'],
 ['Phôi gia công',a=>a.total.parts.stock],['Linh kiện / vật tư phụ khai mã',a=>a.total.parts.ancillary],['Vật tư phụ dự tính theo %',a=>a.total.parts.allowance],['Vật tư hoàn thiện theo định mức',a=>a.total.parts.finishing],['Công đoạn tại xưởng',a=>a.total.parts.factory],['Gia công thuê ngoài',a=>a.total.parts.outside],['Chi phí chung riêng TMC',a=>a.total.parts.tmcCommon],['Vận chuyển nhập vật tư',a=>a.total.parts.incoming],['Vận chuyển thuê ngoài',a=>a.total.parts.outgoing],['Chi phí trực tiếp sản xuất',a=>a.total.direct],['Chi phí chung / hệ số sản xuất',a=>a.total.overhead],['Chi phí quản lý',a=>a.total.management],['Yếu tố khác trong sản xuất',a=>a.total.special],['Yếu tố sản xuất bổ sung',a=>a.total.productionExtras||0],['Giá sản xuất',a=>a.total.production],['Vận chuyển giao hàng',a=>a.total.parts.delivery],['Lắp đặt',a=>a.total.parts.install],['Giá gốc',a=>a.total.cost],
 ['Lợi nhuận dự kiến cộng vào giá',a=>['kg','competitor'].includes(a.id)?null:a.total.profitMarkup],['Chi phí xử lý cộng vào giá',a=>['kg','competitor'].includes(a.id)?null:a.total.processing],['Hệ số đơn hàng',a=>['kg','competitor'].includes(a.id)?null:a.total.order],['Hệ số khách hàng',a=>['kg','competitor'].includes(a.id)?null:a.total.customer],['Dự phòng / yếu tố bán thêm',a=>['kg','competitor'].includes(a.id)?null:a.total.saleExtras],['Giá chào trước thuế',a=>(a.id===result.pricing.selected?result.total:a.total).beforeTax],['Còn lại so với giá gốc — chưa phải lãi ròng',a=>(a.id===result.pricing.selected?result.total:a.total).beforeTax-a.total.cost]
 ].map(([name,get,unit='đ'])=>({name,unit,values:values.map(a=>{const amount=a.ready?get(a):null;return {amount,perKg:unit==='đ'&&amount!==null&&a.total.weight>0?amount/a.total.weight:null};})}));}
const api={FIELDS,rows,analysis};if(typeof module!=='undefined')module.exports=api;else root.TPSource=api;
})(typeof window!=='undefined'?window:globalThis);
