'use strict';
function taxPanel(){const t=result.tax;if(!t)return '';return `<section class="panel intake-panel" data-tax-panel><div class="section-toolbar"><div><h3>Mặt bằng giá và thuế</h3><p>${t.releaseErrors.length?'Chưa đủ căn cứ phát hành. Bản làm việc vẫn giữ số thử tính; không coi là giá đã xác nhận.':'Đã khai căn cứ thuế cho phương án đang chọn. Vẫn cần duyệt bản chào trước khi phát hành.'}</p></div><button class="button primary" data-tax="edit">Khai giá và điều kiện thuế</button></div>${t.releaseErrors.length?`<p class="help-text">${t.releaseErrors.map(esc).join('<br>')}</p>`:''}<p class="help-text">Giá kg / đối thủ đã bao gồm chi phí trọn gói. “Đã gồm thuế” được chia cho (1 + thuế suất nằm trong giá), sau đó mới tính thuế đầu ra đã khai. Không mặc định hai thuế suất giống nhau.</p></section>`;}
function taxComparisonRows(row){const metrics=[['Giá nhập và điều kiện thuế',a=>['kg','competitor'].includes(a.id)?result.tax.methods[a.id].inputs.map(i=>esc(i.name)+': '+taxNumber(i.original)+' · '+(i.status==='included'?'Đã gồm '+num(i.rate)+'%':i.status==='excluded'?'Chưa gồm thuế':'Chưa xác nhận')).join('<br>'):a.id==='tmc'?(result.tmcPolicyErrors.length?'Chưa khai chuỗi riêng TMC':'Chuỗi TMC riêng; nguồn giá/thuế theo bậc đang dùng'):result.tax.costKnown?'Đã rà các đầu vào chi phí chưa thuế':'Chi phí chưa xác nhận mặt bằng thuế'],['Trạng thái mặt bằng giá',a=>result.tax.methods[a.id].comparable?'Đã đưa về trước thuế':result.tax.methods[a.id].reasons.map(esc).join('<br>')],['Giá trước thuế / kg phôi',a=>taxNumber(result.tax.methods[a.id].perKg)],['Chênh so tính toán (đ)',a=>taxNumber(result.tax.methods[a.id].deltaDetail)],['Chênh so tính toán (%)',a=>taxPercent(result.tax.methods[a.id].deltaDetailPercent)],['Chênh so đối thủ (đ)',a=>taxNumber(result.tax.methods[a.id].deltaCompetitor)],['Chênh so đối thủ (%)',a=>taxPercent(result.tax.methods[a.id].deltaCompetitorPercent)],['Giá thị trường độc lập (trước thuế)',()=>taxNumber(result.tax.market)],['Chênh so thị trường (đ)',a=>taxNumber(result.tax.methods[a.id].deltaMarket)],['Chênh so thị trường (%)',a=>taxPercent(result.tax.methods[a.id].deltaMarketPercent)],['Tập chi phí tham khảo không trùng',()=>taxNumber(result.tax.reference)],['Phần còn lại sau chi phí tham khảo',a=>taxNumber(result.tax.methods[a.id].residual)]];return metrics.map(([name,get])=>row(name,get,{explain:name.includes('(%)')?'Mẫu số: tổng trước thuế của phương án được so với. Bằng 0 → N/A.':name.includes('Phần còn lại')?'Giá trước thuế − (giá gốc chi tiết + xử lý). Không phải lợi nhuận ròng.':name.includes('Tập chi phí')?'Vật tư + công + SX bổ sung + quản lý + VC nhập/thuê/giao + lắp đặt + xử lý. Không trừ thêm tổng SX hoặc tổng giá gốc lần nữa.':''})).join('');}
function taxNumber(v){return v===null||v===undefined||!Number.isFinite(v)?'N/A':money(v);}
function taxPercent(v){return v===null||v===undefined||!Number.isFinite(v)?'N/A':num(v,2)+'%';}
function taxEdit(){inWritable();const q=db.quote,d=q.pricing.taxReview||{};
 openDialog('Giá đầu vào và điều kiện thuế',`<p>Chỉ khai theo nguồn giá thực tế. Không biết thì giữ “Chưa xác nhận”. Các tỷ lệ ở đây do người lập nhập, không phải thuế suất hệ thống tự quyết.</p>${q.products.map((n,i)=>`<section class="pa-input-product"><h3>${esc(n.name)}</h3><div class="form-grid">${field('Nguồn giá thị trường (khác giá đối thủ)','market-source-'+i,n.marketSource||'')}${['kg','competitor','market'].map(m=>{const old=d.inputs?.[n.id]?.[m],check=TPTax.declaration(q,n,m);return field(m==='kg'?'Giá trọn gói / kg phôi':(m==='market'?'Giá thị trường / ':'Giá đối thủ / ')+(n.unit||'bộ'),m+'-value-'+i,n[m==='kg'?'pricePerKg':m==='market'?'marketPrice':'competitorPrice']??'','number','min="0" step="any"')+select('Thuế trong giá','tax-'+m+'-'+i,[['unknown','Chưa xác nhận'],['excluded','Chưa gồm thuế'],['included','Đã gồm thuế']],check.known?old.status:'unknown')+field('Thuế suất đã nằm trong giá (%)','rate-'+m+'-'+i,check.known&&old.status==='included'?old.rate:'','number','min="0" max="100" step="any"');}).join('')}</div></section>`).join('')}<h3>Chi phí phương án tính toán</h3><p class="help-text">Rà giá vật tư, thương hiệu, nguyên công, định mức, gói thuê, vận chuyển, công lắp thiết bị và cơ sở tiền tính %. Dùng bảng “Giá nguồn → giá chi phí chưa thuế” bên dưới để giữ nguồn và quy đổi từng giá có thuế. Ô dưới đây là khai rõ rằng mọi giá chi phí còn chưa xác nhận hiện đã là số chưa thuế; không tự chia thuế hoặc thay danh mục.</p><label class="device-confirm"><input type="checkbox" name="costConfirmed"> Tôi đã rà: mọi giá chi phí đang tính đều chưa thuế; khai các dòng chưa xác nhận là giá chưa thuế</label><h3>Thuế đầu ra</h3>${field('Thuế suất đầu ra (%)','outputRate',q.vat,'number','min="0" max="100" step="any" required')}<label class="device-confirm"><input type="checkbox" name="outputConfirmed"> Tôi xác nhận thuế suất đầu ra cho báo giá này</label>${field('Căn cứ / tài liệu / ghi chú đối chiếu','taxReason',d.reason||'','text','required')}<p class="help-text">Lưu theo báo giá, không sửa danh mục. Đổi đầu vào chi phí sẽ mất hiệu lực xác nhận chi phí; đổi giá trọn gói sẽ yêu cầu khai lại thuế của giá đó. Giá thị trường là tham khảo độc lập, không phải phương án thứ năm và không tự thay giá đối thủ. Trống/thiếu nguồn/thuế thì chỉ số thị trường là N/A.</p>`,'Lưu giá và căn cứ',f=>{
   inWritable();const trial=C.copy(q),inputs={};trial.vat=Number(f.get('outputRate'));
   trial.products.forEach((n,i)=>{n.marketSource=String(f.get('market-source-'+i)||'').trim();inputs[n.id]={};for(const m of ['kg','competitor','market']){const value=f.get(m+'-value-'+i);n[m==='kg'?'pricePerKg':m==='market'?'marketPrice':'competitorPrice']=value===''?null:Number(value);inputs[n.id][m]={status:f.get('tax-'+m+'-'+i),rate:f.get('rate-'+m+'-'+i)};}});
   TPTax.review(trial,{inputs,reason:f.get('taxReason'),costConfirmed:f.has('costConfirmed'),outputConfirmed:f.has('outputConfirmed')});
   saveAndClose(()=>{q.vat=trial.vat;for(let i=0;i<q.products.length;i++){q.products[i].pricePerKg=trial.products[i].pricePerKg;q.products[i].competitorPrice=trial.products[i].competitorPrice;q.products[i].marketPrice=trial.products[i].marketPrice;q.products[i].marketSource=trial.products[i].marketSource;}const applied=new Map(TPCostInput.rows(trial).map(r=>[r.key,r.value]));for(const r of TPCostInput.rows(q))if(applied.has(r.key))r.target[r.field]=applied.get(r.key);q.costPriceSources=trial.costPriceSources;q.costPriceHistory=trial.costPriceHistory;q.pricing.taxReview=trial.pricing.taxReview;},'Đã lưu giá và căn cứ thuế trong báo giá');
 });$('#dialog').classList.add('wide-dialog');
}
function installTaxUI(){
 const prices=renderQuotePrices,analysis=renderCostAnalysis;renderQuotePrices=()=>taxPanel()+prices();renderCostAnalysis=()=>taxPanel()+analysis();
 const paperBefore=renderAdvancedPaper;renderAdvancedPaper=()=>{const html=paperBefore();return db.quote.pricing&&db.quote.documentMode!=='official'&&result.tax.releaseErrors.length?`<div class="notice warning">BẢN THỬ TÍNH — CHƯA XÁC NHẬN MẶT BẰNG GIÁ/THUẾ. Không dùng để phát hành.</div>`+html:html;};
 const sheetsBefore=exportSheets;exportSheets=internal=>{const sheets=sheetsBefore(internal);if(!result.tax)return sheets;if(db.quote.documentMode==='official'&&result.tax.releaseErrors.length)throw Error('Chưa xác nhận giá/thuế để phát hành');sheets[0].rows.push(['Căn cứ giá/thuế',result.tax.releaseErrors.length?'CHƯA XÁC NHẬN — chỉ thử tính':'Đã khai căn cứ; đơn giá và thành tiền hàng là trước thuế']);if(internal){const rows=[['NỘI BỘ — đối chiếu cùng mặt bằng trước thuế','Tính toán','TMC','Kg phôi','Đối thủ']];for(const [label,key]of [['Giá trước thuế','net'],['Giá / kg phôi','perKg'],['Chênh so tính toán (đ)','deltaDetail'],['Chênh so tính toán (%)','deltaDetailPercent'],['Chênh so đối thủ (đ)','deltaCompetitor'],['Chênh so đối thủ (%)','deltaCompetitorPercent'],['Chênh so thị trường (đ)','deltaMarket'],['Chênh so thị trường (%)','deltaMarketPercent'],['Phần còn lại — không phải lợi nhuận ròng','residual']])rows.push([label,...['detail','tmc','kg','competitor'].map(id=>result.tax.methods[id][key]??'N/A')]);rows.push(['Tập tham khảo: giá gốc chi tiết + xử lý',result.tax.reference??'N/A'],['Căn cứ',db.quote.pricing.taxReview?.reason||'Chưa khai'],['Thời điểm khai',db.quote.pricing.taxReview?.at||''],['Mẫu số tỷ lệ','Tổng trước thuế của PA được so với; bằng 0 → N/A'],['TMC',result.tax.methods.tmc.reasons.join('; ')||'Đã đủ chuỗi riêng và căn cứ nguồn/thuế'],['Thị trường độc lập trước thuế',result.tax.market??'N/A']);for(const [id,m]of Object.entries(result.tax.methods)){rows.push([id,m.reasons.join('; ')]);for(const i of m.inputs)rows.push([i.name,id,i.original,i.status,i.rate??'',i.net??'N/A']);}sheets.push({name:'Mat bang gia thue',widths:[48,26,26,26,26,26],rows});}return sheets;};
 document.addEventListener('click',e=>{if(e.target.closest('[data-tax="edit"]'))try{taxEdit();}catch(err){toast(err.message);}});
}
