'use strict';
function taxPanel(){const t=result.tax;if(!t)return '';return `<section class="panel intake-panel" data-tax-panel><div class="section-toolbar"><div><h3>Mặt bằng giá và thuế</h3><p>${t.releaseErrors.length?'Chưa đủ căn cứ phát hành. Bản làm việc vẫn giữ số thử tính; không coi là giá đã xác nhận.':'Đã khai căn cứ thuế cho phương án đang chọn. Vẫn cần duyệt bản chào trước khi phát hành.'}</p></div><button class="button primary" data-tax="edit">Khai điều kiện thuế</button></div>${t.releaseErrors.length?`<p class="help-text">${t.releaseErrors.map(esc).join('<br>')}</p>`:''}<p class="help-text">Giá kg / đối thủ cộng thêm các khoản được khai chưa gồm theo PA tính toán; khoản đã gồm không cộng lại. “Đã gồm thuế” được chia cho (1 + thuế suất nằm trong giá), sau đó mới tính thuế đầu ra đã khai. Không mặc định hai thuế suất giống nhau.</p></section>`;}
function taxComparisonRows(row){const metrics=[['Giá nhập và điều kiện thuế',a=>['kg','competitor'].includes(a.id)?result.tax.methods[a.id].inputs.map(i=>esc(i.name)+': '+taxNumber(i.original)+' · '+(i.status==='included'?'Đã gồm '+num(i.rate)+'%':i.status==='excluded'?'Chưa gồm thuế':'Chưa xác nhận')).join('<br>'):a.id==='tmc'?(result.tmcPolicyErrors.length?'Chưa khai chuỗi riêng TMC':'Chuỗi TMC riêng; nguồn giá/thuế theo bậc đang dùng'):result.tax.costKnown?'Đã rà các đầu vào chi phí chưa thuế':'Chi phí chưa xác nhận mặt bằng thuế'],['Trạng thái mặt bằng giá',a=>result.tax.methods[a.id].comparable?'Đã đưa về trước thuế':result.tax.methods[a.id].reasons.map(esc).join('<br>')],['Giá trước thuế / kg phôi',a=>taxNumber(result.tax.methods[a.id].perKg)],['Chênh so tính toán (đ)',a=>taxNumber(result.tax.methods[a.id].deltaDetail)],['Chênh so tính toán (%)',a=>taxPercent(result.tax.methods[a.id].deltaDetailPercent)],['Chênh so đối thủ (đ)',a=>taxNumber(result.tax.methods[a.id].deltaCompetitor)],['Chênh so đối thủ (%)',a=>taxPercent(result.tax.methods[a.id].deltaCompetitorPercent)],['Giá thị trường độc lập (trước thuế)',()=>taxNumber(result.tax.market)],['Chênh so thị trường (đ)',a=>taxNumber(result.tax.methods[a.id].deltaMarket)],['Chênh so thị trường (%)',a=>taxPercent(result.tax.methods[a.id].deltaMarketPercent)],['Tập chi phí tham khảo không trùng',()=>taxNumber(result.tax.reference)],['Phần còn lại sau chi phí tham khảo',a=>taxNumber(result.tax.methods[a.id].residual)]];return metrics.map(([name,get])=>row(name,get,{explain:name.includes('(%)')?'Mẫu số: tổng trước thuế của phương án được so với. Bằng 0 → N/A.':name.includes('Phần còn lại')?'Giá trước thuế − (giá gốc chi tiết + xử lý). Không phải lợi nhuận ròng.':name.includes('Tập chi phí')?'Vật tư + công + SX bổ sung + quản lý + VC nhập/thuê/giao + lắp đặt + xử lý. Không trừ thêm tổng SX hoặc tổng giá gốc lần nữa.':''})).join('');}
function taxNumber(v){return v===null||v===undefined||!Number.isFinite(v)?'N/A':money(v);}
function taxPercent(v){return v===null||v===undefined||!Number.isFinite(v)?'N/A':num(v,2)+'%';}
function taxEdit(){inWritable();const q=db.quote,d=q.pricing.taxReview||{};
 const inputRows=q.products.map((n,i)=>`<section class="pa-input-product"><h3>${esc(n.name)}</h3><div>${field('Nguồn giá thị trường (khác giá đối thủ)','market-source-'+i,n.marketSource||'')}${['kg','competitor','market'].map(m=>{const old=d.inputs?.[n.id]?.[m],check=TPTax.declaration(q,n,m),value=n[m==='kg'?'pricePerKg':m==='market'?'marketPrice':'competitorPrice'],label=m==='kg'?'Giá trọn gói / kg phôi':(m==='market'?'Giá thị trường (không bắt buộc) / ':'Giá đối thủ / ')+(n.unit||'bộ');return `<fieldset data-tax-benchmark="${m}"><legend>${label}</legend><div class="form-grid">`+(m==='market'?field(label,m+'-value-'+i,value??'','number','min="0" step="any"'):`<div class="field"><span>${label} đã khai</span><strong data-tax-price="${m}">${value==null?'Chưa khai':money(value)+' đ'}</strong></div>`)+select('Thuế trong giá','tax-'+m+'-'+i,[['unknown','Chưa xác nhận'],['excluded','Chưa gồm thuế'],['included','Đã gồm thuế']],check.known?old.status:'unknown')+field('Thuế suất đã nằm trong giá (%)','rate-'+m+'-'+i,check.known&&old.status==='included'?old.rate:'','number','min="0" max="100" step="any"')+'</div></fieldset>';}).join('')}</div></section>`).join('');
 openDialog('Điều kiện thuế của báo giá',`<p>Giá kg và giá đối thủ lấy từ phần đã khai. Muốn đổi giá, mở “Giá kg / đối thủ”. Thuế suất do người lập xác nhận theo từng nguồn giá.</p><p class="help-text">Giá thị trường không bắt buộc: có thể để trống và vẫn lưu căn cứ thuế. Chọn “Chưa gồm thuế” thì không cần nhập thuế suất nằm trong giá; thuế đầu ra khai riêng bên dưới.</p>${inputRows}<h3>Chi phí phương án tính toán</h3><p class="help-text">Rà giá vật tư, nguyên công, gói thuê, vận chuyển và lắp đặt. Bảng “Giá nguồn → giá chi phí chưa thuế” giữ nguồn và quy đổi từng giá có thuế.</p><label class="device-confirm"><input type="checkbox" name="costConfirmed" ${result.tax.costKnown?'checked':''}> Tôi đã rà: mọi giá chi phí đang tính đều chưa thuế; khai các dòng chưa xác nhận là giá chưa thuế</label><h3>Thuế đầu ra</h3>${select('Áp dụng thuế','outputScope',[['quote','Chung toàn bộ báo giá'],['product','Riêng từng sản phẩm']],q.outputTax?.scope||'quote')}<div data-tax-scope="quote">${field('Thuế suất chung (%)','outputRate',q.vat,'number','min="0" max="100" step="any" required')}</div><div data-tax-scope="product"><p class="help-text">Khai đủ từng sản phẩm. Tiền thuế được cộng theo từng thuế suất, làm tròn đến đồng rồi cộng vào tổng.</p>${q.products.map((n,i)=>field(n.name+' — thuế suất (%)','output-product-'+i,q.outputTax?.rates?.[n.id]??'','number','min="0" max="100" step="any" required')).join('')}</div><label class="device-confirm"><input type="checkbox" name="outputConfirmed" ${result.tax.outputKnown?'checked':''}> Tôi xác nhận các thuế suất đầu ra đã khai</label>${field('Căn cứ / tài liệu / ghi chú đối chiếu','taxReason',d.reason||'','text','required')}<p class="help-text">Đổi giá đầu vào hoặc thuế suất sẽ yêu cầu xác nhận lại phần liên quan. Không tự suy ra thuế suất từ nhóm sản phẩm.</p>`,'Lưu căn cứ thuế',f=>{
  inWritable();const trial=C.copy(q),inputs={},scope=f.get('outputScope');
  if(scope==='quote'){trial.vat=Number(f.get('outputRate'));trial.outputTax={scope:'quote'};}
  else trial.outputTax={scope:'product',rates:Object.fromEntries(trial.products.map((n,i)=>[n.id,f.get('output-product-'+i)===''?null:Number(f.get('output-product-'+i))]))};
  if(TPTax.outputErrors(trial).length)throw Error(TPTax.outputErrors(trial).join('; '));
  trial.products.forEach((n,i)=>{n.marketSource=String(f.get('market-source-'+i)||'').trim();const value=f.get('market-value-'+i);n.marketPrice=value===''?null:Number(value);inputs[n.id]={};for(const m of ['kg','competitor','market'])inputs[n.id][m]={status:f.get('tax-'+m+'-'+i)||'unknown',rate:f.get('rate-'+m+'-'+i)};});
  TPTax.review(trial,{inputs,reason:f.get('taxReason'),costConfirmed:f.has('costConfirmed'),outputConfirmed:f.has('outputConfirmed')});
  saveAndClose(()=>{q.vat=trial.vat;q.outputTax=trial.outputTax;for(let i=0;i<q.products.length;i++){q.products[i].marketPrice=trial.products[i].marketPrice;q.products[i].marketSource=trial.products[i].marketSource;}const applied=new Map(TPCostInput.rows(trial).map(r=>[r.key,r.value]));for(const r of TPCostInput.rows(q))if(applied.has(r.key))r.target[r.field]=applied.get(r.key);q.costPriceSources=trial.costPriceSources;q.costPriceHistory=trial.costPriceHistory;q.pricing.taxReview=trial.pricing.taxReview;},'Đã lưu căn cứ thuế');
 });$('#dialog').classList.add('wide-dialog');const sync=()=>{for(const el of document.querySelectorAll('[data-tax-scope]')){const active=el.dataset.taxScope===$('#dialog [name=outputScope]').value;el.hidden=!active;for(const input of el.querySelectorAll('input'))input.disabled=!active;}};$('#dialog [name=outputScope]').addEventListener('change',sync);sync();
 const syncInputs=()=>{q.products.forEach((n,i)=>{for(const m of ['kg','competitor','market']){const value=m==='market'?$('#dialog [name=market-value-'+i+']').value:n[m==='kg'?'pricePerKg':'competitorPrice'],present=value!==null&&value!==undefined&&value!=='';const status=$('#dialog [name=tax-'+m+'-'+i+']'),rate=$('#dialog [name=rate-'+m+'-'+i+']');status.disabled=!present;rate.disabled=!present||status.value!=='included';}});};$('#dialog-form').addEventListener('input',syncInputs);$('#dialog-form').addEventListener('change',syncInputs);syncInputs();
}
function installTaxUI(){
 const prices=renderQuotePrices,analysis=renderCostAnalysis;renderQuotePrices=()=>taxPanel()+prices();renderCostAnalysis=()=>taxPanel()+analysis();
 const paperBefore=renderAdvancedPaper;renderAdvancedPaper=()=>{const html=paperBefore();return db.quote.pricing&&db.quote.documentMode!=='official'&&result.tax.releaseErrors.length?`<div class="notice warning">BẢN THỬ TÍNH — CHƯA XÁC NHẬN MẶT BẰNG GIÁ/THUẾ. Không dùng để phát hành.</div>`+html:html;};
 const sheetsBefore=exportSheets;exportSheets=internal=>{const sheets=sheetsBefore(internal);if(!result.tax)return sheets;if(db.quote.documentMode==='official'&&result.tax.releaseErrors.length)throw Error('Chưa xác nhận giá/thuế để phát hành');sheets[0].rows.push(['Căn cứ giá/thuế',result.tax.releaseErrors.length?'CHƯA XÁC NHẬN — chỉ thử tính':'Đã khai căn cứ; đơn giá và thành tiền hàng là trước thuế']);if(internal){const rows=[['NỘI BỘ — đối chiếu cùng mặt bằng trước thuế',...result.comparisonIds.map(id=>result.alternatives[id].name)]];for(const [label,key]of [['Giá trước thuế','net'],['Giá / kg phôi','perKg'],['Chênh so tính toán (đ)','deltaDetail'],['Chênh so tính toán (%)','deltaDetailPercent'],['Chênh so đối thủ (đ)','deltaCompetitor'],['Chênh so đối thủ (%)','deltaCompetitorPercent'],['Chênh so thị trường (đ)','deltaMarket'],['Chênh so thị trường (%)','deltaMarketPercent'],['Phần còn lại — không phải lợi nhuận ròng','residual']])rows.push([label,...result.comparisonIds.map(id=>result.tax.methods[id][key]??'N/A')]);rows.push(['Tập tham khảo: giá gốc chi tiết + xử lý',result.tax.reference??'N/A'],['Căn cứ',db.quote.pricing.taxReview?.reason||'Chưa khai'],['Thời điểm khai',db.quote.pricing.taxReview?.at||''],['Mẫu số tỷ lệ','Tổng trước thuế của PA được so với; bằng 0 → N/A'],['Thị trường độc lập trước thuế',result.tax.market??'N/A']);for(const [id,m]of result.comparisonIds.map(id=>[id,result.tax.methods[id]])){rows.push([id,m.reasons.join('; ')]);for(const i of m.inputs)rows.push([i.name,id,i.original,i.status,i.rate??'',i.net??'N/A']);}sheets.push({name:'Mat bang gia thue',widths:[48,26,26,26,26,26],rows});}return sheets;};
 document.addEventListener('click',e=>{if(e.target.closest('[data-tax="edit"]'))try{taxEdit();}catch(err){toast(err.message);}});
}
