/* Optional local server mode. Never stores passwords, session tokens or remote documents in localStorage. */
'use strict';
const Team={available:false,configured:false,user:null,permissions:null,csrf:'',link:null,loaded:false,local:null,dirty:false};
const teamButton=(label,action,attrs='',style='')=>`<button type="button" class="button ${style}" data-team="${action}" ${attrs}>${label}</button>`;
async function teamApi(route,method='GET',data){const response=await fetch('/api/'+route,{method,credentials:'same-origin',headers:{...(data!==undefined?{'Content-Type':'application/json'}:{}),...(method!=='GET'?{'X-CSRF-Token':Team.csrf}:{})},body:data===undefined?undefined:JSON.stringify(data)});const value=window.TPFormulaAccess?TPFormulaAccess.unwrap(await response.json()):await response.json();if(!response.ok){const error=Error(value.error||'Không kết nối được máy chủ');error.status=response.status;throw error;}return value;}
function teamDialog(title,body,label,handler){openDialog(title,body,label,f=>{const submit=$('#dialog button[type=submit]');submit.disabled=true;Promise.resolve().then(()=>handler(f)).catch(e=>{if($('#dialog').open){$('#dialog-error').hidden=false;$('#dialog-error').textContent=e.message;}else toast(e.message);}).finally(()=>{if(submit.isConnected)submit.disabled=false;});});}
function teamSession(value){Team.sessionGeneration=(Team.sessionGeneration||0)+1;Object.assign(Team,value);const button=$('#team-entry');if(button)button.textContent=Team.user?Team.user.name+' · Máy chủ':'Đăng nhập dùng chung';}
function teamLogin(){teamDialog(Team.configured?'Đăng nhập dùng chung':'Khởi tạo quản trị dùng chung',`<p>${Team.mode==='https-proxy'?'Máy chủ dùng chung qua kết nối HTTPS.':'Máy chủ dùng thử chạy tại máy này.'} Tài khoản đầu tiên là quản trị; không có mật khẩu mặc định.</p>${!Team.configured&&Team.setupKeyRequired?field('Mã khởi tạo do người vận hành cấp','setupKey','','password','required autocomplete="off"'):''}${field('Tài khoản không dấu','username','','text','required autocomplete="username" minlength="3" maxlength="64"')}${!Team.configured?field('Họ tên','name','','text','required'):''}${field('Mật khẩu'+(!Team.configured?' (ít nhất 12 ký tự)':''),'password','','password',`required autocomplete="${Team.configured?'current-password':'new-password'}" ${Team.configured?'':'minlength="12"'}`)}`,Team.configured?'Đăng nhập':'Tạo quản trị',async f=>{const value=await teamApi(Team.configured?'login':'setup','POST',Object.fromEntries(f));Team.configured=true;teamSession(value);closeDialog();render();if(!$('[data-home-results]'))await teamList();});}
async function teamList(){if(!Team.user)return teamLogin();const list=await teamApi('quotes');
  openDialog('Báo giá dùng chung trên máy chủ',`<div class="actions">${Team.permissions.edit?teamButton('Đưa bản đang mở lên máy chủ','save','','primary'):''}${Team.permissions.costs?accessButton('Danh mục dùng chung','catalog'):''}${Team.permissions.manage?accessButton('+ Báo giá mới','new-document'):''}${Team.permissions.users?teamButton('Quản lý tài khoản','users')+teamButton('Sao lưu dữ liệu','backup'):''}${teamButton('Đổi mật khẩu','own-password')}${teamButton('Đăng xuất','logout')}</div><p class="help-text">${esc(Team.user.name)} · ${esc([Team.permissions.costs?'Xem nội bộ':'Chỉ giá bán đã duyệt',Team.permissions.edit?'Được lập/sửa':'Không sửa',Team.permissions.approve?'Được duyệt':'Không duyệt'].join(' · '))}. Bản đã trình hoặc duyệt được khóa; sửa tiếp phải tạo bản sửa có lý do.</p><div class="table-scroll"><table class="quotes-list"><thead><tr><th>Báo giá / khách hàng</th><th>Trạng thái</th><th class="right">Tổng sau thuế</th><th>Phiên bản</th><th>Người cập nhật</th><th></th></tr></thead><tbody>${list.map(q=>`<tr><td><strong>${esc(q.code)}</strong><small class="subtext">${esc(q.customer)}</small>${q.project?`<small class="subtext">${esc(q.project)}</small>`:''}</td><td>${esc({draft:'Nháp',submitted:'Chờ duyệt',approved:'Đã duyệt'}[q.status])}</td><td class="right mono">${money(q.total)}</td><td>${q.version}</td><td>${esc(q.actor)}</td><td>${teamButton('Mở','open',`data-id="${q.id}"`,'small')}${q.canDelete?teamButton('Xóa bản nháp','delete-draft',`data-id="${q.id}"`,'small danger-text'):''}</td></tr>`).join('')||'<tr><td colspan="6">Chưa có báo giá trên máy chủ. Người lập có thể đưa bản đang làm lên.</td></tr>'}</tbody></table></div><p class="help-text">Dữ liệu lưu chung; khi có người khác cập nhật, tải lại bản mới trước khi lưu để tránh ghi đè.</p>`);$('#dialog').classList.add('wide-dialog');}
async function teamDeleteDraft(id){
 if(Team.user?.role!=='admin')throw Error('Chỉ Admin được xóa bản nháp');
 if(teamCurrent()?.id===id&&Team.dirty)throw Error('Bản đang mở có thay đổi chưa lưu. Lưu lại trước khi xóa.');
 const q=await teamApi('quotes/'+id);
 if(q.status!=='draft')throw Error('Chỉ xóa báo giá nháp');
 const code=q.document.quote.id;
 teamDialog('Xóa bản nháp '+esc(code),`<p>Bản nháp <strong>${esc(code)}</strong> · ${esc(q.document.quote.customer||'')} sẽ được bỏ khỏi danh sách làm việc. Lịch sử vẫn được giữ trên máy chủ để đối chiếu.</p>${field('Nhập lại mã báo giá để xác nhận','confirmCode','','text','required autocomplete="off"')}`,'Xóa bản nháp',async f=>{
  await teamApi('quotes/'+id,'DELETE',{expectedVersion:q.version,confirmCode:f.get('confirmCode')});
  if(teamCurrent()?.id===id){Team.dirty=false;teamLeave();}else closeDialog();await teamList();toast('Đã xóa bản nháp '+code);
 });
}
function teamCurrent(){return Team.loaded&&Team.link?.workspaceKey===db.quote.workspaceKey?Team.link:null;}
async function teamLoad(id,revision){if(Team.loaded&&Team.dirty){openDialog('Bản đang mở chưa lưu lên máy chủ',`<p>Lưu lại hoặc sao lưu bản đang làm trước khi chuyển báo giá.</p>`);return;}
  const record=await teamApi('quotes/'+id+(revision?'/revision/'+revision:''));if(!Team.loaded){quoteCheckpoint();Team.local=C.copy(db);}Team.loaded=true;Team.dirty=false;Team.catalogVersion=null;
  Team.quoteTechnicalBaseline=Team.permissions?.technical?{id,document:C.copy(record.document)}:null;
  const key='server-'+id+(revision?'-v'+revision:'');db={...db,...record.document,savedQuotes:[],history:[]};db.quote.workspaceKey=key;Team.link={id,version:record.version,status:record.status,workspaceKey:key,readOnly:!!revision};selected=db.quote.products[0]?.id;page='quote';tab=Team.permissions?.technical?'bom':'pricing';UX.undo=[];UX.redo=[];UX.checked.clear();closeDialog();render();$('#save-status').textContent='Máy chủ · phiên bản '+record.version;
}
function teamDocument(){return {version:2,...(db.__accessRef?{__accessRef:db.__accessRef}:{}),pricingDefaults:db.__accessRef||db.pricingDefaults?.__accessRef?C.copy(db.pricingDefaults||{}):TPInputPrices.defaults(db),shapeDefinitions:C.copy(db.shapeDefinitions||[]),stockSizes:C.copy(db.stockSizes||[]),catalogPriceBaseline:db.catalogPriceBaseline?C.copy(db.catalogPriceBaseline):null,conventions:C.copy(db.conventions||{}),materialPrices:C.copy(db.materialPrices||[]),materials:C.copy(db.materials),rates:C.copy(db.rates),rules:C.copy(db.rules),library:C.copy(db.library),quote:C.copy(db.quote)};}
async function teamSave(){if(!Team.user)return teamLogin();if(!Team.permissions.edit)throw Error('Tài khoản không có quyền lập/sửa');const link=teamCurrent();if(link&&(link.status!=='draft'||link.readOnly))throw Error('Bản này đang khóa. Tạo bản sửa trước.');
  if(!db.quote.pricing)throw Error('Chuyển sang luồng báo giá mới trước khi đưa lên máy chủ');
  const payload={document:teamDocument(),expectedVersion:link?.version},saved=await teamApi('quotes'+(link?'/'+link.id:''),link?'PUT':'POST',payload);
  if(Array.isArray(saved.draftMaterialIds)){const ids=new Set(saved.draftMaterialIds);for(const n of C.flatten(db.quote.products)){if(n.kind==='material'){if(ids.has(n.id))n.draftMaterial=true;else delete n.draftMaterial;}}}
  if(!Team.loaded){quoteCheckpoint();Team.local=C.copy(db);}Team.loaded=true;Team.dirty=false;Team.link={...saved,workspaceKey:db.quote.workspaceKey};closeDialog();render();$('#save-status').textContent='Đã lưu máy chủ · phiên bản '+saved.version;toast(result.errors?.length?'Đã lưu bản nháp lên máy chủ. Còn dữ liệu cần sửa; đồng nghiệp vẫn mở xem được.':'Đã lưu báo giá lên máy chủ; đồng nghiệp có thể mở bản vừa lưu');
}
function teamTransition(action){if(!Team.user)return teamLogin();const link=teamCurrent();if(!link)return toast('Lưu lên máy chủ trước');if(Team.dirty)return toast('Lưu các thay đổi trước khi trình hoặc duyệt');
  const label={submit:'Gửi duyệt báo giá',approve:'Duyệt báo giá',reopen:'Tạo bản sửa'}[action];teamDialog(label,`${action==='approve'&&result.warnings.length?`<div class="notice warning">${result.warnings.map(esc).join('<br>')}</div><label class="pa-checkbox"><input type="checkbox" name="acknowledge" required> Tôi xác nhận duyệt giá dưới gốc</label>`:''}${field('Ghi chú / lý do','reason','','text',action==='reopen'||action==='approve'&&result.warnings.length?'required':'')}<p class="help-text">Máy chủ kiểm tra phiên bản, quyền và dữ liệu trước khi ghi nhận. Phiên bản cũ vẫn giữ nguyên.</p>`,label,async f=>{const saved=await teamApi('quotes/'+link.id+'/'+action,'POST',{expectedVersion:link.version,reason:f.get('reason'),acknowledgeBelowCost:f.has('acknowledge')});Team.dirty=false;await teamLoad(saved.id);});}
async function teamHistory(){const link=teamCurrent();if(!link)return quoteHistory();const rows=await teamApi('quotes/'+link.id+'/revisions');openDialog('Lịch sử trên máy chủ',`<div class="actions">${clButton('Lịch sử gửi / khách chốt','workflow')}</div><p class="help-text">Mỗi lần lưu, trình, duyệt hoặc mở lại có người thực hiện và phiên bản riêng.</p><div class="table-scroll"><table><thead><tr><th>Phiên bản</th><th>Trạng thái</th><th>Người thực hiện</th><th>Thời gian / lý do</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.version}</td><td>${esc(r.status)}</td><td>${esc(r.actor)}</td><td>${esc(new Date(r.at).toLocaleString('vi-VN'))}<small class="subtext">${esc(r.reason)}</small></td><td>${teamButton('Xem','view-version',`data-id="${link.id}" data-version="${r.version}"`,'small')+(Team.permissions.reopen?teamButton('Tạo bản làm việc','restore-version',`data-id="${link.id}" data-version="${r.version}"`,'small'):'')}</td></tr>`).join('')}</tbody></table></div>`);$('#dialog').classList.add('wide-dialog');}
function teamLeave(){if(Team.dirty){openDialog('Bản đang mở chưa lưu',`<p>Lưu lên máy chủ hoặc dùng Sao lưu dữ liệu để giữ bản đang làm trước khi rời chế độ dùng chung.</p>`);return false;}if(Team.local){db=Team.local;Team.local=null;}Team.loaded=false;Team.link=null;selected=db.quote.products[0]?.id;page='quote';tab='bom';UX.undo=[];UX.redo=[];closeDialog();render();persist();return true;}
async function teamUsers(){const users=await teamApi('users');openDialog('Tài khoản dùng chung',`<div class="actions">${teamButton('+ Tạo tài khoản','new-user','','primary')}</div><p class="help-text">Lập giá: được sửa và trình. Người duyệt: chỉ xem và duyệt. Quản trị: quản lý tài khoản, lập và duyệt. Kỹ thuật: chỉ nhập BOM, không xem giá. Kinh doanh: chỉ xem bản chào đã duyệt. Các vai trò này đều xem được chi phí nội bộ trừ Kỹ thuật và Kinh doanh; ma trận quyền chi tiết cần thống nhất trước vận hành.</p><div class="table-scroll"><table><thead><tr><th>Tài khoản</th><th>Họ tên</th><th>Vai trò</th><th>Trạng thái</th><th></th></tr></thead><tbody>${users.map(u=>`<tr><td>${esc(u.username)}</td><td>${esc(u.name)}</td><td>${esc({technical:'Kỹ thuật',sales:'Kinh doanh',estimator:'Lập giá',approver:'Người duyệt',admin:'Quản trị'}[u.role]||u.role)}</td><td>${u.active?'Hoạt động':'Đã khóa'}</td><td>${u.id!==Team.user.id?(u.active?teamButton('Khóa','disable-user',`data-id="${u.id}"`,'small'):teamButton('Mở khóa','enable-user',`data-id="${u.id}"`,'small')):''}</td></tr>`).join('')}</tbody></table></div>`);$('#dialog').classList.add('wide-dialog');}
async function installTeamUI(){
  const oldRender=render,oldPersist=persist,oldMutation=mutation,oldApprove=actions.approve,oldHistory=actions.history;
  render=()=>{oldRender();document.body.classList.toggle('team-loaded',Team.loaded);if(Team.loaded){const link=teamCurrent(),locked=(page==='quote'||!Team.permissions?.catalog)&&(!Team.permissions?.edit||link?.status!=='draft'||link?.readOnly)||link?.readOnly;$('#content').insertAdjacentHTML('afterbegin',`<section class="team-banner"><div><strong>Máy chủ dùng chung · ${esc(Team.user?.name)}</strong><span>${link?'Phiên bản '+link.version+' · '+({draft:'Nháp',submitted:'Chờ duyệt',approved:'Đã duyệt'}[link.status]||''):'Chưa lưu'}${link?.readOnly?' · Chỉ xem phiên bản cũ':''}${Team.dirty?' · Có thay đổi chưa lưu':''}</span></div><div class="actions">${teamButton('Danh sách','list')}${Team.permissions?.edit&&!link?.readOnly&&link?.status==='draft'?teamButton('Lưu báo giá lên máy chủ','save')+teamButton('Gửi duyệt','submit','','primary'):''}${Team.permissions?.approve&&link?.status==='submitted'&&!link?.readOnly?teamButton('Duyệt','approve','','primary'):''}${Team.permissions?.reopen&&link?.status!=='draft'&&!link?.readOnly?teamButton('Tạo bản sửa','reopen'):''}${Team.user?.role==='admin'&&link?.status==='approved'&&!link?.readOnly?teamButton('Chuyển đơn hàng','order','','primary'):''}${teamButton('Về dữ liệu trên máy','leave')}</div>${locked?'<p>Bản đang khóa hoặc tài khoản chỉ có quyền xem/duyệt. Không chỉnh trực tiếp dữ liệu.</p>':''}</section>`);if(locked)$('#content').querySelectorAll('input,select,textarea').forEach(el=>el.disabled=true);}};
  persist=()=>{if(Team.loaded){$('#save-status').textContent=Team.dirty?'Chưa lưu lên máy chủ':'Đang xem dữ liệu máy chủ';return;}oldPersist();};
  mutation=(action,options={})=>{if(Team.loaded){const link=teamCurrent();if(!options.quoteMutation&&page!=='quote'&&Team.permissions?.catalog&&!link?.readOnly){options={...options,preserveQuote:true};}else{if(!Team.permissions?.edit||link?.status!=='draft'||link?.readOnly)return toast('Bản đang khóa hoặc tài khoản không có quyền sửa');Team.dirty=true;}}return oldMutation(action,options);};
  actions.approve=()=>Team.loaded?teamTransition(Team.permissions?.approve&&teamCurrent()?.status==='submitted'?'approve':'submit'):oldApprove();actions.history=()=>Team.loaded?teamHistory().catch(e=>toast(e.message)):oldHistory();
  window.addEventListener('beforeunload',e=>{if(Team.loaded&&Team.dirty){e.preventDefault();e.returnValue='';}});
  document.addEventListener('click',event=>{const el=event.target.closest('[data-team]');if(!el)return;event.preventDefault();const action=el.dataset.team;
    Promise.resolve().then(async()=>{
      if(action==='own-password'){if(Team.dirty)throw Error('Lưu thay đổi trước khi đổi mật khẩu');teamDialog('Đổi mật khẩu',field('Mật khẩu hiện tại','currentPassword','','password','required autocomplete="current-password"')+field('Mật khẩu mới','password','','password','required minlength="12" autocomplete="new-password"'),'Đổi mật khẩu',async f=>{await teamApi('me/password','POST',Object.fromEntries(f));teamLeave();teamSession({user:null,permissions:null,csrf:''});closeDialog();teamLogin();});}else if(action==='list')await teamList();else if(action==='login')Team.user?await teamList():teamLogin();else if(action==='open')await teamLoad(el.dataset.id);else if(action==='delete-draft')await teamDeleteDraft(el.dataset.id);else if(action==='save')await teamSave();else if(['submit','approve','reopen'].includes(action))teamTransition(action);else if(action==='leave')teamLeave();else if(action==='users')await teamUsers();else if(action==='view-version')await teamLoad(el.dataset.id,el.dataset.version);
      else if(action==='restore-version'){if(Team.dirty)throw Error('Lưu thay đổi hiện tại trước khi dùng phiên bản cũ');const current=await teamApi('quotes/'+el.dataset.id);teamDialog('Tạo bản làm việc từ phiên bản '+el.dataset.version,`<p>Giữ toàn bộ lịch sử, không ghi đè bản đã duyệt. Nội dung bản ${el.dataset.version} được sao thành một phiên bản nháp mới của báo giá; phải rà và duyệt lại.</p>${field('Lý do dùng lại','reason','','text','required')}`,'Tạo bản làm việc',async f=>{const saved=await teamApi('quotes/'+el.dataset.id+'/restore','POST',{sourceVersion:Number(el.dataset.version),expectedVersion:current.version,reason:f.get('reason')});await teamLoad(saved.id);});}
      else if(action==='logout'){if(!teamLeave())return;await teamApi('logout','POST',{});teamSession({user:null,permissions:null,csrf:''});toast('Đã đăng xuất; không lưu dữ liệu máy chủ vào bộ nhớ trình duyệt');}
      else if(action==='backup'){const data=await teamApi('backup');download('truongphat-server-backup.json',JSON.stringify(data,null,2),'application/json');}
      else if(action==='order'){const link=teamCurrent();if(!link||Team.dirty)throw Error('Lưu và duyệt phiên bản trước khi chuyển đơn hàng');teamDialog('Chuyển báo giá thành đơn hàng',`${field('Mã đơn hàng','code','DH-'+db.quote.id,'text','required')}<p>Tạo hồ sơ chuyển giao từ phiên bản đã duyệt: sản phẩm, cấu thành, công đoạn, dự toán và giá chốt. Không tạo trùng khi bấm lại. Sau khi tạo, kiểm tra và chốt đơn hàng trước khi phát hành lệnh sản xuất.</p>`,'Tạo hồ sơ đơn hàng',async f=>{const order=await teamApi('quotes/'+link.id+'/order','POST',{expectedVersion:link.version,code:f.get('code')});closeDialog();toast(order.existing?'Đơn hàng đã có, không tạo trùng.':'Đã tạo đơn hàng '+order.code);await ordersOpen(order.id);});}
      else if(action==='new-user')teamDialog('Tạo tài khoản',`${field('Tài khoản','username','','text','required minlength="3"')}${field('Họ tên','name','','text','required')}${select('Vai trò','role',[['technical','Kỹ thuật — không xem giá'],['sales','Kinh doanh'],['estimator','Lập báo giá'],['approver','Duyệt báo giá'],['admin','Quản trị']],'estimator')}${field('Mật khẩu ban đầu (12 ký tự trở lên)','password','','password','required minlength="12" autocomplete="new-password"')}`,'Tạo tài khoản',async f=>{await teamApi('users','POST',Object.fromEntries(f));await teamUsers();});
      else if(action==='disable-user')teamDialog('Khóa tài khoản?',`<p>Tài khoản này bị đăng xuất và không thể đăng nhập tiếp. Dữ liệu đã tạo vẫn giữ nguyên.</p>`,'Khóa',async()=>{await teamApi('users/'+el.dataset.id+'/disable','POST',{});await teamUsers();});
      else if(action==='enable-user'){await teamApi('users/'+el.dataset.id+'/enable','POST',{});await teamUsers();}
    }).catch(e=>toast(e.message));
  });
  if(!/^https?:$/.test(location.protocol))return;
  try{const status=await teamApi('status');Team.available=true;Team.configured=status.configured;Team.mode=status.mode;Team.requireLogin=!!status.requireLogin;render();Team.setupKeyRequired=status.setupKeyRequired;$('.top-actions').insertAdjacentHTML('afterbegin',teamButton('Đăng nhập dùng chung','login','id="team-entry"','small'));try{const generation=Team.sessionGeneration||0,current=await teamApi('me');if((Team.sessionGeneration||0)===generation){teamSession(current);render();}}catch{}}catch{}
}
