// Fast quotation workspace: progressive disclosure, keyboard editing and bulk actions.
const UX={mode:'quick',checked:new Set(),folded:new Set(),query:'',product:'',filters:{shape:'',grade:'',T:'',W:'',H:'',D:''},undo:[],redo:[],basket:new Map(),picker:null,onlyErrors:false};
const foldText=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase();
function initUX(){for(const p of C.flatten([...db.quote.products,...db.library]))if(p.kind==='product')C.configureProduct(p);try{UX.mode=localStorage.getItem('tp-entry-mode')||'quick';}catch{}}
function editableKeys(n){if(n.kind!=='material'||n.spec.shape==='piece')return [];const keys=[...C.shapeInfo(n.spec).input];for(const k of ['H','F','D'])if(!n.spec.props[k]&&new RegExp(`\\b${k}\\b`).test(n.ruleSpec.length+' '+n.ruleSpec.width)&&!keys.includes(k))keys.push(k);return keys;}
function nodeProblem(n){if(!(n.qty>0))return 'Số lượng phải lớn hơn 0';if(n.kind!=='material')return !n.children?.length?'Chưa có thành phần':'';try{C.geometry(n,result.nodes[n.id]?.count||1);}catch(e){return e.message;}const g=result.groups.find(g=>g.error&&g.rows.some(r=>r.id===n.id));return g?.error||'';}
function entrySwitcher(){return `<div class="entry-switcher"><div class="segmented" aria-label="Cách nhập liệu"><button class="${UX.mode==='quick'?'active':''}" data-ux="quick-mode">Bảng nhập nhanh</button><button class="${UX.mode==='detail'?'active':''}" data-ux="detail-mode">Cây chi tiết & 3D</button></div><div class="entry-tools">${btn('↶ Hoàn tác','ux-undo',`data-undo-button ${UX.undo.length?'':'disabled'}`)}${btn('↷','ux-redo',`data-redo-button aria-label="Làm lại" ${UX.redo.length?'':'disabled'}`)}</div></div>`;}
function quickInput(n,key,value,kind='dimension'){const binding=kind==='dimension'&&n.paramLinks?.[key],label=kind==='qty'?'Số lượng / cấp cha':key==='price'?'Đơn giá':key;return `<span class="quick-input ${binding?'linked':''}"><input aria-label="${esc(n.name)} / ${label}" type="number" min="${kind==='qty'?.001:key==='F'||key==='H'?0:1}" max="${kind==='qty'?5000:100000}" step="any" data-qid="${n.id}" data-qkey="${key}" data-qkind="${kind}" value="${esc(value)}" title="${binding?'Đồng bộ tham số '+binding+' của sản phẩm. Các dòng liên kết cùng tham số sẽ đổi theo.':'Nhập riêng cho dòng này'}">${binding?`<span title="Liên kết ${binding}">↔</span>`:''}</span>`;}
const productParamLabels={L:'Dài sản phẩm · PRODUCT_L',W:'Rộng sản phẩm · PRODUCT_W',H:'Cao sản phẩm · PRODUCT_H',T:'Dày sản phẩm · PRODUCT_T'};
function productParamAttrs(k){return 'min="'+(['H','T'].includes(k)?0:1)+'" max="100000" step="any"'+(k==='T'?' placeholder="Chưa khai"':' required');}
function productParamValue(f,k){return k==='T'&&f.get(k)===''?null:Number(f.get(k));}
function thicknessNote(p){const values=[...new Set(C.scopedLeaves(p).map(n=>n.spec?.props?.T).filter(v=>v>0))];return 'Dày chung không tự đổi mã/quy cách vật tư. Khối lượng và giá theo vật tư đang chọn.'+(p.params?.T!=null&&values.length?' Độ dày vật tư hiện tại: '+values.map(v=>num(v,3)+' mm').join(', ')+'.':'');}
function productParams(p){return `<div class="product-params"><span class="param-label">Kích thước sản phẩm <small>mm</small></span>${C.productParamEntries({params:{L:null,W:null,H:null,...p.params}}).map(([k,v])=>`<label><span>${esc(({L:"Dài SP",W:"Rộng SP",H:"Cao SP",T:"Dày SP"})[k]||k)}<code>PRODUCT_${esc(k)}</code></span><input type="number" ${productParamAttrs(k)} data-param-product="${p.id}" data-param-key="${esc(k)}" aria-label="${esc(p.name)} / PRODUCT_${esc(k)}" value="${esc(v??'')}"></label>`).join('')}<button type="button" class="button small" data-ux="configure-links" data-id="${p.id}">↔ Liên kết với vật tư</button><span class="param-link-note">Chỉ cập nhật các dòng đã liên kết</span><small class="thickness-note" data-thickness-note="${p.id}">${esc(thicknessNote(p))}</small><button type="button" class="button small quiet" data-thickness-scope="${esc(p.id)}">Đối chiếu Dày / chọn dòng áp dụng</button></div>`;}
function quickRow(n,depth,p){const problem=nodeProblem(n),leaf=n.kind==='material',keys=editableKeys(n),r=result.nodes[n.id],g=result.rows.find(r=>r.id===n.id)?.geometry,visible=UX.searchView.visible.has(n.id)&&(!UX.errorView||UX.errorView.has(n.id)),contextOnly=!!UX.query&&UX.searchView.context.has(n.id);
  const row=visible?`<tr class="quick-row ${leaf?'':'assembly-row'} ${problem?'has-problem':''} ${contextOnly?'search-context':''}" data-row-id="${n.id}"><td class="check-col"><input type="checkbox" aria-label="Chọn ${esc(n.name)}" data-check-id="${n.id}" ${contextOnly?'disabled title="Dòng giữ vị trí. Chọn các vật tư hiển thị bên dưới."':''} ${UX.checked.has(n.id)?'checked':''}></td><td class="identity-col"><div class="quick-identity" style="--indent:${Math.min(depth,3)*12}px"><span class="node-icon ${n.kind}">${leaf?'VT':n.kind==='product'?'SP':'CK'}</span><span><button class="text-button" data-ux="inspect" data-id="${n.id}" title="Mở chi tiết"><strong data-live-name="${n.id}">${esc(n.name)}</strong></button><small>${leaf?`<button class="code-link" data-action="swap-material" data-id="${n.id}" title="Đổi mã vật tư">${esc(n.materialId)} ↗</button><span>${esc(Object.entries(n.spec.props).map(([k,v])=>`${k} ${num(v)}`).join(' / '))}</span>`:`${n.children?.length||0} thành phần ${n.ops?.length?' / '+n.ops.length+' nguyên công':''}`}</small>${!leaf?`<button class="context-add" data-ux="add-to-node" data-id="${n.id}" aria-label="Thêm vật tư vào ${esc(n.name)}">+ Vật tư vào ${n.kind==='component'?'cấu kiện':'sản phẩm con'}</button>`:''}</span></div></td><td><div class="quantity-cell" title="${esc(quantityHint(n))}">${quickInput(n,'qty',n.qty,'qty')}<small data-qtotal="${n.id}">Tổng: ${num(r.count)}</small></div></td>${['L','W','H','F'].map(k=>`<td>${leaf&&keys.includes(k)?quickInput(n,k,n.dims[k]??0):leaf&&n.spec.props[k]?`<span class="fixed-value" title="Quy cách cố định từ danh mục">${num(n.spec.props[k])}<small>cố định</small></span>`:'<span class="cell-na">·</span>'}</td>`).join('')}<td class="calc-col" data-qgeometry="${n.id}">${problem?`<span class="cell-error" title="${esc(problem)}">Cần kiểm tra</span>`:leaf?(g?.length?`<strong>${num(g.length)}${g.width?' × '+num(g.width):''}</strong><small>mm / ${esc(n.ruleSpec.name)}</small>`:`<span class="muted">Theo ${esc(n.spec.unit)}</span>`):`<span class="muted">${num(r.weight)} kg</span>`}</td><td class="right mono" data-qcost="${n.id}">${money(r.material)}</td><td class="row-actions"><button class="row-more" data-ux="row-actions" data-id="${n.id}" aria-label="Thao tác ${esc(n.name)}">⋯</button></td></tr>`:'';
  return row+(n.children||[]).map(c=>quickRow(c,depth+1,p)).join('');
}
function errorStrip(){if(!result.errors.length)return '';return `<div class="quick-errors" role="status"><span><strong>${result.errors.length} nội dung cần kiểm tra.</strong> ${esc(result.errors[0])}</span><button class="text-button" data-ux="errors">${UX.onlyErrors?'Hiện tất cả':'Chỉ hiện dòng lỗi'}</button></div>`;}
function bulkBar(){return `<div class="bulk-bar ${UX.checked.size?'visible':''}" id="bulk-bar"><span><strong>${UX.checked.size}</strong> dòng đang chọn</span><button data-ux="bulk-op">Gán nguyên công</button><button data-ux="bulk-material">Đổi mã vật tư</button><button data-ux="bulk-copy">Nhân bản</button><button data-ux="bulk-delete">Xóa</button><button data-ux="clear-selection" aria-label="Bỏ chọn">×</button></div>`;}
function quickProduct(p){const folded=UX.folded.has(p.id)&&!UX.query&&!UX.onlyErrors;return `<section class="panel quick-product" data-product-panel="${p.id}"><div class="quick-product-head"><button class="fold-product" data-ux="fold" data-id="${p.id}" aria-label="${folded?'Mở':'Thu gọn'} sản phẩm" aria-expanded="${!folded}">${folded?'›':'⌄'}</button><span class="node-icon product">SP</span><div class="quick-product-title"><strong data-live-name="${p.id}">${esc(p.name)}</strong>${cvProductButton(p)}<span><b data-p-line-count="${p.id}">${C.flatten(p.children||[]).filter(n=>n.kind==='material').length}</b> dòng vật tư <span class="muted">/</span> <button class="text-button" data-ux="inspect" data-id="${p.id}">Chi tiết & nguyên công</button></span></div><label class="product-quantity"><span>Số lượng</span><input type="number" min="1" max="5000" step="1" data-qid="${p.id}" data-qkey="qty" data-qkind="qty" aria-label="Số lượng ${esc(p.name)}" value="${p.qty}"><small>${esc(p.unit||'bộ')}</small></label><div class="product-head-actions">${btn('3D','quick-3d',`data-id="${p.id}"`,'small')}${btn('Lưu mẫu','save-template',`data-id="${p.id}"`,'small')}<button class="row-more" data-ux="row-actions" data-id="${p.id}" aria-label="Thao tác sản phẩm">⋯</button></div></div>${productParams(p)}${folded?'':`<div class="table-swipe-hint">↔ Vuốt ngang bảng để nhập kích thước và xem chi phí</div><div class="quick-table-scroll"><table class="quick-table"><thead><tr><th class="check-col"><input type="checkbox" data-check-product="${p.id}" aria-label="Chọn các dòng hiển thị của ${esc(p.name)}"></th><th>Thành phần / mã vật tư</th><th title="Ô nhập: số lượng cho 1 đơn vị chứa dòng này. Số bên dưới: tổng toàn báo giá.">Định mức / tổng</th><th>Dài L</th><th>Rộng W</th><th>Cao H</th><th>Mép F</th><th>Khai triển / kiểm tra</th><th class="right">Giá vật tư (₫)</th><th></th></tr></thead><tbody>${(p.children||[]).map(n=>quickRow(n,0,p)).join('')}</tbody></table>${!p.children?.length?empty('Thêm vật tư để bắt đầu','Chọn nhiều mã cùng lúc hoặc dán trực tiếp các dòng từ Excel.'):''}</div><div class="quick-product-footer"><div>${btn('+ Vật tư vào sản phẩm','add-material',`data-parent="${p.id}"`)}${btn('+ Cấu kiện','add-component',`data-parent="${p.id}"`)}${btn('Gọi mẫu','pick-template',`data-parent="${p.id}"`)}${btn('Dán từ Excel','paste-excel',`data-parent="${p.id}"`)}</div><span>Giá chào / ${esc(p.unit||'bộ')} <strong class="mono" data-unit-sell="${p.id}">${result.errors.length?'Chưa đủ dữ liệu':money(result.products.find(r=>r.node.id===p.id)?.unitSell)+' ₫'}</strong></span></div>`}</section>`;}
function renderQuickBOM(){prepareSearchView();const products=db.quote.products.filter(p=>(!UX.product||p.id===UX.product)&&UX.searchView.visible.has(p.id)&&(!UX.errorView||UX.errorView.has(p.id)));return `<div class="quick-toolbar"><div><h2>Lập cấu thành, ngay trên một bảng</h2><p>Nút ƒ khai công thức kích thước theo sản phẩm/cấp cha. Ô ↔ là liên kết bằng nhau. Ctrl+Z hoàn tác.</p></div><div class="actions">${btn('Tạo biến thể','variant',`data-id="${UX.product||db.quote.products[0]?.id||''}"`)}${btn('+ Sản phẩm','add-product','','primary')}</div></div><div class="quick-filter"><div class="searchbox"><span>⌕</span><input id="quick-search" aria-label="Tìm trong cấu thành" placeholder="Tìm mã vật tư hoặc cấu kiện…" value="${esc(UX.query)}"></div><select aria-label="Lọc sản phẩm" id="quick-product-filter"><option value="">Tất cả sản phẩm (${db.quote.products.length})</option>${db.quote.products.map(p=>`<option value="${p.id}" ${UX.product===p.id?'selected':''}>${esc(p.name)}</option>`).join('')}</select><span class="entry-autosave">Tự lưu trên máy sau khi nhập</span></div>${UX.query?`<div class="search-status" role="status"><span>${UX.searchView.matched.size} dòng khớp · giữ sản phẩm, cấu kiện và vật tư liên quan</span><button class="text-button" data-ux="clear-search">Xóa tìm kiếm</button></div>`:''}<div id="quick-errors">${errorStrip()}</div>${bulkBar()}<div class="quick-products">${products.map(quickProduct).join('')||(UX.query||UX.onlyErrors?empty('Không có dòng phù hợp','Đổi từ khóa hoặc bỏ bộ lọc để xem lại cấu thành.','<button class="button" data-ux="clear-search">Xóa tìm kiếm & bộ lọc lỗi</button>'):empty('Bắt đầu bằng một sản phẩm','Gọi sản phẩm mẫu để kế thừa cấu kiện, công thức và đơn giá.',btn('+ Sản phẩm','add-product','','primary')))}</div><div class="quick-bottom"><span>${result.rows.length} dòng vật tư / ${db.quote.products.length} sản phẩm</span><span>Tổng chào sau thuế <strong data-quick-grand>${result.errors.length?'Chưa đủ dữ liệu':money(result.total.grand)+' ₫'}</strong></span>${btn('Xem hao hụt →','quick-waste','','primary')}</div>`;}
function refreshQuickUI(){result=C.calculate(db);for(const input of document.querySelectorAll('[data-qid]')){const n=C.findNode(db.quote.products,input.dataset.qid);if(n)input.value=input.dataset.qkind==='qty'?n.qty:n.dims[input.dataset.qkey];}for(const input of document.querySelectorAll('[data-param-product]'))input.value=C.findNode(db.quote.products,input.dataset.paramProduct)?.params?.[input.dataset.paramKey]??'';
  for(const el of document.querySelectorAll('[data-thickness-note]')){const p=C.findNode(db.quote.products,el.dataset.thicknessNote);if(p)el.textContent=thicknessNote(p);}
  for(const el of document.querySelectorAll('[data-live-name]')){const n=C.findNode(db.quote.products,el.dataset.liveName);if(n)el.textContent=n.name;}
  for(const el of document.querySelectorAll('[data-qcost]'))el.textContent=C.findNode(db.quote.products,el.dataset.qcost)?.draftMaterial?'Chưa có giá':money(result.nodes[el.dataset.qcost]?.material);
  for(const el of document.querySelectorAll('[data-qtotal]')){const n=C.findNode(db.quote.products,el.dataset.qtotal);if(n){el.textContent='Tổng: '+num(result.nodes[n.id].count);el.parentElement.title=quantityHint(n);}}
  for(const el of document.querySelectorAll('[data-qgeometry]')){const n=C.findNode(db.quote.products,el.dataset.qgeometry),problem=nodeProblem(n),g=result.rows.find(r=>r.id===n.id)?.geometry;el.closest('tr').classList.toggle('has-problem',!!problem);el.innerHTML=problem?`<span class="cell-error" title="${esc(problem)}">Cần kiểm tra</span>`:n.kind!=='material'?`<span class="muted">${num(result.nodes[n.id].weight)} kg</span>`:g?.length?`<strong>${num(g.length)}${g.width?' × '+num(g.width):''}</strong><small>mm / ${esc(n.ruleSpec.name)}</small>`:`<span class="muted">Theo ${esc(n.spec.unit)}</span>`;}
  for(const el of document.querySelectorAll('[data-unit-sell]'))el.textContent=result.errors.length?'Chưa đủ dữ liệu':money(result.products.find(p=>p.node.id===el.dataset.unitSell)?.unitSell)+' ₫';
  if($('#quick-errors'))$('#quick-errors').innerHTML=errorStrip();
  const metrics=$('.quote-metrics');if(metrics){const values=[null,[result.total.cost,'VNĐ'],[result.total.profit,db.quote.pricing?'Chưa phải lợi nhuận ròng':'Biên '+num(db.quote.margin)+'%'],[result.total.grand,'VNĐ']];values.forEach((v,i)=>{if(v)metrics.children[i].querySelector('strong').innerHTML=(i===3&&db.quote.pricing&&result.errors.length?'Cần rà lại':money(v[0]))+`<small>${v[1]}</small>`;});metrics.children[2].querySelector('strong').className=result.total.profit<0?'pa-negative':'positive';}
  document.querySelectorAll('[data-quick-grand]').forEach(el=>el.textContent=result.errors.length?'Chưa đủ dữ liệu':money(result.total.grand)+' ₫');const badge=$('.quote-ribbon .badge');if(badge){badge.className='badge';badge.textContent='Bản nháp';}refreshHistoryButtons();
}
function refreshHistoryButtons(){document.querySelectorAll('[data-undo-button]').forEach(b=>b.disabled=!UX.undo.length);document.querySelectorAll('[data-redo-button]').forEach(b=>b.disabled=!UX.redo.length);}
function undoUX(redo=false){const from=redo?UX.redo:UX.undo,to=redo?UX.undo:UX.redo;if(!from.length)return;to.push(C.copy(db));db=from.pop();UX.checked.clear();if(!C.findNode(db.quote.products,selected))selected=db.quote.products[0]?.id;persist();render();toast(redo?'Đã làm lại thay đổi':'Đã hoàn tác thay đổi');}
function commitQuick(el){const optionalT=el.dataset.paramProduct&&el.dataset.paramKey==='T',value=optionalT&&el.value===''?null:Number(el.value);el.setCustomValidity(optionalT&&value===0?'Dày T phải lớn hơn 0; để trống nếu chưa khai.':'');if((!optionalT&&el.value==='')||!el.checkValidity()){el.reportValidity();el.classList.add('invalid-input');return false;}el.classList.remove('invalid-input');if(el.dataset.paramProduct){const p=C.findNode(db.quote.products,el.dataset.paramProduct);if((p.params?.[el.dataset.paramKey]??null)===value)return true;mutation(()=>C.applyParam(p,el.dataset.paramKey,value),{soft:true});return true;}const n=C.findNode(db.quote.products,el.dataset.qid);if(!n)return false;const key=el.dataset.qkey;if((el.dataset.qkind==='qty'?n.qty:n.dims[key])===value)return true;mutation(()=>{if(el.dataset.qkind==='qty')n.qty=value;else C.setDimension(db,n.id,key,value);},{soft:true});return true;}
function selectedTopNodes(){const nodes=C.flatten(db.quote.products);return nodes.filter(n=>UX.checked.has(n.id)&&!(C.nodePath(db.quote.products,n.id)||[]).slice(0,-1).some(p=>UX.checked.has(p.id)));}
function updateBulk(){const old=$('#bulk-bar');if(old)old.outerHTML=bulkBar();document.querySelectorAll('[data-check-id]').forEach(el=>el.checked=UX.checked.has(el.dataset.checkId));document.querySelectorAll('[data-check-product]').forEach(el=>{const boxes=[...el.closest('.quick-product').querySelectorAll('[data-check-id]:not(:disabled)')],chosen=boxes.filter(b=>b.checked).length;el.checked=boxes.length>0&&chosen===boxes.length;el.indeterminate=chosen>0&&chosen<boxes.length;});}
function batchMaterialPicker(parentId,keep=false){const parent=C.findNode(db.quote.products,parentId);if(!parent)return;if(!keep){UX.basket=new Map();UX.picker={parentId,query:'',group:''};}const context=UX.picker;context.parentId=parentId;
  openDialog('Thêm vật tư vào '+esc(parent.name),`${pickerTarget(parent)}<div class="batch-picker-top"><div class="searchbox"><span>⌕</span><input id="pick-search" aria-label="Tìm mã vật tư" placeholder="Gõ mã hoặc tên vật tư, không cần dấu…" value="${esc(context.query)}" autocomplete="off"></div><select id="pick-group" aria-label="Lọc nhóm vật tư"><option value="">Tất cả nhóm</option>${[...new Set([...C.groups,...db.materials.map(m=>m.group)])].map(g=>`<option value="${esc(g)}" ${context.group===g?'selected':''}>${esc(g)}</option>`).join('')}</select></div><div class="batch-columns"><span>Chọn các mã cần dùng</span><span>SL / 1 ${parent.kind==='component'?'cấu kiện':'sản phẩm'}</span></div><div id="pick-results" class="batch-results"></div><div class="batch-footer"><span id="basket-summary">Chưa chọn vật tư</span><button class="text-button" type="button" data-ux="create-in-picker">+ Tạo mã vật tư mới</button></div><div class="picker-preview" id="pick-spec">Mỗi mã giữ nguyên vật liệu, hình dạng và kích thước cố định. Kích thước thực tế nhập ngay trên bảng sau khi thêm.</div>`,'Thêm vật tư đã chọn',()=>{
    if(!UX.basket.size)throw Error('Chọn ít nhất một mã vật tư');const chosen=[...UX.basket].map(([id,qty])=>{const m=db.materials.find(m=>m.id===id);if(!m||!Number.isFinite(qty)||qty<=0||qty>5000)throw Error('Kiểm tra số lượng của mã '+id);return createMaterialNode(m,qty);});saveAndClose(()=>{parent.children.push(...chosen);selected=parent.id;UX.query='';UX.onlyErrors=false;},'Đã thêm '+chosen.length+' dòng vật tư. Nhập tiếp kích thước ngay trên bảng.');focusQuickNode(chosen[0].id);
  });$('#dialog').classList.add('wide-dialog');const search=$('#pick-search');$('#picker-target').onchange=e=>batchMaterialPicker(e.target.value,true);search.oninput=()=>{context.query=search.value;drawBatchPicker();};$('#pick-group').onchange=e=>{context.group=e.target.value;drawBatchPicker();};drawBatchPicker();search.focus();}
function createMaterialNode(m,qty=1,dims={}){if(m.shapeDefinition)return TPDefinitions.assign({...TPDefinitions.draft(m.name,qty),dims},m,db.rules);return {id:C.uid(),kind:'material',materialId:m.id,name:m.name,qty,spec:C.copy(m),dims:{L:1000,W:300,H:50,F:15,...dims},rule:m.shape==='sheet'?'flat':'bar',ruleSpec:C.copy(db.rules.find(r=>r.id===(m.shape==='sheet'?'flat':'bar'))),ops:[]};}
function drawBatchPicker(){const context=UX.picker,list=db.materials.filter(m=>(!context.group||m.group===context.group)&&(!context.substance||m.substance===context.substance)&&foldText(m.id+' '+m.name+' '+specText(m)).includes(foldText(context.query)));$('#pick-results').innerHTML=list.map(m=>`<div class="batch-option ${UX.basket.has(m.id)?'selected':''}" data-basket-row="${esc(m.id)}"><label><input type="checkbox" data-basket-id="${esc(m.id)}" ${UX.basket.has(m.id)?'checked':''}><span><b class="mono">${esc(m.id)}</b><strong>${esc(m.name)}</strong><small>${esc(specText(m))} / ${money(m.price)} ₫/${esc(m.unit)}</small></span></label><input type="number" aria-label="Số lượng ${esc(m.id)}" data-basket-qty="${esc(m.id)}" min="0.001" max="5000" step="any" value="${UX.basket.get(m.id)||1}"></div>`).join('')||empty('Không tìm thấy mã phù hợp','Thử từ khóa khác hoặc tạo mã vật tư mới.');refreshBasket();}
function refreshBasket(){if(!$('#basket-summary'))return;$('#basket-summary').textContent=UX.basket.size?'Đã chọn '+UX.basket.size+' mã vật tư':'Chọn nhiều mã rồi thêm một lần';$('#dialog button[type=submit]').textContent=UX.basket.size?'Thêm '+UX.basket.size+' mã vật tư':'Thêm vật tư đã chọn';document.querySelectorAll('[data-basket-row]').forEach(row=>{const id=row.dataset.basketRow;row.classList.toggle('selected',UX.basket.has(id));row.querySelector('[data-basket-id]').checked=UX.basket.has(id);});}
function parseExcel(text,format='auto',parentId=selected){const parent=C.findNode(db.quote.products,parentId),parentCount=parent?result.nodes[parent.id]?.count||1:1;return TPEntry.readPaste(text,db.materials,db.rules,{format,parentCount}).map(row=>{const n=createMaterialNode(row.material,row.qty,row.dims);n.importLine=row.line;return n;});}
function pasteExcel(parentId){
  const parent=C.findNode(db.quote.products,parentId);if(!parent)return;
  openDialog('Dán vật tư từ Excel',`<div class="import-destination"><span>Thêm vào ${parent.kind==='component'?'cấu kiện':'sản phẩm'}</span><strong>${esc(parent.name)}</strong></div><p>Sao chép các ô theo thứ tự dưới đây. Xem lại kích thước trước khi thêm, đơn vị mm.</p><div class="paste-columns"><span>Mã vật tư</span><span>Số lượng</span><span>Dài L</span><span>Rộng W</span><span>Cao H</span><span>Mép F</span></div><div class="paste-format-row">${select('Cách viết số','numberFormat',[['auto','Tự nhận biết · hỏi lại số mơ hồ'],['vi','Việt Nam: 1.800,5 = 1800,5'],['en','Quốc tế: 1,800.5 = 1800,5']],'auto')}<p>Với <b>1.800</b>, chọn Việt Nam nếu muốn 1800 mm; chọn Quốc tế nếu muốn 1,8 mm.</p></div><label class="field"><span>Có thể bỏ trống kích thước không áp dụng. Vật tư theo cái/bộ chỉ cần mã và số lượng.</span><textarea id="excel-paste" aria-label="Dữ liệu từ Excel" rows="5" spellcheck="false" placeholder="PH-T15&#9;2&#9;1800&#9;400&#10;LK-M8&#9;8"></textarea></label><div id="paste-preview" class="paste-preview" aria-live="polite"></div>`,'Kiểm tra & thêm tất cả dòng',()=>{
    const nodes=parseExcel($('#excel-paste').value,$('[name=numberFormat]').value,parentId);
    if(!nodes.length)throw Error('Dán ít nhất một dòng dữ liệu');
    saveAndClose(()=>{parent.children.push(...nodes);selected=parent.id;UX.query='';UX.onlyErrors=false;},'Đã thêm '+nodes.length+' dòng vào '+parent.name);focusQuickNode(nodes[0].id);
  });
  $('#dialog').classList.add('wide-dialog');
  const preview=()=>{const target=$('#paste-preview');$('#dialog-error').hidden=true;try{
    const nodes=parseExcel($('#excel-paste').value,$('[name=numberFormat]').value,parentId);target.className='paste-preview';
    target.innerHTML=nodes.length?`<div class="paste-preview-title"><strong>${nodes.length} dòng đã kiểm tra</strong><span>Chưa thêm vào báo giá</span></div><div class="table-scroll"><table class="paste-preview-table"><thead><tr><th>Mã vật tư</th><th>SL / 1 đơn vị chứa</th><th>Dài L</th><th>Rộng W</th><th>Cao H</th><th>Mép F</th><th>Tổng số lượng</th></tr></thead><tbody>${nodes.slice(0,50).map(n=>`<tr><td class="mono">${esc(n.materialId)}</td><td>${num(n.qty)}</td>${['L','W','H','F'].map(k=>`<td>${n.spec.shape==='piece'?'—':n.spec.props[k]?`${num(n.spec.props[k])}<small>cố định</small>`:C.shapeInfo(n.spec).input.includes(k)?num(n.dims[k]):'—'}</td>`).join('')}<td>${num(n.qty*(result.nodes[parentId]?.count||1))} ${esc(n.spec.shape==='piece'?n.spec.unit:'phôi')}</td></tr>`).join('')}</tbody></table></div>${nodes.length>50?'<p>Hiển thị 50 dòng đầu; toàn bộ '+nodes.length+' dòng đều được kiểm tra.</p>':''}<p>Dòng tấm dùng quy tắc Tấm phẳng; có thể đổi công thức tại Chi tiết. Các cột hiện dấu — không tham gia tính với quy tắc này.</p>`:'Dán dữ liệu để xem trước mã, số lượng và kích thước được đọc.';
    $('#dialog button[type=submit]').textContent=nodes.length?'Thêm '+nodes.length+' dòng đã kiểm tra':'Kiểm tra & thêm tất cả dòng';
  }catch(e){target.className='paste-preview error';target.textContent=e.message;$('#dialog button[type=submit]').textContent='Kiểm tra lại dữ liệu';}};
  $('#excel-paste').oninput=preview;$('[name=numberFormat]').onchange=preview;preview();$('#excel-paste').focus();
}
function variantProduct(id){const p=db.quote.products.find(p=>p.id===id)||db.quote.products[0];if(!p)return addProduct();openDialog('Tạo biến thể từ sản phẩm có sẵn',`${select('Sản phẩm nguồn','source',db.quote.products.map(p=>[p.id,p.name]),p.id)}<div id="variant-fields"></div><div class="notice">Tạo sản phẩm mới từ bản sao cấu thành. Đổi kích thước chung sẽ cập nhật các ô liên kết và tên sản phẩm. Dày chung không tự đổi mã/quy cách vật tư.</div>`,'Tạo biến thể',f=>{const source=C.findNode(db.quote.products,f.get('source')),n=C.cloneNode(source);n.qty=Number(f.get('qty'));if(n.params)for(const [k]of C.productParamEntries(n))C.applyParam(n,k,productParamValue(f,k));else n.name=f.get('name').trim()||n.name+' (biến thể)';saveAndClose(()=>{db.quote.products.push(n);selected=n.id;UX.product='';},'Đã tạo biến thể độc lập với sản phẩm gốc');});const fields=()=>{const p=C.findNode(db.quote.products,$('[name=source]').value);$('#variant-fields').innerHTML=`<div class="form-grid">${field('Số lượng sản phẩm mới','qty',1,'number','min="1" max="5000" required')}${p.params?C.productParamEntries(p).map(([k,v])=>field((productParamLabels[k]||k)+' (mm)',k,v??'','number',productParamAttrs(k))).join(''):field('Tên sản phẩm mới','name',p.name+' (biến thể)','text','required')}</div>`;};$('[name=source]').onchange=fields;fields();}
function bulkOperation(){const nodes=selectedTopNodes();if(!nodes.length)return;openDialog('Gán nguyên công cho '+nodes.length+' dòng',`${select('Nguyên công','op',db.quote.ratesSnapshot.map(r=>[r.id,r.name]),db.quote.ratesSnapshot[0]?.id)}${select('Phương án','mode',[['inside','Tại xưởng'],['outside','Thuê ngoài']],'inside')}${field('Định mức / 1 đơn vị (với m, lần, bộ)','amount',1,'number','min="0" step="any" required')}<div class="notice">Chỉ áp dụng ở cấp được chọn cao nhất, không gán thêm vào cấp con để tránh tính hai lần. Nguyên công đã có sẽ được cập nhật.</div>`,'Áp dụng cho các dòng',f=>saveAndClose(()=>{for(const n of nodes){const op={id:f.get('op'),mode:f.get('mode'),amount:Number(f.get('amount'))},existing=n.ops.find(x=>x.id===op.id);if(existing)Object.assign(existing,op);else n.ops.push(op);}UX.checked.clear();},'Đã gán nguyên công cho '+nodes.length+' dòng'));}
function replaceMaterials(nodes){const materials=nodes.filter(n=>n.kind==='material');if(!materials.length)return toast('Chọn ít nhất một dòng vật tư');openDialog('Đổi mã cho '+materials.length+' dòng vật tư',`${select('Mã vật tư thay thế','material',db.materials.map(m=>[m.id,m.id+' / '+m.name]),materials[0].materialId)}<div class="notice">Giữ số lượng và kích thước thực tế khi hình dạng tương thích. Quy cách cố định và giá lấy từ mã mới.</div>`,'Đổi mã vật tư',f=>{const m=db.materials.find(m=>m.id===f.get('material'));if(materials.some(n=>n.spec.shape!==m.shape))throw Error('Đổi hàng loạt yêu cầu cùng hình dạng. Hãy chọn mã '+C.shapes[materials[0].spec.shape].name+'.');saveAndClose(()=>{for(const n of materials){n.materialId=m.id;n.name=m.name;n.spec=C.copy(m);}UX.checked.clear();},'Đã đổi mã, giữ kích thước và nguyên công');});}
function nodeActions(id){const n=C.findNode(db.quote.products,id);if(!n)return;const linked=Object.keys(n.paramLinks||{}).length;openDialog('Thao tác với '+esc(n.name),`<div class="row-action-menu"><button type="button" data-ux="inspect" data-id="${n.id}">Mở chi tiết & nguyên công <span>↗</span></button><button type="button" data-ux="copy-one" data-id="${n.id}">Nhân bản dòng này <span>＋</span></button>${n.kind==='material'?`<button type="button" data-ux="replace-one" data-id="${n.id}">Đổi mã, giữ kích thước <span>↔</span></button>${linked?`<button type="button" data-ux="detach" data-id="${n.id}">Sửa riêng kích thước dòng này <small>Tách ${linked} liên kết với sản phẩm</small></button>`:''}`:`<button type="button" data-ux="add-to-node" data-id="${n.id}">Thêm nhiều mã vật tư <span>＋</span></button>`}${n.kind==='product'?`<button type="button" data-ux="configure-links" data-id="${n.id}">Kích thước chung & liên kết <span>↔</span></button>`:''}<button type="button" class="danger-text" data-ux="delete-one" data-id="${n.id}">Xóa khỏi báo giá <span>×</span></button></div>`);}
function refreshPriceUI(){result=C.calculate(db);const note=$('.remnant-price-note');if(note)note.outerHTML=remnantCostNote();document.querySelectorAll('[data-quote-price]').forEach(el=>{el.value=C.findNode(db.quote.products,el.dataset.quotePrice).spec.price;});for(const el of document.querySelectorAll('[data-price-node]')){const r=result.nodes[el.dataset.priceNode];if(r)el.textContent=money(r[el.dataset.pricePart]||0);}for(const el of document.querySelectorAll('[data-price-sell]'))el.textContent=money(result.products.find(p=>p.node.id===el.dataset.priceSell)?.sell);for(const el of document.querySelectorAll('[data-total-key]'))el.textContent=money(result.total[el.dataset.totalKey])+' ₫';refreshQuickUI();}
function priceRow(n,depth){const r=result.nodes[n.id];return `<tr class="${n.kind==='material'?'':'assembly-price'}"><td><div class="price-identity" style="padding-left:${depth*12}px"><span class="node-icon ${n.kind}">${n.kind==='material'?'VT':n.kind==='product'?'SP':'CK'}</span><span><strong>${esc(n.kind==='material'?n.materialId:n.name)}</strong><small>${n.kind==='material'?esc(n.name):'Chi phí khai báo riêng ở cấp này'} / SL toàn báo giá: ${num(r.count)}</small></span></div></td><td class="right">${n.kind==='material'?`<label class="price-unit-input"><input aria-label="Giá ${esc(n.materialId)} tại báo giá" data-quote-price="${n.id}" type="number" min="0" step="1" value="${n.spec.price}"><span>₫/${esc(n.spec.unit)}</span></label><strong class="price-line-total" data-price-node="${n.id}" data-price-part="material">${money(r.material)}</strong>`:'<span class="cell-na">Từ vật tư bên dưới</span>'}</td><td><button class="op-cell" data-ux="price-ops" data-id="${n.id}"><strong>${money(r.ownOps.reduce((s,o)=>s+o.cost,0))} ₫</strong><small>${n.ops.length?n.ops.length+' nguyên công / chỉnh sửa':'+ Gán nguyên công'}</small></button></td><td><label class="price-unit-input"><input aria-label="Vận chuyển ${esc(n.name)}" type="number" min="0" step="1" data-node-cost="transport" data-id="${n.id}" value="${n.transport||0}"><span>₫/đv cấp này</span></label><strong class="price-line-total" data-price-node="${n.id}" data-price-part="ownTransport">${money(r.ownTransport)}</strong></td><td><label class="price-unit-input"><input aria-label="Lắp đặt ${esc(n.name)}" type="number" min="0" step="1" data-node-cost="install" data-id="${n.id}" value="${n.install||0}"><span>₫/đv cấp này</span></label><strong class="price-line-total" data-price-node="${n.id}" data-price-part="ownInstall">${money(r.ownInstall)}</strong></td></tr>${(n.children||[]).map(c=>priceRow(c,depth+1)).join('')}`;}
function renderPriceMatrix(){const q=db.quote,t=result.total;return `<div class="section-toolbar"><div><h2>Giá theo từng sản phẩm & mã vật tư</h2><p>Nhập chi phí ở cấp thực hiện. Chi phí cấp con được cộng lên đúng một lần.</p></div><div class="actions">${btn('↶ Hoàn tác','ux-undo',`data-undo-button ${UX.undo.length?'':'disabled'}`)}${btn('Cập nhật giá danh mục','refresh-prices')}</div></div>${remnantCostNote()}<div class="price-help">Số nhỏ: đơn giá/định mức đang nhập. Số đậm: thành tiền cho toàn bộ số lượng. Giá vật tư theo phương án phần dư đang chọn. Đổi đơn giá áp dụng cho cùng mã / ĐVT trong báo giá, không sửa danh mục.</div>${result.products.map(p=>`<section class="panel price-product"><div class="price-product-head"><div><strong>${esc(p.node.name)}</strong><span>${p.node.qty} ${esc(p.node.unit||'bộ')}</span></div><span>Giá chào trước thuế <strong class="mono" data-price-sell="${p.node.id}">${money(p.sell)}</strong> ₫</span></div><div class="table-scroll"><table class="cost-matrix"><thead><tr><th>Sản phẩm / cấu kiện / mã vật tư</th><th class="right">Vật tư</th><th>Nguyên công</th><th>Vận chuyển</th><th>Lắp đặt</th></tr></thead><tbody>${priceRow(p.node,0)}</tbody></table></div></section>`).join('')}<div class="pricing-bottom"><div class="panel"><div class="panel-head"><h2>Cấu hình giá chào</h2></div><div class="panel-body"><div class="form-grid">${[['Chi phí chung (%)','overhead',q.overhead,100],['Biên lợi nhuận (%)','margin',q.margin,95],['VAT (%)','vat',q.vat,100]].map(([label,key,val,max])=>`<label class="field"><span>${label}</span><input type="number" min="0" max="${max}" step="0.1" data-quote-field="${key}" value="${val}"></label>`).join('')}</div><div class="formula-explainer"><span>Cơ sở tính</span><p>Giá bán trước thuế = Chi phí ÷ (1 − Biên lợi nhuận).<br>Đơn giá chào làm tròn đến đồng trước khi nhân số lượng.</p></div></div></div><div class="price-summary"><div><span>Chi phí dự kiến</span><strong data-total-key="cost">${money(t.cost)} ₫</strong></div><div><span>Lợi nhuận dự kiến</span><strong class="positive" data-total-key="profit">${money(t.profit)} ₫</strong></div><div><span>VAT ${q.vat}%</span><strong data-total-key="vat">${money(t.vat)} ₫</strong></div><div class="grand"><span>Tổng chào khách hàng</span><strong data-total-key="grand">${money(t.grand)} ₫</strong></div>${btn('Xem bản chào giá →','preview','','primary wide')}</div></div>`;}
function catalogFilterPanel(){return `<div class="catalog-filters"><label><span>Hình dạng</span><select data-catalog-filter="shape"><option value="">Tất cả hình dạng</option>${Object.entries(C.shapes).map(([k,s])=>`<option value="${k}" ${UX.filters.shape===k?'selected':''}>${s.name}</option>`).join('')}</select></label><label><span>Mác vật liệu</span><select data-catalog-filter="grade"><option value="">Tất cả mác</option>${[...new Set(db.materials.map(m=>m.grade))].map(k=>`<option value="${esc(k)}" ${UX.filters.grade===k?'selected':''}>${esc(k)}</option>`).join('')}</select></label>${[['T','Dày'],['W','Rộng'],['H','Cao'],['D','Ø']].map(([k,label])=>`<label class="numeric-filter"><span>${label} (mm)</span><input aria-label="Lọc ${label.toLowerCase()}" type="number" min="0" step="any" data-catalog-filter="${k}" value="${esc(UX.filters[k])}" placeholder="Bất kỳ"></label>`).join('')}<button class="text-button" data-ux="clear-filters">Xóa lọc</button></div>`;}
function matchCatalog(m){return Object.entries(UX.filters).every(([k,v])=>v===''||(k==='shape'||k==='grade'?m[k]===v:Number(m.props[k])===Number(v)));}
function focusQuickNode(id){const input=document.querySelector('[data-qid="'+id+'"][data-qkind="dimension"]')||document.querySelector('[data-qid="'+id+'"]');if(input){input.focus();input.select();}}
function configureLinks(id){
  const p=C.findNode(db.quote.products,id);if(!p||p.kind!=='product')return;const nodes=C.scopedLeaves(p).filter(n=>n.spec.shape!=='piece'),params={L:null,W:null,H:null,...p.params},paramEntries=C.productParamEntries({params});
  openDialog('Kích thước chung & liên kết',`<p>Cấu hình một lần rồi lưu thành mẫu. Chỉ các ô được chọn liên kết mới đổi theo kích thước chung.</p><div class="form-grid three">${paramEntries.map(([k,v])=>field((productParamLabels[k]||k)+' chung (mm)',k,v??'','number',productParamAttrs(k))).join('')}</div>${field('Mẫu tên tự cập nhật (tùy chọn; dùng {L}, {W}, {H})','pattern',p.namePattern||'')}<div class="table-scroll"><table class="link-config-table"><thead><tr><th>Chi tiết</th><th>Ô nhập thực tế</th><th>Lấy từ tham số</th></tr></thead><tbody>${nodes.map(n=>editableKeys(n).map(k=>`<tr><td><b class="mono">${esc(n.materialId)}</b><small class="subtext">${esc((C.nodePath(db.quote.products,n.id)||[]).at(-2)?.name)}</small></td><td>${k} = ${num(n.dims[k]||0)} mm</td><td>${n.dimensionLinks?.[k]?`<small>${esc(n.dimensionLinks[k].mode==='formula'?n.dimensionLinks[k].expression:'Thông số đã cấu hình riêng')}</small><button type="button" class="button small" data-b2-dim="${n.id}">ƒ Sửa cấu hình</button>`:select('Liên kết '+n.materialId+' / '+k,n.id+'_'+k,[['','Nhập riêng'],...Object.keys(params).map(k=>[k,'PRODUCT_'+k+' · sản phẩm'])],n.paramLinks?.[k]||'')}</td></tr>`).join('')).join('')}</tbody></table></div><div class="notice">Áp dụng sẽ thay kích thước các ô liên kết bằng giá trị chung phía trên. Quy cách cố định của mã vật tư không thay đổi. Có thể hoàn tác.</div>`,'Áp dụng liên kết',f=>{
    const pattern=f.get('pattern').trim();if((pattern.match(/\{[^}]+\}/g)||[]).some(k=>!['{L}','{W}','{H}'].includes(k)))throw Error('Tên mẫu chỉ dùng {L}, {W}, {H}');
    saveAndClose(()=>{p.params=Object.fromEntries(paramEntries.map(([k])=>[k,productParamValue(f,k)]));p.namePattern=pattern;p.manualName=!pattern;for(const n of nodes){const hadLinks=Object.keys(n.paramLinks||{}).length;n.paramLinks={};for(const k of editableKeys(n)){const binding=f.get(n.id+'_'+k);if(binding)n.paramLinks[k]=binding;}if(Object.keys(n.paramLinks).length)n.detached=false;else if(hadLinks)n.detached=true;}for(const [k,v]of Object.entries(p.params))C.applyParam(p,k,v);},'Đã cấu hình liên kết. Lưu mẫu để dùng lại cho báo giá sau.');
  });$('#dialog').classList.add('wide-dialog');
}
function prepareSearchView(){
  if(UX.product&&!db.quote.products.some(p=>p.id===UX.product))UX.product='';
  UX.searchView=TPEntry.searchTree(db.quote.products.filter(p=>!UX.product||p.id===UX.product),UX.query);
  UX.errorView=null;
  if(UX.onlyErrors){UX.errorView=new Set();for(const n of C.flatten(db.quote.products))if(nodeProblem(n))for(const parent of C.nodePath(db.quote.products,n.id)||[])UX.errorView.add(parent.id);}
}
function quantityHint(n){
  const path=C.nodePath(db.quote.products,n.id)||[],parent=path.at(-2);
  return (parent?'Nhập cho 1 '+(parent.kind==='component'?'cấu kiện':'sản phẩm')+' '+parent.name+'. ':'')+'Toàn báo giá: '+path.map(n=>num(n.qty)).join(' × ')+' = '+num(result.nodes[n.id]?.count)+'.';
}
function pickerTarget(parent){
  const options=C.flatten(db.quote.products).filter(n=>n.kind!=='material').map(n=>[n.id,(C.nodePath(db.quote.products,n.id)||[]).map(p=>p.name).join(' › ')]);
  return `<div class="picker-target">${select('Đích thêm vật tư','target',options,parent.id,'id="picker-target"')}<div><span class="target-kind">${parent.kind==='component'?'Cấu kiện':'Sản phẩm'}</span><span>Định mức cho <b>1 ${parent.kind==='component'?'cấu kiện':'sản phẩm'}</b> · Toàn báo giá có <b>${num(result.nodes[parent.id]?.count)} đơn vị</b></span></div></div>`;
}
function addComponentGuided(parentId){
  const parent=C.findNode(db.quote.products,parentId);if(!parent||parent.kind!=='product')return;
  const templates=db.library.filter(n=>n.kind==='component');
  openDialog('Thêm cấu kiện',`<div class="import-destination"><span>Thuộc sản phẩm</span><strong>${esc(parent.name)}</strong></div>${select('Tạo từ','componentTemplate',[['','Cấu kiện trống'],...templates.map(t=>[t.id,(t.productGroup?t.productGroup+' / ':'')+t.name])],'')}${field('Tên cấu kiện','name','','text','maxlength="200" placeholder="Để trống sẽ dùng tên Cấu kiện mới"')}${field('Số cấu kiện trong 1 sản phẩm','qty',1,'number','min="1" max="5000" step="1" required')}<p id="component-template-preview" class="help-text">Tạo dòng cấu kiện trước, bổ sung tên và vật tư sau.</p><label class="continue-materials"><input type="checkbox" name="addMaterials"><span><strong>Chọn vật tư ngay sau khi tạo</strong><small>Vật tư được thêm đúng vào cấu kiện này.</small></span></label>`,'Tạo cấu kiện',f=>{
    inWritable();if(C.findNode(db.quote.products,parentId)!==parent)throw Error('Sản phẩm đã thay đổi, hãy mở lại');
    const template=templates.find(t=>t.id===f.get('componentTemplate')),qty=Number(f.get('qty'));
    if(f.get('componentTemplate')&&!template)throw Error('Mẫu không còn tồn tại');if(!Number.isInteger(qty)||qty<1||qty>5000)throw Error('Số cấu kiện phải từ 1 đến 5.000');
    const n=template?C.cloneNode(template):{id:C.uid(),kind:'component',children:[],ops:[]};delete n.templateKind;
    n.name=String(f.get('name')||'').trim()||template?.name||'Cấu kiện mới';n.qty=qty;const next=f.has('addMaterials');
    saveAndClose(()=>{parent.children??=[];parent.children.push(n);selected=n.id;UX.query='';UX.onlyErrors=false;UX.folded.delete(parent.id);},'Đã tạo cấu kiện '+n.name);
    if(next)batchMaterialPicker(n.id);else focusQuickNode(n.id);
  });
  const form=$('#dialog-form');form.elements.componentTemplate.onchange=()=>{const t=templates.find(t=>t.id===form.elements.componentTemplate.value);form.elements.name.value=t?.name||'';$('#component-template-preview').textContent=t?(t.children?.length||0)+' thành phần · Sao chép cấu thành và công đoạn từ mẫu. Có thể sửa riêng trong báo giá.':'Tạo dòng cấu kiện trước, bổ sung tên và vật tư sau.';};
  form.elements.addMaterials.onchange=e=>{$('#dialog button[type=submit]').textContent=e.target.checked?'Tạo & chọn vật tư':'Tạo cấu kiện';};
}
function setupUXActions(){
  actions['add-component']=el=>addComponentGuided(el.dataset.parent);
  actions.close=()=>{if(UX.returnPicker){const context=UX.returnPicker;UX.returnPicker=null;UX.picker=context;batchMaterialPicker(context.parentId,true);}else closeDialog();};
  $('#dialog').addEventListener('cancel',e=>{if(UX.returnPicker){e.preventDefault();actions.close();}});
  actions['ux-undo']=()=>undoUX();actions['ux-redo']=()=>undoUX(true);actions['quick-waste']=()=>{tab='waste';render();};actions.variant=el=>variantProduct(el.dataset.id);actions['paste-excel']=el=>pasteExcel(el.dataset.parent);actions['quick-3d']=el=>{const p=C.findNode(db.quote.products,el.dataset.id);openDialog(esc(p.name),`<div class="visual-panel modal-3d">${viewer(p)}</div>`);setup3d();};
}
function handleUX(action,el){const id=el.dataset.id;
  if(action==='quick-mode'||action==='detail-mode'){UX.mode=action==='quick-mode'?'quick':'detail';try{localStorage.setItem('tp-entry-mode',UX.mode);}catch{}render();}
  else if(action==='fold'){UX.folded.has(id)?UX.folded.delete(id):UX.folded.add(id);render();}
  else if(action==='inspect'){if($('#dialog').open)closeDialog();selected=id;UX.mode='detail';tab='bom';page='quote';render();}
  else if(action==='row-actions')nodeActions(id);
  else if(action==='configure-links')configureLinks(id);
  else if(action==='clear-search'){UX.query='';UX.onlyErrors=false;UX.checked.clear();render();$('#quick-search')?.focus();}
  else if(action==='clear-selection'){UX.checked.clear();updateBulk();}
  else if(action==='bulk-op')bulkOperation();
  else if(action==='bulk-material')replaceMaterials([...UX.checked].map(id=>C.findNode(db.quote.products,id)).filter(Boolean));
  else if(action==='bulk-copy'){const nodes=selectedTopNodes();mutation(()=>{for(const n of nodes){const path=C.nodePath(db.quote.products,n.id),parent=path.at(-2),list=parent?parent.children:db.quote.products;list.splice(list.indexOf(n)+1,0,C.cloneNode(n));}UX.checked.clear();});toast('Đã nhân bản '+nodes.length+' dòng');}
  else if(action==='bulk-delete'){const nodes=selectedTopNodes();mutation(()=>{for(const n of nodes)C.removeNode(db.quote.products,n.id);UX.checked.clear();});toast('Đã xóa '+nodes.length+' dòng. Bấm Hoàn tác để lấy lại.');}
  else if(action==='copy-one'){closeDialog();actions.duplicate({dataset:{id}});}
  else if(action==='delete-one'){closeDialog();mutation(()=>C.removeNode(db.quote.products,id));toast('Đã xóa dòng. Bấm Hoàn tác để lấy lại.');}
  else if(action==='replace-one'){closeDialog();replaceMaterials([C.findNode(db.quote.products,id)]);}
  else if(action==='detach'){closeDialog();mutation(()=>{const n=C.findNode(db.quote.products,id);n.paramLinks={};n.detached=true;const p=C.productOwner(db,id);if(p)C.formatName(p);});toast('Dòng này được chỉnh riêng. Các dòng khác giữ liên kết.');}
  else if(action==='add-to-node'){closeDialog();batchMaterialPicker(id);}
  else if(action==='create-in-picker'){const context=UX.picker;UX.returnPicker=context;editMaterial(null,m=>{UX.returnPicker=null;UX.picker=context;UX.basket.set(m.id,1);batchMaterialPicker(context.parentId,true);});}
  else if(action==='errors'){UX.onlyErrors=!UX.onlyErrors;UX.checked.clear();render();}
  else if(action==='clear-filters'){for(const k in UX.filters)UX.filters[k]='';search='';catalogGroup='';render();}
  else if(action==='price-ops'){selected=id;openDialog('Nguyên công: '+esc(current().name),renderOperations(current()));}
}
document.addEventListener('click',e=>{const el=e.target.closest('[data-ux]');if(el){e.preventDefault();handleUX(el.dataset.ux,el);}});
document.addEventListener('change',e=>{const el=e.target,d=el.dataset;if(d.basketId){if(el.checked)UX.basket.set(d.basketId,Number(el.closest('.batch-option').querySelector('[data-basket-qty]').value)||1);else UX.basket.delete(d.basketId);refreshBasket();return;}if(d.basketQty){if(!el.checkValidity()){el.reportValidity();return;}UX.basket.set(d.basketQty,Number(el.value));refreshBasket();return;}
  if(d.checkId){el.checked?UX.checked.add(d.checkId):UX.checked.delete(d.checkId);updateBulk();return;}if(d.checkProduct){for(const box of el.closest('.quick-product').querySelectorAll('[data-check-id]:not(:disabled)'))el.checked?UX.checked.add(box.dataset.checkId):UX.checked.delete(box.dataset.checkId);updateBulk();return;}
  if(d.qid||d.paramProduct){commitQuick(el);return;}
  if(d.catalogFilter){UX.filters[d.catalogFilter]=el.value;render();return;}
  if(el.id==='quick-product-filter'){UX.product=el.value;UX.checked.clear();render();return;}
  if(d.nodeCost||d.quotePrice){if(!el.checkValidity()||el.value===''){el.reportValidity();return;}mutation(()=>{const n=C.findNode(db.quote.products,d.quotePrice||d.id);if(d.quotePrice){for(const m of C.flatten(db.quote.products).filter(m=>m.kind==='material'&&m.materialId===n.materialId&&m.spec.unit===n.spec.unit))m.spec.price=Number(el.value);}else n[d.nodeCost]=Number(el.value);},{soft:true});refreshPriceUI();return;}
  if(el.closest('#dialog')&&d.opMode!==undefined){e.stopImmediatePropagation();mutation(()=>current().ops[Number(d.opMode)].mode=el.value);$('#dialog .dialog-body').innerHTML=renderOperations(current());}
  if(el.closest('#dialog')&&d.opAmount!==undefined){e.stopImmediatePropagation();if(!el.checkValidity())return el.reportValidity();mutation(()=>current().ops[Number(d.opAmount)].amount=Number(el.value));$('#dialog .dialog-body').innerHTML=renderOperations(current());}
});
document.addEventListener('input',e=>{if(e.target.id==='quick-search'){const pos=e.target.selectionStart;UX.query=e.target.value;UX.checked.clear();render();$('#quick-search').focus();$('#quick-search').setSelectionRange(pos,pos);}});
document.addEventListener('keydown',e=>{const el=e.target;
  if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!$('#dialog').open&&!el.matches('textarea')&&!el.matches('input[type=text]')){e.preventDefault();undoUX(e.shiftKey);return;}
  if((el.matches('[data-qid]')||el.matches('[data-param-product]'))&&['Tab','Enter'].includes(e.key)){e.preventDefault();if(!commitQuick(el))return;const inputs=[...document.querySelectorAll('[data-qid],[data-param-product]')],index=inputs.indexOf(el);let next;if(e.key==='Enter'&&el.dataset.qid){const same=inputs.filter(i=>i.dataset.qkey===el.dataset.qkey&&i.dataset.qkind===el.dataset.qkind);next=same[same.indexOf(el)+(e.shiftKey?-1:1)];}else next=inputs[index+(e.shiftKey?-1:1)];if(next){next.focus();next.select();}else el.blur();}
  if(el.id==='pick-search'&&e.key==='Enter'){e.preventDefault();const first=$('[data-basket-id]');if(first){first.checked=!first.checked;first.dispatchEvent(new Event('change',{bubbles:true}));}}
});
