'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs');
test('custom role presets, account profile and deletion preserve audit while revoking access',async t=>{const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port;
 async function call(route,method='GET',body,session){const r=await fetch(base+'/api/'+route,{method,headers:{'Content-Type':'application/json',...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};}
 const password='Accounts-review-local-42!',admin=await call('setup','POST',{username:'admin',name:'Admin',password});let r=await call('roles','POST',{name:'Vật tư',role:'estimator',sections:['materials'],canViewCosts:true},admin);A.equal(r.status,201);const role=r.data;
 const created=await call('users','POST',{username:'qa-staff',name:'Vật tư A',password,roleTemplateId:role.id},admin);A.equal(created.status,201);const id=created.data.id,staff=await call('login','POST',{username:'qa-staff',password});A.equal(staff.data.permissions.costs,true);A.deepEqual(staff.data.permissions.sections,['materials']);A.equal(staff.data.permissions.approve,false);
 A.equal((await call('roles','GET',undefined,staff)).status,403);A.equal((await call('users/'+id+'/delete','POST',{confirmUsername:'qa-staff'},staff)).status,403);A.equal((await call('roles/'+role.id,'DELETE',{expectedVersion:1},admin)).status,409);
 r=await call('roles/'+role.id,'PUT',{...role,sections:['logistics'],expectedVersion:1},admin);A.equal(r.status,200);A.deepEqual((await call('me','GET',undefined,staff)).data.permissions.sections,['materials']);A.equal((await call('roles/'+role.id,'PUT',{...role,expectedVersion:1},admin)).status,409);
 r=await call('users/'+id+'/access','POST',{roleTemplateId:role.id},admin);A.equal(r.status,200);A.equal((await call('me','GET',undefined,staff)).status,401);let login=await call('login','POST',{username:'qa-staff',password});A.deepEqual(login.data.permissions.sections,['logistics']);
 A.equal((await call('users/'+id+'/profile','POST',{username:'admin',name:'Duplicate'},admin)).status,409);A.equal((await call('users/'+id+'/profile','POST',{username:'qa-renamed',name:'New name'},admin)).status,200);A.equal((await call('me','GET',undefined,login)).status,401);login=await call('login','POST',{username:'qa-renamed',password});A.equal(login.status,200);
 A.equal((await call('users/'+admin.data.user.id+'/delete','POST',{confirmUsername:'admin'},admin)).status,400);A.equal((await call('users/'+id+'/delete','POST',{confirmUsername:'wrong'},admin)).status,400);A.equal((await call('users/'+id+'/delete','POST',{confirmUsername:'qa-renamed'},admin)).status,200);A.equal((await call('me','GET',undefined,login)).status,401);A.equal((await call('users/'+id+'/enable','POST',{},admin)).status,404);A.ok(!(await call('users','GET',undefined,admin)).data.some(u=>u.id===id));A.ok(app.sql.prepare('SELECT deleted_at FROM users WHERE id=?').get(id).deleted_at);A.ok(app.sql.prepare("SELECT seq FROM audit WHERE entity=? AND action='delete-user'").get(id));A.equal((await call('roles/'+role.id,'DELETE',{expectedVersion:2},admin)).status,200);const backup=(await call('backup','GET',undefined,admin)).data;A.ok(backup.users.find(u=>u.id===id).deleted_at);A.deepEqual(backup.roleTemplates,[]);
});
