const {test}=require('node:test'),A=require('node:assert/strict'),{randomUUID}=require('node:crypto'),{createApp}=require('../server/app.cjs'),AI=require('../server/ai-pdf.cjs'),Core=require('../ai-pdf-core.js'),C=require('../core.js');
const fixture={title:'Bản mã',warnings:[],items:[{group:'Cụm A',name:'Bản mã',material:'Thép',specification:'Lỗ D8',quantity:null,unit:'cái',lengthMm:70,widthMm:70,thicknessMm:3,diameterMm:null,page:1,evidence:'70x70x3',warnings:['Chưa ghi số lượng']}]};
test('AI groups assemblies and targets existing products without mutating them',()=>{
 const db=require('../pricing-core.js').demoSeed(),job={status:'ready',digest:'group-test',filename:'drawing.pdf',result:{...fixture,items:[fixture.items[0],{...fixture.items[0],group:'Cụm B'}]}},rows=[0,1].map(index=>({index,name:'Part '+index,qty:2,unit:'pcs'}));
 const before=JSON.stringify(db),grouped=Core.arrange(db,job,rows);A.equal(grouped.products.length,2);A.equal(grouped.products[0].children[0].kind,'component');A.equal(grouped.products[0].qty,1);A.equal(grouped.products[0].children[0].qty,2);
 const target=Core.arrange(db,job,rows,db.quote.products[0].id);A.equal(target.products.length,2);A.equal(target.target,db.quote.products[0].id);A.equal(JSON.stringify(db),before);A.throws(()=>Core.arrange(db,job,rows,'deleted'));
});
test('AI retains unknowns, no partial import, no duplicates, catalog prices and dimensions',()=>{const db=require('../pricing-core.js').demoSeed(),job={status:'ready',digest:'abc',filename:'drawing.pdf',result:fixture};A.throws(()=>Core.plan(db,job,[{index:0,name:'Bản',qty:''}]),/số lượng/);const row={index:0,name:'Bản',qty:2,unit:'cái',L:70,W:70,T:3,specification:'Lỗ D8'};const request=Core.plan(db,job,[row])[0];A.equal(request.children.length,0);A.match(request.requestSpecification,/L 70/);db.quote.products.push(request);Core.installValidation();A.ok(C.calculate(db).errors.some(e=>e.includes('chưa được bóc tách')));A.throws(()=>Core.plan(db,job,[row]),/đã được nhập/);db.quote.products.pop();const m={id:'ai-m',name:'Thép tấm 3',shape:'sheet',props:{T:3},price:1234,unit:'kg',density:7850,stock:{L:2440,W:1220},substance:'Thép'};db.materials.push(m);const made=Core.plan(db,job,[{...row,materialId:m.id}])[0];A.equal(made.children[0].spec.price,1234);A.equal(made.children[0].dims.L,70);A.equal(made.qty,2);A.throws(()=>Core.plan(db,job,[{...row,materialId:m.id,T:5}]),/chiều dày/);A.throws(()=>Core.plan(db,job,[{...row,materialId:m.id,unit:'m'}]),/số chi tiết/);A.equal(AI.validateResult(fixture).items[0].quantity,null);A.throws(()=>AI.validateResult({...fixture,items:[{...fixture.items[0],lengthMm:Infinity}]}));});
test('AI API protects keys, PDF jobs, retry identity, auth, backup; does not change quotes',async t=>{let calls=0;const app=createApp({aiProvider:async()=>{calls++;return {result:fixture,model:'test',usage:{inputTokens:1,outputTokens:1}};}});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port;async function call(route,method='GET',body,s){const r=await fetch(base+'/api/'+route,{method,headers:{'Content-Type':'application/json',...(s?{Cookie:s.cookie,'X-CSRF-Token':s.data.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};}const pw='Ai-test-password-2026!',a=await call('setup','POST',{username:'admin',name:'Admin',password:pw});await call('users','POST',{username:'tech',name:'Tech',password:pw,role:'technical'},a);const tech=await call('login','POST',{username:'tech',password:pw});A.equal((await call('ai/pdf')).status,401);A.equal((await call('ai/pdf','GET',undefined,tech)).status,200);const payload={requestId:randomUUID(),name:'drawing.pdf',data:Buffer.from('%PDF-1.4\n%%EOF').toString('base64')};A.equal((await call('ai/pdf','POST',payload,{...a,data:{csrf:'bad'}})).status,403);A.equal((await call('ai/pdf','POST',{...payload,data:'SGVsbG8='},a)).status,400);const j=await call('ai/pdf','POST',payload,a);A.equal(j.status,202);const same=await call('ai/pdf','POST',payload,a);A.equal(j.data.id,same.data.id);A.equal(calls,1);const ready=await call('ai/pdf/'+j.data.id,'GET',undefined,a);A.equal(ready.data.status,'ready');A.equal(ready.data.result.items[0].quantity,null);A.equal((await call('ai/pdf/'+j.data.id+'/file','GET',undefined,tech)).status,404);A.equal((await call('ai/pdf/'+j.data.id+'/file','GET',undefined,a)).data.data,payload.data);A.equal(app.sql.prepare('SELECT count(*) AS n FROM quotes').get().n,0);const backup=await call('backup','GET',undefined,a);A.equal(backup.data.aiPdfJobs.length,1);});
test('OpenAI request uses structured output without storage; refusal and rate errors are safe',async()=>{let request;const result=await AI.extract({name:'x.pdf',data:'abcd',apiKey:'test-secret',fetchImpl:async(u,opts)=>{request=JSON.parse(opts.body);return {ok:true,json:async()=>({status:'completed',model:'test',output:[{content:[{type:'output_text',text:JSON.stringify(fixture)}]}]})};}});A.equal(request.store,false);A.equal(request.text.format.strict,true);A.equal(result.result.items[0].thicknessMm,3);await A.rejects(AI.extract({name:'x.pdf',data:'a',apiKey:'secret',fetchImpl:async()=>({ok:false,status:429})}),/hạn mức/);await A.rejects(AI.extract({name:'x.pdf',data:'a',apiKey:'secret',fetchImpl:async()=>({ok:true,json:async()=>({status:'incomplete'})})}),/chưa đọc xong/);});

test('AI cost controls reject expensive model before network and cap output',async()=>{let calls=0;await A.rejects(AI.extract({model:'gpt-6-astra',apiKey:'test',fetchImpl:async()=>{calls++;}}));A.equal(calls,0);let request;await AI.extract({model:'gpt-5.6-terra',name:'x.pdf',data:'abcd',apiKey:'test',fetchImpl:async(u,o)=>{calls++;request=JSON.parse(o.body);return {ok:true,json:async()=>({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(fixture)}]}]})};}});A.equal(calls,1);A.equal(request.model,'gpt-5.6-terra');A.equal(request.max_output_tokens,8000);});
