'use strict';
const {test}=require('node:test'),A=require('node:assert/strict');
const C=require('../core.js'),P=require('../pricing-core.js'),I=require('../intake-core.js'),B=require('../batch-one-core.js'),F=require('../completion-core.js');
const near=(a,b)=>A.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
function profileData(){const db=P.demoSeed(),m=B.profileSpec({id:'KT-HINH',name:'Thép hình kiểm thử',group:C.groups[0],shape:'profile',props:{},price:20000,unit:'kg',substance:'Thép',grade:'CT3',density:7850,stockL:6000,stockW:0},{mass:10,area:.5,reason:'Bảng thử'}),line={id:'vt',kind:'material',name:m.name,materialId:m.id,spec:m,qty:3,dims:{L:2000},rule:'bar',ruleSpec:{id:'bar',name:'Dài thanh',shape:'bar',length:'L',width:'0'},ops:[]};db.materials.push(C.copy(m));db.quote.products=[{id:'sp',kind:'product',name:'Kiểm thử dữ liệu tra',qty:1,unit:'bộ',children:[line],ops:[]}];db.quote.kerf=0;return {db,m,line};}
test('batch01: sequential material codes do not reuse existing IDs',()=>{const materials=[{id:'VT-00001'},{id:'vt-00002'},{id:'OTHER'}];A.equal(B.nextMaterialId(materials),'VT-00003');materials.push({id:B.nextMaterialId(materials)});A.equal(B.nextMaterialId(materials),'VT-00004');});
test('batch01: brand and specification isolate manual/catalogue prices and immutable snapshots',()=>{const db=P.demoSeed(),source=db.materials.find(m=>m.id==='LK-CHAN'),a={...C.copy(source),brand:'Hãng thử A',specification:'Cùng thông số',price:1000000},b={...C.copy(source),brand:'Hãng thử B',specification:'Cùng thông số',price:1500000};db.materials=db.materials.filter(m=>m.id!==a.id).concat(C.copy(b));db.quote.products=[{id:'sp',kind:'product',name:'Thiết bị thử',qty:1,children:[{id:'a',kind:'material',materialId:a.id,name:a.name,qty:2,spec:a,ops:[]},{id:'b',kind:'material',materialId:b.id,name:b.name,qty:2,spec:b,ops:[]}],ops:[]}];db.quote.ratesSnapshot=[];const history=C.copy(db.quote),rows=I.priceRows(db);A.equal(rows.length,2);A.equal(rows[0].reference,undefined);A.equal(rows[1].reference,1500000);I.applyMaterialPrices(db,[{key:rows[1].key,value:1600000,source:'manual'}]);A.equal(a.price,1000000);A.equal(b.price,1600000);A.equal(history.products[0].children[1].spec.price,1500000);P.refreshPrices(db);A.equal(a.price,1000000);A.equal(b.price,1500000);A.equal(F.priceFor(a,[{substance:a.substance,grade:a.grade,unit:a.unit,price:1}]).value,1000000);const result=C.calculate(db);A.equal(result.nodes.a.material,2000000);A.equal(result.nodes.b.material,3000000);});
test('batch01: equipment permits unknown material but not an orphan grade; names do not omit brand',()=>{const db=P.demoSeed();A.doesNotThrow(()=>I.validateMaterial(db,{shape:'piece',substance:''}));A.throws(()=>I.validateMaterial(db,{shape:'piece',substance:'',grade:'CT3'}));A.match(I.materialName({shape:'piece',brand:'Hãng thử A',specification:'500 W'}),/Hãng thử A/);});
test('batch01: kg/m and m²/m convert mm once and apply consistently to purchased stock',()=>{const {db,line}=profileData(),one=C.geometry(line,1),all=C.calculate(db);near(one.weight,20);near(one.blankArea,1);near(all.rows[0].geometry.weight,60);near(all.rows[0].geometry.blankArea,3);near(all.rows[0].purchasedWeight,60);near(all.rows[0].purchasedArea,3);A.deepEqual(C.calculate(JSON.parse(JSON.stringify(db))),all);});
test('batch01: missing or invalid reference data cannot masquerade as zero valid weight',()=>{const {m}=profileData();for(const input of [{mass:0,area:.5,reason:'x'},{mass:10,area:'',reason:'x'},{mass:10,area:.5,reason:''}])A.throws(()=>B.profileSpec(m,input));delete m.massOverride;A.throws(()=>C.materialMass(m),/kg\/m/);delete m.areaOverride;A.throws(()=>C.materialSurface(m),/m²\/m/);});
test('batch01: profile data reused explicitly does not mutate catalogue or old quote',()=>{const {db,line}=profileData(),original=C.copy(db.materials.at(-1)),history=C.copy(db.quote);const updated=B.profileSpec(line.spec,{mass:12,area:.6,reason:'Bảng tra mới'});line.spec=updated;A.deepEqual(db.materials.at(-1),original);A.deepEqual(history.products[0].children[0].spec,original);near(C.geometry(line,1).weight,24);});
test('batch01: stock options are dimensions, not altered section properties; malformed/duplicate stocks rejected',()=>{A.deepEqual(B.parseStocks('2440 x 1220\n3000 × 1500','sheet'),[{length:2440,width:1220},{length:3000,width:1500}]);A.deepEqual(B.parseStocks('6000\n12000','profile'),[{length:6000,width:0},{length:12000,width:0}]);for(const s of ['0','6000x100','NaN','6000\n6000'])A.throws(()=>B.parseStocks(s,'box'));});
test('batch01: remnant threshold is inclusive, rotation invariant and separate from kerf',()=>{const {db,m,line}=profileData();const rule={minL:300,minW:0};for(const [l,expected]of [[299,false],[300,true],[301,true]])A.equal(C.remnantEligibility(m,{l,w:0},rule),expected);A.equal(C.remnantEligibility({...m,shape:'sheet'},{l:200,w:500},{minL:500,minW:200}),true);line.qty=1;line.dims.L=5600;db.quote.kerf=10;let result=C.calculate(db),g=result.groups[0];db.quote.remnantSelections={[g.signature]:g.remnants.map(r=>r.id)};db.quote.remnantMode='exclude';db.quote.remnantRules={[C.remnantRuleKey(m)]:{minL:400,minW:0}};result=C.calculate(db);A.equal(result.reuse.selectedCount,0);A.equal(result.reuse.credit,0);A.equal(result.groups[0].remnants[0].eligible,false);A.equal(db.quote.kerf,10);A.ok(result.errors.some(e=>/phần dư/i.test(e)));});
test('batch01: shared tree preserves ordering, IDs, parentage and multiplied counts without mutating templates',()=>{const db=P.demoSeed(),before=C.copy(db),rows=B.treeRows(db.quote.products);A.deepEqual(rows.map(x=>x.id),C.flatten(db.quote.products).map(n=>n.id));for(const type of ['product','component','component-material','product-material'])A.ok(rows.some(x=>x.type===type));for(const r of rows)near(r.count,C.calculate(db).nodes[r.id].count);const template=C.copy(db.library[0]),clone=C.cloneNode(db.library[0]);clone.name='Biến thể thử';A.deepEqual(db.library[0],template);A.deepEqual(db,before);});
test('batch01: request details and uploads validate without invented deadlines or compulsory project fields',()=>{A.equal(B.requestDetails({}).quoteDeadline,'');A.throws(()=>B.requestDetails({quoteDeadline:'2026-02-30'}));A.doesNotThrow(()=>I.validateRequest({request:{items:[],files:[],quoteDeadline:'2026-09-30',schedule:'Giao đợt 1',recipient:'Phòng mua hàng',location:'Xưởng'}}));A.throws(()=>I.validateRequest({request:{items:[],files:[],schedule:8}}));B.validateFiles([{name:'input.pdf',size:1024}]);A.throws(()=>B.validateFiles([{name:'input.html',size:10}]));A.throws(()=>B.validateFiles([{name:'input.pdf',size:10485761}]));A.throws(()=>B.validateFiles([{name:'input.pdf',size:10}],30));});
