'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),{randomUUID}=require('node:crypto');
test('business: contract lifecycle, receipts, costs, CAS, idempotency, permissions, profile and backup',async t=>{
 const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port,password='Business-Tests-2026!';
 async function call(path,method='GET',body,s=admin){const r=await fetch(base+'/api/'+path,{method,headers:{'Content-Type':'application/json',...(s?{Cookie:s.cookie,'X-CSRF-Token':s.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};}
 let admin;admin=await call('setup','POST',{username:'admin',name:'Admin',password},null);
 app.sql.prepare('INSERT INTO intake_customers VALUES(?,?,?)').run('c1',1,JSON.stringify({id:'c1',name:'Customer 1',ownerId:admin.data.user.id}));
 const doc={code:'HD-01',customerId:'c1',value:1000,status:'active',signDate:'2026-01-01',startDate:'2026-01-01',endDate:'2027-01-01',dueDate:'2026-01-02',terms:'Terms'};
 let r=await call('business/contracts','POST',{expectedVersion:0,document:doc});A.equal(r.status,200,JSON.stringify(r.data));let c=r.data;A.equal(c.remaining,1000);A.equal(c.overdue,true);
 A.equal((await call('business/contracts','POST',{expectedVersion:0,document:doc})).status,409);
 A.equal((await call('business/contracts/'+c.id,'POST',{expectedVersion:0,document:doc})).status,409);
 for(const change of [{value:-1},{endDate:'2025-01-01'},{startDate:'2026-02-30'},{customerId:'missing'}])A.equal((await call('business/contracts/'+c.id,'POST',{expectedVersion:1,document:{...doc,...change}})).status,400);
 const payment={contractId:c.id,expectedVersion:1,requestId:randomUUID(),amount:400,date:'2026-09-25',reference:'PT-1'};
 r=await call('business/payments','POST',payment);A.equal(r.status,200,JSON.stringify(r.data));A.equal((await call('business/payments','POST',payment)).status,200);A.equal((await call('business/payments','POST',{...payment,amount:500})).status,409);
 c=(await call('business/contracts/'+c.id)).data;A.equal(c.paid,400);A.equal(c.version,2);A.equal(c.payments.length,1);
 A.equal((await call('business/payments','POST',{...payment,requestId:randomUUID(),reference:'PT-2',expectedVersion:2,amount:601})).status,400);
 A.equal((await call('business/contracts/'+c.id,'POST',{expectedVersion:2,document:{...doc,status:'cancelled'}})).status,409);
 const cost={contractId:c.id,expectedVersion:2,requestId:randomUUID(),amount:100,date:'2026-09-25',reference:'PC-1',category:'freight'};A.equal((await call('business/costs','POST',cost)).status,200);c=(await call('business/contracts/'+c.id)).data;A.equal(c.actualCost,100);
 const debt=(await call('business/customers/c1')).data;A.equal(debt.receivable,600);A.equal(debt.collected,400);
 await call('users','POST',{username:'sales',name:'Sales',role:'sales',sections:['customer','commercial'],password});const sales=await call('login','POST',{username:'sales',password},null);r=await call('business/contracts/'+c.id,'GET',undefined,sales);A.equal(r.status,200);A.equal(r.data.costs,undefined);A.equal(r.data.actualCost,undefined);A.equal((await call('business/payments','POST',payment,sales)).status,403);
 await call('users','POST',{username:'tech',name:'Tech',role:'technical',password});const tech=await call('login','POST',{username:'tech',password},null);for(const path of ['contracts','orders','profile','customers/c1','people'])A.equal((await call('business/'+path,'GET',undefined,tech)).status,403,path);
 const entry=c.payments[0];A.equal((await call('business/payments/'+entry.id+'/void','POST',{expectedVersion:entry.version,reason:'Correction'})).status,200);c=(await call('business/contracts/'+c.id)).data;A.equal(c.paid,0);A.equal(c.remaining,1000);
 let p=(await call('business/profile')).data;A.equal(p.version,0);r=await call('business/profile','POST',{expectedVersion:0,document:{...p,company:{name:'Company'},staff:[{id:'staff1',department:'Engineering',position:'Engineer',count:'3',qualification:'Mechanical'}]}});A.equal(r.status,200,JSON.stringify(r.data));A.equal(r.data.staff[0].count,'3');A.equal((await call('business/profile','POST',{expectedVersion:0,document:p})).status,409);A.equal((await call('business/profile','POST',{expectedVersion:1,document:p},sales)).status,403);
 A.equal((await call('business/files','POST',{name:'fake.pdf',mime:'application/pdf',data:Buffer.from('not a pdf file').toString('base64')})).status,400);const file=await call('business/files','POST',{name:'test.pdf',mime:'application/pdf',data:Buffer.from('%PDF-1.7\ntest').toString('base64')});A.equal(file.status,201);A.equal((await call('business/files/'+file.data.id)).data.name,'test.pdf');A.equal((await call('business/files/'+file.data.id,'GET',undefined,tech)).status,403);
 const backup=(await call('backup')).data;A.ok(backup.businessRecords.length>=4);A.equal(backup.businessFiles.length,1);
 A.equal((await call('business/customers/c1/delete','POST',{expectedVersion:1,reason:'Cannot delete linked customer'})).status,409);
 app.sql.prepare('INSERT INTO intake_customers VALUES(?,?,?)').run('unused',1,JSON.stringify({id:'unused',name:'Unused'}));A.equal((await call('business/customers/unused/delete','POST',{expectedVersion:0,reason:'Cleanup'})).status,409);A.equal((await call('business/customers/unused/delete','POST',{expectedVersion:1,reason:'Cleanup'})).status,200);A.ok(app.sql.prepare("SELECT * FROM business_records WHERE kind='deleted-customer' AND id='unused'").get());
 A.equal((await call('business/contracts/'+c.id,'POST',{expectedVersion:c.version,document:{...doc,startDate:'2026-99-99'}})).status,400);
});
test('orders derive completion from all ordered quantities, preserve source and protect delivery/cancellation',async t=>{
 const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port;let cookie,csrf;
 async function call(p,m='GET',body){const r=await fetch(base+'/api/'+p,{method:m,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie,'X-CSRF-Token':csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();if(p==='setup'){cookie=r.headers.get('set-cookie').split(';')[0];csrf=data.csrf;}return {status:r.status,data};}
 await call('setup','POST',{username:'admin',name:'Admin',password:'Orders-Tests-2026!'});const q=randomUUID(),id=randomUUID(),now=new Date().toISOString();app.sql.prepare('INSERT INTO quotes VALUES(?,?,?,?,?,?,?,?,?,?)').run(q,'BG','Customer','Project',1,'approved',100,'{}',now,'admin');const packet={id,code:'DH',quoteId:q,quoteCode:'BG',quoteVersion:1,status:'awaiting-production',customer:'Customer',quote:{customerInfo:{id:'c'},products:[{id:'p1',qty:10}]},offer:{products:[],totals:{grand:100}}};app.sql.prepare('INSERT INTO orders VALUES(?,?,?,?,?,?,?)').run(id,'DH',q,1,JSON.stringify(packet),now,'admin');
 A.equal((await call('business/orders/'+id)).data.status,'waiting');A.equal((await call('business/orders/'+id+'/deliver','POST',{expectedVersion:0,date:'2026-09-25',receiver:'A'})).status,409);
 app.sql.prepare('INSERT INTO production_jobs VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(randomUUID(),'LSX',id,'p1',5,1,'completed','{}','{}',now,now,'admin');A.equal((await call('business/orders/'+id)).data.status,'producing');A.equal((await call('business/orders/'+id+'/cancel','POST',{expectedVersion:0,reason:'Cancel'})).status,409);
 app.sql.prepare('UPDATE production_jobs SET quantity=10 WHERE order_id=?').run(id);A.equal((await call('business/orders/'+id)).data.status,'completed');A.equal((await call('business/orders/'+id+'/deliver','POST',{expectedVersion:0,date:'2026-09-25',receiver:'Receiver'})).status,200);A.equal((await call('business/orders/'+id)).data.status,'delivered');A.equal((await call('business/orders/'+id+'/metadata','POST',{expectedVersion:0,dueDate:'',salespeople:[]})).status,409);A.equal(JSON.parse(app.sql.prepare('SELECT package FROM orders WHERE id=?').get(id).package).quoteVersion,1);
});
test('ZIP profile package preserves binary scans and UTF-8 names',()=>{const x=require('../xlsx.js'),bytes=Uint8Array.from([0,255,128,1,13,10]),zip=Buffer.from(x.zip({'scan.png':bytes,'Thông tin.txt':'Trường Phát'}));A.equal(zip.readUInt32LE(0),0x04034b50);let offset=0,files={};while(zip.readUInt32LE(offset)===0x04034b50){const size=zip.readUInt32LE(offset+18),n=zip.readUInt16LE(offset+26),extra=zip.readUInt16LE(offset+28),name=zip.subarray(offset+30,offset+30+n).toString(),start=offset+30+n+extra;files[name]=zip.subarray(start,start+size);offset=start+size;}A.deepEqual(files['scan.png'],Buffer.from(bytes));A.equal(files['Thông tin.txt'].toString(),'Trường Phát');});
