const {chromium,expect}=require('@playwright/test'),{createApp}=require('../server/app.cjs');
(async()=>{const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:'+app.server.address().port);await p.waitForFunction(()=>Team.available);
 await p.evaluate(async()=>{teamSession(await teamApi('setup','POST',{username:'admin',name:'Admin',password:'Business-browser-2026!'}));render();});
 app.sql.prepare('INSERT INTO intake_customers VALUES(?,?,?)').run('customer1',1,JSON.stringify({id:'customer1',name:'Customer test'}));
 await p.locator('#sidebar [data-business=contracts]').click();await expect(p.locator('#content')).toContainText('Hợp đồng');await p.locator('[data-business=new]').click();await p.locator('#dialog [name=code]').fill('HD-BROWSER');await p.locator('#dialog [name=customerId]').selectOption('customer1');await p.locator('#dialog [name=value]').fill('1000000');await p.locator('#dialog [name=signDate]').fill('2026-09-25');await p.locator('#dialog [name=startDate]').fill('2026-09-25');await p.locator('#dialog [name=status]').selectOption('active');await p.locator('#dialog [name=terms]').fill('Supply and installation');await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#content')).toContainText('HD-BROWSER');
 await p.locator('[data-business=payment]').click();await p.locator('#dialog [name=reference]').fill('PT-BROWSER');await p.locator('#dialog [name=amount]').fill('200000');await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#content')).toContainText('PT-BROWSER');await expect(p.locator('#content')).toContainText('800.000');
 await p.locator('#sidebar [data-business=profile]').click();await p.locator('[data-business=profile-company]').click();await p.locator('#dialog [name=name]').fill('Truong Phat test');await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#content')).toContainText('Truong Phat test');await p.locator('[data-business=profile-add][data-id=machines]').click();await p.locator('#dialog [name=name]').fill('Laser cutting');await p.locator('#dialog [name=year]').fill('2025');await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#content')).toContainText('Laser cutting');
 await p.reload();await p.waitForFunction(()=>Team.user);await p.locator('#sidebar [data-business=profile]').click();await expect(p.locator('#content')).toContainText('Laser cutting');
 await p.locator('#sidebar [data-business=contracts]').click();const d=p.waitForEvent('download');await p.locator('[data-business=export]').click();expect((await d).suggestedFilename()).toBe('HOP-DONG.xlsx');await p.locator('#bs-query').fill('not found');await expect(p.locator('#bs-list')).not.toContainText('HD-BROWSER');await p.locator('#bs-query').fill('HD-BROWSER');await expect(p.locator('#bs-list')).toContainText('HD-BROWSER');
 await p.screenshot({path:'artifacts/business-desktop.png'});await p.setViewportSize({width:390,height:844});expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await p.screenshot({path:'artifacts/business-mobile.png'});expect(errors).toEqual([]);console.log('PASS business desktop/mobile, contract creation, payment, profile persistence, export and filter');
 }finally{await browser.close();await new Promise(r=>app.server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
