'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),P=require('../pricing-core.js'),D=require('../definition-core.js');
test('technical formulas wait for admin approval, cannot bypass through quote or material, and duplicate declarations are rejected',async t=>{
 const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));
 async function call(route,method='GET',body,session){const r=await fetch('http://127.0.0.1:'+app.server.address().port+'/api/'+route,{method,headers:{'Content-Type':'application/json',...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};}
 const password='Catalog-review-test-42!',admin=await call('setup','POST',{username:'admin',name:'Admin',password});await call('users','POST',{username:'tech',name:'Technical',password,role:'technical',technicalDelegation:true,canViewCosts:false,canFormulaUse:true,canFormulaView:true,canFormulaEdit:true,sections:['bom','operations','catalogRules','catalogMaterials','catalogTechnicalOperations']},admin);const tech=await call('login','POST',{username:'tech',password});
 let master=(await call('catalog','GET',undefined,admin)).data;const shape={id:'REVIEW-SHAPE',name:'Review triangle',...D.polygonPreset('triangle',3),surface:'1'};master.catalog.shapeDefinitions=[shape];A.equal((await call('catalog','PUT',{expectedVersion:master.version,catalog:master.catalog},admin)).status,200);
 const doc=P.demoSeed(),mat=D.applyShape({id:'REVIEW-MATERIAL',name:'Review material',density:7850,unit:'kg',price:12345,stockL:1000,stockW:1000},shape,{T:2});doc.materials.push(mat);doc.shapeDefinitions=[shape];doc.quote.remnantMode='all';doc.quote.products=[{id:'SP',kind:'product',name:'Product',qty:1,ops:[],children:[D.assign(D.draft('Part',1),mat,doc.rules)]}];const q=(await call('quotes','POST',{document:doc},admin)).data;
 let pending=(await call('catalog','GET',undefined,tech)).data;pending.catalog.shapeDefinitions[0].surface='2';const proposal=await call('catalog','PUT',{expectedVersion:pending.version,catalog:pending.catalog},tech);A.equal(proposal.status,200,JSON.stringify(proposal.data));A.equal(proposal.data.pending,true);A.equal((await call('catalog','GET',undefined,admin)).data.catalog.shapeDefinitions[0].surface,'1');A.equal((await call('quotes/'+q.id,'GET',undefined,admin)).data.version,q.version);
 let quote=(await call('quotes/'+q.id,'GET',undefined,tech)).data;quote.document.quote.products[0].children[0].spec.shapeDefinition.surface='2';const bypass=await call('quotes/'+q.id,'PUT',{expectedVersion:quote.version,document:quote.document},tech);A.equal(bypass.status,403);A.match(bypass.data.error,/Admin/);
 A.equal((await call('catalog/proposals/'+proposal.data.proposalId+'/approve','POST',{},tech)).status,403);A.equal((await call('catalog/proposals/'+proposal.data.proposalId+'/approve','POST',{},admin)).status,200);
 quote=(await call('quotes/'+q.id,'GET',undefined,admin)).data;A.equal(quote.document.quote.products[0].children[0].spec.shapeDefinition.surface,'2');A.equal(quote.document.quote.products[0].children[0].spec.price,12345);A.equal(quote.version,q.version+1);
 // A material-only save must not publish a newly embedded formula immediately.
 pending=(await call('catalog','GET',undefined,tech)).data;const raw=structuredClone(mat);raw.id='EMBEDDED-PENDING';raw.price=0;raw.shapeDefinition={...raw.shapeDefinition,id:'EMBEDDED-FORMULA',name:'Embedded formula',surface:'3'};pending.catalog.materials.push(require('../technical-core.js').projectCatalog({...doc,materials:[raw]}).materials[0]);const embedded=await call('catalog','PUT',{expectedVersion:pending.version,catalog:pending.catalog},tech);A.equal(embedded.status,200,JSON.stringify(embedded.data));A.equal(embedded.data.pending,true);A.ok(!(await call('catalog','GET',undefined,admin)).data.catalog.materials.some(m=>m.id===raw.id));
 master=(await call('catalog','GET',undefined,admin)).data;for(const kind of ['shapeDefinitions','rates']){const duplicate=structuredClone(master.catalog),item=duplicate[kind][0];duplicate[kind].push({...item,id:'DUPLICATE-'+kind,name:'  '+item.name.toUpperCase()+'  '});const response=await call('catalog','PUT',{expectedVersion:master.version,catalog:duplicate},admin);A.equal(response.status,409,JSON.stringify(response.data));A.match(response.data.error,/trùng/);A.equal((await call('catalog','GET',undefined,admin)).data.version,master.version);}
 A.equal((await call('catalog/proposals/'+embedded.data.proposalId+'/reject','POST',{reason:'Use existing approved declaration'},admin)).status,200);A.equal((await call('catalog/proposals/'+embedded.data.proposalId+'/approve','POST',{},admin)).status,409);
});
