const {test}=require('node:test'),A=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{randomUUID}=require('node:crypto'),{createApp}=require('../server/app.cjs');
test('chat contract: direct/group, membership isolation, images, deduplication, read state and persistence',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tp-chat-')),databasePath=path.join(dir,'chat.sqlite');let app=createApp({databasePath});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));let base='http://127.0.0.1:'+app.server.address().port;t.after(async()=>{await new Promise(r=>app.server.close(r));fs.rmSync(dir,{recursive:true,force:true});});
 const call=async(route,method='GET',body,s)=>{const r=await fetch(base+'/api/'+route,{method,headers:{'Content-Type':'application/json',...(s?{Cookie:s.cookie,'X-CSRF-Token':s.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:(r.headers.get('content-type')||'').includes('json')?await r.json():Buffer.from(await r.arrayBuffer()),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
 const password='Chat-local-test-2026!';let admin=await call('setup','POST',{username:'admin',name:'Admin',password});admin.csrf=admin.data.csrf;const users={};for(const username of ['tech','sales','other']){const u=(await call('users','POST',{username,name:username,password,role:username==='tech'?'technical':'estimator'},admin)).data;const s=await call('login','POST',{username,password});s.csrf=s.data.csrf;users[username]={...s,id:u.id};}
 A.equal((await call('chat/rooms')).status,401);A.equal((await call('chat/users','GET',undefined,users.tech)).status,200);A.equal((await call('chat/users','GET',undefined,users.tech)).data[0].password,undefined);
 const b={kind:'direct',members:[users.tech.id]},room=(await call('chat/rooms','POST',b,admin)).data;A.ok(room.id);A.equal((await call('chat/rooms','POST',b,admin)).data.id,room.id);A.equal((await call('chat/rooms','POST',{kind:'direct',members:[admin.data.user.id]},users.tech)).data.id,room.id);
 A.equal((await call('chat/rooms/'+room.id+'/messages','GET',undefined,users.other)).status,404);A.equal((await call('chat/rooms','GET',undefined,users.other)).data.length,0);
 const payload={clientId:randomUUID(),body:'<img src=x onerror=alert(1)> hello'};const sent=await call('chat/rooms/'+room.id+'/messages','POST',payload,admin);A.equal(sent.status,201);A.equal((await call('chat/rooms/'+room.id+'/messages','POST',payload,admin)).data.seq,sent.data.seq);A.equal((await call('chat/rooms','GET',undefined,users.tech)).data[0].unread,1);
 A.equal((await call('chat/rooms/'+room.id+'/read','POST',{seq:sent.data.seq},users.tech)).status,200);A.equal((await call('chat/rooms','GET',undefined,users.tech)).data[0].unread,0);
 A.equal((await call('chat/rooms/'+room.id+'/messages','POST',{clientId:randomUUID(),body:' '},admin)).status,400);A.equal((await call('chat/rooms/'+room.id+'/messages','POST',{clientId:randomUUID(),body:'x'.repeat(5001)},admin)).status,400);
 const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
 const photo=await call('chat/rooms/'+room.id+'/messages','POST',{clientId:randomUUID(),body:'',image:png},users.tech);A.equal(photo.status,201);A.equal(photo.data.hasImage,true);A.equal(photo.data.image,undefined);A.equal((await call('chat/images/'+photo.data.seq,'GET',undefined,admin)).status,200);A.equal((await call('chat/images/'+photo.data.seq,'GET',undefined,users.other)).status,404);
 A.equal((await call('chat/rooms/'+room.id+'/messages','POST',{clientId:randomUUID(),body:'',image:'data:image/png;base64,'+Buffer.from('<script>bad</script>').toString('base64')},admin)).status,400);
 A.equal((await call('chat/rooms/'+room.id+'/messages','POST',{clientId:randomUUID(),body:'CSRF'},{...admin,csrf:'wrong'})).status,403);
 const group=(await call('chat/rooms','POST',{kind:'group',title:'Nhóm công việc',members:[users.tech.id,users.sales.id]},admin)).data;A.ok(group.id);A.equal((await call('chat/rooms/'+group.id+'/members','PUT',{title:'Bad',members:[admin.data.user.id,users.tech.id,users.other.id]},users.tech)).status,403);
 const gp=(await call('chat/rooms/'+group.id+'/messages','POST',{clientId:randomUUID(),body:'image',image:png},admin)).data;
 A.equal((await call('chat/rooms/'+group.id+'/members','PUT',{title:'Nhóm mới',members:[admin.data.user.id,users.sales.id,users.other.id]},admin)).status,200);A.equal((await call('chat/images/'+gp.seq,'GET',undefined,users.tech)).status,404);A.equal((await call('chat/rooms/'+group.id+'/messages','GET',undefined,users.tech)).status,404);A.equal((await call('chat/rooms/'+group.id+'/messages','POST',{clientId:randomUUID(),body:'not member'},users.tech)).status,404);
 A.equal((await call('chat/rooms/'+group.id+'/messages','GET',undefined,users.other)).data.items[0].body,'image');
 for(let i=0;i<65;i++)app.sql.prepare('INSERT INTO chat_messages(room,sender,client_id,body,at) VALUES(?,?,?,?,?)').run(group.id,admin.data.user.id,randomUUID(),'history '+i,'2020-01-01T00:00:00.000Z');
 const last=(await call('chat/rooms/'+group.id+'/messages','GET',undefined,admin)).data;A.equal(last.items.length,60);A.equal(last.more,true);const older=(await call('chat/rooms/'+group.id+'/messages?before='+last.items[0].seq,'GET',undefined,admin)).data;A.equal(older.items.length,6);A.equal(new Set([...older.items,...last.items].map(m=>m.seq)).size,66);
 const exported=(await call('backup','GET',undefined,admin)).data;A.ok(exported.chatRooms.some(r=>r.id===room.id));A.ok(exported.chatMessages.some(m=>m.seq===photo.data.seq&&m.image));
 const backup=await require('../server/backup.cjs').backupDatabase(databasePath,path.join(dir,'backups'));const copy=new(require('node:sqlite').DatabaseSync)(backup,{readOnly:true});A.equal(copy.prepare('SELECT mime FROM chat_messages WHERE seq=?').get(photo.data.seq).mime,'image/png');copy.close();
 await new Promise(r=>app.server.close(r));app=createApp({databasePath});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+app.server.address().port;A.equal((await call('chat/rooms/'+room.id+'/messages','GET',undefined,users.tech)).data.items.length,2);A.equal((await call('chat/images/'+photo.data.seq,'GET',undefined,users.tech)).status,200);
 await call('users/'+users.tech.id+'/disable','POST',{},admin);A.equal((await call('chat/rooms','GET',undefined,users.tech)).status,401);A.equal((await call('chat/rooms','POST',{kind:'direct',members:[users.tech.id]},users.other)).status,400);
});
