const {test}=require('node:test'),A=require('node:assert/strict'),C=require('../core.js'),P=require('../pricing-core.js'),F=require('../completion-core.js'),S=require('../source-core.js'),G=require('../server/catalog-guard.cjs');
const near=(a,b)=>A.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
test('completion: special sheet mass scales raw/purchased/recoverable kg together, not volume',()=>{const d=P.demoSeed();d.quote.remnantMode='all';d.quote.remnantSelections={};const before=P.calculate(d);for(const n of C.flatten(d.quote.products))if(n.spec?.shape==='sheet')n.spec.massOverride={value:C.materialMass(n.spec)*2,reason:'Bảng tra thử'};const r=P.calculate(d);A.deepEqual(r.errors,[]);near(r.total.weight,2*before.total.weight);near(r.groups[0].purchasedWeight,2*before.groups[0].purchasedWeight);near(r.nodes[d.quote.products[0].id].volume,before.nodes[d.quote.products[0].id].volume);for(let i=0;i<r.rows.length;i++)near(r.rows[i].purchasedWeight||0,2*(before.rows[i].purchasedWeight||0));A.ok(r.alternatives.kg.total.grand>before.alternatives.kg.total.grand);});
test('completion: bar kg/m formula, invalid override, profile changes produce distinct stock groups',()=>{const d=C.seed(),bars=C.flatten(d.quote.products).filter(n=>n.spec?.shape==='box');A.ok(bars.length);const m=bars[0].spec;m.massOverride={formula:'W / 10',reason:'Bảng tra'};near(C.materialMass(m),4);near(C.geometry(bars[0],1).weight,bars[0].dims.L/1000*4);A.throws(()=>C.materialMass({...m,massOverride:{value:3}}),/căn cứ/);A.throws(()=>C.materialMass({...m,massOverride:{formula:'L',reason:'x'}}));const r=P.legacyCalculate(d);A.ok(r.groups.filter(g=>g.shape==='box'||g.spec?.shape==='box').length>=2);});
test('completion: volume work and finishing norms multiply the hierarchy exactly once',()=>{const d=P.demoSeed(),p=d.quote.products[0];d.quote.remnantMode='all';d.quote.remnantSelections={};d.quote.ratesSnapshot.push({id:'vol',name:'Phủ theo thể tích',unit:'m³',inside:10000,outside:15000,consumptions:[{spec:d.materials.find(m=>m.id==='BM-SON'),basis:'m³',norm:2,layers:3,loss:5}]});p.ops=[{id:'vol',mode:'inside',amount:1}];const r=P.calculate(d),v=r.nodes[p.id].volume;A.deepEqual(r.errors,[]);near(r.nodes[p.id].ownOps[0].basis,v);near(r.nodes[p.id].ownOps[0].cost,v*10000);near(r.generated.find(x=>x.ownerId===p.id).quantity,v*2*3*1.05);});
test('completion: material price precedence and restore preserve new codes and quote snapshots',()=>{const d=P.demoSeed(),m=d.materials[0],original=C.copy(d.quote),baseline=F.priceSnapshot(d),book=[{substance:m.substance,grade:'',unit:m.unit,price:10},{substance:m.substance,grade:m.grade,unit:m.unit,price:20}];near(F.priceFor(m,book).value,20);near(F.priceFor({...m,grade:'OTHER'},book).value,10);near(F.priceFor({...m,unit:'tấm'},book).value,m.price);A.throws(()=>F.priceFor(m,[book[1],book[1]]),/trùng/);d.materials[0].price=99;d.materialPrices=book;d.materials.push({id:'NEW',price:777});F.restorePrices(d,baseline);near(d.materials[0].price,baseline.materials[0].price);A.equal(d.materials.at(-1).price,777);A.deepEqual(d.quote,original);A.deepEqual(d.materialPrices,[]);A.throws(()=>G.validateBook([{substance:'Thép',unit:'kg',price:-1}]));});
test('completion: safe catalog deletion covers saved quotes, templates and norm materials',()=>{const d=P.demoSeed(),m=d.quote.products[0].children[0].children[0].materialId;A.ok(F.references(d,'materials',m).length);A.throws(()=>F.removeCatalog(d,'materials',m),/Đang dùng/);d.materials.push({id:'UNUSED'});F.removeCatalog(d,'materials','UNUSED');A.ok(!d.materials.some(x=>x.id==='UNUSED'));const t=d.library[0],copy=C.cloneNode(t);A.equal(copy.templateId,t.id);A.notEqual(copy.id,t.id);const n=C.copy(d);n.materials=n.materials.filter(x=>x.id!==m);A.throws(()=>G.protect(d,n,[d]),/Không xóa/);const master=C.copy(d);master.materials=[];A.ok(G.candidates(master,[d,d]).every(x=>x.quotes.length===1));});
test('completion: commercial state requires actual sent confirmation, approved offer and valid calendar',()=>{const q={status:'approved',date:'2026-09-13',valid:7},opts={today:'2026-09-13',offerVersion:3},input={status:'sent',expectedVersion:0,reason:'Email đã gửi'};A.throws(()=>F.transition(q,{},input,'Sale',opts),/thực sự/);const sent=F.transition(q,{}, {...input,confirmedSent:true},'Sale',opts);A.equal(sent.version,1);A.equal(sent.events[0].offerVersion,3);A.equal(F.workflow(q,sent,'2026-09-21').status,'expired');A.throws(()=>F.transition(q,sent,{...input,status:'accepted'},'Sale',opts),/người khác/);A.throws(()=>F.transition(q,{}, {...input,confirmedSent:true,validUntil:'2026-02-31'},'Sale',opts),/không hợp lệ/);A.throws(()=>F.transition({...q,status:'draft'}, {}, {...input,confirmedSent:true},'Sale',opts),/đã duyệt/);let state=sent;for(const status of ['negotiating','accepted','negotiating','rejected','sent'])state=F.transition(q,state,{status,expectedVersion:state.version,confirmedSent:true,reason:'Trao đổi'},'Sale',opts);A.equal(state.events.length,6);});
test('completion: accent-insensitive customer/status/date filters compose without mutation',()=>{const rows=[{code:'BG-1',customer:'Trường Phát',date:'2026-09-13',commercialStatus:'sent'},{code:'BG-2',customer:'Khách khác',date:'2026-09-12',commercialStatus:'draft'}];A.equal(F.filterQuotes(rows,{search:'truong phat',status:'sent',from:'2026-09-13',to:'2026-09-13'}).length,1);A.equal(F.filterQuotes(rows,{search:'truong phat',status:'draft'}).length,0);A.equal(rows.length,2);});
test('completion: source mapping is exactly 38 columns, raw and kg-normalized values reconcile',()=>{const d=P.demoSeed(),r=P.calculate(d),rows=S.rows(d,r);A.equal(S.FIELDS.length,38);A.ok(rows.every(x=>x.values.length===38));near(rows.reduce((s,x)=>s+x.values[30],0),r.total.weight);A.equal(rows[0].values[0],1);A.equal(rows[0].values[15].split(' / ')[0],r.rows[0].spec.id);A.ok(S.FIELDS[35].includes('kg/m'));for(const row of S.analysis(r))for(let i=0;i<4;i++)if(row.values[i].perKg!==null)near(row.values[i].perKg*Object.values(r.alternatives)[i].total.weight,row.values[i].amount);});
test('completion: auxiliary allowance is explicit per raw row, TMC recomputes on its own stock',()=>{const d=P.demoSeed();d.quote.remnantMode='all';d.quote.remnantSelections={};const n=d.quote.products[0].children[0].children[0];n.auxiliaryPercent=3;const r=P.calculate(d);A.deepEqual(r.errors,[]);near(r.total.parts.allowance,r.rows.find(x=>x.id===n.id).cost*.03);near(r.alternatives.tmc.products[0].parts.allowance,r.alternatives.tmc.products[0].parts.stock*.03);const copy=C.copy(d);copy.quote.remnantMode='exclude';const raw=P.legacyCalculate(copy);for(const g of raw.groups)copy.quote.remnantSelections[g.signature]=g.remnants.map(x=>x.id);const r2=P.calculate(copy);A.deepEqual(r2.errors,[]);A.ok(r2.total.parts.allowance<r.total.parts.allowance);near(r2.reuse.chargeAll.parts.allowance,r.total.parts.allowance);});
test('completion: named conventions generate reference prices, keep snapshots and protect used values',()=>{const CV=require('../conventions-core'),d=P.demoSeed(),old=C.copy(d.quote);CV.save(d,'substances',{name:'Nhôm thử',density:2700,price:80000});A.ok(d.materialPrices.some(x=>x.substance==='Nhôm thử'&&x.price===80000));CV.save(d,'grades',{name:'A6061',parent:'Nhôm thử',price:90000});A.equal(F.priceFor({substance:'Nhôm thử',grade:'A6061',unit:'kg'},d.materialPrices).value,90000);A.deepEqual(d.quote,old);A.throws(()=>CV.remove(d,'substances','Thép'),/Đang dùng/);CV.save(d,'parameters',{name:'KHE',unit:'mm'});A.ok(CV.entries(d,'parameters').some(x=>x.name==='KHE'));A.throws(()=>CV.save(d,'parameters',{name:'BW'}),/không hợp lệ/);CV.remove(d,'parameters','KHE');A.ok(!CV.entries(d,'parameters').some(x=>x.name==='KHE'));});
test('completion: convention rename updates editable references without rewriting approved documents',()=>{const CV=require('../conventions-core'),d=P.demoSeed();d.savedQuotes=[{quote:{...C.copy(d.quote),id:'APPROVED',status:'approved'}}];const saved=C.copy(d.savedQuotes);CV.save(d,'substances',{name:'Thép mới',density:7900,price:21000},'Thép');A.equal(d.quote.products[0].children[0].children[0].spec.substance,'Thép mới');A.equal(d.quote.products[0].children[0].children[0].spec.density,7850);A.equal(d.materials.find(x=>x.id==='PH-T15').density,7900);A.deepEqual(d.savedQuotes,saved);});
test('completion: custom work units require an explicit quantity rather than inventing a conversion',()=>{const W=require('../work-core'),r={count:2,weight:10,area:4},rate={name:'Thử',unit:'ca máy',inside:500};A.throws(()=>W.operation(rate,{mode:'inside',amount:1},{},r,P.tier),/lượng công việc/);const x=W.operation(rate,{mode:'inside',basisMode:'manual_unit',workQuantity:3},{},r,P.tier);near(x.basis,6);near(x.cost,3000);});

test('completion: resend is explicit, preserves recipients and keeps past version expiry separate',()=>{
 const q={status:'approved',date:'2026-09-16',valid:15},opts={today:'2026-09-16',offerVersion:1},input={status:'sent',confirmedSent:true,expectedVersion:0,reason:'Gửi lần đầu',recipient:'Anh A',channel:'Zalo'};
 const one=F.transition(q,{},input,'Sale',opts);
 A.throws(()=>F.transition(q,one,{...input,expectedVersion:1},'Sale',opts),/đã được ghi nhận/);
 A.throws(()=>F.transition(q,one,{...input,expectedVersion:1,resend:true,confirmedSent:false},'Sale',opts),/thực sự/);
 const again=F.transition(q,one,{...input,expectedVersion:1,resend:true,reason:'Gửi lại bản cũ'},'Sale',opts);
 A.equal(again.events.length,2);A.equal(again.events[1].resend,true);A.equal(again.events[1].offerVersion,1);A.equal(again.events[1].recipient,'Anh A');A.equal(one.events.length,1);
 const nextQ={...q,date:'2026-10-01',valid:30},fresh=F.workflow(nextQ,again,'2026-10-01',2);
 A.equal(fresh.status,'draft');A.equal(fresh.validUntil,'2026-10-31');A.equal(fresh.events[0].validUntil,'2026-10-01');
 const second=F.transition(nextQ,again,{...input,expectedVersion:2},'Sale',{today:'2026-10-01',offerVersion:2});
 A.equal(second.events[2].offerVersion,2);A.equal(second.validUntil,'2026-10-31');A.equal(second.events[0].channel,'Zalo');
});

test('completion: returning to an older offer restores its own state and expiry without rewriting other events',()=>{
 const q1={status:'approved',date:'2026-09-16',valid:15},q2={...q1,valid:30},today='2026-09-16';
 const send={status:'sent',reason:'Sent QA',confirmedSent:true};
 let state=F.transition(q1,{}, {...send,expectedVersion:0},'Sale',{today,offerVersion:1});
 state=F.transition(q2,state,{...send,expectedVersion:1},'Sale',{today,offerVersion:2});
 const before=JSON.stringify(state.events),old=F.workflow(q1,state,today,1);
 A.equal(old.status,'sent');A.equal(old.validUntil,'2026-10-01');
 state=F.transition(q1,state,{status:'accepted',reason:'Customer chose V1',expectedVersion:2},'Sale',{today,offerVersion:1});
 A.equal(state.events.at(-1).offerVersion,1);A.equal(JSON.stringify(state.events.slice(0,2)),before);
 const latest=F.workflow(q2,state,today,2);A.equal(latest.status,'sent');A.equal(latest.validUntil,'2026-10-16');
 A.equal(F.workflow(q1,state,today,1).status,'accepted');
});
