'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),F=require('./cost-flow-fixture.cjs'),P=require('../pricing-core.js'),G=require('../group-pricing-core.js'),Flow=require('../cost-flow-core.js'),I=require('../input-prices-core.js'),C=require('../core.js'),D=require('../device-core.js');
test('component alternative builds independent cost, applies production/sales once, rounds once and totals VAT',()=>{const d=F.seed(),before=JSON.stringify(d),r=P.calculate(d),p=r.products[0];A.deepEqual(r.errors,[]);A.equal(p.direct,2310);A.equal(p.production,2541);A.equal(p.cost,2615);A.equal(p.unitSell,1569);A.equal(r.total.beforeTax,3138);A.equal(r.total.vat,251);A.equal(r.total.grand,3389);A.equal(p.costFlow.reduce((s,x)=>s+x.amount,0)+p.overhead,p.cost);A.equal(JSON.stringify(d),before);A.equal(P.calculate(JSON.parse(before)).total.grand,3389);A.notEqual(r.alternatives.detail.total.cost,r.total.cost);});
test('included delivery subtracts the duplicated charge and preserves other alternative/BOM',()=>{const d=F.seed(),bom=JSON.stringify(d.quote.products),detail=P.calculate(d).alternatives.detail.total;d.quote.pricing.productGroups[0].flow.rules.delivery={mode:'included',includedIn:'factory',reason:'Công gói đã gồm giao hàng'};const r=P.calculate(d);A.equal(r.products[0].cost,2595);A.equal(r.products[0].parts.delivery,0);A.deepEqual(r.alternatives.detail.total,detail);A.equal(JSON.stringify(d.quote.products),bom);});
test('bad rules, invalid inclusion targets, missing dimensions and out-of-family assignments block the alternative',()=>{const d=F.seed(),g=d.quote.pricing.productGroups[0];for(const rules of [{alien:{mode:'base'}},{factory:{mode:'formula',formula:'BAD',reason:'QA'}},{delivery:{mode:'included',includedIn:'delivery',reason:'QA'}},{factory:{mode:'none',reason:'QA'},delivery:{mode:'included',includedIn:'factory',reason:'QA'}}])A.throws(()=>G.validateGroup({...g,flow:{rules}}));
 g.flow.rules.factory={mode:'formula',formula:'Q * T',reason:'Thiếu T phải khai'};A.equal(P.calculate(d).alternatives['group:'+g.id].ready,false);g.flow.rules.factory.formula='-1';A.equal(P.calculate(d).alternatives['group:'+g.id].ready,false);g.flow.rules.factory.formula='Q';d.quote.products[0].productGroup='Lan can';A.equal(P.calculate(d).alternatives['group:'+g.id].ready,false);
 A.throws(()=>I.validateMaster({...P.defaults(),costFlows:{unknown:{rules:{}}}}));
});
test('package table and factors replace selected work once while keeping unbundled work and technical operations',()=>{
 const d=F.seed(),q=d.quote,g=q.pricing.productGroups[0],n=q.products[0];q.pricing.operationPriceTables=[{id:'cabinet-work',name:'Công tủ',productGroups:['Tủ điện'],lookupParam:'W',unit:'bộ',tiers:[{max:1000,price:100},{max:null,price:200}]}];
 q.ratesSnapshot.push({id:'pack-cabinet',name:'Gói tủ',operationType:'package',productGroups:['Tủ điện'],inside:0,outside:0,unit:'bộ',factors:[{id:'count',name:'Số lượng',param:'count',tiers:[{max:null,percent:10}]}],tmcPackage:{tableIds:['cabinet-work'],replaces:['cut']}});
 g.flow.rules.factory={mode:'package',rateId:'pack-cabinet',tableId:'cabinet-work',quantityFormula:'Q',reason:'Gói thay công cắt'};const bom=JSON.stringify(q.products),r=P.calculate(d),line=r.products[0].costFlow.find(x=>x.key==='factory');A.deepEqual(r.errors,[]);A.equal(line.calculation.replaced,140);A.ok(Math.abs(line.amount-220)<1e-8);A.equal(JSON.stringify(q.products),bom);
 n.children[0].ops.push({id:'bend',mode:'inside',amount:1,pricingMethod:'fixed',unitPrice:20,fixedScope:'total'});A.ok(Math.abs(P.calculate(d).products[0].costFlow.find(x=>x.key==='factory').amount-240)<1e-8);
 q.pricing.operationPriceTables[0].productGroups=['Lan can'];A.equal(P.calculate(d).alternatives['group:'+g.id].ready,false);
});
test('TMC explicitly adds declared device labour only when flow requests it, preserving legacy defaults',()=>{const d=require('./tmc-fixture.cjs').seed(),q=d.quote,p=q.products[0],device=C.copy(P.demoSeed().quote.products[0].children.find(n=>n.kind==='material'));device.id='device';device.qty=1;device.spec.price=100;p.children.push(device);q.deviceInstallations=[{id:'device-work',nodeId:device.id,variant:D.variant(device.spec),mode:'unit',rate:50,stage:'base',work:'Đấu nối',location:'Tủ',priceConfirmed:true,scopeConfirmed:true,reason:'Đấu nối riêng'}];const original=P.calculate(d);q.pricing.costFlows={tmc:{rules:{deviceInstallation:{mode:'detail'}}}};const r=P.calculate(d);A.equal(r.alternatives.tmc.total.cost-original.alternatives.tmc.total.cost,100);A.deepEqual(r.alternatives.detail.total,original.alternatives.detail.total);});
test('mixed quotation applies a component profile only to its assigned products and retains other products',()=>{const d=F.seed(),n=C.cloneNode(d.quote.products[0]);n.priceGroupId='detail';n.productGroup='Cơ khí';d.quote.products.push(n);const r=P.calculate(d);A.deepEqual(r.errors,[]);A.equal(r.products[0].cost,2615);A.equal(r.products[1].cost,r.alternatives.detail.products[1].cost);A.equal(r.products[1].sell,r.alternatives.detail.products[1].sell);});
test('loading master flow copies dependent rate and table; subsequent master edits do not change quote snapshot',()=>{const d=F.seed(),g=C.copy(d.quote.pricing.productGroups[0]);g.flow.rules.factory={mode:'package',rateId:'package',tableId:'table',quantityFormula:'Q',reason:'QA'};d.rates.push({id:'package',operationType:'package',name:'Công gói',tmcPackage:{tableIds:['table'],replaces:['cut']}});d.pricingDefaults={operationPriceTables:[{id:'table',name:'Bảng',unit:'bộ',lookupParam:'W',tiers:[{max:null,price:200}]}]};G.loadMaster(d,g);const saved=JSON.stringify(d.quote);d.pricingDefaults.operationPriceTables[0].tiers[0].price=900;A.equal(JSON.stringify(d.quote),saved);A.equal(d.quote.pricing.operationPriceTables[0].tiers[0].price,200);});
