'use strict';
const {chromium,expect}=require('@playwright/test'),{createApp}=require('../server/app.cjs'),fs=require('node:fs');
(async()=>{const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+app.server.address().port,browser=await chromium.launch({channel:'msedge',headless:true}),p=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[],dir='artifacts/customer-review/crm-2026-09-17';fs.mkdirSync(dir,{recursive:true});p.on('pageerror',e=>errors.push(e.message));const field=name=>p.locator('#dialog [name="'+name+'"]'),submit=async()=>{await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#dialog')).not.toBeVisible();};
try{
 await p.goto(url);await p.evaluate(async()=>{teamSession(await teamApi('setup','POST',{username:'admin',name:'Admin QA',password:'CRM-browser-local-tests-42!'}));await teamApi('users','POST',{username:'staff',name:'Staff QA',role:'estimator',password:'CRM-browser-local-tests-42!',sections:['customer']});render();});await p.locator('[data-page=customers]').click();await expect.poll(()=>p.evaluate(()=>Crm.owners.length)).toBe(2);
 await p.locator('[data-intake=customer]').first().click();await field('name').fill('CRM Company');await field('phone').fill('0901234567');await field('type').selectOption('company');await field('industry').fill('Construction');await field('notes').fill('Internal care note');await submit();const cid=await p.evaluate(()=>Intake.customers[0].id);
 await p.locator(`[data-crm=open][data-id="${cid}"]`).click();await expect(p.locator('.crm-profile')).toContainText('Admin QA');await p.locator('[data-crm=interaction]').click();await field('content').fill('Discussed cable trays and delivery schedule');await field('nextCareDate').fill('2026-01-01');await submit();await expect(p.locator('.crm-profile')).toContainText('Discussed cable trays');await expect(p.locator('.crm-profile')).toContainText('Quá hạn chăm sóc');
 await p.locator('[data-crm=opportunity]').first().click();await field('title').fill('Cable tray project QA');await field('stage').selectOption('qualifying');await field('value').fill('120000000');await field('description').fill('Tray width 300');await submit();await expect(p.locator('.crm-profile')).toContainText('Cable tray project QA');
 await p.locator('[data-crm=assign]').click();const staffId=await p.evaluate(()=>Crm.owners.find(o=>o.name==='Staff QA').id);await field('ownerId').selectOption(staffId);await field('reason').fill('New follow-up responsibility');await submit();await expect(p.locator('.crm-profile')).toContainText('Phụ trách: Staff QA');
 await p.locator('[data-crm=start-opportunity]').click();await expect(field('customer')).toHaveValue('CRM Company');await expect(field('project')).toHaveValue('Cable tray project QA');const opportunity=await field('opportunityId').inputValue();expect(opportunity).not.toBe('');await submit();expect(await p.evaluate(()=>db.quote.opportunityId)).toBe(opportunity);expect(await p.evaluate(()=>db.quote.customerInfo.notes)).toBeUndefined();expect(await p.evaluate(()=>db.quote.customerInfo.events)).toBeUndefined();
 await p.locator('[data-page=customers]').click();await p.locator(`[data-crm=open][data-id="${cid}"]`).click();await expect(p.locator('.crm-profile')).toContainText('Báo giá liên quan (1)');await p.locator('.crm-profile [data-intake=customer]').click();await field('rating').selectOption('vip');await field('ratingReason').fill('QA classification only');await field('phone').fill('0907654321');await submit();await expect(p.locator('.crm-profile')).toContainText('0907654321');expect(await p.evaluate(()=>db.quote.customerInfo.phone)).toBe('0901234567');
 await p.locator('[data-crm=policy]').click();await field('vipOrders').fill('5');await field('careDays').fill('7');await field('factor-vip').fill('-3');await submit();await p.locator('[data-crm=factor]').click();await submit();expect(await p.evaluate(()=>db.quote.pricing.customer)).toBe(-3);expect(await p.evaluate(()=>db.quote.pricing.customerFactorReview.customerId)).toBe(cid);await p.locator('[data-team=save]').first().click();await expect.poll(()=>p.evaluate(()=>Team.dirty)).toBe(false);
 await p.reload();await expect.poll(()=>p.evaluate(()=>Team.user?.username)).toBe('admin');await p.locator('[data-page=customers]').click();await p.locator(`[data-crm=open][data-id="${cid}"]`).click();await expect(p.locator('.crm-profile')).toContainText('Discussed cable trays');await expect(p.locator('.crm-profile')).toContainText('Phụ trách: Staff QA');await expect(p.locator('.crm-profile')).toContainText('Báo giá liên quan (1)');await p.screenshot({path:dir+'/profile.png',fullPage:true});
 await p.locator('[name=crm-filter-type]').selectOption('individual');await expect(p.locator(`[data-crm=open][data-id="${cid}"]`)).toHaveCount(0);await p.locator('[name=crm-filter-type]').selectOption('company');await expect(p.locator(`[data-crm=open][data-id="${cid}"]`)).toHaveCount(1);await p.setViewportSize({width:390,height:844});expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);expect(errors).toEqual([]);console.log('PASS CRM customer profile, interaction, opportunity -> quote, owner transfer, immutable contact snapshot, explicit factor application, reload and responsive filters');
}catch(e){await p.screenshot({path:dir+'/failure.png',fullPage:true});throw e;}finally{await browser.close();await new Promise(r=>app.server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
