const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),S=require('../customer-scoring-core.js');
test('server validates scoring permissions/version, history, persistent care inbox and resets',async t=>{const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port;async function call(path,method='GET',body,user){const r=await fetch(base+'/api/'+path,{method,headers:{'Content-Type':'application/json',...(user?{Cookie:user.cookie,'X-CSRF-Token':user.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};}
const admin=await call('setup','POST',{username:'admin',name:'Admin',password:'Customer-scoring-42!'}),staffBody={username:'staff',name:'Sales',password:'Customer-scoring-42!',role:'estimator',sections:['customer']};await call('users','POST',staffBody,admin);const staff=await call('login','POST',staffBody),scoring=S.config();scoring.enabled=true;scoring.criteria.forEach(c=>c.levels=[{label:'Đạt',score:100},{label:'Thấp',score:0}]);scoring.ranks=[{name:'C',min:0},{name:'A',min:80}];const policy={scoring,careLevels:{due:2,overdue:5,critical:10}};
A.equal((await call('intake/policy','POST',{policy,expectedVersion:0},staff)).status,403);A.equal((await call('intake/policy','POST',{policy,expectedVersion:0},admin)).status,200);
let c=(await call('intake/customers','POST',{customer:{id:'scoring-c',name:'Customer',ownerId:staff.data.user.id},expectedVersion:0},admin)).data;const answers=Object.fromEntries(S.CRITERIA.map(([id])=>[id,{level:'Đạt'}]));let r=await call('intake/customers/'+c.id+'/score','POST',{answers,reason:'Checked',policyVersion:0,expectedVersion:c.version},staff);A.equal(r.status,409);r=await call('intake/customers/'+c.id+'/score','POST',{answers,reason:'Checked',policyVersion:1,expectedVersion:c.version,total:0,rank:'Forged'},staff);A.equal(r.status,200,JSON.stringify(r.data));c=r.data;A.equal(c.scorecard.total,100);A.equal(c.scorecard.rank,'A');A.equal(c.scorecard.actor,'Sales');
await call('intake/policy','POST',{policy:{careDays:8},expectedVersion:1},admin);const saved=(await call('intake/policy','GET',undefined,admin)).data;A.equal(saved.scoring.enabled,true);A.equal(saved.careLevels.critical,10);const history=await call('intake/policy/history','GET',undefined,admin);A.equal(history.status,200,JSON.stringify(history.data));A.equal(history.data.length,2);A.equal((await call('intake/policy/history','GET',undefined,staff)).status,403);
c.createdAt=new Date(Date.now()-12*86400000).toISOString();app.sql.prepare('UPDATE intake_customers SET document=? WHERE id=?').run(JSON.stringify(c),c.id);const inbox=(await call('notifications','GET',undefined,staff)).data;A.equal(inbox.items.length,1);A.equal(inbox.items[0].stage,'customer-care');A.equal((await call('notifications','GET',undefined,staff)).data.items[0].id,inbox.items[0].id);A.equal((await call('notifications/'+inbox.items[0].id+'/read','POST',{},admin)).status,404);A.equal((await call('notifications/'+inbox.items[0].id+'/read','POST',{},staff)).status,200);A.equal((await call('notifications','GET',undefined,staff)).data.unread,0);A.equal((await call('notifications','GET',undefined,admin)).data.items.length,1);
c=(await call('intake/customers/'+c.id+'/interaction','POST',{expectedVersion:c.version,content:'Care today'},staff)).data;A.equal((await call('notifications','GET',undefined,staff)).data.items.length,0);A.equal(c.scorecard.total,100);A.equal((await call('backup','GET',undefined,admin)).data.customerCareNotices.length,2);
});
