const {test}=require('node:test'),A=require('node:assert/strict'),S=require('../customer-scoring-core.js'),CRM=require('../crm-core.js');
function policy(){const p=S.config();p.enabled=true;p.criteria.forEach(c=>c.levels=[{label:'Tốt',score:100},{label:'Thấp',score:0}]);p.ranks=[{name:'C',min:0},{name:'B',min:60},{name:'A',min:80}];return p;}
const answers=()=>Object.fromEntries(S.CRITERIA.map(([id])=>[id,{level:'Tốt',note:'Căn cứ'}]));
test('eight criteria validate weights, scales, ranks and weighted normalization',()=>{const p=policy();A.equal(S.config().enabled,false);A.deepEqual(S.careConfig(),{due:null,overdue:null,critical:null});let a=answers();A.equal(S.evaluate(p,a).total,100);a.revenue.level='Thấp';A.equal(S.evaluate(p,a).total,80);A.equal(S.evaluate(p,a).rank,'A');p.criteria[0].maxScore=5;p.criteria[0].levels[0].score=5;A.equal(S.evaluate(p,answers()).total,100);p.criteria[0].weight=19;A.throws(()=>S.config(p),/100/);p.criteria[0].weight=20;p.ranks[0].min=1;A.throws(()=>S.config(p),/0 điểm/);p.ranks[0].min=0;p.criteria[0].levels.push({label:'Tốt',score:1});A.throws(()=>S.config(p),/trùng/);A.throws(()=>S.evaluate(policy(),{}),/Chọn mức/);A.throws(()=>S.evaluate({},answers()),/Chưa cấu hình/);});
test('care boundaries follow configured VN calendar dates without assignment side effects',()=>{const c={createdAt:'2026-09-01T00:00:00+07:00',ownerId:'sales',status:'active'},p={careLevels:{due:8,overdue:15,critical:31}};for(const [d,level]of [[7,'normal'],[8,'due'],[14,'due'],[15,'overdue'],[30,'overdue'],[31,'critical']])A.equal(S.care(c,p,new Date(Date.parse(c.createdAt)+d*86400000).toISOString()).level,level);A.equal(S.care(c,{},'2026-09-20').level,'unconfigured');A.equal(S.care({...c,status:'inactive'},p,'2026-12-01').level,'inactive');A.equal(S.care({...c,events:[{kind:'interaction',occurredOn:'2026-09-20'}]},p,'2026-09-21').days,1);A.equal(c.ownerId,'sales');A.throws(()=>S.careConfig({due:10,overdue:5}));A.throws(()=>S.careConfig({critical:1.5}));});
test('scorecards are immutable snapshots preserved by profile edits, no implicit price/rating change',()=>{const p={scoring:policy(),version:2},c={id:'a',name:'A',rating:'regular'},next=CRM.update(c,'score',{policy:p,answers:answers(),reason:'Reviewed'}, {id:'admin',name:'Admin'});A.equal(next.scorecard.total,100);A.equal(next.rating,'regular');A.equal(next.events[0].result.policyVersion,2);p.scoring.criteria[0].weight=10;A.equal(next.scorecard.policy.criteria[0].weight,20);const saved=CRM.saveProfile(next,{id:'a',name:'B',rating:'regular'},{name:'Editor'});A.deepEqual(saved.scorecard,next.scorecard);A.equal(saved.events.length,2);A.throws(()=>CRM.update(c,'score',{policy:{scoring:policy()},answers:answers()},{name:'A'}),/căn cứ/);});
test('care includes actual offer contact on approved customer snapshots, not internal scheduling',()=>{const {DatabaseSync}=require('node:sqlite'),db=new DatabaseSync(':memory:');try{db.exec('CREATE TABLE commercial(id TEXT,document TEXT);CREATE TABLE revisions(id TEXT,version INTEGER,status TEXT,document TEXT)');db.prepare('INSERT INTO revisions VALUES(?,?,?,?)').run('q',1,'approved',JSON.stringify({quote:{customerInfo:{id:'a'}}}));db.prepare('INSERT INTO revisions VALUES(?,?,?,?)').run('q',2,'draft',JSON.stringify({quote:{customerInfo:{id:'b'}}}));db.prepare('INSERT INTO commercial VALUES(?,?)').run('q',JSON.stringify({dispatches:{1:{sentAt:'2026-09-01T00:00:00Z',entries:[{kind:'care',at:'2026-09-15T18:00:00Z'},{kind:'schedule',at:'2026-09-20T00:00:00Z'}]}}}));const map=require('../server/customer-care.cjs').offerCare(db);A.equal(map.get('a'),'2026-09-15T18:00:00Z');A.equal(map.has('b'),false);A.equal(S.care({createdAt:'2026-09-01',lastOfferCare:map.get('a')},{careLevels:{due:3}},'2026-09-18T00:00:00Z').days,2);}finally{db.close();}});

test('numeric score thresholds have explicit units/period, exact boundaries and frozen evidence',()=>{const p=policy(),c=p.criteria[0];c.unit='triệu đồng';c.period='Năm đánh giá';c.levels=[{label:'Dưới 300',min:0,score:0},{label:'Từ 300',min:300,score:60},{label:'Từ 500',min:500,score:70},{label:'Từ 1000',min:1000,score:80}];for(const [value,score]of [[299,0],[300,60],[499,60],[500,70],[1000,80]]){const a=answers();a.revenue={value,note:'Đã đối chiếu'};const row=S.evaluate(p,a).rows[0];A.equal(row.score,score);A.equal(row.weighted,score*.2);A.equal(row.value,value);A.equal(row.unit,'triệu đồng');}const a=answers();a.revenue={value:''};A.throws(()=>S.evaluate(p,a),/Số liệu/);delete c.period;A.throws(()=>S.config(p),/kỳ đánh giá/);c.period='Năm';c.levels[1].min=0;A.throws(()=>S.config(p),/trùng/);});
