const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs');
test('customer identity enforced on create/update/concurrent writes and import, with self edits allowed',async t=>{const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>{app.server.closeAllConnections();return new Promise(r=>app.server.close(r));});const base='http://127.0.0.1:'+app.server.address().port;let session;
async function call(route,body){const r=await fetch(base+'/api/'+route,{method:'POST',headers:{'Content-Type':'application/json',...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{})},body:JSON.stringify(body)});const data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};}
session=await call('setup',{username:'admin',name:'Admin',password:'Duplicate-customer-42!'});const save=(c,v=0)=>call('intake/customers',{customer:c,expectedVersion:v});
const c={id:'original',name:'Công ty Vivian',taxId:'0311790858',account:{code:'KH-001'}};A.equal((await save(c)).status,200);A.equal((await save({...c,id:'dupe',taxId:'031 179 0858'})).status,409);A.equal((await save({...c,id:'dupe2',taxId:'',name:' CONG TY VIVIAN '})).status,409);A.equal((await save({id:'code-dupe',name:'Different',account:{code:'kh 001'}})).status,409);A.equal((await save({...c,phone:'123'},1)).status,200);
A.equal((await save({id:'branch',name:c.name,taxId:'0311790858-001'})).status,200);A.equal((await save({id:'branch',taxId:c.taxId,name:'Branch'},1)).status,409);
const results=await Promise.all(Array.from({length:8},(_,i)=>save({id:'race-'+i,name:'Concurrent',taxId:'8888888888'})));A.equal(results.filter(r=>r.status===200).length,1);A.equal(results.filter(r=>r.status===409).length,7);
const before=app.sql.prepare('SELECT count(*) n FROM intake_customers').get().n;const r=await call('intake/customers/import',{rows:[{line:1,customer:{name:'Import OK',taxId:'111'},expectedVersion:0},{line:2,customer:{name:'Import OK',taxId:'111'},expectedVersion:0}]});A.equal(r.status,400);A.equal(app.sql.prepare('SELECT count(*) n FROM intake_customers').get().n,before);
});
