const {test}=require('node:test'),A=require('node:assert/strict'),I=require('../customer-import-core.js'),{createApp}=require('../server/app.cjs');
test('Customer import recognizes template headers, preserves identifiers and rejects ambiguous matches',()=>{
 const parsed=I.records([['Thông tin khách hàng'],['Mã khách hàng','Tên khách hàng','Điện thoại','Ngày cấp'],['KH01','ABC','001234','18/09/2026']]);A.equal(parsed.rows[0].data.phone,'001234');A.equal(parsed.rows[0].data.account.identityDate,'2026-09-18');
 const old=[{id:'one',name:'ABC',account:{code:'KH01'},version:2},{id:'two',name:'Other',taxId:'123',version:1}];A.equal(I.plan(parsed.rows,old)[0].expectedVersion,2);A.match(I.plan([{line:1,data:{name:'ABC',account:{code:'KH01'},taxId:'123'}}],old)[0].error,/khác nhau/);A.match(I.plan([{line:1,data:{name:'ABC'}}],old)[0].error,/Tên đã tồn tại/);
 A.match(I.plan([{line:1,data:{name:'A',account:{code:'A'},taxId:'123'}},{line:2,data:{name:'B',account:{code:'B'},taxId:'123'}}],[])[1].error,/lặp/);
});
test('Customer import is atomic, version checked, preserves history, ownership and absent fields',async t=>{
 const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port;
 async function call(route,method='GET',body,session){const r=await fetch(base+'/api/'+route,{method,headers:{'Content-Type':'application/json',...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};}
 const admin=await call('setup','POST',{username:'admin',name:'Admin',password:'Import-test-password-42!'}),old=(await call('intake/customers','POST',{customer:{id:'old',name:'Old',phone:'00123',account:{code:'C01',bankAccount:'00077'}},expectedVersion:0},admin)).data;
 const rows=[{customer:{id:'old',name:'Updated'},expectedVersion:1},{customer:{name:'New',account:{code:'C02'}},expectedVersion:0}];let r=await call('intake/customers/import','POST',{rows},admin);A.equal(r.status,200,JSON.stringify(r.data));let list=(await call('intake/customers','GET',undefined,admin)).data;A.equal(list.length,2);let updated=list.find(c=>c.id==='old');A.equal(updated.phone,'00123');A.equal(updated.account.bankAccount,'00077');A.equal(updated.ownerId,old.ownerId);A.ok(updated.events.length>old.events.length);
 A.equal((await call('intake/customers/import','POST',{rows},admin)).status,409);
 const before=JSON.stringify((await call('intake/customers','GET',undefined,admin)).data);r=await call('intake/customers/import','POST',{rows:[{customer:{id:'old',name:'Must rollback'},expectedVersion:2},{customer:{name:'Bad',email:'invalid'},expectedVersion:0}]},admin);A.equal(r.status,400);A.equal(JSON.stringify((await call('intake/customers','GET',undefined,admin)).data),before);
 await call('users','POST',{username:'reader',name:'Reader',password:'Import-test-password-42!',role:'approver',sections:[]},admin);const reader=await call('login','POST',{username:'reader',password:'Import-test-password-42!'});A.equal((await call('intake/customers/import','POST',{rows},reader)).status,403);
});
