'use strict';
const {chromium,expect}=require('@playwright/test'),{createApp}=require('../server/app.cjs');
(async()=>{const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const b=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:'+app.server.address().port);await p.waitForFunction(()=>Team.available);await p.evaluate(async()=>{teamSession(await teamApi('setup','POST',{username:'admin',name:'Admin',password:'Dashboard-browser-2026!'}));await dashboardOpen();});
 await expect(p.locator('.dashboard-cards article')).toHaveCount(6);await expect(p.locator('.dashboard-chart').first().locator('li')).toHaveCount(12);await expect(p.locator('.dashboard-steps button')).toHaveCount(10);
 for(const width of [1440,1024,768,390,360]){await p.setViewportSize({width,height:900});expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+2)).toBe(true);await p.screenshot({path:'artifacts/gd2-audit/dashboard-'+width+'.png'});}
 await p.locator('[data-dashboard=orders]').click();await expect(p.locator('#orders-console')).toBeVisible();await p.evaluate(()=>document.querySelector('#orders-console').close());await p.locator('[data-dashboard=reports]').click();await expect(p.locator('#content h1')).toHaveText('Trung tâm báo cáo');await p.locator('#sidebar [data-erp=overview]').evaluate(el=>el.click());await expect(p.locator('.dashboard-cards article')).toHaveCount(6);
 await p.route('**/api/dashboard',r=>r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Không thể tải số liệu kiểm tra'})}));await p.locator('[data-dashboard=refresh]').click();await expect(p.locator('#content [role=alert]')).toContainText('Không thể tải');await expect(p.locator('.dashboard-cards')).toHaveCount(0);await p.unroute('**/api/dashboard');await p.locator('[data-dashboard=refresh]').click();await expect(p.locator('.dashboard-cards article')).toHaveCount(6);expect(errors).toEqual([]);console.log('PASS dashboard sources, navigation, failed-load recovery, five responsive widths');
 }finally{await b.close();await new Promise(r=>app.server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
