'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),F=require('../completion-core.js'),P=require('../pricing-core.js');
test('dashboard reconciles current sources, zero-fills 12 months and enforces each source permission',async t=>{
 const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));let admin;
 const call=async(path,method='GET',body,session=admin)=>{const r=await fetch('http://127.0.0.1:'+app.server.address().port+'/api/'+path,{method,headers:{'Content-Type':'application/json',Cookie:session?.cookie||'','X-CSRF-Token':session?.csrf||''},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};};
 A.equal((await call('dashboard')).status,401);admin=await call('setup','POST',{username:'admin',name:'Admin',password:'Dashboard-test-2026!'});
 const today=F.todayVN(),put=(table,kind,id,doc)=>app.sql.prepare('INSERT INTO '+table+' VALUES(?,?,?,?)').run(kind,id,1,JSON.stringify(doc));
 const doc=P.demoSeed(),q=(await call('quotes','POST',{document:doc})).data;await call('quotes/'+q.id+'/submit','POST',{expectedVersion:1});await call('quotes/'+q.id+'/approve','POST',{expectedVersion:2});const order=(await call('quotes/'+q.id+'/order','POST',{expectedVersion:3,code:'DH-DASHBOARD'})).data;
 await call('orders/'+order.id+'/confirm','POST',{quoteVersion:3});const job=(await call('production','POST',{orderId:order.id,productId:doc.quote.products[0].id,quantity:1,code:'LSX-DASHBOARD'})).data;A.ok(job.id,JSON.stringify(job));
 const progress={...job.progress,deadline:'2020-01-01'};app.sql.prepare('UPDATE production_jobs SET state=?,progress=? WHERE id=?').run('running',JSON.stringify(progress),job.id);
 put('business_records','order',order.id,{deliveredAt:today,deliveryDate:today});put('business_records','contract','contract',{code:'HD-DASHBOARD',status:'active',startDate:'2020-01-01',endDate:today,value:1000});put('business_records','payment','payment',{contractId:'contract',date:today,amount:200});put('business_records','payment','void',{contractId:'contract',date:today,amount:700,voidedAt:today});
 put('ops_records','material','m',{name:'STEEL-DASHBOARD',unit:'kg',minimum:2,active:true});put('ops_records','purchase','purchase',{code:'PO-DASHBOARD',state:'pending',created:today});
 for(let i=0;i<12;i++)app.sql.prepare('INSERT INTO audit(at,user_id,action,entity,detail) VALUES(?,?,?,?,?)').run(new Date().toISOString(),admin.data.user.id,'private-test','private-entity','SECRET-NOT-FOR-DASHBOARD');
 let out=await call('dashboard');A.equal(out.status,200);const d=out.data;A.equal(d.cards.length,6);A.equal(d.cards[0].value,order.package.offer.totals.beforeTax);A.equal(d.cards[1].value,1);A.equal(d.cards[2].value,1);A.equal(d.cards[3].value,1);A.equal(d.cards[5].value,800);A.equal(d.months.length,12);A.equal(d.months[11].label,today.slice(0,7));A.equal(d.months.filter(m=>m.value!==0).length,1);A.equal(d.orderStates.find(s=>s.label==='Đã giao').value,1);A.equal(d.stages.reduce((s,r)=>s+r.value,0),1);for(const a of d.alerts)A.equal(a.count,1,a.type);A.equal(d.activity.length,10);A.ok(!JSON.stringify(d).includes('SECRET-NOT'));A.ok(!JSON.stringify(d).includes('private-entity'));
 const user=async(name,grants)=>{const u=(await call('users','POST',{username:name,name,role:'sales',password:'Dashboard-test-2026!'})).data;app.sql.prepare('UPDATE users SET action_access=? WHERE id=?').run(JSON.stringify(grants),u.id);return call('login','POST',{username:name,password:'Dashboard-test-2026!'});};
 const store=await user('store',{reports:['view'],inventory:['view']});out=await call('dashboard','GET',undefined,store);A.equal(out.status,200);A.ok(out.data.cards.every(c=>c.value===null));A.equal(out.data.alerts.length,1);A.equal(out.data.alerts[0].type,'low');A.equal(out.data.activity,null);A.equal(out.data.months.length,0);A.equal(out.data.orderStates.length,0);A.equal(out.data.stages.length,0);A.ok(!JSON.stringify(out.data).includes('DH-DASHBOARD'));
 const denied=await user('denied',{inventory:['view']});A.equal((await call('dashboard','GET',undefined,denied)).status,403);A.equal((await call('dashboard','POST',{})).status,405);
});
