'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),C=require('../core.js'),P=require('../pricing-core.js'),W=require('../work-core.js'),D=require('../definition-core.js'),CV=require('../conventions-core.js'),R=require('../declaration-review-core.js'),Cost=require('../cost-input-core.js');
const near=(a,b)=>A.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
const option=(extra={})=>({id:'opt-kg',name:'Theo kg',method:'catalog',inside:2000,outside:3000,insideUnit:'kg',outsideUnit:'kg',fixedScope:'total',enabled:true,...extra});
function setup(){const db=P.demoSeed(),rate=db.quote.ratesSnapshot.find(r=>r.id==='cut'),n=db.quote.products[0].children[0],other=db.quote.products[1].children[0];rate.priceOptions=[option(),option({id:'opt-area',name:'Theo m²',insideUnit:'m²',outsideUnit:'m²',inside:4000,outside:6000}),option({id:'opt-ton',name:'Theo tấn',insideUnit:'tấn',outsideUnit:'tấn',inside:2000000,outside:3000000}),option({id:'opt-item',name:'Theo cái',insideUnit:'cái',outsideUnit:'cái',inside:10000,outside:15000}),option({id:'opt-package',name:'Trọn gói',method:'fixed',inside:500000,outside:700000})];return {db,rate,n,other};}
test('review: each price option uses its own rate, unit and quantity; unrelated operations remain unchanged',()=>{const {db,n}=setup(),before=P.calculate(db).nodes[n.id].ownOps[1].cost;for(const [id,cost,unit]of [['opt-kg',188400,'kg'],['opt-area',64000,'m²'],['opt-ton',188400,'tấn'],['opt-item',100000,'cái'],['opt-package',500000,'gói']]){W.setPriceOption(db.quote,'cut',id);const r=P.calculate(db);near(r.nodes[n.id].ownOps[0].cost,cost);A.equal(r.nodes[n.id].ownOps[0].unit,unit);near(r.nodes[n.id].ownOps[1].cost,before);}n.ops[0].mode='outside';near(P.calculate(db).nodes[n.id].ownOps[0].cost,700000);});
test('review: shared method, separate quantities and complexity; multiplier is applied once',()=>{const {db,rate,n,other}=setup();rate.factors.push({id:'complexity',name:'Độ khó',param:'complexity',kind:'category',categories:[{key:'Khó',percent:50}]});n.complexity=other.complexity='Khó';rate.priceOptions.push(option({id:'opt-factor',name:'Theo hệ số',method:'factors',inside:1000}));W.setPriceOption(db.quote,'cut','opt-factor');const before=P.calculate(db),otherCost=before.nodes[other.id].ownOps[0].cost;n.ops[0].complexity={label:'Đánh giá trực tiếp',multiplier:1.2};const r=P.calculate(db);near(r.nodes[n.id].ownOps[0].rate,1254);near(r.nodes[other.id].ownOps[0].cost,otherCost);A.equal(r.nodes[n.id].ownOps[0].factors.filter(f=>f.param==='complexity').length,1);A.equal(W.optionFor(other.ops[0],db.quote),'opt-factor');});
test('review: choosing a direct method clears the price option, without losing complexity or changing base prices',()=>{const {db,n,rate}=setup();W.setPriceOption(db.quote,'cut','opt-kg');W.setMethod(db.quote,'cut','direct');for(const node of C.flatten(db.quote.products))for(const op of node.ops||[])if(op.id==='cut')Object.assign(op,{unitPrice:10000,priceUnit:'kg'});n.ops[0].complexity={label:'Khó',multiplier:1.5};near(P.calculate(db).nodes[n.id].ownOps[0].cost,1413000);A.equal(W.optionFor(n.ops[0],db.quote),'');A.equal(rate.inside,1000);});
test('review: a declared package has a precise total or per-unit scope, including quantities and complexity',()=>{const {db,n,rate}=setup();rate.priceOptions.find(x=>x.id==='opt-package').fixedScope='unit';W.setPriceOption(db.quote,'cut','opt-package');n.ops[0].complexity={label:'Thử',multiplier:1.2};near(P.calculate(db).nodes[n.id].ownOps[0].cost,6000000);});
test('review: missing or disabled selected options report errors instead of falling back to another price',()=>{const {db,rate,n}=setup();W.setPriceOption(db.quote,'cut','opt-area');rate.priceOptions=rate.priceOptions.filter(x=>x.id!=='opt-area');A.match(P.calculate(db).nodes[n.id].ownOps[0].error,/không còn khả dụng/);rate.priceOptions.push(option({id:'opt-area',enabled:false}));A.throws(()=>W.setPriceOption(db.quote,'cut','opt-area'));A.match(P.calculate(db).nodes[n.id].ownOps[0].error,/không còn khả dụng/);});
test('review: price-option data and complexity reject malformed, empty and negative values',()=>{for(const extra of [{inside:-1},{inside:null},{inside:''},{outside:NaN},{insideUnit:''},{method:'unknown'},{fixedScope:'bad',method:'fixed'},{id:'__proto__'},{enabled:'false'}])A.throws(()=>W.validatePriceOptions({priceOptions:[option(extra)]}));A.throws(()=>W.validatePriceOptions({priceOptions:[option(),option()]}));for(const x of [{label:'',multiplier:1},{label:'Thử',multiplier:0},{label:'Thử',multiplier:-1},{label:'Thử',multiplier:null},{label:'Thử',multiplier:'oops'}])A.throws(()=>W.validateComplexity(x));});
test('review: catalogue edits preserve the quoted option snapshot; serialization preserves the selected calculation',()=>{const {db,n}=setup();db.rates.find(r=>r.id==='cut').priceOptions=C.copy(db.quote.ratesSnapshot.find(r=>r.id==='cut').priceOptions);W.setPriceOption(db.quote,'cut','opt-area');const before=C.copy(db.quote);db.rates.find(r=>r.id==='cut').priceOptions[1].inside=999999;A.deepEqual(db.quote,before);const reloaded=JSON.parse(JSON.stringify(db));near(P.calculate(reloaded).nodes[n.id].ownOps[0].cost,64000);});
test('review: restoring input prices keeps newly declared methods and restores only prior monetary fields',()=>{const {db}=setup(),Complete=require('../completion-core.js'),r=db.rates.find(x=>x.id==='cut');r.priceOptions=[option()];const baseline=Complete.priceSnapshot(db);r.priceOptions[0].inside=9000;r.priceOptions[0].name='Tên đã sửa';r.priceOptions.push(option({id:'opt-new',name:'Cách mới',inside:123}));Complete.restorePrices(db,baseline);A.equal(r.priceOptions[0].inside,2000);A.equal(r.priceOptions[0].name,'Tên đã sửa');A.equal(r.priceOptions[1].inside,123);});
test('review: selected option prices appear in source confirmation and changing a source changes the actual calculation',()=>{const {db,n}=setup();W.setPriceOption(db.quote,'cut','opt-area');const rows=Cost.rows(db.quote),row=rows.find(x=>x.key==='rate-option:cut:opt-area:inside');A.equal(row.value,4000);A.equal(row.unit,'m²');A.ok(!rows.some(x=>x.key==='rate:cut:inside'));Cost.apply(db.quote,[{key:row.key,original:4400,status:'included',rate:10}],'Nguồn thử');near(P.calculate(db).nodes[n.id].ownOps[0].cost,64000);A.equal(Cost.state(db.quote,Cost.rows(db.quote).find(x=>x.key===row.key)).known,true);W.setPriceOption(db.quote,'cut','opt-kg');A.ok(!Cost.rows(db.quote).some(x=>x.key===row.key));});
test('review: every option and every factor tier is checked without mutating the catalogue',()=>{const {rate}=setup(),before=JSON.stringify(rate),report=R.rate(rate,P.tier);A.equal(report.ok,true,JSON.stringify(report.checks.filter(x=>!x.ok)));A.equal(report.samples.length,14);A.equal(JSON.stringify(rate),before);rate.priceOptions[3].outside=-1;A.equal(R.rate(rate,P.tier).ok,false);rate.priceOptions[3].outside=2000;rate.factors[0].tiers[1].max=1;A.equal(R.rate(rate,P.tier).ok,false);});
test('review: parameter names are independent of symbols, preserved through save and available to formula editors',()=>{const {db}=setup();const q=JSON.stringify(db.quote);CV.save(db,'parameters',{name:'GAP',label:'Khoảng hở lắp ghép',unit:'mm'});A.equal(CV.parameterName(db,'GAP'),'Khoảng hở lắp ghép');A.equal(CV.parameterName(db,'L'),'Chiều dài');A.equal(JSON.stringify(db.quote),q);A.equal(R.convention(db,'parameters',CV.entries(db,'parameters').find(x=>x.name==='GAP')).ok,true);A.throws(()=>CV.save(db,'parameters',{name:'GAP',label:'',unit:'mm'},'GAP'));});
test('review: shape check covers names, dimensions, mass, area and purchased stock with unchanged data',()=>{const {db}=setup(),d={id:'TRIANGLE',name:'Tam giác thử',base:'sheet',fields:[{key:'L',name:'Chiều dài',unit:'mm',mode:'input',sample:1000},{key:'W',name:'Chiều rộng',unit:'mm',mode:'input',sample:200},{key:'T',name:'Chiều dày',unit:'mm',mode:'fixed',sample:2}],length:'L',width:'W',mass:'T/1000*RHO',surface:'1',blankMass:'PHOI_D*PHOI_R/2000000*KL_DV',blankSurface:'PHOI_D*PHOI_R/2000000'};const before=JSON.stringify(d),report=R.shape(d,db,undefined,7850,{length:1000,width:1000});A.equal(report.ok,true);near(report.geometry.weight,1.57);near(report.geometry.blankArea,.1);A.equal(JSON.stringify(d),before);d.blankMass='L';A.equal(R.shape(d,db).ok,false);d.blankMass='PHOI_D*PHOI_R/2000000*KL_DV';d.length='L/0';A.equal(R.shape(d,db).ok,false);});
