'use strict';
const {chromium,expect}=require('@playwright/test'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const url=process.env.BATCH_ONE_URL||pathToFileURL(path.resolve('dist/index.html')).href;
const dir=path.resolve(process.env.DEFINITION_ARTIFACT_ROOT||'artifacts/customer-review/batch-01-complete-2026-09-14',url.startsWith('https:')?'live':'local');fs.mkdirSync(dir,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true}),p=await browser.newPage({viewport:{width:1560,height:1080}}),errors=[],checks=[],screens=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(10000);
const click=a=>p.locator(`[data-definition="${a}"]`).first().click(),submit=async()=>{await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#dialog')).not.toBeVisible();},shot=async n=>{await p.screenshot({path:path.join(dir,n+'.png'),fullPage:true});screens.push(n+'.png');},pass=s=>{checks.push(s);console.log('PASS '+s);},tab=async n=>{await p.locator(`[data-tab="${n}"]`).click();};
try{
  await p.goto(url);await p.locator('[data-page=rules]').click();await click('shape-new');await p.locator('[name=id]').fill('QD-LIVE-TEST');await p.locator('[name=name]').fill('Thép hình kiểm thử — không phải bảng thật');await expect(p.locator('#definition-preview')).toContainText('20 kg');await expect(p.locator('#definition-preview')).toContainText('60 kg');await p.locator('[name=mass]').fill('L');await expect(p.locator('#definition-preview')).toContainText('sai đơn vị');await p.locator('[name=mass]').fill('KM / (1-1)');await expect(p.locator('#definition-preview')).toContainText('chia cho 0');await p.locator('[name=mass]').fill('KM');await p.locator('[name=condition]').fill('Chỉ áp dụng theo bảng tra giả lập đã kiểm');await p.locator('#definition-preview').scrollIntoViewIfNeeded();await shot('01-quy-uoc-thu-cong-thuc');await submit();
  await click('shape-material');await p.locator('[name=id]').fill('VT-SCHEMA-TEST');await p.locator('[name=price]').fill('20000');await submit();await p.locator('[data-page=materials]').click();await expect(p.locator('#content')).toContainText('VT-SCHEMA-TEST');await p.locator('[data-action=edit-material][data-id=VT-SCHEMA-TEST]').click();await expect(p.locator('[name=KM]')).toHaveValue('10');await expect(p.locator('[name=KM]').locator('..')).toContainText('kg/m');await submit();pass('DM-02: declare fixed/input fields, real unit/zero checks, matching preview and material catalogue');
  await click('stocks');await click('stock-new');await p.locator('[name=id]').fill('KHO-LIVE-TEST');await p.locator('[name=name]').fill('Thanh chuẩn kiểm thử 12m');await p.locator('[name=length]').fill('12000');await p.locator('[name=workshop]').fill('Xưởng thử');await p.locator('[name=machine]').fill('Máy cưa thử');await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#dialog')).toContainText('Thanh chuẩn kiểm thử 12m');await shot('02-kho-chuan-theo-may-xuong');await p.locator('#dialog .dialog-head [data-action=close]').click();
  await p.locator('[data-page=quote]').click();await p.locator('[data-work=new-quote]').first().click();await p.locator('[name=id]').fill('BG-SCHEMA-TEST');await p.locator('[name=customer]').fill('Khách kiểm thử quy ước');await p.locator('[name=customer]').blur();await submit();await tab('bom');await p.locator('[data-action=add-product]').first().click();await p.locator('[name=template]').selectOption('');await p.locator('[name=name]').fill('Sản phẩm từ dòng nháp');await submit();const sp=await p.evaluate(()=>db.quote.products[0].id);
  await p.locator(`[data-action=add-material][data-parent="${sp}"]`).click();await click('draft');await p.locator('[name=name]').fill('Dòng chờ chọn mã');await p.locator('[name=qty]').fill('3');await submit();await p.reload();await tab('bom');await expect(p.locator('#content')).toContainText('Chưa có giá');const id=await p.evaluate(()=>db.quote.products[0].children[0].id);const before=await p.evaluate(()=>TPBatchOne.treeRows(db.quote.products).map(r=>({id:r.id,parentId:r.parentId,type:r.type,count:r.count})));await expect(p.locator('[data-quick-grand]')).toContainText('Chưa đủ dữ liệu');await expect(p.locator('[data-unit-sell]')).toContainText('Chưa đủ dữ liệu');await shot('03-dong-nhap-canh-bao');
  for(const name of ['operations','waste','mass','prices']){await tab(name);expect(await p.locator(`[data-b1-tree="${name}"] [data-b1-node]`).evaluateAll(es=>es.map(e=>e.dataset.b1Node))).toEqual(before.map(r=>r.id));}
  expect(await p.evaluate(()=>result.errors.some(e=>e.includes('chưa chọn mã')))).toBe(true);await tab('preview');await expect(p.locator('#content')).toContainText(/kiểm tra|chưa đủ|chưa thể|chưa hợp lệ|Chưa chọn/i);await tab('bom');await p.locator(`[data-action=swap-material][data-id="${id}"]`).click();await p.locator('[name=material]').selectOption('VT-SCHEMA-TEST');await submit();expect(await p.evaluate(()=>TPBatchOne.treeRows(db.quote.products).map(r=>({id:r.id,parentId:r.parentId,type:r.type,count:r.count})))).toEqual(before);expect(await p.evaluate(()=>result.rows[0].geometry.weight)).toBe(60);expect(await p.evaluate(()=>result.rows[0].geometry.blankArea)).toBe(3);pass('DM-04: draft survives reload/five tabs, blocks valid price, assigning preserves row identity and quantity');
  await tab('mass');await p.locator(`[data-batch-one=inspect][data-id="${id}"]`).click().catch(async()=>{await p.evaluate(id=>{selected=id;tab='bom';UX.mode='detail';render();},id);});await click('dimensions');await expect(p.locator('#definition-dim-preview')).toContainText('20 kg');await expect(p.locator('#definition-dim-preview')).toContainText('60 kg');await shot('04-thong-so-va-ket-qua-trong-don');await p.locator('[name=L]').fill('1000');await submit();expect(await p.evaluate(()=>result.rows[0].geometry.weight)).toBe(30);
  await tab('waste');await p.locator(`[data-batch-one=stock][data-id="${id}"]`).click();await p.locator('[name=sharedStock]').selectOption('KHO-LIVE-TEST');await expect(p.locator('[name=stockL]')).toHaveValue('12000');await submit();await p.reload();expect(await p.evaluate(()=>db.quote.products[0].children[0].spec.stockL)).toBe(12000);expect(await p.evaluate(()=>db.materials.find(m=>m.id==='VT-SCHEMA-TEST').stockL)).toBe(6000);expect(await p.evaluate(()=>result.rows[0].purchasedWeight)).toBe(120);expect(await p.evaluate(()=>result.rows[0].purchasedArea)).toBe(6);await tab('waste');await shot('05-kho-chung-khong-doi-quy-cach');pass('DM-03: select shared machine/workshop stock, reload keeps snapshot, catalogue unchanged, purchased kg/area correct');
  await p.locator(`[data-batch-one=stock][data-id="${id}"]`).click();await p.locator('[name=stockL]').fill('9000');await submit();expect(await p.evaluate(()=>db.quote.products[0].children[0].spec.stockSource)).toEqual({name:'Khổ đặt riêng',length:9000,width:0});await p.locator(`[data-batch-one=stock][data-id="${id}"]`).click();await p.locator('[name=sharedStock]').selectOption('KHO-LIVE-TEST');await submit();expect(await p.evaluate(()=>db.quote.products[0].children[0].spec.stockSource.id)).toBe('KHO-LIVE-TEST');
  await p.locator('[data-page=rules]').click();await click('shape-edit');await p.locator('[name=mass]').fill('KM*2');await submit();expect(await p.evaluate(()=>db.shapeDefinitions.find(d=>d.id==='QD-LIVE-TEST').version)).toBe(2);await p.locator('[data-page=quote]').click();await tab('mass');expect(await p.evaluate(()=>result.rows[0].geometry.weight)).toBe(30);await p.reload();expect(await p.evaluate(()=>db.quote.products[0].children[0].spec.shapeDefinition.version)).toBe(1);pass('DM-02: revision 2 in catalogue does not rewrite revision 1 selected in saved quotation');
  await p.setViewportSize({width:390,height:844});await tab('mass');expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await shot('06-quy-uoc-man-hinh-hep');expect(errors).toEqual([]);pass('Narrow screen, reload and new definition workflow without JavaScript errors');
  fs.writeFileSync(path.join(dir,'results.json'),JSON.stringify({url,passed:true,at:new Date().toISOString(),checks,screens,errors},null,2));
}catch(e){console.error(e);await shot('FAILURE');fs.writeFileSync(path.join(dir,'results.json'),JSON.stringify({url,passed:false,at:new Date().toISOString(),checks,screens,errors,error:e.message},null,2));process.exitCode=1;}finally{await browser.close();}})();
