'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),P=require('../pricing-core.js'),C=require('../core.js'),D=require('../definition-core.js');
async function run(t){const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port;let session;const call=async(route,method='GET',body)=>{const r=await fetch(base+'/api/'+route,{method,headers:{'Content-Type':'application/json',...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const s=await call('setup','POST',{username:'admin',name:'Kiểm thử quy ước',password:'Only-for-definition-tests-42!'});session={cookie:s.cookie,csrf:s.data.csrf};return {call};}
function defined(){const db=P.demoSeed();D.saveShape(db,{id:'SCHEMA-TEST',name:'Tra giả lập',base:'bar',fields:[{key:'L',mode:'input',unit:'mm',sample:2000},{key:'KM',mode:'fixed',unit:'kg/m',sample:10},{key:'AM',mode:'fixed',unit:'m²/m',sample:.5}],length:'L',width:'0',mass:'KM',surface:'AM'});D.saveStock(db,{id:'STOCK-TEST',name:'Khổ thử',base:'bar',length:12000,width:0,workshop:'Xưởng thử',machine:'Máy thử',active:true});return db;}
test('shape workbench server: function formulas persist and reproduce the trial in actual quote calculation',async t=>{
 const {call}=await run(t),db=defined(),d=db.shapeDefinitions[0];d.length='MAX(L, 1000)';d.mass='ROUND(KM, 2)';d.blankMass='IF(PHOI_D > 0, PHOI_D / 1000 * KL_DV, PHOI_D / 1000 * KL_DV)';
 const m=D.applyShape({id:'FUNCTION-MAT',name:'Thanh thử hàm',density:7850,unit:'kg',price:20000,stockL:6000},d,{KM:12,AM:.6});db.materials.push(m);db.quote.products=[{id:'FUNC-SP',kind:'product',name:'Bốn thanh thử',qty:1,children:[D.assign(D.draft('Thanh',4),m,db.rules)],ops:[]}];
 const created=await call('quotes','POST',{document:db});A.equal(created.status,201);const saved=(await call('quotes/'+created.data.id)).data.document,r=C.calculate(saved);A.equal(r.rows[0].geometry.weight,96);A.equal(r.rows[0].purchasedWeight,144);A.equal(saved.quote.products[0].children[0].spec.shapeDefinition.mass,'ROUND(KM, 2)');
 const master=(await call('catalog')).data;A.equal((await call('catalog','PUT',{expectedVersion:master.version,catalog:{...master.catalog,shapeDefinitions:[{...d,mass:'MIN(KM, L)'}]}})).status,400);
});
test('definitions server: shared shapes/stocks survive catalogue publish and quotation persistence',async t=>{const {call}=await run(t),db=defined(),master=(await call('catalog')).data;const catalog={...master.catalog,shapeDefinitions:db.shapeDefinitions,stockSizes:db.stockSizes};A.equal((await call('catalog','PUT',{expectedVersion:master.version,catalog})).status,200);const saved=(await call('catalog')).data;A.deepEqual(saved.catalog.shapeDefinitions,db.shapeDefinitions);A.deepEqual(saved.catalog.stockSizes,db.stockSizes);const n=D.draft('Dòng nháp máy chủ',2);db.quote.products[0].children.push(n);const created=await call('quotes','POST',{document:db});A.equal(created.status,201);const read=(await call('quotes/'+created.data.id)).data;A.deepEqual(read.document.shapeDefinitions,db.shapeDefinitions);A.deepEqual(read.document.stockSizes,db.stockSizes);A.ok(C.findNode(read.document.quote.products,n.id).draftMaterial);const submit=await call('quotes/'+created.data.id+'/submit','POST',{expectedVersion:read.version});A.equal(submit.status,422);A.match(JSON.stringify(submit.data),/chưa chọn mã/);});
test('definitions server: approved quote snapshot unchanged after shared definition update',async t=>{const {call}=await run(t),db=defined(),m=D.applyShape({id:'SHAPE-MAT',name:'Vật tư thử',density:7850,unit:'kg',price:10000,stockL:6000,stockW:0},db.shapeDefinitions[0],{KM:10,AM:.5});db.materials.push(m);db.quote.products[0].children.push(D.assign(D.draft('Thêm',1),m,db.rules));const q=await call('quotes','POST',{document:db});A.equal(q.status,201);const submitted=await call('quotes/'+q.data.id+'/submit','POST',{expectedVersion:q.data.version});A.equal(submitted.status,200);const approved=await call('quotes/'+q.data.id+'/approve','POST',{expectedVersion:submitted.data.version,acknowledgeBelowCost:true,reason:'Kiểm thử dữ liệu giả'});A.equal(approved.status,200);const before=(await call('quotes/'+q.data.id)).data.document.quote;D.saveShape(db,{...db.shapeDefinitions[0],mass:'KM * 2'});const master=(await call('catalog')).data;A.equal((await call('catalog','PUT',{expectedVersion:master.version,catalog:{...master.catalog,shapeDefinitions:db.shapeDefinitions,stockSizes:db.stockSizes}})).status,200);const after=(await call('quotes/'+q.data.id)).data.document.quote;A.deepEqual(after,before);});
test('definitions server: malformed schema and stock cannot enter shared catalogue',async t=>{const {call}=await run(t),master=(await call('catalog')).data;for(const extra of [{shapeDefinitions:[{id:'broken'}]},{stockSizes:[{id:'BAD',name:'Bad',base:'bar',length:0}]},{shapeDefinitions:defined().shapeDefinitions.map(d=>({...d,length:'process.exit(0)'}))}])A.equal((await call('catalog','PUT',{expectedVersion:master.version,catalog:{...master.catalog,...extra}})).status,400);});

test('definitions server: independent per-piece mass and area persist and are recalculated on the server',async t=>{const {call}=await run(t),db=defined(),d=D.saveShape(db,{...db.shapeDefinitions[0],blankShape:'profile',blankMass:'PHOI_D / 1000 * KL_DV / 2',blankSurface:'PHOI_D / 1000 * DT_DV / 2'}),m=D.applyShape({id:'PART-MAT',name:'Phôi công thức riêng',density:7850,unit:'kg',price:10000,stockL:6000,stockW:0},d,{KM:10,AM:.5});db.materials.push(m);db.quote.products=[{id:'PART-SP',kind:'product',name:'Ba phôi thử',qty:1,children:[D.assign(D.draft('Phôi',3),m,db.rules)],ops:[]}];db.quote.kerf=0;const created=await call('quotes','POST',{document:db});A.equal(created.status,201);const read=(await call('quotes/'+created.data.id)).data;A.equal(read.document.quote.products[0].children[0].spec.shapeDefinition.blankMass,d.blankMass);A.equal(C.calculate(read.document).rows[0].geometry.weight,30);A.equal(C.calculate(read.document).rows[0].geometry.blankArea,1.5);A.equal(C.calculate(read.document).rows[0].purchasedWeight,60);const master=(await call('catalog')).data;A.equal((await call('catalog','PUT',{expectedVersion:master.version,catalog:{...master.catalog,shapeDefinitions:[{...d,blankMass:'L'}]}})).status,400);});

test('review server: named parameters, alternate prices and per-job complexity persist and calculate together',async t=>{
 const {call}=await run(t),db=P.demoSeed(),W=require('../work-core.js'),CV=require('../conventions-core.js'),master=(await call('catalog')).data;
 CV.save(db,'parameters',{name:'GAP',label:'Khoảng hở lắp ghép',unit:'mm'});
 const options=[{id:'opt-area',name:'Theo m² thử',method:'catalog',inside:4000,outside:6000,insideUnit:'m²',outsideUnit:'m²',fixedScope:'total'}];
 db.rates.find(r=>r.id==='cut').priceOptions=C.copy(options);db.quote.ratesSnapshot.find(r=>r.id==='cut').priceOptions=C.copy(options);W.setPriceOption(db.quote,'cut','opt-area');const n=db.quote.products[0].children[0];n.ops[0].complexity={label:'Khó',multiplier:1.2};
 A.equal((await call('catalog','PUT',{expectedVersion:master.version,catalog:{...master.catalog,rates:db.rates,conventions:db.conventions}})).status,200);
 const created=await call('quotes','POST',{document:db});A.equal(created.status,201);const saved=(await call('quotes/'+created.data.id)).data.document;A.equal(saved.conventions.parameters[0].label,'Khoảng hở lắp ghép');A.equal(saved.quote.operationPriceOptions.cut,'opt-area');A.equal(C.calculate(saved).nodes[n.id].ownOps[0].cost,76800);
 const catalogue=(await call('catalog')).data;catalogue.catalog.rates.find(r=>r.id==='cut').priceOptions[0].inside=9999;A.equal((await call('catalog','PUT',{expectedVersion:catalogue.version,catalog:catalogue.catalog})).status,200);
 A.deepEqual((await call('quotes/'+created.data.id)).data.document.quote,saved.quote);
});

test('review server: malformed options, names and direct complexity cannot be persisted',async t=>{
 const {call}=await run(t),master=(await call('catalog')).data;
 for(const patch of [{priceOptions:[{id:'opt-test',name:'Thử',method:'catalog',inside:-1,outside:2,insideUnit:'kg',outsideUnit:'kg'}]},{priceOptions:[{id:'opt-test',name:'Thử',method:'unknown',inside:1,outside:2,insideUnit:'kg',outsideUnit:'kg'}]}]){const catalog=C.copy(master.catalog);Object.assign(catalog.rates[0],patch);A.equal((await call('catalog','PUT',{expectedVersion:master.version,catalog})).status,400);}
 for(const multiplier of [0,-1,null,'oops']){const db=P.demoSeed();db.quote.products[0].ops[0].complexity={label:'Thử',multiplier};A.equal((await call('quotes','POST',{document:db})).status,400);}
 const db=P.demoSeed();db.conventions={parameters:[{name:'L',label:123,unit:'mm'}]};A.equal((await call('quotes','POST',{document:db})).status,400);
});
