'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),C=require('../core.js'),P=require('../pricing-core.js'),D=require('../device-core.js'),I=require('../intake-core.js');
const near=(a,b)=>A.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function seed(){const d=P.demoSeed();d.quote.remnantMode='all';const p=d.quote.products[0];p.qty=1;const n=p.children.find(n=>n.kind==='material');n.qty=2;n.spec.price=10000000;n.spec.brand='Hãng A';n.spec.specification='Thiết bị thử';const e={id:'device-test',nodeId:n.id,variant:D.variant(n.spec),mode:'percent',rate:20,basis:'selected-price',priceConfirmed:true,scopeConfirmed:true,work:'Lắp thiết bị A',location:'Công trình',reason:'QA: giá thiết bị đúng phạm vi, lắp ngoài SX',stage:'base'};return {d,n,p,e};}
test('TC07: 2 devices × 10M × 20% = 4M; fixed 1.5M/unit = 3M, no double quantity',()=>{const {d,e}=seed();d.quote.deviceInstallations=[e];let r=P.calculate(d);A.deepEqual(r.errors,[]);near(r.devices.items[0].cost,4000000);e.mode='unit';e.rate=1500000;r=P.calculate(d);near(r.devices.items[0].cost,3000000);});
test('TC07: explicit total value multiplies percent only; changing count requires reconfirmation',()=>{const {d,n,e}=seed();Object.assign(e,{basis:'declared-total',deviceTotal:20000000,totalQuantity:2});d.quote.deviceInstallations=[e];near(P.calculate(d).devices.items[0].cost,4000000);n.qty=3;A.match(P.calculate(d).errors.join(' '),/Số lượng đã đổi/);e.totalQuantity=3;e.deviceTotal=30000000;near(P.calculate(d).devices.items[0].cost,6000000);});
test('BG04: explicit base stage bypasses SX; production stage multiplies SX exactly once; nodes agree',()=>{const {d,n,p,e}=seed();Object.assign(d.quote.pricing,{overhead:10,management:20,special:0});const before=P.calculate(d).alternatives.detail.total;d.quote.deviceInstallations=[e];let r=P.calculate(d);near(r.alternatives.detail.total.cost-before.cost,4000000);near(r.nodes[n.id].parts.install,4000000);near(r.nodes[p.id].deviceParts.install,4000000);e.stage='production';r=P.calculate(d);near(r.alternatives.detail.total.cost-before.cost,4000000*1.1*1.2);near(r.nodes[n.id].parts.factory,4000000);});
test('BG02/D04: changing detail-only device cost/stage never increases complete kg/TMC/competitor selling totals',()=>{const {d,e}=seed();const before=P.calculate(d);for(const stage of ['production','base']){d.quote.deviceInstallations=[{...e,stage,rate:30}];const after=P.calculate(d);A.ok(after.alternatives.detail.total.sell>before.alternatives.detail.total.sell);for(const key of ['kg','tmc','competitor'])near(after.alternatives[key].total.sell,before.alternatives[key].total.sell);}});
test('TC07: supplier-included work costs zero; another on-site product installation remains',()=>{const {d,p,e}=seed();d.quote.expenses=[{id:'site',name:'Cẩu sản phẩm tại công trình',category:'install',method:'fixed',scope:'all',rate:500000,allocation:'equal'}];const before=P.calculate(d).alternatives.detail.total.cost;e.mode='supplier';d.quote.deviceInstallations=[e];const r=P.calculate(d);near(r.devices.items[0].cost,0);near(r.alternatives.detail.total.cost,before);near(r.logistics.items[0].cost,500000);});
test('TC05/TC07: same work links existing installation source once, missing/changed scope blocks calculation',()=>{const {d,n,e}=seed();d.quote.expenses=[{id:'site',name:'Lắp thiết bị A',category:'install',method:'unit',scope:'nodes',nodeIds:[n.id],rate:1500000,allocation:'quantity'}];let r=P.calculate(d),s=D.sources(d.quote,r,r.logistics,n.id).find(s=>s.key.includes('expense'));A.ok(s);Object.assign(e,{mode:'covered',sourceKey:s.key});d.quote.deviceInstallations=[e];r=P.calculate(d);A.deepEqual(r.errors,[]);near(r.devices.items[0].cost,0);near(r.logistics.items[0].cost,3000000);d.quote.expenses[0].nodeIds=[d.quote.products[1].id];A.match(P.calculate(d).errors.join(' '),/đổi\/xóa hoặc ngoài phạm vi/);});
test('TC07: duplicate work on same node/location is rejected; different location retained',()=>{const {d,e}=seed();d.quote.deviceInstallations=[e,{...e,id:'second',work:'  LẮP   THIẾT BỊ A '}];A.match(P.calculate(d).errors.join(' '),/Trùng cùng thiết bị/);d.quote.deviceInstallations[1].location='Xưởng';near(P.calculate(d).devices.items.reduce((s,e)=>s+e.cost,0),8000000);});
test('TC07: missing stage, confirmation, price, rate or basis blocks ready state, zero is deliberate',()=>{for(const change of [{stage:''},{scopeConfirmed:false},{priceConfirmed:false},{rate:''},{rate:-1},{basis:''}]){const {d,e}=seed();d.quote.deviceInstallations=[{...e,...change}];const r=P.calculate(d);A.ok(r.errors.length);A.equal(r.alternatives.detail.ready,false);}const {d,n,e}=seed();d.quote.deviceInstallations=[e];n.spec.price=null;A.ok(P.calculate(d).errors.length);n.spec.price=0;near(P.calculate(d).devices.items[0].cost,0);});
test('GD01: unconfirmed brand swap blocks; deliberate replacement picks new price, preserves percent and fixed labor',()=>{const {d,n,e}=seed();d.quote.deviceInstallations=[e,{...e,id:'fixed',work:'Đấu nối',mode:'unit',rate:1500000}];const m={...C.copy(n.spec),id:'BRAND-B',brand:'Hãng B',price:15000000};d.materials.push(m);A.throws(()=>D.replaceMaterial(d,n.id,m.id,false,m.price),/Xác nhận/);const other=C.copy(d.quote),catalog=JSON.stringify(d.materials);D.replaceMaterial(d,n.id,m.id,true,m.price);const r=P.calculate(d);A.deepEqual(r.errors,[]);near(r.devices.items[0].cost,6000000);near(r.devices.items[1].cost,3000000);A.equal(d.quote.deviceInstallations[0].rate,20);A.equal(JSON.stringify(d.materials),catalog);A.equal(C.findNode(other.products,n.id).spec.brand,'Hãng A');n.spec.brand='Unconfirmed';A.match(P.calculate(d).errors.join(' '),/thương hiệu/);});
test('GD01: explicit new price in material table recalculates linked percent, not fixed unit labor',()=>{const {d,n,e}=seed();d.quote.deviceInstallations=[e,{...e,id:'fixed',work:'Đấu nối',mode:'unit',rate:15}];const row=I.priceRows(d).find(r=>r.targets.includes(n.spec));I.applyMaterialPrices(d,[{key:row.key,value:12000000}]);const r=P.calculate(d);near(r.devices.items[0].cost,4800000);near(r.devices.items[1].cost,30);});
test('GD01: changing unit with existing work is not silently accepted; declared total invalidates on brand change',()=>{const {d,n,e}=seed();d.quote.deviceInstallations=[{...e,basis:'declared-total',deviceTotal:20000000,totalQuantity:2}];const m={...C.copy(n.spec),id:'B',unit:n.spec.unit==='bộ'?'cái':'bộ',brand:'B'};d.materials.push(m);A.throws(()=>D.replaceMaterial(d,n.id,m.id,true,10),/Đổi đơn vị/);m.unit=n.spec.unit;D.replaceMaterial(d,n.id,m.id,true,10);A.match(P.calculate(d).errors.join(' '),/xác nhận lại tổng/);});
test('TC07: deleting object or changing source operation blocks stale coverage',()=>{const {d,n,p,e}=seed();n.ops=[{id:'cut',mode:'inside',amount:1,pricingMethod:'fixed',unitPrice:100}];let r=P.calculate(d);const s=D.sources(d.quote,r,r.logistics,n.id).find(s=>JSON.parse(s.key)[0]==='op'&&JSON.parse(s.key)[1]===n.id);A.ok(s);d.quote.deviceInstallations=[{...e,mode:'covered',sourceKey:s.key}];A.deepEqual(P.calculate(d).devices.errors,[]);n.ops[0].id='bend';A.ok(P.calculate(d).devices.errors.length);p.children=p.children.filter(x=>x.id!==n.id);A.ok(P.calculate(d).devices.errors.length);});
test('TC07: included package keeps BOM and separate work, skipped operations are not valid coverage sources',()=>{const {d,n,p,e}=seed();n.ops=[{id:'cut',mode:'inside',amount:1,pricingMethod:'fixed',unitPrice:100}];p.outsource={enabled:true,supplier:'QA Vendor',output:'Khung đã đấu nối',materialSupply:'vendor',unit:'gói',price:1000000};let r=P.calculate(d);const sources=D.sources(d.quote,r,r.logistics,n.id);A.equal(sources.filter(s=>JSON.parse(s.key)[0]==='op').length,0);const source=sources.find(s=>JSON.parse(s.key)[0]==='package');A.ok(source);d.quote.deviceInstallations=[{...e,mode:'covered',sourceKey:source.key},{...e,id:'site-extra',location:'Công trình khác',mode:'unit',rate:100}];r=P.calculate(d);A.deepEqual(r.devices.errors,[]);near(r.devices.items[0].cost,0);near(r.devices.items[1].cost,200);A.ok(r.rows.find(row=>row.id===n.id));p.outsource.enabled=false;A.ok(P.calculate(d).devices.errors.length);});
test('Device calculation pure, JSON roundtrip stable; submitted and approved work cannot be edited',()=>{const {d,e}=seed();d.quote.deviceInstallations=[e];const before=JSON.stringify(d),r=P.calculate(d);A.equal(JSON.stringify(d),before);near(P.calculate(JSON.parse(before)).total.grand,r.total.grand);for(const status of ['approved','submitted']){d.quote.status=status;A.throws(()=>D.save(d.quote,e));A.throws(()=>D.replaceMaterial(d,e.nodeId,'anything',true,1));}});
test('TC07: cloning a configured device branch cannot silently drop installation costs; explicit removal clears marker',()=>{const {d,n,p,e}=seed();D.save(d.quote,e);const clone=C.cloneNode(n);p.children.push(clone);A.match(P.calculate(d).devices.errors.join(' '),/khai lại sau khi nhân bản/);D.save(d.quote,{...e,id:'cloned-work',nodeId:clone.id});A.deepEqual(P.calculate(d).devices.errors,[]);D.remove(d.quote,'cloned-work');A.equal(clone.deviceWorkRequired,undefined);A.deepEqual(P.calculate(d).devices.errors,[]);p.children=p.children.filter(x=>x.id!==n.id);A.ok(P.calculate(d).devices.errors.length);D.remove(d.quote,e.id);A.deepEqual(P.calculate(d).devices.errors,[]);});
