'use strict';
const {chromium,expect}=require('@playwright/test'),{createApp}=require('../server/app.cjs');
(async()=>{const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});try{const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:'+app.server.address().port);await p.waitForFunction(()=>Team.available);await p.evaluate(async()=>{teamSession(await teamApi('setup','POST',{username:'admin',name:'Admin',password:'Enterprise-browser-2026!'}));await enterpriseOpen('finance');});const open=async(a)=>p.locator('#content [data-ent="'+a+'"]').first().click(),fill=async(k,v)=>p.locator('#dialog [name="'+k+'"]').fill(String(v)),submit=async()=>{await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#dialog')).not.toBeVisible();};
 await open('expense');await fill('reference','INVOICE-UI');await fill('amount',1000);await fill('note','Office supplies');await submit();await expect(p.locator('#ent-body')).toContainText('INVOICE-UI');await open('pay-cost');await fill('reference','CASH-UI');await fill('amount',400);await fill('note','Partial payment');await submit();await expect(p.locator('#ent-body')).toContainText('CASH-UI');const download=p.waitForEvent('download');await open('export');expect((await download).suggestedFilename()).toMatch(/\.xlsx$/);
 await p.evaluate(()=>enterpriseOpen('payroll'));await open('rule');await fill('name','Office UI');for(const [k,v]of Object.entries({standardDays:20,hoursPerDay:8,overtime:1.5,rest:2,holiday:3,onsiteAllowance:100,employeeInsurance:10,employerInsurance:20}))await fill(k,v);await fill('note','Agreed company rules');await submit();await open('salary');for(const [k,v]of Object.entries({monthly:16000,insuranceBase:1000,allowance:50,deduction:10,tax:20}))await fill(k,v);await fill('note','Salary input');await submit();
 await p.evaluate(()=>enterpriseOpen('attendance'));await open('attendance');await fill('date','2026-09-01');await fill('regular',8);await submit();await open('attendance-approve');await submit();await expect(p.locator('#ent-body')).toContainText('Ngày quy đổi');await p.evaluate(()=>enterpriseOpen('payroll'));await open('payroll');await fill('month','2026-09');await submit();await open('payroll-detail');await expect(p.locator('#dialog')).toContainText('720');await p.locator('#dialog [data-ent=payroll-export]').click();await p.evaluate(()=>closeDialog());await open('payroll-approve');await submit();await open('payroll-pay');await fill('date','2026-09-25');await fill('reference','PAYROLL-UI');await submit();await expect(p.locator('#ent-body')).toContainText('Đã trả');
 await p.evaluate(()=>enterpriseOpen('work'));await open('task');await fill('name','Daily review');await fill('plannedHours',8);await submit();for(const state of ['accepted','running']){await p.locator('[data-ent=transition][data-state="'+state+'"]').click();await submit();}await open('report');await fill('hours',6);await fill('output',3);await fill('content','Reviewed 3 items');await fill('issue','Missing supplier response');await fill('proposal','Call supplier');await fill('nextPlan','Finish review');await submit();await open('resolve');await fill('resolution','Response received');await submit();for(const state of ['done','confirmed']){await p.locator('[data-ent=transition][data-state="'+state+'"]').click();await submit();}await expect(p.locator('#ent-body')).toContainText('Đã xác nhận');await expect(p.locator('#ent-body')).toContainText('Finish review');
 for(const view of ['finance','attendance','payroll','work']){await p.evaluate(v=>enterpriseOpen(v),view);await p.setViewportSize({width:390,height:844});const overflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2);expect(overflow,'mobile '+view).toBe(false);await p.screenshot({path:'artifacts/enterprise-'+view+'-mobile.png',fullPage:true});await p.setViewportSize({width:1440,height:1000});}await p.reload();await p.waitForFunction(()=>Team.user);await p.evaluate(()=>enterpriseOpen('payroll'));await expect(p.locator('#ent-body')).toContainText('Đã trả');expect(errors).toEqual([]);console.log('PASS enterprise UI: cash, exports, attendance, payroll, tasks, reload and four mobile pages');
 }finally{await browser.close();await new Promise(r=>app.server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
