'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),P=require('../pricing-core.js'),C=require('../core.js'),D=require('../definition-core.js');
async function fixture(t){const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));let cookie,csrf;const call=async(path,method='GET',body)=>{const r=await fetch('http://127.0.0.1:'+app.server.address().port+'/api/'+path,{method,headers:{'Content-Type':'application/json',Cookie:cookie||'','X-CSRF-Token':csrf||''},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();if(path==='setup'){cookie=r.headers.get('set-cookie').split(';')[0];csrf=data.csrf;}return {status:r.status,data};};await call('setup','POST',{username:'admin',name:'Formula publisher',password:'Formula-sync-local-42!'});return {app,call};}

async function assignSender(call,id,version){const u=(await call('me')).data.user;const s=(await call('quotes/'+id+'/followup')).data;const r=await call('quotes/'+id+'/followup/assign','POST',{expectedVersion:s.revision,offerVersion:version,senderId:u.id,careOwnerId:u.id});A.equal(r.status,200,JSON.stringify(r.data));return {expectedVersion:r.data.revision,careOwnerId:u.id,recipient:'Customer',channel:'Email'};}
test('name-only publication updates repeated material rows but keeps sent documents and revision history intact',async t=>{
 const {app,call}=await fixture(t),db=P.demoSeed();let master=(await call('catalog')).data;
 const materialId=C.flatten(db.quote.products).find(n=>n.kind==='material').spec.id,quotes=[];
 for(const sent of [false,true]){const doc=C.copy(db);doc.quote.id='NAME-'+sent;let saved=await call('quotes','POST',{document:doc});A.equal(saved.status,201);const id=saved.data.id;
 if(sent){saved=await call('quotes/'+id+'/submit','POST',{expectedVersion:saved.data.version});A.equal(saved.status,200);saved=await call('quotes/'+id+'/approve','POST',{expectedVersion:saved.data.version,acknowledgeBelowCost:true});A.equal(saved.status,200);A.equal((await call('quotes/'+id+'/workflow','POST',{offerVersion:saved.data.version,...await assignSender(call,id,saved.data.version),status:'sent',confirmedSent:true,reason:'Sent test',validUntil:'2099-01-01'})).status,200);}
 quotes.push({id,sent,before:app.sql.prepare('SELECT * FROM quotes WHERE id=?').get(id)});}
 master=(await call('catalog')).data;master.catalog.materials.find(m=>m.id===materialId).name='Published material name';
 const published=await call('catalog','PUT',{expectedVersion:master.version,catalog:master.catalog});A.equal(published.status,200);A.equal(published.data.formulaUpdates.updated,1);A.equal(published.data.formulaUpdates.sent,1);
 for(const {id,sent,before}of quotes){const after=app.sql.prepare('SELECT * FROM quotes WHERE id=?').get(id);A.equal(app.sql.prepare('SELECT document FROM revisions WHERE id=? AND version=?').get(id,before.version).document,before.document);if(sent){A.deepEqual(after,before);A.equal((await call('quotes/'+id+'/formula-update')).data.state,'changed');continue;}A.equal(after.total,before.total);const original=C.flatten(JSON.parse(before.document).quote.products),nodes=C.flatten(JSON.parse(after.document).quote.products);for(const n of nodes.filter(n=>n.kind==='material'&&n.spec.id===materialId)){A.equal(n.name,'Published material name');A.equal(n.spec.name,n.name);A.equal(n.spec.price,original.find(x=>x.id===n.id).spec.price);}A.equal((await call('quotes/'+id,'PUT',{expectedVersion:before.version,document:JSON.parse(before.document)})).status,409);}
});
test('published formulas update locked/draft/submitted/approved unsent quotes, preserve sent versions and entered prices',async t=>{
 const {app,call}=await fixture(t),definition={id:'SYNC',name:'Tam giác thử',...D.polygonPreset('triangle',3),surface:'1'};let master=(await call('catalog')).data;master.catalog.shapeDefinitions=[definition];A.equal((await call('catalog','PUT',{expectedVersion:master.version,catalog:master.catalog})).status,200);
 const quotes=[];for(const status of ['draft','submitted','approved','sent']){const db=P.demoSeed(),m=D.applyShape({id:'SYNC-MAT',name:'Vật tư thử',density:7850,unit:'kg',price:12345,stockL:1000,stockW:1000},definition,{T:2});db.materials.push(m);db.shapeDefinitions=[definition];db.quote.id='SYNC-'+status;db.quote.remnantMode='all';db.quote.products=[{id:'SP',kind:'product',name:'Sản phẩm',qty:1,ops:[],children:[D.assign(D.draft('Tấm',2),m,db.rules)]}];let made=await call('quotes','POST',{document:db});A.equal(made.status,201,JSON.stringify(made.data));const id=made.data.id;
 if(status==='draft'){for(const stage of ['intake','technical','materials']){const h=await call('quotes/'+id+'/handoff/'+stage,'POST',{expectedVersion:made.data.version});A.equal(h.status,200,JSON.stringify(h.data));}}else{made=await call('quotes/'+id+'/submit','POST',{expectedVersion:made.data.version});A.equal(made.status,200,JSON.stringify(made.data));if(status!=='submitted'){made=await call('quotes/'+id+'/approve','POST',{expectedVersion:made.data.version,acknowledgeBelowCost:true});A.equal(made.status,200,JSON.stringify(made.data));}}
 if(status==='sent'){const sent=await call('quotes/'+id+'/workflow','POST',{offerVersion:made.data.version,...await assignSender(call,id,made.data.version),status:'sent',confirmedSent:true,reason:'Đã gửi bản thử',validUntil:'2099-01-01'});A.equal(sent.status,200,JSON.stringify(sent.data));}
 quotes.push({id,status,before:app.sql.prepare('SELECT * FROM quotes WHERE id=?').get(id)});}
 master=(await call('catalog')).data;master.catalog.shapeDefinitions[0].name='Renamed shape';master.catalog.shapeDefinitions[0].surface='2';master.catalog.shapeDefinitions[0].mass='RHO * T / 1000 * 2';const published=await call('catalog','PUT',{expectedVersion:master.version,catalog:master.catalog});A.equal(published.status,200,JSON.stringify(published.data));A.equal(published.data.formulaUpdates.updated,3);A.equal(published.data.formulaUpdates.sent,1);
 for(const {id,status,before}of quotes){const after=app.sql.prepare('SELECT * FROM quotes WHERE id=?').get(id),preview=(await call('quotes/'+id+'/formula-update')).data;A.equal(JSON.parse(after.document).quote.products[0].children[0].spec.price,12345);A.deepEqual(JSON.parse(after.document).quote.pricing,JSON.parse(before.document).quote.pricing);A.equal(app.sql.prepare('SELECT document FROM revisions WHERE id=? AND version=?').get(id,before.version).document,before.document);
 if(status==='sent'){A.deepEqual(after,before);A.equal(preview.sent,true);A.ok(preview.values.surfaceArea.delta>0);A.ok(preview.values.grand.delta>0);}else{A.equal(after.version,before.version+1);A.equal(after.status,before.status);A.equal(preview.state,'current');A.equal(JSON.parse(after.document).quote.products[0].children[0].ruleSpec.name,'Renamed shape');A.equal(JSON.parse(after.document).quote.products[0].children[0].spec.shapeDefinition.surface,'2');const stale=await call('quotes/'+id,'PUT',{expectedVersion:before.version,document:JSON.parse(before.document)});A.equal(stale.status,409);}}
 const h=(await call('quotes/'+quotes[0].id+'/handoff')).data;A.equal(h.intake.current,true);A.equal(h.technical.current,false);A.match(h.technical.changeReason,/Cập nhật công thức/);
 const draftId=quotes[0].id,current=(await call('quotes/'+draftId)).data;current.document.quote.pricing.profit=17;
 const draftSave=await call('quotes/'+draftId,'PUT',{expectedVersion:current.version,document:current.document});A.equal(draftSave.status,200,JSON.stringify(draftSave.data));
 A.equal((await call('quotes/'+draftId+'/handoff/materials','POST',{expectedVersion:draftSave.data.version})).status,409);
 A.equal((await call('quotes/'+draftId)).data.document.quote.pricing.profit,17);
 master=(await call('catalog')).data;const again=await call('catalog','PUT',{expectedVersion:master.version,catalog:master.catalog});A.equal(again.data.formulaUpdates.updated,0);
 const copy=JSON.parse(quotes[0].before.document);copy.quote.id='SYNC-NEW-FROM-OLD';const fresh=await call('quotes','POST',{document:copy});A.equal(fresh.status,201);A.equal(fresh.data.formulaUpdated,true);A.equal(JSON.parse(app.sql.prepare('SELECT document FROM quotes WHERE id=?').get(fresh.data.id).document).quote.products[0].children[0].spec.shapeDefinition.surface,'2');
 master=(await call('catalog')).data;master.catalog.shapeDefinitions[0].fields.push({key:'NEW_X',mode:'input',unit:'number',sample:1});master.catalog.shapeDefinitions[0].mass='RHO * T / 1000 * NEW_X';const bad=await call('catalog','PUT',{expectedVersion:master.version,catalog:master.catalog});A.equal(bad.status,200);A.equal(bad.data.formulaUpdates.blocked,4);A.equal((await call('quotes/'+quotes[0].id+'/formula-update')).data.state,'blocked');
});
