'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),P=require('../pricing-core.js'),SA=require('../section-access.js');
test('four-level grants, hidden factors, calculation and protected round-trip',async t=>{const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port,password='Four-level-tests-only-42!';
 async function call(route,method='GET',body,session){const r=await fetch(base+'/api/'+route,{method,headers:{'Content-Type':'application/json',...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};}
 const admin=await call('setup','POST',{username:'admin',name:'Admin',password}),d=P.demoSeed();d.quote.pricing.overhead=12.34567;const id=(await call('quotes','POST',{document:d},admin)).data.id;
 const modes=Object.fromEntries(SA.keys.map(k=>[k,'view']));modes.bom='use';modes.operations='use';modes.factors='use';modes.customer='none';
 const role=await call('roles','POST',{name:'Operator',role:'estimator',sectionModes:modes,canViewCosts:true,canEditFactors:false},admin);A.equal(role.status,201,JSON.stringify(role.data));A.deepEqual(role.data.sectionModes,modes);
 A.equal((await call('users','POST',{username:'operator',name:'Operator',password,roleTemplateId:role.data.id},admin)).status,201);const user=await call('login','POST',{username:'operator',password});A.equal(user.data.permissions.sectionModes.customer,'none');A.equal(user.data.permissions.formulaEdit,false);
 let view=await call('quotes/'+id,'GET',undefined,user);A.equal(view.status,200);A.equal(JSON.stringify(view.data).includes('12.34567'),false);A.equal(view.data.document.quote.customer,'');A.equal((await call('intake/customers','GET',undefined,user)).status,403);
 const calc=await call('access/calculate','POST',{document:view.data.document},user);A.equal(calc.status,200,JSON.stringify(calc.data));A.equal(calc.data.total.grand,P.calculate(d).total.grand);A.equal(JSON.stringify(calc.data).includes('12.34567'),false);
 view.data.document.quote.products[0].qty=7;let saved=await call('quotes/'+id,'PUT',{document:view.data.document,expectedVersion:view.data.version},user);A.equal(saved.status,200,JSON.stringify(saved.data));const full=(await call('quotes/'+id,'GET',undefined,admin)).data;A.equal(full.document.quote.products[0].qty,7);A.equal(full.document.quote.pricing.overhead,12.34567);A.equal(full.document.quote.customer,d.quote.customer);
 const forbidden=structuredClone(full.document);forbidden.quote.pricing.overhead=55;A.equal((await call('quotes/'+id,'PUT',{document:forbidden,expectedVersion:full.version},user)).status,403);
 const viewModes={...modes,factors:'view',bom:'view'};await call('users','POST',{username:'reader',name:'Reader',password,role:'estimator',sectionModes:viewModes,canViewCosts:true},admin);const reader=await call('login','POST',{username:'reader',password});let plain=(await call('quotes/'+id,'GET',undefined,reader)).data;A.equal(plain.document.quote.pricing.overhead,12.34567);plain.document.quote.products[0].qty=99;A.equal((await call('quotes/'+id,'PUT',{document:plain.document,expectedVersion:plain.version},reader)).status,403);
 const lock=await call('formulas/locks','POST',{key:'calculationFactors:all',locked:true,reason:'QA lock',expectedVersion:0},admin);A.equal(lock.status,200);const protectedView=await call('quotes/'+id,'GET',undefined,reader);A.equal(JSON.stringify(protectedView.data).includes('12.34567'),false);A.equal((await call('me','GET',undefined,reader)).data.permissions.factorsHidden,true);A.equal((await call('quotes/'+id,'GET',undefined,admin)).data.document.quote.pricing.overhead,12.34567);
 A.equal((await call('access/calculate','POST',{document:protectedView.data.document},user)).status,403);
 A.equal((await call('formulas/locks','POST',{key:'calculationFactors:all',locked:false,reason:'QA unlock',expectedVersion:1},admin)).status,200);A.equal((await call('quotes/'+id,'GET',undefined,reader)).data.document.quote.pricing.overhead,12.34567);

});
