'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),C=require('../core.js'),P=require('../pricing-core.js'),G=require('../group-pricing-core.js'),F=require('./tmc-fixture.cjs'),Tax=require('../tax-core.js'),Access=require('../server/access.cjs');
const definition=()=>({id:'grp-qa',name:'Nhóm QA — không phải công thức khách',engine:'formula',formula:'KG * P_RATE + Q * P_EXTRA',source:'QA independent arithmetic, all-in before VAT',netConfirmed:true,parameters:[{key:'P_RATE',name:'Giá theo kg',unit:'đ/kg',value:120},{key:'P_EXTRA',name:'Phần thêm mỗi sản phẩm',unit:'đ/SP',value:100}]});
function mechanical(){const d=F.seed();G.assign(d.quote,d.quote.products[0].id,'detail');d.quote.pricing.selected='detail';delete d.quote.pricing.tmcPolicy;F.confirm(d.quote);return d;}
test('no TMC: hide comparison, do not require TMC policy/rates or block valid detailed release',()=>{const d=mechanical();d.quote.pricing.tmcTables=[];F.confirm(d.quote);const r=P.calculate(d);A.ok(!r.comparisonIds.includes('tmc'));A.equal(r.alternatives.tmc.applicable,false);A.deepEqual(r.errors,[]);A.deepEqual(r.tax.releaseErrors,[]);A.equal(r.tax.methods.tmc.net,null);});
test('new quotation starts with detailed comparison only; pre-existing declarations retained',()=>{const d=C.seed();P.enable(d);A.deepEqual(G.comparisonIds(d.quote),['detail']);delete d.quote.pricing.comparisonMethods;A.ok(G.comparisonIds(d.quote).includes('kg'));});
test('comparison selection is pure presentation: all totals, chosen price, overrides and tax confirmation unchanged',()=>{const d=F.mixed();F.confirm(d.quote);const before=P.calculate(d),signature=Tax.costSignature(d.quote);G.setComparisons(d.quote,['detail','competitor']);const r=P.calculate(d);A.deepEqual(r.comparisonIds,['detail','competitor']);A.deepEqual(r.total,before.total);A.equal(r.pricing.selected,'tmc');A.equal(Tax.costSignature(d.quote),signature);A.deepEqual(r.tax,before.tax);A.deepEqual(r.alternatives,before.alternatives);G.setComparisons(d.quote,[]);A.deepEqual(P.calculate(d).comparisonIds,[]);A.deepEqual(P.calculate(d).total,before.total);A.deepEqual(G.comparisonIds(JSON.parse(JSON.stringify(d.quote))),[]);});
test('unknown group never proves no TMC and selected applicable TMC stays visible when inputs are missing',()=>{const d=F.mixed();G.assign(d.quote,d.quote.products[1].id,'unknown');let r=P.calculate(d);A.ok(r.comparisonIds.includes('tmc'));A.ok(r.groupIssues.length);A.equal(r.alternatives.tmc.ready,false);d.quote.products[0].tmcKind='missing';r=P.calculate(d);A.ok(r.comparisonIds.includes('tmc'));A.equal(r.tax.methods.tmc.net,null);});
test('removing/reclassifying last TMC leaves selected method untouched but blocks official and overrides',()=>{const d=F.seed();F.confirm(d.quote);G.assign(d.quote,d.quote.products[0].id,'detail');const r=P.calculate(d);A.equal(d.quote.pricing.selected,'tmc');A.equal(r.pricing.selected,'tmc');A.ok(r.errors.length);A.ok(!r.comparisonIds.includes('tmc'));d.quote.pricing.selected='detail';F.confirm(d.quote);A.deepEqual(P.calculate(d).errors,[]);});
test('group formula is scoped, all-in, independently expected and rounds per unit then quantity once',()=>{const d=F.mixed(),q=d.quote;G.saveGroup(q,definition());G.assign(q,q.products[1].id,'grp-qa');G.setComparisons(q,['detail','tmc','group:grp-qa']);q.pricing.selected='group:grp-qa';F.confirm(q);const r=P.calculate(d),g=r.products[1],detail=r.alternatives.detail.products[0];A.equal(g.groupCalculation.total,3900);A.equal(g.unitSell,1300);A.equal(g.sell,3900);A.equal(r.products[0].sell,detail.sell);A.equal(r.total.beforeTax,3900+detail.sell);A.deepEqual(r.tax.releaseErrors,[]);A.equal(r.alternatives.tmc.products[1].sell,r.alternatives.detail.products[1].sell);A.ok(r.comparisonIds.includes('group:grp-qa'));});
test('own group parameters change only that calculation; detailed fallback and TMC remain intact',()=>{const d=F.mixed(),q=d.quote;G.saveGroup(q,definition());G.assign(q,q.products[1].id,'grp-qa');F.confirm(q);const r=P.calculate(d);q.pricing.productGroups[0].parameters[0].value=150;const s=P.calculate(d);A.equal(s.alternatives['group:grp-qa'].products[1].sell,4800);A.equal(s.alternatives['group:grp-qa'].products[0].sell,r.alternatives['group:grp-qa'].products[0].sell);A.deepEqual(s.alternatives.tmc.total,r.alternatives.tmc.total);A.deepEqual(s.alternatives.detail.total,r.alternatives.detail.total);A.equal(s.tax.costKnown,false);});
test('invalid group updates are atomic; division by zero/unknown dimensions cannot produce valid zero',()=>{const d=F.seed(),q=d.quote;for(const change of [{formula:'process.exit()'},{formula:'KG * MISSING'},{parameters:[{key:'Q',name:'Override',unit:'cái',value:1}]},{netConfirmed:false},{id:'tmc'},{source:''}]){const before=JSON.stringify(q);A.throws(()=>G.saveGroup(q,{...definition(),...change}));A.equal(JSON.stringify(q),before);}G.saveGroup(q,{...definition(),formula:'KG / (W - L)'});G.assign(q,q.products[0].id,'grp-qa');q.pricing.selected='group:grp-qa';A.equal(P.calculate(d).alternatives['group:grp-qa'].ready,false);G.saveGroup(q,{...definition(),formula:'Q * T'});A.equal(P.calculate(d).alternatives['group:grp-qa'].ready,false);});
test('formula dimension mm conversion, fractional rounding and a declared true zero are distinct from missing',()=>{const d=mechanical(),q=d.quote;G.saveGroup(q,{...definition(),formula:'L / 1000 * Q * P_RATE',parameters:[{key:'P_RATE',name:'Giá mét',unit:'đ/m',value:100.6}]});G.assign(q,q.products[0].id,'grp-qa');q.pricing.selected='group:grp-qa';F.confirm(q);let r=P.calculate(d);A.equal(r.products[0].unitSell,101);A.equal(r.total.beforeTax,202);G.saveGroup(q,{...definition(),formula:'0',parameters:[]});F.confirm(q);r=P.calculate(d);A.equal(r.total.beforeTax,0);A.equal(r.tax.methods['group:grp-qa'].net,0);});
test('no automatic named business groups, no cross-quote propagation, same-name text is not classification',()=>{const d=mechanical(),q=d.quote,other=C.copy(q);q.products[0].name='Máng cáp cửa gió tủ điện';A.equal(G.resolve(q,q.products[0]).id,'detail');G.saveGroup(q,definition());A.equal(G.groups(other).length,2);A.deepEqual(G.groups(other).map(g=>g.id),['tmc','detail']);const snapshot=JSON.stringify(d);P.calculate(d);A.equal(JSON.stringify(d),snapshot);});
test('locked snapshots, factor fingerprint and referenced group deletion protection',()=>{const d=F.seed(),q=d.quote,fp=Access.factorFingerprint(d);G.saveGroup(q,definition());A.notEqual(Access.factorFingerprint(d),fp);G.assign(q,q.products[0].id,'grp-qa');A.throws(()=>G.removeGroup(q,'grp-qa'),/đang dùng/);G.assign(q,q.products[0].id,'tmc');G.removeGroup(q,'grp-qa');A.equal(q.pricing.productGroups.length,0);q.status='approved';const before=JSON.stringify(q);for(const fn of [()=>G.saveGroup(q,definition()),()=>G.assign(q,q.products[0].id,'detail'),()=>G.removeGroup(q,'grp-qa'),()=>G.setComparisons(q,[])])A.throws(fn,/khóa/);A.equal(JSON.stringify(q),before);});
