'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),F=require('./tmc-fixture.cjs'),P=require('../pricing-core.js'),G=require('../group-pricing-core.js');
async function run(t){const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port;let cookie,csrf;const call=async(route,method='GET',body)=>{const r=await fetch(base+'/api/'+route,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie,'X-CSRF-Token':csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];if(data.csrf)csrf=data.csrf;return {status:r.status,data};};await call('setup','POST',{username:'admin',name:'QA GROUP',password:'Group-only-QA-server-42!'});return call;}
function seed(){const d=F.mixed(),q=d.quote;G.saveGroup(q,{id:'grp-qa',name:'Group QA',formula:'KG * P_RATE + Q * P_EXTRA',parameters:[{key:'P_RATE',name:'QA kg',unit:'VND/kg',value:120},{key:'P_EXTRA',name:'QA per item',unit:'VND/item',value:100}],source:'Private QA source: not customer parameters',netConfirmed:true});G.assign(q,q.products[1].id,'grp-qa');q.pricing.selected='group:grp-qa';G.setComparisons(q,['detail','group:grp-qa']);q.documentMode='official';require('./offer-fixture.cjs')(q);F.confirm(q);return d;}
test('component flow persists, recalculates server-side, approves at 3389, and stays private in customer offer',async t=>{
 const call=await run(t),CF=require('./cost-flow-fixture.cjs'),d=CF.seed();d.quote.documentMode='official';require('./offer-fixture.cjs')(d.quote);CF.confirm(d.quote);
 const saved=await call('quotes','POST',{document:d});A.equal(saved.status,201,JSON.stringify(saved));const id=saved.data.id,read=(await call('quotes/'+id)).data.document;A.equal(P.calculate(read).total.grand,3389);A.deepEqual(read.quote.pricing.productGroups[0].flow,d.quote.pricing.productGroups[0].flow);
 const submitted=await call('quotes/'+id+'/submit','POST',{expectedVersion:1});A.equal(submitted.status,200,JSON.stringify(submitted));const approved=await call('quotes/'+id+'/approve','POST',{expectedVersion:submitted.data.version,acknowledgeBelowCost:true,reason:'Synthetic cost flow QA'});A.equal(approved.status,200,JSON.stringify(approved));const offer=(await call('quotes/'+id)).data.document.quote.approvedOffer;A.equal(offer.totals.grand,3389);A.ok(!JSON.stringify(offer).includes('costFlow'));A.ok(!JSON.stringify(offer).includes('Q * 50'));
});
test('cost-flow changes invalidate tax confirmation and require factor permission',async t=>{
 const call=await run(t),CF=require('./cost-flow-fixture.cjs'),d=CF.seed();d.quote.documentMode='official';require('./offer-fixture.cjs')(d.quote);CF.confirm(d.quote);d.quote.pricing.productGroups[0].flow.rules.factory.formula='Q * 51';const saved=await call('quotes','POST',{document:d});A.equal(saved.status,201);A.equal((await call('quotes/'+saved.data.id+'/submit','POST',{expectedVersion:1})).status,422);
 await call('users','POST',{username:'flowlimited',name:'Limited flow',password:'Flow-only-local-test-42!',role:'estimator',canEditFactors:false});await call('login','POST',{username:'flowlimited',password:'Flow-only-local-test-42!'});d.quote.pricing.costFlows={detail:{rules:{incoming:{mode:'none',reason:'Test'}}}};A.equal((await call('quotes/'+saved.data.id,'PUT',{document:d,expectedVersion:1})).status,403);
});
test('group server: recalculates 8530 net, locks approved snapshot and strips private formula/parameters from public offer',async t=>{const call=await run(t),d=seed();A.equal(P.calculate(d).total.grand,9212);const saved=await call('quotes','POST',{document:d});A.equal(saved.status,201);const id=saved.data.id;const sub=await call('quotes/'+id+'/submit','POST',{expectedVersion:1});A.equal(sub.status,200,JSON.stringify(sub));const ap=await call('quotes/'+id+'/approve','POST',{expectedVersion:sub.data.version,acknowledgeBelowCost:true,reason:'Synthetic QA only'});A.equal(ap.status,200,JSON.stringify(ap));const read=await call('quotes/'+id),offer=read.data.document.quote.approvedOffer;A.equal(offer.totals.grand,9212);A.equal(offer.products[1].total,3900);A.ok(!JSON.stringify(offer).includes('P_RATE'));A.ok(!JSON.stringify(offer).includes('Private QA source'));d.quote.pricing.productGroups[0].parameters[0].value=1;const denied=await call('quotes/'+id,'PUT',{document:d,expectedVersion:ap.data.version});A.ok([403,409,422].includes(denied.status));A.equal((await call('quotes/'+id)).data.document.quote.approvedOffer.totals.grand,9212);});
test('group server: missing group, invalid formula, changed inputs and invalid classification cannot bypass official submission',async t=>{const call=await run(t);for(const [i,mutate]of [q=>q.pricing.productGroups=[],q=>q.pricing.productGroups[0].formula='KG / 0',q=>q.pricing.productGroups[0].parameters[0].value++,q=>q.products[1].priceGroupId='unknown',q=>q.pricing.productGroups.push({...q.pricing.productGroups[0]})].entries()){const d=seed();d.quote.id='QA-GROUP-'+i;mutate(d.quote);d.total={grand:9212};const saved=await call('quotes','POST',{document:d});A.equal(saved.status,201,JSON.stringify(saved));A.equal((await call('quotes/'+saved.data.id+'/submit','POST',{expectedVersion:1})).status,422);}});
test('group server: no-factor estimator may change comparison visibility but cannot alter a group formula or parameters',async t=>{const call=await run(t),d=seed();const saved=await call('quotes','POST',{document:d});A.equal(saved.status,201);A.equal((await call('users','POST',{username:'limited',name:'Limited QA',password:'Limited-group-QA-42!',role:'estimator',canEditFactors:false})).status,201);A.equal((await call('login','POST',{username:'limited',password:'Limited-group-QA-42!'})).status,200);G.setComparisons(d.quote,['detail']);const visibility=await call('quotes/'+saved.data.id,'PUT',{document:d,expectedVersion:1});A.equal(visibility.status,200,JSON.stringify(visibility));d.quote.pricing.productGroups[0].formula='1';A.equal((await call('quotes/'+saved.data.id,'PUT',{document:d,expectedVersion:visibility.data.version})).status,403);d.quote.pricing.productGroups[0].formula='KG * P_RATE + Q * P_EXTRA';d.quote.pricing.productGroups[0].parameters[0].value=1;A.equal((await call('quotes/'+saved.data.id,'PUT',{document:d,expectedVersion:visibility.data.version})).status,403);});
