'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),P=require('../pricing-core.js'),I=require('../input-prices-core.js'),W=require('../work-core.js');
const rate=(extra={})=>({id:'VC-KG',name:'Nhập phôi / kg',category:'incoming',method:'kg_purchase',rate:1000,minimum:0,massBasis:'purchase',...extra});
test('records actual material price changes with old/new/unit/time; ignores unchanged and new material values',()=>{const before=[{id:'a',unit:'kg',price:100}],after=structuredClone(before);I.recordChanges(before,after);A.equal(after[0].priceHistory,undefined);for(let i=0;i<4;i++){const b=structuredClone(after);after[0].price+=100;I.recordChanges(b,after,'2026-09-15T01:00:00Z');}A.deepEqual(after[0].priceHistory.slice(0,3).map(h=>[h.from,h.to]),[[400,500],[300,400],[200,300]]);A.equal(after[0].priceHistory[0].unit,'kg');const b=structuredClone(after);after[0].price=-1;A.throws(()=>I.recordChanges(b,after),/không âm/);});
test('expense declarations validate without changing saved quote and independent snapshots use the existing logistics engine',()=>{const d=P.demoSeed(),before=JSON.stringify(d.quote);I.save(d,'expenseRates',rate());A.equal(JSON.stringify(d.quote),before);const e=I.applyExpense({id:'e',name:'Phí thử',scope:'all',allocation:'weight',repeats:1},rate()),base=P.calculate(d);const r=W.expenses([e],base,base.generated);A.deepEqual(r.errors,[]);A.ok(r.items[0].cost>0);A.equal(r.items[0].cost,r.items[0].basis*1000);I.save(d,'expenseRates',rate({rate:2000}));A.equal(e.rate,1000);A.equal(e.priceSource.rate,1000);d.quote.expenses=[e];I.refresh(d);A.equal(d.quote.expenses[0].rate,2000);A.equal(e.rate,1000);});
test('all declared cost methods are accepted and invalid values fail before catalogue mutation',()=>{const d=P.demoSeed();for(const [method]of W.METHODS)I.save(d,'expenseRates',rate({id:method,method}));A.equal(d.pricingDefaults.expenseRates.length,W.METHODS.length);const saved=JSON.stringify(d.pricingDefaults);for(const extra of [{rate:null},{rate:-1},{rate:''},{category:'bad'},{method:'bad'},{factors:[{id:'f',name:'bad',param:'T',tiers:[{max:null,percent:0}]}]}]){A.throws(()=>I.save(d,'expenseRates',rate(extra)));A.equal(JSON.stringify(d.pricingDefaults),saved);}});
test('TMC master supports custom tables, preserves extended settings, inherits independently, validates tiers',()=>{const d=P.demoSeed(),q=JSON.stringify(d.quote);I.save(d,'tmcTables',{id:'custom',name:'Cút máng',unit:'cái',tiers:[{max:100,price:500},{max:null,price:900}],common:{kind:'fixed',value:10}});A.equal(JSON.stringify(d.quote),q);const p=I.defaults(d);A.equal(P.tier(101,p.tmcTables.at(-1).tiers,'price').value,900);p.tmcTables.at(-1).tiers[0].price=1;A.equal(d.pricingDefaults.tmcTables.at(-1).tiers[0].price,500);A.throws(()=>I.save(d,'tmcTables',{id:'bad',name:'Bad',unit:'m',tiers:[{max:200,price:20},{max:100,price:10}]}));A.equal(d.pricingDefaults.tmcTables.at(-1).common.value,10);});
test('disabled or missing expense master remains unchanged on explicit refresh and manual costs stay manual',()=>{const d=P.demoSeed();d.quote.expenses=[I.applyExpense({id:'a'},rate()),{id:'b',rate:10,method:'fixed'}];I.save(d,'expenseRates',rate({enabled:false,rate:5000}));const saved=JSON.stringify(d.quote.expenses);I.refresh(d);A.equal(JSON.stringify(d.quote.expenses),saved);});

test('expense base-price choices bypass declared factors while factor choices apply once with identical quantity units',()=>{const d=P.demoSeed(),base=P.calculate(d),factors=[{id:'YT1',name:'Số chuyến',param:'trips',tiers:[{max:null,percent:20}]}],r=rate({method:'trip',rate:100000,factors}),entry={id:'e',scope:'all',allocation:'weight',repeats:1,trips:3};for(const [priceMode,expected]of [['catalog',300000],['factors',360000]]){const e=I.applyExpense(entry,{...r,priceMode}),out=W.expenses([e],base,base.generated);A.deepEqual(out.errors,[]);A.equal(out.items[0].cost,expected);A.equal(e.priceSource.factors.length,1);A.equal(e.factors.length,priceMode==='catalog'?0:1);}A.throws(()=>I.validateExpense({...r,priceMode:'bad'}));});

test('master TMC supports kg and area, exact thresholds and auxiliary costs without accepting malformed declarations',()=>{for(const unit of ['kg','m²']){const d=P.demoSeed(),row={id:'advanced',name:'Thử',unit,loss:2,thresholdMode:'exact',tiers:[{max:300,price:1000},{max:null,price:1500}],ancillary:{kind:'fixed',value:100},common:{kind:'percent',basis:'labor',value:10}};I.save(d,'tmcTables',row);A.deepEqual(I.defaults(d).tmcTables.at(-1),row);for(const extra of [{thresholdMode:'bad'},{ancillary:{kind:'percent',value:5,basis:'scope'}},{common:{kind:'percent',value:-1,basis:'labor'}}])A.throws(()=>I.save(d,'tmcTables',{...row,...extra}));}});
