'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),C=require('../core.js'),P=require('../pricing-core.js'),I=require('../intake-core.js'),CV=require('../conventions-core.js');
test('intake: customer validation keeps only public business contact fields',()=>{A.throws(()=>I.customer({name:''}));A.throws(()=>I.customer({name:'Khách thử',email:'bad'}));const x=I.customer({name:' Khách thử ',contact:'Người liên hệ',secret:'not kept'});A.equal(x.name,'Khách thử');A.equal(x.secret,undefined);});
test('intake: raw request creates independent products once and preserves specification/quantity',()=>{const d=P.demoSeed();d.quote.products=[];const x=I.requestLine({name:'Giá đỡ thử',specification:'CT3, dày 2 mm',qty:3,unit:'cái'});d.quote.request={items:[x],files:[]};I.addRequestProducts(d,[x.id]);I.addRequestProducts(d,[x.id]);A.equal(d.quote.products.length,1);A.equal(d.quote.products[0].qty,3);A.equal(d.quote.products[0].requestSpecification,x.specification);A.equal(d.quote.products[0].children.length,0);});
test('intake: template from request is cloned and no quantity or name is silently inherited',()=>{const d=P.demoSeed(),t=d.library.find(x=>x.templateKind==='product'),original=C.copy(t),x=I.requestLine({name:'Theo yêu cầu',qty:2,unit:'cái'});d.quote.request={items:[x],files:[]};const [id]=I.addRequestProducts(d,[x.id],{[x.id]:t.id});const n=d.quote.products.find(x=>x.id===id);A.equal(n.qty,2);A.equal(n.name,x.name);A.notEqual(n.children[0].id,t.children[0].id);A.deepEqual(t,original);});
test('intake: material pickers filter parents and reject incompatible combinations',()=>{const d=P.demoSeed();CV.save(d,'substances',{name:'Nhôm kiểm thử',density:2700,price:90000});CV.save(d,'grades',{name:'A6061',parent:'Nhôm kiểm thử',price:95000});CV.save(d,'characteristics',{name:'T6 thử',parent:'Nhôm kiểm thử'});A.ok(I.materialChoices(d,'grades','Thép').every(x=>x.parent==='Thép'));A.equal(I.materialChoices(d,'characteristics','Nhôm kiểm thử')[0].name,'T6 thử');A.throws(()=>I.validateMaterial(d,{substance:'Thép',grade:'A6061'}));A.doesNotThrow(()=>I.validateMaterial(d,{substance:'Nhôm kiểm thử',grade:'A6061',characteristic:'T6 thử'}));});
test('intake: used characteristics and materials with child declarations cannot be removed',()=>{const d=P.demoSeed();CV.save(d,'characteristics',{name:'Cán kiểm thử',parent:'Thép'});d.materials[0].characteristic='Cán kiểm thử';A.throws(()=>CV.remove(d,'characteristics','Cán kiểm thử'),/Đang dùng/);CV.save(d,'substances',{name:'Vật liệu riêng',density:10,price:1});CV.save(d,'characteristics',{name:'Đặc tính riêng',parent:'Vật liệu riêng'});A.throws(()=>CV.remove(d,'substances','Vật liệu riêng'),/Đang dùng/);});
test('intake: renaming parent relinks child catalogs and retains approved snapshots',()=>{const d=P.demoSeed();CV.save(d,'characteristics',{name:'Mạ riêng',parent:'Thép'});d.savedQuotes=[{quote:{...C.copy(d.quote),status:'approved'}}];const snapshot=C.copy(d.savedQuotes);CV.save(d,'substances',{name:'Thép đổi tên',density:7850,price:20000},'Thép');A.ok(CV.entries(d,'grades').filter(x=>x.parent==='Thép đổi tên').length);A.equal(CV.entries(d,'characteristics').find(x=>x.name==='Mạ riêng').parent,'Thép đổi tên');A.deepEqual(d.savedQuotes,snapshot);});
test('intake: suggestion is deterministic and includes shape, material and dimensions',()=>{const name=I.materialName({substance:'Thép',grade:'CT3',characteristic:'Cán nóng',shape:'sheet',props:{T:1.5}});A.match(name,/CT3/);A.match(name,/1,5 mm/);});
test('intake: quote-local selected material prices never rewrite catalogs or other quotes',()=>{const d=P.demoSeed(),master=C.copy(d.materials),rows=I.priceRows(d),r=rows[0];d.savedQuotes=[{quote:C.copy(d.quote)}];const other=C.copy(d.savedQuotes);I.applyMaterialPrices(d,[{key:r.key,value:23456,source:'manual'}]);A.ok(I.priceRows(d)[0].targets.every(x=>x.price===23456));A.deepEqual(d.materials,master);A.deepEqual(d.savedQuotes,other);A.equal(I.priceRows(d)[0].targets[0].priceSelection.source,'manual');});
test('intake: invalid price batch is atomic and missing reference is not zero',()=>{const d=P.demoSeed(),rows=I.priceRows(d),before=C.copy(d);A.throws(()=>I.applyMaterialPrices(d,[{key:rows[0].key,value:3},{key:rows[1].key,value:-1}]));A.deepEqual(d,before);d.materials=[];A.ok(I.priceRows(d).every(x=>x.reference===undefined));});
test('intake: finishing recipe prices participate in explicit quote price selection',()=>{const d=P.demoSeed(),row=I.priceRows(d).find(r=>r.owners.some(x=>x.startsWith('Định mức')));A.ok(row);I.applyMaterialPrices(d,[{key:row.key,value:123456}]);A.ok(row.targets.every(x=>x.price===123456));});
test('intake: legacy preview does not change source, migration archives exact prior quote and total',()=>{const d=C.seed(),before=C.copy(d),total=C.calculate(d).total.grand,v=I.legacyPreview(d);A.equal(v.before,total);A.deepEqual(d,before);I.convertLegacy(d);A.deepEqual(d.legacyArchives[0].quote,before.quote);A.equal(d.legacyArchives[0].total,total);A.deepEqual(d.quote.products,before.quote.products);A.ok(d.quote.pricing);A.equal(I.convertLegacy(d),false);A.equal(d.legacyArchives.length,1);});
test('intake: approved legacy quote becomes a new document without modifying saved approved quote',()=>{const d=C.seed();d.quote.status='approved';d.savedQuotes=[{quote:C.copy(d.quote)}];const old=C.copy(d.savedQuotes);I.convertLegacy(d);A.match(d.quote.id,/-MOI$/);A.equal(d.quote.status,'draft');A.deepEqual(d.savedQuotes,old);});
test('intake: request limits and file references validated before server storage',()=>{const q={request:{items:[],files:[]}};I.validateRequest(q);q.request.items=[{id:'a',name:'A',qty:0}];A.throws(()=>I.validateRequest(q));q.request.items=[];q.request.files=[{id:'../file',size:12,storage:'local'}];A.throws(()=>I.validateRequest(q));});

test('material name follows current readable sheet, tube and stainless conventions',()=>{
 A.equal(I.materialName({substance:'Thép',grade:'CT3',characteristic:'Cán nóng',shape:'sheet',props:{T:1.5}}),'Thép CT3 tấm dày 1,5 mm');
 A.equal(I.materialName({substance:'Thép',shape:'box',props:{W:40,H:40,T:2}}),'Thép hộp 40 × 40 × 2 mm');
 A.equal(I.materialName({substance:'Inox',grade:'SUS304',shape:'sheet',props:{T:1.5}}),'Inox 304 tấm dày 1,5 mm');
 A.match(I.materialName({substance:'Thép',shape:'pipe',props:{D:60,T:2},characteristic:'Mạ kẽm'}),/Ø60 × 2 mm, mạ kẽm/);
 A.match(I.materialName({shape:'profile',shapeDefinition:{name:'Dạng riêng',fields:[{key:'K',unit:'kg/m'}]},props:{K:4.5}}),/Dạng riêng, K 4,5 kg\/m/);
});
