'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),P=require('../pricing-core.js');
test('batch01 server: complete initial dossier and brand snapshots persist; invalid deadline rejected',async t=>{const {call,session}=await run(t),d=P.demoSeed();d.quote.customerInfo={id:'BATCH-CUSTOMER',name:'Khách thử',contact:'Liên hệ thử'};d.quote.customer='Khách thử';d.quote.request={code:'YC-TEST',items:[],files:[],notes:'Yêu cầu thử',recipient:'Bộ phận mua hàng',location:'Xưởng thử',quoteDeadline:'2026-09-30',schedule:'Giao từng đợt'};const m=d.materials.find(m=>m.id==='LK-CHAN');m.brand='Hãng thử A';m.specification='500 W';const saved=await call('quotes','POST',{document:d},session);A.equal(saved.status,201);const read=await call('quotes/'+saved.data.id,'GET',undefined,session);A.deepEqual(read.data.document.quote.request,d.quote.request);A.equal(read.data.document.materials.find(m=>m.id==='LK-CHAN').brand,'Hãng thử A');d.quote.id+='-INVALID';d.quote.request.quoteDeadline='2026-02-30';A.equal((await call('quotes','POST',{document:d},session)).status,400);});
async function run(t){const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port;
const call=async(route,method='GET',body,session)=>{const r=await fetch(base+'/api/'+route,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const s=await call('setup','POST',{username:'admin',name:'Quản trị thử',password:'Only-for-intake-tests-42!'});return {app,call,session:{cookie:s.cookie,csrf:s.data.csrf}};}
test('intake server: customer CAS, immutable quote contact, source file bytes and private endpoint permissions',async t=>{const {call,session}=await run(t);A.equal((await call('intake/customers')).status,401);const value={id:'C-TEST',name:'Khách kiểm thử',phone:'0900000123',secret:'omit'};const c=await call('intake/customers','POST',{customer:value,expectedVersion:0},session);A.equal(c.status,200);A.equal(c.data.version,1);A.equal(c.data.secret,undefined);A.equal((await call('intake/customers','POST',{customer:value,expectedVersion:0},session)).status,409);
const data=Buffer.from('San pham,So luong\nMang cap,2\n'),file={id:'file-test-1',name:'yeu-cau.csv',size:data.length,data:data.toString('base64')};A.equal((await call('intake/files','POST',file,session)).status,201);A.equal((await call('intake/files','POST',file,session)).status,409);const downloaded=await call('intake/files/'+file.id,'GET',undefined,session);A.deepEqual(Buffer.from(downloaded.data.data,'base64'),data);
const d=P.demoSeed();d.quote.customer=value.name;d.quote.customerInfo=c.data;d.quote.request={items:[],files:[{...file,data:undefined,storage:'server'}]};const q=await call('quotes','POST',{document:d},session);A.equal(q.status,201);A.equal((await call('intake/customers','POST',{customer:{...value,phone:'0900000999'},expectedVersion:1},session)).status,200);const saved=await call('quotes/'+q.data.id,'GET',undefined,session);A.equal(saved.data.document.quote.customerInfo.phone,value.phone);A.equal(saved.data.document.quote.request.files[0].id,file.id);
const account={username:'sales',name:'Kinh doanh thử',role:'sales',password:'Only-for-intake-tests-42!'};await call('users','POST',account,session);const login=await call('login','POST',account),sales={cookie:login.cookie,csrf:login.data.csrf};A.equal((await call('intake/customers','GET',undefined,sales)).status,403);A.equal((await call('intake/files/'+file.id,'GET',undefined,sales)).status,403);
});
test('intake server: rejects bad files, stale updates, read-only writes and malformed request data',async t=>{const {call,session}=await run(t);for(const f of [{id:'../escape',name:'a.pdf',size:1,data:'YQ=='},{id:'test',name:'a.html',size:1,data:'YQ=='},{id:'test',name:'a.pdf',size:99,data:'YQ=='},{id:'test',name:'a.pdf',size:1,data:'??'}])A.ok((await call('intake/files','POST',f,session)).status>=400);const doc=P.demoSeed();doc.quote.request={items:[{id:'x',qty:0}],files:[]};A.equal((await call('quotes','POST',{document:doc},session)).status,400);const acct={username:'approver',name:'Người duyệt',role:'approver',password:'Only-for-intake-tests-42!'};await call('users','POST',acct,session);const login=await call('login','POST',acct),viewer={cookie:login.cookie,csrf:login.data.csrf};A.equal((await call('intake/customers','POST',{customer:{name:'Không được tạo'},expectedVersion:0},viewer)).status,403);});
