const {chromium,expect}=require('@playwright/test'),{pathToFileURL}=require('node:url'),{createApp}=require('../server/app.cjs'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true}),folder=path.resolve('artifacts/phase1-2026-09-12');fs.mkdirSync(folder,{recursive:true});const errors=[],passed=[];let server;const p=await browser.newPage({viewport:{width:1440,height:1050}});p.on('pageerror',e=>errors.push(e.message));const check=text=>{passed.push(text);console.log('PASS '+text);},tab=id=>p.locator(`[data-tab="${id}"]`).click(),submit=()=>p.locator('#dialog button[type=submit]').click(),close=()=>p.locator('#dialog .dialog-head [data-action=close]').click();const reset=async()=>{await p.locator('[data-pa=sample]').click();await submit();};
try{
  await p.goto(pathToFileURL(path.resolve('dist/index.html')).href);await tab('operations');let root=await p.evaluate(()=>db.quote.products[0].id);
  await p.locator(`[data-mfg=package][data-id="${root}"]`).first().click();await p.locator('[name=enabled]').check();await p.locator('[name=supplier]').fill('Xưởng thử');await p.locator('[name=output]').fill('Giao hoàn chỉnh, chưa sơn');await p.locator('[name=price]').fill('150000');await submit();expect(await p.evaluate(()=>result.products[0].parts.stock)).toBe(0);expect(await p.evaluate(()=>result.products[0].parts.outside)).toBe(1500000);expect(await p.evaluate(()=>result.products[0].weight)).toBeCloseTo(94.2);check('Whole-product vendor supply removes purchasing and covered labor, retains geometry');
  await p.locator(`[data-pa=op-detail][data-id="${root}"]`).first().click();await p.locator('[name=afterPackage]').check();await submit();expect(await p.evaluate(()=>result.generated[0].quantity)).toBeCloseTo(1.92);expect(await p.evaluate(()=>result.products[0].parts.factory)).toBeCloseTo(105600);check('Post-receipt operation adds its labor and consumables once');
  await tab('waste');await p.locator('[data-remnant=review]').click();expect(await p.evaluate(()=>result.errors)).toEqual([]);await tab('operations');await p.screenshot({path:path.join(folder,'05-thue-tron.png'),fullPage:true});
  await p.locator(`[data-mfg=package][data-id="${root}"]`).first().click();await p.locator('[name=materialSupply]').selectOption('company');await submit();expect(await p.evaluate(()=>result.products[0].parts.stock)).toBeGreaterThan(0);expect(await p.evaluate(()=>result.products[0].parts.outside)).toBe(1500000);check('Changing supply responsibility restores stock without restoring included labor');
  await reset();await tab('operations');root=await p.evaluate(()=>db.quote.products[0].id);const kg=await p.evaluate(()=>result.alternatives.kg.total.grand);
  await p.locator(`[data-mfg=measure][data-id="${root}"]`).first().click();await p.locator('[name=weightFormula]').fill('BW * 0.9');await p.locator('[name=areaFormula]').fill('CA * 0.8');await expect(p.locator('#mfg-measure-preview')).toContainText('12,8');await submit();expect(await p.evaluate(()=>result.nodes[db.quote.products[0].id].workArea)).toBeCloseTo(12.8);expect(await p.evaluate(()=>result.generated[0].quantity)).toBeCloseTo(1.536);expect(await p.evaluate(()=>result.alternatives.kg.total.grand)).toBe(kg);check('Measurement formula previews and changes work quantities without changing kg-phoi offer');
  await p.locator(`[data-mfg=measure][data-id="${root}"]`).first().click();await p.locator('[name=areaFormula]').fill('CA/0');await submit();await expect(p.locator('#dialog-error')).toContainText('chia cho 0');await close();check('Invalid custom formula is rejected before saving');
  await reset();await tab('pricing');await p.locator('[data-pa=tmc]').click();await p.locator('[data-mfg=tmc-presets]').click();await expect(p.locator('.mfg-tmc-group')).toHaveCount(9);await p.locator('[name=loss-u-v-bar]').fill('2.5');await p.locator('[name=common-kind-u-v-bar]').selectOption('percent');await p.locator('[name=common-value-u-v-bar]').fill('2');await p.locator('[name=common-basis-u-v-bar]').selectOption('labor');await submit();expect(await p.evaluate(()=>db.quote.pricing.tmcTables.length)).toBe(9);check('Editable TMC groups include ladder fittings, covers, connectors, clamps and U/V');
  root=await p.evaluate(()=>db.quote.products[0].id);const component=await p.evaluate(()=>db.quote.products[0].children[0].id);await p.locator(`[data-mfg=breakdown][data-id="${root}"]`).click();const assignment=p.locator('.mfg-assignment');await assignment.locator('select[name^=target]').selectOption(component);await assignment.locator('select[name^=table]').selectOption('u-v-bar');await assignment.locator('input[name^=width]').fill('400');await submit();expect(await p.evaluate(()=>result.alternatives.tmc.products[0].tmc.items[0].rate)).toBe(7000);expect(await p.evaluate(()=>result.alternatives.tmc.products[0].parts.tmcCommon)).toBe(1400);check('TMC composition uses selected component, group unit, private loss and explicit cost basis');
  await p.locator(`[data-mfg=breakdown][data-id="${root}"]`).click();await p.locator('[data-mfg=add-assignment]').click();await submit();await expect(p.locator('#dialog-error')).toContainText('chồng');await close();check('Overlapping TMC scopes cannot silently double bill materials');
  await p.screenshot({path:path.join(folder,'06-tmc-cau-thanh.png'),fullPage:true});await p.setViewportSize({width:390,height:844});for(const name of ['operations','mass','pricing']){await tab(name);expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}await p.screenshot({path:path.join(folder,'07-mobile-mo-rong.png'),fullPage:true});check('Manufacturing additions remain usable without page overflow on mobile');
  await p.setViewportSize({width:1440,height:1050});await p.locator('[data-page=rules]').click();await p.locator('[data-action=new-rule]').click();await p.locator('[name=name]').fill('Quy tắc thử có lỗ');await p.locator('#dialog details summary').click();await p.locator('[name=weightFormula]').fill('BW * 0.9');await p.locator('[name=areaFormula]').fill('SA * 0.8');await expect(p.locator('#formula-test')).toContainText('9 kg / 1,6 m²');await submit();expect(await p.evaluate(()=>db.rules.at(-1).measurementRules.area)).toBe('SA * 0.8');check('One reusable rule editor saves unfolding and custom work quantities together');
  await p.locator('[data-page=rates]').click();await p.locator('[data-rate-tab=operations]').click();await p.locator('[data-rate-lab]').first().click();await expect(p.locator('#rate-lab-result')).toContainText('Đơn giá kết hợp hai yếu tố');expect(await p.locator('#rate-lab-result td').count()).toBeGreaterThan(1);const matrix=p.waitForEvent('download');await submit();await (await matrix).saveAs(path.join(folder,'ma-tran-don-gia.xlsx'));await p.locator('[name=axis-y]').selectOption(await p.locator('[name=axis-x]').inputValue());await expect(p.locator('#rate-lab-result')).toContainText('Hai trục cần dùng hai tham số khác nhau');await close();const ratebook=p.waitForEvent('download');await p.locator('[data-rate-export]').click();await (await ratebook).saveAs(path.join(folder,'bang-don-gia.xlsx'));check('Rate sandbox exposes factor traces, two-axis prices and private Excel ratebook');
  await p.locator('[data-page=quote]').click();await reset();await p.locator('[data-action=quote-info]').click();await p.locator('[name=documentMode]').selectOption('official');await p.locator('[name=issuer-name]').fill('TRƯỜNG PHÁT — KIỂM THỬ');await p.locator('[name=issuer-signer]').fill('Người ký thử');await p.locator('[name=notes]').fill('Điều kiện thử nghiệm, không giao dịch.');await submit();await tab('preview');await expect(p.locator('#content .paper')).toHaveCount(0);await p.locator('[data-work=export-customer-xlsx]').click();await expect(p.locator('#toast')).toContainText('Duyệt bản chào');await p.locator('[data-action=approve]').click();await submit();await expect(p.locator('#content .paper')).toContainText('TRƯỜNG PHÁT — KIỂM THỬ');await expect(p.locator('#content .paper')).toContainText('Người ký thử');await expect(p.locator('#content .paper')).toContainText('Bản chào đã duyệt');await expect(p.locator('#content .paper')).not.toContainText('BẢN MINH HỌA NGHIỆP VỤ');const official=p.waitForEvent('download');await p.locator('[data-work=export-customer-xlsx]').click();await (await official).saveAs(path.join(folder,'official-CHAO-GIA.xlsx'));await p.screenshot({path:path.join(folder,'09-ban-chao-da-duyet.png'),fullPage:true});check('Official customer output requires approval, carries issuer/signature and keeps costs private');
  const app=createApp();server=app.server;await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port,a=await browser.newPage({viewport:{width:1440,height:1050}});a.on('pageerror',e=>errors.push(e.message));await a.goto(url);const asubmit=()=>a.locator('#dialog button[type=submit]').click();await a.locator('#team-entry').click();await a.locator('[name=username]').fill('admin');await a.locator('[name=name]').fill('Quản trị');await a.locator('[name=password]').fill('Only-for-browser-tests-42!');await asubmit();await a.locator('#dialog [data-team=save]').click();
  await a.locator('.team-banner [data-team=list]').click();await a.locator('[data-access=catalog]').click();await a.locator('[data-access=catalog-publish]').click();await asubmit();await expect(a.locator('#dialog')).toContainText('Phiên bản 1');await a.locator('#dialog .dialog-head [data-action=close]').click();check('Shared catalog publishes from real controls with a version number');
  await a.locator('.team-banner [data-team=submit]').click();await asubmit();await a.locator('.team-banner [data-team=approve]').click();await asubmit();await a.locator('.team-banner [data-team=list]').click();await a.locator('[data-team=users]').click();await a.locator('[data-access=new-user]').click();await a.locator('[name=username]').fill('sales');await a.locator('[name=name]').fill('Kinh doanh thử');await a.locator('[name=role]').selectOption('sales');await a.locator('[name=password]').fill('Only-for-browser-tests-42!');await asubmit();await expect(a.locator('#dialog')).toContainText('Kinh doanh — chỉ xem giá bán đã duyệt');await a.locator('#dialog .dialog-head [data-action=close]').click();check('User management creates a sales-only role with explicit data rights');
  const salesContext=await browser.newContext(),s=await salesContext.newPage();s.on('pageerror',e=>errors.push(e.message));const responses=[];s.on('response',r=>{if(r.url().includes('/api/quotes/'))responses.push(r.json());});await s.goto(url);await s.locator('#team-entry').click();await s.locator('[name=username]').fill('sales');await s.locator('[name=password]').fill('Only-for-browser-tests-42!');await s.locator('#dialog button[type=submit]').click();await s.locator('#dialog [data-team=open]').first().click();await expect(s.locator('#content .paper')).toContainText('7.126.053');await expect(s.locator('#content')).not.toContainText('Giá gốc');await expect(s.locator('#content [data-tab=pricing]')).toHaveCount(0);const payloads=await Promise.all(responses);expect(payloads.length).toBeGreaterThan(0);expect(payloads[0].document).toBeUndefined();expect(payloads[0].offer.totals.cost).toBeUndefined();check('Sales browser receives only public offer data, not merely hidden cost columns');
  const dl=s.waitForEvent('download');await s.locator('[data-access=sales-excel]').click();await (await dl).saveAs(path.join(folder,'sales-CHAO-GIA.xlsx'));await s.screenshot({path:path.join(folder,'08-quyen-kinh-doanh.png'),fullPage:true});await s.locator('#content [data-team=logout]').click();await expect(s.locator('#content .paper')).toHaveCount(0);await expect(s.locator('body')).not.toHaveClass(/team-sales/);check('Sales exports customer XLSX and logout clears its restricted screen');
  await a.context().clearCookies();await a.locator('.team-banner [data-team=list]').click();await expect(a.locator('#content')).toContainText('Phiên đăng nhập đã kết thúc');await a.locator('#content .notice [data-team=login]').click();await a.locator('[name=username]').fill('admin');await a.locator('[name=password]').fill('Only-for-browser-tests-42!');await asubmit();await expect(a.locator('#dialog')).toContainText('Báo giá dùng chung');check('Expired session locks editing and supports sign-in again without a broken screen');
  await a.locator('[data-access=new-document]').click();await a.locator('[name=code]').fill('NEW-FROM-MASTER');await a.locator('[name=customer]').fill('Khách thử danh mục');await a.locator('[name=project]').fill('Luồng tạo mới');await asubmit();await expect.poll(()=>a.evaluate(()=>db.quote.id)).toBe('NEW-FROM-MASTER');expect(await a.evaluate(()=>db.quote.products.length)).toBe(0);expect(await a.evaluate(()=>db.quote.ratesSnapshot.length)).toBeGreaterThan(0);await expect(a.locator('.team-banner')).toContainText('Phiên bản 1');check('New server quote starts empty with shared catalog snapshots, no old sample products');
  expect(errors).toEqual([]);check('No runtime errors across manufacturing, catalog and restricted-role flows');fs.writeFileSync(path.join(folder,'manufacturing-browser-results.json'),JSON.stringify({passed,errors},null,2));
}catch(e){await p.screenshot({path:path.join(folder,'manufacturing-failure.png'),fullPage:true});console.error(errors);throw e;}finally{await browser.close();if(server)await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
