const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../core.js'),P=require('../pricing-core.js');
const near=(a,b)=>assert.ok(Math.abs(a-b)<.00001,`${a} != ${b}`);
const seed=()=>{const d=P.demoSeed();d.quote.remnantMode='all';d.quote.remnantSelections={};return d;};
const pack=(extra={})=>({enabled:true,supplier:'Xưởng đối tác',output:'Hoàn chỉnh theo bản vẽ',materialSupply:'vendor',unit:'cái',price:100000,...extra});
test('manufacturing: entire outsourced product removes covered purchasing and workshop work, retains geometry',()=>{const d=seed(),n=d.quote.products[0];n.outsource=pack();const r=P.calculate(d),p=r.products[0];near(p.parts.stock,0);near(p.parts.ancillary,0);near(p.parts.factory,0);near(p.parts.finishing,0);near(p.parts.outside,1000000);near(p.weight,94.2);assert.ok(r.rows.filter(x=>x.productId===n.id).every(x=>x.externallySupplied&&x.cost===0));assert.equal(r.groups.length,1);assert.ok(r.groups[0].rows.every(x=>x.productId!==n.id));assert.equal(r.packages.length,1);assert.deepEqual(r.errors,[]);});
test('manufacturing: company-supplied outsourced component keeps material procurement but no duplicate labor',()=>{const d=seed(),n=d.quote.products[0].children[0];n.outsource=pack({materialSupply:'company'});const r=P.calculate(d);assert.ok(r.nodes[n.id].parts.stock>0);near(r.nodes[n.id].parts.factory,0);near(r.nodes[n.id].parts.outside,1000000);assert.ok(r.rows.find(x=>x.coveredBy===n.id).purchasedWeight>0);assert.deepEqual(r.errors,[]);});
test('manufacturing: work after delivery adds only that operation and its finishing consumption',()=>{const d=seed(),n=d.quote.products[0];n.outsource=pack();n.ops[0].afterPackage=true;const r=P.calculate(d);near(r.products[0].parts.factory,105600);near(r.products[0].parts.finishing,153600);near(r.products[0].parts.outside,1000000);assert.equal(r.generated.length,1);assert.ok(r.nodes[n.children[0].id].ownOps.every(x=>x.skipped));});
test('manufacturing: outer package suppresses nested package, preserves configurations when disabled',()=>{const d=seed(),n=d.quote.products[0];n.outsource=pack();n.children[0].outsource=pack({price:999999});const r=P.calculate(d);near(r.products[0].parts.outside,1000000);assert.equal(r.packages.length,1);n.outsource.enabled=false;near(P.calculate(d).nodes[n.children[0].id].packageCharge.cost,9999990);});
test('manufacturing: fixed whole package and work kilograms use unambiguous bases',()=>{const d=seed(),n=d.quote.products[0];n.outsource=pack({unit:'gói',price:1200000});near(P.calculate(d).products[0].parts.outside,1200000);n.outsource.unit='kg';n.outsource.price=10000;n.measurementRules={weight:'BW * 0.9'};near(P.calculate(d).products[0].parts.outside,94.2*.9*10000);});
test('manufacturing: incomplete package is blocked and externally supplied stock needs no own material price',()=>{const d=seed(),n=d.quote.products[0];n.outsource=pack({supplier:''});assert.ok(P.calculate(d).errors.some(x=>x.includes('đơn vị')));n.outsource.supplier='A';for(const leaf of C.flatten([n]).filter(x=>x.kind==='material'))leaf.spec.price=null;assert.deepEqual(P.calculate(d).errors,[]);});
test('manufacturing: reusable measurement formula changes work and consumables, never physical stock or kg-phoi method',()=>{const d=seed(),p=d.quote.products[0],leaf=p.children[0].children[0],before=P.calculate(d);leaf.ruleSpec.measurementRules={weight:'BW - hole',area:'SA * factor',vars:{hole:.2,factor:.75}};const r=P.calculate(d);near(r.nodes[leaf.id].workWeight,before.nodes[leaf.id].weight-2);near(r.nodes[p.id].workArea,12);near(r.generated[0].quantity,12*.12);near(r.total.weight,before.total.weight);near(r.groups[0].purchasedWeight,before.groups[0].purchasedWeight);near(r.alternatives.kg.total.grand,before.alternatives.kg.total.grand);});
test('manufacturing: parent measurement override uses child totals once and custom variables survive JSON',()=>{const d=seed(),n=d.quote.products[0];n.measurementRules={weight:'CW * ratio',area:'CA + plus',vars:{ratio:.9,plus:.5}};const r=P.calculate(JSON.parse(JSON.stringify(d)));near(r.nodes[n.id].workWeight,94.2*.9);near(r.nodes[n.id].workArea,21);near(r.generated[0].quantity,21*.12);});
test('manufacturing: invalid formulas, variable collisions and excessive nesting block calculations',()=>{for(const rules of [{weight:'BW/0'},{area:'-1'},{weight:'BW',vars:{BW:1}},{weight:'window.alert(1)'},{weight:'('.repeat(21)+'BW'+')'.repeat(21)}]){const d=seed();d.quote.products[0].measurementRules=rules;assert.ok(P.calculate(d).errors.length);}});
test('manufacturing: composite TMC partition applies independent losses, quantities and supplementary cost',()=>{const d=seed(),n=d.quote.products[0],second=C.cloneNode(n.children[0]);second.name='Nắp';n.children.push(second);const a=n.children[0],b=second;d.quote.pricing.tmcTables.push({id:'special',name:'Nắp riêng',unit:'cái',loss:3,tiers:[{max:null,price:1500}],ancillary:{kind:'fixed',value:100},common:{kind:'percent',value:2,basis:'labor'}});n.tmcBreakdown=[{id:'a',nodeId:a.id,tableId:'tray',width:300,length:2000},{id:'b',nodeId:b.id,tableId:'special',width:300}];const r=P.calculate(d),p=r.alternatives.tmc.products[0];assert.deepEqual(r.alternatives.tmc.errors,[]);assert.equal(p.tmc.items.length,2);near(p.parts.stock,94.2*20000*(1.015+1.03));near(p.tmc.items[1].labor,15000);near(p.tmc.items[1].ancillary,1000);near(p.parts.tmcCommon,300);});
test('manufacturing: TMC rejects overlapping, missing and stale physical scopes',()=>{for(const mode of ['overlap','missing','stale']){const d=seed(),n=d.quote.products[0],a=n.children[0];n.tmcBreakdown=[{id:'a',nodeId:mode==='stale'?'gone':mode==='missing'?n.children[1].id:a.id,tableId:'tray',width:300,length:2000}];if(mode==='overlap')n.tmcBreakdown.push({id:'b',nodeId:n.id,tableId:'tray',width:300,length:2000});assert.ok(P.calculate(d).alternatives.tmc.errors.length);}});
test('manufacturing: custom TMC group applies width boundary and is independent of detailed costing',()=>{const d=seed(),before=P.calculate(d);d.quote.pricing.tmcTables.push({id:'u-bar',name:'Thanh U/V',unit:'cái',loss:2,tiers:[{max:400,price:7000},{max:700,price:10000},{max:null,price:30000}]});d.quote.products[0].tmcKind='u-bar';d.quote.products[0].tmcWidth=400;const r=P.calculate(d);near(r.total.grand,before.total.grand);near(r.alternatives.tmc.products[0].tmc.rate,7000);d.quote.products[0].tmcWidth=401;near(P.calculate(d).alternatives.tmc.products[0].tmc.rate,10000);});
test('manufacturing: calculation stays pure with package, measurements and TMC',()=>{const d=seed();d.quote.products[0].outsource=pack();d.quote.products[1].measurementRules={area:'CA * 0.9'};const before=JSON.stringify(d);P.calculate(d);assert.equal(JSON.stringify(d),before);});

test('manufacturing: exact TMC sizes never silently use the next price tier',()=>{const d=seed(),n=d.quote.products[0],table=d.quote.pricing.tmcTables.find(t=>t.id===n.tmcKind);table.thresholdMode='exact';d.quote.products[1].tmcWidth=100;n.tmcWidth=100;assert.equal(P.calculate(d).alternatives.tmc.errors.length,0);n.tmcWidth=101;assert.ok(P.calculate(d).alternatives.tmc.errors.some(e=>e.includes('đúng khổ')));n.tmcWidth=1200;assert.equal(P.calculate(d).alternatives.tmc.errors.length,0);});
