'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),P=require('../pricing-core.js'),T=require('../tax-core.js');
test('server saves and approves mixed VAT, preserves approved tax breakdown after draft rate change',async t=>{
 const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port;let cookie,csrf;
 const call=async(path,method='GET',body)=>{const r=await fetch(base+'/api/'+path,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie,'X-CSRF-Token':csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];if(data.csrf)csrf=data.csrf;return {status:r.status,data};};
 await call('setup','POST',{username:'admin',name:'QA Admin',password:'Local-mixed-VAT-tests-42!'});const d=P.demoSeed(),q=d.quote;q.remnantMode='all';q.documentMode='official';q.issuer={name:'QA issuer'};require('./offer-fixture.cjs')(q);q.pricing.selected='competitor';q.products.forEach(n=>n.competitorPrice=1100000);q.outputTax={scope:'product',rates:{[q.products[0].id]:8,[q.products[1].id]:10}};
 T.review(q,{reason:'QA synthetic source',costConfirmed:true,outputConfirmed:true,inputs:Object.fromEntries(q.products.map(n=>[n.id,{competitor:{status:'included',rate:10}}]))});
 const saved=await call('quotes','POST',{document:d});A.equal(saved.status,201);const sub=await call('quotes/'+saved.data.id+'/submit','POST',{expectedVersion:1});A.equal(sub.status,200,JSON.stringify(sub));const ap=await call('quotes/'+saved.data.id+'/approve','POST',{expectedVersion:sub.data.version});A.equal(ap.status,200,JSON.stringify(ap));const read=await call('quotes/'+saved.data.id),offer=read.data.document.quote.approvedOffer;
 A.equal(offer.totals.beforeTax,20000000);A.equal(offer.totals.vat,1800000);A.equal(offer.totals.grand,21800000);A.deepEqual(offer.taxBreakdown.map(g=>g.rate),[8,10]);A.deepEqual(read.data.document.quote.outputTax,q.outputTax);
 const reopened=await call('quotes/'+saved.data.id+'/reopen','POST',{expectedVersion:ap.data.version,reason:'QA changed output VAT'});q.outputTax.rates[q.products[0].id]=0;const changed=await call('quotes/'+saved.data.id,'PUT',{document:d,expectedVersion:reopened.data.version});A.equal(changed.status,200);A.equal((await call('quotes/'+saved.data.id+'/submit','POST',{expectedVersion:changed.data.version})).status,422);const old=await call('quotes/'+saved.data.id+'/revision/'+ap.data.version);A.deepEqual(old.data.document.quote.approvedOffer,offer);
});
