'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),P=require('../pricing-core.js');
test('technical handoff ignores legacy bookkeeping IDs and prices but tracks quantities and norms',()=>{
 const {fingerprints}=require('../server/notifications.cjs'),d=P.demoSeed(),initial=fingerprints(d).technical;
 d.quote.products[0].ops[0].instanceId='new-legacy-id';d.quote.ratesSnapshot.find(r=>r.consumption).consumption.id='new-recipe-id';d.quote.products[0].children[0].children[0].spec.price+=100;
 A.equal(fingerprints(d).technical,initial);d.quote.ratesSnapshot.find(r=>r.consumption).consumption.norm+=1;A.notEqual(fingerprints(d).technical,initial);
});
test('handoff notifications route by permissions, persist read state, reject stale confirmations and avoid duplicates',async t=>{
 const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port;
 async function call(route,method='GET',body,session){const r=await fetch(base+'/api/'+route,{method,headers:{'Content-Type':'application/json',...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};}
 const password='Local-notifications-tests-42!',admin=await call('setup','POST',{username:'admin',name:'Admin',password}),sessions={admin},users={};
 for(const [username,role,sections]of [['tech','technical',['bom','operations']],['materials','estimator',['materials']],['approver','approver',[]],['other','estimator',['logistics']],['disabled','estimator',['materials']]]){const b={username,role,name:username,password,sections};users[username]=(await call('users','POST',b,admin)).data;sessions[username]=await call('login','POST',b);}
 await call('users/'+users.disabled.id+'/disable','POST',{},admin);
 const d=P.demoSeed();d.quote.remnantMode='all';const created=await call('quotes','POST',{document:d},admin),id=created.data.id,path='quotes/'+id+'/handoff';A.equal(created.status,201);A.equal(created.data.technicalRecipients,2);const newInbox=(await call('notifications','GET',undefined,sessions.tech)).data;A.equal(newInbox.items[0].stage,'created');A.equal(newInbox.items[0].quoteId,id);A.equal((await call('notifications','GET',undefined,sessions.materials)).data.items.length,0);
 A.equal((await call('notifications')).status,401);A.equal((await call(path+'/materials','POST',{expectedVersion:1},sessions.materials)).status,409);A.equal((await call(path+'/technical','POST',{expectedVersion:1},sessions.materials)).status,403);
 let r=await call(path+'/technical','POST',{expectedVersion:1,note:'Technical ready'},sessions.tech);A.equal(r.status,200,JSON.stringify(r.data));A.equal(r.data.recipients,3);A.equal(r.data.state.technical.current,true);A.equal(r.data.state.technical.signature,undefined);
 const savedHandoff=app.sql.prepare('SELECT document FROM quote_handoffs WHERE quote_id=?').get(id).document,legacyState=JSON.parse(savedHandoff);legacyState.technical.signature='old-stale-confirmation';app.sql.prepare('UPDATE quote_handoffs SET document=? WHERE quote_id=?').run(JSON.stringify(legacyState),id);
 d.quote.products[0].qty++;A.equal((await call('quotes/'+id,'PUT',{document:d,expectedVersion:1},admin)).status,409,'A stale confirmation still requires explicit reopening');d.quote.products[0].qty--;app.sql.prepare('UPDATE quote_handoffs SET document=? WHERE quote_id=?').run(savedHandoff,id);
 A.equal((await call(path+'/technical','POST',{expectedVersion:1},sessions.tech)).data.duplicate,true);A.equal(app.sql.prepare('SELECT COUNT(*) n FROM handoff_events').get().n,2);
 const inbox=(await call('notifications','GET',undefined,sessions.materials)).data;A.equal(inbox.unread,1);A.equal(inbox.items[0].stage,'technical');A.equal((await call('notifications','GET',undefined,sessions.other)).data.items.length,0);A.equal((await call('notifications','GET',undefined,sessions.tech)).data.items.length,1);
 A.equal((await call('notifications/'+inbox.items[0].id+'/read','POST',{},sessions.other)).status,404);A.equal((await call('notifications/'+inbox.items[0].id+'/read','POST',{},sessions.materials)).status,200);A.equal((await call('notifications','GET',undefined,sessions.materials)).data.unread,0);
 d.quote.products[0].children[0].children[0].spec.price+=100;const priceSave=await call('quotes/'+id,'PUT',{document:d,expectedVersion:1},sessions.materials);A.equal(priceSave.status,200);A.equal((await call(path,'GET',undefined,sessions.tech)).data.technical.current,true);
 r=await call(path+'/materials','POST',{expectedVersion:2,note:'Private price note'},sessions.materials);A.equal(r.status,200,JSON.stringify(r.data));A.equal(r.data.recipients,2);A.equal((await call('notifications','GET',undefined,sessions.approver)).data.unread,2);A.equal((await call(path+'/materials','POST',{expectedVersion:2},sessions.materials)).data.duplicate,true);
 const technicalState=(await call(path,'GET',undefined,sessions.tech)).data;A.equal(technicalState.materials.note,undefined);A.ok(!JSON.stringify(technicalState).includes('Private price note'));
 d.quote.products[0].ops[0].amount=2;
 A.equal((await call('quotes/'+id,'PUT',{document:d,expectedVersion:2},admin)).status,409);
 A.equal((await call(path+'/technical/reopen','POST',{expectedVersion:2,reason:'Đổi định mức'},sessions.materials)).status,403);
 A.equal((await call(path+'/technical/reopen','POST',{expectedVersion:2,reason:''},sessions.tech)).status,403);
 A.equal((await call(path+'/technical/reopen','POST',{expectedVersion:1,reason:'Đổi định mức'},sessions.tech)).status,409);
 A.equal((await call(path+'/technical/reopen','POST',{expectedVersion:2,reason:'Đổi định mức'},sessions.tech)).status,403);const unlocked=await call(path+'/technical/reopen','POST',{expectedVersion:2,reason:'Đổi định mức'},admin);A.equal(unlocked.status,200,JSON.stringify(unlocked.data));A.equal(unlocked.data.state.technical.current,false);A.equal(unlocked.data.state.materials.current,false);A.equal(unlocked.data.state.materials.changeReason,'Đổi định mức');
 A.ok((await call('notifications','GET',undefined,sessions.materials)).data.items.some(n=>n.note.includes('Đổi định mức')));
 A.equal((await call('quotes/'+id,'PUT',{document:d,expectedVersion:2},admin)).status,200);const changed=(await call(path,'GET',undefined,admin)).data;A.equal(changed.technical.current,false);A.equal(changed.materials.current,false);
 A.equal((await call(path+'/materials','POST',{expectedVersion:3},sessions.materials)).status,409);A.equal((await call(path+'/technical','POST',{expectedVersion:2},sessions.tech)).status,409);
 const parallel=await Promise.all([1,2].map(()=>call(path+'/technical','POST',{expectedVersion:3},sessions.tech)));A.deepEqual(parallel.map(x=>x.data.duplicate).sort(),[false,true]);A.equal(app.sql.prepare('SELECT COUNT(*) n FROM handoff_events').get().n,6);
 app.sql.prepare('UPDATE users SET section_access=? WHERE id=?').run(JSON.stringify(['logistics']),users.materials.id);A.equal((await call('notifications','GET',undefined,sessions.materials)).data.items.length,0);
 app.sql.prepare("UPDATE quotes SET status='submitted' WHERE id=?").run(id);A.equal((await call(path+'/intake/reopen','POST',{expectedVersion:3,reason:'Không được mở bản khóa'},admin)).status,409);A.equal((await call(path+'/technical','POST',{expectedVersion:3},sessions.tech)).status,409);
 const empty=P.demoSeed();empty.quote.id='BG-EMPTY-NOTIFICATIONS';empty.quote.products=[];const emptyCreated=await call('quotes','POST',{document:empty},admin);A.equal(emptyCreated.status,201);const emptyId=emptyCreated.data.id;A.equal((await call('quotes/'+emptyId+'/handoff/technical','POST',{expectedVersion:1},sessions.tech)).status,422);
 const summary=(await call('quotes','GET',undefined,admin)).data.find(q=>q.id===id);A.equal(summary.progress.technical.current,true);A.equal(summary.progress.materials.current,false);A.equal(summary.progress.sentCount,0);A.ok(!JSON.stringify(summary.progress).includes('signature'));const technicalList=(await call('quotes','GET',undefined,sessions.tech)).data;A.equal(technicalList.find(q=>q.id===id).progress.technical.current,true);A.equal(technicalList.find(q=>q.id===id).total,undefined);
 const backup=(await call('backup','GET',undefined,admin)).data;A.equal(backup.handoffEvents.length,7);A.equal(backup.handoffs.length,1);A.equal(backup.notifications.length,17);
});

test('intake confirmation is permissioned, versioned and tracks only customer/request data',async t=>{
 const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port;
 const call=async(route,method='GET',body,session)=>{const r=await fetch(base+'/api/'+route,{method,headers:{'Content-Type':'application/json',...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};};
 const password='Intake-confirmation-test-42!',admin=await call('setup','POST',{username:'admin',name:'Admin',password});await call('users','POST',{username:'tech',name:'Tech',password,role:'technical',sections:['bom','operations']},admin);const tech=await call('login','POST',{username:'tech',password});
 let d=P.demoSeed();const created=await call('quotes','POST',{document:d},admin),id=created.data.id,path='quotes/'+id+'/handoff';A.equal(created.status,201);A.equal((await call(path,'GET',undefined,admin)).data.intake,null);
 A.equal((await call(path+'/intake','POST',{expectedVersion:1},tech)).status,403);A.equal((await call(path+'/intake','POST',{expectedVersion:0},admin)).status,409);
 const confirmed=await call(path+'/intake','POST',{expectedVersion:1,note:'Input checked'},admin);A.equal(confirmed.status,200,JSON.stringify(confirmed.data));A.equal(confirmed.data.state.intake.current,true);A.equal(confirmed.data.state.intake.actor,'Admin');A.equal(confirmed.data.state.intake.signature,undefined);A.equal((await call(path+'/intake','POST',{expectedVersion:1},admin)).data.duplicate,true);
 A.ok((await call('notifications','GET',undefined,tech)).data.items.some(x=>x.stage==='intake'));A.equal((await call(path,'GET',undefined,tech)).data.intake.note,undefined);
 d=(await call('quotes/'+id,'GET',undefined,admin)).data.document;d.quote.products[0].qty++;A.equal((await call('quotes/'+id,'PUT',{document:d,expectedVersion:1},admin)).status,200);A.equal((await call(path,'GET',undefined,admin)).data.intake.current,true);
 d.quote.project+=' revised';A.equal((await call('quotes/'+id,'PUT',{document:d,expectedVersion:2},admin)).status,409);
 A.equal((await call(path+'/intake/reopen','POST',{expectedVersion:2,reason:'Khách đổi yêu cầu'},admin)).status,200);A.equal((await call('quotes/'+id,'PUT',{document:d,expectedVersion:2},admin)).status,200);A.equal((await call(path,'GET',undefined,admin)).data.intake.current,false);A.equal((await call(path+'/intake','POST',{expectedVersion:3},admin)).status,200);A.equal((await call('quotes','GET',undefined,admin)).data.find(q=>q.id===id).progress.intake.current,true);
 app.sql.prepare("UPDATE quotes SET status='submitted' WHERE id=?").run(id);A.equal((await call(path+'/intake/reopen','POST',{expectedVersion:3,reason:'Không được mở bản khóa'},admin)).status,409);A.equal((await call(path+'/intake','POST',{expectedVersion:3},admin)).status,409);
});

test('cost confirmation ignores bookkeeping but still tracks prices, quantities and tax evidence',()=>{
 const Tax=require('../tax-core.js'),{fingerprints}=require('../server/notifications.cjs'),d=P.demoSeed(),old=fingerprints(d).materials;
 d.quote.products[0].ops[0].instanceId='generated-on-open';d.quote.ratesSnapshot.find(r=>r.consumption).consumption.id='generated-recipe';
 A.equal(fingerprints(d).materials,old);d.quote.products[0].qty++;A.notEqual(fingerprints(d).materials,old);
 const a=JSON.stringify({costSources:{a:{original:100,net:100,status:'excluded',at:'old'}}}),b=JSON.stringify({costSources:{a:{original:100,net:100,status:'excluded',at:'new'}}});A.equal(Tax.canonicalCostSignature(a),Tax.canonicalCostSignature(b));A.notEqual(Tax.canonicalCostSignature(a),Tax.canonicalCostSignature(b.replace('excluded','included')));
});
