'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),P=require('../pricing-core.js');
test('technical handoff ignores legacy bookkeeping IDs and prices but tracks quantities and norms',()=>{
 const {fingerprints}=require('../server/notifications.cjs'),d=P.demoSeed(),initial=fingerprints(d).technical;
 d.quote.products[0].ops[0].instanceId='new-legacy-id';d.quote.ratesSnapshot.find(r=>r.consumption).consumption.id='new-recipe-id';d.quote.products[0].children[0].children[0].spec.price+=100;
 A.equal(fingerprints(d).technical,initial);d.quote.ratesSnapshot.find(r=>r.consumption).consumption.norm+=1;A.notEqual(fingerprints(d).technical,initial);
});
test('handoff notifications route by permissions, persist read state, reject stale confirmations and avoid duplicates',async t=>{
 const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port;
 async function call(route,method='GET',body,session){const r=await fetch(base+'/api/'+route,{method,headers:{'Content-Type':'application/json',...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};}
 const password='Local-notifications-tests-42!',admin=await call('setup','POST',{username:'admin',name:'Admin',password}),sessions={admin},users={};
 for(const [username,role,sections]of [['tech','technical',['bom','operations']],['materials','estimator',['materials']],['approver','approver',[]],['other','estimator',['logistics']],['disabled','estimator',['materials']]]){const b={username,role,name:username,password,sections};users[username]=(await call('users','POST',b,admin)).data;sessions[username]=await call('login','POST',b);}
 await call('users/'+users.disabled.id+'/disable','POST',{},admin);
 const d=P.demoSeed();d.quote.remnantMode='all';const created=await call('quotes','POST',{document:d},admin),id=created.data.id,path='quotes/'+id+'/handoff';A.equal(created.status,201);
 A.equal((await call('notifications')).status,401);A.equal((await call(path+'/materials','POST',{expectedVersion:1},sessions.materials)).status,409);A.equal((await call(path+'/technical','POST',{expectedVersion:1},sessions.materials)).status,403);
 let r=await call(path+'/technical','POST',{expectedVersion:1,note:'Technical ready'},sessions.tech);A.equal(r.status,200,JSON.stringify(r.data));A.equal(r.data.recipients,3);A.equal(r.data.state.technical.current,true);A.equal(r.data.state.technical.signature,undefined);
 A.equal((await call(path+'/technical','POST',{expectedVersion:1},sessions.tech)).data.duplicate,true);A.equal(app.sql.prepare('SELECT COUNT(*) n FROM handoff_events').get().n,1);
 const inbox=(await call('notifications','GET',undefined,sessions.materials)).data;A.equal(inbox.unread,1);A.equal(inbox.items[0].stage,'technical');A.equal((await call('notifications','GET',undefined,sessions.other)).data.items.length,0);A.equal((await call('notifications','GET',undefined,sessions.tech)).data.items.length,0);
 A.equal((await call('notifications/'+inbox.items[0].id+'/read','POST',{},sessions.other)).status,404);A.equal((await call('notifications/'+inbox.items[0].id+'/read','POST',{},sessions.materials)).status,200);A.equal((await call('notifications','GET',undefined,sessions.materials)).data.unread,0);
 d.quote.products[0].children[0].children[0].spec.price+=100;const priceSave=await call('quotes/'+id,'PUT',{document:d,expectedVersion:1},sessions.materials);A.equal(priceSave.status,200);A.equal((await call(path,'GET',undefined,sessions.tech)).data.technical.current,true);
 r=await call(path+'/materials','POST',{expectedVersion:2,note:'Private price note'},sessions.materials);A.equal(r.status,200,JSON.stringify(r.data));A.equal(r.data.recipients,2);A.equal((await call('notifications','GET',undefined,sessions.approver)).data.unread,2);A.equal((await call(path+'/materials','POST',{expectedVersion:2},sessions.materials)).data.duplicate,true);
 const technicalState=(await call(path,'GET',undefined,sessions.tech)).data;A.equal(technicalState.materials.note,undefined);A.ok(!JSON.stringify(technicalState).includes('Private price note'));
 d.quote.products[0].ops[0].amount=2;A.equal((await call('quotes/'+id,'PUT',{document:d,expectedVersion:2},admin)).status,200);const changed=(await call(path,'GET',undefined,admin)).data;A.equal(changed.technical.current,false);A.equal(changed.materials.current,false);
 A.equal((await call(path+'/materials','POST',{expectedVersion:3},sessions.materials)).status,409);A.equal((await call(path+'/technical','POST',{expectedVersion:2},sessions.tech)).status,409);
 const parallel=await Promise.all([1,2].map(()=>call(path+'/technical','POST',{expectedVersion:3},sessions.tech)));A.deepEqual(parallel.map(x=>x.data.duplicate).sort(),[false,true]);A.equal(app.sql.prepare('SELECT COUNT(*) n FROM handoff_events').get().n,3);
 app.sql.prepare('UPDATE users SET section_access=? WHERE id=?').run(JSON.stringify(['logistics']),users.materials.id);A.equal((await call('notifications','GET',undefined,sessions.materials)).data.items.length,0);
 app.sql.prepare("UPDATE quotes SET status='submitted' WHERE id=?").run(id);A.equal((await call(path+'/technical','POST',{expectedVersion:3},sessions.tech)).status,409);
 const empty=P.demoSeed();empty.quote.id='BG-EMPTY-NOTIFICATIONS';empty.quote.products=[];const emptyCreated=await call('quotes','POST',{document:empty},admin);A.equal(emptyCreated.status,201);const emptyId=emptyCreated.data.id;A.equal((await call('quotes/'+emptyId+'/handoff/technical','POST',{expectedVersion:1},sessions.tech)).status,422);
 const backup=(await call('backup','GET',undefined,admin)).data;A.equal(backup.handoffEvents.length,3);A.equal(backup.handoffs.length,1);A.equal(backup.notifications.length,8);
});
