'use strict';
const {chromium,expect}=require('@playwright/test'),{createApp}=require('../server/app.cjs'),P=require('../pricing-core.js'),fs=require('node:fs');
(async()=>{const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+app.server.address().port,browser=await chromium.launch({channel:'msedge',headless:true}),errors=[],dir='artifacts/customer-review/notifications';fs.mkdirSync(dir,{recursive:true});
 const page=async()=>{const p=await browser.newPage({viewport:{width:1600,height:1000}});p.on('pageerror',e=>errors.push(e.message));await p.goto(url);return p;},password='Notifications-local-browser-42!';
 try{const admin=await page();await admin.evaluate(async password=>{teamSession(await teamApi('setup','POST',{username:'admin',name:'Admin QA',password}));for(const [username,role,sections]of [['tech','technical',['bom','operations']],['materials','estimator',['materials']],['approver','approver',[]]])await teamApi('users','POST',{username,name:username,role,sections,password});render();},password);
 const doc=P.demoSeed();doc.quote.remnantMode='all';const id=await admin.evaluate(async document=>(await teamApi('quotes','POST',{document})).id,doc),tech=await page(),materials=await page(),approver=await page();for(const [p,username]of [[tech,'tech'],[materials,'materials'],[approver,'approver']])await p.evaluate(async({username,password})=>{teamSession(await teamApi('login','POST',{username,password}));render();},{username,password});
 await tech.evaluate(()=>noticeRefresh());await tech.locator('[data-notice=inbox]').click();await expect(tech.locator('.notification-list')).toContainText('cần kỹ thuật nhập dữ liệu');await tech.locator('[data-notice=open]').first().click();await expect.poll(()=>tech.evaluate(()=>tab)).toBe('intake');await tech.locator('[data-review-key$=":handoff"] > summary').click();await expect(tech.locator('[data-notice=confirm][data-stage=technical]')).toBeVisible();await expect(tech.locator('[data-notice=confirm][data-stage=materials]')).toHaveCount(0);
 const openHandoff=async p=>{const summary=p.locator('[data-review-key$=":handoff"]:not([open]) > summary');if(await summary.count())await summary.click();};
 const confirm=async(p,stage)=>{await openHandoff(p);await p.locator(`[data-notice-panel] [data-notice=confirm][data-stage=${stage}]`).click();await p.locator('#dialog [name=note]').fill('QA handoff');await p.locator('#dialog button[type=submit]').click();try{await expect(p.locator('#dialog')).not.toBeVisible();}catch(e){console.log(await p.locator('#dialog').innerText());throw e;}};
 await confirm(tech,'technical');await expect(tech.locator('[data-notice-panel]')).toContainText('Đã xác nhận');await materials.evaluate(()=>noticeRefresh());await expect(materials.locator('[data-notice=inbox]')).toHaveText('Thông báo (1)');await materials.locator('[data-notice=inbox]').click();await expect(materials.locator('.notification-list')).toContainText('cần cập nhật giá vật tư');await materials.locator('[data-notice=open]').click();await expect.poll(()=>materials.evaluate(()=>tab)).toBe('prices');await expect.poll(()=>materials.evaluate(()=>Notices.unread)).toBe(0);
 await materials.evaluate(()=>{db.quote.products[0].children[0].children[0].spec.price+=100;Team.dirty=true;render();});await openHandoff(materials);await materials.locator('[data-notice-panel] [data-notice=confirm][data-stage=materials]').click();await expect(materials.locator('#dialog')).not.toBeVisible();expect(app.sql.prepare('SELECT COUNT(*) n FROM handoff_events').get().n).toBe(2);await materials.locator('[data-team=save]').first().click();await expect.poll(()=>materials.evaluate(()=>Team.dirty)).toBe(false);await confirm(materials,'materials');
 await approver.evaluate(()=>noticeRefresh());await expect(approver.locator('[data-notice=inbox]')).toHaveText('Thông báo (2)');await approver.locator('[data-notice=inbox]').click();await expect(approver.locator('.notification-list article').first()).toContainText('cần phê duyệt giá');await approver.locator('[data-notice=open]').first().click();await expect.poll(()=>approver.evaluate(()=>tab)).toBe('pricing');await expect(approver.locator('[data-notice-panel]')).toContainText('Giá vật tư');await expect(approver.locator('[data-notice=confirm]')).toHaveCount(0);expect(await approver.evaluate(()=>Notices.state.materials.current)).toBe(true);expect(await approver.evaluate(()=>Team.link.status)).toBe('draft');
 await approver.reload();await expect.poll(()=>approver.evaluate(()=>Team.user?.username)).toBe('approver');await approver.evaluate(()=>noticeRefresh());expect(await approver.evaluate(()=>Notices.unread)).toBe(1);await approver.evaluate(id=>teamLoad(id),id);await approver.screenshot({path:dir+'/approver.png',fullPage:true});
 await tech.evaluate(id=>teamLoad(id),id);await tech.evaluate(async()=>{const q=teamCurrent();await teamApi('quotes/'+q.id+'/handoff/technical','POST',{expectedVersion:q.version});});expect(app.sql.prepare('SELECT COUNT(*) n FROM handoff_events').get().n).toBe(3);await tech.evaluate(async()=>{const q=teamCurrent();await teamApi('quotes/'+q.id+'/handoff/technical/reopen','POST',{expectedVersion:q.version,reason:'QA changed quantity'});await noticeRefresh();});await tech.evaluate(()=>{db.quote.products[0].qty+=1;Team.dirty=true;render();});await tech.locator('[data-team=save]').first().click();await expect.poll(()=>tech.evaluate(()=>Team.dirty)).toBe(false);await expect(tech.locator('[data-notice-panel]')).toContainText('Dữ liệu đã đổi');await materials.evaluate(id=>teamLoad(id),id);await openHandoff(materials);await materials.locator('[data-notice-panel] [data-notice=confirm][data-stage=materials]').click();await materials.locator('#dialog button[type=submit]').click();await expect(materials.locator('#dialog')).toContainText('Cần kỹ thuật xác nhận lại');await materials.evaluate(()=>closeDialog());await confirm(tech,'technical');expect(app.sql.prepare('SELECT COUNT(*) n FROM handoff_events').get().n).toBe(6);await tech.setViewportSize({width:390,height:844});await tech.screenshot({path:dir+'/technical-mobile.png',fullPage:true});expect(await tech.evaluate(()=>document.querySelector('[data-notice-panel]').getBoundingClientRect().right<=innerWidth+1)).toBe(true);expect(errors).toEqual([]);
 console.log('PASS technical -> material pricing -> approval notifications; permissions, opening relevant step, saved revisions, unread persistence, duplicates, stale data and mobile panel');
 }catch(e){const rows=app.sql.prepare('SELECT document FROM revisions ORDER BY version').all();if(rows.length>1){const project=require('../technical-core.js').project,a=project(JSON.parse(rows[0].document)).quote,b=project(JSON.parse(rows[1].document)).quote;function diff(a,b,path=''){if(JSON.stringify(a)===JSON.stringify(b))return;if(a&&b&&typeof a==='object'&&typeof b==='object')for(const k of new Set([...Object.keys(a),...Object.keys(b)]))diff(a[k],b[k],path+'.'+k);else console.log(path,JSON.stringify(a),'->',JSON.stringify(b));}diff(a,b);}throw e;}finally{await browser.close();await new Promise(r=>app.server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
