const {chromium,expect}=require('@playwright/test');
const fs=require('node:fs');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
(async()=>{
  const fallback=path.join(process.env.LOCALAPPDATA||'','ms-playwright','chromium-1228','chrome-win64','chrome.exe');
  const browser=await chromium.launch({headless:true,...(fs.existsSync(fallback)?{executablePath:fallback}:{})});
  const context=await browser.newContext({viewport:{width:1440,height:1000},offline:true});
  const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
  await p.goto(pathToFileURL(path.resolve('dist/index.html')).href);
  await expect(p.locator('h1')).toHaveText('Báo giá cơ khí');
  await expect(p.locator('.notice.error')).toHaveCount(0);
  await p.screenshot({path:'artifacts/demo-hoan-thien.png',fullPage:true});
  await expect(p.locator('.quick-product')).toHaveCount(2);
  await p.locator('[data-action="quick-3d"]').first().click();
  await expect(p.locator('#dialog .model-scene')).toHaveCount(1);
  const rotation=await p.locator('#dialog .model-scene').getAttribute('style');
  await p.locator('#dialog .model-stage').press('ArrowRight');
  expect(await p.locator('#dialog .model-scene').getAttribute('style')).not.toBe(rotation);
  await p.locator('#dialog [data-action="close"]').first().click();
  const width=p.locator('[data-param-key="W"]').first();
  await width.fill('400');await width.press('Tab');
  await expect(p.locator('.quick-product').first()).toContainText('Máng cáp 400');
  await p.locator('[data-action="ux-undo"]').click();
  await p.locator('#quick-search').fill('Thân máng cáp');
  await expect(p.locator('.quick-row input[data-qkey=L]')).toHaveCount(1);
  await p.getByRole('button',{name:'Xóa tìm kiếm',exact:true}).click();
  await p.locator('.quick-product').first().getByRole('button',{name:'Dán từ Excel',exact:true}).click();
  await p.locator('#excel-paste').fill('PH-T15\t1\t1.800\t400');
  await p.locator('#dialog button[type=submit]').click();
  await expect(p.locator('#dialog-error')).toContainText('hai cách hiểu');
  await p.locator('[name=numberFormat]').selectOption('vi');
  await expect(p.locator('.paste-preview-table tbody tr')).toContainText('1.800');
  await p.locator('#dialog button[type=submit]').click();
  await expect(p.locator('.quick-product').first().locator('tbody tr').last().locator('[data-qkey=L]')).toHaveValue('1800');
  await p.locator('[data-action="ux-undo"]').click();
  await p.locator('[data-tab="waste"]').click();await expect(p.locator('.nesting-panel')).toHaveCount(2);await p.screenshot({path:'artifacts/hao-hut-hoan-thien.png',fullPage:true});
  await p.locator('[data-tab="preview"]').click();
  await p.evaluate(()=>document.querySelector('#print-area').innerHTML=paper());
  await p.pdf({path:'artifacts/bao-gia-hoan-thien.pdf',format:'A4',printBackground:true});
  await p.setViewportSize({width:390,height:844});await p.locator('[data-tab="bom"]').click();await p.screenshot({path:'artifacts/mobile-hoan-thien.png',fullPage:true});
  await p.locator('[data-action="menu"]').click();await expect(p.locator('.sidebar')).toHaveClass(/open/);await p.locator('[data-page="materials"]').click();await expect(p.locator('.sidebar')).not.toHaveClass(/open/);await expect(p.locator('h1')).toHaveText('Danh mục vật tư');
  expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  expect(errors).toEqual([]);
  console.log('Single-file HTML works offline, 3D/BOM/contextual search/locale-aware paste/nesting/print/mobile navigation verified.');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
