'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{randomUUID}=require('node:crypto'),{createApp}=require('../server/app.cjs'),P=require('../pricing-core.js');
async function fixture(t){const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));let admin;const call=async(path,method='GET',body,s=admin)=>{const r=await fetch('http://127.0.0.1:'+app.server.address().port+'/api/'+path,{method,headers:{'Content-Type':'application/json',Cookie:s?.cookie||'','X-CSRF-Token':s?.csrf||''},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};};admin=await call('setup','POST',{username:'admin',name:'Admin',password:'Operations-test-2026!'},null);const d=P.demoSeed();const q=(await call('quotes','POST',{document:d})).data;await call('quotes/'+q.id+'/submit','POST',{expectedVersion:1});await call('quotes/'+q.id+'/approve','POST',{expectedVersion:2});const o=(await call('quotes/'+q.id+'/order','POST',{expectedVersion:3,code:'ORDER-OPS'})).data;await call('orders/'+o.id+'/confirm','POST',{quoteVersion:3});const j=await call('production','POST',{orderId:o.id,productId:d.quote.products[0].id,quantity:1,code:'JOB-OPS'});A.equal(j.status,201,JSON.stringify(j.data));j.data=await require('./production-review-fixture.cjs').review(call,admin,j.data.id);const post=(p,b,s)=>call('ops/'+p,'POST',{requestId:randomUUID(),...b},s);return {app,call,post,admin,job:j.data};}
test('concurrent holds, source-linked offcuts, mass conservation and delegated cost isolation',async t=>{
 const {app,call,post,job}=await fixture(t),d=(await call('ops/job/'+job.id)).data.requirements.find(d=>d.unit==='tấm');
 await post('master',{kind:'material',expectedVersion:0,document:{id:d.materialId,code:d.materialId,name:d.name,unit:d.unit,form:'sheet'}});
 const lot=(await post('receipt',{materialId:d.materialId,warehouse:'A',quantity:1,unitWeight:10,unitCost:100,length:d.length,width:d.width,thickness:d.thickness,reference:'SHEET'})).data;
 const results=await Promise.all([post('reserve',{jobId:job.id,lotId:lot.id,quantity:1}),post('reserve',{jobId:job.id,lotId:lot.id,quantity:1})]);A.deepEqual(results.map(r=>r.status).sort(),[200,409]);
 const h=results.find(r=>r.status===200).data;app.sql.prepare("UPDATE ops_records SET document=? WHERE kind='hold' AND id=?").run(JSON.stringify({...h,state:'issued'}),h.id);app.sql.prepare("UPDATE ops_records SET document=? WHERE kind='lot' AND id=?").run(JSON.stringify({...lot,quantity:0}),lot.id);
 const remnants=[{quantity:1,unitWeight:5,length:d.length/2,width:d.width,thickness:d.thickness}];A.equal((await post('return',{holdId:h.id,productWeight:4,scrapWeight:1,remnants:[{...remnants[0],unitWeight:4}]})).status,400);
 A.equal((await post('return',{holdId:h.id,productWeight:4,scrapWeight:1,remnants})).status,200);const state=(await call('ops/state')).data,rem=state.lots.find(l=>l.sourceLotId===lot.id);A.equal(rem.rootLotId,lot.id);A.equal(rem.quantity,1);A.equal(rem.unitCost,50);
 const u=(await call('users','POST',{username:'store',name:'Store',role:'sales',password:'Operations-test-2026!'})).data;app.sql.prepare('UPDATE users SET action_access=? WHERE id=?').run(JSON.stringify({inventory:['view','export']}),u.id);const s=await call('login','POST',{username:'store',password:'Operations-test-2026!'});
 const view=await call('ops/state','GET',undefined,s);A.equal(view.status,200);A.equal(view.data.lots[0].unitCost,undefined);A.equal(view.data.movements[0].value,undefined);A.equal((await post('issue',{lotId:rem.id,quantity:1,reference:'NO',note:'No rights'},s)).status,403);
});
test('real stock blocks start, reservations prevent double allocation, issue is automatic and returns balance',async t=>{const {call,post,admin,job}=await fixture(t);let j=job;const update=async b=>{const r=await call('production/'+j.id,'PUT',{expectedVersion:j.version,...b});if(r.status===200)j=r.data;return r;};await update({action:'prepare',deadline:'2026-10-01',workshop:'A',materialsReady:true,drawingReady:true,note:''});const op=j.packet.operations[0],start={action:'operation',operationId:op.id,assignee:admin.data.user.id,machine:'Manual',status:'running',output:0,note:''};A.equal((await update(start)).status,409);await require('./ops-fixture.cjs').seedStock(call,admin,j.id);j=await require('./production-flow-fixture.cjs').approveRoute(call,admin,j.id);j=await require('./production-review-fixture.cjs').review(call,admin,j.id);const state=(await call('ops/state')).data,l=state.lots[0];A.equal((await post('issue',{lotId:l.id,quantity:1,reference:'BAD',note:'Reserved'})).status,409);A.equal((await update(start)).status,200);const state2=(await call('ops/state')).data;A.ok(state2.movements.some(m=>m.kind==='issue'));const h=state2.holds[0],lot=state2.lots.find(l=>l.id===h.lotId),weight=h.quantity*lot.unitWeight;A.equal((await post('return',{holdId:h.id,productWeight:weight+1,scrapWeight:0,remnants:[]})).status,409);const body={requestId:randomUUID(),holdId:h.id,productWeight:weight-1,scrapWeight:1,remnants:[]};const a=await post('return',body),b=await post('return',body);A.equal(a.status,409);A.equal(b.status,409);j=await require('./production-flow-fixture.cjs').settleStage(call,admin,j.id);A.equal((await post('return',{...body,requestId:randomUUID()})).status,409);A.equal((await post('delete',{kind:'material',id:lot.materialId,expectedVersion:1})).status,409);});
test('shortage purchasing records approval, receipt, actual inventory and a single linked cost',async t=>{const {call,post,job}=await fixture(t);const ds=(await call('ops/job/'+job.id)).data.requirements;for(const d of ds)A.equal((await post('master',{kind:'material',expectedVersion:0,document:{id:d.materialId,code:d.materialId,name:d.name||d.materialId,unit:d.unit,form:d.unit==='tấm'?'sheet':'bulk'}})).status,200);const s=(await post('master',{kind:'supplier',expectedVersion:0,document:{code:'SUP',name:'Supplier',prices:ds.map(d=>({materialId:d.materialId,unitCost:20,leadDays:2}))}})).data;let p=(await post('purchase',{jobId:job.id,code:'PO-1',supplierId:s.id})).data;A.equal(p.state,'pending');A.equal((await post('purchase',{jobId:job.id,code:'PO-2',supplierId:s.id})).status,409);A.equal((await post('transition',{id:p.id,expectedVersion:p.version,state:'stocked'})).status,409);for(const state of ['approved','ordered','shipping','received','stocked']){const b={id:p.id,expectedVersion:p.version,state,note:'Verified',receipts:ds.map(d=>({materialId:d.materialId,quantity:d.quantity,warehouse:'Main',unitWeight:10,length:d.length,width:d.width,thickness:d.thickness||1}))};const r=await post('transition',b);A.equal(r.status,200,JSON.stringify(r.data));p=r.data;}const db=(await call('backup')).data;A.equal(db.businessRecords.filter(r=>r.kind==='cost').length,1);A.equal((await call('ops/state')).data.lots.length,ds.length);A.equal((await post('transition',{id:p.id,expectedVersion:p.version,state:'stocked'})).status,409);A.equal((await call('ops/job/'+job.id)).data.requirements.every(d=>d.missing===0),true);});
test('workshop daily work records operator, capacity hours and issue resolution; non-authorized APIs denied',async t=>{const {call,post,admin,job}=await fixture(t);await call('users','POST',{username:'sales',name:'Sales',role:'sales',password:'Operations-test-2026!'});const sales=await call('login','POST',{username:'sales',password:'Operations-test-2026!'});A.equal((await call('ops/state','GET',undefined,sales)).status,403);A.equal((await post('master',{kind:'machine',expectedVersion:0,document:{name:'Cutter',code:'M1',workshop:'A',hoursPerDay:8}},sales)).status,403);const m=(await post('master',{kind:'machine',expectedVersion:0,document:{name:'Cutter',code:'M1',workshop:'A',hoursPerDay:8}})).data;const tk=(await post('task',{expectedVersion:0,document:{name:'Cut lot 1',jobId:job.id,assignee:admin.data.user.id,machineId:m.id,startDate:'2026-09-25',dueDate:'2026-09-26',plannedHours:8}})).data;const r=await post('report',{taskId:tk.id,date:'2026-09-25',hours:9,output:1,state:'running',content:'Cutting',issue:'Machine jam'});A.equal(r.status,200,JSON.stringify(r.data));A.equal((await post('report',{taskId:tk.id,date:'2026-09-25',hours:20,output:1,state:'running',content:'Too much'})).status,400);A.equal((await post('resolve',{id:r.data.id,resolution:'Repaired'})).status,200);A.equal((await post('delete',{kind:'machine',id:m.id,expectedVersion:1})).status,409);});

test('catalog operation and split batches persist and lock after completion',async t=>{
 const {call,post,admin,job}=await fixture(t);let j=job;
 const catalog=(await post('master',{kind:'operation',expectedVersion:0,document:{code:'PREP',name:'Preparation',workshop:'A',hourRate:100,factors:[{name:'Normal',value:1}]}})).data;
 const update=async body=>{const r=await call('production/'+j.id,'PUT',{expectedVersion:j.version,...body});if(r.status===200)j=r.data;return r;};
 A.equal((await update({action:'add-operation',catalogId:catalog.id})).status,409);
 const route=[{name:catalog.name,catalogId:catalog.id,lossPercent:0,machine:'M',unit:'hour',workQuantity:1,outputUnit:'piece'},...j.packet.operations.map(o=>({...o,lossPercent:0,machine:'M',unit:o.unit||'hour',workQuantity:o.workQuantity||1}))];
 j=await require('./production-flow-fixture.cjs').approveRoute(call,admin,j.id,route);j=await require('./production-review-fixture.cjs').review(call,admin,j.id);const op=j.packet.operations[0];
 await require('./ops-fixture.cjs').seedStock(call,admin,j.id);
 A.equal((await update({action:'prepare',deadline:'2026-10-01',workshop:'A',materialsReady:true,drawingReady:true,note:''})).status,200);
 A.equal((await update({action:'operation',operationId:op.id,status:'running',assignee:admin.data.user.id,output:0,hours:1,machine:'M',note:''})).status,200);
 A.equal((await update({action:'add-operation',catalogId:catalog.id})).status,409);
 A.equal((await update({action:'operation',operationId:op.id,status:'running',assignee:admin.data.user.id,output:op.quantity,hours:2,machine:'M',lotCode:'BATCH-1',note:''})).status,200);
 A.equal(j.progress.batches.at(-1).quantity,op.quantity);j=await require('./production-flow-fixture.cjs').settleStage(call,admin,j.id);
 A.equal((await update({action:'operation',operationId:op.id,status:'running',assignee:admin.data.user.id,machine:'M',output:0,note:''})).status,409);
 const costs=(await call('ops/job/'+j.id)).data;A.ok(Array.isArray(costs.baseline));
});
