'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),P=require('../pricing-core.js');
test('organization migration, multi-position permissions, scoped managers, changes and account lifecycle',async t=>{
 const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port,password='Organization-test-2026!';
 async function call(route,method='GET',body,s){const r=await fetch(base+'/api/'+route,{method,headers:{'Content-Type':'application/json',...(s?{Cookie:s.cookie,'X-CSRF-Token':s.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};}
 const admin=await call('setup','POST',{username:'admin',name:'Admin',password});const users={};for(const name of ['head','worker','outside'])users[name]=(await call('users','POST',{username:name,name,role:'technical',sections:['bom','operations'],password},admin)).data;
 const login=name=>call('login','POST',{username:name,password});let head=await login('head');A.equal((await call('organization','GET',undefined,head)).status,403);
 const role=async(name,role,sections,canViewCosts=false)=>(await call('roles','POST',{name,role,sections,canViewCosts,canFormulaUse:true,canFormulaView:true},admin)).data;
 const tech=await role('Technical','technical',['bom','operations']),price=await role('Pricing','estimator',['materials'],true);
 let state=(await call('organization','GET',undefined,admin)).data;A.equal(state.employees.length,4);A.ok(state.employees.every(e=>!e.managed));A.equal((await call('me','GET',undefined,head)).status,200,'migration does not revoke sessions');
 const doc={departments:[{id:'a',name:'Technical A',stage:'technical',active:true},{id:'b',name:'Technical B',stage:'technical',active:true},{id:'p',name:'Price',stage:'materials',active:true}],positions:[{id:'ha',name:'Head',departmentId:'a',manager:true,roleIds:[tech.id],active:true},{id:'wa',name:'Worker',departmentId:'a',manager:false,roleIds:[tech.id],active:true},{id:'wb',name:'Worker',departmentId:'b',manager:false,roleIds:[tech.id],active:true},{id:'pr',name:'Pricing',departmentId:'p',manager:false,roleIds:[price.id],active:true}],employees:state.employees.map(e=>({...e,positionIds:e.userId===users.head.id?['ha']:e.userId===users.worker.id?['wa']:e.userId===users.outside.id?['wb']:[]}))};
 async function save(d=doc,extra={}){const r=await call('organization','PUT',{expectedVersion:state.version,document:d,...extra},admin);if(r.status===200)state=(await call('organization','GET',undefined,admin)).data;return r;}
 A.equal((await save()).status,200);A.equal((await call('me','GET',undefined,head)).status,401);head=await login('head');
 A.equal((await call('organization','PUT',{expectedVersion:0,document:doc},admin)).status,409);
 const q=(await call('quotes','POST',{document:P.demoSeed()},admin)).data,work='quotes/'+q.id+'/work';
 let options=(await call(work,'GET',undefined,head)).data;A.deepEqual(options.candidates.technical.map(u=>u.id).sort(),[users.head.id,users.worker.id].sort());
 A.equal((await call(work,'PUT',{expectedRevision:0,technicalId:users.outside.id,materialsId:null,status:'not-started'},head)).status,403);
 A.equal((await call('users/'+users.worker.id+'/access','POST',{role:'admin'},admin)).status,409,'legacy editing cannot override positions');
 const worker=doc.employees.find(e=>e.userId===users.worker.id);worker.positionIds=['wa','pr'];A.equal((await save()).status,200);let ws=await login('worker');A.equal(ws.data.permissions.costs,true);A.ok(ws.data.permissions.sections.includes('bom')&&ws.data.permissions.sections.includes('materials'));
 worker.positionIds=['wb'];A.equal((await save()).status,200);A.equal((await call('me','GET',undefined,ws)).status,401);options=(await call(work,'GET',undefined,head)).data;A.deepEqual(options.candidates.technical.map(u=>u.id),[users.head.id]);
 A.equal((await call('roles/'+tech.id,'DELETE',{expectedVersion:tech.version},admin)).status,409);
 const changed=await call('roles/'+tech.id,'PUT',{...tech,sections:['bom'],expectedVersion:tech.version},admin);A.equal(changed.status,200);ws=await login('worker');A.ok(!ws.data.permissions.sections.includes('operations'));A.ok(ws.data.permissions.sections.includes('bom'));state=(await call('organization','GET',undefined,admin)).data;
 const broken=structuredClone(doc);broken.departments=broken.departments.filter(x=>x.id!=='b');A.equal((await save(broken)).status,400);
 const self=structuredClone(doc);self.employees.find(e=>e.userId===admin.data.user.id).positionIds=['wa'];A.equal((await save(self)).status,409);A.equal((await call('me','GET',undefined,admin)).status,200);
 doc.employees.push({id:'new-person',code:'NV-NEW',name:'New person',active:true,positionIds:['wa'],phone:'0123456789',email:'new@example.com'});A.equal((await save(doc,{createAccount:{employeeId:'new-person',username:'new-person',password}})).status,200);const ns=await login('new-person');A.equal(ns.status,200);A.equal(ns.data.permissions.technical,true);
 // Continue from the canonical server document, including the newly linked account.
 Object.assign(doc,{departments:state.departments,positions:state.positions,employees:state.employees});doc.employees.find(e=>e.id==='new-person').active=false;A.equal((await save()).status,200);A.equal((await login('new-person')).status,401);
 const newId=state.employees.find(e=>e.id==='new-person').userId;A.equal((await call('users/'+newId+'/enable','POST',{},admin)).status,409);
 doc.employees.find(e=>e.id==='new-person').active=true;A.equal((await save()).status,200);A.equal((await login('new-person')).status,200);
 await call('users/'+newId+'/disable','POST',{},admin);doc.departments[0].name='Technical A renamed';A.equal((await save()).status,200);A.equal((await login('new-person')).status,401,'unrelated changes never unlock manually disabled account');
 const teams=(await call('work-teams','GET',undefined,admin)).data;for(const entry of Object.values(teams.teams))for(const k of ['managers','members'])entry[k]=entry[k].filter(id=>id!==newId);teams.teams.technical.managers.push(users.outside.id);A.equal((await call('work-teams','PUT',{expectedVersion:teams.version,teams:teams.teams},admin)).status,409);
 doc.departments.find(d=>d.id==='b').active=false;doc.employees.find(e=>e.userId===users.worker.id).managed=false;A.equal((await save()).status,200);ws=await login('worker');A.equal(ws.data.permissions.costs,false);A.deepEqual(ws.data.permissions.sections,[]);A.equal((await call('users/'+users.worker.id+'/access','POST',{role:'admin'},admin)).status,409);
 const backup=(await call('backup','GET',undefined,admin)).data;A.equal(backup.organization.length,1);A.ok(backup.organizationRevisions.length>3);A.ok(backup.audit.some(a=>a.action==='organization:access'));
});
