const {chromium,expect}=require('@playwright/test'),{createApp}=require('../server/app.cjs');
(async()=>{const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const b=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:'+app.server.address().port);await p.waitForFunction(()=>Team.available);
 await p.evaluate(async()=>{teamSession(await teamApi('setup','POST',{username:'admin',name:'Admin',password:'Organization-browser-2026!'}));await teamApi('roles','POST',{name:'Quyền kỹ thuật',role:'technical',sections:['bom','operations'],canViewCosts:false});render();await noticeRefresh();});
 await p.locator('#permissions-nav').click();await expect(p.locator('#dialog')).toContainText('Vai trò & phân quyền');await p.locator('[data-ar=new-role]').click();await expect(p.locator('#dialog-title')).toHaveText('Thêm bộ quyền');await p.locator('#dialog [data-action=close]').first().click();await p.locator('#organization-nav').click();await expect(p.locator('#dialog-title')).toHaveText('Cơ cấu tổ chức');await p.locator('[data-org=edit][data-id=""]').click();await p.locator('[name=name]').fill('Phòng kỹ thuật A');await p.locator('[name=workflow]').selectOption('technical');await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#dialog')).toContainText('Phòng kỹ thuật A');
 await expect(p.locator('#organization-nav')).toBeVisible();
 await p.locator('[data-org=workflows]').click();await p.locator('[data-org=edit][data-id=""]').click();await p.locator('[name=name]').fill('Design workflow');await p.locator('[name=stage]').selectOption('technical');await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#dialog')).toContainText('Design workflow');
 await p.locator('#dialog [data-org=departments]').click();await p.locator('[data-org=edit][data-id=""]').click();await p.locator('[name=name]').fill('Design department');await p.locator('[name=workflow]').selectOption({label:'Design workflow'});await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#dialog')).toContainText('Design department');
 await p.locator('.organization-table tr').filter({hasText:'Design department'}).locator('[data-org=up]').click();await expect(p.locator('.organization-table tbody tr').first()).toContainText('Design department');await p.locator('.organization-table tr').filter({hasText:'Design department'}).locator('[data-org=down]').click();await expect(p.locator('.organization-table tbody tr').first()).not.toContainText('Design department');
 await p.locator('[data-org=edit][data-id=""]').click();await p.locator('[name=name]').fill('Team A1');await p.locator('[name=kind]').selectOption('team');const parent=await p.locator('[name=parentId] option').nth(1).getAttribute('value');await p.locator('[name=parentId]').selectOption(parent);await p.locator('[name=workflow]').selectOption('technical');await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#dialog')).toContainText('Team A1');
 await p.locator('[data-org=positions]').click();await p.locator('[data-org=edit][data-id=""]').click();await p.locator('[name=name]').fill('Kỹ sư');await p.locator('[name=departmentId]').selectOption({index:1});await p.locator('[name=roleIds]').check();await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#dialog')).toContainText('Kỹ sư');
 // Personnel now has a reviewed declaration flow, covered by personnel-browser.
 // Keep this suite focused on organization-derived account permissions.
 await p.evaluate(async()=>{const org=await teamApi('organization');const document={...org,employees:[...org.employees,{id:'browser-staff',code:'NV-TEST',name:'Organization staff',active:true,positionIds:[org.positions[0].id]}]};await teamApi('organization','PUT',{expectedVersion:org.version,document,createAccount:{employeeId:'browser-staff',username:'new-staff',password:'New-staff-test-2026!'}});closeDialog();});
 await p.locator('#personnel-nav').click();await expect(p.locator('[data-hr-rows]')).toContainText('NV-TEST');
 await p.setViewportSize({width:390,height:844});expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
 await p.evaluate(()=>accessReviewOpen());await expect(p.locator('#review-user-rights')).not.toBeEmpty();const matrix=p.waitForEvent('download');await p.locator('[data-review=matrix-export]').click();expect((await matrix).suggestedFilename()).toBe('MA-TRAN-PHAN-QUYEN.xlsx');await p.locator('[data-review=access-history]').click();await expect(p.locator('#dialog details')).not.toHaveCount(0);await p.evaluate(()=>auditOpen());await expect(p.locator('#audit-results tbody tr')).not.toHaveCount(0);await p.locator('[name=auditQuery]').fill('nothing-matches-123');await p.locator('[data-review=audit-search]').click();await expect(p.locator('#audit-results')).toContainText('0 b');
 const login=await p.evaluate(()=>teamApi('login','POST',{username:'new-staff',password:'New-staff-test-2026!'}));expect(login.permissions.technical).toBe(true);expect(login.permissions.costs).toBe(false);expect(errors).toEqual([]);console.log('PASS organization UI: department, position permissions, employee, account creation and mobile layout');
 }finally{await b.close();await new Promise(r=>app.server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
