const {chromium,expect}=require('@playwright/test'),{createApp}=require('../server/app.cjs');
(async()=>{const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const b=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:'+app.server.address().port);await p.waitForFunction(()=>Team.available);
 await p.evaluate(async()=>{teamSession(await teamApi('setup','POST',{username:'admin',name:'Admin',password:'Organization-browser-2026!'}));await teamApi('roles','POST',{name:'Quyền kỹ thuật',role:'technical',sections:['bom','operations'],canViewCosts:false});render();await noticeRefresh();});
 await p.locator('[data-work-tools=teams]').click();await expect(p.locator('#dialog')).toContainText('Nhân sự & phòng ban');await p.locator('[data-org=departments]').click();await p.locator('[data-org=edit][data-id=""]').click();await p.locator('[name=name]').fill('Phòng kỹ thuật A');await p.locator('[name=stage]').selectOption('technical');await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#dialog')).toContainText('Phòng kỹ thuật A');
 await p.locator('[data-org=positions]').click();await p.locator('[data-org=edit][data-id=""]').click();await p.locator('[name=name]').fill('Kỹ sư');await p.locator('[name=roleIds]').check();await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#dialog')).toContainText('Kỹ sư');
 await p.locator('[data-org=employees]').click();await p.locator('[data-org=edit][data-id=""]').click();await p.locator('[name=code]').fill('NV-TEST');await p.locator('[name=name]').fill('Nhân sự mới');await p.locator('[name=email]').fill('test@example.com');await p.locator('[name=positionIds]').check();await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#dialog')).toContainText('NV-TEST');
 await p.locator('[data-org=account]').click();await p.locator('[name=username]').fill('new-staff');await p.locator('[name=password]').fill('New-staff-test-2026!');await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#dialog')).toContainText('new-staff');
 await p.setViewportSize({width:390,height:844});expect(await p.locator('#dialog').evaluate(d=>d.scrollWidth<=d.clientWidth+1)).toBe(true);await p.screenshot({path:'artifacts/organization-mobile.png'});
 const login=await p.evaluate(()=>teamApi('login','POST',{username:'new-staff',password:'New-staff-test-2026!'}));expect(login.permissions.technical).toBe(true);expect(login.permissions.costs).toBe(false);expect(errors).toEqual([]);console.log('PASS organization UI: department, position permissions, employee, account creation and mobile layout');
 }finally{await b.close();await new Promise(r=>app.server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
