'use strict';
const {chromium,expect}=require('@playwright/test'),fs=require('fs'),path=require('path'),{pathToFileURL}=require('url'),crypto=require('crypto');
(async()=>{
 const live=process.argv.includes('--live'),build=path.resolve(process.env.UNFOLD_BUILD||'artifacts/polygon-release/dist/index.html'),dir=path.resolve('artifacts/customer-review/polygon/'+(live?'live':'local'));fs.mkdirSync(dir,{recursive:true});
 const credentials=live?JSON.parse(fs.readFileSync('artifacts/railway-team/private/credentials.json','utf8').replace(/^\uFEFF/,'')):null,url=credentials?.url||pathToFileURL(build).href;
 const hash=s=>crypto.createHash('sha256').update(s.replace(/\r\n/g,'\n').trim()).digest('hex');if(live)expect(hash(await fetch(url).then(r=>r.text()))).toBe(hash(fs.readFileSync(build,'utf8')));
 const browser=await chromium.launch({channel:'msedge',headless:true}),p=await browser.newPage({viewport:{width:1560,height:1050}}),errors=[],writes=[],checks=[];
 p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(12000);
 if(live)await p.route('**/api/**',r=>{const q=r.request();if(['GET','HEAD'].includes(q.method())||new URL(q.url()).pathname==='/api/login')return r.continue();writes.push(q.method()+' '+q.url());return r.abort();});
 const submit=async()=>{await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#dialog')).not.toBeVisible();},close=()=>p.locator('#dialog .dialog-head [data-action=close]').click(),value=async(key,n)=>expect(Number(await p.locator(`[data-df-result="${key}"]`).getAttribute('data-value'))).toBeCloseTo(n,7),shot=name=>p.screenshot({path:path.join(dir,name+'.png')});
 try{
  await p.goto(url);let before;
  if(live){await p.waitForFunction(()=>typeof Team!=='undefined'&&Team.available);await p.evaluate(async c=>{teamSession(await teamApi('login','POST',c));},credentials);before=await p.evaluate(async()=>({catalog:await teamApi('catalog'),quotes:await teamApi('quotes')}));await p.evaluate(()=>{db=TPPrice.demoSeed();Team.loaded=true;Team.link={workspaceKey:db.quote.workspaceKey,status:'draft',version:0};CatalogDraft.record=null;CatalogDraft.dirty=false;page='rules';render();});}
  const input=name=>p.locator('[name='+name+']');
  await p.evaluate(()=>{page='rules';RulesCatalog.kind='shapes';render();});await p.locator('[data-definition=shape-new]').click();
  if(!await p.locator('[data-df-polygon]').evaluate(el=>el.open))await p.locator('[data-df-polygon] summary').click();await input('polygonKind').selectOption('triangle');await p.locator('[data-df-polygon-apply]').click();await expect(input('key1')).toHaveValue('C1');
  await input('id').fill('QA-TRI-3');await input('name').fill('Tam giác 3 cạnh kiểm thử');await value('blankSurface',.06);await expect(p.locator('#definition-calculations [data-df-calculation=length],#definition-calculations [data-df-calculation=width]')).toHaveCount(0);for(const [k,n]of [['C01',300],['C02',400],['C03',500]]){const out=p.locator('[data-df-declared-result='+k+']');await expect(out).toBeVisible();expect(Number(await out.getAttribute('data-value'))).toBe(n);}await expect(p.locator('[data-df-envelope]')).toBeVisible();await expect(input('length')).not.toBeVisible();await expect(p.locator('[data-df-polygon-preview] polygon')).toHaveCount(1);
  await input('sample1').fill('100');await expect(p.locator('#definition-preview')).toContainText('không tạo thành tam giác');await expect(p.locator('[data-df-declared-result=C01]')).toHaveText('—');await input('sample1').fill('300');await p.locator('[data-df-edit-output=outputFormula0]').click();await expect(input('outputFormula0')).toBeFocused();await input('outputFormula0').fill('C1 + 10');expect(Number(await p.locator('[data-df-declared-result=C01]').getAttribute('data-value'))).toBe(310);await input('outputFormula0').fill('C1');await p.locator('[data-df-allowance]').scrollIntoViewIfNeeded();await shot('01-tam-giac-ba-canh');await submit();
  const row=p.locator('[data-rc-definition=QA-TRI-3]');for(const k of ['C01','C02','C03'])await expect(row.locator('[data-rc-formula-status=output-'+k+']')).toHaveCount(1);await expect(row.locator('[data-rc-formula-status=length],[data-rc-formula-status=width]')).toHaveCount(0);
  await row.locator('[data-definition=shape-material]').click();await input('id').fill('QA-TRI-M');await input('price').fill('100');await input('unit').selectOption('kg');await submit();
  await p.evaluate(()=>{const m=db.materials.find(m=>m.id==='QA-TRI-M');m.stockL=1000;m.stockW=1000;const n=TPDefinitions.assign(TPDefinitions.draft('Phôi tam giác',4),m,db.rules);db.quote.products=[{id:'QA-P',name:'SP kiểm thử',kind:'product',qty:1,ops:[],children:[n]}];db.quote.kerf=0;db.quote.remnantSelections={};db.quote.remnantMode='all';db.quote.nestingPlans=[];page='quote';tab='waste';MaterialEstimateUI.proposal=true;render();});
  await expect(p.locator('[data-remnant-group] [data-triangle-piece]')).toHaveCount(4);await expect(p.locator('.remnant-cut-details')).toContainText('C01 = 300');
  const initial=await p.evaluate(()=>TPMaterialEstimate.comparisons(result,result.rows.map(r=>r.id))[0].percent);
  const count=await p.locator('[data-remnant-batch]').count();for(let i=0;i<count;i++)await p.locator('[data-remnant-batch]').nth(i).check();
  const loss=await p.evaluate(()=>{const x=TPMaterialEstimate.comparisons(result,result.rows.map(r=>r.id))[0];return {percent:x.percent,remaining:x.remainingWeight,blank:x.blankWeight,purchased:x.purchasedWeight,reuse:x.reusableWeight};});expect(loss.percent).toBeCloseTo(100,7);expect(loss.percent).toBeLessThan(initial);expect(loss.remaining).toBeCloseTo(loss.purchased-loss.blank-loss.reuse,7);await p.locator('[data-remnant-loss]').scrollIntoViewIfNeeded();await shot('02-hao-hut-sau-tan-dung');
  await p.locator('[data-me=group-estimate]').click();await expect(p.locator('[data-me-suggested]')).toHaveText('100%');await p.locator('[data-me-use-suggestion]').click();await submit();expect(await p.evaluate(()=>result.rows[0].estimate.percent)).toBeCloseTo(100,7);expect(await p.evaluate(()=>result.rows[0].estimate.weight)).toBeCloseTo(loss.blank*2,7);
  if(!live)await p.reload();await p.locator('[data-page=rules]').click();await p.locator('[data-rc-tab=shapes]').click();await row.locator('[data-rc=summary]').click();await expect(p.locator('#dialog')).toBeVisible();await value('blankSurface',.06);await expect(input('outputKey0')).toHaveValue('C01');await expect(p.locator('[data-df-declared=C01]')).toContainText('C1');await expect(p.locator('#definition-calculations [data-df-calculation=length]')).toHaveCount(0);await close();
  await p.locator('[data-definition=shape-new]').click();if(!await p.locator('[data-df-polygon]').evaluate(el=>el.open))await p.locator('[data-df-polygon] summary').click();await input('polygonKind').selectOption('regular');await input('polygonCount').fill('6');await p.locator('[data-df-polygon-apply]').click();await expect(input('key6')).toHaveValue('C6');await input('name').fill('Lục giác kiểm thử');await value('blankSurface',3*Math.sqrt(3)*.09/2);await expect(p.locator('[data-df-declared]')).toHaveCount(6);await expect(p.locator('[data-df-declared-result=C06]')).toHaveText('300');
  await input('polygonKind').selectOption('edges');await input('polygonCount').fill('4');await p.locator('[data-df-polygon-apply]').click();await expect(input('key2')).toHaveValue('G1');await value('blankSurface',.09);await input('sample2').fill('10');await expect(p.locator('#definition-preview')).toContainText('chưa khép kín');await input('sample2').fill('0');await value('blankSurface',.09);
  await p.setViewportSize({width:390,height:844});await p.locator('[data-df-polygon]').scrollIntoViewIfNeeded();expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await shot('03-da-giac-mobile');await close();checks.push('triangle 3 sides; invalid triangle blocked; actual contour; side labels only; save/reload; regular polygon; edge angles and closure; reusable mass deduction and explicit estimate application; mobile');
  if(live)expect(await p.evaluate(async()=>({catalog:await teamApi('catalog'),quotes:await teamApi('quotes')}))).toEqual(before);
  expect(errors).toEqual([]);expect(writes).toEqual([]);fs.writeFileSync(dir+'/results.json',JSON.stringify({passed:true,live,checks,errors,writes,at:new Date().toISOString()},null,2));console.log('PASS polygon declarations and reuse-adjusted allowance'+(live?' on production; no business writes':''));
 }catch(e){await shot('FAILURE').catch(()=>{});throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
