const {chromium,expect}=require('@playwright/test');
const {pathToFileURL}=require('node:url');
const path=require('node:path'),fs=require('node:fs');
(async()=>{
  const browser=await chromium.launch({channel:'msedge',headless:true});
  const folder=path.resolve('artifacts/pricing-2026-09-12');fs.mkdirSync(folder,{recursive:true});
  const page=await browser.newPage({viewport:{width:1440,height:1000},offline:true});
  const errors=[],passed=[];page.on('pageerror',e=>errors.push(e.message));
  const check=name=>{passed.push(name);console.log('PASS '+name);};
  const tab=async name=>page.locator(`[data-tab="${name}"]`).click();
  const submit=()=>page.locator('#dialog button[type=submit]').click();
  const close=()=>page.locator('#dialog .dialog-head [data-action=close]').click();
  const sample=async()=>{await page.locator('[data-pa=sample]').first().click();await submit();};
  try{
    await page.goto(pathToFileURL(path.resolve('dist/index.html')).href);
    await expect(page.locator('h1')).toHaveText('Báo giá cơ khí');await tab('pricing');
    expect(await page.evaluate(()=>result.errors)).toEqual([]);
    expect(await page.evaluate(()=>result.total.grand)).toBe(7126053);
    await expect(page.locator('[data-pa=choose]')).toHaveCount(4);check('Fresh offline sample opens with four methods and new customer formula');
    await page.screenshot({path:path.join(folder,'01-phan-tich-gia.png'),fullPage:true});
    await page.locator('[data-pa=policy]').click();
    await page.locator('[name=customer]').fill('20');await page.locator('[name=order]').fill('10');
    await page.locator('[name=install]').fill('100000');await submit();
    expect(await page.evaluate(()=>result.errors)).toEqual([]);
    expect(await page.evaluate(()=>result.products.every(p=>p.unitSell===Math.round(p.cost*1.1*1.03*1.1*1.2/p.node.qty)))).toBe(true);
    check('UI edits order / customer independently and includes installation in base cost');
    await page.locator('[data-pa=choose][data-method=kg]').click();
    expect(await page.evaluate(()=>db.quote.pricing.selected)).toBe('kg');
    expect(await page.evaluate(()=>result.products.every(p=>p.unitSell===Math.round(p.weight/p.node.qty*p.node.pricePerKg)))).toBe(true);
    await page.locator('[data-pa=choose][data-method=competitor]').click();
    expect(await page.evaluate(()=>result.products.map(p=>p.unitSell))).toEqual([395000,320000]);check('One method selection updates every product');
    await page.locator('[data-pa=product-inputs]').click();const ids=await page.evaluate(()=>db.quote.products.map(p=>p.id));
    await page.locator(`[name="kg-${ids[0]}"]`).fill('');await submit();
    await expect(page.locator('[data-pa=choose][data-method=kg]')).toBeDisabled();check('Missing kg rate cannot be selected as a zero-cost quote');
    await sample();await tab('operations');
    await expect(page.locator('.pa-operations tbody tr')).toHaveCount(10);
    expect(await page.evaluate(()=>result.generated.length)).toBe(1);
    const p0=await page.evaluate(()=>db.quote.products[0].id);
    await page.locator(`select[data-pa-op-mode][data-id="${p0}"]`).selectOption('outside');
    expect(await page.evaluate(()=>result.generated.length)).toBe(0);
    await page.locator(`select[data-pa-op-mode][data-id="${p0}"]`).selectOption('inside');
    expect(await page.evaluate(()=>result.generated[0].quantity)).toBeCloseTo(1.92,8);
    check('Finishing consumption is automatic; all-in outsourcing does not double count');
    const matrix=page.locator('[data-pa-scroll]');await matrix.evaluate(el=>{el.scrollLeft=450;el.scrollTop=180;});
    const currentLeft=await matrix.evaluate(el=>el.scrollLeft);
    const newOp=page.locator(`[data-pa-op-toggle][data-id="${p0}"][data-rate=weld]`);
    await newOp.check();expect(await matrix.evaluate(el=>el.scrollLeft)).toBe(currentLeft);
    await newOp.uncheck();check('Operation changes retain matrix scroll position');
    await page.locator('[data-pa=quote-rates]').click();await page.locator('#dialog [data-pa=edit-rate][data-id=cut]').click();
    await page.locator('.pa-factor-editor').first().locator('.pa-tier-value').first().fill('25');await submit();
    expect(await page.evaluate(()=>result.nodes[db.quote.products[0].children[0].id].ownOps[0].rate)).toBeCloseTo(1187.5,8);
    check('Editable operation matrix factors change actual applied rates');
    await page.screenshot({path:path.join(folder,'02-cong-doan-dinh-muc.png'),fullPage:true});
    await tab('pricing');const detailBefore=await page.evaluate(()=>result.alternatives.detail.total.grand);
    await page.locator('[data-pa=tmc]').click();await page.locator('[name=loss]').fill('8');await submit();
    expect(await page.evaluate(()=>result.alternatives.detail.total.grand)).toBe(detailBefore);
    await page.locator('[data-pa=choose][data-method=tmc]').click();check('TMC loss edits do not rewrite the detailed cutting-cost method');
    await page.locator('[data-pa=final-price]').first().click();await page.locator('[name=value]').fill('1');await page.locator('[name=reason]').fill('Thử cảnh báo nội bộ');await submit();
    await expect(page.locator('.notice.warning')).toContainText('Giá chào dưới giá gốc');
    await tab('preview');await page.locator('[data-action=approve]').click();await expect(page.locator('#dialog-title')).toHaveText('Xác nhận báo giá dưới giá gốc');await close();
    await tab('pricing');await page.locator('[data-pa=policy]').click();await page.locator('[name=customer]').fill('5');await submit();
    expect(await page.evaluate(()=>result.errors.some(e=>e.includes('xác nhận lại')))).toBe(true);
    await tab('preview');await expect(page.locator('.paper')).toHaveCount(0);check('Manual price records reason, warns below cost and blocks stale output');
    await sample();await tab('preview');
    await expect(page.locator('.paper-grand')).toContainText('7.126.053');
    await expect(page.locator('.paper')).not.toContainText('Hệ số');await expect(page.locator('.paper')).not.toContainText('Giá gốc');
    await page.locator('[data-action=approve]').click();await submit();
    expect(await page.evaluate(()=>db.history.length)).toBe(1);await page.reload();
    expect(await page.evaluate(()=>db.quote.status)).toBe('approved');await tab('preview');
    const downloadPromise=page.waitForEvent('download');await page.locator('[data-action=export-quote]').click();const download=await downloadPromise;await download.saveAs(path.join(folder,'bao-gia-thu.csv'));
    const csv=fs.readFileSync(path.join(folder,'bao-gia-thu.csv'),'utf8');expect(csv).toContain('7126053');expect(csv).not.toContain('Hệ số');
    await page.evaluate(()=>{document.querySelector('#print-area').innerHTML=paper();});
    await page.pdf({path:path.join(folder,'03-bao-gia-thu.pdf'),format:'A4',printBackground:true});check('Quote PDF/CSV share selected totals; no internal costing; history survives reload');
    await page.setViewportSize({width:390,height:844});
    for(const name of ['bom','operations','waste','mass','pricing','preview']){await tab(name);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),name+' page overflow').toBe(true);}
    await tab('pricing');await page.screenshot({path:path.join(folder,'04-mobile.png'),fullPage:true});check('All six tabs keep tables within horizontal scrollers on mobile');
    await page.setViewportSize({width:1440,height:1000});await tab('bom');await page.locator('[data-ux=detail-mode]').click();
    await expect(page.locator('.viewer3d')).toBeVisible();check('3D product inspection still available');
    await page.evaluate(()=>{db=C.seed();selected=db.quote.products[0].id;page='quote';tab='bom';persist();});await page.reload();
    await expect(page.locator('[data-pa=enable]')).toBeVisible();expect(await page.evaluate(()=>!!db.quote.pricing)).toBe(false);
    const legacyNames=await page.evaluate(()=>db.quote.products.map(p=>p.name));
    await page.locator('[data-pa=enable]').click();await submit();expect(await page.evaluate(()=>db.quote.products.map(p=>p.name))).toEqual(legacyNames);
    expect(await page.evaluate(()=>!!db.quote.pricing)).toBe(true);check('Legacy quote requires explicit conversion and retains product structure');
    expect(errors).toEqual([]);check('No browser JavaScript errors');
    fs.writeFileSync(path.join(folder,'browser-results.json'),JSON.stringify({passed,errors},null,2));
  }catch(e){await page.screenshot({path:path.join(folder,'failure.png'),fullPage:true});console.error('Browser errors',errors);throw e;}
  finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
