const {test}=require('node:test'),A=require('node:assert/strict'),{randomUUID}=require('node:crypto'),{createApp}=require('../server/app.cjs');
test('custom workflows: permissions, editable definitions, parallel barrier, snapshots and idempotent creation',async t=>{
 const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));let admin;
 const call=async(path,method='GET',body,session=admin)=>{const r=await fetch('http://127.0.0.1:'+app.server.address().port+'/api/'+path,{method,headers:{'Content-Type':'application/json',Cookie:session?.cookie||'','X-CSRF-Token':session?.csrf||''},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};};
 const ok=r=>{A.equal(r.status,200,JSON.stringify(r.data));return r.data;};admin=await call('setup','POST',{username:'admin',name:'Admin',password:'Custom-test-2026!'});
 for(const name of ['head','viewer'])await require('./helpers/personnel-user.cjs')(call,admin,{username:name,name,role:'estimator',password:'Custom-test-2026!',actionAccess:{processRouting:name==='head'?['view','submit','confirm','return','propose','assign']:['view']}});
 const head=await call('login','POST',{username:'head',password:'Custom-test-2026!'}),viewer=await call('login','POST',{username:'viewer',password:'Custom-test-2026!'});
 const org=ok(await call('organization')),departmentId=org.departments.find(d=>d.name==='Fixture head').id;org.positions.find(p=>p.departmentId===departmentId).manager=true;app.sql.prepare('UPDATE organization SET document=? WHERE id=1').run(JSON.stringify(org));
 const id='custom-'+randomUUID(),step=(name,parallelWithPrevious=false,admin=false)=>({key:'review-'+randomUUID(),name,departmentId:admin?'':departmentId,module:'processRouting',instructions:'Kiểm tra',parallelWithPrevious,admin});
 const draft={action:'save',id,name:'Quy trình riêng',expectedVersion:0,active:true,steps:[step('Kỹ thuật'),step('Kho',true),step('Duyệt',false,true)]};
 A.equal((await call('process-routing','POST',draft,head)).status,403);
 A.equal((await call('process-routing','POST',{...draft,steps:[]})).status,400);
 A.equal((await call('process-routing','POST',{...draft,steps:draft.steps.map((s,i)=>({...s,parallelWithPrevious:i===0}))})).status,400);
 const saved=ok(await call('process-routing','POST',draft));A.equal(saved.custom,true);A.equal(saved.version,1);
 const create={action:'start-custom',definitionId:id,requestId:randomUUID(),title:'Kiểm tra thiết bị',description:'Căn cứ yêu cầu xưởng'};
 A.equal((await call('process-routing','POST',create,viewer)).status,403);
 let r=ok(await call('process-routing','POST',create,head));A.equal(r.activeSteps.length,2);A.equal(r.description,create.description);
 A.equal(ok(await call('process-routing','POST',create,head)).id,r.id);
 const inbox=ok(await call('notifications','GET',undefined,head));const messages=inbox.items.filter(n=>n.processId===r.id);A.equal(messages.length,2);A.ok(messages.every(n=>!n.readAt));
 A.equal(ok(await call('notifications','GET',undefined,viewer)).items.filter(n=>n.processId===r.id).length,0);
 A.equal((await call('notifications/'+messages[0].id+'/read','POST',{},viewer)).status,404);
 ok(await call('notifications/'+messages[0].id+'/read','POST',{},head));A.ok(ok(await call('notifications','GET',undefined,head)).items.find(n=>n.id===messages[0].id).readAt);

 A.equal(ok(await call('process-routing','GET',undefined,viewer)).instances.length,0);
 const updated=ok(await call('process-routing','POST',{...draft,expectedVersion:1,name:'Tên mới',steps:[...draft.steps,step('Lưu kết quả')]}));A.equal(updated.version,2);
 r=ok(await call('process-routing','GET',undefined,head)).instances.find(x=>x.id===r.id);A.equal(r.definitionVersion,1);A.equal(r.steps.length,3);
 const complete=async(key,session=head)=>{r=ok(await call('process-routing','POST',{action:'complete',id:r.id,stepKey:key,expectedVersion:r.version,note:'Đạt'},session));};
 await complete(draft.steps[1].key);A.equal(r.index,0);A.equal(r.activeSteps.length,1);
 await complete(draft.steps[0].key);A.equal(r.index,2);
 A.equal((await call('process-routing','POST',{action:'complete',id:r.id,stepKey:draft.steps[2].key,expectedVersion:r.version,note:'Đạt'},head)).status,403);
 await complete(draft.steps[2].key,admin);A.equal(r.state,'completed');
 ok(await call('process-routing','POST',{...draft,expectedVersion:2,active:false}));A.equal((await call('process-routing','POST',{...create,requestId:randomUUID()},head)).status,400);
 A.equal(ok(await call('process-routing','GET',undefined,head)).availableProcesses.length,0);
});
