'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),P=require('../pricing-core.js'),C=require('../core.js'),CV=require('../conventions-core.js');
async function run(t){const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port;let session;const call=async(route,method='GET',body)=>{const r=await fetch(base+'/api/'+route,{method,headers:{'Content-Type':'application/json',...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const s=await call('setup','POST',{username:'admin',name:'Kiểm thử quy ước',password:'Only-for-definition-tests-42!'});session={cookie:s.cookie,csrf:s.data.csrf};return {call};}

test('server persists group catalogue and product selections, blocks removal of used default/custom groups and malformed values',async t=>{
 const {call}=await run(t),master=(await call('catalog')).data,doc=P.demoSeed();CV.save(doc,'productGroups',{name:'Bồn QA'});const saved=await call('catalog','PUT',{expectedVersion:master.version,catalog:{...master.catalog,conventions:doc.conventions}});A.equal(saved.status,200,JSON.stringify(saved));
 let current=(await call('catalog')).data;A.ok(CV.entries(current.catalog,'productGroups').some(x=>x.name==='Bồn QA'));
 doc.quote.products[0].productGroup='Cửa gió';doc.quote.products.push({...C.cloneNode(doc.quote.products[0]),id:'CUSTOM-GROUP-QA',productGroup:'Bồn QA'});const created=await call('quotes','POST',{document:doc});A.equal(created.status,201,JSON.stringify(created));const read=(await call('quotes/'+created.data.id)).data.document;A.equal(read.quote.products[0].productGroup,'Cửa gió');A.equal(read.quote.products.at(-1).productGroup,'Bồn QA');A.deepEqual(P.calculate(read).total,P.calculate(doc).total);
 for(const name of ['Cửa gió','Bồn QA']){current=(await call('catalog')).data;const catalog=structuredClone(current.catalog);catalog.conventions.productGroups=(catalog.conventions.productGroups||[]).filter(x=>x.name!==name).concat({name,hidden:true});const denied=await call('catalog','PUT',{expectedVersion:current.version,catalog});A.equal(denied.status,400,JSON.stringify(denied));}
 const bad=structuredClone(doc);bad.quote.products[0].productGroup={name:'invalid'};A.equal((await call('quotes','POST',{document:bad})).status,400);
});
