const {chromium,expect}=require('@playwright/test'),{createApp}=require('../artifacts/gd1-report-2026-09-20/release/server/app.cjs'),path=require('node:path'),fs=require('node:fs');
(async()=>{const app=createApp({staticRoot:path.resolve('artifacts/gd1-report-2026-09-20/release/dist')});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port,b=await chromium.launch({channel:'msedge',headless:true}),errors=[];try{
 const admin=await b.newPage({viewport:{width:1366,height:768}}),tech=await b.newPage({viewport:{width:1366,height:768}});for(const p of [admin,tech]){p.on('pageerror',e=>errors.push(e.message));await p.goto(base);await p.waitForFunction(()=>Team.available);}
 const password='Local-production-browser-2026!';await admin.evaluate(async password=>{teamSession(await teamApi('setup','POST',{username:'admin',name:'Quản trị',password}));await teamApi('users','POST',{username:'tech',name:'Kỹ thuật xưởng',role:'technical',password});const doc=JSON.parse(JSON.stringify(db));const q=await teamApi('quotes','POST',{document:doc});await teamApi('quotes/'+q.id+'/submit','POST',{expectedVersion:1});await teamApi('quotes/'+q.id+'/approve','POST',{expectedVersion:2});await teamApi('quotes/'+q.id+'/order','POST',{expectedVersion:3,code:'DH-XUONG-01'});render();},password);
 await tech.evaluate(async password=>{teamSession(await teamApi('login','POST',{username:'tech',password}));render();},password);
 await admin.locator('[data-production-launch]').click();await admin.locator('[data-production=issue]').click();await admin.locator('#production-order').selectOption({label:'DH-XUONG-01 · bản 3'});await admin.locator('#production-issue [name=code]').fill('LSX-TEST-01');await admin.locator('#production-issue [name=quantity]').fill('1');await admin.locator('#production-issue [type=submit]').click();await expect(admin.locator('#production-main h3').first()).toContainText('LSX-TEST-01');
 await tech.locator('[data-production-launch]').click();await expect(tech.locator('[data-production=issue]')).toHaveCount(0);await tech.locator('[data-production-job]').click();await tech.locator('[name=drawingReady]').check();await tech.locator('[name=materialsReady]').check();await tech.locator('[name=workshop]').fill('Xưởng cơ khí 1');await tech.locator('[name=deadline]').fill('2026-10-01');await tech.locator('#production-prepare [type=submit]').click();await expect(tech.locator('#production-message')).toHaveText('Đã lưu lên máy chủ');
 // Stale admin save must be rejected and preserve entered data.
 await admin.locator('[name=workshop]').fill('Stale');await admin.locator('#production-prepare [type=submit]').click();await expect(admin.locator('#production-message')).toContainText('người khác');await admin.locator('[data-production=refresh]').click();await expect(admin.locator('[name=workshop]')).toHaveValue('Xưởng cơ khí 1');
 await tech.locator('[data-production-tab=operations]').click();const ops=await tech.locator('.production-operation').count();for(let i=0;i<ops;i++){const f=tech.locator('.production-operation').nth(i);await f.locator('[name=status]').selectOption('done');const max=await f.locator('[name=output]').getAttribute('max');await f.locator('[name=output]').fill(max);await f.locator('[type=submit]').click();await tech.waitForFunction(()=>!Production.saving);await expect(tech.locator('.production-operation').nth(i).locator('[type=submit]')).toBeDisabled();}
 await tech.locator('[data-production-tab=materials]').click();await expect(tech.locator('#production-materials table')).toBeVisible();await tech.locator('[data-production-tab=cutting]').click();await expect(tech.locator('.production-sheet svg').first()).toBeVisible();
 for(const width of [1920,1366,1093]){await tech.setViewportSize({width,height:768});expect(await tech.locator('#production-console').evaluate(d=>d.scrollWidth<=d.clientWidth+1)).toBe(true);expect(await tech.locator('#production-console').evaluate(d=>d.getBoundingClientRect().width)).toBeGreaterThan(Math.min(1500,width-100));await tech.screenshot({path:`artifacts/customer-review/production-${width}.png`});}
 await tech.locator('[data-production-tab=qc]').click();await tech.locator('#production-qc-form [name=passed]').fill('1');await tech.locator('#production-qc-form [type=submit]').click();await tech.waitForFunction(()=>!Production.saving);await expect(tech.locator('#production-message')).toHaveText('Đã lưu lên máy chủ');await tech.locator('[data-production=complete]').click();await expect(tech.locator('.production-heading .production-status')).toHaveText('Hoàn thành');await expect(tech.locator('#production-qc-form [name=passed]')).toBeDisabled();
 await tech.reload();await tech.waitForFunction(()=>Team.user);await tech.locator('[data-production-launch]').click();await expect(tech.locator('[data-job-state=completed]')).toHaveCount(1);await tech.locator('[data-production-job]').click();await tech.evaluate(()=>teamSession({user:null,permissions:null,csrf:''}));expect(await tech.locator('#production-console').count()).toBe(0);expect(errors).toEqual([]);console.log('PASS production: admin issue, technical receive, readiness, conflict, operations, cutting, QC, completion, reload, laptop layouts');
 }finally{await b.close();await new Promise(r=>app.server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
