'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),P=require('../pricing-core.js'),{approveRoute,settleStage}=require('./production-flow-fixture.cjs');
test('production routing, mass balance, remnant return, stage stock and shipping are atomic and permission checked',async t=>{
 const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));let admin;const call=async(route,method='GET',body,s=admin)=>{const r=await fetch('http://127.0.0.1:'+app.server.address().port+'/api/'+route,{method,headers:{'Content-Type':'application/json',Cookie:s?.cookie||'','X-CSRF-Token':s?.csrf||''},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};};admin=await call('setup','POST',{username:'admin',name:'Admin',password:'Production-flow-2026!'});const uid=admin.data.user.id;
 await call('users','POST',{username:'tech',name:'Technical',role:'technical',password:'Production-flow-2026!',actionAccess:{production:['view','edit','confirm']}});const tech=await call('login','POST',{username:'tech',password:'Production-flow-2026!'});
 const d=P.demoSeed();d.quote.products=[d.quote.products[0]];d.quote.products[0].qty=1;d.quote.remnantMode='all';d.quote.remnantSelections={};const q=(await call('quotes','POST',{document:d})).data;await call('quotes/'+q.id+'/submit','POST',{expectedVersion:1});await call('quotes/'+q.id+'/approve','POST',{expectedVersion:2});const o=(await call('quotes/'+q.id+'/order','POST',{expectedVersion:3,code:'FLOW'})).data;await call('orders/'+o.id+'/confirm','POST',{quoteVersion:3});let j=(await call('production','POST',{orderId:o.id,productId:d.quote.products[0].id,quantity:1,code:'FLOW-01'})).data;
 const update=async b=>{const r=await call('production/'+j.id,'PUT',{expectedVersion:j.version,...b});if(r.status===200)j=r.data;return r;};await update({action:'prepare',deadline:'',workshop:'A',materialsReady:true,drawingReady:true,note:''});A.ok(j.packet,JSON.stringify(j));const first=j.packet.operations[0];A.equal((await update({action:'operation',operationId:first.id,status:'running',assignee:uid,machine:'M',output:0,note:''})).status,409);
 const proposal=(await call('production/'+j.id+'/flow/plan','POST',{expectedVersion:j.version,reason:'Reviewed technology',operations:j.packet.operations.map(x=>({...x,lossPercent:0,machine:'M',workQuantity:x.workQuantity||1,unit:x.unit||'hour'}))},tech)).data;
 A.equal((await call('production/'+j.id+'/flow/approve','POST',{expectedVersion:j.version,id:proposal.id})).status,409);A.equal((await call('production/'+j.id+'/flow/confirm','POST',{expectedVersion:j.version,id:proposal.id},tech)).status,200);A.equal((await call('production/'+j.id+'/flow/approve','POST',{expectedVersion:j.version,id:proposal.id},tech)).status,403);A.equal((await call('production/'+j.id+'/flow/approve','POST',{expectedVersion:j.version,id:proposal.id})).status,200);j=(await call('production/'+j.id)).data;
 j=await require('./production-review-fixture.cjs').review(call,admin,j.id);await require('./ops-fixture.cjs').seedStock(call,admin,j.id);A.equal((await update({action:'operation',operationId:first.id,status:'running',assignee:'',machine:'M',output:0,note:''})).status,400);A.equal((await update({action:'operation',operationId:first.id,status:'running',assignee:uid,machine:'M',output:0,note:'Started',issue:'Tool inspection',proposal:'Check blade'})).status,200);
 const flow=(await call('production/'+j.id+'/flow')).data;A.ok(flow.inputs.length);const body={expectedVersion:j.version,operationId:first.id,output:first.quantity,warehouse:'Phôi',reason:'Đã đo thực tế; phế do mạch cắt',materials:flow.inputs.map(x=>({holdId:x.holdId,productWeight:x.inputWeight,scrapWeight:0,remnants:[]}))};
 A.equal((await call('production/'+j.id+'/flow/settle','POST',body,tech)).status,403);
 A.equal((await call('production/'+j.id+'/flow/settle','POST',{...body,output:0})).status,400);
 const bad=structuredClone(body);bad.materials[0].productWeight+=1;const before=(await call('ops/state')).data;A.equal((await call('production/'+j.id+'/flow/settle','POST',bad)).status,400);A.equal((await call('ops/state')).data.movements.length,before.movements.length);
 const next=j.packet.operations[1];if(next)A.equal((await update({action:'operation',operationId:next.id,status:'running',assignee:uid,machine:'M',output:0,note:''})).status,409);
 const sheet=flow.inputs.find(x=>{const h=before.holds.find(h=>h.id===x.holdId),l=before.lots.find(l=>l.id===h.lotId);return l.length&&l.width;});A.ok(sheet);const hold=before.holds.find(h=>h.id===sheet.holdId),lot=before.lots.find(l=>l.id===hold.lotId),mat=body.materials.find(x=>x.holdId===sheet.holdId),remWeight=lot.unitWeight/4;mat.productWeight-=remWeight+.1;mat.scrapWeight=.1;mat.remnants=[{quantity:1,length:lot.length/4,width:lot.width,thickness:lot.thickness,unitWeight:remWeight}];
 const results=await Promise.all([call('production/'+j.id+'/flow/settle','POST',body),call('production/'+j.id+'/flow/settle','POST',body)]);A.deepEqual(results.map(r=>r.status).sort(),[200,409]);j=results.find(r=>r.status===200).data;const after=(await call('ops/state')).data;A.equal(after.lots.filter(l=>l.sourceLotId===lot.id).length,1);A.equal(after.stageStocks.length,1);A.equal(j.progress.operations[0].status,'done');
 A.equal((await call('production/'+j.id+'/flow/plan','POST',{expectedVersion:j.version,reason:'Cannot alter past',operations:j.packet.operations.map(x=>({...x,machine:'Changed'}))})).status,409);
 for(const op of j.packet.operations.slice(1)){A.equal((await update({action:'operation',operationId:op.id,status:'running',assignee:uid,machine:'M',output:0,hours:1,note:''})).status,200);j=await settleStage(call,admin,j.id);}
 A.equal((await update({action:'qc',passed:1,rejected:0,note:'Pass'})).status,200);A.equal((await update({action:'complete'})).status,200);let stocks=(await call('ops/state')).data.stageStocks;A.equal(stocks.filter(s=>!s.consumedBy).length,1);A.equal(stocks.find(s=>!s.consumedBy).kind,'finished');
 const order=(await call('business/orders/'+o.id)).data;A.equal((await call('business/orders/'+o.id+'/deliver','POST',{expectedVersion:order.version,date:'2026-09-25',receiver:'Customer',note:''})).status,200);stocks=(await call('ops/state')).data.stageStocks;A.ok(stocks.every(s=>s.consumedBy));const report=(await call('reports?kind=inventory&from=2026-01-01&to=2026-12-31')).data;A.ok(report.tables.find(t=>t.id==='production-stock').rows.every(r=>r.closing===0));A.deepEqual((await call('orders/'+o.id)).data.quote.products,d.quote.products);
});

