const {test}=require('node:test'),A=require('node:assert/strict'),{randomUUID,createECDH,randomBytes}=require('node:crypto'),{createApp}=require('../server/app.cjs');
test('persistent push: authenticated opt-in, transactional delivery, privacy, retries and device revocation',async t=>{
 const delivered=[];let error=null;const app=createApp({pushInterval:0,pushTransport:async(s,p,o)=>{if(error)throw error;delivered.push({s,p:JSON.parse(p),o});}});
 await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port;
 const call=async(route,method='GET',body,s)=>{const r=await fetch(base+'/api/'+route,{method,headers:{'Content-Type':'application/json',...(s?{Cookie:s.cookie,'X-CSRF-Token':s.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
 const password='Push-test-password-2026';const admin=await call('setup','POST',{username:'admin',name:'Admin',password});admin.csrf=admin.data.csrf;
 const u=(await call('users','POST',{username:'tech',name:'Tech',password,role:'technical'},admin)).data;
 const tech=await call('login','POST',{username:'tech',password});tech.csrf=tech.data.csrf;
 const ec=createECDH('prime256v1');ec.generateKeys();const subscription={endpoint:'https://fcm.googleapis.com/fcm/send/test',keys:{p256dh:ec.getPublicKey().toString('base64url'),auth:randomBytes(16).toString('base64url')}};
 A.equal((await call('push')).status,401);A.equal((await call('push','POST',{subscription},{...tech,csrf:'bad'})).status,403);
 A.equal((await call('push','POST',{subscription:{...subscription,endpoint:'https://localhost/private'}},tech)).status,400);
 A.equal((await call('push','POST',{subscription},tech)).status,200);const publicKey=(await call('push','GET',undefined,tech)).data.publicKey;A.ok(publicKey);A.equal((await call('push','GET',undefined,tech)).data.privateKey,undefined);
 const room=(await call('chat/rooms','POST',{kind:'direct',members:[u.id]},admin)).data;
 const message={clientId:randomUUID(),body:'Confidential price 999999'};const sent=(await call('chat/rooms/'+room.id+'/messages','POST',message,admin)).data;
 await call('chat/rooms/'+room.id+'/messages','POST',message,admin);A.equal(app.sql.prepare('SELECT COUNT(*) AS n FROM push_outbox').get().n,1);
 await call('push','POST',{subscription},tech);A.equal(app.sql.prepare('SELECT COUNT(*) AS n FROM push_outbox').get().n,1,'refreshing same device retains pending notifications');
 await app.push.flush();A.equal(delivered.length,1);A.equal(delivered[0].o.vapidDetails.publicKey,publicKey);A.ok(!JSON.stringify(delivered[0].p).includes('999999'));A.equal(delivered[0].p.userId,u.id);await app.push.flush();A.equal(delivered.length,1);
 const send=()=>call('chat/rooms/'+room.id+'/messages','POST',{clientId:randomUUID(),body:'Another'},admin);
 const read=(await send()).data;await call('chat/rooms/'+room.id+'/read','POST',{seq:read.seq},tech);await app.push.flush();A.equal(delivered.length,1);
 await send();error={statusCode:503};await app.push.flush();A.equal(app.sql.prepare('SELECT attempts FROM push_outbox').get().attempts,1);error=null;app.sql.prepare('UPDATE push_outbox SET due=0').run();await app.push.flush();A.equal(delivered.length,2);
 await send();error={statusCode:410};await app.push.flush();A.equal(app.sql.prepare('SELECT COUNT(*) AS n FROM push_subscriptions').get().n,0);error=null;
 await call('push','POST',{subscription},tech);await send();await call('logout','POST',{},tech);await app.push.flush();A.equal(delivered.length,2);A.equal(app.sql.prepare('SELECT COUNT(*) AS n FROM push_outbox').get().n,0);
 const again=await call('login','POST',{username:'tech',password});again.csrf=again.data.csrf;await call('push','POST',{subscription},again);await send();await call('push','POST',{subscription},admin);await app.push.flush();A.equal(delivered.length,2,'rebinding browser drops old user jobs');
 await call('push','POST',{subscription},again);await send();await call('users/'+u.id+'/disable','POST',{},admin);await app.push.flush();A.equal(delivered.length,2,'disabled accounts cannot receive');
 for(const route of ['/sw.js','/manifest.webmanifest','/push-icon.png'])A.equal((await fetch(base+route)).status,200);
 A.ok(sent.seq);
 A.equal((await call('push/test','POST',{endpoint:subscription.endpoint},admin)).status,400);
 await call('push','POST',{subscription},admin);
 A.equal((await call('push/test','POST',{endpoint:subscription.endpoint},{...admin,csrf:'bad'})).status,403);
 A.equal((await call('push/test','POST',{endpoint:subscription.endpoint},admin)).status,202);
 A.equal((await call('push/test','POST',{endpoint:subscription.endpoint},admin)).status,429);
 await app.push.flush();A.equal(delivered.length,2,'test waits ten seconds so user can lock screen');
 app.sql.prepare('UPDATE push_outbox SET due=0').run();await app.push.flush();A.equal(delivered.length,3);A.match(delivered.at(-1).p.tag,/^tp-test-/);A.equal(delivered.at(-1).p.userId,admin.data.user.id);
});
test('work outbox survives restart with stable VAPID keys and follows recipient permissions',async t=>{
 const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'tp-push-')),databasePath=path.join(dir,'db.sqlite'),sent=[];
 let app=createApp({databasePath,pushInterval:0,pushTransport:async(s,p)=>sent.push(JSON.parse(p))});
 const key=app.sql.prepare('SELECT public_key FROM push_keys').get().public_key;
 const run=(s,...a)=>app.sql.prepare(s).run(...a),at=new Date().toISOString();
 run('INSERT INTO users(id,username,name,role,password) VALUES(?,?,?,?,?)','sender','sender','Sender','admin','unused');
 run('INSERT INTO users(id,username,name,role,password) VALUES(?,?,?,?,?)','tech','tech','Tech','technical','unused');
 run('INSERT INTO quotes VALUES(?,?,?,?,?,?,?,?,?,?)','q','BG-test','','',1,'draft',0,'{}',at,'sender');
 run('INSERT INTO push_subscriptions VALUES(?,?,?,?,?)','https://fcm.googleapis.com/test','tech','session','{}',Date.now());
 run('INSERT INTO handoff_events VALUES(?,?,?,?,?,?,?)','e','q','assigned-technical',1,'sender',at,'');
 run('INSERT INTO notifications VALUES(?,?,?,NULL)','n','tech','e');
 app.server.emit('close');app=createApp({databasePath,pushInterval:0,pushTransport:async(s,p)=>sent.push(JSON.parse(p))});
 t.after(()=>{app.server.emit('close');fs.rmSync(dir,{recursive:true,force:true});});
 A.equal(app.sql.prepare('SELECT public_key FROM push_keys').get().public_key,key);await app.push.flush();A.equal(sent.length,1);A.match(sent[0].tag,/^tp-work-/);
 run('INSERT INTO handoff_events VALUES(?,?,?,?,?,?,?)','e2','q','materials',1,'sender',at,'');run('INSERT INTO notifications VALUES(?,?,?,NULL)','n2','tech','e2');await app.push.flush();A.equal(sent.length,1,'technical recipient cannot receive approval-only work');
 app.sql.exec('BEGIN');run('INSERT INTO handoff_events VALUES(?,?,?,?,?,?,?)','e3','q','assigned-technical',1,'sender',at,'');run('INSERT INTO notifications VALUES(?,?,?,NULL)','rolled-back','tech','e3');app.sql.exec('ROLLBACK');A.equal(app.sql.prepare('SELECT COUNT(*) AS n FROM push_outbox').get().n,0);
});
