'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),{createQuotePresence}=require('../server/quote-presence.cjs'),{permissions}=require('../server/access.cjs'),P=require('../pricing-core.js');
test('presence separates users and tabs, leaves no revisions, expires and enforces internal access',async t=>{
 const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));let cookie='',csrf='';
 async function call(path,method='GET',body){const r=await fetch('http://127.0.0.1:'+app.server.address().port+'/api/'+path,{method,headers:{'Content-Type':'application/json',Cookie:cookie,'X-CSRF-Token':csrf},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();if(['setup','login'].includes(path)){cookie=r.headers.get('set-cookie').split(';')[0];csrf=data.csrf;}return {status:r.status,data};}
 const password='Presence-test-local-42!';await call('setup','POST',{username:'admin',name:'Admin',password});await call('users','POST',{username:'tech',name:'Technical',role:'technical',password});await call('users','POST',{username:'sales',name:'Sales',role:'sales',password});const q=(await call('quotes','POST',{document:P.demoSeed()})).data,before=app.sql.prepare('SELECT * FROM quotes WHERE id=?').get(q.id),count=app.sql.prepare('SELECT count(*) AS n FROM revisions').get().n;
 const tab='presence_admin_tab_1',second='presence_admin_tab_2';A.equal((await call('quote-presence','POST',{clientId:tab,quoteId:q.id,editing:true})).status,200);await call('quote-presence','POST',{clientId:second,quoteId:q.id,editing:false});A.equal((await call('quote-presence')).data.quotes[q.id].length,1);
 await call('quote-presence','POST',{clientId:tab,quoteId:null,editing:false});A.equal((await call('quote-presence')).data.quotes[q.id][0].editing,false);
 await call('login','POST',{username:'tech',password});const two=await call('quote-presence','POST',{clientId:'presence_tech_tab_1',quoteId:q.id,editing:true});A.equal(two.data.quotes[q.id].length,2);A.equal(two.data.quotes[q.id].find(x=>x.name==='Technical').editing,true);A.deepEqual(app.sql.prepare('SELECT * FROM quotes WHERE id=?').get(q.id),before);A.equal(app.sql.prepare('SELECT count(*) AS n FROM revisions').get().n,count);
 await call('logout','POST',{});await call('login','POST',{username:'admin',password});A.equal((await call('quote-presence')).data.quotes[q.id].length,1);await call('login','POST',{username:'sales',password});A.equal((await call('quote-presence')).status,403);
 // Controllable clock checks disconnected tabs without a real 75-second wait.
 let now=Date.now(),body,out;const user={...app.sql.prepare("SELECT u.*,s.token FROM users u JOIN sessions s ON u.id=s.user_id WHERE username='admin' LIMIT 1").get()},presence=createQuotePresence({sql:app.sql,now:()=>now,readBody:async()=>body,getQuote:id=>app.sql.prepare('SELECT * FROM quotes WHERE id=?').get(id),fail:(status,message)=>{throw Error(status+message);}}),invoke=async method=>presence.handle({req:{method},route:'/api/quote-presence',user,rights:permissions(user),send:(code,data)=>out=data});body={clientId:'expiry_presence_tab',quoteId:q.id,editing:true};await invoke('POST');A.equal(out.quotes[q.id].length,1);now+=75001;await invoke('GET');A.deepEqual(out.quotes,{});
});
