const {test}=require('node:test'),A=require('node:assert/strict'),C=require('../core.js'),P=require('../pricing-core.js'),Pkg=require('../package-operation-core.js'),I=require('../input-prices-core.js');
test('TMC reconciliation uses exact calculated replacement, factors and quantities without changing detailed costs',()=>{
 const d=P.demoSeed(),before=P.calculate(d),technical=JSON.stringify(d.quote.products);
 Pkg.save(d,{id:'pkg-audit',name:'Gói đối chiếu',operationType:'package',unit:'m',inside:0,outside:0,insideUnit:'m',outsideUnit:'m',factors:[{id:'audit',name:'Điều chỉnh',param:'W',tiers:[{max:null,percent:20}]}],tmcPackage:{tableIds:['tray'],replaces:['cut']}});I.refresh(d);
 const r=P.calculate(d);A.equal(JSON.stringify(d.quote.products),technical);A.deepEqual(r.alternatives.detail.total,before.alternatives.detail.total);
 for(const p of r.alternatives.tmc.products){const a=p.tmc.laborReconciliation;A.ok(a);const nodes=C.flatten([p.node]);const expected=nodes.reduce((s,n)=>s+r.nodes[n.id].ownOps.filter(o=>!o.skipped&&n.ops[o.index].mode==='inside'&&!n.ops[o.index].afterPackage&&n.ops[o.index].id==='cut').reduce((x,o)=>x+o.cost,0),0);A.equal(a.replacedFactory,expected);A.equal(a.finalFactory,p.parts.factory);A.equal(a.retainedFactory+a.packageLabor,a.finalFactory);A.equal(a.originalFactory-a.replacedFactory+a.packageLabor,a.finalFactory);for(const i of p.tmc.items){A.equal(i.width,p.node.params.W);A.equal(i.count,p.node.qty);A.equal(i.basis,i.length/1000*i.count*i.quantityFactor);A.equal(i.rate,i.bound.value*1.2);A.equal(i.labor,i.rate*i.basis);}}
});
test('legacy width table and piece table expose reconciliation; failed TMC does not expose successful totals',()=>{
 const d=P.demoSeed();d.quote.pricing.tmcTables.find(t=>t.id==='tray').unit='cái';const r=P.calculate(d);for(const p of r.alternatives.tmc.products){A.equal(p.tmc.items[0].basis,p.node.qty);A.equal(p.tmc.laborReconciliation.finalFactory,p.parts.factory);A.equal(p.tmc.items[0].laborPricing,null);}d.quote.products[0].params.W=0;const bad=P.calculate(d);A.ok(bad.alternatives.tmc.errors.length);A.equal(bad.alternatives.tmc.products[0].tmc.laborReconciliation,undefined);
});
