'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),R=require('../reporting-core.js'),{createApp}=require('../server/app.cjs');
const empty=()=>({now:'2026-09-25T03:00:00Z',orders:[],contracts:[],payments:[],cash:[],jobs:[],lots:[],materials:[],movements:[]});
const filter={kind:'overview',from:'2026-09-01',to:'2026-09-30'},all={revenue:true,debt:true,production:true,inventory:true,inventoryValue:true,finance:true},table=(d,id)=>d.tables.find(t=>t.id===id).rows;
test('reports separate delivered revenue, VAT, collections and opening receivables, reconcile products',()=>{const d=empty();d.orders=[{id:'o',code:'DH',customerKey:'c',customer:'Customer',meta:{deliveredAt:'2026-09-25',deliveryDate:'2026-09-25'},offer:{totals:{beforeTax:105,vat:10.5,grand:115.5},products:[{name:'Product',qty:1,unit:'bộ',total:100}]}},{id:'not-delivered',customerKey:'c',meta:{},offer:{totals:{grand:999}}}];d.contracts=[{id:'c1',code:'HD',status:'active',value:200,customerId:'c',startDate:'2026-08-01',dueDate:'2026-09-20'}];d.payments=[{contractId:'c1',date:'2026-08-15',amount:20},{contractId:'c1',date:'2026-09-02',amount:30},{contractId:'c1',date:'2026-10-02',amount:40},{contractId:'c1',date:'2026-09-03',amount:70,voidedAt:'now'}];const out=R.build(d,filter,all);A.equal(table(out,'revenue-month')[0].revenue,105);A.equal(table(out,'revenue-product').reduce((s,r)=>s+r.revenue,0),105);A.equal(table(out,'receivable')[0].remaining,150);A.equal(out.cards.find(c=>c.label.startsWith('Tiền thực thu')).value,30);A.ok(!table(out,'revenue-month')[0].source);});
test('inventory reconstructs beginning/end and offcuts without counting scrap twice, preserves fractional kg',()=>{const d=empty();d.materials=[{id:'m',name:'Steel',minimum:2,unit:'kg'}];d.lots=[{id:'l',materialId:'m',unit:'kg',warehouse:'A'},{id:'r',materialId:'m',unit:'kg',warehouse:'A'}];d.movements=[{kind:'receipt',lotId:'l',materialId:'m',warehouse:'A',at:'2026-08-31T16:59:59Z',quantity:10,value:100},{kind:'issue',lotId:'l',materialId:'m',warehouse:'A',at:'2026-08-31T17:00:00Z',quantity:-4,value:-40},{kind:'return',lotId:'r',materialId:'m',warehouse:'A',at:'2026-09-01',quantity:0.001,value:0.01},{kind:'scrap',lotId:'l',materialId:'m',warehouse:'A',at:'2026-09-01',quantity:0,weight:1,value:0},{kind:'receipt',lotId:'l',materialId:'m',warehouse:'A',at:'2026-10-01',quantity:100,value:1000}];const out=R.build(d,filter,all),r=table(out,'inventory-balance')[0];A.equal(r.opening,10);A.equal(r.incoming,.001);A.equal(r.outgoing,4);A.equal(r.closing,6.001);A.equal(r.closingValue,60.01);A.equal(table(out,'inventory-source').length,3);const limited=R.build(d,{...filter,kind:'inventory'},{inventory:true});A.ok(!JSON.stringify(limited).includes('closingValue'));A.ok(!JSON.stringify(limited).includes('60.01'));});
test('production never combines incompatible units or fabricates efficiency when hour norms missing',()=>{const d=empty();d.jobs=['bộ','kg'].map((unit,i)=>({id:'j'+i,code:'LSX'+i,created:'2026-08-01',updated:'2026-09-02',state:'completed',quantity:10,packet:{product:{name:'P',unit},operations:[{id:'op',unit:i?'kg':'hour',workQuantity:8}]},progress:{workshop:'A',operations:[{id:'op',status:'done',hours:4,finishedAt:'2026-09-02'}],qc:{at:'2026-09-03',passed:9,rejected:1}}}));const out=R.build(d,filter,all);A.equal(table(out,'production-output').length,2);A.equal(table(out,'production-quality').length,2);A.equal(table(out,'production-quality')[0].ratio,90);A.equal(table(out,'production-workshops')[0].efficiency,null);A.equal(table(out,'production-workshops')[0].actual,8);});
async function fixture(t){const app=createApp({databasePath:':memory:'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));let admin;const call=async(path,method='GET',body,s=admin)=>{const r=await fetch('http://127.0.0.1:'+app.server.address().port+'/api/'+path,{method,headers:{'Content-Type':'application/json',Cookie:s?.cookie||'','X-CSRF-Token':s?.csrf||''},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};};admin=await call('setup','POST',{username:'admin',name:'Admin',password:'Reports-test-2026!'},null);return {app,call,admin};}
test('report API requires source permissions, independently checks exports and isolates financial data',async t=>{const {app,call}=await fixture(t);const user=async(name,access)=>{const u=(await call('users','POST',{username:name,name,role:'sales',password:'Reports-test-2026!'})).data;app.sql.prepare('UPDATE users SET action_access=? WHERE id=?').run(JSON.stringify(access),u.id);return call('login','POST',{username:name,password:'Reports-test-2026!'});};const u=await user('store',{reports:['view','export'],inventory:['view']}),blocked=await user('blocked',{reports:['view','export']}),exporter=await user('exporter',{reports:['view','export'],inventory:['view','export']});
 A.equal((await call('reports?kind=overview','GET',undefined,blocked)).status,403);let r=await call('reports?kind=inventory','GET',undefined,u);A.equal(r.status,200,JSON.stringify(r.data));A.equal(r.data.canExport,false);A.deepEqual(r.data.available,['overview','inventory']);A.equal((await call('reports?kind=revenue','GET',undefined,u)).status,403);A.equal((await call('reports?kind=inventory&export=1','GET',undefined,u)).status,403);A.equal((await call('reports?kind=inventory&export=1','GET',undefined,exporter)).status,200);
 app.sql.prepare('UPDATE users SET section_access=? WHERE username=?').run(JSON.stringify(Object.fromEntries(require('../section-access.js').keys.map(k=>[k,'none']))),'store');
 app.sql.prepare('INSERT INTO ops_records VALUES(?,?,?,?)').run('material','steel',1,JSON.stringify({id:'steel',name:'Steel',unit:'kg',minimum:2}));
 app.sql.prepare('INSERT INTO stock_movements VALUES(?,?,?)').run('mv','2026-09-25',JSON.stringify({id:'mv',at:'2026-09-25',kind:'receipt',materialId:'steel',warehouse:'A',quantity:1,value:12345}));
 const scoped=await call('reports?kind=inventory&from=2026-09-01&to=2026-09-30','GET',undefined,u);A.equal(scoped.status,200);A.equal(table(scoped.data,'inventory-balance')[0].incoming,1);A.equal(table(scoped.data,'inventory-balance')[0].closing,1);A.ok(!JSON.stringify(scoped.data).includes('12345'));A.ok(!JSON.stringify(scoped.data).includes('__accessRef'));
 const debtReader=await user('debtreader',{reports:['view','export'],orders:['view','export'],contracts:['view'],payments:['view']});A.equal((await call('reports?kind=revenue&export=1','GET',undefined,debtReader)).status,403);const debtExporter=await user('debtexporter',{reports:['view','export'],orders:['view','export'],contracts:['view','export'],payments:['view']});A.equal((await call('reports?kind=revenue&export=1','GET',undefined,debtExporter)).status,200);
 A.equal((await call('reports?from=2026-02-30')).status,400);A.equal((await call('reports?from=2026-10-01&to=2026-09-01')).status,400);A.equal((await call('reports','POST',{})).status,405);A.ok(app.sql.prepare("SELECT * FROM audit WHERE action='report-export'").get());
});
module.exports={fixture};
