'use strict';
const {chromium,expect}=require('@playwright/test'),{createApp}=require('../server/app.cjs'),fs=require('node:fs');
(async()=>{const app=createApp({databasePath:':memory:'});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:'+app.server.address().port);await p.waitForFunction(()=>Team.available);
 const order=await p.evaluate(async()=>{teamSession(await teamApi('setup','POST',{username:'admin',name:'Admin',password:'Reports-browser-2026!'}));const d=TPPrice.demoSeed();d.quote.customer='Report Customer';const q=await teamApi('quotes','POST',{document:d});await teamApi('quotes/'+q.id+'/submit','POST',{expectedVersion:1});await teamApi('quotes/'+q.id+'/approve','POST',{expectedVersion:2});const o=await teamApi('quotes/'+q.id+'/order','POST',{expectedVersion:3,code:'DH-REPORT'});await teamApi('users','POST',{username:'warehouse',name:'Warehouse',role:'sales',password:'Reports-browser-2026!'});return o;});
 app.sql.prepare('INSERT OR REPLACE INTO business_records VALUES(?,?,?,?)').run('order',order.id,1,JSON.stringify({id:order.id,deliveredAt:'2026-09-25',deliveryDate:'2026-09-25'}));
 app.sql.prepare('INSERT INTO ops_records VALUES(?,?,?,?)').run('material','m',1,JSON.stringify({id:'m',name:'Steel',unit:'kg',minimum:2}));app.sql.prepare('INSERT INTO ops_records VALUES(?,?,?,?)').run('lot','l',1,JSON.stringify({id:'l',materialId:'m',unit:'kg',warehouse:'Main'}));app.sql.prepare('INSERT INTO stock_movements VALUES(?,?,?)').run('mv','2026-09-25',JSON.stringify({id:'mv',at:'2026-09-25',kind:'receipt',materialId:'m',lotId:'l',warehouse:'Main',quantity:1.25,value:98765,reference:'PN-UI'}));
 app.sql.prepare('UPDATE users SET action_access=? WHERE username=?').run(JSON.stringify({reports:['view'],inventory:['view']}),'warehouse');
 await p.locator('#sidebar [data-erp=reports]').click();await p.waitForFunction(()=>Reports.data);await p.locator('[name=report-anchor]').fill('2026-09');await p.locator('#report-filter button[type=submit]').click();await p.waitForFunction(()=>Reports.data?.from==='2026-09-01');await expect(p.locator('#report-revenue-source')).toContainText('DH-REPORT');
 for(const [period,from,to]of [['quarter','2026-07-01','2026-09-30'],['year','2026-01-01','2026-12-31'],['month','2026-09-01','2026-09-30']]){await p.locator('[name=report-period]').selectOption(period);await expect(p.locator('[name=report-from]')).toHaveValue(from);await expect(p.locator('[name=report-to]')).toHaveValue(to);await p.locator('#report-filter button[type=submit]').click();await p.waitForFunction(f=>Reports.data?.from===f,from);}
 for(const kind of ['production','revenue','inventory','overview']){await p.locator('[data-report-kind='+kind+']').click();await p.waitForFunction(k=>Reports.data?.kind===k,kind);const download=p.waitForEvent('download');await p.locator('[data-report-export]').click();const file=await download;expect(file.suggestedFilename()).toContain(kind);await file.saveAs('artifacts/reports-'+kind+'.xlsx');const xml=fs.readFileSync('artifacts/reports-'+kind+'.xlsx','utf8');expect(xml).toContain('2026-09-01');if(kind==='inventory'||kind==='overview')expect(xml).toContain('<v>98765</v>');await p.setViewportSize({width:390,height:844});expect(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),'mobile '+kind).toBe(false);await p.screenshot({path:'artifacts/reports-'+kind+'-mobile.png',fullPage:true});await p.setViewportSize({width:1440,height:1000});}
 await p.screenshot({path:'artifacts/reports-overview-desktop.png',fullPage:true});
 // An unsubmitted date edit must not silently change the exported period.
 await p.locator('[name=report-from]').fill('2026-08-01');const dl=p.waitForEvent('download');await p.locator('[data-report-export]').click();expect((await dl).suggestedFilename()).toContain('2026-09-01');
 await p.evaluate(async()=>{await teamApi('logout','POST',{});teamSession({user:null,permissions:null,csrf:''});});expect(await p.evaluate(()=>Reports.data)).toBeNull();await expect(p.locator('#sidebar [data-erp=reports]')).toBeHidden();await p.evaluate(async()=>{teamSession(await teamApi('login','POST',{username:'warehouse',password:'Reports-browser-2026!'}));await reportsOpen('inventory');});await expect(p.locator('[data-report-export]')).toHaveCount(0);await expect(p.locator('[data-report-kind=revenue]')).toHaveCount(0);await expect(p.locator('#content')).not.toContainText('98.765');expect(await p.evaluate(async()=>{try{await teamApi('reports?kind=inventory&export=1');return false;}catch{return true;}})).toBe(true);await p.reload();await p.waitForFunction(()=>Team.user);await p.locator('#sidebar [data-erp=reports]').click();await p.waitForFunction(()=>Reports.data);expect(await p.evaluate(()=>Reports.data.available)).toEqual(['overview','inventory']);expect(errors).toEqual([]);console.log('PASS reports browser: periods, 4 tabs, numeric Excel, applied filters, desktop/mobile, source data, limited role, logout/reload');
 }finally{await browser.close();await new Promise(r=>app.server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});

