'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),P=require('../pricing-core.js'),{randomUUID}=require('node:crypto'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
test('end-to-end quote, purchase, stock, production/QC, delivery, collection, reports and database restore',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tp-reports-flow-')),databasePath=path.join(dir,'source.sqlite'),app=createApp({databasePath});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));let restored,admin;
 t.after(async()=>{await new Promise(r=>app.server.close(r));if(restored){await new Promise(r=>restored.server.close(r));}for(const n of fs.readdirSync(dir))fs.unlinkSync(path.join(dir,n));fs.rmdirSync(dir);});
 const call=async(route,method='GET',body,server=app)=>{const r=await fetch('http://127.0.0.1:'+server.server.address().port+'/api/'+route,{method,headers:{'Content-Type':'application/json',Cookie:admin?.cookie||'','X-CSRF-Token':admin?.csrf||''},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};};
 const ok=async(route,method='GET',body)=>{const r=await call(route,method,body);A.ok(r.status<300,route+': '+JSON.stringify(r));return r.data;},ops=(route,b)=>ok('ops/'+route,'POST',{requestId:randomUUID(),...b});
 admin=await call('setup','POST',{username:'admin',name:'Admin',password:'Reports-flow-2026!'});const today=require('../completion-core.js').todayVN(),customerId='flow-customer';app.sql.prepare('INSERT INTO intake_customers VALUES(?,?,?)').run(customerId,1,JSON.stringify({id:customerId,name:'Flow Customer'}));
 const d=P.demoSeed();d.quote.products=[d.quote.products[0]];d.quote.products[0].qty=1;d.quote.remnantMode='all';d.quote.remnantSelections={};d.quote.customerInfo={id:customerId,name:'Flow Customer'};d.quote.customer='Flow Customer';
 const q=await ok('quotes','POST',{document:d});await ok('quotes/'+q.id+'/submit','POST',{expectedVersion:1});await ok('quotes/'+q.id+'/approve','POST',{expectedVersion:2});const order=await ok('quotes/'+q.id+'/order','POST',{expectedVersion:3,code:'DH-FLOW'});await ok('orders/'+order.id+'/confirm','POST',{quoteVersion:3});let j=await ok('production','POST',{orderId:order.id,productId:d.quote.products[0].id,quantity:1,code:'LSX-FLOW'});
 const update=async b=>j=await ok('production/'+j.id,'PUT',{expectedVersion:j.version,...b});const ds=(await ok('ops/job/'+j.id)).requirements;
 for(const x of ds)await ops('master',{kind:'material',expectedVersion:0,document:{id:x.materialId,code:x.materialId,name:x.name||x.materialId,unit:x.unit,form:x.unit==='tấm'?'sheet':'bulk'}});
 const supplier=await ops('master',{kind:'supplier',expectedVersion:0,document:{code:'NCC-FLOW',name:'Supplier',prices:ds.map(x=>({materialId:x.materialId,unitCost:20,leadDays:1}))}});let purchase=await ops('purchase',{jobId:j.id,code:'PO-FLOW',supplierId:supplier.id});
 for(const state of ['approved','ordered','shipping','received','stocked'])purchase=await ops('transition',{id:purchase.id,expectedVersion:purchase.version,state,note:'Checked',receipts:ds.map(x=>({materialId:x.materialId,quantity:x.quantity,warehouse:'Main',unitWeight:10,length:x.length,width:x.width,thickness:x.thickness||1}))});
 const state=await ok('ops/state');for(const l of state.lots)await ops('reserve',{jobId:j.id,lotId:l.id,quantity:l.quantity});await update({action:'prepare',workshop:'Xưởng A',deadline:today,drawingReady:true,materialsReady:true,note:'Checked'});
 j=await require('./production-flow-fixture.cjs').approveRoute((r,m,b)=>call(r,m,b),admin,j.id);for(const o of j.packet.operations){await update({action:'operation',operationId:o.id,assignee:admin.data.user.id,machine:'Manual',status:'running',output:o.quantity,hours:2,note:'Done'});j=await require('./production-flow-fixture.cjs').settleStage((r,m,b)=>call(r,m,b),admin,j.id);}
 await update({action:'qc',passed:1,rejected:0,note:'Passed'});await update({action:'complete'});
 let o=await ok('business/orders/'+order.id);A.equal(o.status,'completed');await ok('business/orders/'+o.id+'/deliver','POST',{expectedVersion:o.version,date:today,receiver:'Customer',note:'Delivered'});
 const c=await ok('business/contracts','POST',{expectedVersion:0,document:{code:'HD-FLOW',customerId,orderId:o.id,value:o.offer.totals.grand,status:'active',signDate:today,startDate:today,dueDate:today}});
 const payment={contractId:c.id,expectedVersion:c.version,requestId:randomUUID(),amount:100,date:today,reference:'PT-FLOW'};await ok('business/payments','POST',payment);await ok('business/payments','POST',payment);
 const finance=await ok('enterprise/finance');A.equal(finance.costs.length,1);const cost=finance.costs[0],cash={requestId:randomUUID(),direction:'out',date:today,reference:'PC-FLOW',costId:cost.id,amount:cost.amount,note:'Paid supplier'};await ok('enterprise/finance/cash','POST',cash);await ok('enterprise/finance/cash','POST',cash);
 const route='reports?kind=overview&from='+today+'&to='+today,report=await ok(route),rows=id=>report.tables.find(t=>t.id===id).rows;
 A.equal(rows('revenue-source').length,1);A.equal(rows('revenue-source')[0].grand,o.offer.totals.grand);A.equal(rows('receivable')[0].remaining,Math.round((c.value-100)*100)/100);A.equal(report.cards.find(c=>c.label.startsWith('Tiền thực thu')).value,100);A.equal(report.cards.find(c=>c.label.startsWith('Tiền thực chi')).value,cost.amount);A.equal(rows('production-output')[0].passed,1);A.ok(rows('inventory-balance').every(r=>r.closing===0&&r.closingValue===0));A.equal(rows('revenue-product').reduce((s,r)=>s+r.revenue,0),o.offer.totals.beforeTax);
 // Independent SQLite copy is opened by a new application; report results must survive restoration.
 const copy=path.join(dir,'restored.sqlite');app.sql.prepare('VACUUM INTO ?').run(copy);restored=createApp({databasePath:copy});await new Promise(r=>restored.server.listen(0,'127.0.0.1',r));const replay=await call(route,'GET',undefined,restored);A.equal(replay.status,200);A.deepEqual(replay.data.tables,report.tables);A.deepEqual(replay.data.cards,report.cards);A.equal((await call('backup','GET',undefined,restored)).data.stockMovements.length,(await ok('backup')).stockMovements.length);
});
