const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),SA=require('../section-access'),AA=require('../server/action-access.cjs');
const fail=(status,message)=>{throw Error(status+': '+message);};
test('intake uses customer declaration grants without full quotation creation rights',()=>{const user={role:'sales',section_access:JSON.stringify({...Object.fromEntries(Object.keys(SA.labels).map(k=>[k,'none'])),customer:'use',commercial:'use'}),action_access:JSON.stringify({quotes:['view'],customers:['view','create','edit']})};for(const [route,method]of [['/api/quote-intakes','POST'],['/api/quote-intakes/abc','PUT']])A.doesNotThrow(()=>AA.guardRoute(route,method,user,fail));A.throws(()=>AA.guardRoute('/api/quotes','POST',user,fail),/Thêm/);A.throws(()=>AA.guardRoute('/api/quotes/abc','PUT',user,fail),/Sửa/);for(const actions of [['view'],['view','edit']]){const restricted={...user,action_access:JSON.stringify({quotes:['view'],customers:actions})};A.throws(()=>AA.guardRoute('/api/quote-intakes','POST',restricted,fail),/Thêm/);}const reader={...user,section_access:JSON.stringify({customer:'view'})};A.throws(()=>AA.guardRoute('/api/quote-intakes','POST',reader,fail),/đầu vào/);});
test('protected coefficient roundtrip accepts only mask or exact server value, keeps current quote coefficients',()=>{const app=createApp(),u={id:'qa',role:'estimator',can_view_costs:1,can_factors:0,section_access:JSON.stringify({bom:'use',operations:'use',factors:'none'})},D=require('../server/data-access.cjs').createDataAccess({sql:app.sql,fail});const source={quote:{pricing:{overhead:5,profit:10}}},masked=D.protect(source,u);A.equal(masked.quote.pricing.overhead,0);for(const overhead of [0,5]){const incoming=structuredClone(masked);incoming.quote.pricing.overhead=overhead;const hydrated=D.hydrate(incoming,u);A.equal(hydrated.quote.pricing.overhead,5);D.retainCurrentHiddenCoefficients(hydrated,{quote:{pricing:{overhead:7,profit:12}}},u);A.equal(hydrated.quote.pricing.overhead,7);A.equal(hydrated.quote.pricing.profit,12);}const bad=structuredClone(masked);bad.quote.pricing.overhead=999;A.throws(()=>D.hydrate(bad,u),/đang ẩn/);A.throws(()=>D.hydrate(masked,{...u,id:'other'}),/không thuộc/);app.sql.close();});

test('quote transport restores masked catalogue defaults for old tabs without granting catalogue or quote writes',()=>{
 const app=createApp(),u={id:'qa',role:'estimator',can_view_costs:1,can_factors:0,section_access:JSON.stringify({bom:'use',operations:'use',factors:'none'})},D=require('../server/data-access.cjs').createDataAccess({sql:app.sql,fail});
 const source={document:{rates:[{id:'cut',factors:[{id:'width',percent:7}]}],pricingDefaults:{tmcLoss:2.75,salesFactors:[{id:'a',percent:7}]},quote:{pricing:{tmcLoss:2.75},products:[{id:'a',qty:1}]}}},d=D.protect(source,u);
 d.document.rates[0].factors=[{id:'client-default',percent:999}];d.document.pricingDefaults.tmcLoss=1.5;d.document.pricingDefaults.salesFactors=[{id:'bad',percent:999}];delete d.document.pricingDefaults.__accessFields;d.document.quote.products[0].qty=3;
 A.throws(()=>D.hydrate(d,u),/factors|tmcLoss/);
 const saved=D.hydrate(d,u,{quoteTransport:true});A.deepEqual(saved.document.pricingDefaults,source.document.pricingDefaults);A.deepEqual(saved.document.rates,source.document.rates);A.equal(saved.document.quote.products[0].qty,3);
 d.document.quote.pricing.tmcLoss=99;A.throws(()=>D.hydrate(d,u,{quoteTransport:true}),/tmcLoss/);A.throws(()=>D.hydrate(d,{...u,id:'other'},{quoteTransport:true}),/không thuộc/);app.sql.close();
});
