const {chromium,expect}=require('@playwright/test'),{createApp}=require('../server/app.cjs'),path=require('node:path');
(async()=>{const app=createApp({databasePath:':memory:',staticRoot:path.resolve('dist')});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'msedge',headless:true});try{
const p=await browser.newPage({viewport:{width:1366,height:768}}),errors=[];p.on('pageerror',e=>errors.push(e.message));const url='http://127.0.0.1:'+app.server.address().port;await p.goto(url);await p.waitForFunction(()=>Team.available);
await p.evaluate(async()=>teamSession(await teamApi('setup','POST',{username:'admin',name:'Admin',password:'Settings-browser-2026!'})));
await p.locator('[data-settings-open]').click();await expect(p.locator('#display-settings')).toBeVisible();
await p.locator('[name=locale]').selectOption('en-US');await p.locator('[name=date]').selectOption('yyyy-MM-dd');await p.locator('[name=theme]').selectOption('dark');await p.locator('#display-settings [type=submit]').click();await expect(p.locator('html')).toHaveAttribute('data-theme','dark');expect(await p.evaluate(()=>money(12345))).toBe('12,345');expect(await p.evaluate(()=>TPDisplay.date('2026-09-25'))).toBe('2026-09-25');
for(const width of [1366,1440,1920]){await p.setViewportSize({width,height:width===1366?768:1080});expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await p.screenshot({path:'artifacts/settings-dark-'+width+'.png',fullPage:true});}
await p.reload();await p.waitForFunction(()=>Team.user);await expect(p.locator('html')).toHaveAttribute('data-theme','dark');await p.locator('[data-settings-open]').click();await expect(p.locator('[name=locale]')).toHaveValue('en-US');
await p.evaluate(()=>{page='quote';render();});await p.screenshot({path:'artifacts/settings-quote-dark.png',fullPage:true});await p.evaluate(()=>{page='materials';render();});await p.screenshot({path:'artifacts/settings-materials-dark.png',fullPage:true});await p.locator('[data-settings-open]').click();
await p.locator('[data-setting-link=customer-policy]').click();await expect(p.locator('#dialog')).toBeVisible();await expect(p.locator('[name=scoring-enabled]')).toBeVisible();await p.screenshot({path:'artifacts/settings-policy-dark.png',fullPage:true});await p.locator('[name=care-due]').fill('10');await p.locator('[name=care-overdue]').fill('20');await p.locator('[name=care-critical]').fill('35');await p.locator('#dialog-form [type=submit]').click();await expect(p.locator('#dialog[open]')).toHaveCount(0);expect(await p.evaluate(async()=>(await teamApi('intake/policy')).careLevels)).toEqual({due:10,overdue:20,critical:35});
await p.locator('[data-setting-link=customer-fields]').click();await expect(p.locator('#dialog')).toBeVisible();await p.evaluate(()=>closeDialog());
await p.locator('[data-setting-link=teams]').click();await expect(p.locator('#dialog')).toBeVisible();await p.evaluate(()=>closeDialog());
await p.locator('[data-setting-link=payroll]').click();await expect(p.locator('#content')).toContainText('Nguyên tắc tính lương');await p.screenshot({path:'artifacts/settings-payroll-dark.png',fullPage:true});
await p.locator('[data-settings-open]').click();await p.locator('[name=theme]').selectOption('system');await p.locator('#display-settings [type=submit]').click();await p.emulateMedia({colorScheme:'light'});await expect(p.locator('html')).toHaveAttribute('data-theme','light');await p.emulateMedia({colorScheme:'dark'});await expect(p.locator('html')).toHaveAttribute('data-theme','dark');
await p.locator('[data-display-reset]').click();await expect(p.locator('html')).toHaveAttribute('data-theme','light');await expect(p.locator('[name=locale]')).toHaveValue('vi-VN');await p.screenshot({path:'artifacts/settings-light.png',fullPage:true});
await p.evaluate(()=>teamSession({user:null,permissions:{},csrf:null}));await p.locator('[data-settings-open]').click();await expect(p.locator('[data-setting-link=customer-policy]')).toBeDisabled();expect(errors).toEqual([]);console.log('PASS settings, configuration links, saved display formats, light/dark/system, laptop/PC widths');
}finally{await browser.close();await new Promise(r=>app.server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
