'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),P=require('../pricing-core.js'),D=require('../definition-core.js');
async function run(t){const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port;let session;const call=async(route,method='GET',body)=>{const r=await fetch(base+'/api/'+route,{method,headers:{'Content-Type':'application/json',...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};const s=await call('setup','POST',{username:'admin',name:'Kiểm thử quy ước',password:'Only-for-definition-tests-42!'});session={cookie:s.cookie,csrf:s.data.csrf};return {call};}


test('server saves parent/detail links and retains referenced quote snapshots after regrouping the catalogue',async t=>{
 const {call}=await run(t),db=P.demoSeed(),d=D.saveShape(db,{id:'GROUP-SERVER',name:'Thanh thử nhóm',productGroup:'Thang máng cáp',base:'bar',fields:[{key:'L',mode:'input',unit:'mm',sample:2000},{key:'KM',mode:'fixed',unit:'kg/m',sample:10},{key:'AM',mode:'fixed',unit:'m²/m',sample:.5}],length:'L',width:'0',mass:'KM',surface:'AM'}),m=D.applyShape({id:'GROUP-MAT',name:'Thanh nhóm thử',density:7850,price:10000,unit:'kg',stockL:6000},d,{KM:10,AM:.5});db.materials.push(m);db.quote.products[0].children.push(D.assign(D.draft('Thanh',1),m,db.rules));
 const created=await call('quotes','POST',{document:db});A.equal(created.status,201,JSON.stringify(created));const before=(await call('quotes/'+created.data.id)).data.document.quote;
 const master=(await call('catalog')).data;D.saveShape(db,{...d,productGroup:'Cơ khí'});const catalog={...master.catalog,shapeDefinitions:db.shapeDefinitions};A.equal((await call('catalog','PUT',{expectedVersion:master.version,catalog})).status,200);const next=(await call('catalog')).data;A.equal(next.catalog.shapeDefinitions[0].productGroup,'Cơ khí');A.deepEqual((await call('quotes/'+created.data.id)).data.document.quote,before);
 const bad={...next.catalog,conventions:{...next.catalog.conventions,productGroups:[{name:'Thang máng cáp',hidden:true}]}};const denied=await call('catalog','PUT',{expectedVersion:next.version,catalog:bad});A.equal(denied.status,400);A.match(denied.data.error,/Không xóa/);
 const invalid={...next.catalog,shapeDefinitions:[{...d,productGroup:{name:'Bad'}}]};A.equal((await call('catalog','PUT',{expectedVersion:next.version,catalog:invalid})).status,400);
});
