'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),C=require('../core.js'),P=require('../pricing-core.js'),D=require('../definition-core.js');
const sheet=()=>({id:'TRIANGLE-QA',name:'Tam giác kiểm thử',base:'sheet',blankShape:'sheet',fields:[{key:'T',mode:'fixed',unit:'mm',sample:2},{key:'L',mode:'input',unit:'mm',sample:1000},{key:'W',mode:'input',unit:'mm',sample:200}],length:'L',width:'W',mass:'T / 1000 * RHO',surface:'1',blankMass:'PHOI_D * PHOI_R / 2000000 * KL_DV',blankSurface:'PHOI_D * PHOI_R / 2000000'});
function fixture(){const db=P.demoSeed(),d=D.saveShape(db,sheet()),m=D.applyShape({id:'TRIANGLE-MAT',name:'Phôi thử',substance:'Thép',density:7850,unit:'kg',price:20000,stockL:1000,stockW:1000},d,{T:2}),n=D.assign(D.draft('Ba phôi',3),m,db.rules);db.materials.push(m);db.quote.products=[{id:'SP-QA',name:'Sản phẩm thử',kind:'product',qty:1,children:[n],ops:[]}];db.quote.kerf=0;return {db,d,m,n};}
const near=(actual,expected)=>A.ok(Math.abs(actual-expected)<1e-9,`${actual} != ${expected}`);
test('shape formulas: per-piece triangle mass/area differ from the nesting rectangle and do not reduce purchased stock',()=>{const {db,d}=fixture(),g=D.testShape(d,{T:2,L:1000,W:200}),r=C.calculate(db);near(g.weight,1.57);near(g.blankArea,.1);near(r.rows[0].geometry.weight,4.71);near(r.rows[0].geometry.blankArea,.3);near(r.rows[0].geometry.measure,.6);near(r.rows[0].purchasedWeight,15.7);near(r.rows[0].purchasedArea,1);near(r.rows[0].purchaseCost,314000);A.equal(r.groups[0].layout.stocks.length,1);});
test('shape formulas: changing unfolding formulas feeds the per-piece aliases and quantities multiply once',()=>{const d={...sheet(),length:'L + 100',width:'W + 20'},g=D.testShape(d,{T:2,L:1000,W:200});near(g.weight,1.8997);near(g.blankArea,.121);const {db,n}=fixture();db.quote.products[0].qty=2;n.dims.L=500;near(C.calculate(db).rows[0].geometry.weight,4.71);});
test('shape formulas: expanded expressions match declared aliases, including physical mass override',()=>{const {d,n}=fixture(),full=D.expandedFormulas(d),vars={L:1000,W:200,T:2,RHO:7850};near(C.formula(full.blankMass,vars),1.57);near(C.formula(full.blankSurface,vars),.1);n.spec.massOverride={value:20,reason:'Dữ liệu thử theo đơn vị'};near(C.geometry(n,3).weight,6);near(C.materialMass(n.spec),20);});
test('shape formulas: independent expressions persist without rewriting an older quote or library material',()=>{const {db,n,m,d}=fixture();db.quote.status='approved';const before=C.copy(db.quote);D.saveShape(db,{...d,blankMass:'PHOI_D * PHOI_R / 1000000 * KL_DV',blankSurface:'PHOI_D * PHOI_R / 1000000'});A.deepEqual(db.quote,before);A.equal(n.spec.shapeDefinition.version,1);A.equal(m.shapeDefinition.version,1);near(C.calculate(db).rows[0].geometry.weight,4.71);near(C.calculate(JSON.parse(JSON.stringify(db))).rows[0].geometry.weight,4.71);});
test('shape formulas: wrong output units, unknown/circular variables, invalid values and incompatible blank shape are rejected',()=>{for(const patch of [{blankMass:'L'},{blankSurface:'KL_DV'},{blankMass:'MISSING'},{blankMass:'blankMass + 1'},{blankMass:'L / (W-W)'},{blankMass:'-PHOI_D / 1000 * KL_DV'},{blankSurface:'0'},{blankMass:0},{blankShape:'pipe'},{blankShape:'piece'},{blankShape:'unknown'}])A.throws(()=>D.saveShape({}, {...sheet(),...patch}));});
test('shape formulas: old definitions retain identical mass and area when optional per-piece formulas are absent',()=>{const d=sheet();delete d.blankMass;delete d.blankSurface;delete d.blankShape;const g=D.testShape(d,{T:2,L:1000,W:200});near(g.weight,3.14);near(g.blankArea,.2);A.equal(D.blankFormulas(d).blankMass,'PHOI_D * PHOI_R / 1000000 * KL_DV');});
