'use strict';
const {chromium,expect}=require('@playwright/test'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const url=process.env.BATCH_FIVE_URL||pathToFileURL(path.resolve('dist/index.html')).href,dir=path.resolve(process.env.BATCH_FIVE_ROOT||'artifacts/customer-review/batch-05-2026-09-14',url.startsWith('https:')?'live':'local');fs.mkdirSync(dir,{recursive:true});
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage({viewport:{width:1560,height:1080}}),checks=[],screens=[],errors=[];p.setDefaultTimeout(12000);p.on('pageerror',e=>errors.push(e.message));const pass=s=>{checks.push(s);console.log('PASS '+s);},shot=async s=>{const target=s.startsWith('04-')?p.locator('#content .paper'):s.startsWith('03-')||s.startsWith('06-')?p.locator('.pa-comparison'):p;await target.screenshot({path:path.join(dir,s+'.png')});screens.push(s+'.png');},submit=async()=>{await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#dialog')).not.toBeVisible();},f=name=>p.locator('#dialog [name='+name+']');
try{
 await p.goto(url);await p.evaluate(()=>{db=TPPrice.demoSeed();db.quote.remnantMode='all';db.quote.products.forEach(n=>n.qty=2);page='quote';tab='pricing';render();persist();});await expect(p.locator('[data-tax-panel]')).toContainText('Chưa đủ căn cứ');expect(await p.evaluate(()=>result.tax.methods.kg.net)).toBe(null);await shot('01-chua-xac-nhan-khong-so-sanh');pass('Unknown input tax is shown as unknown, not silently comparable');
 await p.locator('[data-tax=edit]').click();for(let i=0;i<2;i++){await f('competitor-value-'+i).fill('1100000');await f('tax-competitor-'+i).selectOption('included');await f('rate-competitor-'+i).fill('10');await f('tax-kg-'+i).selectOption('excluded');}await f('outputRate').fill('8');await f('costConfirmed').check();await f('outputConfirmed').check();await f('taxReason').fill('QA: 1.100.000 gồm 10% → 1.000.000 trước thuế; đầu ra thử 8%, không phải chỉ dẫn thuế thực tế');await shot('02-khai-gia-gop-va-hai-thue-suat');await submit();await p.locator('[data-pa=choose][data-method=competitor]').click();expect(await p.evaluate(()=>result.total.beforeTax)).toBe(4000000);expect(await p.evaluate(()=>result.total.grand)).toBe(4320000);expect(await p.evaluate(()=>db.quote.products[0].competitorPrice)).toBe(1100000);expect(await p.evaluate(()=>result.tax.releaseErrors)).toEqual([]);await shot('03-so-sanh-cung-mat-bang');pass('Gross competitor price /1.10 then output tax 8% gives 4.32M, original 1.1M preserved');
 const before=await p.evaluate(()=>({total:result.total,ref:result.tax.reference,metrics:result.tax.methods}));await p.locator('[data-pa=toggle-costs]').click();expect(await p.evaluate(()=>({total:result.total,ref:result.tax.reference,metrics:result.tax.methods}))).toEqual(before);await p.reload();await p.locator('[data-tab=pricing]').click();expect(await p.evaluate(()=>result.total.grand)).toBe(4320000);expect(await p.evaluate(()=>db.quote.changeHistory.some(e=>e.after.taxReview))).toBe(true);pass('Hide/show does not affect totals; price and tax snapshot survive reload with history');
 const sheets=await p.evaluate(()=>exportSheets(true));const analysis=sheets.find(s=>s.name==='Mat bang gia thue');expect(analysis.rows.find(r=>r[0]==='Giá trước thuế')[4]).toBe(4000000);expect(await p.evaluate(()=>exportSheets(false).some(s=>s.name==='Mat bang gia thue'))).toBe(false);pass('Internal comparison export matches calculation; customer export excludes reference costs and tax source');
 await p.evaluate(()=>{db.quote.documentMode='official';db.quote.issuer={name:'QA TRƯỜNG PHÁT'};tab='preview';render();});await expect(p.locator('#content .paper')).toHaveCount(0);await p.locator('[data-action=approve]').click();await submit();await expect(p.locator('#content .paper')).toContainText('Bản chào đã duyệt');await expect(p.locator('#content .paper')).toContainText('4.320.000');await shot('04-ban-chao-chinh-thuc-khong-cong-thue-trung');const dl=p.waitForEvent('download');await p.locator('[data-work=export-customer-xlsx]').click();await(await dl).saveAs(path.join(dir,'QA-CHAO-GIA.xlsx'));pass('Official paper requires approval; approved paper and downloaded customer XLSX contain normalized total');
 await p.evaluate(()=>{mutation(()=>db.quote.products[0].competitorPrice=2200000);tab='pricing';render();});expect(await p.evaluate(()=>result.tax.methods.competitor.comparable)).toBe(false);expect(await p.evaluate(()=>result.errors.some(e=>e.includes('thuế')))).toBe(true);await shot('05-doi-gia-phai-xac-nhan-lai');await p.locator('[data-tab=preview]').click();await expect(p.locator('#content .paper')).toHaveCount(0);await p.locator('[data-action=approve]').click();await expect(p.locator('#dialog')).not.toBeVisible();pass('Changed price invalidates its tax declaration and blocks official approval/output');
 await p.evaluate(()=>{db.quote.documentMode='working';db.quote.status='draft';tab='pricing';render();});await p.locator('[data-tax=edit]').click();for(let i=0;i<2;i++){await f('competitor-value-'+i).fill('0');await f('tax-competitor-'+i).selectOption('excluded');}await f('costConfirmed').check();await f('outputConfirmed').check();await f('taxReason').fill('QA zero denominator case');await submit();expect(await p.evaluate(()=>result.tax.methods.detail.deltaCompetitorPercent)).toBe(null);expect(await p.evaluate(()=>result.tax.methods.tmc.net)).toBe(null);await shot('06-mau-so-khong-tmc-chua-chot');pass('Zero comparison denominator is N/A; unresolved TMC does not claim a verified comparable price');
 await p.setViewportSize({width:390,height:844});expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await p.locator('[data-tax=edit]').click();await shot('07-khai-thue-man-hinh-hep');await p.keyboard.press('Escape');expect(errors).toEqual([]);pass('Narrow screen usable; no browser runtime errors');
 fs.writeFileSync(path.join(dir,'results.json'),JSON.stringify({passed:true,url,at:new Date().toISOString(),checks,screens,errors},null,2));
}catch(e){console.error(e);await shot('FAILURE');fs.writeFileSync(path.join(dir,'results.json'),JSON.stringify({passed:false,url,checks,screens,errors,error:e.message},null,2));process.exitCode=1;}finally{await b.close();}})();
