'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),P=require('../pricing-core.js'),T=require('../tax-core.js');
test('official server recomputes tax, rejects unknown/stale declarations and protects approved version',async t=>{
 const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port;let cookie,csrf;
 const call=async(path,method='GET',body)=>{const r=await fetch(base+'/api/'+path,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie,'X-CSRF-Token':csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(r.headers.get('set-cookie'))cookie=r.headers.get('set-cookie').split(';')[0];if(data.csrf)csrf=data.csrf;return {status:r.status,data};};
 await call('setup','POST',{username:'admin',name:'QA Admin',password:'Tax-check-only-42!'});const d=P.demoSeed(),q=d.quote;q.remnantMode='all';q.documentMode='official';q.issuer={name:'QA issuer'};require('./offer-fixture.cjs')(q);q.pricing.selected='competitor';q.vat=8;q.products.forEach(n=>n.competitorPrice=1100000);
 const saved=await call('quotes','POST',{document:d});A.equal(saved.status,201);A.equal((await call('quotes/'+saved.data.id+'/submit','POST',{expectedVersion:1})).status,422);
 T.review(q,{reason:'QA synthetic source',costConfirmed:true,outputConfirmed:true,inputs:Object.fromEntries(q.products.map(n=>[n.id,{kg:{status:'unknown'},competitor:{status:'included',rate:10}}]))});
 const updated=await call('quotes/'+saved.data.id,'PUT',{document:d,expectedVersion:1});A.equal(updated.status,200);const sub=await call('quotes/'+saved.data.id+'/submit','POST',{expectedVersion:updated.data.version});A.equal(sub.status,200,JSON.stringify(sub));const ap=await call('quotes/'+saved.data.id+'/approve','POST',{expectedVersion:sub.data.version});A.equal(ap.status,200,JSON.stringify(ap));const read=await call('quotes/'+saved.data.id);A.equal(read.data.document.quote.approvedOffer.totals.beforeTax,20000000);A.equal(read.data.document.quote.approvedOffer.totals.grand,21600000);
 const reopened=await call('quotes/'+saved.data.id+'/reopen','POST',{expectedVersion:ap.data.version,reason:'QA new input'});A.equal(reopened.status,200);q.products[0].competitorPrice=2200000;const changed=await call('quotes/'+saved.data.id,'PUT',{document:d,expectedVersion:reopened.data.version});A.equal(changed.status,200);A.equal((await call('quotes/'+saved.data.id+'/submit','POST',{expectedVersion:changed.data.version})).status,422);const old=await call('quotes/'+saved.data.id+'/revision/'+ap.data.version);A.equal(old.data.document.quote.approvedOffer.totals.grand,21600000);
});
