'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),P=require('../pricing-core.js'),T=require('../tax-core.js');
function seed(){const d=P.demoSeed();d.quote.remnantMode='all';return d;}
function confirm(q,options={}){return T.review(q,{reason:'QA source only, not customer confirmation',costConfirmed:true,outputConfirmed:true,inputs:Object.fromEntries(q.products.map(n=>[n.id,{kg:{status:'excluded'},competitor:{status:'excluded'}}])),...options});}
test('unknown tax preserves draft arithmetic but cannot compare or issue official',()=>{const d=seed(),before=P.calculate(d);A.equal(before.tax.methods.kg.net,null);A.equal(before.tax.outputKnown,false);A.equal(before.tax.costKnown,false);A.equal(before.errors.length,0);d.quote.documentMode='official';const after=P.calculate(d);A.equal(after.total.grand,before.total.grand);A.match(after.errors.join(' '),/thuế/);});
test('all-in gross competitor normalizes per input, not by output VAT; original retained',()=>{const d=seed(),q=d.quote;q.vat=8;q.products.forEach(n=>{n.competitorPrice=110000;n.qty=2;});q.pricing.selected='competitor';confirm(q,{inputs:Object.fromEntries(q.products.map(n=>[n.id,{kg:{status:'excluded'},competitor:{status:'included',rate:10}}]))});const r=P.calculate(d);A.equal(r.total.beforeTax,400000);A.equal(r.total.vat,32000);A.equal(r.total.grand,432000);A.equal(q.products[0].competitorPrice,110000);A.equal(r.tax.releaseErrors.length,0);});
test('kg normalization uses blank weight; zero input VAT is an explicit valid declaration',()=>{const d=seed(),q=d.quote;q.pricing.selected='kg';confirm(q);const net=P.calculate(d).total.beforeTax;for(const n of q.products)n.pricePerKg*=1.1;confirm(q,{inputs:Object.fromEntries(q.products.map(n=>[n.id,{kg:{status:'included',rate:10},competitor:{status:'included',rate:0}}]))});A.equal(P.calculate(d).total.beforeTax,net);A.equal(P.calculate(d).tax.methods.competitor.comparable,true);});
test('changing alternative price invalidates only that declaration; selection does not invalidate tax',()=>{const d=seed(),q=d.quote;confirm(q);q.products[0].competitorPrice++;let r=P.calculate(d);A.equal(r.tax.methods.competitor.comparable,false);A.equal(r.tax.methods.kg.comparable,true);A.equal(r.tax.costKnown,true);q.pricing.selected='kg';r=P.calculate(d);A.equal(r.tax.releaseErrors.length,0);});
test('cost, brand, dimensions, recipe and VAT changes invalidate relevant confirmation',()=>{for(const change of [q=>q.products[0].qty++,q=>q.products[0].children[0].children[0].spec.price++,q=>q.products[0].children[0].children[0].spec.brand='Other',q=>q.products[0].params.W++,q=>q.ratesSnapshot[0].inside++,q=>q.pricing.delivery++,q=>q.operationMethods={cut:'catalog'},q=>q.remnantRules={test:{minL:500}}]){const d=seed();confirm(d.quote);change(d.quote);A.equal(P.calculate(d).tax.costKnown,false);}const d=seed();confirm(d.quote);d.quote.vat=8;A.equal(P.calculate(d).tax.outputKnown,false);});
test('comparison has fixed disjoint reference cost + processing, null zero denominator, no mutation',()=>{const d=seed(),q=d.quote;q.products.forEach(n=>n.competitorPrice=0);confirm(q);const json=JSON.stringify(d),r=P.calculate(d),t=r.alternatives.detail.total;A.ok(Math.abs(r.tax.reference-(t.cost+t.processing))<1e-7);A.equal(r.tax.methods.detail.deltaCompetitorPercent,null);A.equal(r.tax.methods.detail.residual,t.beforeTax-r.tax.reference);A.equal(r.tax.methods.tmc.net,null);A.equal(JSON.stringify(d),json);A.deepEqual(P.calculate(JSON.parse(json)).tax,r.tax);});
test('declaration validation is atomic, explicit and locked; no missing or invalid rate inferred',()=>{const d=seed(),q=d.quote;for(const rate of ['',null,-1,101,'abc']){const json=JSON.stringify(q);A.throws(()=>confirm(q,{inputs:{[q.products[0].id]:{kg:{status:'included',rate}}}}),/thuế suất/);A.equal(JSON.stringify(q),json);}A.throws(()=>confirm(q,{reason:''}),/căn cứ/);q.status='approved';A.throws(()=>confirm(q),/khóa/);});
test('known selected tax does not require unrelated alternative inputs; TMC unresolved not issuable',()=>{const d=seed(),q=d.quote;confirm(q,{inputs:{}});q.documentMode='official';A.equal(P.calculate(d).errors.length,0);q.pricing.selected='tmc';A.match(P.calculate(d).errors.join(' '),/CĐ-01/);});
test('changing reference costs never adds them again to all-in prices',()=>{const d=seed(),q=d.quote;confirm(q);const before=P.calculate(d);q.pricing.delivery+=100000;const after=P.calculate(d);for(const id of ['kg','competitor'])A.equal(after.alternatives[id].total.beforeTax,before.alternatives[id].total.beforeTax);A.equal(after.tax.methods.kg.residual,null);});
test('copy or change quote identity requires a fresh output tax declaration',()=>{const d=seed();confirm(d.quote);d.quote.id+='-COPY';A.equal(P.calculate(d).tax.outputKnown,false);confirm(d.quote);A.equal(P.calculate(d).tax.outputKnown,true);});
