'use strict';
const {chromium,expect}=require('@playwright/test'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url');
const url=process.env.THICKNESS_URL||pathToFileURL(path.resolve('dist/index.html')).href,dir=path.resolve(process.env.THICKNESS_ROOT||'artifacts/customer-review/thickness-2026-09-14',url.startsWith('https:')?'live':'local');fs.mkdirSync(dir,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true}),p=await browser.newPage({viewport:{width:1560,height:1080}}),checks=[],screens=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(12000);
 const shot=async name=>{await p.screenshot({path:path.join(dir,name+'.png'),fullPage:true});screens.push(name+'.png');},pass=s=>{checks.push(s);console.log('PASS '+s);},submit=async()=>{await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#dialog')).not.toBeVisible();},bom=async()=>p.locator('[data-tab=bom]').click();
 try{
  await p.goto(url);await p.evaluate(()=>{db=TP.seed();TPPrice.enable(db);page='quote';tab='bom';selected=db.quote.products[0].id;UX.mode='quick';render();persist();});
  const id=await p.evaluate(()=>db.quote.products[0].id),input=()=>p.locator(`[data-param-product="${id}"][data-param-key=T]`),snapshot=()=>p.evaluate(id=>{const n=C.findNode(db.quote.products,id);return {children:n.children,materials:db.materials,total:result.total};},id),baseline=await snapshot();
  await expect(input()).toHaveValue('');expect(await p.locator(`[data-param-product="${id}"]`).evaluateAll(es=>es.map(e=>e.dataset.paramKey))).toEqual(['L','W','H','T']);await input().scrollIntoViewIfNeeded();await shot('01-day-chung-chua-khai');pass('Legacy quotation shows empty Dày T after L/W/H, with no guessed value');
  await input().fill('2.25');await input().blur();expect(await p.evaluate(id=>C.findNode(db.quote.products,id).params.T,id)).toBe(2.25);expect(await snapshot()).toEqual(baseline);await expect(p.locator(`[data-thickness-note="${id}"]`)).toContainText('1,5 mm');await shot('02-day-thap-phan-khong-doi-vat-tu');await p.reload();await bom();await expect(input()).toHaveValue('2.25');pass('Decimal survives reload; fixed material dimensions, brands, catalogue and quote totals unchanged');
  await input().fill('0');await input().blur();await expect(input()).toHaveClass(/invalid-input/);expect(await p.evaluate(id=>C.findNode(db.quote.products,id).params.T,id)).toBe(2.25);await shot('03-chan-day-bang-khong');await input().fill('-1');await input().blur();expect(await p.evaluate(id=>C.findNode(db.quote.products,id).params.T,id)).toBe(2.25);await input().fill('');await input().blur();expect(await p.evaluate(id=>C.findNode(db.quote.products,id).params.T,id)).toBeNull();await p.locator('[data-action=ux-undo]').first().click();await expect(input()).toHaveValue('2.25');pass('Zero/negative rejected; clear means unknown, undo restores previous value');
  await input().fill('1.5');await input().blur();await p.locator(`[data-product-panel="${id}"] [data-action=save-template]`).click();await p.locator('[name=name]').fill('QA mẫu Dày 1,5');await submit();const template=await p.evaluate(()=>db.library.find(n=>n.name==='QA mẫu Dày 1,5'));expect(template.params.T).toBe(1.5);
  await p.locator('[data-action=variant]').first().click();await expect(p.locator('[name=T]')).toHaveValue('1.5');await p.locator('[name=T]').fill('2');await shot('04-bien-the-day-rieng');await submit();const variant=await p.evaluate(()=>db.quote.products.at(-1));expect(variant.params.T).toBe(2);expect(await p.evaluate(id=>C.findNode(db.quote.products,id).params.T,id)).toBe(1.5);expect(await p.evaluate(()=>db.library.find(n=>n.name==='QA mẫu Dày 1,5').params.T)).toBe(1.5);await p.reload();await bom();expect(await p.evaluate(()=>db.quote.products.at(-1).params.T)).toBe(2);pass('Real save-template and variant forms retain independent thickness through reload');
  // Exercise existing template insertion through the user-facing picker.
  await p.locator(`[data-product-panel="${id}"] [data-action=pick-template]`).click();await expect(p.locator('#dialog')).toContainText('QA mẫu Dày 1,5');await p.locator('[name=template]').selectOption(template.id);await shot('05-mau-luu-co-day');await submit();expect(await p.evaluate(id=>C.findNode(db.quote.products,id).children.at(-1).params.T,id)).toBe(1.5);pass('Template picker inserts a real independent product copy with saved thickness');
  await p.locator(`[data-product-panel="${id}"] .row-more`).first().click();await p.locator('#dialog [data-ux=configure-links]').click();await expect(p.locator('[name=T]')).toHaveValue('1.5');await p.locator('[name=T]').fill('');await submit();await expect(input()).toHaveValue('');await p.reload();await bom();await expect(input()).toHaveValue('');pass('Common dimension configuration accepts empty T without coercing it to zero');
  await p.setViewportSize({width:390,height:844});await input().scrollIntoViewIfNeeded();expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await shot('06-day-tren-man-hinh-hep');expect(errors).toEqual([]);pass('Narrow viewport: field reachable, no page overflow or runtime errors');
  fs.writeFileSync(path.join(dir,'results.json'),JSON.stringify({passed:true,url,at:new Date().toISOString(),checks,screens,errors},null,2));
 }catch(e){console.error(e);await shot('FAILURE');fs.writeFileSync(path.join(dir,'results.json'),JSON.stringify({passed:false,url,at:new Date().toISOString(),checks,screens,errors,error:e.message},null,2));process.exitCode=1;}finally{await browser.close();}
})();
