'use strict';
const {chromium,expect}=require('@playwright/test'),fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url'),F=require('./tmc-fixture.cjs');
const url=process.env.TMC_URL||pathToFileURL(path.resolve('dist/index.html')).href,dir=path.resolve(process.env.TMC_ROOT||'artifacts/customer-review/tmc-2026-09-14',url.startsWith('https:')?'live':'local');fs.mkdirSync(dir,{recursive:true});
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true}),p=await b.newPage({viewport:{width:1560,height:1080}}),checks=[],screens=[],errors=[];p.on('pageerror',e=>errors.push(e.message));p.setDefaultTimeout(12000);const f=n=>p.locator('#dialog [name="'+n+'"]'),submit=async()=>{await p.locator('#dialog button[type=submit]').click();await expect(p.locator('#dialog')).not.toBeVisible();},shot=async n=>{await p.screenshot({path:path.join(dir,n+'.png'),fullPage:true});screens.push(n+'.png');},pass=s=>{checks.push(s);console.log('PASS '+s);};
try{
 await p.goto(url);const pure=F.seed();F.confirm(pure.quote);await p.evaluate(d=>{db=d;page='quote';tab='pricing';render();},pure);expect(await p.evaluate(()=>result.total.grand)).toBe(3458);await shot('00-tmc-thuan-dap-an-3458');pass('Pure TMC independently expected 3,202 net + 256 VAT = 3,458 in rendered application');const data=F.mixed();delete data.quote.pricing.tmcPolicy;data.quote.products[1].tmcScope='unknown';await p.evaluate(d=>{db=d;page='quote';tab='pricing';render();persist();},data);expect(await p.evaluate(()=>result.alternatives.tmc.ready)).toBe(false);await shot('01-chua-phan-nhom-khong-am-tham-tinh');
 await p.locator('[data-pa=product-inputs]').first().click();await f('scope-qa-mechanical').selectOption('detail');await submit();await expect(p.locator('.pa-comparison')).toContainText('Chi tiết (ngoài TMC)');expect(await p.evaluate(()=>result.tax.methods.tmc.comparable)).toBe(false);pass('Explicit mechanical scope through real form; unknown grouping and missing recipe not treated as valid TMC');
 await p.locator('[data-mfg=policy]').first().click();for(const [k,v]of Object.entries({overhead:5,management:3,special:0,profit:10,processing:2,order:0,customer:0}))await f('tmcp-'+k).fill(String(v));await f('tmcp-reason').fill('QA independent 10,009 before tax; synthetic coefficients');await f('tmcp-confirm').check();await shot('02-chuoi-rieng-tmc');await submit();expect(await p.evaluate(()=>result.total.beforeTax)).toBe(10009);pass('Independent TMC policy real form gives mixed total 10,009; not copied from detail factors');
 await p.locator('[data-tab=prices]').click();for(const key of ['tmc:qa:0','tmc:qa:ancillary','tmc:qa:common']){await p.locator('[data-b6=cost][data-key="'+key+'"]').click();await f('sourceStatus').selectOption('excluded');await f('sourceReason').fill('QA net-price fixture; not customer rates');await f('confirmSource').check();await submit();}
 await p.locator('[data-tax=edit]').click();for(let i=0;i<2;i++){await f('tax-kg-'+i).selectOption('excluded');await f('tax-competitor-'+i).selectOption('excluded');await f('market-value-'+i).fill('2200');await f('market-source-'+i).fill('QA market source '+i);await f('tax-market-'+i).selectOption('included');await f('rate-market-'+i).fill('10');}await f('costConfirmed').check();await f('outputConfirmed').check();await f('taxReason').fill('QA: market 2200 includes 10%; output 8%, test only');await submit();await p.locator('[data-tab=pricing]').click();expect(await p.evaluate(()=>result.tax.market)).toBe(10000);expect(await p.evaluate(()=>result.tax.methods.tmc.deltaMarket)).toBe(9);expect(await p.evaluate(()=>result.tax.releaseErrors)).toEqual([]);await shot('03-bon-cot-tmc-co-khi-va-thi-truong');await p.locator('.pa-comparison').evaluate(el=>el.scrollTop=500);await p.locator('.pa-comparison').screenshot({path:path.join(dir,'03b-chi-so-thi-truong-va-nhanh-tinh.png')});screens.push('03b-chi-so-thi-truong-va-nhanh-tinh.png');pass('Used TMC source prices declared through real forms; four comparable methods and independent gross market normalization');
 const totals=await p.evaluate(()=>Object.fromEntries(Object.entries(result.alternatives).map(([k,a])=>[k,a.total.beforeTax])));for(const id of ['kg','competitor','detail','tmc']){await p.locator('[data-pa=choose][data-method='+id+']').click();expect(await p.evaluate(()=>result.total.beforeTax)).toBe(totals[id]);expect(await p.evaluate(()=>Object.fromEntries(Object.entries(result.alternatives).map(([k,a])=>[k,a.total.beforeTax])))).toEqual(totals);}await p.locator('[data-pa=toggle-costs]').click();expect(await p.evaluate(()=>result.tax.methods.tmc.deltaMarket)).toBe(9);await p.reload();await p.locator('[data-tab=pricing]').click();expect(await p.evaluate(()=>db.quote.pricing.selected)).toBe('tmc');expect(await p.evaluate(()=>result.total.grand)).toBe(10810);pass('One quote-level choice; switching/hiding columns does not mutate four inputs; reload preserves mixed total and policy');
 const sheets=await p.evaluate(()=>exportSheets(true)),internal=sheets.find(s=>s.name==='Mat bang gia thue');expect(internal.rows.find(r=>r[0]==='Giá trước thuế')[2]).toBe(10009);expect(internal.rows.find(r=>r[0]==='Chênh so thị trường (đ)')[2]).toBe(9);expect(JSON.stringify(await p.evaluate(()=>exportSheets(false)))).not.toContain('QA market source');pass('Internal export reconciles TMC and market; customer export excludes private market source');
 await p.evaluate(()=>{db.quote.documentMode='official';db.quote.issuer={name:'QA TRƯỜNG PHÁT'};tab='preview';render();});await require('./offer-form.cjs')(p);await p.locator('[data-action=approve]').click();await submit();await expect(p.locator('#content .paper')).toContainText('10.810');await shot('04-ban-chao-duyet-tmc-hon-hop');const dl=p.waitForEvent('download');await p.locator('[data-work=export-customer-xlsx]').click();await(await dl).saveAs(path.join(dir,'QA-TMC.xlsx'));await p.evaluate(()=>{window.__qaPrintInvoked=false;window.print=()=>{window.__qaPrintInvoked=true;};});await p.locator('[data-action=print]').click();expect(await p.evaluate(()=>window.__qaPrintInvoked)).toBe(true);await expect(p.locator('#print-area .paper')).toContainText('10.810');await p.emulateMedia({media:'print'});await p.pdf({path:path.join(dir,'QA-TMC.pdf'),format:'A4',printBackground:true});await p.emulateMedia({media:'screen'});pass('Official approval, real downloaded XLSX and printed PDF from mixed TMC quote have verified total');
 await p.evaluate(()=>{mutation(()=>db.quote.pricing.tmcTables[0].tiers[0].price=120);tab='pricing';render();});expect(await p.evaluate(()=>result.tax.methods.tmc.comparable)).toBe(false);await shot('05-nguon-tmc-thay-doi-chan-phat-hanh');await p.locator('[data-tab=preview]').click();await expect(p.locator('#content .paper')).toHaveCount(0);pass('Changing used TMC rate invalidates tax evidence and blocks stale official paper');
 await p.evaluate(()=>{db.quote.documentMode='working';db.quote.status='draft';tab='pricing';render();});await p.setViewportSize({width:390,height:844});await p.locator('[data-mfg=policy]').first().click();await shot('06-chuoi-tmc-man-hinh-hep');expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await p.keyboard.press('Escape');expect(errors).toEqual([]);pass('Narrow viewport policy form usable; no runtime errors');
 fs.writeFileSync(path.join(dir,'results.json'),JSON.stringify({passed:true,url,at:new Date().toISOString(),checks,screens,errors},null,2));
}catch(e){console.error(e);await shot('FAILURE');fs.writeFileSync(path.join(dir,'results.json'),JSON.stringify({passed:false,url,at:new Date().toISOString(),checks,screens,errors,error:e.message},null,2));process.exitCode=1;}finally{await b.close();}})();
