'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),C=require('../core.js'),P=require('../pricing-core.js'),M=require('../manufacturing-core.js'),I=require('../input-prices-core.js'),Cost=require('../cost-input-core.js'),Tax=require('../tax-core.js');
const near=(a,b)=>A.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function fixture(){const d=P.demoSeed();d.quote.remnantMode='all';d.quote.products=d.quote.products.slice(0,1);const p=d.quote.pricing;p.tmcTables=p.tmcTables.filter(t=>t.id===d.quote.products[0].tmcKind);const rate={id:'aggregate-tmc',name:'Toàn bộ nguyên công',unit:'m',inside:2000,outside:3000,factors:[{id:'width-tmc',name:'Khổ rộng',param:'W',tiers:[{max:300,percent:10},{max:null,percent:20}]}]};d.rates.push(rate);p.tmcLaborOperation={default:{rate:C.copy(rate),choice:'factors'},tables:{},replaces:['cut','bend']};return d;}
test('TMC package replaces included factory work once while detailed pricing and technical declaration remain identical',()=>{const d=fixture(),q=d.quote,config=q.pricing.tmcLaborOperation;delete q.pricing.tmcLaborOperation;const before=P.calculate(d),technical=JSON.stringify(q.products);q.pricing.tmcLaborOperation=config;const input=JSON.stringify(d),after=P.calculate(d),item=after.alternatives.tmc.products[0].tmc.items[0];A.deepEqual(after.alternatives.tmc.errors,[]);near(item.labor,item.basis*2200);near(after.alternatives.detail.total.grand,before.alternatives.detail.total.grand);near(after.alternatives.tmc.products[0].parts.factory,before.products[0].parts.factory-C.flatten(q.products).reduce((s,n)=>s+before.nodes[n.id].ownReplaceableFactory,0)+item.labor);A.equal(JSON.stringify(q.products),technical);A.equal(JSON.stringify(d),input);q.products[0].tmcWidth=301;near(P.calculate(d).alternatives.tmc.products[0].tmc.items[0].rate,2400);});
test('TMC supports separate accessory units and chosen price option without converting metres to pieces',()=>{const d=fixture(),p=d.quote.pricing,n=d.quote.products[0];p.tmcTables[0].unit='cái';A.throws(()=>M.validateLabor(p),/đơn vị/);const rate=C.copy(p.tmcLaborOperation.default.rate);rate.priceOptions=[{id:'opt-accessory',name:'Phụ kiện',method:'catalog',inside:7000,outside:8000,insideUnit:'cái',outsideUnit:'cái'}];p.tmcLaborOperation.tables[n.tmcKind]={rate,choice:'option:opt-accessory'};M.validateLabor(p);const item=P.calculate(d).alternatives.tmc.products[0].tmc.items[0];near(item.labor,n.qty*7000);A.equal(item.unit,'cái');A.equal(item.laborPricing.priceOptionName,'Phụ kiện');});
test('TMC fixed package has explicit scope and does not inherit the quote operation pricing method',()=>{const d=fixture(),b=d.quote.pricing.tmcLaborOperation.default;b.rate.priceOptions=[{id:'opt-total',name:'Công trọn phần',method:'fixed',inside:100000,outside:200000,insideUnit:'gói',outsideUnit:'gói',fixedScope:'total'}];b.choice='option:opt-total';d.quote.operationMethods={[b.rate.id]:'catalog'};near(P.calculate(d).alternatives.tmc.products[0].tmc.items[0].labor,100000);b.rate.priceOptions[0].fixedScope='unit';near(P.calculate(d).alternatives.tmc.products[0].tmc.items[0].labor,100000*d.quote.products[0].qty);});
test('TMC does not duplicate aggregate if technical scope already declares it; outside work stays separate',()=>{const d=fixture(),q=d.quote,n=q.products[0],b=q.pricing.tmcLaborOperation.default;q.ratesSnapshot.push(C.copy(b.rate));n.ops.push({id:b.rate.id,mode:'inside',pricingMethod:'catalog',amount:2});const r=P.calculate(d),p=r.alternatives.tmc.products[0],own=C.flatten([n]).reduce((s,x)=>s+r.nodes[x.id].ownReplaceableFactory,0);near(p.parts.factory,r.products[0].parts.factory-own+p.tmc.items[0].labor);A.equal(n.ops.at(-1).pricingMethod,'catalog');near(p.parts.outside,r.products[0].parts.outside);});
test('TMC source VAT normalization uses selected aggregate price and ignores unused width-table labour source',()=>{const d=fixture(),q=d.quote,key=M.laborSourceKey(q.pricing,q.products[0].tmcKind);Cost.apply(q,[{key,original:2200,status:'included',rate:10}],'Nguồn QA');near(q.pricing.tmcLaborOperation.default.rate.inside,2000);A.equal(Cost.view(q).find(x=>x.key===key).known,true);M.setPolicy(q,{reason:'QA',...Object.fromEntries(M.policyKeys.map(k=>[k,0]))});const used=Cost.view(q).filter(x=>x.tmcOnly&&x.key!==key&&!/^tmc:[^:]+:\d+$/.test(x.key));if(used.length)Cost.apply(q,used.map(x=>({key:x.key,original:x.value,status:'excluded'})),'QA');Tax.review(q,{reason:'QA',costConfirmed:true,outputConfirmed:true,inputs:{}});A.equal(P.calculate(d).tax.methods.tmc.comparable,true);q.pricing.tmcLaborOperation.default.rate.inside++;A.equal(P.calculate(d).tax.methods.tmc.comparable,false);});
test('TMC master updates only on explicit refresh; quote JSON carries independent saved aggregate',()=>{const d=fixture();d.pricingDefaults=C.copy(d.quote.pricing);const old=JSON.stringify(d.quote.pricing.tmcLaborOperation),rate=d.rates.find(r=>r.id==='aggregate-tmc');rate.inside=5000;I.defaults(d);A.equal(JSON.stringify(d.quote.pricing.tmcLaborOperation),old);I.refresh(d);A.equal(d.quote.pricing.tmcLaborOperation.default.rate.inside,5000);rate.inside=8000;A.equal(d.quote.pricing.tmcLaborOperation.default.rate.inside,5000);A.deepEqual(P.calculate(JSON.parse(JSON.stringify(d))).alternatives.tmc.errors,[]);});
module.exports={fixture};
