'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),P=require('../pricing-core.js'),C=require('../core.js'),M=require('../manufacturing-core.js'),Tax=require('../tax-core.js'),Cost=require('../cost-input-core.js'),F=require('./tmc-fixture.cjs');
const near=(a,b)=>A.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
test('TMC complete independent recipe: material, replaced labor, auxiliary, common, freight, factors and rounding once',()=>{const d=F.seed();F.confirm(d.quote);const r=P.calculate(d),p=r.products[0];A.deepEqual(r.errors,[]);near(p.weight,20);near(p.parts.stock,2200);near(p.parts.factory,200);near(p.parts.ancillary,20);near(p.parts.tmcCommon,30);near(p.direct,2510);near(p.production,2714.565);near(p.cost,2854.565);A.equal(p.unitSell,1601);A.equal(r.total.beforeTax,3202);A.equal(r.total.vat,256);A.equal(r.total.grand,3458);A.equal(r.tax.methods.tmc.net,3202);A.deepEqual(r.tax.releaseErrors,[]);});
test('mixed order preserves every non-TMC detailed cost/factor; global selection and totals reconcile',()=>{const d=F.mixed();F.confirm(d.quote);const r=P.calculate(d),outside=r.alternatives.tmc.products[1],detail=r.alternatives.detail.products[1];for(const k of ['cost','production','suggestedUnit','sell'])A.equal(outside[k],detail[k]);A.deepEqual(outside.parts,detail.parts);A.equal(outside.tmc.scope,'detail');A.equal(r.total.beforeTax,r.products.reduce((s,p)=>s+p.sell,0));A.equal(r.products.length,2);A.deepEqual(r.tax.releaseErrors,[]);});
test('not-TMC is explicit, unknown grouping and missing/stale TMC prices never silently fall back',()=>{for(const mutate of [n=>{delete n.tmcScope;delete n.tmcKind;},n=>n.tmcKind='missing',n=>n.tmcScope='other']){const d=F.seed();mutate(d.quote.products[0]);const r=P.calculate(d);A.equal(r.alternatives.tmc.ready,false);A.ok(r.errors.length);}const d=F.seed();d.quote.products[0].tmcScope='detail';delete d.quote.pricing.tmcPolicy;F.confirm(d.quote);const r=P.calculate(d);A.equal(r.total.beforeTax,r.alternatives.detail.total.beforeTax);A.equal(r.alternatives.tmc.applicable,false);A.ok(r.tax.releaseErrors.length);A.ok(r.errors.some(e=>e.includes('Không có sản phẩm')));});
test('TMC policy and reference-only detailed factors are isolated; actual TMC inputs remain reactive',()=>{const d=F.seed(),before=P.calculate(d);for(const key of M.policyKeys)d.quote.pricing[key]=50;d.quote.pricing.salesFactors=[{id:'extra',name:'QA reference',percent:30,reason:'QA'}];d.quote.pricing.productionFactors=[{id:'extra-p',name:'QA ref',percent:30,reason:'QA'}];const after=P.calculate(d);A.equal(after.alternatives.tmc.total.beforeTax,before.total.beforeTax);A.notEqual(after.alternatives.detail.total.beforeTax,before.alternatives.detail.total.beforeTax);d.quote.pricing.tmcTables[0].tiers[0].price=120;A.ok(P.calculate(d).total.beforeTax>before.total.beforeTax);});
test('TMC units distinguish per metre from accessory each, boundary exact and above, factor/quantity once',()=>{const d=F.seed(),n=d.quote.products[0];n.params.L=2000;n.children[0].spec.stockL=2000;let r=P.calculate(d);A.equal(r.products[0].tmc.items[0].basis,4);d.quote.pricing.tmcTables[0].unit='cái';r=P.calculate(d);A.equal(r.products[0].tmc.items[0].basis,2);n.tmcWidth=1001;A.equal(P.calculate(d).products[0].tmc.items[0].rate,200);n.tmcWidth=1000;A.equal(P.calculate(d).products[0].tmc.items[0].rate,100);d.quote.pricing.tmcTables[0].tiers[0].price=0;A.equal(P.calculate(d).alternatives.tmc.ready,true);A.equal(P.calculate(d).products[0].parts.factory,0);});
test('TMC source tax converts gross once, used tier changes require fresh declarations, unused missing tiers do not block',()=>{const d=F.seed(),q=d.quote;q.pricing.tmcTables[0].tiers[0].price=110;Cost.apply(q,[{key:'tmc:qa:0',status:'included',rate:10,original:110}],'QA gross 110 at 10%');F.confirm(q);delete q.costPriceSources['tmc:qa:1'];Tax.review(q,{reason:'QA unused tier',costConfirmed:true,outputConfirmed:true,inputs:{}});let r=P.calculate(d);A.equal(r.total.beforeTax,3202);A.deepEqual(r.tax.releaseErrors,[]);q.pricing.tmcTables[0].tiers[0].price=120;r=P.calculate(d);A.equal(r.tax.methods.tmc.net,null);A.ok(r.tax.methods.tmc.reasons.some(s=>s.includes('nguồn')));});
test('TMC policy requires explicit complete coefficients and source; invalid recipe cannot issue official',()=>{const d=F.seed(),q=d.quote;for(const value of ['',null,-100,Infinity]){const before=JSON.stringify(q);A.throws(()=>M.setPolicy(q,{...q.pricing.tmcPolicy,overhead:value}));A.equal(JSON.stringify(q),before);}delete q.pricing.tmcPolicy;F.confirm(q);q.documentMode='official';require('./offer-fixture.cjs')(q);A.ok(P.calculate(d).errors.some(e=>e.includes('CĐ-01')));q.status='approved';A.throws(()=>M.setPolicy(q,{reason:'QA'}),/khóa/);});
test('independent market benchmark: source/gross normalization/deltas/zero denominator, not a fifth method',()=>{const d=F.seed(),q=d.quote,n=q.products[0];n.marketPrice=2200;n.marketSource='QA market sheet, not competitor';F.confirm(q);Tax.review(q,{reason:'QA',costConfirmed:true,outputConfirmed:true,inputs:{[n.id]:{market:{status:'included',rate:10},competitor:{status:'excluded'},kg:{status:'excluded'}}}});let r=P.calculate(d);A.equal(r.tax.market,4000);A.equal(r.tax.methods.tmc.deltaMarket,-798);near(r.tax.methods.tmc.deltaMarketPercent,-19.95);A.equal(Object.keys(r.alternatives).length,4);A.equal(n.marketPrice,2200);n.marketPrice=0;F.confirm(q);r=P.calculate(d);A.equal(r.tax.market,0);A.equal(r.tax.methods.tmc.deltaMarketPercent,null);});
test('market absent/stale/partial/unknown never changes a quoted price or blocks otherwise valid quotation',()=>{const d=F.mixed(),q=d.quote;F.confirm(q);const before=P.calculate(d);q.products[0].marketPrice=100;q.products[0].marketSource='QA';F.confirm(q);let r=P.calculate(d);A.equal(r.tax.market,null);A.equal(r.total.beforeTax,before.total.beforeTax);A.deepEqual(r.tax.releaseErrors,[]);q.products[1].marketPrice=200;q.products[1].marketSource='QA 2';F.confirm(q);A.equal(P.calculate(d).tax.market,800);q.products[0].marketSource='Changed source';r=P.calculate(d);A.equal(r.tax.market,null);A.equal(r.tax.costKnown,true);A.deepEqual(r.tax.releaseErrors,[]);});
test('TMC/market snapshots are pure and factor permission fingerprint covers separate policy',()=>{const d=F.mixed();F.confirm(d.quote);const s=JSON.stringify(d),a=P.calculate(d);A.equal(JSON.stringify(d),s);A.deepEqual(P.calculate(JSON.parse(s)),a);const access=require('../server/access.cjs'),fp=access.factorFingerprint(d);d.quote.pricing.tmcPolicy.profit++;A.notEqual(access.factorFingerprint(d),fp);});
test('TMC XL CB common base includes finishing/internal freight/install, excludes delivery and never repeats common',()=>{
 const d=F.seed(),q=d.quote;q.pricing.tmcTables[0].common={kind:'percent',value:2,basis:'scope'};
 // Controlled numbers: stock 2200 + labor 200 + auxiliary 20 + inbound 60 + install 40 = 2520.
 // Common is 50.4, not 48 (stock+labor) or 52.4 (incorrectly including delivery).
 F.confirm(q);const before=JSON.stringify(d),r=P.calculate(d),n=r.products[0];A.deepEqual(r.errors,[]);near(n.parts.tmcCommon,50.4);near(n.tmc.items[0].commonBase,2520);near(n.direct,2530.4);near(n.production,2736.6276);near(n.cost,2876.6276);A.equal(n.unitSell,1614);A.equal(r.total.beforeTax,3228);A.equal(JSON.stringify(d),before);
 q.pricing.delivery+=100;near(P.calculate(d).products[0].parts.tmcCommon,50.4);q.pricing.install+=100;near(P.calculate(d).products[0].parts.tmcCommon,52.4);
 const base={rows:[],nodes:{root:{count:1,node:{}}}},node={id:'root',qty:1,kind:'product',name:'QA full cost',params:{W:100,L:1000},children:[],tmcKind:'full'},parts={stock:0,factory:17,outside:19,finishing:23,ancillary:29,allowance:0,incoming:31,outgoing:37,delivery:1000,install:41};base.nodes.root.node=node;
 const p={tmcLoss:0,tmcTables:[{id:'full',unit:'cái',name:'QA',tiers:[{max:null,price:43}],ancillary:{kind:'fixed',value:47},common:{kind:'percent',value:2,basis:'scope'}}]};const calculated=M.tmc({node,parts},base,p,P.tier,()=>0);near(calculated.items[0].commonBase,287);near(calculated.parts.tmcCommon,5.74);A.equal(calculated.parts.delivery,1000);
});
test('TMC XL CB common base aggregates multiple scopes once; inconsistent rates and duplicate common charges fail closed',()=>{
 const d=F.seed(),q=d.quote,n=q.products[0],second=C.cloneNode(n.children[0]);n.children.push(second);q.pricing.tmcTables[0].common={kind:'percent',value:2,basis:'scope'};n.tmcBreakdown=n.children.map(node=>({nodeId:node.id,tableId:'qa'}));let r=P.calculate(d);A.deepEqual(r.errors,[]);near(r.products[0].tmc.commonSummary.basis,4940);near(r.products[0].parts.tmcCommon,98.8);A.ok(r.products[0].tmc.items.every(i=>i.common===0));n.tmcBreakdown.reverse();near(P.calculate(d).products[0].parts.tmcCommon,98.8);
 const other=C.copy(q.pricing.tmcTables[0]);other.id='other';other.common.value=3;q.pricing.tmcTables.push(other);n.tmcBreakdown[1].tableId='other';A.ok(P.calculate(d).errors.some(s=>s.includes('cùng một tỷ lệ')));other.common={kind:'fixed',value:1};A.ok(P.calculate(d).errors.some(s=>s.includes('khoản chung')));other.common={kind:'fixed',value:0};A.deepEqual(P.calculate(d).errors,[]);
 n.tmcBreakdown=[{nodeId:n.id,tableId:'qa',laborOnly:true}];A.ok(P.calculate(d).errors.some(s=>s.includes('chỉ bổ sung nhân công')));
});
