const {test}=require('node:test'),A=require('node:assert/strict'),C=require('../core'),D=require('../definition-core'),ME=require('../material-estimate-core');
const near=(a,b)=>A.ok(Math.abs(a-b)<1e-6,`${a} ≠ ${b}`);
const def=()=>({id:'TRIANGLE-QA',...D.example('triangle')});
function fixture(count=8,kerf=0){
 const db=C.seed(),d=def(),m=D.applyShape({id:'TRI',name:'Tam giác thử',density:7850,stockL:2000,stockW:1000,unit:'m²',price:100},d,{T:2}),n=D.assign(D.draft('Tam giác',count),m,db.rules);
 n.dims={L:1000,H:500};db.quote.products=[{id:'P',kind:'product',name:'P',qty:1,children:[n],ops:[]}];db.quote.kerf=kerf;return {db,n,d};
}
const area=points=>Math.abs(points.reduce((s,p,i)=>{const q=points[(i+1)%points.length];return s+p[0]*q[1]-p[1]*q[0];},0))/2;
// Separating axis theorem: interiors may not intersect; touching is permitted at kerf 0.
function separated(a,b){for(const poly of [a,b])for(let i=0;i<3;i++){const p=poly[i],q=poly[(i+1)%3],axis=[q[1]-p[1],p[0]-q[0]],project=ps=>ps.map(v=>v[0]*axis[0]+v[1]*axis[1]),x=project(a),y=project(b);if(Math.max(...x)<=Math.min(...y)+1e-7||Math.max(...y)<=Math.min(...x)+1e-7)return true;}return false;}
function inspect(layout,count){let seen=0,actual=0;for(const stock of layout.stocks){for(const p of stock.placements){seen++;actual+=area(p.polygon);for(const [x,y]of p.polygon){A.ok(x>=-1e-7&&x<=layout.stockL+1e-7);A.ok(y>=-1e-7&&y<=layout.stockW+1e-7);}for(const other of stock.placements)if(p!==other)A.ok(separated(p.polygon,other.polygon),'triangles overlap');}for(const free of stock.free)for(const p of stock.placements)A.ok(free.x+free.l<=p.x+1e-7||p.x+p.l<=free.x+1e-7||free.y+free.w<=p.y+1e-7||p.y+p.w<=free.y+1e-7,'free rectangle overlaps a triangle');}A.equal(seen,count);near(actual,layout.netUsed);near(layout.used,layout.netUsed+layout.internalAllowance+layout.triangleOffcut);}
test('eight right triangles pair into one stock, compared with two bounding stocks; quote and trial agree',()=>{
 const {db,n,d}=fixture(),r=C.calculate(db),g=r.groups[0],v=D.trial(d,{stockL:2000,stockW:1000,count:8,kerf:0});
 A.equal(g.layout.stocks.length,1);A.equal(g.layout.boundingStockCount,2);A.equal(g.layout.pairCount,4);near(g.totalWeight,31.4);near(g.purchaseCost,200);near(v.allowance.percent,0);near(v.buyKg,g.purchasedWeight);inspect(g.layout,8);
 const x=ME.comparisons(r,[n.id])[0];near(x.percent,0);near(x.used,2e6);
});
test('kerf opens the diagonal gap and cannot claim an exact-fit zero-loss sheet',()=>{
 const {db}=fixture(8,3),g=C.calculate(db).groups[0];A.ok(g.layout.stocks.length>1);A.ok(g.layout.internalAllowance>0);inspect(g.layout,8);
 for(const stock of g.layout.stocks){const ids=new Set(stock.placements.map(p=>p.pairId).filter(Boolean));for(const id of ids){const [a,b]=stock.placements.filter(p=>p.pairId===id),edges=poly=>poly.map((p,i)=>[p,poly[(i+1)%3]]).sort((x,y)=>Math.hypot(...[y[1][0]-y[0][0],y[1][1]-y[0][1]])-Math.hypot(...[x[1][0]-x[0][0],x[1][1]-x[0][1]])),[p,q]=edges(a.polygon)[0],b0=edges(b.polygon)[0][0];near(Math.abs((q[0]-p[0])*(b0[1]-p[1])-(q[1]-p[1])*(b0[0]-p[0]))/Math.hypot(q[0]-p[0],q[1]-p[1]),3);}}
 const free=g.remnants.reduce((s,x)=>s+x.measure,0);near(g.layout.netUsed+g.layout.triangleOffcut+g.kerfMeasure+free,g.layout.purchased);
});
test('odd count retains one unpaired triangle and accounts for its offcut separately',()=>{const {db}=fixture(7,0),g=C.calculate(db).groups[0];A.equal(g.layout.pairCount,3);A.equal(g.layout.singleCount,1);near(g.layout.triangleOffcut,250000);inspect(g.layout,7);near(ME.comparisons(C.calculate(db),[db.quote.products[0].children[0].id])[0].percent,(2/1.75-1)*100);});
test('a pair that exceeds stock can fall back to single bounds',()=>{const {db,n}=fixture(2,3);n.spec.stockL=1000;n.spec.stockW=500;const g=C.calculate(db).groups[0];A.equal(g.layout.pairCount,0);A.equal(g.layout.stocks.length,2);inspect(g.layout,2);});
test('mixed row dimensions preserve identity; compatible triangles can pair across rows',()=>{const {db,n}=fixture(1,2),b=C.cloneNode(n),c=C.cloneNode(n);b.qty=2;c.qty=3;c.dims={L:700,H:300};db.quote.products[0].children.push(b,c);const g=C.calculate(db).groups[0];inspect(g.layout,6);A.equal(g.layout.pairCount,2);A.equal(g.layout.singleCount,2);for(const row of g.rows)A.equal(g.layout.stocks.flatMap(s=>s.placements).filter(p=>p.rowId===row.id).length,row.count);});
test('explicit rotation can fit pairs on a narrow stock without reflecting the shape',()=>{const {db,n}=fixture(2,2);n.spec.stockL=550;n.spec.stockW=1100;const layout=C.calculate(db).groups[0].layout;A.equal(layout.pairCount,1);A.equal(layout.stocks.length,1);inspect(layout,2);for(const p of layout.stocks[0].placements)near(area(p.polygon),250000);});
test('undeclared historic triangle keeps bounding plan; saving a new definition does not migrate it',()=>{const {db,n,d}=fixture();delete n.spec.shapeDefinition.nesting;const before=JSON.stringify(db.quote);A.equal(C.calculate(db).groups[0].layout.stocks.length,2);D.saveShape(db,d);A.equal(JSON.stringify(db.quote),before);A.equal(C.calculate(db).groups[0].layout.stocks.length,2);});
test('triangle layout rejects a mismatched physical area/mass and invalid base',()=>{const {db,n}=fixture();n.spec.shapeDefinition.blankSurface='L * H / 1000000';A.match(C.calculate(db).errors.join(' '),/tam giác vuông/);A.throws(()=>D.validateShape({...def(),base:'bar'}),/xếp phôi/);A.throws(()=>D.validateShape({...def(),nesting:'unknown'}),/xếp phôi/);});
test('fixed orientation never rotates a bounding blank to make it fit',()=>{const {db,n}=fixture(2,0);n.spec.stockL=600;n.spec.stockW=1200;n.spec.shapeDefinition.nesting='bounding-fixed';A.match(C.calculate(db).errors.join(' '),/vượt khổ/);n.spec.shapeDefinition.nesting='bounding';A.equal(C.calculate(db).groups[0].layout.stocks.length,2);n.spec.stockL=2000;n.spec.stockW=1000;n.spec.shapeDefinition.nesting='bounding-fixed';const layout=C.calculate(db).groups[0].layout;for(const p of layout.stocks.flatMap(s=>s.placements)){A.equal(p.l,1000);A.equal(p.w,500);}});
test('several quantities and kerfs keep polygon areas, stock boundaries and non-overlap',()=>{for(const count of [1,2,3,6,11,20])for(const kerf of [0,.5,3,10]){const {db,n}=fixture(count,kerf);n.dims={L:317,H:211};inspect(C.calculate(db).groups[0].layout,count);}});
