const {chromium,expect}=require('@playwright/test'),{pathToFileURL}=require('node:url');
const fs=require('node:fs'),path=require('node:path'),{createApp}=require('../server/app.cjs');
(async()=>{
  const browser=await chromium.launch({channel:'msedge',headless:true}),folder=path.resolve('artifacts/phase1-2026-09-12');fs.mkdirSync(folder,{recursive:true});
  const p=await browser.newPage({viewport:{width:1440,height:1050},offline:true}),errors=[],passed=[];
  p.on('pageerror',e=>errors.push(e.message));const check=s=>{passed.push(s);console.log('PASS '+s);};
  const tab=n=>p.locator(`[data-tab="${n}"]`).click(),submit=()=>p.locator('#dialog button[type=submit]').click(),close=()=>p.locator('#dialog .dialog-head [data-action=close]').click();
  const reset=async()=>{await p.locator('[data-pa=sample]').click();await submit();};let server;
  try{
    await p.goto(pathToFileURL(path.resolve('dist/index.html')).href);await tab('operations');const first=await p.evaluate(()=>db.quote.products[0].id);
    await p.locator(`[data-pa=op-detail][data-id="${first}"]`).click();await p.locator('[name=method]').selectOption('direct');await p.locator('[name=unitPrice]').fill('1000');await p.locator('[name=priceUnit]').selectOption('m²');await p.locator('[name=basisMode]').selectOption('manual_total');await p.locator('[name=workQuantity]').fill('3');await submit();expect(await p.evaluate(()=>result.nodes[db.quote.products[0].id].ownOps[0].cost)).toBe(3000);
    await p.locator(`[data-pa=op-detail][data-id="${first}"]`).click();await p.locator('[name=method]').selectOption('fixed');await p.locator('[name=unitPrice]').fill('150000');await p.locator('[name=fixedScope]').selectOption('total');await submit();expect(await p.evaluate(()=>result.nodes[db.quote.products[0].id].ownOps[0].cost)).toBe(150000);check('Direct and fixed job methods save and recalculate through actual controls');
    await p.locator('[data-pa=quote-rates]').click();await p.locator('#dialog [data-pa=edit-rate][data-id=cut]').click();
    const factor=p.locator('.pa-factor-editor').first();await factor.locator('[data-work-factor-kind]').selectOption('category');await factor.locator('select[name^=factor-param]').selectOption('substance');await factor.locator('.work-category-row input').first().fill('Thép');await factor.locator('.work-category-row input').nth(1).fill('25');await submit();expect(await p.evaluate(()=>result.errors)).toEqual([]);check('Category factors can be declared and looked up without missing-group fallback');
    await p.locator('[data-pa=quote-rates]').click();await p.locator('#dialog [data-pa=edit-rate][data-id=paint]').click();await p.locator('[data-work=add-recipe]').click();const recipe=p.locator('.work-recipe').last();await recipe.locator('select[name^=recipe-material]').selectOption('BM-SON');await recipe.locator('input[name^=recipe-norm]').fill('0.05');await recipe.locator('input[name^=recipe-layers]').fill('2');await recipe.locator('input[name^=recipe-loss]').fill('10');await submit();expect(await p.evaluate(()=>result.generated.length)).toBe(2);check('Multiple finishing materials, layer counts and material loss can be edited');
    await reset();await tab('logistics');const before=await p.evaluate(()=>result.total.grand);
    await p.locator('[data-work=convert-expenses]').click();await submit();expect(await p.evaluate(()=>result.logistics.items.length)).toBe(3);expect(await p.evaluate(()=>result.total.grand)).toBe(before);check('Migration makes existing freight items explicit with exactly unchanged final price');
    await p.locator('[data-work=expense]').first().click();await p.locator('[name=name]').fill('Giao hàng thử hai chuyến');await p.locator('[name=category]').selectOption('delivery');await p.locator('[name=method]').selectOption('trip');await p.locator('[name=trips]').fill('2');await p.locator('[name=rate]').fill('100000');await p.locator('[name=minimum]').fill('250000');await expect(p.locator('#work-expense-result')).toContainText('250.000');await submit();expect(await p.evaluate(()=>result.logistics.items.at(-1).cost)).toBe(250000);
    await p.locator('[data-work=expense]').first().click();await p.locator('[name=name]').fill('Tuyến tấn km');await p.locator('[name=method]').selectOption('ton_km');await p.locator('[name=distance]').fill('50');await p.locator('[name=rate]').fill('20000');await submit();expect(await p.evaluate(()=>result.errors)).toEqual([]);check('Trip minimum and tấn×km live preview agree with saved costs');
    await p.screenshot({path:path.join(folder,'01-van-chuyen.png'),fullPage:true});
    await p.locator('[data-work=expense]').first().click();await p.locator('[name=name]').fill('Chưa chọn vật tư');await p.locator('[name=scope]').selectOption('materials');await p.locator('[name=rate]').fill('100');await submit();await expect(p.locator('#dialog-error')).toBeVisible();await close();check('Missing expense scope blocks save with an actionable message');
    await reset();await p.locator('[data-action=quote-list]').click();await p.locator('#dialog [data-work=copy-quote]').click();await p.locator('[name=id]').fill('BG-COPY-TEST');await submit();expect(await p.evaluate(()=>db.quote.id)).toBe('BG-COPY-TEST');const copyKey=await p.evaluate(()=>db.quote.workspaceKey);
    await tab('pricing');await p.locator('[data-pa=policy]').click();await p.locator('[name=customer]').fill('8');await submit();await p.locator('[data-action=quote-list]').click();const original=await p.evaluate(()=>db.savedQuotes.find(x=>x.key!==db.quote.workspaceKey&&x.quote.id==='BG-DEMO-0912').key);await p.locator(`[data-work=open-quote][data-id="${original}"]`).click();expect(await p.evaluate(()=>db.quote.pricing.customer)).toBe(0);check('Quote copies and switching preserve independent pricing snapshots');
    await tab('preview');await p.locator('[data-action=approve]').click();await submit();await p.locator('[data-action=history]').click();await p.locator('[data-work=view-version]').click();await expect(p.locator('#dialog .paper')).toContainText('BẢNG CHÀO GIÁ');await close();expect(await p.evaluate(()=>db.quote.id)).toBe('BG-DEMO-0912');check('Approved local history opens read-only without replacing active quote');
    const dl=p.waitForEvent('download');await p.locator('[data-work=export-customer-xlsx]').click();await (await dl).saveAs(path.join(folder,'khach.xlsx'));
    await p.locator('[data-work=export-workbook]').first().click();const dl2=p.waitForEvent('download');await submit();await (await dl2).saveAs(path.join(folder,'noi-bo.xlsx'));check('Separate genuine XLSX downloads for customer and internal costing');
    await p.setViewportSize({width:390,height:844});for(const name of ['operations','logistics','pricing','preview']){await tab(name);expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);}await tab('logistics');await p.screenshot({path:path.join(folder,'02-mobile.png'),fullPage:true});check('New business screens fit mobile without document overflow');
    await p.setViewportSize({width:1440,height:1050});await tab('bom');await p.locator('[data-work=new-quote]').click();await p.locator('[name=id]').fill('BG-NEW-TEST');await p.locator('[name=customer]').fill('Khách mới');await p.locator('[name=project]').fill('Công trình thử');await submit();expect(await p.evaluate(()=>db.quote.products.length)).toBe(0);await p.reload();expect(await p.evaluate(()=>db.quote.id)).toBe('BG-NEW-TEST');check('New empty quotes and quote archive survive reload');
    const app=createApp();server=app.server;await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;
    const team=await browser.newPage({viewport:{width:1440,height:1050}});team.on('pageerror',e=>errors.push(e.message));await team.goto(url);await team.locator('#team-entry').click();await team.locator('[name=username]').fill('admin');await team.locator('[name=name]').fill('Quản trị thử');await team.locator('[name=password]').fill('Only-for-browser-tests-42!');await team.locator('#dialog button[type=submit]').click();await expect(team.locator('#dialog-title')).toHaveText('Báo giá dùng chung trên máy chủ');
    await team.locator('#dialog [data-team=save]').click();await expect(team.locator('.team-banner')).toContainText('Phiên bản 1');await team.locator('[data-team=submit]').click();await team.locator('#dialog button[type=submit]').click();await expect(team.locator('.team-banner')).toContainText('Chờ duyệt');await team.locator('.team-banner [data-team=approve]').click();await team.locator('#dialog button[type=submit]').click();await expect(team.locator('.team-banner')).toContainText('Đã duyệt');check('Real server setup → save → submit → approve succeeds in browser');
    await team.locator('[data-team=order]').click();await team.locator('[name=code]').fill('DH-BROWSER-001');const orderDownload=team.waitForEvent('download');await team.locator('#dialog button[type=submit]').click();const orderFile=path.join(folder,'don-hang-NOI-BO.json');await (await orderDownload).saveAs(orderFile);const order=JSON.parse(fs.readFileSync(orderFile,'utf8'));expect(order.baseline.grand).toBe(7126053);expect(order.quoteVersion).toBe(3);expect(order.status).toBe('awaiting-production');check('Approved quotation creates a downloadable order baseline through the real button');
    await team.locator('[data-action=quote-info]').click();await team.locator('[name=project]').fill('Must not alter approved document');await team.locator('#dialog button[type=submit]').click();expect(await team.evaluate(()=>db.quote.project)).not.toBe('Must not alter approved document');check('Approved server document cannot be edited through ordinary form');
    await team.locator('[data-team=reopen]').click();await team.locator('[name=reason]').fill('Thử phiên bản sửa');await team.locator('#dialog button[type=submit]').click();await expect(team.locator('.team-banner')).toContainText('Nháp');await team.locator('[data-action=quote-info]').click();await team.locator('[name=project]').fill('SERVER-ONLY-PRIVATE-TEST');await team.locator('#dialog button[type=submit]').click();await team.locator('.team-banner [data-team=save]').click();await expect(team.locator('.team-banner')).toContainText('Phiên bản 5');expect(await team.evaluate(()=>localStorage.getItem(STORE).includes('SERVER-ONLY-PRIVATE-TEST'))).toBe(false);check('Remote edits are saved on server, not leaked into localStorage');
    await team.locator('[data-action=history]').click();await expect(team.locator('#dialog tbody tr')).toHaveCount(5);await team.locator('#dialog .dialog-head [data-action=close]').click();await team.screenshot({path:path.join(folder,'03-may-chu.png'),fullPage:true});
    await team.locator('.team-banner [data-team=list]').click();await team.locator('[data-team=logout]').click();await expect(team.locator('.team-banner')).toHaveCount(0);await expect(team.locator('#team-entry')).toContainText('Đăng nhập');check('Logout returns to local workspace and clears server session');
    expect(errors).toEqual([]);check('No runtime errors in tested local and server flows');fs.writeFileSync(path.join(folder,'browser-results.json'),JSON.stringify({passed,errors},null,2));
  }catch(e){await p.screenshot({path:path.join(folder,'failure.png'),fullPage:true});console.error('Runtime errors:',errors);throw e;}
  finally{await browser.close();if(server)await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
