const {test}=require('node:test'),A=require('node:assert/strict'),{createApp}=require('../server/app.cjs'),P=require('../pricing-core.js');
test('assignment validates rights, routes confirmed work, persists status independently and rejects stale updates',async t=>{
 const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port;
 const call=async(route,method='GET',body,session)=>{const r=await fetch(base+'/api/'+route,{method,headers:{'Content-Type':'application/json',...(session?{Cookie:session.cookie,'X-CSRF-Token':session.csrf}:{})},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};};
 const password='Assignment-Local-Only-42!',admin=await call('setup','POST',{username:'admin',name:'Admin',password}),users={},sessions={};
 for(const [name,role,sections]of [['tech1','technical',['bom','operations']],['tech2','technical',['bom']],['price1','estimator',['materials']],['price2','estimator',['materials']]]){users[name]=(await call('users','POST',{username:name,name,role,sections,password},admin)).data;sessions[name]=await call('login','POST',{username:name,password});}
 const d=P.demoSeed();d.quote.remnantMode='all';const created=await call('quotes','POST',{document:d},admin);A.equal(created.status,201);const id=created.data.id,path='quotes/'+id,work=path+'/work',before=app.sql.prepare('SELECT * FROM quotes WHERE id=?').get(id);
 A.equal((await call(work)).status,401);A.equal((await call(work,'GET',undefined,admin)).data.status,'not-started');A.equal((await call(work,'GET',undefined,sessions.tech1)).data.canEdit,false);
 const update={expectedRevision:0,technicalId:users.tech1.id,materialsId:users.price1.id,status:'in-progress'};
 A.equal((await call(work,'PUT',update,sessions.tech1)).status,403);A.equal((await call(work,'PUT',{...update,technicalId:users.price1.id},admin)).status,400);A.equal((await call(work,'PUT',{...update,status:'bad'},admin)).status,400);
 A.equal((await call(work,'PUT',update,admin)).status,200);A.equal((await call(work,'PUT',update,admin)).status,409);A.equal((await call(path+'/handoff/intake','POST',{expectedVersion:1},admin)).data.recipients,1);
 const inbox=async who=>(await call('notifications','GET',undefined,sessions[who])).data.items;
 A.equal((await inbox('tech1')).filter(n=>n.stage==='intake').length,1);A.equal((await inbox('tech2')).filter(n=>n.stage==='intake').length,0);
 const technical=await call(path+'/handoff/technical','POST',{expectedVersion:1},sessions.tech1);A.equal(technical.status,200,JSON.stringify(technical.data));A.equal(technical.data.recipients,2);A.equal((await inbox('price1')).filter(n=>n.stage==='technical').length,1);A.equal((await inbox('price2')).length,0);
 A.equal((await call(work,'PUT',{...update,expectedRevision:1,materialsId:users.price2.id,status:'completed'},admin)).status,200);const state=(await call(path+'/handoff','GET',undefined,admin)).data;A.equal(state.technical.current,true);A.equal(state.work.status,'completed');A.equal((await call(path+'/handoff/technical','POST',{expectedVersion:1},sessions.tech1)).data.duplicate,false);A.equal((await inbox('price2')).length,1);A.equal((await call(path+'/handoff/technical','POST',{expectedVersion:1},sessions.tech1)).data.duplicate,true);
 await call('users/'+users.price2.id+'/disable','POST',{},admin);A.equal((await call(path+'/handoff/technical','POST',{expectedVersion:1},sessions.tech1)).status,422);
 A.equal((await call(work,'PUT',{...update,expectedRevision:2,status:'cancelled'},admin)).status,200);const list=(await call('quotes','GET',undefined,sessions.tech1)).data;A.equal(list[0].progress.work.status,'cancelled');A.equal(list[0].progress.work.technical.name,'tech1');A.equal(list[0].total,undefined);
 const after=app.sql.prepare('SELECT * FROM quotes WHERE id=?').get(id);A.equal(after.document,before.document);A.equal(after.version,before.version);A.equal(after.status,'draft');A.equal(after.total,before.total);
 const backup=(await call('backup','GET',undefined,admin)).data;A.equal(JSON.parse(backup.handoffs.find(x=>x.quote_id===id).document).work.status,'cancelled');A.equal(backup.audit.filter(x=>x.action==='quote:work').length,3);
});
