'use strict';
const {test}=require('node:test'),A=require('node:assert/strict'),{randomUUID}=require('node:crypto'),{createApp}=require('../server/app.cjs'),P=require('../pricing-core.js');
async function fixture(t){const app=createApp();await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));let admin;const call=async(path,method='GET',body,s=admin)=>{const r=await fetch('http://127.0.0.1:'+app.server.address().port+'/api/'+path,{method,headers:{'Content-Type':'application/json',Cookie:s?.cookie||'','X-CSRF-Token':s?.csrf||''},body:body===undefined?undefined:JSON.stringify(body)}),data=await r.json();return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],csrf:data.csrf};};admin=await call('setup','POST',{username:'admin',name:'Admin',password:'Work-board-2026!'});admin.id=admin.data.user.id;const user=async(name,rights)=>{const u=(await call('users','POST',{username:name,name,role:'sales',password:'Work-board-2026!'})).data;app.sql.prepare('UPDATE users SET action_access=? WHERE id=?').run(JSON.stringify(rights),u.id);return {...await call('login','POST',{username:name,password:'Work-board-2026!'}),id:u.id};};const post=(part,b,s=admin)=>call('enterprise/work/'+part,'POST',{requestId:randomUUID(),...b},s),ok=async(part,b,s)=>{const r=await post(part,b,s);A.equal(r.status,200,JSON.stringify(r.data));return r.data;};return {app,admin,call,user,post,ok};}
const task=(who,extra={})=>({name:'Inspect',assignee:who,startDate:'2026-09-25',dueDate:'2026-09-26',plannedHours:8,plannedOutput:0,unit:'chi tiết',expectedVersion:0,...extra});
test('work hierarchy scopes assignments, department claims, approvals, exports data and old endpoints',async t=>{
 const f=await fixture(t),m=await f.user('manager',{dailyWork:['view','assign','approve','edit']}),w=await f.user('worker',{dailyWork:['view','edit']}),w2=await f.user('worker2',{dailyWork:['view','edit']}),other=await f.user('other',{dailyWork:['view','assign','approve','edit']});
 const org={departments:[{id:'parent',name:'Parent',active:true},{id:'child',name:'Child',parentId:'parent',active:true},{id:'other',name:'Other',active:true}],positions:[{id:'manager',departmentId:'parent',manager:true,active:true},{id:'worker',departmentId:'child',manager:false,active:true},{id:'other',departmentId:'other',manager:true,active:true}],employees:[{id:m.id,userId:m.id,active:true,positionIds:['manager']},{id:w.id,userId:w.id,active:true,positionIds:['worker']},{id:w2.id,userId:w2.id,active:true,positionIds:['worker']},{id:other.id,userId:other.id,active:true,positionIds:['other']}]};f.app.sql.prepare('INSERT INTO organization VALUES(1,1,?)').run(JSON.stringify(org));
 A.equal((await f.post('task',task(other.id),m)).status,403);let x=await f.ok('task',task(w.id,{departmentId:'child'}),m);A.equal((await f.call('enterprise/work','GET',undefined,other)).data.tasks.length,0);A.equal((await f.call('ops/state','GET',undefined,other)).data.tasks.length,0);A.equal((await f.post('task',{...x,expectedVersion:x.version,name:'Steal',assignee:other.id},other)).status,403);
 let dept=await f.ok('task',task('',{name:'Department task',departmentId:'child'}),m);const b={id:dept.id,expectedVersion:dept.version,state:'accepted'},claims=await Promise.all([f.post('transition',b,w),f.post('transition',b,w2)]);A.equal(claims.filter(r=>r.status===200).length,1);A.ok(claims.some(r=>[404,409].includes(r.status)));dept=claims.find(r=>r.status===200).data;A.ok([w.id,w2.id].includes(dept.assignee));
 for(const state of ['accepted','running'])x=await f.ok('transition',{id:x.id,expectedVersion:x.version,state},w);
 const report=await f.ok('report',{taskId:x.id,expectedVersion:x.version,date:'2026-09-25',hours:2,output:3,content:'Measured',issue:'Missing part',proposal:'Purchase'},w);
 A.equal((await f.call('ops/resolve','POST',{requestId:randomUUID(),id:report.id,resolution:'Bypass'},other)).status,403);A.equal((await f.post('transition',{id:x.id,expectedVersion:x.version,state:'done'},w)).status,409);
 await f.ok('resolve',{taskId:x.id,reportId:report.id,expectedVersion:x.version,resolution:'Part supplied'},m);x=await f.ok('transition',{id:x.id,expectedVersion:x.version,state:'done'},w);A.equal((await f.post('transition',{id:x.id,expectedVersion:x.version,state:'confirmed'},other)).status,404);x=await f.ok('transition',{id:x.id,expectedVersion:x.version,state:'confirmed'},m);
 const data=(await f.call('enterprise/work','GET',undefined,m)).data,r=data.tasks.find(t=>t.id===x.id);A.equal(r.output,3);A.equal(r.hours,2);A.equal(r.openIssues,0);A.equal(r.departmentId,'child');A.equal(data.people.find(p=>p.id===other.id).assignable,false);
});
test('parent tasks wait for children, quantity, issue resolution and preserve report units',async t=>{const f=await fixture(t);let parent=await f.ok('task',task(f.admin.id,{name:'Parent',plannedOutput:2})),child=await f.ok('task',task(f.admin.id,{parentId:parent.id,name:'Child'}));A.equal((await f.post('task',{...parent,parentId:child.id,expectedVersion:parent.version})).status,400);for(const state of ['accepted','running'])parent=await f.ok('transition',{id:parent.id,expectedVersion:parent.version,state});A.equal((await f.post('transition',{id:parent.id,expectedVersion:parent.version,state:'done'})).status,409);for(const state of ['accepted','running','done','confirmed'])child=await f.ok('transition',{id:child.id,expectedVersion:child.version,state});A.equal((await f.post('transition',{id:parent.id,expectedVersion:parent.version,state:'done'})).status,409);const b={requestId:randomUUID(),taskId:parent.id,expectedVersion:parent.version,date:'2026-09-25',hours:1,output:2,content:'Complete'};const r=await f.ok('report',b);A.deepEqual(await f.ok('report',b),r);A.equal((await f.post('task',{...parent,expectedVersion:parent.version,unit:'kg'})).status,409);parent=await f.ok('transition',{id:parent.id,expectedVersion:parent.version,state:'done'});A.equal((await f.call('enterprise/work')).data.tasks.find(t=>t.id===parent.id).progress,100);});
test('production tasks follow actual workflow without duplicate task writes or source status edits',async t=>{
 const f=await fixture(t),d=P.demoSeed();d.quote.products=[d.quote.products[0]];d.quote.products[0].qty=1;d.quote.remnantMode='all';d.quote.remnantSelections={};const q=(await f.call('quotes','POST',{document:d})).data;await f.call('quotes/'+q.id+'/submit','POST',{expectedVersion:1});await f.call('quotes/'+q.id+'/approve','POST',{expectedVersion:2});const o=(await f.call('quotes/'+q.id+'/order','POST',{expectedVersion:3,code:'WB-ORDER'})).data;await f.call('orders/'+o.id+'/confirm','POST',{quoteVersion:3});let j=(await f.call('production','POST',{orderId:o.id,productId:d.quote.products[0].id,quantity:1,code:'WB-JOB'})).data;
 A.ok(j.id,JSON.stringify(j));j=await require('./production-review-fixture.cjs').review(f.call,f.admin,j.id);await require('./ops-fixture.cjs').seedStock(f.call,f.admin,j.id);j=await require('./production-flow-fixture.cjs').approveRoute(f.call,f.admin,j.id);j=await require('./production-review-fixture.cjs').review(f.call,f.admin,j.id);j=(await f.call('production/'+j.id,'PUT',{action:'prepare',expectedVersion:j.version,drawingReady:true,materialsReady:true,workshop:'A',deadline:'2026-09-26',note:''})).data;const op=j.packet.operations[0];
 j=(await f.call('production/'+j.id,'PUT',{action:'operation',expectedVersion:j.version,operationId:op.id,status:'running',assignee:f.admin.id,machine:'Manual',hours:2,output:0,note:'Started',issue:'Blade check',proposal:'Inspect blade'})).data;
 let s=(await f.call('enterprise/work')).data;const source=s.tasks.find(t=>t.source?.operationId===op.id);A.equal(source.state,'running');A.equal(source.hours,2);A.equal(source.issue,'Blade check');A.equal((await f.post('transition',{id:source.id,expectedVersion:source.version,state:'done'})).status,409);
 A.equal((await f.call('enterprise/work')).data.tasks.filter(t=>t.id===source.id).length,1);A.equal(f.app.sql.prepare("SELECT COUNT(*) n FROM ops_records WHERE kind='task'").get().n,0);
 j=await require('./production-flow-fixture.cjs').settleStage(f.call,f.admin,j.id);s=(await f.call('enterprise/work')).data;A.equal(s.tasks.find(t=>t.id===source.id).state,'confirmed');A.equal(s.tasks.find(t=>t.id===source.id).output,op.quantity);
 const limited=await f.user('limited',{dailyWork:['view','assign','approve']});A.equal((await f.call('enterprise/work','GET',undefined,limited)).data.tasks.filter(t=>t.sourceManaged).length,0);
});
test('offer and purchasing projections track source transitions and never expose commercial amounts',async t=>{const f=await fixture(t),q=(await f.call('quotes','POST',{document:P.demoSeed()})).data;await f.call('quotes/'+q.id+'/submit','POST',{expectedVersion:1});await f.call('quotes/'+q.id+'/approve','POST',{expectedVersion:2});const row=f.app.sql.prepare('SELECT * FROM commercial WHERE id=?').get(q.id),doc=JSON.parse(row.document);doc.dispatches[3]={senderId:f.admin.id,careOwnerId:f.admin.id,sentAt:new Date().toISOString(),dueDate:'2026-09-26',careClosed:true,entries:[{kind:'close',content:'Done'},{kind:'assignment',content:'Keep owner'}]};doc.dispatches[1]={senderId:f.admin.id,entries:[]};f.app.sql.prepare('UPDATE commercial SET document=? WHERE id=?').run(JSON.stringify(doc),q.id);f.app.sql.prepare('INSERT INTO ops_records VALUES(?,?,?,?)').run('purchase','test-purchase',1,JSON.stringify({code:'PURCHASE',actor:f.admin.id,created:new Date().toISOString(),state:'ordered',lines:[{unitCost:999999}]}));let tasks=(await f.call('enterprise/work')).data.tasks;A.equal(tasks.find(t=>t.id==='source:offer:'+q.id+':3:care').state,'confirmed');A.equal(tasks.some(t=>t.id==='source:offer:'+q.id+':1:send'),false);const purchase=tasks.find(t=>t.id==='source:purchase:test-purchase');A.equal(purchase.state,'running');A.equal(JSON.stringify(purchase).includes('999999'),false);f.app.sql.prepare('UPDATE ops_records SET document=?,version=2 WHERE kind=? AND id=?').run(JSON.stringify({code:'PURCHASE',actor:f.admin.id,created:new Date().toISOString(),state:'stocked'}),'purchase','test-purchase');tasks=(await f.call('enterprise/work')).data.tasks;A.equal(tasks.find(t=>t.id===purchase.id).state,'confirmed');});
test('successor waits for confirmed predecessor, not save or completion; notification and dependency cycles',async t=>{
 const f=await fixture(t);let a=await f.ok('task',task(f.admin.id,{name:'First'})),b=await f.ok('task',task(f.admin.id,{name:'Next',predecessorId:a.id}));
 A.equal((await f.post('task',{...a,predecessorId:b.id,expectedVersion:a.version})).status,400);
 b=await f.ok('transition',{id:b.id,state:'accepted',expectedVersion:b.version});
 A.equal((await f.post('transition',{id:b.id,state:'running',expectedVersion:b.version})).status,409);
 for(const state of ['accepted','running','done'])a=await f.ok('transition',{id:a.id,state,expectedVersion:a.version});
 A.equal((await f.post('transition',{id:b.id,state:'running',expectedVersion:b.version})).status,409);
 a=await f.ok('transition',{id:a.id,state:'confirmed',expectedVersion:a.version});
 const view=(await f.call('enterprise/work')).data;A.ok(view.notices.some(n=>n.taskId===b.id&&n.title.includes('Sẵn sàng')));A.equal(view.tasks.find(t=>t.id===b.id).blocked,false);
 b=await f.ok('transition',{id:b.id,state:'running',expectedVersion:b.version});
 const report=await f.ok('report',{taskId:b.id,expectedVersion:b.version,date:'2026-09-26',hours:1,output:1,content:'Working',issue:'Waiting'});
 await f.ok('resolve',{taskId:b.id,expectedVersion:b.version,reportId:report.id,resolution:'Ready'});
 A.ok((await f.call('enterprise/work')).data.notices.some(n=>n.taskId===b.id&&n.title.includes('Đã xử lý')));
});
