// End-to-end customer work, not just individual controls.
const {chromium,expect}=require('@playwright/test'),fs=require('node:fs'),path=require('node:path');
(async()=>{
  const fallback=path.join(process.env.LOCALAPPDATA||'','ms-playwright','chromium-1228','chrome-win64','chrome.exe');
  const browser=await chromium.launch({headless:true,...(fs.existsSync(fallback)?{executablePath:fallback}:{})});
  const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  p.on('pageerror',e=>errors.push(e.message));const submit=()=>p.locator('#dialog button[type=submit]').click();
  const commit=async(locator,value)=>{await locator.fill(String(value));await locator.press('Tab');};
  await p.goto('http://127.0.0.1:4173');
  await p.getByRole('button',{name:'Tạo biến thể',exact:true}).click();
  for(const [key,value]of Object.entries({L:1800,W:400,H:100,qty:5}))await p.locator('#dialog [name='+key+']').fill(String(value));
  await submit();const product=p.locator('.quick-product').last();
  await product.getByRole('button',{name:'+ Cấu kiện',exact:true}).click();
  await p.getByRole('textbox',{name:'Tên cấu kiện',exact:true}).fill('Giá đỡ bổ sung');
  await p.getByRole('spinbutton',{name:'Số cấu kiện trong 1 sản phẩm'}).fill('2');await submit();
  await expect(p.locator('#dialog-title')).toContainText('Giá đỡ bổ sung');
  await expect(p.locator('.picker-target')).toContainText('10 đơn vị');
  await p.locator('#pick-search').fill('PH-H402');await p.locator('[data-basket-id="PH-H402"]').check();
  await commit(p.locator('[data-basket-qty="PH-H402"]'),2);
  await p.locator('#pick-search').fill('LK-M8');await p.locator('[data-basket-id="LK-M8"]').check();
  await commit(p.locator('[data-basket-qty="LK-M8"]'),4);await submit();
  const component=product.locator('tbody tr').filter({hasText:'Giá đỡ bổ sung'});
  await expect(component).toContainText('2 thành phần');
  const bar=product.locator('tbody tr').filter({hasText:'PH-H402'});
  await expect(bar.locator('[data-qtotal]')).toHaveText('Tổng: 20');
  await commit(bar.locator('[data-qkey=L]'),500);
  await expect(bar.locator('.calc-col')).toContainText('500');
  await expect(bar.locator('.fixed-value')).toHaveCount(2);
  await p.getByRole('textbox',{name:'Tìm trong cấu thành'}).fill('giá đỡ bổ sung');
  await expect(p.locator('.quick-product')).toHaveCount(1);
  await expect(p.locator('.quick-row')).toHaveCount(3);
  await expect(p.locator('.quick-row').filter({hasText:'PH-H402'}).locator('[data-qkey=L]')).toHaveValue('500');
  await p.locator('[data-check-product]').check();
  await p.getByRole('button',{name:'Gán nguyên công',exact:true}).click();
  await p.locator('#dialog [name=op]').selectOption('cut');await p.locator('#dialog [name=mode]').selectOption('outside');await submit();
  await expect(p.locator('.quick-row').filter({hasText:'Giá đỡ bổ sung'})).toContainText('1 nguyên công');
  await p.getByRole('button',{name:'Xóa tìm kiếm',exact:true}).click();
  // Direct action on the component is always visible, including after cancelling the next step.
  await product.locator('tr').filter({hasText:'Giá đỡ bổ sung'}).getByRole('button',{name:'Thêm vật tư vào Giá đỡ bổ sung',exact:true}).click();
  await expect(p.locator('#dialog-title')).toContainText('Giá đỡ bổ sung');
  await p.locator('#pick-search').fill('PH-T20');await p.locator('[data-basket-id="PH-T20"]').check();
  const destinationBefore=await p.locator('#picker-target').inputValue();
  await p.locator('#picker-target').selectOption({index:0});
  await expect(p.locator('#basket-summary')).toContainText('1 mã');
  await p.locator('#picker-target').selectOption(destinationBefore);await expect(p.locator('#basket-summary')).toContainText('1 mã');
  await p.locator('#dialog [data-action=close]').first().click();
  // Ambiguous numbers block import, then explicit locale produces visible, normalized dimensions.
  await product.getByRole('button',{name:'Dán từ Excel',exact:true}).click();
  await p.locator('#excel-paste').fill('PH-T15\t2\t1.800\t400\nVP-GIOANG\t0,6');await submit();
  await expect(p.locator('#dialog-error')).toContainText('hai cách hiểu');
  await p.locator('[name=numberFormat]').selectOption('vi');
  await expect(p.locator('.paste-preview-table tbody tr').first()).toContainText('1.800');
  await expect(p.locator('.paste-preview-table tbody tr').last()).toContainText('0,6');
  await p.screenshot({path:'artifacts/nhap-excel-da-kiem-tra.png'});
  await submit();await expect(product.locator('tbody tr').nth(-2).locator('[data-qkey=L]')).toHaveValue('1800');
  await expect(p.locator('#quick-errors')).toBeEmpty();
  // Search by material keeps ancestors, but bulk selection excludes context-only rows.
  await p.locator('#quick-search').fill('PH-H402');
  const contextChecks=await p.locator('.search-context [data-check-id]').all();
  expect(contextChecks.length).toBeGreaterThan(0);
  for(const checkbox of contextChecks)await expect(checkbox).toBeDisabled();
  for(const selectAll of await p.locator('[data-check-product]').all())await selectAll.check();
  expect(await p.evaluate(()=>selectedTopNodes().every(n=>n.kind==='material'))).toBe(true);
  await p.getByRole('button',{name:'Xóa tìm kiếm',exact:true}).click();
  // Four cost groups and quantity-aware row changes, then client-facing export.
  await p.getByRole('tab').filter({hasText:'Phân tích giá'}).click();
  const before=await p.evaluate(()=>result.total.transport);
  const costRow=p.locator('.cost-matrix tbody tr').filter({hasText:'Giá đỡ bổ sung'});
  await commit(costRow.locator('[data-node-cost=transport]'),1000);
  expect(await p.evaluate(()=>result.total.transport)).toBe(before+10000);
  await expect(costRow.locator('[data-price-part=ownTransport]')).toHaveText('10.000');
  await p.getByRole('tab').filter({hasText:'Bản chào giá'}).click();
  await expect(p.locator('.paper')).toContainText('Máng cáp 400 × 100, dài 1.800 mm');
  await expect(p.locator('.paper')).not.toContainText('Biên lợi nhuận');
  await p.evaluate(()=>{window.print=()=>{window.didPrint=true;};});
  await p.locator('[data-action=print]').click();
  expect(await p.evaluate(()=>window.didPrint)).toBe(true);
  await p.pdf({path:'artifacts/bao-gia-sau-kiem-thu-luong.pdf',format:'A4',printBackground:true});
  const downloadPromise=p.waitForEvent('download');await p.locator('[data-action=export-quote]').click();
  const download=await downloadPromise,csv=fs.readFileSync(await download.path(),'utf8');
  expect(csv).toContain('L 1800 × W 400 × H 100 mm');expect(csv).not.toContain('Biên lợi nhuận');
  const grand=await p.evaluate(()=>result.total.grand);await p.reload();expect(await p.evaluate(()=>result.total.grand)).toBe(grand);
  await p.setViewportSize({width:390,height:844});
  await p.locator('.quick-product').last().getByRole('button',{name:'Dán từ Excel',exact:true}).click();
  await p.locator('#excel-paste').fill('PH-T15\t1\t1,800.5\t400');
  await expect(p.locator('.paste-preview-table tbody tr')).toContainText('1.800,5');
  expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
  await p.screenshot({path:'artifacts/nhap-excel-mobile.png'});await p.locator('#dialog [data-action=close]').first().click();
  expect(errors).toEqual([]);
  await browser.close();console.log('Workflow passed: variant → component → materials → dimensions → search/bulk → locale-aware paste → costs → PDF/CSV → persistence/mobile.');
})().catch(e=>{console.error(e);process.exit(1);});
