'use strict';
const C=require('../core.js'),P=require('../pricing-core.js');
const ROLES=['admin','estimator','approver','sales','technical'];
const SA=require('../section-access.js');
function basePermissions(user){
 if(typeof user==='string')user={role:user};
 const sectionModes=SA.modes(user),viewSections=SA.keys.filter(k=>sectionModes[k]!=='none');
 if(user?.role==='technical'&&!(user.technical_delegated&&user.can_view_costs)){const safe=require('../technical-core.js').catalogSections,sections=SA.sections(user).filter(k=>['customer','bom','operations',...(user.technical_delegated?safe:[])].includes(k));return {sectionModes,viewSections,catalogRead:(user.role!=='technical'||!!user.technical_delegated)&&viewSections.some(k=>SA.catalogKeys.includes(k)),...require('./formula-access.cjs').rights(user,sections),technical:true,edit:sections.some(k=>!safe.includes(k)),approve:false,users:false,catalog:sections.some(k=>safe.includes(k)),costs:false,sections,factors:false,belowCost:false,manage:false,commercial:false};}
 const role=user.role,sections=SA.sections(user),costs=role==='admin'||(user.can_view_costs==null?role!=='sales':!!user.can_view_costs),edit=costs&&['admin','estimator','technical'].includes(role)&&sections.some(k=>!SA.catalogKeys.includes(k)),approve=costs&&(user.can_approve==null?['admin','approver'].includes(role):!!user.can_approve);
 return {sectionModes,viewSections,catalogRead:(user.role!=='technical'||!!user.technical_delegated)&&viewSections.some(k=>SA.catalogKeys.includes(k)),...require('./formula-access.cjs').rights(user,sections),customers:sections.includes('customer')&&(edit||role==='sales'),edit,approve,users:role==='admin',catalog:costs&&sections.some(k=>SA.catalogKeys.includes(k)),costs,sections,factors:costs&&sectionModes.factors==='configure'&&sections.includes('factors')&&(user.can_factors==null?['admin','estimator'].includes(role):!!user.can_factors),belowCost:approve&&(user.can_below_cost==null?role==='admin':!!user.can_below_cost),manage:edit&&sections.includes('manage'),commercial:sections.includes('commercial')&&(costs||role==='sales')};
}

function permissions(user){const p=basePermissions(user),A=require('../action-access.js');if(A.explicit(user)&&user.role!=='admin'){p.edit&&=A.allows(user,'quotes','edit');p.manage&&=A.allows(user,'quotes','create')||A.allows(user,'quotes','submit');p.approve&&=A.allows(user,'quotes','approve');p.reopen&&=A.allows(user,'quotes','reopen');p.belowCost&&=p.approve;p.customers=p.sectionModes.customer!=='none'&&A.allows(user,'customers','view');}return {...p,actionAccess:A.explicit(user)?A.parse(user.action_access??user.actionAccess):null};}
const FACTOR_KEYS=['factorSuggestions','suggestionCustomerType','costSequence','overhead','management','special','profit','processing','order','reserve','customer','salesFactors','productionFactors','tmcLoss','tmcTables','tmcLaborOperation','productGroups','costFlows','operationPriceTables'];
// Per-job complexity is a technical declaration governed by the operations section.
// Commercial factors and shared rate tables remain protected here.
function factorFingerprint(document){const p={...P.defaults(),...document.quote.pricing};return JSON.stringify({productSpecials:(document.quote.products||[]).filter(n=>n.productionSpecialPercent!==undefined&&n.productionSpecialPercent!==null).map(n=>({id:n.id,percent:n.productionSpecialPercent})),deviceFactors:(document.quote.deviceInstallations||[]).filter(e=>e.mode==='percent').map(e=>({id:e.id,rate:Number(e.rate)})),expenseFactors:(document.quote.expenses||[]).filter(e=>e.factors?.length).map(e=>({id:e.id,factors:e.factors})),tmcPolicy:p.tmcPolicy||null,pricing:Object.fromEntries(FACTOR_KEYS.map(k=>[k,k==='costSequence'?(document.quote.pricing?.costSequence||'legacy'):p[k]])),rates:document.quote.ratesSnapshot.map(r=>({id:r.id,productGroups:r.productGroups||[],factorsEnabled:r.factorsEnabled!==false,factors:r.factors||[],outsideFactors:!!r.outsideFactors,priceOptionFactors:(r.priceOptions||[]).map(x=>({id:x.id,method:x.method,outsideFactors:!!x.outsideFactors}))})).sort((a,b)=>a.id.localeCompare(b.id))});}
function specification(n,q,result){const nodes=C.flatten([n]),texts=[n.requestSpecification,C.quoteSpecification(n)];texts.push(...nodes.filter(n=>n.kind==='material'&&n.spec.shape!=='piece').map(n=>[n.spec.substance,n.spec.grade,n.spec.props?.T?'dày '+n.spec.props.T+' mm':''].filter(Boolean).join(' ')));texts.push(...nodes.flatMap(n=>(n.ops||[]).filter((op,i)=>!result.nodes[n.id]?.ownOps?.[i]?.skipped).map(op=>q.ratesSnapshot.find(r=>r.id===op.id)).filter(r=>r&&(r.finishing||r.consumption||r.consumptions?.length||r.id==='galvanize')).map(r=>r.name)));texts.push(...nodes.filter(n=>result.nodes[n.id]?.packageOwner).map(n=>n.outsource.output));return [...new Set(texts.filter(Boolean))].join('; ');}
function publicOffer(document,result){const q=document.quote;return {code:q.id,documentMode:q.documentMode||'working',taxConfirmed:!!result.tax&&!result.tax.releaseErrors.length,offerTerms:require('../offer-terms-core.js').publicTerms(q),termsConfirmed:!require('../offer-terms-core.js').errors(q).length,customer:q.customer,customerInfo:q.customerInfo&&q.customerInfo.name===q.customer?{name:q.customerInfo.name,contact:q.customerInfo.contact,phone:q.customerInfo.phone,email:q.customerInfo.email,address:q.customerInfo.address,taxId:q.customerInfo.taxId}:undefined,project:q.project,date:q.date,valid:q.valid,notes:q.notes,vatRate:q.outputTax?.scope==='product'?null:q.vat,taxBreakdown:result.total.taxBreakdown,issuer:q.issuer?{name:q.issuer.name,address:q.issuer.address,phone:q.issuer.phone,email:q.issuer.email,taxId:q.issuer.taxId,signer:q.issuer.signer}:undefined,products:result.products.map(p=>({name:p.node.name,specification:specification(p.node,q,result),unit:p.node.unit||'bộ',qty:p.node.qty,unitPrice:p.unitSell,total:p.sell,vatRate:require('../tax-core.js').outputRate(q,p.node)})),totals:{beforeTax:result.total.beforeTax,vat:result.total.vat,grand:result.total.grand}};}
function catalogSeed(){const d=P.demoSeed();return {shapeDefinitions:d.shapeDefinitions||[],stockSizes:d.stockSizes||[],conventions:d.conventions||{},materialPrices:d.materialPrices||[],materials:d.materials,rates:d.rates,rules:d.rules,library:d.library,pricingDefaults:P.defaults()};}
module.exports={ROLES,permissions,FACTOR_KEYS,factorFingerprint,publicOffer,catalogSeed};
