'use strict';
const C=require('../core.js'),P=require('../pricing-core.js');
const ROLES=['admin','estimator','approver','sales'];
function permissions(user){if(typeof user==='string')user={role:user};const role=user.role;return {edit:['admin','estimator'].includes(role),approve:['admin','approver'].includes(role),users:role==='admin',catalog:role==='admin',costs:role!=='sales',factors:user.can_factors==null?['admin','estimator'].includes(role):!!user.can_factors,belowCost:user.can_below_cost==null?role==='admin':!!user.can_below_cost};}
const FACTOR_KEYS=['overhead','management','special','profit','processing','order','reserve','customer','salesFactors','tmcLoss','tmcTables'];
function factorFingerprint(document){const p={...P.defaults(),...document.quote.pricing};return JSON.stringify({pricing:Object.fromEntries(FACTOR_KEYS.map(k=>[k,p[k]])),rates:document.quote.ratesSnapshot.map(r=>({id:r.id,factors:r.factors||[],outsideFactors:!!r.outsideFactors})).sort((a,b)=>a.id.localeCompare(b.id))});}
function specification(n,q,result){const nodes=C.flatten([n]),texts=[n.requestSpecification,C.quoteSpecification(n)];texts.push(...nodes.filter(n=>n.kind==='material'&&n.spec.shape!=='piece').map(n=>[n.spec.substance,n.spec.grade,n.spec.props?.T?'dày '+n.spec.props.T+' mm':''].filter(Boolean).join(' ')));texts.push(...nodes.flatMap(n=>(n.ops||[]).filter((op,i)=>!result.nodes[n.id]?.ownOps?.[i]?.skipped).map(op=>q.ratesSnapshot.find(r=>r.id===op.id)).filter(r=>r&&(r.finishing||r.consumption||r.consumptions?.length||r.id==='galvanize')).map(r=>r.name)));texts.push(...nodes.filter(n=>result.nodes[n.id]?.packageOwner).map(n=>n.outsource.output));return [...new Set(texts.filter(Boolean))].join('; ');}
function publicOffer(document,result){const q=document.quote;return {code:q.id,customer:q.customer,customerInfo:q.customerInfo&&q.customerInfo.name===q.customer?{name:q.customerInfo.name,contact:q.customerInfo.contact,phone:q.customerInfo.phone,email:q.customerInfo.email,address:q.customerInfo.address,taxId:q.customerInfo.taxId}:undefined,project:q.project,date:q.date,valid:q.valid,notes:q.notes,vatRate:q.vat,issuer:q.issuer?{name:q.issuer.name,address:q.issuer.address,phone:q.issuer.phone,email:q.issuer.email,taxId:q.issuer.taxId,signer:q.issuer.signer}:undefined,products:result.products.map(p=>({name:p.node.name,specification:specification(p.node,q,result),unit:p.node.unit||'bộ',qty:p.node.qty,unitPrice:p.unitSell,total:p.sell})),totals:{beforeTax:result.total.beforeTax,vat:result.total.vat,grand:result.total.grand}};}
function catalogSeed(){const d=P.demoSeed();return {conventions:d.conventions||{},materialPrices:d.materialPrices||[],materials:d.materials,rates:d.rates,rules:d.rules,library:d.library,pricingDefaults:P.defaults()};}
module.exports={ROLES,permissions,FACTOR_KEYS,factorFingerprint,publicOffer,catalogSeed};
