'use strict';
const {randomUUID}=require('node:crypto'),SA=require('../section-access.js'),{ROLES}=require('./access.cjs');
function createAccounts({sql,fail,readBody,transaction,audit}){
 const columns=new Set(sql.prepare('PRAGMA table_info(users)').all().map(c=>c.name));for(const k of ['deleted_at','role_template_id'])if(!columns.has(k))sql.exec('ALTER TABLE users ADD COLUMN '+k+' TEXT');
 sql.exec('CREATE TABLE IF NOT EXISTS role_templates(id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE COLLATE NOCASE,version INTEGER NOT NULL,document TEXT NOT NULL)');
 const list=()=>sql.prepare('SELECT u.id,u.username,u.name,u.role,u.active,u.can_factors,u.can_below_cost,u.can_view_costs,u.can_approve,u.technical_delegated,u.section_access,u.can_formula_use,u.can_formula_view,u.can_formula_edit,u.can_formula_unlock,u.can_reopen,u.role_template_id,r.name AS role_label FROM users u LEFT JOIN role_templates r ON r.id=u.role_template_id WHERE u.deleted_at IS NULL ORDER BY u.username').all();
 function resolve(body){if(!body.roleTemplateId)return {...body,roleTemplateId:null};const r=sql.prepare('SELECT * FROM role_templates WHERE id=?').get(String(body.roleTemplateId));if(!r)fail(400,'Vai trò đã bị xóa; chọn lại');const {name,...defaults}=JSON.parse(r.document);return {...defaults,...body,role:defaults.role,roleTemplateId:r.id};}
 function validate(body){for(const k of Object.keys(require('./formula-access.cjs').FIELDS))if(Object.hasOwn(body,k)&&typeof body[k]!=='boolean')fail(400,'Quyền phải là bật/tắt');const name=String(body.name||'').trim(),role=body.role;if(!name||name.length>100||!ROLES.includes(role))fail(400,'Nhập tên vai trò và chọn loại quyền nền');let sections;try{sections=SA.parse(body.sections)||[];}catch(e){fail(400,e.message);}validateDelegation({...body,sections,technicalDelegation:true});return {...Object.fromEntries(Object.keys(require('./formula-access.cjs').FIELDS).filter(k=>Object.hasOwn(body,k)).map(k=>[k,!!body[k]])),name,role,sections,canViewCosts:role==='admin'||!!body.canViewCosts,canApprove:!!body.canApprove,canEditFactors:!!body.canEditFactors,canApproveBelowCost:!!body.canApproveBelowCost};}
 function validateDelegation(body){if(body.role==='technical'&&body.technicalDelegation===true&&!body.canViewCosts&&((SA.parse(body.sections)||[]).some(k=>!['customer','bom','operations',...require('../technical-core.js').catalogSections].includes(k))||body.canEditFactors||body.canApprove||body.canApproveBelowCost))fail(400,'Quyền giá, hệ số và duyệt cần quyền Xem chi phí nội bộ. Danh mục vật tư, công đoạn kỹ thuật, quy ước và thư viện mẫu có thể cấp riêng mà không mở giá.');}
 return {list,resolve,validateDelegation,async handle({req,route,user,rights,send}){
  const roleMatch=route.match(/^\/api\/roles(?:\/([a-f0-9-]+))?$/),profile=route.match(/^\/api\/users\/([a-f0-9-]+)\/(profile|delete)$/);if(!roleMatch&&!profile)return false;if(!rights.users)fail(403,'Chỉ quản trị được quản lý tài khoản và vai trò');
  if(roleMatch){const id=roleMatch[1];if(req.method==='GET'&&!id){send(200,sql.prepare('SELECT * FROM role_templates ORDER BY name').all().map(r=>({...JSON.parse(r.document),id:r.id,version:r.version})));return true;}
   const body=await readBody(req);const value=transaction(()=>{const old=id?sql.prepare('SELECT * FROM role_templates WHERE id=?').get(id):null;if(id&&!old)fail(404,'Không tìm thấy vai trò');if(old&&body.expectedVersion!==old.version)fail(409,'Vai trò đã đổi; tải lại trước khi lưu');
    if(req.method==='DELETE'&&id){if(sql.prepare('SELECT id FROM users WHERE role_template_id=? AND deleted_at IS NULL').get(id))fail(409,'Vai trò đang có tài khoản sử dụng; đổi vai trò tài khoản trước');sql.prepare('DELETE FROM role_templates WHERE id=?').run(id);audit(user,'delete-role',id,old.name);return {ok:true};}
    if(!(req.method==='POST'&&!id||req.method==='PUT'&&id))fail(405,'Phương thức không hỗ trợ');const d=validate(body);if(sql.prepare('SELECT id FROM role_templates WHERE name=? COLLATE NOCASE AND id<>?').get(d.name,id||''))fail(409,'Tên vai trò đã tồn tại');const key=id||randomUUID(),version=(old?.version||0)+1;sql.prepare('INSERT INTO role_templates VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,version=excluded.version,document=excluded.document').run(key,d.name,version,JSON.stringify(d));audit(user,old?'update-role':'create-role',key,d.name);return {...d,id:key,version};});send(req.method==='POST'?201:200,value);return true;
  }
  if(req.method!=='POST')fail(405,'Phương thức không hỗ trợ');const body=await readBody(req);transaction(()=>{const target=sql.prepare('SELECT * FROM users WHERE id=? AND deleted_at IS NULL').get(profile[1]);if(!target)fail(404,'Không tìm thấy tài khoản');
   if(profile[2]==='delete'){if(target.id===user.id)fail(400,'Không tự xóa tài khoản đang đăng nhập');if(body.confirmUsername!==target.username)fail(400,'Nhập đúng tài khoản để xác nhận xóa');sql.prepare('UPDATE users SET active=0,deleted_at=? WHERE id=?').run(new Date().toISOString(),target.id);audit(user,'delete-user',target.id,'Ẩn tài khoản; giữ lịch sử công việc');}
   else{const username=String(body.username||'').trim().toLowerCase(),name=String(body.name||'').trim();if(!/^[a-z0-9._-]{3,64}$/.test(username)||!name||name.length>100)fail(400,'Tài khoản 3–64 ký tự không dấu; họ tên tối đa 100 ký tự');if(sql.prepare('SELECT id FROM users WHERE username=? AND id<>?').get(username,target.id))fail(409,'Tài khoản đã tồn tại hoặc đã được dùng trong lịch sử');sql.prepare('UPDATE users SET username=?,name=? WHERE id=?').run(username,name,target.id);audit(user,'update-user',target.id,target.username+' → '+username);}
   sql.prepare('DELETE FROM sessions WHERE user_id=?').run(target.id);
  });send(200,{ok:true});return true;
 }};
}
module.exports={createAccounts};
