'use strict';
const {randomUUID}=require('node:crypto'),SA=require('../section-access.js'),{ROLES}=require('./access.cjs');
function createAccounts({sql,fail,readBody,transaction,audit}){
 let organization;const history=require('./access-history.cjs');history.setup(sql);
 const columns=new Set(sql.prepare('PRAGMA table_info(users)').all().map(c=>c.name));for(const k of ['deleted_at','role_template_id','role_template_ids','work_roles','action_access'])if(!columns.has(k))sql.exec('ALTER TABLE users ADD COLUMN '+k+' TEXT');
 if(!columns.has('follow_role_templates'))sql.exec('ALTER TABLE users ADD COLUMN follow_role_templates INTEGER NOT NULL DEFAULT 0');
 sql.exec('CREATE TABLE IF NOT EXISTS role_templates(id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE COLLATE NOCASE,version INTEGER NOT NULL,document TEXT NOT NULL)');
 const list=()=>sql.prepare('SELECT u.action_access,u.follow_role_templates,u.id,u.username,u.name,u.role,u.active,u.can_factors,u.can_below_cost,u.can_view_costs,u.can_approve,u.technical_delegated,u.section_access,u.can_formula_use,u.can_formula_view,u.can_formula_edit,u.can_formula_unlock,u.can_reopen,u.role_template_id,u.role_template_ids,u.work_roles,r.name AS role_label FROM users u LEFT JOIN role_templates r ON r.id=u.role_template_id WHERE u.deleted_at IS NULL ORDER BY u.username').all().map(u=>{const teams=sql.prepare('SELECT document FROM work_teams WHERE id=1').get();if(teams){const t=JSON.parse(teams.document);u.work_roles=JSON.stringify(Object.fromEntries(['sales','technical','materials'].map(k=>[k,(t[k]?.managers||[t[k]?.lead]).includes(u.id)?'manager':t[k]?.members?.includes(u.id)?'member':''])));}return u;});
 function resolve(body){
  const ids=body.roleTemplateIds===undefined?[body.roleTemplateId].filter(Boolean):body.roleTemplateIds;
  if(!Array.isArray(ids)||ids.length>30||ids.some(id=>typeof id!=='string'))fail(400,'Danh sách vai trò không hợp lệ');
  const selected=[...new Set(ids)],roles=selected.map(id=>{const r=sql.prepare('SELECT * FROM role_templates WHERE id=?').get(id);if(!r)fail(400,'Vai trò đã bị xóa; tải lại danh sách');return JSON.parse(r.document);});
  let workRoles;try{workRoles=require('../role-access.js').workRoles(body.workRoles??require('../role-access.js').combine(roles)?.workRoles);}catch(e){fail(400,e.message);}
  if(body.followRoleTemplates!==undefined&&typeof body.followRoleTemplates!=='boolean')fail(400,'Chế độ bộ quyền không hợp lệ');
  const defaults=require('../role-access.js').combine(roles)||{};
  if(body.followRoleTemplates){if(!roles.length)fail(400,'Chọn bộ quyền để tự cập nhật');return {...body,...defaults,technicalDelegation:true,roleTemplateId:selected[0],roleTemplateIds:selected,followRoleTemplates:true};}
  return {...defaults,...body,...(roles.length?{role:defaults.role}:{}),technicalDelegation:roles.length?true:body.technicalDelegation,roleTemplateId:selected[0]||null,roleTemplateIds:selected,workRoles};
 }
 function saveRoles(id,body){
  let actions;try{actions=require('../action-access.js').parse(body.actionAccess);}catch(e){fail(400,e.message);}sql.prepare('UPDATE users SET action_access=? WHERE id=?').run(actions===null?null:JSON.stringify(actions),id);
  sql.prepare('UPDATE users SET follow_role_templates=? WHERE id=?').run(Number(body.followRoleTemplates===true),id);
  sql.prepare('UPDATE users SET role_template_id=?,role_template_ids=?,work_roles=? WHERE id=?').run(body.roleTemplateId,JSON.stringify(body.roleTemplateIds||[]),JSON.stringify(body.workRoles||{}),id);
  const old=sql.prepare('SELECT * FROM work_teams WHERE id=1').get();
  if(old||Object.values(body.workRoles||{}).some(Boolean)){const teams=old?JSON.parse(old.document):{};for(const stage of ['sales','technical','materials']){const t=teams[stage]||{};t.managers=(t.managers||[t.lead].filter(Boolean)).filter(x=>x!==id);t.members=(t.members||[]).filter(x=>x!==id);delete t.lead;const role=body.workRoles?.[stage];if(role)t[role==='manager'?'managers':'members'].push(id);teams[stage]=t;}sql.prepare('INSERT INTO work_teams VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET version=excluded.version,document=excluded.document').run((old?.version||0)+1,JSON.stringify(teams));}
 }
 function validate(body){let actionAccess;try{actionAccess=require('../action-access.js').parse(body.actionAccess);}catch(e){fail(400,e.message);}if(body.permissionModel!==undefined&&!['matrix','legacy'].includes(body.permissionModel))fail(400,'Invalid permission model');if(body.permissionModel==='matrix'){try{body={...Object.fromEntries(require('../role-access.js').flags.map(k=>[k,false])),...body,role:require('../role-access.js').matrixRole(body)};}catch(e){fail(400,e.message);}}for(const k of require('../role-access.js').flags)if(Object.hasOwn(body,k)&&typeof body[k]!=='boolean')fail(400,'Quyền phải là bật/tắt');const name=String(body.name||'').trim(),role=body.role;if(!name||name.length>100||!ROLES.includes(role))fail(400,'Nhập tên vai trò và chọn loại quyền nền');let sections,sectionModes;try{sectionModes=body.sectionModes===undefined?undefined:SA.parseModes(body.sectionModes);sections=SA.parse(sectionModes||body.sections)||[];}catch(e){fail(400,e.message);}validateDelegation({...body,sections,technicalDelegation:true});let workRoles;try{workRoles=require('../role-access.js').workRoles(body.workRoles);}catch(e){fail(400,e.message);}return {...(actionAccess===null?{}:{actionAccess}),permissionModel:body.permissionModel||'legacy',workRoles,...Object.fromEntries(Object.keys(require('./formula-access.cjs').FIELDS).filter(k=>Object.hasOwn(body,k)).map(k=>[k,!!body[k]])),name,role,sections,...(sectionModes?{sectionModes}:{}),canViewCosts:role==='admin'||!!body.canViewCosts,canApprove:!!body.canApprove,canEditFactors:!!body.canEditFactors,canApproveBelowCost:!!body.canApproveBelowCost};}
 function refreshBoundUsers(actor,roleId){
  for(const u of sql.prepare('SELECT * FROM users WHERE deleted_at IS NULL AND follow_role_templates=1').all()){
   if(require('./organization.cjs').managed(sql,u.id))continue;
   const ids=JSON.parse(u.role_template_ids||'null')||[u.role_template_id].filter(Boolean);if(!ids.includes(roleId))continue;
   const b=resolve({roleTemplateIds:ids,followRoleTemplates:true});validateDelegation(b);
   if(u.id===actor.id&&b.role!=='admin')fail(409,'Không tự thu hồi quyền quản trị đang dùng');
   const values={action_access:b.actionAccess==null?null:JSON.stringify(b.actionAccess),role:b.role,section_access:JSON.stringify(b.sectionModes),technical_delegated:1,can_view_costs:Number(b.canViewCosts),can_approve:Number(b.canApprove),can_factors:Number(b.canEditFactors),can_below_cost:Number(b.canApproveBelowCost),...Object.fromEntries(Object.entries(require('./formula-access.cjs').FIELDS).map(([k,col])=>[col,Number(b[k])]))};
   if(Object.entries(values).some(([k,v])=>u[k]!==v)||!SA.equal(JSON.parse(u.work_roles||'{}'),b.workRoles)){
    sql.prepare('UPDATE users SET '+Object.keys(values).map(k=>k+'=?').join(',')+' WHERE id=?').run(...Object.values(values),u.id);saveRoles(u.id,b);sql.prepare('DELETE FROM sessions WHERE user_id=? AND token<>?').run(u.id,u.id===actor.id?actor.token:'');history.record(sql,actor,u.id,'role-access-updated',history.userSnapshot(u),history.userSnapshot(sql.prepare('SELECT * FROM users WHERE id=?').get(u.id)));audit(actor,'role-access-updated',u.id,JSON.stringify({roleIds:ids,changedRole:roleId}));
   }
  }
 }
 function validateDelegation(body){if(body.role==='technical'&&body.technicalDelegation===true&&!body.canViewCosts&&((SA.parse(body.sections)||[]).some(k=>!['customer','bom','operations',...require('../technical-core.js').catalogSections].includes(k))||body.canEditFactors||body.canApprove||body.canApproveBelowCost))fail(400,'Quyền giá, hệ số và duyệt cần quyền Xem chi phí nội bộ. Danh mục vật tư, công đoạn kỹ thuật, quy ước và thư viện mẫu có thể cấp riêng mà không mở giá.');}
 return {list,resolve,saveRoles,validateDelegation,setOrganization(value){organization=value;},async handle({req,route,user,rights,send}){
  const roleMatch=route.match(/^\/api\/roles(?:\/([a-f0-9-]+))?$/),profile=route.match(/^\/api\/users\/([a-f0-9-]+)\/(profile|delete)$/);if(!roleMatch&&!profile)return false;if(!rights.users)fail(403,'Chỉ quản trị được quản lý tài khoản và vai trò');
  if(roleMatch){const id=roleMatch[1];if(req.method==='GET'&&!id){send(200,sql.prepare('SELECT * FROM role_templates ORDER BY name').all().map(r=>({...JSON.parse(r.document),id:r.id,version:r.version})));return true;}
   const body=await readBody(req);const value=transaction(()=>{const old=id?sql.prepare('SELECT * FROM role_templates WHERE id=?').get(id):null;if(id&&!old)fail(404,'Không tìm thấy vai trò');if(old&&body.expectedVersion!==old.version)fail(409,'Vai trò đã đổi; tải lại trước khi lưu');
    if(req.method==='DELETE'&&id){if(organization?.roleUsed(id))fail(409,'Bộ quyền đang dùng cho vị trí; cập nhật vị trí trước');if(sql.prepare('SELECT role_template_id,role_template_ids FROM users WHERE deleted_at IS NULL').all().some(u=>u.role_template_id===id||JSON.parse(u.role_template_ids||'[]').includes(id)))fail(409,'Vai trò đang có tài khoản sử dụng; đổi vai trò tài khoản trước');sql.prepare('DELETE FROM role_templates WHERE id=?').run(id);history.record(sql,user,id,'delete-role',JSON.parse(old.document),null);audit(user,'delete-role',id,old.name);return {ok:true};}
    if(!(req.method==='POST'&&!id||req.method==='PUT'&&id))fail(405,'Phương thức không hỗ trợ');const d=validate(body);if(sql.prepare('SELECT id FROM role_templates WHERE name=? COLLATE NOCASE AND id<>?').get(d.name,id||''))fail(409,'Tên vai trò đã tồn tại');const key=id||randomUUID(),version=(old?.version||0)+1;sql.prepare('INSERT INTO role_templates VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,version=excluded.version,document=excluded.document').run(key,d.name,version,JSON.stringify(d));history.record(sql,user,key,old?'update-role':'create-role',old?JSON.parse(old.document):null,d);refreshBoundUsers(user,key);organization?.roleChanged(user);audit(user,old?'update-role':'create-role',key,d.name);return {...d,id:key,version};});send(req.method==='POST'?201:200,value);return true;
  }
  if(req.method!=='POST')fail(405,'Phương thức không hỗ trợ');const body=await readBody(req);transaction(()=>{const target=sql.prepare('SELECT * FROM users WHERE id=? AND deleted_at IS NULL').get(profile[1]);if(!target)fail(404,'Không tìm thấy tài khoản');
   if(profile[2]==='delete'){if(target.id===user.id)fail(400,'Không tự xóa tài khoản đang đăng nhập');if(body.confirmUsername!==target.username)fail(400,'Nhập đúng tài khoản để xác nhận xóa');sql.prepare('UPDATE users SET active=0,deleted_at=? WHERE id=?').run(new Date().toISOString(),target.id);organization?.accountChanged(user,target.id,target.name,true);audit(user,'delete-user',target.id,'Ẩn tài khoản; giữ lịch sử công việc');}
   else{const username=String(body.username||'').trim().toLowerCase(),name=String(body.name||'').trim();if(!/^[a-z0-9._-]{3,64}$/.test(username)||!name||name.length>100)fail(400,'Tài khoản 3–64 ký tự không dấu; họ tên tối đa 100 ký tự');if(sql.prepare('SELECT id FROM users WHERE username=? AND id<>?').get(username,target.id))fail(409,'Tài khoản đã tồn tại hoặc đã được dùng trong lịch sử');if(require('./organization.cjs').managed(sql,target.id)&&name!==target.name)fail(409,'Sửa họ tên tại hồ sơ nhân sự');sql.prepare('UPDATE users SET username=?,name=? WHERE id=?').run(username,name,target.id);organization?.accountChanged(user,target.id,name);audit(user,'update-user',target.id,target.username+' → '+username);}
   history.record(sql,user,target.id,profile[2],history.userSnapshot(target),history.userSnapshot(sql.prepare('SELECT * FROM users WHERE id=?').get(target.id)));sql.prepare('DELETE FROM sessions WHERE user_id=?').run(target.id);
  });send(200,{ok:true});return true;
 }};
}
module.exports={createAccounts};
