'use strict';
const {randomUUID}=require('node:crypto'),SA=require('../section-access.js'),{ROLES}=require('./access.cjs');
function createAccounts({sql,fail,readBody,transaction,audit}){
 const columns=new Set(sql.prepare('PRAGMA table_info(users)').all().map(c=>c.name));for(const k of ['deleted_at','role_template_id','role_template_ids','work_roles'])if(!columns.has(k))sql.exec('ALTER TABLE users ADD COLUMN '+k+' TEXT');
 sql.exec('CREATE TABLE IF NOT EXISTS role_templates(id TEXT PRIMARY KEY,name TEXT NOT NULL UNIQUE COLLATE NOCASE,version INTEGER NOT NULL,document TEXT NOT NULL)');
 const list=()=>sql.prepare('SELECT u.id,u.username,u.name,u.role,u.active,u.can_factors,u.can_below_cost,u.can_view_costs,u.can_approve,u.technical_delegated,u.section_access,u.can_formula_use,u.can_formula_view,u.can_formula_edit,u.can_formula_unlock,u.can_reopen,u.role_template_id,u.role_template_ids,u.work_roles,r.name AS role_label FROM users u LEFT JOIN role_templates r ON r.id=u.role_template_id WHERE u.deleted_at IS NULL ORDER BY u.username').all().map(u=>{const teams=sql.prepare('SELECT document FROM work_teams WHERE id=1').get();if(teams){const t=JSON.parse(teams.document);u.work_roles=JSON.stringify(Object.fromEntries(['sales','technical','materials'].map(k=>[k,(t[k]?.managers||[t[k]?.lead]).includes(u.id)?'manager':t[k]?.members?.includes(u.id)?'member':''])));}return u;});
 function resolve(body){
  const ids=body.roleTemplateIds===undefined?[body.roleTemplateId].filter(Boolean):body.roleTemplateIds;
  if(!Array.isArray(ids)||ids.length>30||ids.some(id=>typeof id!=='string'))fail(400,'Danh sách vai trò không hợp lệ');
  const selected=[...new Set(ids)],roles=selected.map(id=>{const r=sql.prepare('SELECT * FROM role_templates WHERE id=?').get(id);if(!r)fail(400,'Vai trò đã bị xóa; tải lại danh sách');return JSON.parse(r.document);});
  let workRoles;try{workRoles=require('../role-access.js').workRoles(body.workRoles??require('../role-access.js').combine(roles)?.workRoles);}catch(e){fail(400,e.message);}
  const defaults=require('../role-access.js').combine(roles)||{};
  return {...defaults,...body,...(roles.length?{role:defaults.role}:{}),technicalDelegation:roles.length?true:body.technicalDelegation,roleTemplateId:selected[0]||null,roleTemplateIds:selected,workRoles};
 }
 function saveRoles(id,body){
  sql.prepare('UPDATE users SET role_template_id=?,role_template_ids=?,work_roles=? WHERE id=?').run(body.roleTemplateId,JSON.stringify(body.roleTemplateIds||[]),JSON.stringify(body.workRoles||{}),id);
  const old=sql.prepare('SELECT * FROM work_teams WHERE id=1').get();
  if(old||Object.values(body.workRoles||{}).some(Boolean)){const teams=old?JSON.parse(old.document):{};for(const stage of ['sales','technical','materials']){const t=teams[stage]||{};t.managers=(t.managers||[t.lead].filter(Boolean)).filter(x=>x!==id);t.members=(t.members||[]).filter(x=>x!==id);delete t.lead;const role=body.workRoles?.[stage];if(role)t[role==='manager'?'managers':'members'].push(id);teams[stage]=t;}sql.prepare('INSERT INTO work_teams VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET version=excluded.version,document=excluded.document').run((old?.version||0)+1,JSON.stringify(teams));}
 }
 function validate(body){for(const k of Object.keys(require('./formula-access.cjs').FIELDS))if(Object.hasOwn(body,k)&&typeof body[k]!=='boolean')fail(400,'Quyền phải là bật/tắt');const name=String(body.name||'').trim(),role=body.role;if(!name||name.length>100||!ROLES.includes(role))fail(400,'Nhập tên vai trò và chọn loại quyền nền');let sections,sectionModes;try{sectionModes=body.sectionModes===undefined?undefined:SA.parseModes(body.sectionModes);sections=SA.parse(sectionModes||body.sections)||[];}catch(e){fail(400,e.message);}validateDelegation({...body,sections,technicalDelegation:true});let workRoles;try{workRoles=require('../role-access.js').workRoles(body.workRoles);}catch(e){fail(400,e.message);}return {workRoles,...Object.fromEntries(Object.keys(require('./formula-access.cjs').FIELDS).filter(k=>Object.hasOwn(body,k)).map(k=>[k,!!body[k]])),name,role,sections,...(sectionModes?{sectionModes}:{}),canViewCosts:role==='admin'||!!body.canViewCosts,canApprove:!!body.canApprove,canEditFactors:!!body.canEditFactors,canApproveBelowCost:!!body.canApproveBelowCost};}
 function validateDelegation(body){if(body.role==='technical'&&body.technicalDelegation===true&&!body.canViewCosts&&((SA.parse(body.sections)||[]).some(k=>!['customer','bom','operations',...require('../technical-core.js').catalogSections].includes(k))||body.canEditFactors||body.canApprove||body.canApproveBelowCost))fail(400,'Quyền giá, hệ số và duyệt cần quyền Xem chi phí nội bộ. Danh mục vật tư, công đoạn kỹ thuật, quy ước và thư viện mẫu có thể cấp riêng mà không mở giá.');}
 return {list,resolve,saveRoles,validateDelegation,async handle({req,route,user,rights,send}){
  const roleMatch=route.match(/^\/api\/roles(?:\/([a-f0-9-]+))?$/),profile=route.match(/^\/api\/users\/([a-f0-9-]+)\/(profile|delete)$/);if(!roleMatch&&!profile)return false;if(!rights.users)fail(403,'Chỉ quản trị được quản lý tài khoản và vai trò');
  if(roleMatch){const id=roleMatch[1];if(req.method==='GET'&&!id){send(200,sql.prepare('SELECT * FROM role_templates ORDER BY name').all().map(r=>({...JSON.parse(r.document),id:r.id,version:r.version})));return true;}
   const body=await readBody(req);const value=transaction(()=>{const old=id?sql.prepare('SELECT * FROM role_templates WHERE id=?').get(id):null;if(id&&!old)fail(404,'Không tìm thấy vai trò');if(old&&body.expectedVersion!==old.version)fail(409,'Vai trò đã đổi; tải lại trước khi lưu');
    if(req.method==='DELETE'&&id){if(sql.prepare('SELECT role_template_id,role_template_ids FROM users WHERE deleted_at IS NULL').all().some(u=>u.role_template_id===id||JSON.parse(u.role_template_ids||'[]').includes(id)))fail(409,'Vai trò đang có tài khoản sử dụng; đổi vai trò tài khoản trước');sql.prepare('DELETE FROM role_templates WHERE id=?').run(id);audit(user,'delete-role',id,old.name);return {ok:true};}
    if(!(req.method==='POST'&&!id||req.method==='PUT'&&id))fail(405,'Phương thức không hỗ trợ');const d=validate(body);if(sql.prepare('SELECT id FROM role_templates WHERE name=? COLLATE NOCASE AND id<>?').get(d.name,id||''))fail(409,'Tên vai trò đã tồn tại');const key=id||randomUUID(),version=(old?.version||0)+1;sql.prepare('INSERT INTO role_templates VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,version=excluded.version,document=excluded.document').run(key,d.name,version,JSON.stringify(d));audit(user,old?'update-role':'create-role',key,d.name);return {...d,id:key,version};});send(req.method==='POST'?201:200,value);return true;
  }
  if(req.method!=='POST')fail(405,'Phương thức không hỗ trợ');const body=await readBody(req);transaction(()=>{const target=sql.prepare('SELECT * FROM users WHERE id=? AND deleted_at IS NULL').get(profile[1]);if(!target)fail(404,'Không tìm thấy tài khoản');
   if(profile[2]==='delete'){if(target.id===user.id)fail(400,'Không tự xóa tài khoản đang đăng nhập');if(body.confirmUsername!==target.username)fail(400,'Nhập đúng tài khoản để xác nhận xóa');sql.prepare('UPDATE users SET active=0,deleted_at=? WHERE id=?').run(new Date().toISOString(),target.id);audit(user,'delete-user',target.id,'Ẩn tài khoản; giữ lịch sử công việc');}
   else{const username=String(body.username||'').trim().toLowerCase(),name=String(body.name||'').trim();if(!/^[a-z0-9._-]{3,64}$/.test(username)||!name||name.length>100)fail(400,'Tài khoản 3–64 ký tự không dấu; họ tên tối đa 100 ký tự');if(sql.prepare('SELECT id FROM users WHERE username=? AND id<>?').get(username,target.id))fail(409,'Tài khoản đã tồn tại hoặc đã được dùng trong lịch sử');sql.prepare('UPDATE users SET username=?,name=? WHERE id=?').run(username,name,target.id);audit(user,'update-user',target.id,target.username+' → '+username);}
   sql.prepare('DELETE FROM sessions WHERE user_id=?').run(target.id);
  });send(200,{ok:true});return true;
 }};
}
module.exports={createAccounts};
