'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const {DatabaseSync}=require('node:sqlite');
const {randomBytes,scryptSync,timingSafeEqual,createHash,randomUUID}=require('node:crypto');
const SA=require('../section-access.js');
const C=require('../core.js');require('../pricing-core.js');
const {ROLES,permissions,factorFingerprint,publicOffer,catalogSeed}=require('./access.cjs');
const sha=value=>createHash('sha256').update(value).digest('hex');
const fail=(status,message)=>{const e=Error(message);e.status=status;throw e;};
function cleanDocument(input){
  if(!input||input.version!==2||!input.quote?.pricing||!Array.isArray(input.quote.products))fail(400,'Dữ liệu báo giá không đúng định dạng');
  const text=JSON.stringify(input);if(text.length>1500000)fail(413,'Báo giá quá lớn');
  const data=JSON.parse(text,(key,value)=>{if(['__proto__','constructor','prototype'].includes(key))fail(400,'Dữ liệu chứa khóa không hợp lệ');return value;});
  for(const key of ['materials','rates','rules'])if(!Array.isArray(data[key])||data[key].length>2000)fail(400,'Danh mục không hợp lệ');
  const validId=id=>typeof id==='string'&&/^[\p{L}\p{N}_. /-]{1,100}$/u.test(id)&&!['__proto__','constructor','prototype'].includes(id);for(const items of [data.materials,data.rates,data.rules,data.quote.ratesSnapshot||[]]){const keys=new Set();for(const item of items){if(!item||!validId(item.id)||keys.has(item.id))fail(400,'Mã danh mục không hợp lệ hoặc bị trùng');keys.add(item.id);}}const ids=new Set();let count=0,physical=0;
  function walk(nodes,depth=0,mult=1){if(depth>12)fail(400,'Cấu thành vượt 12 cấp');for(const n of nodes){if(++count>1000||!validId(n.id)||ids.has(n.id))fail(400,'Quá nhiều dòng hoặc mã dòng bị trùng');ids.add(n.id);if(!['product','component','material'].includes(n.kind)||!(n.qty>0)||n.qty>5000||!Number.isFinite(Number(n.qty)))fail(400,'Loại hoặc số lượng dòng không hợp lệ');const qty=mult*n.qty;if(qty>5000)fail(400,'Một dòng vượt 5.000 đơn vị');if(n.kind==='material'){if(!n.spec||!Object.hasOwn(C.shapes,n.spec.shape))fail(400,'Thiếu quy cách vật tư');if(n.spec.shape!=='piece')physical+=qty;}if(physical>5000)fail(400,'Tối đa 5.000 phôi trong lần tính dùng thử');if(n.children){if(!Array.isArray(n.children))fail(400,'Cấu thành không hợp lệ');walk(n.children,depth+1,qty);}if(n.ops&&(!Array.isArray(n.ops)||n.ops.length>100))fail(400,'Công đoạn không hợp lệ');}}
  walk(data.quote.products);
  try{require('../intake-core.js').validateRequest(data.quote);}catch(e){fail(400,e.message);}
  if(!String(data.quote.id||'').trim()||String(data.quote.id).length>100)fail(400,'Nhập mã báo giá');
  if(data.library!==undefined&&(!Array.isArray(data.library)||data.library.length>1000))fail(400,'Thư viện không hợp lệ');
  for(const template of data.library||[]){ids.clear();count=0;physical=0;walk([template]);}
  if(data.materialPrices!==undefined&&(!Array.isArray(data.materialPrices)||data.materialPrices.length>2000))fail(400,'Bảng giá vật liệu không hợp lệ');
  try{require('./catalog-guard.cjs').validateBook(data.materialPrices||[]);}catch(e){fail(400,e.message);}
  for(const m of data.materials)try{require('../completion-core.js').priceFor(m,data.materialPrices||[]);}catch(e){fail(400,e.message);}
  if(data.conventions!==undefined){const CV=require('../conventions-core.js');if(!data.conventions||Array.isArray(data.conventions)||typeof data.conventions!=='object')fail(400,'Danh mục quy ước không hợp lệ');for(const [kind,items]of Object.entries(data.conventions)){if(!Object.hasOwn(CV.KINDS,kind)||!Array.isArray(items)||items.length>2000||items.some(x=>!x||typeof x.name!=='string'||!x.name.trim()||x.name.length>80))fail(400,'Giá trị quy ước không hợp lệ');if(kind==='parameters'&&items.some(x=>!/^[A-Za-z][A-Za-z0-9_]{0,23}$/.test(x.name)))fail(400,'Biến công thức không hợp lệ');}}
  if(data.catalogPriceBaseline!==undefined&&data.catalogPriceBaseline!==null){const b=data.catalogPriceBaseline;if(!b||typeof b!=='object'||!Array.isArray(b.materials)||!Array.isArray(b.rates)||[b.materials,b.rates].some(rows=>rows.length>2000||rows.some(x=>!x||!validId(x.id))))fail(400,'Mốc khôi phục giá không hợp lệ');}
  try{require('../definition-core.js').validateCatalog(data);}catch(e){fail(400,e.message);}
  try{const W=require('../work-core.js');for(const r of [...data.rates,...data.quote.ratesSnapshot||[]])W.validatePriceOptions(r);for(const n of C.flatten([...data.quote.products,...data.library||[]]))for(const op of n.ops||[])if(op.complexity!==undefined)W.validateComplexity(op.complexity);for(const n of C.flatten([...data.quote.products,...data.library||[]]))if(n.productGroup!==undefined&&(typeof n.productGroup!=='string'||n.productGroup.length>80))throw Error('Nhóm sản phẩm không hợp lệ');for(const x of data.conventions?.parameters||[])if(x.label!==undefined&&(typeof x.label!=='string'||x.label.length>120))throw Error('Tên thông số không hợp lệ');}catch(e){fail(400,e.message);}
  if(data.pricingDefaults!==undefined)try{require('../input-prices-core.js').validateMaster(data.pricingDefaults);}catch(e){fail(400,e.message);}
  let pricingDefaults;try{pricingDefaults=require('../input-prices-core.js').defaults(data);}catch(e){fail(400,e.message);}
  const safe={version:2,pricingDefaults,shapeDefinitions:data.shapeDefinitions||[],stockSizes:data.stockSizes||[],catalogPriceBaseline:data.catalogPriceBaseline||null,conventions:data.conventions||{},materialPrices:data.materialPrices||[],materials:data.materials,rates:data.rates,rules:data.rules,library:data.library||[],history:[],quote:data.quote};
  let result;try{result=C.calculate(safe);}catch{fail(400,'Dữ liệu không tính được; kiểm tra cấu thành và cấu hình');}
  if(result.total.grand>1e15||!Number.isFinite(result.total.grand))fail(400,'Giá trị vượt giới hạn dùng thử');
  return {data:safe,result};
}
function createApp({databasePath=':memory:',staticRoot=path.resolve(__dirname,'../dist'),sessionHours=8,publicOrigin='',setupKey=''}={}){
  let origin='';if(publicOrigin){const parsed=new URL(publicOrigin);if(parsed.protocol!=='https:'||parsed.username||parsed.password||parsed.pathname!=='/'||parsed.search||parsed.hash)throw Error('TP_PUBLIC_ORIGIN phải là nguồn HTTPS, không chứa đường dẫn');origin=parsed.origin;if(String(setupKey).length<24)throw Error('Cần TP_SETUP_KEY ít nhất 24 ký tự khi cấu hình địa chỉ HTTPS');}const cookieSecurity=origin?'; Secure':'';
  if(databasePath!==':memory:')fs.mkdirSync(path.dirname(path.resolve(databasePath)),{recursive:true});
  const sql=new DatabaseSync(databasePath);sql.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;
    CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY, username TEXT UNIQUE NOT NULL, name TEXT NOT NULL, role TEXT NOT NULL, password TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1);
    CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), csrf TEXT NOT NULL, expires INTEGER NOT NULL);
    CREATE TABLE IF NOT EXISTS quotes(id TEXT PRIMARY KEY, code TEXT NOT NULL, customer TEXT NOT NULL, project TEXT NOT NULL, version INTEGER NOT NULL, status TEXT NOT NULL, total REAL NOT NULL, document TEXT NOT NULL, updated TEXT NOT NULL, actor TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS revisions(id TEXT NOT NULL REFERENCES quotes(id), version INTEGER NOT NULL, status TEXT NOT NULL, document TEXT NOT NULL, total REAL NOT NULL, actor TEXT NOT NULL, at TEXT NOT NULL, reason TEXT NOT NULL, PRIMARY KEY(id,version));
    CREATE TABLE IF NOT EXISTS audit(seq INTEGER PRIMARY KEY AUTOINCREMENT, at TEXT NOT NULL, user_id TEXT NOT NULL, action TEXT NOT NULL, entity TEXT NOT NULL, detail TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY, code TEXT UNIQUE NOT NULL, quote_id TEXT UNIQUE NOT NULL REFERENCES quotes(id), quote_version INTEGER NOT NULL, package TEXT NOT NULL, at TEXT NOT NULL, actor TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS catalog(id INTEGER PRIMARY KEY CHECK(id=1), version INTEGER NOT NULL, document TEXT NOT NULL, updated TEXT NOT NULL, actor TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS catalog_revisions(version INTEGER PRIMARY KEY, document TEXT NOT NULL, updated TEXT NOT NULL, actor TEXT NOT NULL);
  `);
  const columns=new Set(sql.prepare('PRAGMA table_info(users)').all().map(c=>c.name));for(const column of ['can_factors','can_below_cost','can_view_costs','can_approve','technical_delegated'])if(!columns.has(column))sql.exec('ALTER TABLE users ADD COLUMN '+column+' INTEGER');
  if(!columns.has('section_access'))sql.exec('ALTER TABLE users ADD COLUMN section_access TEXT');
  if(!sql.prepare('SELECT id FROM catalog WHERE id=1').get())sql.prepare('INSERT INTO catalog(id,version,document,updated,actor) VALUES(1,0,?,?,?)').run(JSON.stringify(catalogSeed()),new Date().toISOString(),'system');
  const attempts=new Map();
  function accessValue(body){try{return body.sections===undefined?null:JSON.stringify(SA.parse(body.sections));}catch(e){fail(400,e.message);}}
  function requireSection(user,key){if(!permissions(user).sections.includes(key))fail(403,'Chưa được cấp quyền: '+SA.labels[key]);}
  function guardSections(user,before,after,catalog=false){if(user.role==='admin'||user.section_access==null&&user.role!=='technical')return;if(permissions(user).technical&&!catalog){const T=require('../technical-core.js');before=T.project(before);after=T.project(after);}const denied=SA.denied(before,after,permissions(user),{catalog});if(denied.length)fail(403,'Không được sửa: '+denied.map(k=>SA.labels[k]||k).join(', '));}

  const run=(query,...args)=>sql.prepare(query).run(...args),one=(query,...args)=>sql.prepare(query).get(...args),all=(query,...args)=>sql.prepare(query).all(...args);
  const transaction=fn=>{sql.exec('BEGIN IMMEDIATE');try{const result=fn();sql.exec('COMMIT');return result;}catch(e){sql.exec('ROLLBACK');throw e;}};
  const audit=(user,action,entity,detail='')=>run('INSERT INTO audit(at,user_id,action,entity,detail) VALUES(?,?,?,?,?)',new Date().toISOString(),user.id,action,entity,String(detail).slice(0,1000));
  function addUser(body,role=body.role){const sectionAccess=accessValue(body);accounts.validateDelegation(body);formulaAccess.validateRights(body);const username=String(body.username||'').trim().toLowerCase(),name=String(body.name||'').trim(),password=String(body.password||'');if(!/^[a-z0-9._-]{3,64}$/.test(username)||!name||name.length>100)fail(400,'Tài khoản 3–64 ký tự không dấu; cần họ tên');if(password.length<12||password.length>200)fail(400,'Mật khẩu cần 12–200 ký tự');if(!ROLES.includes(role))fail(400,'Vai trò không hợp lệ');if(one('SELECT id FROM users WHERE username=?',username))fail(409,'Tài khoản đã tồn tại');const salt=randomBytes(16).toString('hex'),hash=scryptSync(password,salt,64).toString('hex'),id=randomUUID();run('INSERT INTO users(id,username,name,role,password) VALUES(?,?,?,?,?)',id,username,name,role,salt+':'+hash);if(typeof body.canEditFactors==='boolean')run('UPDATE users SET can_factors=? WHERE id=?',Number(body.canEditFactors),id);if(typeof body.canApproveBelowCost==='boolean')run('UPDATE users SET can_below_cost=? WHERE id=?',Number(body.canApproveBelowCost),id);for(const [field,column]of [['canViewCosts','can_view_costs'],['canApprove','can_approve']])if(typeof body[field]==='boolean')run('UPDATE users SET '+column+'=? WHERE id=?',Number(body[field]),id);run('UPDATE users SET section_access=?,technical_delegated=? WHERE id=?',sectionAccess,Number(body.technicalDelegation===true),id);formulaAccess.saveRights(id,body);return {id,username,name,role};}
  function session(req){const match=(req.headers.cookie||'').match(/(?:^|;\s*)tp_session=([a-f0-9]{64})(?:;|$)/);if(!match)return null;return one('SELECT users.id,users.username,users.name,users.role,users.can_factors,users.can_below_cost,users.can_view_costs,users.can_approve,users.technical_delegated,users.section_access,users.can_formula_use,users.can_formula_view,users.can_formula_edit,users.can_formula_unlock,users.can_reopen,sessions.csrf,sessions.token FROM sessions JOIN users ON users.id=sessions.user_id WHERE token=? AND expires>? AND active=1',sha(match[1]),Date.now());}
  function beginSession(user,res){const token=randomBytes(32).toString('hex'),csrf=randomBytes(24).toString('hex');run('DELETE FROM sessions WHERE expires<?',Date.now());run('INSERT INTO sessions(token,user_id,csrf,expires) VALUES(?,?,?,?)',sha(token),user.id,csrf,Date.now()+sessionHours*3600000);res.setHeader('Set-Cookie',`tp_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${sessionHours*3600}${cookieSecurity}`);return {user,permissions:permissions(user),csrf};}
  function getQuote(id){const q=one('SELECT * FROM quotes WHERE id=?',id);if(!q)fail(404,'Không tìm thấy báo giá');return q;}
  function offerRecord(record){const document=JSON.parse(record.document),offer=document.quote.approvedOffer||publicOffer(document,cleanDocument(document).result);return {id:record.id,version:record.version,status:'approved',readOnly:true,offer};}
  function currentOffer(id){const record=one("SELECT id,version,status,document FROM revisions WHERE id=? AND status='approved' ORDER BY version DESC LIMIT 1",id);if(!record)fail(403,'Chưa có bản đã duyệt được phép xem');return offerRecord(record);}
  function saveQuote(id,document,user,expectedVersion,status,reason,autoCode=false){return transaction(()=>{
    if(!id&&autoCode){document=C.copy(document);try{document.quote.id=require('../batch-one-core.js').nextQuoteCode(document.quote.date,all('SELECT code FROM quotes').map(x=>x.code));}catch(error){fail(400,error.message);}}
    const old=id?getQuote(id):null;if(old&&old.version!==expectedVersion)fail(409,'Bản trên máy chủ đã đổi. Tải lại hoặc lưu bản sao, không ghi đè.');
    const {data,result}=cleanDocument(formulaAccess.hydrate(document,user));formulaAccess.guard(old?JSON.parse(old.document):{...JSON.parse(one('SELECT document FROM catalog WHERE id=1').document),quote:{products:[]}},data,permissions(user));if(old)guardSections(user,JSON.parse(old.document),data);else if(user.section_access!=null&&user.role!=='admin'){const masterRow=one('SELECT document FROM catalog WHERE id=1'),master=masterRow?JSON.parse(masterRow.document):catalogSeed(),baseline=cleanDocument({...data,...master,quote:{...data.quote,products:[],ratesSnapshot:master.rates,pricing:master.pricingDefaults}}).data;guardSections(user,baseline,data);}const key=id||randomUUID(),version=(old?.version||0)+1,now=new Date().toISOString();data.quote.status=status;
    if(!permissions(user).factors){let baseline=old?JSON.parse(old.document):null;if(!baseline){const catalog=one('SELECT document FROM catalog WHERE id=1'),master=catalog?JSON.parse(catalog.document):catalogSeed();baseline={quote:{pricing:master.pricingDefaults,ratesSnapshot:master.rates}};}if(factorFingerprint(data)!==factorFingerprint(baseline))fail(403,'Tài khoản không được thay hệ số hoặc bảng tác động. Dùng bản đã có hoặc lấy từ danh mục chung.');}
    if(data.quote.opportunityId){const customerId=data.quote.customerInfo?.id,record=one('SELECT document FROM intake_customers WHERE id=?',customerId||'');if(!record||!JSON.parse(record.document).opportunities?.some(o=>o.id===data.quote.opportunityId))fail(400,'Cơ hội không thuộc hồ sơ khách hàng đã chọn');}
    if(['submitted','approved'].includes(status)&&(result.errors.length||!data.quote.products.length||!data.quote.customer?.trim()))fail(422,'Chưa thể duyệt: '+(result.errors.join('; ')||'cần sản phẩm và khách hàng'));
    if(['submitted','approved'].includes(status)&&data.quote.documentMode==='official'&&!String(data.quote.issuer?.name||'').trim())fail(422,'Bản chào chính thức cần tên đơn vị phát hành');delete data.quote.approvedOffer;delete data.quote.approvedBaseline;if(status==='approved'){data.quote.approvedOffer=publicOffer(data,result);data.quote.approvedBaseline=result.total;}
    if(one('SELECT id FROM quotes WHERE code=? AND id<>?',data.quote.id,key))fail(409,'Mã báo giá đã tồn tại trên máy chủ');
    const oldQuote=old?JSON.parse(old.document).quote:null;data.quote.changeHistory=oldQuote?.changeHistory||[];if(JSON.stringify(oldQuote?.pricing)!==JSON.stringify(data.quote.pricing))data.quote.changeHistory.push({kind:'Hệ số / phương án / giá chốt (máy chủ)',actor:user.name,at:now,revision:version,before:oldQuote?.pricing||null,after:data.quote.pricing});
    const CostInput=require('../cost-input-core.js'),oldInputs=oldQuote?Object.fromEntries(CostInput.view(oldQuote).map(r=>[r.key,{value:r.value,identity:r.identity,unit:r.unit}])):{},newInputs=Object.fromEntries(CostInput.view(data.quote).map(r=>[r.key,{value:r.value,identity:r.identity,unit:r.unit}])),inputChanges=CostInput.differences(oldInputs,newInputs);data.quote.inputPriceAudit=oldQuote?.inputPriceAudit||[];if(inputChanges.length)data.quote.inputPriceAudit.push({at:now,actor:user.name,revision:version,changes:inputChanges});
    const encoded=JSON.stringify(data);
    if(old)run('UPDATE quotes SET code=?,customer=?,project=?,version=?,status=?,total=?,document=?,updated=?,actor=? WHERE id=?',data.quote.id,data.quote.customer||'',data.quote.project||'',version,status,result.total.grand,encoded,now,user.id,key);
    else run('INSERT INTO quotes(id,code,customer,project,version,status,total,document,updated,actor) VALUES(?,?,?,?,?,?,?,?,?,?)',key,data.quote.id,data.quote.customer||'',data.quote.project||'',version,status,result.total.grand,encoded,now,user.id);
    run('INSERT INTO revisions(id,version,status,document,total,actor,at,reason) VALUES(?,?,?,?,?,?,?,?)',key,version,status,encoded,result.total.grand,user.id,now,reason||'');audit(user,status,key,reason||'');const technicalRecipients=old?undefined:notifications.created(key,user);return {id:key,version,status,total:result.total.grand,updated:now,errors:result.errors,...(technicalRecipients===undefined?{}:{technicalRecipients})};
  });}
  async function readBody(req,limit=2000000){if(!/^application\/json(?:;|$)/i.test(req.headers['content-type']||''))fail(415,'Yêu cầu JSON');const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>limit)fail(413,'Dữ liệu quá lớn');chunks.push(chunk);}let body;try{body=JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{fail(400,'JSON không hợp lệ');}if(!body||typeof body!=='object'||Array.isArray(body))fail(400,'Yêu cầu một đối tượng JSON');return body;}
  const workflow=require('./workflow.cjs').createWorkflow({sql,fail,transaction,audit,readBody,getQuote,currentOffer});
  const intake=require('./intake.cjs').createIntake({sql,fail,readBody,audit});
  const accounts=require('./accounts.cjs').createAccounts({sql,fail,readBody,transaction,audit});
  const formulaAccess=require('./formula-access.cjs').createFormulaAccess({sql,fail,readBody,audit,transaction});
  const notifications=require('./notifications.cjs').createNotifications({sql,fail,readBody,transaction,audit,getQuote});
  const server=http.createServer(async(req,res)=>{let responseUser=null;
    const send=(status,value)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8'});res.end(JSON.stringify(responseUser?formulaAccess.project(value,responseUser,permissions(responseUser)):value));};
    res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Cache-Control','no-store');
    try{
      const url=new URL(req.url,'http://localhost'),route=url.pathname;
      if(route==='/healthz'&&req.method==='GET')return send(200,{ok:!!one('SELECT 1 AS ready')});
      // Bind to loopback; optional explicit HTTPS origin behind an operator-managed proxy. Reject other hosts and cross-origin writes.
      if(origin?req.headers.host!==new URL(origin).host:!/^(?:127\.0\.0\.1|localhost|\[::1\])(?::\d+)?$/.test(req.headers.host||''))fail(403,'Địa chỉ máy chủ không hợp lệ');
      if(!route.startsWith('/api/')){if(req.method!=='GET'||!['/','/index.html'].includes(route))fail(404,'Không tìm thấy');const html=fs.readFileSync(path.join(staticRoot,'index.html'));res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});return res.end(html);}
      if(req.method==='OPTIONS')fail(403,'Không cho phép truy cập khác nguồn');
      if(req.headers.origin&&req.headers.origin!==(origin||`http://${req.headers.host}`))fail(403,'Nguồn truy cập không hợp lệ');
      if(route==='/api/status'&&req.method==='GET')return send(200,{configured:!!one('SELECT id FROM users LIMIT 1'),mode:origin?'https-proxy':'local-pilot',setupKeyRequired:!!origin,requireLogin:!!origin,version:2});
      if(route==='/api/setup'&&req.method==='POST'){const body=await readBody(req);if(origin&&!timingSafeEqual(Buffer.from(sha(String(body.setupKey||''))),Buffer.from(sha(String(setupKey)))))fail(403,'Mã khởi tạo không đúng');const user=transaction(()=>{if(one('SELECT id FROM users LIMIT 1'))fail(409,'Đã khởi tạo quản trị');return addUser(body,'admin');});audit(user,'setup',user.id);return send(201,beginSession(user,res));}
      if(route==='/api/login'&&req.method==='POST'){
        const body=await readBody(req),identity=String(body.username||'').trim().toLowerCase().slice(0,64),key=req.socket.remoteAddress+'|'+identity;
        for(const [bucket,limit]of [[req.socket.remoteAddress,200],[key,10]]){const entry=attempts.get(bucket)||{count:0,until:Date.now()+60000};if(Date.now()>entry.until){entry.count=0;entry.until=Date.now()+60000;}attempts.set(bucket,entry);if(++entry.count>limit)fail(429,'Thử đăng nhập quá nhiều; chờ một phút');}if(attempts.size>2000)for(const [bucket,entry]of attempts)if(entry.until<Date.now())attempts.delete(bucket);
        if(String(body.password||'').length>200)fail(401,'Tài khoản hoặc mật khẩu không đúng');const user=one('SELECT * FROM users WHERE username=? AND active=1',String(body.username||'').trim().toLowerCase());const [salt,hash]=(user?.password||'00000000000000000000000000000000:'+('0'.repeat(128))).split(':');const test=scryptSync(String(body.password||''),salt,64);if(!user||!timingSafeEqual(test,Buffer.from(hash,'hex')))fail(401,'Tài khoản hoặc mật khẩu không đúng');attempts.delete(key);const {password,...publicUser}=user;audit(user,'login',user.id);return send(200,beginSession(publicUser,res));
      }
      const user=session(req);if(!user)fail(401,'Cần đăng nhập');const rights=permissions(user);responseUser=user;
      if(!['GET','HEAD'].includes(req.method)&&req.headers['x-csrf-token']!==user.csrf)fail(403,'Phiên yêu cầu không hợp lệ; tải lại trang');
      if(await formulaAccess.handle({req,route,user,rights,send}))return;
      if(await accounts.handle({req,route,user,rights,send}))return;
      if(await notifications.handle({req,route,user,rights,send}))return;
      if(rights.technical){
        const Technical=require('../technical-core.js');
        if(route==='/api/quotes'&&req.method==='GET')return send(200,all('SELECT id,code,customer,project,version,status,updated,document FROM quotes ORDER BY updated DESC').map(({document,...row})=>({...row,customer:'',project:'',progress:notifications.summary({...row,document})})));
        const technicalQuote=route.match(/^\/api\/quotes\/([a-f0-9-]+)$/);
        if(technicalQuote){const q=getQuote(technicalQuote[1]);
          if(req.method==='GET')return send(200,{id:q.id,version:q.version,status:q.status,document:Technical.project(JSON.parse(q.document))});
          if(req.method==='PUT'){
            if(!rights.edit)fail(403,'Chưa được cấp phần kỹ thuật để sửa');
            if(q.status!=='draft')fail(409,'Bản đã trình/duyệt được khóa.');
            const body=await readBody(req);if(q.version!==body.expectedVersion)fail(409,'Báo giá đã đổi. Tải lại trước khi lưu.');
            let document;try{document=Technical.merge(JSON.parse(q.document),formulaAccess.hydrate(body.document,user));}catch(e){fail(403,e.message);}
            const saved=saveQuote(q.id,document,user,body.expectedVersion,'draft','Cập nhật kỹ thuật');
            return send(200,{id:saved.id,version:saved.version,status:saved.status,updated:saved.updated});
          }
        }
        const reopenMatch=route.match(/^\/api\/quotes\/([a-f0-9-]+)\/(reopen|restore)$/);
        if(reopenMatch&&req.method==='POST'){
          if(!rights.reopen)fail(403,'Chưa có quyền mở sửa báo giá sau hoàn thiện');
          const q=getQuote(reopenMatch[1]),body=await readBody(req);if(!String(body.reason||'').trim())fail(400,'Nhập lý do mở sửa');
          if(reopenMatch[2]==='reopen'&&q.status==='draft')fail(409,'Báo giá đang là bản nháp');
          const source=reopenMatch[2]==='restore'?one('SELECT document FROM revisions WHERE id=? AND version=?',q.id,body.sourceVersion):q;if(!source)fail(404,'Không có phiên bản nguồn');
          const saved=saveQuote(q.id,JSON.parse(source.document),user,body.expectedVersion,'draft',String(body.reason).slice(0,1000));return send(200,{id:saved.id,version:saved.version,status:saved.status});
        }
        if(!(route==='/api/catalog'&&rights.catalog)&&!['/api/me','/api/logout','/api/me/password'].includes(route))fail(403,'Tài khoản kỹ thuật chỉ được làm việc với dữ liệu kỹ thuật, không được xem giá');
      }
      if(await intake.handle({req,route,user,rights,send}))return;
      if(await workflow.handle({req,route,user,rights,send}))return;
      if(route==='/api/me/password'&&req.method==='POST'){
        const body=await readBody(req),record=one('SELECT password FROM users WHERE id=?',user.id),[salt,hash]=record.password.split(':'),password=String(body.password||'');
        if(String(body.currentPassword||'').length>200||!timingSafeEqual(scryptSync(String(body.currentPassword||''),salt,64),Buffer.from(hash,'hex')))fail(403,'Mật khẩu hiện tại không đúng');
        if(password.length<12||password.length>200)fail(400,'Mật khẩu cần 12–200 ký tự');const nextSalt=randomBytes(16).toString('hex');run('UPDATE users SET password=? WHERE id=?',nextSalt+':'+scryptSync(password,nextSalt,64).toString('hex'),user.id);run('DELETE FROM sessions WHERE user_id=?',user.id);audit(user,'change-password',user.id);return send(200,{ok:true});
      }
      if(route==='/api/me'&&req.method==='GET'){const {csrf,token,...publicUser}=user;return send(200,{user:publicUser,permissions:rights,csrf});}
      if(route==='/api/logout'&&req.method==='POST'){run('DELETE FROM sessions WHERE token=?',user.token);res.setHeader('Set-Cookie','tp_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0'+cookieSecurity);return send(200,{ok:true});}
      if(route==='/api/catalog/candidates'&&req.method==='GET'){if(!rights.catalog)fail(403,'Chỉ quản trị danh mục');const row=one('SELECT version,document FROM catalog WHERE id=1'),master=row?JSON.parse(row.document):catalogSeed();return send(200,{version:row?.version||0,catalog:master,candidates:require('./catalog-guard.cjs').candidates(master,all('SELECT document FROM quotes').map(x=>JSON.parse(x.document)))});}
      if(route==='/api/catalog'){
        if(!rights.costs&&!(rights.technical&&rights.catalog))fail(403,'Không có quyền xem danh mục giá nội bộ');
        const current=one('SELECT * FROM catalog WHERE id=1');
        if(req.method==='GET')return send(200,{version:current?.version||0,updated:current?.updated||null,demonstration:!current?.version,catalog:rights.technical?require('../technical-core.js').projectCatalog(current?JSON.parse(current.document):catalogSeed()):current?JSON.parse(current.document):catalogSeed()});
        if(req.method==='PUT'){if(!rights.catalog)fail(403,'Chỉ quản trị được phát hành danh mục chung');const body=await readBody(req);const result=transaction(()=>{const old=one('SELECT * FROM catalog WHERE id=1');if((old?.version||0)!==body.expectedVersion)fail(409,'Danh mục đã đổi. Tải lại trước khi phát hành.');let value=formulaAccess.hydrate(body.catalog,user);if(rights.technical){try{value=require('../technical-core.js').mergeCatalog(old?JSON.parse(old.document):catalogSeed(),value);}catch(e){fail(403,e.message);}}formulaAccess.guard(old?JSON.parse(old.document):catalogSeed(),value,rights,true);guardSections(user,old?JSON.parse(old.document):catalogSeed(),value,true);if(!value||typeof value!=='object')fail(400,'Thiếu danh mục');
          const trial=require('../pricing-core.js').demoSeed();Object.assign(trial,{pricingDefaults:value.pricingDefaults||catalogSeed().pricingDefaults,shapeDefinitions:value.shapeDefinitions||[],stockSizes:value.stockSizes||[],conventions:value.conventions||{},materialPrices:value.materialPrices||[],materials:value.materials,rates:value.rates,rules:value.rules,library:value.library});const safe=cleanDocument(trial).data;
          for(const [type,items]of [['vật tư',safe.materials],['nguyên công',safe.rates],['công thức',safe.rules]]){const ids=new Set();for(const item of items){if(typeof item.id!=='string'||!item.id.trim()||item.id.length>100||ids.has(item.id))fail(400,'Mã '+type+' bị trống/trùng');ids.add(item.id);if(type==='vật tư'&&(!Object.hasOwn(C.shapes,item.shape)||!Number.isFinite(Number(item.price))||item.price===null||item.price<0))fail(400,'Vật tư thiếu dạng hoặc giá');if(type==='nguyên công'&&['inside','outside'].some(k=>item[k]===null||!Number.isFinite(Number(item[k]))||Number(item[k])<0))fail(400,'Đơn giá công đoạn không hợp lệ');}}
          const previousTemplates=new Map((old?JSON.parse(old.document).library:[]).map(t=>[t.id,JSON.stringify(t)])),materialIds=new Set(safe.materials.map(x=>x.id)),rateIds=new Set(safe.rates.map(x=>x.id)),ruleIds=new Set(safe.rules.map(x=>x.id));
          for(const template of safe.library){if(previousTemplates.get(template.id)===JSON.stringify(template))continue;for(const node of C.flatten([template])){if(node.kind==='material'&&(!materialIds.has(node.materialId)||node.rule&&!ruleIds.has(node.rule)))fail(400,'Mẫu '+template.name+': thiếu mã vật tư hoặc quy tắc trong danh mục chung');for(const op of node.ops||[])if(!rateIds.has(op.id))fail(400,'Mẫu '+template.name+': thiếu nguyên công '+op.id+' trong danh mục chung');}try{C.attachTemplateRates({ratesSnapshot:safe.rates},[],template);}catch(error){fail(400,error.message);}}
          const defaults=value.pricingDefaults||catalogSeed().pricingDefaults,check=require('../pricing-core.js').demoSeed();try{if(!rights.technical)require('../package-operation-core.js').synchronize(defaults,safe.rates);require('../input-prices-core.js').validateMaster(defaults);}catch(e){fail(400,e.message);}check.quote.pricing={...defaults,selected:'detail',overrides:{}};const errors=C.calculate(check).errors;if(errors.length)fail(400,'Hệ số chung không hợp lệ: '+errors.join('; '));
          try{require('./catalog-guard.cjs').protect(old?JSON.parse(old.document):catalogSeed(),safe,all('SELECT document FROM quotes UNION ALL SELECT document FROM revisions').map(x=>JSON.parse(x.document)));}catch(e){fail(400,e.message);}
          const document=JSON.stringify({shapeDefinitions:safe.shapeDefinitions,stockSizes:safe.stockSizes,conventions:safe.conventions,materialPrices:safe.materialPrices,materials:safe.materials,rates:safe.rates,rules:safe.rules,library:safe.library,pricingDefaults:defaults}),version=(old?.version||0)+1,updated=new Date().toISOString();run('INSERT INTO catalog(id,version,document,updated,actor) VALUES(1,?,?,?,?) ON CONFLICT(id) DO UPDATE SET version=excluded.version,document=excluded.document,updated=excluded.updated,actor=excluded.actor',version,document,updated,user.id);run('INSERT INTO catalog_revisions(version,document,updated,actor) VALUES(?,?,?,?)',version,document,updated,user.id);audit(user,'catalog',String(version));return {version,updated};});return send(200,result);}
      }
      if(route==='/api/users'){if(!rights.users)fail(403,'Chỉ quản trị được quản lý tài khoản');if(req.method==='GET')return send(200,accounts.list());if(req.method==='POST'){const body=accounts.resolve(await readBody(req)),created=transaction(()=>{const u=addUser(body);run('UPDATE users SET role_template_id=? WHERE id=?',body.roleTemplateId,u.id);return u;});audit(user,'create-user',created.id);return send(201,created);}}
      const userAction=route.match(/^\/api\/users\/([a-f0-9-]+)\/(disable|password|access|enable)$/);
      if(userAction&&req.method==='POST'){if(!rights.users)fail(403,'Chỉ quản trị');const body=accounts.resolve(await readBody(req)),target=one('SELECT * FROM users WHERE id=? AND deleted_at IS NULL',userAction[1]);if(!target)fail(404,'Không tìm thấy tài khoản');if(userAction[2]==='disable'){if(target.id===user.id)fail(400,'Không tự khóa tài khoản đang dùng');run('UPDATE users SET active=0 WHERE id=?',target.id);}else if(userAction[2]==='enable'){run('UPDATE users SET active=1 WHERE id=?',target.id);}else if(userAction[2]==='access'){const sectionAccess=accessValue(body);accounts.validateDelegation(body);formulaAccess.validateRights(body);if(!ROLES.includes(body.role))fail(400,'Vai trò không hợp lệ');if(target.id===user.id&&body.role!=='admin')fail(400,'Không tự hạ quyền quản trị đang dùng');formulaAccess.saveRights(target.id,body);run('UPDATE users SET section_access=?,role_template_id=?,technical_delegated=? WHERE id=?',sectionAccess,body.roleTemplateId,Number(body.technicalDelegation===true),target.id);run('UPDATE users SET role=?,can_factors=?,can_below_cost=? WHERE id=?',body.role,body.canEditFactors==null?null:Number(!!body.canEditFactors),body.canApproveBelowCost==null?null:Number(!!body.canApproveBelowCost),target.id);for(const [field,column]of [['canViewCosts','can_view_costs'],['canApprove','can_approve']])run('UPDATE users SET '+column+'=? WHERE id=?',body[field]==null?null:Number(!!body[field]),target.id);}else{const pw=String(body.password||'');if(pw.length<12||pw.length>200)fail(400,'Mật khẩu cần 12–200 ký tự');const salt=randomBytes(16).toString('hex');run('UPDATE users SET password=? WHERE id=?',salt+':'+scryptSync(pw,salt,64).toString('hex'),target.id);}run('DELETE FROM sessions WHERE user_id=?',target.id);audit(user,userAction[2],target.id);return send(200,{ok:true});}
      if(route==='/api/quotes'&&req.method==='GET'){if(!rights.costs)return send(200,all("SELECT r.* FROM revisions r WHERE r.status='approved' AND r.version=(SELECT MAX(x.version) FROM revisions x WHERE x.id=r.id AND x.status='approved') ORDER BY r.at DESC").map(r=>{const o=offerRecord(r);return {id:r.id,code:o.offer.code,customer:o.offer.customer,project:o.offer.project,version:r.version,status:'approved',total:o.offer.totals.grand,date:o.offer.date,commercialStatus:workflow.describe(r.id,o.offer).status,updated:r.at,actor:''};}));return send(200,all('SELECT q.id,q.code,q.customer,q.project,q.version,q.status,q.total,q.updated,q.document,u.name AS actor FROM quotes q LEFT JOIN users u ON u.id=q.actor ORDER BY q.updated DESC').map(({document,...row})=>{const q=JSON.parse(document).quote;const trade=workflow.describe(row.id,q),sent=trade.events.filter(e=>e.to==='sent');return {...row,date:q.date,commercialStatus:trade.status,progress:{...notifications.summary({...row,document}),sentCount:sent.length,lastSentAt:sent.at(-1)?.at||null}};}));}
      const orderRoute=route.match(/^\/api\/quotes\/([a-f0-9-]+)\/order$/);
      if(orderRoute&&req.method==='POST'){
        if(!rights.manage)fail(403,'Không có quyền tạo đơn hàng');const body=await readBody(req),quote=getQuote(orderRoute[1]);
        const order=transaction(()=>{const existing=one('SELECT * FROM orders WHERE quote_id=?',quote.id);if(existing){if(existing.quote_version!==body.expectedVersion)fail(409,'Báo giá đã có đơn hàng; cần xử lý thay đổi đơn hàng riêng');return {...existing,existing:true};}
          if(quote.version!==body.expectedVersion||quote.status!=='approved')fail(409,'Chỉ chuyển đúng phiên bản đã duyệt');const code=String(body.code||'').trim();if(!code||code.length>100)fail(400,'Nhập mã đơn hàng');if(one('SELECT id FROM orders WHERE code=?',code))fail(409,'Mã đơn hàng đã tồn tại');const document=JSON.parse(quote.document),result=cleanDocument(document).result,id=randomUUID(),at=new Date().toISOString();
          const packet={format:'truongphat-order-handoff-1',id,code,quoteId:quote.id,quoteCode:quote.code,quoteVersion:quote.version,status:'awaiting-production',customer:quote.customer,project:quote.project,at,quote:document.quote,baseline:document.quote.approvedBaseline||result.total,offer:document.quote.approvedOffer||publicOffer(document,result),packages:result.packages,operations:Object.values(result.nodes).flatMap(r=>(r.ownOps||[]).map(op=>({...op,ownerId:r.node.id}))),materials:result.rows.map(r=>({materialId:r.spec.id,name:r.node.name,productId:r.productId,count:r.count,geometry:r.geometry,purchaseWeight:r.purchasedWeight,externallySupplied:!!r.externallySupplied,coveredBy:r.coveredBy,cost:r.cost,spec:r.spec})),finishing:result.generated,logistics:result.logistics.items,deviceInstallations:result.devices.items};
          run('INSERT INTO orders(id,code,quote_id,quote_version,package,at,actor) VALUES(?,?,?,?,?,?,?)',id,code,quote.id,quote.version,JSON.stringify(packet),at,user.id);audit(user,'create-order',id,quote.code+' v'+quote.version);return {id,code,quote_id:quote.id,quote_version:quote.version,package:JSON.stringify(packet),at,actor:user.id};
        });return send(order.existing?200:201,{id:order.id,code:order.code,quoteVersion:order.quote_version,existing:!!order.existing,package:JSON.parse(order.package)});
      }
      if(route==='/api/orders'&&req.method==='GET')return send(200,all('SELECT id,code,quote_id,quote_version,at,actor FROM orders ORDER BY at DESC'));
      const orderGet=route.match(/^\/api\/orders\/([a-f0-9-]+)$/);if(orderGet&&req.method==='GET'){const o=one('SELECT * FROM orders WHERE id=?',orderGet[1]);if(!o)fail(404,'Không tìm thấy đơn hàng');if(!rights.costs){const revision=one('SELECT * FROM revisions WHERE id=? AND version=?',o.quote_id,o.quote_version);return send(200,{id:o.id,code:o.code,quoteVersion:o.quote_version,offer:offerRecord(revision).offer});}return send(200,JSON.parse(o.package));}
      if(route==='/api/quotes'&&req.method==='POST'){if(!rights.manage)fail(403,'Không có quyền lập báo giá');const body=await readBody(req);return send(201,saveQuote(null,body.document,user,null,'draft','Tạo báo giá',body.autoCode===true));}
      const match=route.match(/^\/api\/quotes\/([a-f0-9-]+)(?:\/(submit|approve|reopen|restore|revisions|revision\/(\d+)))?$/);
      if(match){const id=match[1],action=match[2],q=getQuote(id);
        if(req.method==='GET'&&!action)return send(200,rights.costs?{id,version:q.version,status:q.status,document:JSON.parse(q.document)}:currentOffer(id));
        if(req.method==='GET'&&action==='revisions')return send(200,rights.costs?all('SELECT r.version,r.status,r.total,r.at,r.reason,u.name AS actor FROM revisions r LEFT JOIN users u ON u.id=r.actor WHERE r.id=? ORDER BY r.version DESC',id):all("SELECT version,status,total,at FROM revisions WHERE id=? AND status='approved' ORDER BY version DESC",id));
        if(req.method==='GET'&&match[3]){const r=one('SELECT id,document,version,status FROM revisions WHERE id=? AND version=?',id,Number(match[3]));if(!r)fail(404,'Không có phiên bản');if(!rights.costs){if(r.status!=='approved')fail(403,'Chỉ được xem phiên bản đã duyệt');return send(200,offerRecord(r));}return send(200,{id,version:r.version,status:r.status,document:JSON.parse(r.document),readOnly:true});}
        if(req.method==='PUT'&&!action){if(!rights.edit)fail(403,'Không có quyền sửa');if(q.status!=='draft')fail(409,'Bản đã trình/duyệt được khóa. Tạo bản sửa trước.');const body=await readBody(req);return send(200,saveQuote(id,body.document,user,body.expectedVersion,'draft','Lưu bản nháp'));}
        if(req.method==='POST'&&action==='restore'){if(!rights.reopen)fail(403,'Chưa có quyền mở sửa báo giá sau hoàn thiện');const body=await readBody(req);if(!String(body.reason||'').trim())fail(400,'Nhập lý do dùng lại phiên bản');if(!Number.isInteger(body.sourceVersion)||body.sourceVersion<1)fail(400,'Phiên bản nguồn chưa hợp lệ');const source=one('SELECT document FROM revisions WHERE id=? AND version=?',id,body.sourceVersion);if(!source)fail(404,'Không có phiên bản nguồn');return send(200,saveQuote(id,JSON.parse(source.document),user,body.expectedVersion,'draft','Dùng lại bản '+body.sourceVersion+': '+String(body.reason).slice(0,900)));}
        if(req.method==='POST'&&['submit','approve','reopen'].includes(action)){const body=await readBody(req);if(action==='approve'?!rights.approve:action==='reopen'?!rights.reopen:!rights.manage)fail(403,'Không có quyền thực hiện');if(action==='submit'&&q.status!=='draft'||action==='approve'&&q.status!=='submitted'||action==='reopen'&&q.status==='draft')fail(409,'Trạng thái không phù hợp');if(action==='reopen'&&!String(body.reason||'').trim())fail(400,'Nhập lý do sửa lại');const document=JSON.parse(q.document);if(action==='approve'){const result=cleanDocument(document).result;if(result.warnings.length&&!rights.belowCost)fail(403,'Tài khoản chưa được cấp quyền duyệt dưới giá gốc');if(result.warnings.length&&!body.acknowledgeBelowCost)fail(422,'Giá dưới gốc; người duyệt phải xác nhận rõ');if(result.warnings.length&&!String(body.reason||'').trim())fail(400,'Cần lý do duyệt giá dưới gốc');}
          return send(200,saveQuote(id,document,user,body.expectedVersion,{submit:'submitted',approve:'approved',reopen:'draft'}[action],String(body.reason||action).slice(0,1000)));
        }
      }
      if(route==='/api/audit'&&req.method==='GET'){if(!rights.users)fail(403,'Chỉ quản trị');return send(200,all('SELECT a.at,u.name,a.action,a.entity,a.detail FROM audit a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.seq DESC LIMIT 500'));}
      if(route==='/api/backup'&&req.method==='GET'){if(!rights.users)fail(403,'Chỉ quản trị');audit(user,'backup','workspace');return send(200,{format:'truongphat-server-backup-1',at:new Date().toISOString(),quotes:all('SELECT * FROM quotes'),revisions:all('SELECT * FROM revisions'),orders:all('SELECT * FROM orders'),catalog:all('SELECT * FROM catalog'),catalogRevisions:all('SELECT * FROM catalog_revisions'),commercial:all('SELECT * FROM commercial'),customers:all('SELECT * FROM intake_customers'),customerPolicy:all('SELECT * FROM customer_policy'),roleTemplates:all('SELECT * FROM role_templates'),formulaLocks:all('SELECT * FROM formula_locks'),handoffs:all('SELECT * FROM quote_handoffs'),handoffEvents:all('SELECT * FROM handoff_events'),notifications:all('SELECT * FROM notifications'),audit:all('SELECT * FROM audit'),users:all('SELECT id,username,name,role,active,can_factors,can_below_cost,can_view_costs,can_approve,technical_delegated,section_access,role_template_id,can_formula_use,can_formula_view,can_formula_edit,can_formula_unlock,can_reopen,deleted_at FROM users')});}
      fail(404,'Không tìm thấy chức năng');
    }catch(error){if(!res.headersSent)send(error.status||500,{error:error.status?error.message:'Không thực hiện được; kiểm tra dữ liệu hoặc máy chủ'});else res.end();}
  });
  server.headersTimeout=15000;server.requestTimeout=30000;
  server.on('close',()=>sql.close());return {server,sql};
}
module.exports={createApp,cleanDocument};
if(require.main===module){
 const publicOrigin=process.env.TP_PUBLIC_ORIGIN||'',databasePath=path.resolve(process.env.TP_DATABASE_PATH||path.join(__dirname,'../data/truongphat.sqlite')),port=Number(process.env.PORT||process.env.TP_PORT||4174),host=publicOrigin?'0.0.0.0':'127.0.0.1';
 if(process.env.RAILWAY_ENVIRONMENT_ID&&(!publicOrigin||!process.env.RAILWAY_VOLUME_MOUNT_PATH||!databasePath.startsWith(process.env.RAILWAY_VOLUME_MOUNT_PATH+'/')))throw Error('Railway cần HTTPS và cơ sở dữ liệu trên volume cố định');
 const {server}=createApp({databasePath,publicOrigin,setupKey:process.env.TP_SETUP_KEY||''});
 server.listen(port,host,()=>console.log('Truong Phat team server listening on port '+port));
 const stop=()=>server.close(()=>process.exit(0));process.on('SIGTERM',stop);process.on('SIGINT',stop);
}
