'use strict';
const {randomUUID}=require('node:crypto');
const SA=require('../section-access.js');
const ORDER_STATES={draft:'Chờ xử lý',waiting:'Chờ sản xuất',producing:'Đang sản xuất',completed:'Hoàn thành',delivered:'Đã giao',cancelled:'Đã hủy'};
function createBusiness({sql,fail,readBody,transaction,audit}){
 sql.exec(`CREATE TABLE IF NOT EXISTS business_records(kind TEXT NOT NULL,id TEXT NOT NULL,version INTEGER NOT NULL,document TEXT NOT NULL,PRIMARY KEY(kind,id));
 CREATE TABLE IF NOT EXISTS business_files(id TEXT PRIMARY KEY,name TEXT NOT NULL,mime TEXT NOT NULL,data TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL);`);
 const all=(s,...a)=>sql.prepare(s).all(...a),one=(s,...a)=>sql.prepare(s).get(...a);
 const records=kind=>all('SELECT * FROM business_records WHERE kind=?',kind).map(unpack);
 function unpack(r){return {...JSON.parse(r.document),id:r.id,version:r.version};}
 const get=(kind,id)=>{const r=one('SELECT * FROM business_records WHERE kind=? AND id=?',kind,id);return r?unpack(r):null;};
 function put(kind,id,doc,version){sql.prepare('INSERT INTO business_records VALUES(?,?,?,?) ON CONFLICT(kind,id) DO UPDATE SET version=excluded.version,document=excluded.document').run(kind,id,version,JSON.stringify(doc));return {...doc,id,version};}
 const str=(v,max=200,required=false)=>{if(typeof v!=='string'||v.length>max||required&&!v.trim())fail(400,'Nội dung thiếu hoặc quá dài');return v.trim();};
 const date=v=>{v=str(v,10);if(v&&(!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v+'T00:00:00Z'))||new Date(v+'T00:00:00Z').toISOString().slice(0,10)!==v))fail(400,'Ngày không hợp lệ');return v;};
 const money=v=>{if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>1e15)fail(400,'Số tiền không hợp lệ');return Math.round(v*100)/100;};
 function allowed(user,write=false){const p=require('./access.cjs').permissions(user),m=SA.modes(user);return user.role==='admin'||['sales','estimator','approver'].includes(user.role)&&m.commercial!=='none'&&m.customer!=='none'&&(!write||p.commercial&&user.role!=='approver');}
 function customer(id){const r=one('SELECT document FROM intake_customers WHERE id=?',id);if(!r)fail(400,'Chọn hồ sơ khách hàng có thật');return JSON.parse(r.document);}
 function order(id){const r=one('SELECT * FROM orders WHERE id=?',id);if(!r)fail(404,'Không tìm thấy đơn hàng');const p=JSON.parse(r.package),meta=get('order',id)||{version:0},jobs=all('SELECT id,code,product_id,quantity,state FROM production_jobs WHERE order_id=?',id),products=p.quote?.products||[],done=products.length>0&&products.every(n=>jobs.filter(j=>j.product_id===n.id&&j.state==='completed').reduce((s,j)=>s+j.quantity,0)>=n.qty-1e-9),state=meta.cancelledAt?'cancelled':meta.deliveredAt?'delivered':done?'completed':jobs.some(j=>['running','qc','completed'].includes(j.state))?'producing':p.status==='draft'?'draft':'waiting';
 return {id:r.id,code:r.code,quoteId:r.quote_id,quoteVersion:r.quote_version,quoteCode:p.quoteCode,customerId:p.quote?.customerInfo?.id||'',customer:p.customer,project:p.project,at:r.at,offer:p.offer,status:state,statusLabel:ORDER_STATES[state],jobs,meta,version:meta.version,steps:[true,true,jobs.length>0,jobs.some(j=>['running','qc','completed'].includes(j.state)),jobs.some(j=>['qc','completed'].includes(j.state)),done,!!meta.deliveredAt]};}
 function contractView(c,user){const payments=records('payment').filter(p=>p.contractId===c.id&&!p.voidedAt),paid=payments.reduce((s,p)=>s+p.amount,0),today=new Date(Date.now()+7*3600000).toISOString().slice(0,10),costs=records('cost').filter(p=>p.contractId===c.id&&!p.voidedAt),value=c.value,remaining=Math.max(0,value-paid);const out={...c,paid,remaining,overdue:!!c.dueDate&&c.dueDate<today&&remaining>0&&c.status==='active',expiring:!!c.endDate&&c.endDate>=today&&c.endDate<=new Date(Date.now()+30*86400000+7*3600000).toISOString().slice(0,10),effective:c.status==='active'&&c.startDate<=today&&(!c.endDate||c.endDate>=today),payments};const cost=costs.reduce((s,p)=>s+p.amount,0),meta=c.orderId?(get('order',c.orderId)||{}):{};out.commission=require('../business-commission-core.js').calculate({value,paid,cost,reviewed:!!c.costReview&&c.costReview.amount===cost,policy:meta.commissionPolicy,shares:meta.salespeople});if(require('./access.cjs').permissions(user).costs){out.costs=costs;out.actualCost=cost;}else {delete out.costReview;if(out.commission.ready){out.commission.rows=out.commission.rows.filter(r=>r.userId===user.id);out.commission.earned=out.commission.rows.reduce((s,r)=>s+r.amount,0);}}return out;}
 function cas(old,b){if(b.expectedVersion!==(old?.version||0))fail(409,'Dữ liệu đã thay đổi; tải lại trước khi lưu');}
 async function handle({req,route,user,send}){
  if(!route.startsWith('/api/business/'))return false;
  const url=new URL(req.url,'http://localhost'),path=url.pathname.slice('/api/business/'.length),write=!['GET','HEAD'].includes(req.method),profile=path.startsWith('profile')||path.startsWith('files');
  if(profile){if(write&&user.role!=='admin'||!write&&!allowed(user))fail(403,'Chưa có quyền hồ sơ năng lực');}else if(!allowed(user,write))fail(403,'Chưa có quyền quản lý kinh doanh');
  if(path==='orders'&&req.method==='GET'){send(200,all('SELECT id FROM orders ORDER BY at DESC').map(r=>order(r.id)));return true;}
  const om=path.match(/^orders\/([a-f0-9-]+)(?:\/(deliver|cancel|metadata))?$/);
  if(om){if(req.method==='GET'&&!om[2]){send(200,order(om[1]));return true;}if(req.method!=='POST'||!om[2])fail(405,'Phương thức không hỗ trợ');const b=await readBody(req);const o=transaction(()=>{const o=order(om[1]);cas(o.meta,b);let meta={...o.meta};delete meta.version;const at=new Date().toISOString();
   if(om[2]==='deliver'){if(!['completed','delivered'].includes(o.status))fail(409,'Chỉ xác nhận giao khi toàn bộ số lượng đã hoàn thành sản xuất');if(!meta.deliveredAt){meta.deliveredAt=at;meta.deliveryDate=date(b.date);if(!meta.deliveryDate)fail(400,'Nhập ngày giao');meta.receiver=str(b.receiver,200,true);meta.deliveryNote=str(b.note||'',2000);meta.deliveredBy=user.id;}}
   if(om[2]==='cancel'){if(user.role!=='admin')fail(403,'Chỉ quản trị hủy đơn');if(o.jobs.length||o.meta.deliveredAt||records('contract').some(c=>c.orderId===o.id&&c.status!=='cancelled'))fail(409,'Đơn đã phát sinh lệnh hoặc hợp đồng; cần xử lý chứng từ liên quan trước');meta.cancelledAt=at;meta.cancelReason=str(b.reason,2000,true);const p=JSON.parse(one('SELECT package FROM orders WHERE id=?',o.id).package);p.status='cancelled';sql.prepare('UPDATE orders SET package=? WHERE id=?').run(JSON.stringify(p),o.id);}
   if(om[2]==='metadata'){meta.dueDate=date(b.dueDate||'');meta.note=str(b.note||'',3000);if(!Array.isArray(b.salespeople)||b.salespeople.length>30)fail(400,'Danh sách phụ trách không hợp lệ');const ids=new Set();meta.salespeople=b.salespeople.map(s=>{if(ids.has(s.userId)||!one('SELECT id FROM users WHERE id=? AND active=1',s.userId))fail(400,'Người phụ trách trùng hoặc không hoạt động');ids.add(s.userId);const percent=money(s.percent);if(percent>100)fail(400,'Tỷ lệ vượt 100%');return {userId:s.userId,percent};});if(meta.salespeople.length&&Math.abs(meta.salespeople.reduce((s,p)=>s+p.percent,0)-100)>0.001)fail(400,'Tổng tỷ lệ phụ trách phải bằng 100%');}
   put('order',o.id,meta,o.version+1);audit(user,'order:'+om[2],o.id,JSON.stringify(meta));return order(o.id);});send(200,o);return true;}
  if(path==='contracts'&&req.method==='GET'){send(200,records('contract').map(c=>contractView(c,user)));return true;}
  if(path==='commission-policies'){if(user.role!=='admin')fail(403,'Chỉ quản trị khai chính sách hưởng');if(req.method==='GET'){send(200,records('commission-policy'));return true;}if(req.method!=='POST')fail(405,'Phương thức không hỗ trợ');const b=await readBody(req);send(200,transaction(()=>{const v=b.document||{},old=v.id?get('commission-policy',v.id):null;cas(old,b);const number=(x,min,max)=>{if(typeof x!=='number'||!Number.isFinite(x)||x<min||x>max)fail(400,'Ngưỡng chính sách không hợp lệ');return x;};const policy={name:str(v.name,200,true),minValue:money(v.minValue),maxValue:v.maxValue===null?null:money(v.maxValue),minMargin:number(v.minMargin,-10000,100),maxMargin:v.maxMargin===null?null:number(v.maxMargin,-10000,100),rate:number(v.rate,0,100),basis:v.basis,active:v.active!==false};if(!['value','profit'].includes(policy.basis)||policy.maxValue!==null&&policy.maxValue<policy.minValue||policy.maxMargin!==null&&policy.maxMargin<policy.minMargin)fail(400,'Khoảng điều kiện không hợp lệ');const saved=put('commission-policy',old?.id||randomUUID(),policy,(old?.version||0)+1);audit(user,'commission-policy:save',saved.id,JSON.stringify(policy));return saved;}));return true;}
  const commissionOrder=path.match(/^orders\/([a-f0-9-]+)\/commission$/);if(commissionOrder&&req.method==='POST'){if(user.role!=='admin')fail(403,'Chỉ quản trị chốt chính sách hưởng');const b=await readBody(req);send(200,transaction(()=>{const o=order(commissionOrder[1]);cas(o.meta,b);const policy=get('commission-policy',b.policyId);if(!policy||!policy.active)fail(400,'Chọn chính sách đang áp dụng');put('order',o.id,{...o.meta,commissionPolicy:policy},o.version+1);audit(user,'order:commission',o.id,JSON.stringify(policy));return order(o.id);}));return true;}
  const costReview=path.match(/^contracts\/([a-f0-9-]+)\/review-costs$/);if(costReview&&req.method==='POST'){if(user.role!=='admin')fail(403,'Chỉ quản trị chốt chi phí thực tế');const b=await readBody(req);send(200,transaction(()=>{const c=get('contract',costReview[1]);if(!c)fail(404,'Không tìm thấy hợp đồng');cas(c,b);const costs=records('cost').filter(p=>p.contractId===c.id&&!p.voidedAt),total=costs.reduce((s,p)=>s+p.amount,0);if(b.amount!==total)fail(409,'Chi phí đã đổi; rà soát lại');const saved=put('contract',c.id,{...c,costReview:{amount:total,at:new Date().toISOString(),actor:user.id,reason:str(b.reason,2000,true)}},c.version+1);audit(user,'contract:review-costs',c.id,JSON.stringify(saved.costReview));return contractView(saved,user);}));return true;}
  const cm=path.match(/^contracts(?:\/([a-f0-9-]+))?$/);
  if(cm){if(req.method==='GET'&&cm[1]){const c=get('contract',cm[1]);if(!c)fail(404,'Không tìm thấy hợp đồng');send(200,contractView(c,user));return true;}if(req.method!=='POST')fail(405,'Phương thức không hỗ trợ');const b=await readBody(req),saved=transaction(()=>{const old=cm[1]?get('contract',cm[1]):null;if(cm[1]&&!old)fail(404,'Không tìm thấy hợp đồng');cas(old,b);const v=b.document||{},id=old?.id||randomUUID(),code=str(v.code,100,true),cid=str(v.customerId,100,true),cust=customer(cid);if(records('contract').some(c=>c.id!==id&&c.code.toLowerCase()===code.toLowerCase()))fail(409,'Số hợp đồng đã tồn tại');const orderId=str(v.orderId||'',100),o=orderId?order(orderId):null;if(o&&(o.customerId!==cid||['draft','cancelled'].includes(o.status)))fail(400,'Chọn đơn đã chốt của đúng khách hàng');if(o&&records('contract').some(c=>c.id!==id&&c.orderId===orderId&&c.status!=='cancelled'))fail(409,'Đơn hàng đã có hợp đồng');
   const c={code,customerId:cid,customerName:cust.name,orderId,quoteId:o?.quoteId||'',quoteVersion:o?.quoteVersion||null,quoteCode:o?.quoteCode||'',value:money(v.value),type:str(v.type||'',100),signDate:date(v.signDate||''),startDate:date(v.startDate||''),endDate:date(v.endDate||''),dueDate:date(v.dueDate||''),status:v.status,terms:str(v.terms||'',20000),note:str(v.note||'',4000),updatedAt:new Date().toISOString(),updatedBy:user.id,createdAt:old?.createdAt||new Date().toISOString()};
   if(!['draft','active','completed','cancelled'].includes(c.status))fail(400,'Trạng thái không hợp lệ');if(c.status!=='draft'&&(!c.signDate||!c.startDate))fail(400,'Khai ngày ký và ngày hiệu lực');if(c.endDate&&c.endDate<c.startDate)fail(400,'Ngày hết hạn trước ngày hiệu lực');const payments=records('payment').filter(p=>p.contractId===id&&!p.voidedAt),costs=records('cost').filter(p=>p.contractId===id&&!p.voidedAt);if(old&&(payments.length||costs.length)&&(cid!==old.customerId||orderId!==old.orderId||c.status==='cancelled'))fail(409,'Đã phát sinh thu/chi; không được đổi liên kết hoặc hủy');if(c.value<payments.reduce((s,p)=>s+p.amount,0))fail(400,'Giá trị nhỏ hơn số đã thu');if(c.status==='completed'&&payments.reduce((s,p)=>s+p.amount,0)<c.value)fail(409,'Chưa thanh toán đủ để tất toán');const result=put('contract',id,c,(old?.version||0)+1);audit(user,'contract:save',id,JSON.stringify({before:old,after:c}));return result;});send(200,contractView(saved,user));return true;}
  if(['payments','costs'].includes(path)&&req.method==='POST'){if(user.role!=='admin')fail(403,'Chỉ quản trị ghi nhận thu/chi thực tế');const b=await readBody(req),kind=path==='payments'?'payment':'cost',saved=transaction(()=>{const c=get('contract',b.contractId);if(!c)fail(404,'Không tìm thấy hợp đồng');const token=str(b.requestId,100,true),existing=get(kind,token);if(existing){if(existing.contractId!==c.id||existing.amount!==b.amount||existing.reference!==b.reference||existing.date!==b.date||existing.category!==(b.category||'')||existing.note!==(b.note||''))fail(409,'Mã thao tác đã dùng cho nội dung khác');return existing;}cas(c,b);if(c.status!=='active')fail(409,'Chỉ ghi thu/chi cho hợp đồng đang thực hiện');const amount=money(b.amount);if(!amount)fail(400,'Số tiền phải lớn hơn 0');const paid=records('payment').filter(p=>p.contractId===c.id&&!p.voidedAt).reduce((s,p)=>s+p.amount,0);if(kind==='payment'&&amount>Math.round((c.value-paid)*100)/100)fail(400,'Số thu vượt công nợ còn lại');const entry={contractId:c.id,amount,date:date(b.date),reference:str(b.reference,200,true),category:str(b.category||'',100),note:str(b.note||'',3000),actor:user.id,at:new Date().toISOString()};if(!entry.date)fail(400,'Nhập ngày chứng từ');if(records(kind).some(p=>!p.voidedAt&&p.reference===entry.reference))fail(409,'Số chứng từ đã được ghi nhận');if(kind==='cost')delete c.costReview;put('contract',c.id,c,c.version+1);const out=put(kind,token,entry,1);audit(user,kind+':create',token,JSON.stringify(entry));return out;});send(200,saved);return true;}
  const vm=path.match(/^(payments|costs)\/([a-zA-Z0-9_-]+)\/void$/);if(vm&&req.method==='POST'){if(user.role!=='admin')fail(403,'Chỉ quản trị điều chỉnh chứng từ');const b=await readBody(req);send(200,transaction(()=>{const kind=vm[1]==='payments'?'payment':'cost',p=get(kind,vm[2]);if(!p)fail(404,'Không tìm thấy chứng từ');cas(p,b);const c=get('contract',p.contractId);if(c.status==='completed')fail(409,'Mở lại hợp đồng trước khi điều chỉnh');const out=put(kind,p.id,{...p,voidedAt:new Date().toISOString(),voidReason:str(b.reason,2000,true),voidedBy:user.id},p.version+1);if(kind==='cost')delete c.costReview;put('contract',c.id,c,c.version+1);audit(user,kind+':void',p.id,b.reason);return out;}));return true;}
  if(path.startsWith('customers/')&&req.method==='GET'){const id=path.slice(10),c=customer(id),contracts=records('contract').filter(c=>c.customerId===id).map(c=>contractView(c,user)),orders=all('SELECT id FROM orders').map(r=>order(r.id)).filter(o=>o.customerId===id);send(200,{customerId:id,ownerId:c.ownerId||'',orders,contracts,receivable:contracts.filter(c=>['active','completed'].includes(c.status)).reduce((s,c)=>s+c.remaining,0),collected:contracts.filter(c=>['active','completed'].includes(c.status)).reduce((s,c)=>s+c.paid,0),overdue:contracts.filter(c=>c.overdue).reduce((s,c)=>s+c.remaining,0)});return true;}
  const removeCustomer=path.match(/^customers\/([a-zA-Z0-9_-]+)\/delete$/);
  if(removeCustomer&&req.method==='POST'){if(user.role!=='admin')fail(403,'Chỉ quản trị xóa hồ sơ khách hàng');const b=await readBody(req);send(200,transaction(()=>{const id=removeCustomer[1],row=one('SELECT * FROM intake_customers WHERE id=?',id);if(!row)fail(404,'Không tìm thấy khách hàng');cas(row,b);if(all('SELECT document FROM quotes').some(q=>JSON.parse(q.document).quote?.customerInfo?.id===id)||records('contract').some(c=>c.customerId===id)||all('SELECT id FROM orders').some(o=>order(o.id).customerId===id))fail(409,'Khách đã có giao dịch; chuyển trạng thái Ngừng giao dịch để giữ hồ sơ');const reason=str(b.reason,2000,true);put('deleted-customer',id,{document:JSON.parse(row.document),deletedAt:new Date().toISOString(),deletedBy:user.id,reason},row.version+1);sql.prepare('DELETE FROM intake_customers WHERE id=?').run(id);audit(user,'customer:delete',id,reason);return {deleted:true};}));return true;}
  if(path==='people'&&req.method==='GET'){send(200,all('SELECT id,name FROM users WHERE active=1 ORDER BY name'));return true;}
  if(path==='profile'&&req.method==='GET'){const p=get('profile','company')||{id:'company',version:0,company:{},machines:[],staff:[],certificates:[],projects:[]},org=one('SELECT document FROM organization WHERE id=1'),departments=org?JSON.parse(org.document).departments:[];send(200,{...p,structure:departments.filter(d=>d.active!==false).map(d=>({id:d.id,name:d.name,parentId:d.parentId||null}))});return true;}
  if(path==='profile'&&req.method==='POST'){const b=await readBody(req,2000000);send(200,transaction(()=>{const old=get('profile','company');cas(old,b);const v=b.document||{},company={};for(const k of ['name','taxId','address','phone','email','industry','introduction','organization'])company[k]=str(v.company?.[k]||'',k==='introduction'||k==='organization'?20000:500);const out={company};const fields={machines:['name','specification','capacity','year'],staff:['department','position','count','qualification'],certificates:['name','number','issuer','date','expires'],projects:['name','owner','value','scope','start','end']};for(const [kind,keys]of Object.entries(fields)){if(!Array.isArray(v[kind])||v[kind].length>1000)fail(400,'Danh sách hồ sơ không hợp lệ');out[kind]=v[kind].map(r=>{const x={id:str(r.id||randomUUID(),100)};for(const k of keys)x[k]=str(r[k]||'',4000);if(!x[keys[0]])fail(400,'Nhập tên nội dung');if(kind==='staff'&&(!/^\d+$/.test(x.count)||Number(x.count)>100000))fail(400,'Số nhân sự không hợp lệ');if(kind==='machines'&&x.year&&!/^\d{4}$/.test(x.year))fail(400,'Năm đầu tư không hợp lệ');for(const k of ['date','expires','start','end'])if(x[k])date(x[k]);if(x.start&&x.end&&x.end<x.start||x.date&&x.expires&&x.expires<x.date)fail(400,'Khoảng ngày không hợp lệ');if(r.files!==undefined&&(!Array.isArray(r.files)||r.files.some(f=>typeof f!=='string')))fail(400,'Invalid attachments');x.files=(r.files||[]).map(id=>{if(!one('SELECT id FROM business_files WHERE id=?',id))fail(400,'Tài liệu không tồn tại');return id;});if(x.files.length>20)fail(400,'Tối đa 20 tài liệu mỗi mục');return x;});}out.updatedAt=new Date().toISOString();out.updatedBy=user.id;const saved=put('profile','company',out,(old?.version||0)+1);audit(user,'profile:save','company');return saved;}));return true;}
  if(path==='files'&&req.method==='POST'){const b=await readBody(req,8000000),name=str(b.name,200,true),mime=str(b.mime,100),data=str(b.data,7500000,true);if(!['application/pdf','image/png','image/jpeg'].includes(mime)||!/^[A-Za-z0-9+/]+={0,2}$/.test(data))fail(400,'Chỉ nhận PDF, PNG, JPEG');const bytes=Buffer.from(data,'base64');if(bytes.length>5*1024*1024||bytes.length<8)fail(400,'Tài liệu tối đa 5 MB');if(mime==='application/pdf'&&bytes.subarray(0,5).toString()!=='%PDF-'||mime==='image/png'&&bytes.subarray(0,8).toString('hex')!=='89504e470d0a1a0a'||mime==='image/jpeg'&&bytes.subarray(0,3).toString('hex')!=='ffd8ff')fail(400,'Nội dung không khớp định dạng');const id=randomUUID();sql.prepare('INSERT INTO business_files VALUES(?,?,?,?,?,?)').run(id,name,mime,data,user.id,new Date().toISOString());audit(user,'profile:file',id,name);send(201,{id,name,mime});return true;}
  const fm=path.match(/^files\/([a-f0-9-]+)$/);if(fm&&req.method==='GET'){const f=one('SELECT id,name,mime,data FROM business_files WHERE id=?',fm[1]);if(!f)fail(404,'Không tìm thấy tài liệu');send(200,f);return true;}
  fail(404,'Không tìm thấy chức năng kinh doanh');
 }
 return {handle,order,records,allowed};
}
module.exports={createBusiness,ORDER_STATES};
