'use strict';
const {randomUUID}=require('node:crypto');
function createChat({sql,fail,readBody,transaction}){
 sql.exec(`CREATE TABLE IF NOT EXISTS chat_rooms(id TEXT PRIMARY KEY,kind TEXT NOT NULL,title TEXT NOT NULL,owner TEXT NOT NULL REFERENCES users(id),direct_key TEXT UNIQUE,created TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS chat_members(room TEXT NOT NULL REFERENCES chat_rooms(id),user_id TEXT NOT NULL REFERENCES users(id),last_read INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(room,user_id));
 CREATE TABLE IF NOT EXISTS chat_messages(seq INTEGER PRIMARY KEY AUTOINCREMENT,room TEXT NOT NULL REFERENCES chat_rooms(id),sender TEXT NOT NULL REFERENCES users(id),client_id TEXT NOT NULL,body TEXT NOT NULL,image TEXT,mime TEXT,at TEXT NOT NULL,UNIQUE(sender,client_id));
 CREATE INDEX IF NOT EXISTS chat_message_room_seq ON chat_messages(room,seq);`);
 sql.exec(`CREATE TABLE IF NOT EXISTS chat_mentions(seq INTEGER NOT NULL REFERENCES chat_messages(seq),user_id TEXT NOT NULL REFERENCES users(id),PRIMARY KEY(seq,user_id));
 CREATE TABLE IF NOT EXISTS chat_tasks(id TEXT PRIMARY KEY,room TEXT NOT NULL REFERENCES chat_rooms(id),message_seq INTEGER NOT NULL REFERENCES chat_messages(seq),creator TEXT NOT NULL REFERENCES users(id),assignee TEXT NOT NULL REFERENCES users(id),body TEXT NOT NULL,deadline TEXT NOT NULL,state TEXT NOT NULL,version INTEGER NOT NULL,created TEXT NOT NULL,updated TEXT NOT NULL,UNIQUE(message_seq,creator));`);
 const one=(s,...a)=>sql.prepare(s).get(...a),all=(s,...a)=>sql.prepare(s).all(...a),run=(s,...a)=>sql.prepare(s).run(...a);
 if(!all('PRAGMA table_info(chat_messages)').some(c=>c.name==='reply_to'))sql.exec('ALTER TABLE chat_messages ADD COLUMN reply_to INTEGER');
 if(!all('PRAGMA table_info(sessions)').some(c=>c.name==='chat_seen'))sql.exec('ALTER TABLE sessions ADD COLUMN chat_seen INTEGER NOT NULL DEFAULT 0');
 const presence=rows=>rows.map(u=>({...u,online:!!one('SELECT 1 FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.user_id=? AND u.active=1 AND s.expires>? AND s.chat_seen>? LIMIT 1',u.id,Date.now(),Date.now()-75000)}));
 const member=(room,user)=>{if(!one('SELECT 1 FROM chat_members WHERE room=? AND user_id=?',room,user.id))fail(404,'Không tìm thấy hội thoại hoặc bạn không còn là thành viên');return one('SELECT * FROM chat_rooms WHERE id=?',room);};
 const members=room=>presence(all('SELECT u.id,u.name,u.active,m.last_read AS readSeq FROM chat_members m JOIN users u ON u.id=m.user_id WHERE m.room=? ORDER BY u.name',room));
 const activeIds=ids=>{if(!Array.isArray(ids)||ids.length>100||ids.some(x=>typeof x!=='string'))fail(400,'Chọn tối đa 100 thành viên');const unique=[...new Set(ids)];for(const id of unique)if(!one('SELECT 1 FROM users WHERE id=? AND active=1',id))fail(400,'Thành viên không còn hoạt động');return unique;};
 const brief=(r,user)=>{const last=one('SELECT seq,body,sender,at,mime FROM chat_messages WHERE room=? ORDER BY seq DESC LIMIT 1',r.id);return {id:r.id,kind:r.kind,title:r.title,owner:r.owner,created:r.created,members:members(r.id),last:last?{...last,body:last.body.slice(0,160),hasImage:!!last.mime,mentions:all('SELECT user_id FROM chat_mentions WHERE seq=?',last.seq).map(x=>x.user_id)}:null,unread:one('SELECT COUNT(*) n FROM chat_messages WHERE room=? AND seq>(SELECT last_read FROM chat_members WHERE room=? AND user_id=?) AND sender<>?',r.id,r.id,user.id,user.id).n};};
 const message=r=>({seq:r.seq,room:r.room,sender:r.sender,name:r.name,body:r.body,at:r.at,hasImage:!!r.mime,reply:r.reply_to?one('SELECT m.seq,m.sender,u.name,substr(m.body,1,500) AS body,(m.mime IS NOT NULL) AS hasImage FROM chat_messages m JOIN users u ON u.id=m.sender WHERE m.seq=? AND m.room=?',r.reply_to,r.room):null,mentions:all('SELECT user_id FROM chat_mentions WHERE seq=?',r.seq).map(x=>x.user_id)});
 const title=s=>{if(typeof s!=='string'||!s.trim()||s.trim().length>80)fail(400,'Tên nhóm cần 1–80 ký tự');return s.trim();};
 return {async handle({req,route,user,send,res}){
 if(!route.startsWith('/api/chat/'))return false;
 const url=new URL(req.url,'http://localhost');if(route==='/api/chat/rooms'&&req.method==='GET')run('UPDATE sessions SET chat_seen=? WHERE token=? AND chat_seen<?',Date.now(),user.token,Date.now()-15000);
 if(route==='/api/chat/users'&&req.method==='GET'){send(200,presence(all('SELECT id,name FROM users WHERE active=1 ORDER BY name')));return true;}
 if(route==='/api/chat/rooms'){
  if(req.method==='GET'){send(200,all('SELECT r.* FROM chat_rooms r JOIN chat_members m ON m.room=r.id WHERE m.user_id=? ORDER BY COALESCE((SELECT MAX(seq) FROM chat_messages WHERE room=r.id),0) DESC,r.created DESC',user.id).map(r=>brief(r,user)));return true;}
  if(req.method==='POST'){const b=await readBody(req,20000),ids=activeIds(b.members);if(!['direct','group'].includes(b.kind))fail(400,'Loại hội thoại không hợp lệ');const people=[...new Set([user.id,...ids])];if(people.length>100)fail(400,'Nhóm tối đa 100 thành viên');if(b.kind==='direct'&&people.length!==2||b.kind==='group'&&people.length<3)fail(400,'Chat riêng cần 2 người; nhóm cần ít nhất 3 người');const name=b.kind==='group'?title(b.title):'',key=b.kind==='direct'?people.sort().join(':'):null;const room=transaction(()=>{const old=key&&one('SELECT * FROM chat_rooms WHERE direct_key=?',key);if(old)return old;if(one('SELECT COUNT(*) n FROM chat_rooms WHERE owner=? AND created>?',user.id,new Date(Date.now()-60000).toISOString()).n>=10)fail(429,'Tạo quá nhiều hội thoại; thử lại sau một phút');const id=randomUUID(),at=new Date().toISOString();run('INSERT INTO chat_rooms VALUES(?,?,?,?,?,?)',id,b.kind,name,user.id,key,at);for(const p of people)run('INSERT INTO chat_members(room,user_id) VALUES(?,?)',id,p);return one('SELECT * FROM chat_rooms WHERE id=?',id);});send(201,brief(room,user));return true;}
 }
 const match=route.match(/^\/api\/chat\/rooms\/([a-f0-9-]+)(?:\/(messages|read|members|tasks))?$/);
 if(match){const id=match[1],action=match[2],room=member(id,user);
  if(!action&&req.method==='GET'){send(200,brief(room,user));return true;}
  if(action==='tasks'&&req.method==='GET'){send(200,all('SELECT t.*,u.name AS assigneeName FROM chat_tasks t JOIN users u ON u.id=t.assignee WHERE room=? ORDER BY created DESC',id));return true;}
  if(action==='tasks'&&req.method==='POST'){const b=await readBody(req,10000);if(!one('SELECT 1 FROM chat_messages WHERE seq=? AND room=?',b.seq,id))fail(404,'Không tìm thấy tin nhắn');if(!members(id).some(m=>m.id===b.assignee&&m.active))fail(400,'Chọn người phụ trách đang ở trong hội thoại');if(typeof b.body!=='string'||!b.body.trim()||b.body.length>5000)fail(400,'Nội dung công việc cần 1–5000 ký tự');if(typeof b.deadline!=='string'||b.deadline&&!/^\d{4}-\d{2}-\d{2}$/.test(b.deadline))fail(400,'Hạn công việc không hợp lệ');const task=transaction(()=>{const old=one('SELECT * FROM chat_tasks WHERE message_seq=? AND creator=?',b.seq,user.id);if(old)return old;const tid=randomUUID(),at=new Date().toISOString();run('INSERT INTO chat_tasks VALUES(?,?,?,?,?,?,?,?,?,?,?)',tid,id,b.seq,user.id,b.assignee,b.body.trim(),b.deadline,'assigned',1,at,at);return one('SELECT * FROM chat_tasks WHERE id=?',tid);});send(201,task);return true;}
  if(action==='members'&&req.method==='PUT'){if(room.kind!=='group'||room.owner!==user.id)fail(403,'Chỉ người tạo nhóm được sửa tên và thành viên');const b=await readBody(req,20000),ids=activeIds(b.members),name=title(b.title);if(!ids.includes(user.id)||ids.length<3)fail(400,'Giữ người tạo nhóm và ít nhất 3 thành viên');transaction(()=>{for(const m of members(id))if(!ids.includes(m.id))run('DELETE FROM chat_members WHERE room=? AND user_id=?',id,m.id);for(const m of ids)run('INSERT OR IGNORE INTO chat_members(room,user_id) VALUES(?,?)',id,m);run('UPDATE chat_rooms SET title=? WHERE id=?',name,id);});send(200,brief(one('SELECT * FROM chat_rooms WHERE id=?',id),user));return true;}
  if(action==='messages'&&req.method==='GET'){const after=Number(url.searchParams.get('after')||0),before=Number(url.searchParams.get('before')||0);if(!Number.isSafeInteger(after)||after<0||!Number.isSafeInteger(before)||before<0)fail(400,'Mốc tin nhắn không hợp lệ');const where=before?'AND seq<?':after?'AND seq>?':'',args=before?[before]:after?[after]:[],order=after&&!before?'ASC':'DESC';let rows=all(`SELECT m.seq,m.room,m.sender,m.client_id,m.reply_to,m.body,m.mime,m.at,u.name FROM chat_messages m JOIN users u ON u.id=m.sender WHERE room=? ${where} ORDER BY seq ${order} LIMIT 61`,id,...args);const more=rows.length>60;rows=rows.slice(0,60);if(order==='DESC')rows.reverse();send(200,{items:rows.map(message),more});return true;}
  if(action==='read'&&req.method==='POST'){const b=await readBody(req,1000),seq=Number(b.seq);if(!Number.isSafeInteger(seq)||seq<0||seq>0&&!one('SELECT 1 FROM chat_messages WHERE room=? AND seq=?',id,seq))fail(400,'Mốc đọc không hợp lệ');run('UPDATE chat_members SET last_read=MAX(last_read,?) WHERE room=? AND user_id=?',seq,id,user.id);send(200,{ok:true});return true;}
  if(action==='messages'&&req.method==='POST'){const b=await readBody(req,4500000);if(typeof b.clientId!=='string'||! /^[a-zA-Z0-9-]{16,80}$/.test(b.clientId))fail(400,'Mã gửi không hợp lệ');const old=one('SELECT m.seq,m.room,m.sender,m.client_id,m.reply_to,m.body,m.mime,m.at,u.name FROM chat_messages m JOIN users u ON u.id=m.sender WHERE sender=? AND client_id=?',user.id,b.clientId);if(old){if(old.room!==id)fail(409,'Mã gửi đã dùng');send(200,message(old));return true;}
   if(typeof b.body!=='string'||b.body.length>5000)fail(400,'Tin nhắn tối đa 5.000 ký tự');const mentionIds=activeIds(b.mentions||[]);if(mentionIds.some(uid=>!members(id).some(m=>m.id===uid)))fail(400,'Chỉ nhắc thành viên của hội thoại');const replyTo=b.replyTo??null;if(replyTo!==null&&(!Number.isSafeInteger(replyTo)||!one('SELECT 1 FROM chat_messages WHERE seq=? AND room=?',replyTo,id)))fail(400,'Tin g\u1ed1c kh\u00f4ng thu\u1ed9c h\u1ed9i tho\u1ea1i n\u00e0y');const body=b.body.trim();let image=null,mime=null;if(b.image){if(typeof b.image!=='string'||b.image.length>4200000)fail(413,'Ảnh tối đa 3 MB');const m=b.image.match(/^data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/]+={0,2})$/);if(!m)fail(400,'Chỉ nhận ảnh PNG, JPEG hoặc WebP');const bytes=Buffer.from(m[2],'base64');if(bytes.length>3*1024*1024||bytes.length<12)fail(400,'Ảnh không hợp lệ hoặc quá 3 MB');const valid=m[1]==='png'?bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):m[1]==='jpeg'?bytes[0]===255&&bytes[1]===216&&bytes[2]===255:bytes.toString('ascii',0,4)==='RIFF'&&bytes.toString('ascii',8,12)==='WEBP';if(!valid)fail(400,'Nội dung ảnh không hợp lệ');image=m[2];mime='image/'+m[1];}if(!body&&!image)fail(400,'Nhập tin nhắn hoặc chọn ảnh');if(one('SELECT COUNT(*) n FROM chat_messages WHERE sender=? AND at>?',user.id,new Date(Date.now()-60000).toISOString()).n>=60)fail(429,'Gửi quá nhanh; chờ một phút rồi thử lại');const seq=Number(run('INSERT INTO chat_messages(room,sender,client_id,body,image,mime,at,reply_to) VALUES(?,?,?,?,?,?,?,?)',id,user.id,b.clientId,body,image,mime,new Date().toISOString(),replyTo).lastInsertRowid);for(const uid of mentionIds)run('INSERT INTO chat_mentions VALUES(?,?)',seq,uid);send(201,message(one('SELECT m.seq,m.room,m.sender,m.client_id,m.reply_to,m.body,m.mime,m.at,u.name FROM chat_messages m JOIN users u ON u.id=m.sender WHERE seq=?',seq)));return true;}
 }
 const taskRoute=route.match(/^\/api\/chat\/tasks\/([a-f0-9-]+)$/);
 if(taskRoute&&req.method==='PUT'){const t=one('SELECT * FROM chat_tasks WHERE id=?',taskRoute[1]);if(!t)fail(404,'Không tìm thấy công việc');member(t.room,user);const b=await readBody(req,2000);if(t.version!==b.expectedVersion)fail(409,'Công việc đã thay đổi. Mở lại danh sách.');const next={assigned:'accepted',accepted:'doing',doing:'done',done:'confirmed'}[t.state];if(b.state!==next)fail(409,'Chuyển trạng thái theo đúng thứ tự');if(next==='confirmed'?user.id!==t.creator&&user.role!=='admin':user.id!==t.assignee)fail(403,'Chỉ người phụ trách được cập nhật; người giao xác nhận hoàn thành');run('UPDATE chat_tasks SET state=?,version=version+1,updated=? WHERE id=?',next,new Date().toISOString(),t.id);send(200,one('SELECT * FROM chat_tasks WHERE id=?',t.id));return true;}
 const img=route.match(/^\/api\/chat\/images\/(\d+)$/);if(img&&req.method==='GET'){const m=one('SELECT room,image,mime FROM chat_messages WHERE seq=?',Number(img[1]));if(!m||!m.image)fail(404,'Không tìm thấy ảnh');member(m.room,user);res.writeHead(200,{'Content-Type':m.mime,'Content-Security-Policy':"default-src 'none'; sandbox",'Cache-Control':'no-store'});res.end(Buffer.from(m.image,'base64'));return true;}
 fail(404,'Không tìm thấy chức năng chat');
 }};
}
module.exports={createChat};
