'use strict';
const SC=require('../customer-scoring-core.js'),A=require('../action-access.js'),{permissions}=require('./access.cjs'),{createHash}=require('node:crypto');
function manager(user){let roles={};try{roles=JSON.parse(user.work_roles||'{}');}catch{}return user.role==='admin'||roles.sales==='manager'&&A.allows(user,'customers','edit');}
function visible(user){const p=permissions(user);return A.allows(user,'customers','view')&&(p.costs||A.explicit(user));}
function offerCare(sql){const latest=new Map();for(const r of sql.prepare("SELECT c.document followup,r.document quotation,r.version FROM commercial c JOIN revisions r ON r.id=c.id WHERE r.status='approved'").all()){const q=JSON.parse(r.quotation).quote,id=q.customerInfo?.id,e=JSON.parse(r.followup).dispatches?.[r.version];if(!id||!e)continue;const at=[e.sentAt,...(e.entries||[]).filter(x=>['care','feedback'].includes(x.kind)).map(x=>x.at)].filter(Boolean).sort().at(-1);if(at&&at>(latest.get(id)||''))latest.set(id,at);}return latest;}
function create({sql}){sql.exec('CREATE TABLE IF NOT EXISTS customer_care_notices(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,read_at TEXT)');
 function list(user,now=new Date().toISOString()){if(!visible(user))return [];const row=sql.prepare('SELECT document FROM customer_policy WHERE id=1').get();if(!row)return [];const policy=JSON.parse(row.document);if(!Object.values(SC.careConfig(policy.careLevels)).some(x=>x!==null))return [];const items=[],offers=offerCare(sql);
 for(const row of sql.prepare('SELECT document FROM intake_customers').all()){const c=JSON.parse(row.document),a=SC.care({...c,lastOfferCare:offers.get(c.id)},policy,now);if(!['due','overdue','critical'].includes(a.level)||c.ownerId!==user.id&&!(a.level==='critical'&&manager(user)))continue;const id=createHash('sha256').update(JSON.stringify([c.id,user.id,c.ownerId,a.baseline,a.level,a.threshold])).digest('hex');sql.prepare('INSERT OR IGNORE INTO customer_care_notices VALUES(?,?,NULL)').run(id,user.id);const saved=sql.prepare('SELECT read_at FROM customer_care_notices WHERE id=?').get(id);items.push({id,readAt:saved.read_at,customerId:c.id,stage:'customer-care',code:c.name,actor:'Hệ thống',at:new Date(Date.parse(a.baseline+'T00:00:00+07:00')+a.threshold*86400000).toISOString(),note:a.label+' · '+a.days+' ngày chưa ghi nhận chăm sóc'+(a.level==='critical'?' · Quản lý có thể rà soát, điều chuyển người phụ trách.':'')});}return items;}
 function read(id,user){if(!list(user).some(n=>n.id===id))return false;sql.prepare('UPDATE customer_care_notices SET read_at=COALESCE(read_at,?) WHERE id=? AND user_id=?').run(new Date().toISOString(),id,user.id);return true;}
 return {list,read};}
module.exports={create,manager,visible,offerCare};
