'use strict';
const {randomUUID,createHash}=require('node:crypto'),AA=require('../action-access.js'),F=require('../completion-core.js'),Payroll=require('../payroll-core.js');
function createEnterprise({sql,fail,readBody,transaction,audit,organization}){
 sql.exec('CREATE TABLE IF NOT EXISTS enterprise_records(kind TEXT NOT NULL,id TEXT NOT NULL,version INTEGER NOT NULL,document TEXT NOT NULL,PRIMARY KEY(kind,id)); CREATE TABLE IF NOT EXISTS enterprise_requests(id TEXT PRIMARY KEY,actor TEXT NOT NULL,route TEXT NOT NULL,body TEXT NOT NULL,result TEXT NOT NULL);');
 const all=(s,...a)=>sql.prepare(s).all(...a),one=(s,...a)=>sql.prepare(s).get(...a),unpack=r=>r?{...JSON.parse(r.document),id:r.id,version:r.version}:null;
 const list=(kind,table='enterprise_records')=>all('SELECT * FROM '+table+' WHERE kind=?',kind).map(unpack),get=(kind,id,table='enterprise_records')=>unpack(one('SELECT * FROM '+table+' WHERE kind=? AND id=?',kind,id||''));
 const put=(kind,id,d,version,table='enterprise_records')=>{const previous=get(kind,id,table);if(previous)sql.prepare('INSERT INTO enterprise_records VALUES(?,?,?,?)').run('history',randomUUID(),1,JSON.stringify({table,kind,recordId:id,previous,at:new Date().toISOString()}));sql.prepare('INSERT INTO '+table+' VALUES(?,?,?,?) ON CONFLICT(kind,id) DO UPDATE SET version=excluded.version,document=excluded.document').run(kind,id,version,JSON.stringify(d));return {...d,id,version};};
 const allowed=(u,k,a)=>AA.allows(u,k,a,false),need=(u,k,a)=>{if(!allowed(u,k,a))fail(403,'Chưa có quyền '+(AA.labels[a]||a)+' · '+AA.schema[k][0]);};
 const text=(v,max=300,required=false)=>{if(typeof v!=='string'||v.length>max||required&&!v.trim())fail(400,'Nội dung thiếu hoặc quá dài');return v.trim();},num=(v,max=1e12)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>max)fail(400,'Số liệu không hợp lệ');return v;},amount=v=>Payroll.round(num(v)),date=v=>{if(!F.validDate(v))fail(400,'Ngày không hợp lệ');return v;},month=v=>{if(typeof v!=='string'||!/^\d{4}-(0[1-9]|1[0-2])$/.test(v))fail(400,'Kỳ lương không hợp lệ');return v;};
 const now=()=>new Date().toISOString(),cas=(old,b)=>{if((old?.version||0)!==b.expectedVersion)fail(409,'Dữ liệu đã đổi; tải lại trước khi lưu');},active=r=>!r.voidedAt;
 const biz=k=>list(k,'business_records'),ops=k=>list(k,'ops_records'),employees=()=>organization.get().employees;
 const employee=id=>{const e=employees().find(e=>e.id===id);if(!e)fail(400,'Nhân sự không tồn tại');return e;};
 const users=()=>all('SELECT id,name FROM users WHERE active=1 AND deleted_at IS NULL');
 const person=id=>{if(!users().some(u=>u.id===id))fail(400,'Người phụ trách không hoạt động');return id;};
 function orders(){return all('SELECT * FROM orders').map(r=>{const p=JSON.parse(r.package);return {id:r.id,code:r.code,quoteId:r.quote_id,quoteVersion:r.quote_version,customer:p.customer,offer:p.offer,quote:p.quote};});}
 function sourceOrder(id){const o=orders().find(o=>o.id===id);if(!o)fail(400,'Đơn hàng không tồn tại');return o;}
 function notice(userId,title,taskId){put('notice',randomUUID(),{userId,title,taskId,at:now(),read:false},1);}
 function costRows(){return biz('cost').filter(active).map(c=>{const contract=biz('contract').find(x=>x.id===c.contractId),allocation=get('allocation',c.id),lines=allocation?.lines||((c.orderId||contract?.orderId)?[{orderId:c.orderId||contract.orderId,amount:c.amount}]:[]),paid=list('cash').filter(x=>active(x)&&x.costId===c.id).reduce((s,x)=>s+x.amount,0);return {...c,category:category(c.category),allocationVersion:allocation?.version||0,lines,allocated:Payroll.round(lines.reduce((s,x)=>s+x.amount,0)),paid:Payroll.round(paid),remaining:Payroll.round(c.amount-paid)};});}
 function category(k){return ({material:'material','Mua vật tư':'material','Vật tư':'material',freight:'freight','Vận chuyển':'freight',labor:'labor','Nhân công':'labor',equipment:'equipment',tools:'tools',overhead:'overhead'})[k]||'other';}
 const categories=['material','freight','labor','equipment','tools','overhead','other'];
 function financeState(){const costs=costRows(),contracts=biz('contract').filter(c=>['active','completed'].includes(c.status)).map(c=>{const paid=biz('payment').filter(p=>active(p)&&p.contractId===c.id).reduce((s,p)=>s+p.amount,0);return {...c,paid,remaining:Payroll.round(c.value-paid),overdue:!!c.dueDate&&c.dueDate<F.todayVN()&&paid<c.value};}),ledger=[...biz('payment').map(p=>({...p,direction:'in',source:'contract'})),...list('cash')].sort((a,b)=>a.date.localeCompare(b.date));
  const summaries=orders().map(o=>{const matched=costs.flatMap(c=>c.lines.filter(l=>l.orderId===o.id).map(l=>({...c,amount:l.amount}))),actual=Payroll.round(matched.reduce((s,c)=>s+c.amount,0)),contract=contracts.find(c=>c.orderId===o.id),revenue=contract?.value??o.offer?.totals?.grand??0;let estimate=null;try{const r=require('../pricing-core.js').calculate(JSON.parse(one('SELECT document FROM revisions WHERE id=? AND version=?',o.quoteId,o.quoteVersion).document));estimate={total:r.total.cost,material:r.total.parts.stock+r.total.parts.ancillary+r.total.parts.finishing+r.total.parts.allowance,freight:r.total.parts.incoming+r.total.parts.outgoing+r.total.parts.delivery,labor:r.total.parts.factory+r.total.parts.outside};}catch{}
   return {id:o.id,code:o.code,customer:o.customer,revenue,actual,profit:Payroll.round(revenue-actual),margin:revenue?Payroll.round((revenue-actual)/revenue*100):null,estimate,review:get('costReview',o.id),categories:Object.fromEntries(categories.map(k=>[k,Payroll.round(matched.filter(c=>c.category===k).reduce((s,c)=>s+c.amount,0))])),sources:matched.map(c=>({id:c.id,reference:c.reference,amount:c.amount,category:c.category}))};});
  return {costs,contracts,ledger,orders:summaries,unallocated:Payroll.round(costs.reduce((s,c)=>s+c.amount-c.allocated,0)),payables:Payroll.round(costs.reduce((s,c)=>s+c.remaining,0)),receivable:Payroll.round(contracts.reduce((s,c)=>s+c.remaining,0))};
 }
 function finance(part,b,u){need(u,'finance','view');need(u,'finance',part==='void'?'delete':part==='review'?'approve':'create');if(!require('./access.cjs').permissions(u).costs)fail(403,'Cần quyền chi phí nội bộ');
  if(part==='expense'){const reference=text(b.reference,200,true);if(biz('cost').some(c=>active(c)&&c.reference===reference))fail(409,'Số chứng từ chi phí đã có');const orderId=b.orderId||'',jobId=b.jobId||'';if(orderId)sourceOrder(orderId);if(jobId){const j=one('SELECT order_id FROM production_jobs WHERE id=?',jobId);if(!j||j.order_id!==orderId)fail(400,'Lệnh không thuộc đơn hàng');}const v=amount(b.amount);if(!v||!categories.includes(b.category))fail(400,'Khai số tiền và loại chi phí');return put('cost',randomUUID(),{reference,date:date(b.date),amount:v,category:b.category,note:text(b.note,3000,true),responsible:text(b.responsible||u.name,200,true),workshop:text(b.workshop||'',200),orderId,jobId,paymentStatus:'unpaid',actor:u.id,actorName:u.name,at:now()},1,'business_records');}
  if(part==='allocate'){const c=costRows().find(c=>c.id===b.id);if(!c)fail(404,'Không có chi phí');cas({version:c.allocationVersion},b);if(!Array.isArray(b.lines)||b.lines.length>200)fail(400,'Phân bổ không hợp lệ');const seen=new Set(),lines=b.lines.map(l=>{sourceOrder(l.orderId);if(seen.has(l.orderId))fail(400,'Đơn hàng bị lặp');seen.add(l.orderId);return {orderId:l.orderId,amount:amount(l.amount)};});if(Payroll.round(lines.reduce((s,l)=>s+l.amount,0))>c.amount)fail(400,'Phân bổ vượt chi phí');return put('allocation',c.id,{lines,reason:text(b.reason,2000,true),actor:u.id,at:now()},c.allocationVersion+1);}
  if(part==='cash'){if(!['in','out'].includes(b.direction))fail(400,'Loại thu chi không hợp lệ');const value=amount(b.amount);if(!value)fail(400,'Số tiền phải lớn hơn 0');const reference=text(b.reference,200,true);if([...list('cash'),...biz('payment')].some(c=>active(c)&&c.reference===reference))fail(409,'Chứng từ tiền đã tồn tại');const cost=b.costId?costRows().find(c=>c.id===b.costId):null;if(b.costId&&!cost||cost&&(b.direction!=='out'||value>cost.remaining))fail(400,'Khoản trả vượt công nợ hoặc sai chứng từ');if(cost?.payrollId&&get('payroll',cost.payrollId)?.state!=='paid')fail(409,'Thực hiện Chi lương tại kỳ lương đã duyệt trước');if(b.direction==='out'&&!cost)fail(400,'Chọn chi phí phải thanh toán trước khi chi tiền');return put('cash',randomUUID(),{direction:b.direction,amount:value,reference,date:date(b.date),costId:cost?.id||'',responsible:text(b.responsible||u.name,200,true),note:text(b.note,3000,true),actor:u.id,actorName:u.name,at:now()},1);}
  if(part==='void'){const table=b.kind==='expense'?'business_records':'enterprise_records',kind=b.kind==='expense'?'cost':'cash',r=get(kind,b.id,table);if(!r||r.voidedAt)fail(404,'Chứng từ không còn hiệu lực');cas(r,b);if(r.payrollId)fail(409,'Khoản trả lương phải xử lý từ kỳ lương');if(kind==='cost'&&(r.purchaseId||r.contractId))fail(409,'Điều chỉnh chứng từ tại nghiệp vụ nguồn');if(kind==='cost'&&list('cash').some(c=>active(c)&&c.costId===r.id))fail(409,'Hủy chứng từ chi tiền trước');return put(kind,r.id,{...r,voidedAt:now(),voidedBy:u.id,voidReason:text(b.reason,2000,true)},r.version+1,table);}
  if(part==='review'){const o=financeState().orders.find(o=>o.id===b.id);if(!o)fail(404,'Đơn hàng không có');const old=get('costReview',o.id);cas(old,b);if(b.confirmed!==true)fail(400,'Xác nhận doanh thu và chi phí cùng phạm vi thuế, chi phí đã đủ');return put('costReview',o.id,{signature:hash({sources:o.sources,revenue:o.revenue}),note:text(b.note,2000,true),actor:u.id,actorName:u.name,at:now()},(old?.version||0)+1);}
  fail(404,'Thao tác không có');
 }
 const hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
 function payrollLocked(employeeId,day){return list('payroll').some(p=>['approved','paid'].includes(p.state)&&p.month===day.slice(0,7)&&p.rows.some(r=>r.employeeId===employeeId));}
 function contractFinancials(c){const costs=c.orderId?costRows().flatMap(x=>x.lines.filter(l=>l.orderId===c.orderId).map(l=>({...x,amount:l.amount}))):costRows().filter(x=>x.contractId===c.id),cost=Payroll.round(costs.reduce((s,x)=>s+x.amount,0)),review=c.orderId?get('costReview',c.orderId):null,summary=review?financeState().orders.find(o=>o.id===c.orderId):null;return {costs,cost,hasOrderReview:!!review,reviewed:review?!!summary&&review.signature===hash({sources:summary.sources,revenue:summary.revenue}):!!c.costReview&&c.costReview.amount===cost};}
 function commissionFor(e){if(!e.userId)return {amount:0,sources:[]};let amount=0;const sources=[];for(const c of biz('contract').filter(c=>['active','completed'].includes(c.status)&&c.orderId)){const context=contractFinancials(c),paid=biz('payment').filter(p=>active(p)&&p.contractId===c.id).reduce((s,p)=>s+p.amount,0),o=get('order',c.orderId,'business_records');const r=require('../business-commission-core.js').calculate({value:c.value,paid,cost:context.cost,reviewed:context.reviewed,policy:o?.commissionPolicy,shares:o?.salespeople});if(r.ready){const earned=r.rows.find(x=>x.userId===e.userId)?.amount||0,used=list('payroll').filter(p=>['approved','paid'].includes(p.state)).flatMap(p=>p.rows).filter(x=>x.userId===e.userId).flatMap(x=>x.commissionSources||[]).filter(x=>x.contractId===c.id).reduce((s,x)=>s+x.amount,0),remaining=Payroll.round(earned-used);if(remaining<0)fail(409,'Tiền hưởng đã chốt vượt căn cứ hiện tại; cần đối soát kỳ lương');if(remaining){amount+=remaining;sources.push({contractId:c.id,amount:remaining,paid,cost:context.cost});}}}return {amount:Payroll.round(amount),sources};}
 function payrollPreview(m){const pending=list('attendance').filter(r=>r.date.startsWith(m)&&r.state!=='approved');if(pending.length)fail(409,'Còn ngày công chưa duyệt trong kỳ');for(const a of list('attendance').filter(r=>r.date.startsWith(m)&&r.state==='approved'))if(!get('salary',a.employeeId))fail(409,'Chưa khai hồ sơ lương: '+a.name);const rows=[];for(const p of list('salary')){const e=employee(p.employeeId),rule=get('rule',p.ruleId);const days=list('attendance').filter(r=>r.employeeId===e.id&&r.date.startsWith(m)&&r.state==='approved');if(!days.length)continue;if(!rule)fail(400,'Chưa khai nguyên tắc lương cho '+e.name);const cm=commissionFor(e),calculation=Payroll.calculate(p,rule,days,cm.amount);if(calculation.net<0)fail(400,'Thực nhận âm; kiểm tra khấu trừ của '+e.name);rows.push({employeeId:e.id,name:e.name,code:e.code,userId:e.userId,profile:{...p},rule:{...rule},attendance:days,commissionSources:cm.sources,...calculation});}if(!rows.length)fail(400,'Chưa có ngày công đã duyệt và hồ sơ lương trong kỳ');return rows;}
 function hr(part,b,u){
  const right=part.startsWith('attendance')?'attendance':'payroll';need(u,right,'view');need(u,right,part.endsWith('approve')?'approve':part.endsWith('reopen')?'reopen':'edit');
  if(part==='rule'){const old=get('rule',b.id);cas(old,b);const d={name:text(b.name,200,true),group:text(b.group,100,true),standardDays:num(b.standardDays,31),hoursPerDay:num(b.hoursPerDay,24),overtime:num(b.overtime,20),rest:num(b.rest,20),holiday:num(b.holiday,20),onsiteAllowance:amount(b.onsiteAllowance),onsiteFactor:num(b.onsiteFactor??1,20),otherFactor:num(b.otherFactor??1,20),employeeInsurance:num(b.employeeInsurance,100),employerInsurance:num(b.employerInsurance,100),note:text(b.note,3000,true),actor:u.id,at:now()};if(!d.standardDays||!d.hoursPerDay)fail(400,'Ngày chuẩn và giờ/ngày phải lớn hơn 0');return put('rule',old?.id||randomUUID(),d,(old?.version||0)+1);}
  if(part==='salary'){const e=employee(b.employeeId),old=get('salary',e.id);cas(old,b);if(b.id&&b.id!==e.id)fail(400,'Không đổi nhân sự của hồ sơ đang sửa');if(!get('rule',b.ruleId))fail(400,'Chọn nguyên tắc lương');return put('salary',e.id,{employeeId:e.id,ruleId:b.ruleId,monthly:amount(b.monthly),insuranceBase:amount(b.insuranceBase),allowance:amount(b.allowance),deduction:amount(b.deduction),tax:amount(b.tax),note:text(b.note,2000,true),actor:u.id,at:now()},(old?.version||0)+1);}
  if(part==='attendance'){const e=employee(b.employeeId),day=date(b.date);if(e.startDate&&day<e.startDate||e.endDate&&day>e.endDate)fail(400,'Ngày công ngoài thời gian làm việc');if(payrollLocked(e.id,day))fail(409,'Kỳ lương đã chốt');const id=e.id+'@'+day,old=get('attendance',id);cas(old,b);if(b.id&&b.id!==id)fail(400,'Không đổi nhân sự hoặc ngày của bản công đang sửa');if(old?.state==='approved')fail(409,'Mở lại ngày công đã duyệt trước');const hours=Object.fromEntries(Payroll.buckets.map(k=>[k,num(b[k],24)]));if(Object.values(hours).reduce((s,n)=>s+n,0)>24)fail(400,'Tổng giờ trong ngày vượt 24');return put('attendance',id,{employeeId:e.id,name:e.name,date:day,...hours,note:text(b.note||'',2000),state:'pending',actor:u.id,at:now()},(old?.version||0)+1);}
  if(part==='attendance-approve'||part==='attendance-reopen'){const r=get('attendance',b.id);if(!r)fail(404,'Không có ngày công');cas(r,b);if(payrollLocked(r.employeeId,r.date))fail(409,'Kỳ lương đã chốt');if(part.endsWith('reopen'))text(b.reason,2000,true);return put('attendance',r.id,{...r,state:part.endsWith('approve')?'approved':'pending',reviewer:u.id,reviewedAt:now(),reviewNote:b.reason||''},r.version+1);}
  if(part==='payroll'){const m=month(b.month),old=list('payroll').find(p=>p.month===m);cas(old,b);if(old&&old.state!=='draft')fail(409,'Kỳ đã chốt');const rows=payrollPreview(m);return put('payroll',old?.id||randomUUID(),{month:m,state:'draft',rows,signature:hash(rows),actor:u.id,at:now()},(old?.version||0)+1);}
  if(part.startsWith('payroll-')){const p=get('payroll',b.id);if(!p)fail(404,'Không có kỳ lương');cas(p,b);
   if(part==='payroll-approve'){if(p.state!=='draft')fail(409,'Chỉ duyệt bản nháp');if(hash(payrollPreview(p.month))!==p.signature)fail(409,'Đầu vào đã đổi; tính lại bảng lương');const oldCost=get('cost','payroll-'+p.id,'business_records'),value=Payroll.round(p.rows.reduce((s,r)=>s+r.employerCost,0));if((get('allocation','payroll-'+p.id)?.lines||[]).reduce((s,l)=>s+l.amount,0)>value)fail(409,'Phân bổ kỳ trước vượt chi phí mới; điều chỉnh phân bổ trước');put('cost','payroll-'+p.id,{amount:value,date:p.month+'-01',reference:'LUONG-'+p.month,category:'labor',note:'Chi phí lương '+p.month,payrollId:p.id,paymentStatus:'unpaid',actor:u.id,at:now()},(oldCost?.version||0)+1,'business_records');return put('payroll',p.id,{...p,state:'approved',reviewer:u.id,reviewedAt:now()},p.version+1);}
   if(part==='payroll-reopen'){if(p.state!=='approved'||list('cash').some(c=>active(c)&&c.costId==='payroll-'+p.id))fail(409,'Chỉ mở kỳ đã duyệt chưa phát sinh chi trả');const reason=text(b.reason,2000,true),cost=get('cost','payroll-'+p.id,'business_records');const allocation=get('allocation','payroll-'+p.id);if(allocation)put('allocation',allocation.id,{lines:[],reason,previous:allocation.lines,actor:u.id,at:now()},allocation.version+1);put('payrollHistory',randomUUID(),{...p,allocation,reopenedBy:u.id,reopenedAt:now(),reason},1);if(cost)put('cost',cost.id,{...cost,voidedAt:now(),voidReason:reason},cost.version+1,'business_records');return put('payroll',p.id,{...p,state:'draft',reopenReason:reason},p.version+1);}
   if(part==='payroll-pay'){need(u,'finance','create');if(!require('./access.cjs').permissions(u).costs)fail(403,'Cần quyền xem chi phí nội bộ để chi lương');if(p.state!=='approved')fail(409,'Chỉ trả kỳ đã duyệt');const reference=text(b.reference,200,true);if([...list('cash'),...biz('payment')].some(c=>active(c)&&c.reference===reference))fail(409,'Trùng số chứng từ');const day=date(b.date),total=Payroll.round(p.rows.reduce((s,r)=>s+r.net,0));if(list('cash').some(c=>active(c)&&c.costId==='payroll-'+p.id))fail(409,'Kỳ đã có chi trả; cần đối soát');put('cash','payroll-'+p.id,{direction:'out',date:day,reference,amount:total,costId:'payroll-'+p.id,payrollId:p.id,note:'Trả lương '+p.month,actor:u.id,actorName:u.name,at:now()},1);return put('payroll',p.id,{...p,state:'paid',paidAt:now(),paidBy:u.id,paymentReference:reference},p.version+1);}
  }fail(404,'Thao tác không có');
 }
 function taskVisible(t,u){return t.assignee===u.id||t.creator===u.id||allowed(u,'dailyWork','assign')||allowed(u,'dailyWork','approve');}
 function work(part,b,u){need(u,'dailyWork','view');need(u,'dailyWork',part==='resolve'||part==='transition'&&(b.state==='confirmed'||b.state==='running'&&get('task',b.id,'ops_records')?.state==='done')?'approve':part==='task'&&b.assignee!==u.id?'assign':'edit');
  if(part==='task'){const old=get('task',b.id,'ops_records');cas(old,b);if(old&&!taskVisible(old,u))fail(403,'Ngoài phạm vi công việc');if(old&&old.state==='confirmed')fail(409,'Công việc đã xác nhận');if(old&&old.assignee!==u.id&&!allowed(u,'dailyWork','assign'))fail(403,'Không được đổi người nhận');const jobId=b.jobId||'',j=jobId?one('SELECT * FROM production_jobs WHERE id=?',jobId):null;if(jobId&&(!j||j.state==='completed'))fail(400,'Lệnh không tồn tại');const startDate=date(b.startDate),dueDate=date(b.dueDate);if(dueDate<startDate)fail(400,'Hạn trước ngày bắt đầu');const d={...old,name:text(b.name,300,true),assignee:person(b.assignee),creator:old?.creator||u.id,workflow:'enterprise',jobId,orderId:j?.order_id||'',startDate,dueDate,plannedHours:num(b.plannedHours,100000),state:old?.state||'pending',created:old?.created||now()};const r=put('task',old?.id||randomUUID(),d,(old?.version||0)+1,'ops_records');notice(r.assignee,'Giao việc: '+r.name,r.id);return r;}
  const t=get('task',b.taskId||b.id,'ops_records');if(!t||!taskVisible(t,u))fail(404,'Không có công việc trong phạm vi');cas(t,b);
  if(part==='transition'){const state=b.state,manager=allowed(u,'dailyWork','approve');if(state==='confirmed'||state==='running'&&t.state==='done'){if(!manager)fail(403,'Cần quyền xác nhận công việc');}else if(t.assignee!==u.id)fail(403,'Chỉ người nhận cập nhật bước công việc');const paths={pending:['accepted'],accepted:['running'],running:['done'],done:['confirmed','running']};if(!paths[t.state]?.includes(state))fail(409,'Bước công việc không hợp lệ');const reason=text(b.reason||'',2000,state==='running'&&t.state==='done');const r=put('task',t.id,{...t,state,updated:now(),updatedBy:u.id,transitionNote:reason,events:[...(t.events||[]),{state,actor:u.id,at:now(),reason}]},t.version+1,'ops_records');for(const id of new Set([t.assignee,t.creator,...(state==='done'?users().filter(x=>allowed(one('SELECT * FROM users WHERE id=?',x.id),'dailyWork','approve')).map(x=>x.id):[])]))if(id)notice(id,'Công việc '+t.name+': '+({accepted:'Đã nhận',running:'Đang làm',done:'Chờ xác nhận',confirmed:'Đã xác nhận'}[state]||state),t.id);return r;}
  if(part==='report'){if(t.assignee!==u.id&&u.role!=='admin')fail(403,'Chỉ người nhận báo cáo');if(!['accepted','running'].includes(t.state))fail(409,'Nhận/bắt đầu công việc trước khi báo cáo');const day=date(b.date),hours=num(b.hours,24);if(ops('report').filter(r=>r.actor===u.id&&r.date===day).reduce((s,r)=>s+r.hours,0)+hours>24)fail(400,'Tổng giờ báo cáo vượt 24');return put('report',randomUUID(),{taskId:t.id,jobId:t.jobId,orderId:t.orderId,actor:u.id,actorName:u.name,date:day,hours,output:num(b.output),content:text(b.content,3000,true),issue:text(b.issue||'',3000),proposal:text(b.proposal||'',3000),nextPlan:text(b.nextPlan||'',3000),resolved:false,at:now()},1,'ops_records');}
  if(part==='resolve'){need(u,'dailyWork','approve');const r=get('report',b.reportId,'ops_records');if(!r||r.taskId!==t.id||!r.issue||r.resolved)fail(409,'Không có vướng mắc đang mở');return put('report',r.id,{...r,resolved:true,resolution:text(b.resolution,3000,true),resolvedBy:u.name,resolvedAt:now()},r.version+1,'ops_records');}
  fail(404,'Thao tác không có');
 }
 function state(u,view){const perms=Object.fromEntries(['finance','payroll','attendance','dailyWork'].map(k=>[k,Object.fromEntries(AA.schema[k][1].map(a=>[a,allowed(u,k,a)]))]));need(u,view==='finance'?'finance':view==='work'?'dailyWork':view==='attendance'?'attendance':'payroll','view');const out={permissions:perms,view};
  if(view==='finance'){if(!require('./access.cjs').permissions(u).costs)fail(403,'Cần quyền chi phí nội bộ');Object.assign(out,financeState());out.jobs=all('SELECT id,code,order_id FROM production_jobs');out.orders.forEach(o=>{o.reviewCurrent=!!o.review&&o.review.signature===hash({sources:o.sources,revenue:o.revenue});});}
  if(view==='payroll'||view==='attendance'){out.people=employees().map(e=>({id:e.id,code:e.code,name:e.name,startDate:e.startDate,endDate:e.endDate,active:e.active,standardHours:get('rule',get('salary',e.id)?.ruleId)?.hoursPerDay||null}));out.attendance=list('attendance');if(view==='payroll')Object.assign(out,{rules:list('rule'),salaries:list('salary'),payrolls:list('payroll')});}
  if(view==='work'){out.people=users();out.jobs=all('SELECT id,code FROM production_jobs');out.tasks=ops('task').filter(t=>taskVisible(t,u));out.reports=ops('report').filter(r=>out.tasks.some(t=>t.id===r.taskId));out.notices=list('notice').filter(n=>n.userId===u.id).sort((a,b)=>b.at.localeCompare(a.at)).slice(0,100);}
  if(!require('./access.cjs').permissions(u).costs)Object.keys(out.permissions.finance).forEach(k=>out.permissions.finance[k]=false);return out;
 }
 async function handle({req,route,user,send}){if(!route.startsWith('/api/enterprise/'))return false;const part=route.slice(16),[group,action]=part.split('/');if(req.method==='GET'){if(!['finance','payroll','attendance','work'].includes(group)||action)fail(404,'Không có màn hình');send(200,state(user,group));return true;}if(!action)fail(404,'Thao tác không tồn tại');if(req.method!=='POST')fail(405,'Phương thức không hỗ trợ');const b=await readBody(req,300000),key=text(b.requestId,100,true);if(!/^[a-zA-Z0-9_-]{8,100}$/.test(key))fail(400,'Mã thao tác không hợp lệ');const out=transaction(()=>{const prior=one('SELECT * FROM enterprise_requests WHERE id=?',key),raw=JSON.stringify(b);if(prior){if(prior.actor!==user.id||prior.route!==part||prior.body!==raw)fail(409,'Mã thao tác đã sử dụng');state(user,group==='hr'?(action.startsWith('attendance')?'attendance':'payroll'):group);return JSON.parse(prior.result);}let result;if(group==='finance')result=finance(action,b,user);else if(group==='hr')result=hr(action,b,user);else if(group==='work')result=work(action,b,user);else fail(404,'Thao tác không có');audit(user,'enterprise:'+part,result.id||'',JSON.stringify({month:result.month,state:result.state}));sql.prepare('INSERT INTO enterprise_requests VALUES(?,?,?,?,?)').run(key,user.id,part,raw,JSON.stringify(result));return result;});send(200,out);return true;}
 return {handle,financeState,contractFinancials};
}
module.exports={createEnterprise};
