'use strict';
const C=require('../core.js'),{isDeepStrictEqual:equal}=require('node:util');require('../pricing-core.js');
const pick=(x,keys)=>Object.fromEntries(keys.filter(k=>x?.[k]!==undefined).map(k=>[k,x[k]]));
function shapeMeaning(d){return {...pick(d,['base','blankShape','nesting','length','width','mass','surface','blankMass','blankSurface','polygon']),fields:(d.fields||[]).map(f=>pick(f,['key','mode','unit'])),unfoldOutputs:(d.unfoldOutputs||[]).map(f=>pick(f,['key','unit','formula']))};}
function apply(document,master){const next=C.copy(document),shapes=new Map((master.shapeDefinitions||[]).map(d=>[d.id,d])),rules=new Map((master.rules||[]).map(r=>[r.id,r])),changes=new Map();
 function material(spec){const old=spec?.shapeDefinition,published=old&&shapes.get(old.id);if(!published||equal(shapeMeaning(old),shapeMeaning(published)))return false;spec.shapeDefinition=C.copy(published);changes.set('shapeDefinitions:'+old.id,{id:old.id,name:published.name||old.id,kind:'shapeDefinitions'});return true;}
 for(const n of C.flatten(next.quote.products||[])){if(n.kind!=='material')continue;const shaped=!!n.spec?.shapeDefinition,changed=material(n.spec);if(shaped){if(changed){const d=n.spec.shapeDefinition;n.ruleSpec={...n.ruleSpec,id:d.id,name:d.name,shape:d.base,length:d.length,width:d.width};}continue;}const r=rules.get(n.ruleSpec?.id||n.rule);if(r&&!equal(pick(n.ruleSpec,['length','width','formulas']),pick(r,['length','width','formulas']))){n.ruleSpec=C.copy(r);changes.set('rules:'+r.id,{id:r.id,name:r.name||r.id,kind:'rules'});}}
 if(!changes.size)return {document,changes:[]};for(const spec of next.materials||[])material(spec);for(const change of changes.values()){const key=change.kind,list=next[key]??=[],value=(key==='shapeDefinitions'?shapes:rules).get(change.id),index=list.findIndex(x=>x.id===change.id);if(index>=0)list[index]=C.copy(value);else list.push(C.copy(value));}return {document:next,changes:[...changes.values()]};}
function metrics(result){const rows=result.rows||[];return {weight:rows.reduce((s,r)=>s+(Number(r.geometry?.weight)||0),0),blankArea:rows.reduce((s,r)=>s+(Number(r.geometry?.blankArea)||0),0),surfaceArea:rows.reduce((s,r)=>s+(Number(r.geometry?.area)||0),0),grand:result.total.grand};}
function comparison(before,after){const a=metrics(before),b=metrics(after);return Object.fromEntries(Object.keys(a).map(k=>[k,{before:a[k],after:b[k],delta:b[k]-a[k]}]));}
function createFormulaSync({sql,cleanDocument,publicOffer,audit}){
 const master=()=>{const row=sql.prepare('SELECT * FROM catalog WHERE id=1').get();return {...row,catalog:JSON.parse(row.document)};};
 function sent(id,version){const row=sql.prepare('SELECT document FROM commercial WHERE id=?').get(id);return !!row&&(JSON.parse(row.document).events||[]).some(e=>e.to==='sent'&&(!e.offerVersion||e.offerVersion===version));}
 function preview(record,catalogRow=master()){const before=JSON.parse(record.document),patched=apply(before,catalogRow.catalog),base={quoteVersion:record.version,catalogVersion:catalogRow.version,sent:sent(record.id,record.version),changes:patched.changes};if(!patched.changes.length)return {...base,state:'current',lastUpdate:before.quote.formulaSync||null};try{const old=cleanDocument(before).result,result=cleanDocument(patched.document).result,errors=result.errors.filter(e=>!old.errors.includes(e));if(errors.length)return {...base,state:'blocked',errors};return {...base,state:'changed',values:comparison(old,result),document:patched.document,result};}catch(e){return {...base,state:'blocked',errors:[e.message]};}}
 function sync(catalogRow,user,onlyId){const report={updated:0,sent:0,blocked:0};for(const record of sql.prepare('SELECT * FROM quotes WHERE id NOT IN (SELECT id FROM quote_deletions)').all()){if(onlyId&&record.id!==onlyId)continue;const p=preview(record,catalogRow);if(p.state==='current')continue;if(p.sent){report.sent++;continue;}if(p.state==='blocked'){report.blocked++;continue;}
 const doc=p.document,version=record.version+1,at=new Date().toISOString(),reason='Cập nhật công thức danh mục v'+catalogRow.version+': '+p.changes.map(c=>c.name).join(', ');doc.quote.formulaSync={catalogVersion:catalogRow.version,at,actor:user.name,fromVersion:record.version,version,changes:p.changes,reason};if(record.status==='approved'){doc.quote.approvedOffer=publicOffer(doc,p.result);doc.quote.approvedBaseline=p.result.total;}const encoded=JSON.stringify(doc);sql.prepare('UPDATE quotes SET version=?,document=?,total=?,updated=?,actor=? WHERE id=?').run(version,encoded,p.result.total.grand,at,user.id,record.id);sql.prepare('INSERT INTO revisions(id,version,status,document,total,actor,at,reason) VALUES(?,?,?,?,?,?,?,?)').run(record.id,version,record.status,encoded,p.result.total.grand,user.id,at,reason);
 const handoff=sql.prepare('SELECT document FROM quote_handoffs WHERE quote_id=?').get(record.id);if(handoff){const state=JSON.parse(handoff.document);for(const key of ['technical','materials'])if(state[key]){state[key].changeReason=reason;state[key].changedBy=user.name;state[key].changedAt=at;state[key].changedStage='technical';}sql.prepare('UPDATE quote_handoffs SET document=? WHERE quote_id=?').run(JSON.stringify(state),record.id);}audit(user,'formula-sync',record.id,reason);report.updated++;}return report;}
 function describe(record,rights){const p=preview(record);delete p.document;delete p.result;if(!rights.costs){if(p.values)delete p.values.grand;delete p.errors;}return p;}
 return {sync,describe,sent,preview};}
module.exports={apply,shapeMeaning,createFormulaSync};
