'use strict';
const {combine}=require('../role-access.js'),SA=require('../section-access.js'),{FIELDS}=require('./formula-access.cjs');
function stored(sql){if(!sql.prepare("SELECT 1 FROM sqlite_master WHERE name='organization'").get())return null;const r=sql.prepare('SELECT * FROM organization WHERE id=1').get();return r?{version:r.version,...JSON.parse(r.document)}:null;}
function managed(sql,id){return stored(sql)?.employees.some(e=>e.userId===id&&e.managed);}
function ancestry(d,id){const out=[],seen=new Set();while(id){if(seen.has(id))return [];seen.add(id);const a=d.departments.find(a=>a.id===id);if(!a)return [];out.push(a);id=a.parentId;}return out;}
function activeDepartment(d,id){const chain=ancestry(d,id);return chain.length>0&&chain.every(a=>a.active);}
function scope(sql,id,stage){const d=stored(sql),e=d?.employees.find(e=>e.userId===id&&e.managed);if(!e)return null;
 const positions=x=>x.active?d.positions.filter(p=>p.active&&x.positionIds.includes(p.id)&&activeDepartment(d,p.departmentId)&&d.departments.some(a=>a.id===p.departmentId&&a.stage===stage)):[];
 const departments=positions(e).filter(p=>p.manager).map(p=>p.departmentId);
 const descendant=p=>ancestry(d,p.departmentId).slice(1).some(a=>departments.includes(a.id));
 return {manager:!!departments.length,ids:d.employees.filter(x=>x.userId&&x.managed&&x.active&&(x.userId===id||positions(x).some(p=>descendant(p)||departments.includes(p.departmentId)&&!p.manager)&&!positions(x).some(p=>departments.includes(p.departmentId)&&p.manager))).map(x=>x.userId)};
}
function createOrganization({sql,fail,readBody,transaction,audit,accounts,formulaAccess,addUser}){
 sql.exec('CREATE TABLE IF NOT EXISTS organization(id INTEGER PRIMARY KEY,version INTEGER NOT NULL,document TEXT NOT NULL); CREATE TABLE IF NOT EXISTS organization_revisions(version INTEGER PRIMARY KEY,document TEXT NOT NULL,actor TEXT NOT NULL,at TEXT NOT NULL)');
 const users=()=>sql.prepare('SELECT * FROM users WHERE deleted_at IS NULL').all();
 function get(){const d=stored(sql)||{version:0,departments:[],positions:[],employees:[]};for(const u of users())if(!d.employees.some(e=>e.userId===u.id))d.employees.push({id:u.id,code:'TK-'+u.username,name:u.name,email:'',phone:'',userId:u.id,active:!!u.active,managed:false,positionIds:[]});return d;}
 const text=(v,label,max=100)=>{if(typeof v!=='string'||!v.trim()||v.length>max)fail(400,label+' không hợp lệ');return v.trim();};
 function validate(input,old){const d={};for(const k of ['departments','positions','employees']){if(!Array.isArray(input[k])||input[k].length>1000)fail(400,'Danh sách '+k+' không hợp lệ');d[k]=input[k].map(x=>({...x}));const ids=new Set();for(const x of d[k]){if(!x||typeof x.id!=='string'||! /^[a-zA-Z0-9_-]{1,80}$/.test(x.id)||ids.has(x.id))fail(400,'Mã dòng bị trùng hoặc không hợp lệ');ids.add(x.id);x.name=text(x.name,'Tên');x.active=x.active!==false;}const names=new Set();for(const x of d[k]){const key=(k==='positions'?x.departmentId+'|':k==='departments'?(x.parentId||'')+'|':'')+(k==='employees'?text(x.code,'Mã nhân sự'):x.name).normalize('NFC').toLocaleLowerCase('vi');if(names.has(key))fail(409,'Trùng tên phòng/vị trí hoặc mã nhân sự');names.add(key);}}
  d.workflows=(input.workflows===undefined?old.workflows||[]:input.workflows);if(!Array.isArray(d.workflows)||d.workflows.length>1000)fail(400,'Danh sách luồng không hợp lệ');
  const workflowIds=new Set(),workflowNames=new Set();d.workflows=d.workflows.map(w=>{if(!w||typeof w.id!=='string'||! /^[a-zA-Z0-9_-]{1,80}$/.test(w.id)||workflowIds.has(w.id))fail(400,'Mã luồng không hợp lệ');workflowIds.add(w.id);const name=text(w.name,'Tên luồng'),key=name.normalize('NFC').toLocaleLowerCase('vi');if(workflowNames.has(key))fail(409,'Trùng tên luồng công việc');workflowNames.add(key);if(!['sales','technical','materials','other'].includes(w.stage))fail(400,'Phần việc của luồng không hợp lệ');return {id:w.id,name,stage:w.stage};});
  for(const a of d.departments){if(a.workflowId){const w=d.workflows.find(w=>w.id===a.workflowId);if(!w)fail(400,'Luồng đang sử dụng không còn tồn tại');a.stage=w.stage;}else a.workflowId=null;}
  for(const a of d.departments){if(!['sales','technical','materials','other'].includes(a.stage))fail(400,'Chọn luồng công việc của phòng ban');a.parentId=a.parentId||null;a.kind=a.kind||'department';if(!['department','division','team','factory','board'].includes(a.kind))fail(400,'Loại đơn vị không hợp lệ');if(a.parentId&&!d.departments.some(x=>x.id===a.parentId))fail(400,'Đơn vị cấp trên không còn tồn tại');}
  for(const a of d.departments)if(!ancestry(d,a.id).length)fail(400,'Cơ cấu không được tạo vòng lặp cấp trên / cấp dưới');
  for(const p of d.positions){if(!d.departments.some(a=>a.id===p.departmentId))fail(400,'Vị trí phải thuộc phòng ban còn tồn tại');if(!Array.isArray(p.roleIds)||!p.roleIds.length||p.roleIds.length>30)fail(400,'Vị trí cần ít nhất một bộ quyền');if(p.roleIds.some(id=>typeof id!=='string'))fail(400,'Bộ quyền không hợp lệ');p.roleIds=[...new Set(p.roleIds)];for(const id of p.roleIds)if(!sql.prepare('SELECT 1 FROM role_templates WHERE id=?').get(id))fail(400,'Bộ quyền không còn tồn tại');p.manager=p.manager===true;}
  const linked=new Set(),validUsers=users();for(const e of d.employees){e.code=text(e.code,'Mã nhân sự');e.email=String(e.email||'').trim();e.phone=String(e.phone||'').trim();if(e.email.length>160||e.phone.length>40)fail(400,'Thông tin liên hệ quá dài');if(e.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e.email))fail(400,'Email không hợp lệ');if(!Array.isArray(e.positionIds)||e.positionIds.length>50||e.positionIds.some(id=>!d.positions.some(p=>p.id===id)))fail(400,'Vị trí nhân sự không còn tồn tại');e.positionIds=[...new Set(e.positionIds)];const before=old.employees.find(x=>x.id===e.id);if(before?.userId&&before.userId!==e.userId)fail(409,'Không đổi liên kết tài khoản đã có lịch sử');e.managed=!!(before?.managed||e.positionIds.length||before?.active!==false&&!e.active);e.userId=e.userId||null;if(e.userId){if(linked.has(e.userId)||!validUsers.some(u=>u.id===e.userId)&&!before?.userId)fail(400,'Tài khoản không hợp lệ hoặc đã gắn với nhân sự khác');linked.add(e.userId);}}
  for(const e of d.employees){for(const key of ['startDate','endDate']){e[key]=e[key]||'';if(e[key]&&(typeof e[key]!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(e[key])||!Number.isFinite(Date.parse(e[key]))||new Date(e[key]).toISOString().slice(0,10)!==e[key]))fail(400,'Ngày nhân sự không hợp lệ');}if(e.startDate&&e.endDate&&e.endDate<e.startDate)fail(400,'Ngày kết thúc không được trước ngày vào làm');e.duties=String(e.duties||'').trim();if(e.duties.length>2000)fail(400,'Nội dung phụ trách tối đa 2.000 ký tự');}
  for(const e of old.employees)if(e.userId&&!d.employees.some(x=>x.id===e.id))fail(409,'Nhân sự có tài khoản cần chuyển Ngừng làm việc để giữ lịch sử');
  return d;
 }
 function effective(d,e){const positions=e.active?d.positions.filter(p=>p.active&&e.positionIds.includes(p.id)&&activeDepartment(d,p.departmentId)):[],ids=[...new Set(positions.flatMap(p=>p.roleIds))],roles=ids.map(id=>JSON.parse(sql.prepare('SELECT document FROM role_templates WHERE id=?').get(id).document));
  const r=combine(roles)||{role:'sales',sectionModes:Object.fromEntries(SA.keys.map(k=>[k,'none'])),sections:[]};for(const k of require('../role-access.js').flags)r[k]=!!r[k];r.workRoles={sales:'',technical:'',materials:''};for(const p of positions){const stage=d.departments.find(a=>a.id===p.departmentId).stage;if(stage!=='other'&&(p.manager||!r.workRoles[stage]))r.workRoles[stage]=p.manager?'manager':'member';}return {...r,roleTemplateIds:ids,roleTemplateId:ids[0]||null,technicalDelegation:true};
 }
 function apply(d,actor){const previous=stored(sql)?.employees||[];for(const e of d.employees){if(!e.userId)continue;const u=sql.prepare('SELECT * FROM users WHERE id=? AND deleted_at IS NULL').get(e.userId);if(!u)continue;if(!e.managed){if(u.name!==e.name)sql.prepare('UPDATE users SET name=? WHERE id=?').run(e.name,u.id);continue;}const b=effective(d,e);accounts.validateDelegation(b);formulaAccess.validateRights(b);if(u.id===actor.id&&(!e.active||b.role!=='admin'))fail(409,'Không tự thu hồi quyền quản trị hoặc ngừng tài khoản đang dùng');
   const values={name:e.name,role:b.role,section_access:JSON.stringify(b.sectionModes),technical_delegated:1,can_factors:Number(b.canEditFactors),can_below_cost:Number(b.canApproveBelowCost),can_view_costs:Number(b.canViewCosts),can_approve:Number(b.canApprove),role_template_id:b.roleTemplateId,role_template_ids:JSON.stringify(b.roleTemplateIds),work_roles:JSON.stringify(b.workRoles),...Object.fromEntries(Object.entries(FIELDS).map(([k,col])=>[col,Number(b[k])]))};if(!e.active)values.active=0;else if(previous.some(x=>x.id===e.id&&!x.active))values.active=1;
   if(Object.entries(values).some(([k,v])=>u[k]!==v)){sql.prepare('UPDATE users SET '+Object.keys(values).map(k=>k+'=?').join(',')+' WHERE id=?').run(...Object.values(values),u.id);accounts.saveRoles(u.id,b);const h=require('./access-history.cjs');h.record(sql,actor,u.id,'organization:access',h.userSnapshot(u),h.userSnapshot(sql.prepare('SELECT * FROM users WHERE id=?').get(u.id)));sql.prepare('DELETE FROM sessions WHERE user_id=? AND token<>?').run(u.id,u.id===actor.id?actor.token:'');audit(actor,'organization:access',u.id,JSON.stringify({employee:e.id,positions:e.positionIds}));}
  }
 }
 function write(d,version,actor){sql.prepare('INSERT INTO organization_revisions VALUES(?,?,?,?)').run(version,JSON.stringify(d),actor.id,new Date().toISOString());sql.prepare('INSERT INTO organization VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET version=excluded.version,document=excluded.document').run(version,JSON.stringify(d));}
 function roleUsed(id){return stored(sql)?.positions.some(p=>p.roleIds.includes(id));}
 function roleChanged(actor){const d=stored(sql);if(!d)return;const {version,...doc}=d;apply(doc,actor);write(doc,version+1,actor);}
 function accountChanged(actor,id,name,deleted=false){const d=stored(sql);if(!d)return;const e=d.employees.find(e=>e.userId===id);if(!e)return;if(deleted){e.active=false;e.managed=true;}else e.name=name;const {version,...doc}=d;write(doc,version+1,actor);}
 async function handle({req,route,user,send}){if(route!=='/api/organization')return false;if(user.role!=='admin')fail(403,'Chỉ Admin được quản lý cơ cấu và nhân sự');if(req.method==='GET'){send(200,{...get(),users:users().map(u=>({id:u.id,name:u.name,username:u.username,active:!!u.active})),roles:sql.prepare('SELECT id,name,version FROM role_templates ORDER BY name').all()});return true;}if(req.method!=='PUT')fail(405,'Phương thức không hỗ trợ');const b=await readBody(req,500000);
  const saved=transaction(()=>{const old=get();if(b.expectedVersion!==old.version)fail(409,'Cơ cấu nhân sự đã thay đổi; tải lại trước khi lưu');const d=validate(b.document,old);if(b.createAccount){const e=d.employees.find(e=>e.id===b.createAccount.employeeId);if(!e||e.userId||!e.active||!e.positionIds.length)fail(400,'Nhân sự cần vị trí hoạt động và chưa có tài khoản');const body=effective(d,e);if(!body.roleTemplateIds.length)fail(400,'Vị trí hoặc phòng ban đang ngừng sử dụng');const u=addUser({...body,name:e.name,username:b.createAccount.username,password:b.createAccount.password});e.userId=u.id;e.managed=true;accounts.saveRoles(u.id,body);}apply(d,user);write(d,old.version+1,user);audit(user,'organization:save','1','Phiên bản '+(old.version+1));return {version:old.version+1,reauthenticate:!sql.prepare('SELECT 1 FROM sessions WHERE token=?').get(user.token)};});send(200,saved);return true;
 }
 return {handle,roleUsed,roleChanged,accountChanged,get};
}
module.exports={createOrganization,stored,managed,scope};
