/* Versioned routing. Native business operations retain their own validation and transaction. */
'use strict';
const AA=require('../action-access.js'),Scope=require('./work-scope.cjs');
const native=(key,name,module,action,admin=false)=>({key,name,module,action,admin,native:true,departmentId:'',instructions:''});
const manual=(key,name,module,action='view',admin=false)=>({...native(key,name,module,action,admin),native:false});
function templates(types){return [
 {id:'quote',name:'Chào giá và chăm sóc khách hàng',steps:[native('intake','Khai báo và xác nhận đầu vào','quotes','confirm'),native('technical','Kỹ thuật xác nhận','quotes','confirm'),native('materials','Cập nhật giá và bàn giao','quotes','confirm'),native('approve','Duyệt báo giá','quotes','approve',true),native('send','Gửi chào giá','quotes','edit'),native('care','Chăm sóc khách hàng','customers','edit')]},
 {id:'order',name:'Chốt đơn hàng và đề nghị sản xuất',steps:[manual('submit','Trình chốt đơn hàng','orders','edit'),native('confirm','Chốt đơn hàng','orders','confirm',true),native('contract','Chốt hợp đồng','contracts','edit',true),manual('production-request','Đề nghị tạo lệnh sản xuất','orders','edit'),manual('production-approve','Duyệt đề nghị tạo lệnh','production','issue',true),native('issue','Phát hành lệnh sản xuất','production','issue')]},
 {id:'contract',name:'Thương thảo và chốt hợp đồng',steps:[manual('negotiate','Thương thảo hợp đồng','contracts','edit'),native('sign','Chốt hợp đồng','contracts','edit',true)]},
 {id:'production',name:'Rà soát và thực hiện lệnh sản xuất',steps:[manual('review','Rà soát lệnh và hồ sơ kỹ thuật','production','confirm'),manual('materials','Mua / chuẩn bị vật tư','purchasing','edit'),native('complete','Sản xuất và xác nhận hoàn thành','production','complete')]},
 {id:'purchase',name:'Đề nghị mua và nhập kho',steps:[manual('review','Rà soát đề nghị mua','purchasing','edit'),native('approve','Duyệt mua','purchasing','approve'),native('execute','Đặt hàng, giao hàng và nhận hàng','purchasing','edit'),native('stock','Nhập kho và ghi nhận chi phí','inventory','create')]},
 ...types.filter(t=>!t.external&&t.active!==false).map(t=>({id:'service:'+t.id,name:t.name,steps:[...(t.id==='supply'?[manual('technical','Rà soát thông tin kỹ thuật','production'),manual('stock','Kho xác nhận lượng đáp ứng và lượng cần mua','inventory'),manual('price','Vật tư–giá xác nhận giá và khả năng đáp ứng','purchasing')]:[manual('review','Rà soát nội dung đề nghị',t.module)]),native('approve','Duyệt và chỉ định đơn vị thực hiện',t.module,t.approve),...(t.id==='supply'?[manual('purchase','Mua / chuẩn bị phần vật tư còn thiếu','purchasing','edit')]:[]),native('execute','Thực hiện và bàn giao kết quả',t.workModule||t.module,t.work)]}))];}
module.exports=function create({sql,fail,transaction,readBody,audit}){
 const now=()=>new Date().toISOString(),one=(q,...a)=>sql.prepare(q).get(...a),all=(q,...a)=>sql.prepare(q).all(...a);
 const get=(kind,id)=>{const r=one('SELECT * FROM enterprise_records WHERE kind=? AND id=?',kind,id);return r?{...JSON.parse(r.document),id:r.id,version:r.version}:null;};
 const rows=kind=>all('SELECT * FROM enterprise_records WHERE kind=?',kind).map(r=>({...JSON.parse(r.document),id:r.id,version:r.version}));
 const put=(kind,id,d)=>{const version=(get(kind,id)?.version||0)+1;sql.prepare('INSERT INTO enterprise_records VALUES(?,?,?,?) ON CONFLICT(kind,id) DO UPDATE SET version=excluded.version,document=excluded.document').run(kind,id,version,JSON.stringify(d));return {...d,id,version};};
 const types=()=>[...require('./service-request-types.cjs').types,...all("SELECT * FROM ops_records WHERE kind='service-request-type'").map(r=>({...require('./service-request-types.cjs').types.find(t=>t.id==='other'),...JSON.parse(r.document),id:r.id}))];
 const catalog=()=>[...templates(types()),...rows('process-definition').filter(d=>d.custom).map(d=>({id:d.id,name:d.name,custom:true,steps:[]}))],definition=id=>get('process-definition',id),instance=(kind,id)=>get('process-instance',kind+':'+id);
 const org=()=>require('./organization.cjs').stored(sql)||{departments:[],positions:[],employees:[]};
 function activeDepartment(id){const d=org(),seen=new Set();while(id){if(seen.has(id))return false;seen.add(id);const row=d.departments.find(x=>x.id===id);if(!row||row.active===false)return false;id=row.parentId;}return seen.size>0;}
 const right=(u,s)=>{if(u.role==='admin')return true;if(s.admin||!AA.allows(u,s.module,s.action,false))return false;if(s.module==='quotes'){const p=require('./access.cjs').permissions(u);if(s.key==='intake')return p.edit&&p.sections.includes('customer');if(s.key==='technical')return p.edit&&p.sections.some(x=>['bom','operations'].includes(x));if(s.key==='materials')return p.edit&&p.costs&&p.sections.includes('materials');if(s.key==='send')return p.commercial;}if(s.key==='care')return require('./access.cjs').permissions(u).commercial;return true;};
 const scope=(u,s)=>u.role==='admin'||!!s.departmentId&&activeDepartment(s.departmentId)&&Scope.context(sql,u).member(s.departmentId);
 const eligible=(u,s)=>!!u&&u.active!==0&&right(u,s)&&scope(u,s)&&routingRight(u,s,'view');
 const current=r=>r?.steps[r._stepIndex??r.index];
 const routingRight=(u,s,a)=>(!s?.routingPermissions&&!['return','propose'].includes(a))||AA.allows(u,'processRouting',a,false);
 function activeIndices(r){if(!r||r.state!=='running')return [];let end=r.index+1;while(end<r.steps.length&&r.steps[end].parallelWithPrevious)end++;return Array.from({length:end-r.index},(_,i)=>r.index+i).filter(i=>!r.steps[i].completedAt);}
 function selectStep(r,i){Object.defineProperty(r,'_stepIndex',{value:i,writable:true,configurable:true,enumerable:false});return r;}
 function phaseStart(r){let i=r.index;while(i>0&&r.steps[i].parallelWithPrevious)i--;return i;}

 function manage(u,s){return u.role==='admin'||!!s?.departmentId&&activeDepartment(s.departmentId)&&!Scope.context(sql,u).legacy&&Scope.context(sql,u).managesDepartment(s.departmentId);}
 function allowed(r,u){const s=current(r);return r?.state==='running'&&!r.correction&&!!s&&!s.completedAt&&eligible(u,s)&&(s.assigneeId?s.assigneeId===u.id||u.role==='admin'||!!s.pendingReview&&manage(u,s):manage(u,s));}
 function needsReview(s){return !!s?.assigneeId&&!s.admin&&!manage(people().find(u=>u.id===s.assigneeId)||{},s);}
 function canFinalize(r,u){const s=current(r);return allowed(r,u)&&routingRight(u,s,'confirm')&&!s.proposal&&(!needsReview(s)||!!s.pendingReview&&manage(u,s));}
 function submitReview(r,u,content){const s=current(r);if(r.correction||!routingRight(u,s,'submit')||!needsReview(s)||s.assigneeId!==u.id||!eligible(u,s))fail(403,'Chỉ nhân viên được giao gửi kết quả rà soát');if(s.pendingReview)fail(409,'Kết quả đang chờ trưởng phòng rà soát');s.pendingReview={actorId:u.id,actor:u.name,at:now(),note:content};log(r,u,'submit-review',content);const out=put('process-instance',r.id,r);notify(out);return out;}
 function visible(r,u){return u.role==='admin'||r.creatorId===u.id||r.steps.some(s=>right(u,s)&&routingRight(u,s,'view')&&(scope(u,s)||manage(u,s)));}
 function note(b){if(typeof b.note!=='string'||!b.note.trim()||b.note.length>3000)fail(400,'Nhập nội dung xác nhận / lý do (tối đa 3.000 ký tự)');return b.note.trim();}
 function log(r,u,action,content){r.history.push({at:now(),actorId:u.id,actor:u.name,action,stepKey:current(r)?.key||'',note:content});r.updated=now();}
 const people=()=>all('SELECT * FROM users WHERE active=1 AND deleted_at IS NULL');
 function notify(r){for(const i of activeIndices(r)){selectStep(r,i);const s=current(r);require('./work-notifications.cjs').notify(sql,r.correction?[r.creatorId]:people().filter(u=>allowed(r,u)||manage(u,s)).map(u=>u.id),r.code+' · '+(r.correction?'Trả lại xử lý':s.name),'process:'+r.id);}delete r._stepIndex;}
 function start(kind,id,selector,code,u){if(instance(kind,id))return;const d=definition(selector);if(!d?.active)return;for(const step of d.steps)if(!step.admin&&(!activeDepartment(step.departmentId)||!people().some(u=>u.role!=='admin'&&eligible(u,step))))fail(409,'Quy trình cần cập nhật đơn vị / nhân sự đủ quyền: '+step.name);const r=put('process-instance',kind+':'+id,{kind,sourceId:id,selector,name:d.name,code,definitionVersion:d.version,steps:structuredClone(d.steps),index:0,state:'running',creatorId:u.id,created:now(),updated:now(),history:[]});notify(r);return r;}
 function guard(kind,id,key,u){const r=instance(kind,id);if(!r)return;const s=current(r);if(r.state!=='running'||s?.key!==key)fail(409,'Quy trình '+r.code+': cần xử lý bước '+(s?.name||r.state)+' trước');if(!allowed(r,u))fail(403,'Không thuộc đơn vị / người được giao bước '+s.name+' hoặc thiếu quyền nghiệp vụ');}
 function advance(r,u,content){log(r,u,'complete',content);if(current(r).pendingReview){log(r,u,'review',content);current(r).reviewedBy=u.id;current(r).reviewedAt=now();delete current(r).pendingReview;}current(r).completedAt=now();delete current(r).proposal;while(r.index<r.steps.length&&r.steps[r.index].completedAt)r.index++;delete r._stepIndex;if(r.index===r.steps.length)r.state='completed';const out=put('process-instance',r.id,r);notify(out);return out;}
 function complete(kind,id,key,u,content){const r=instance(kind,id);if(!r)return;guard(kind,id,key,u);if(!canFinalize(r,u))fail(403,'Nhân viên gửi kết quả tại Quy trình & phân luồng; trưởng phòng rà soát và xác nhận tại hồ sơ gốc trước khi chuyển bước');return advance(r,u,content);}
 function stop(kind,id,u,content){const r=instance(kind,id);if(!r||r.state!=='running')return;log(r,u,'cancel',content);r.state='cancelled';put('process-instance',r.id,r);}
 function reset(kind,id,key,u){const r=instance(kind,id);if(!r||r.state==='cancelled')return;const i=r.steps.findIndex(s=>s.key===key);if(i<0||i>=r.index)return;log(r,u,'reopen','Mở lại từ '+r.steps[i].name);r.index=i;r.state='running';for(const s of r.steps.slice(i)){delete s.completedAt;delete s.pendingReview;delete s.reviewedBy;delete s.reviewedAt;}const out=put('process-instance',r.id,r);notify(out);}
 const ops=(kind,id)=>{const x=one('SELECT document FROM ops_records WHERE kind=? AND id=?',kind,id);return x?JSON.parse(x.document):null;};
 function event(u,action,id,detail){
  if(action==='handoff:created'){const q=one('SELECT code FROM quotes WHERE id=?',id);if(q)start('quote',id,'quote',q.code,u);}
  if(['handoff:intake','handoff:technical','handoff:materials','approved'].includes(action)){const key=action==='approved'?'approve':action.slice(8);const r=instance('quote',id),i=r?.steps.findIndex(s=>s.key===key);if(action!=='approved'&&r&&i<r.index){if(!eligible(u,r.steps[i]))fail(403,'Không thuộc đơn vị xác nhận theo quy trình');}else complete('quote',id,key,u,action);}
  if(action==='draft'&&one("SELECT status FROM revisions WHERE id=? ORDER BY version DESC LIMIT 1 OFFSET 1",id)?.status==='approved')reset('quote',id,'approve',u);
  if(action.startsWith('handoff:reopen:'))reset('quote',id,action.slice(15),u);
  if(action==='quote:work'){const r=instance('quote',id);if(r){const change=JSON.parse(detail||'{}');let changed=false;for(const key of ['technical','materials']){const field=key+'Id',before=change.before?.[field]||'',after=change.after?.[field]||'';if(before===after)continue;const s=r.steps.find(s=>s.key===key);if(!routingRight(u,s,'assign')||!manage(u,s))fail(403,'Chỉ quản lý đơn vị trong quy trình được giao phần việc này');if(after){const person=people().find(p=>p.id===after);if(!eligible(person,s))fail(400,'Người nhận không thuộc đơn vị trong quy trình hoặc thiếu quyền');delete s.pendingReview;s.assigneeId=person.id;s.assigneeName=person.name;}else{delete s.pendingReview;delete s.assigneeId;delete s.assigneeName;}changed=true;}if(changed){log(r,u,'assign','Cập nhật phân công từ hồ sơ báo giá');const saved=put('process-instance',r.id,r);notify(saved);}}}
  if(action.startsWith('work:start:'))guard('quote',id,action.slice(11),u);
  if(action==='commercial:sent'){const row=one('SELECT document FROM commercial WHERE id=?',id),d=row?JSON.parse(row.document):{},latest=one("SELECT MAX(version) v FROM revisions WHERE id=? AND status='approved'",id)?.v,r=instance('quote',id);if(d.offerVersion===latest&&r&&current(r)?.key!=='care'&&r.state!=='completed')complete('quote',id,'send',u,'Đã gửi chào giá');}
  if(action==='offer:care'){const row=one('SELECT document FROM commercial WHERE id=?',id),doc=row?JSON.parse(row.document):{},version=Number(String(detail||'').slice(1)),latest=one("SELECT MAX(version) v FROM revisions WHERE id=? AND status='approved'",id)?.v,entry=doc.dispatches?.[version];if(version===latest&&entry?.entries?.at(-1)?.kind==='close'&&instance('quote',id)?.state==='running')complete('quote',id,'care',u,'Đã kết thúc chăm sóc');}
  if(action==='delete-draft')stop('quote',id,u,'Đã xóa bản nháp');
  if(action==='create-order'){const o=one('SELECT * FROM orders WHERE id=?',id),q=instance('quote',o.quote_id);if(q&&q.state!=='completed'&&current(q)?.key!=='care')fail(409,'Gửi chào giá theo quy trình trước khi trình chốt đơn hàng');start('order',id,'order',o.code,u);}
  if(action==='confirm-order')complete('order',id,'confirm',u,'Đã chốt đơn hàng');
  if(action==='order:cancel')stop('order',id,u,'Đơn hàng đã hủy');
  if(action==='contract:save'){const c=one("SELECT document FROM business_records WHERE kind='contract' AND id=?",id);if(c){const d=JSON.parse(c.document),before=JSON.parse(detail||'{}').before;if(instance('contract',id)&&before?.status==='active'&&d.status==='active'&&['code','customerId','orderId','value','terms','signDate','startDate','endDate'].some(k=>before[k]!==d[k]))fail(409,'Lưu hợp đồng về nháp để thương thảo và duyệt lại thay đổi');if(before?.status==='active'&&d.status==='draft')reset('contract',id,'negotiate',u);if(!instance('contract',id)&&!JSON.parse(detail||'{}').before)start('contract',id,'contract',d.code,u);if(d.status==='active'){if(instance('contract',id)?.state==='cancelled')fail(409,'Quy trình hợp đồng đã dừng; không kích hoạt lại trực tiếp');if(instance('contract',id)?.state==='running')complete('contract',id,'sign',u,'Hợp đồng có hiệu lực');const order=instance('order',d.orderId);if(order?.state==='running'&&current(order)?.key==='contract')complete('order',d.orderId,'contract',u,'Đã chốt hợp đồng '+d.code);}if(d.status==='cancelled')stop('contract',id,u,'Đã hủy hợp đồng');}}
  if(action==='production-issued'){const j=one('SELECT * FROM production_jobs WHERE id=?',id);const parent=instance('order',j.order_id);if(parent?.state==='running')complete('order',j.order_id,'issue',u,'Phát hành '+j.code);start('production',id,'production',j.code,u);}
  if(['production-operation','production-quantity','production-qc'].includes(action)){const r=instance('production',id),j=one('SELECT progress FROM production_jobs WHERE id=?',id),started=action!=='production-operation'||JSON.parse(j.progress).operations.some(o=>o.status!=='pending');if(started&&r&&r.state==='running'&&current(r)?.key!=='complete')fail(409,'Hoàn tất rà soát và chuẩn bị vật tư trong quy trình trước khi sản xuất');}
  if(action==='production-part'){const j=one('SELECT code FROM production_jobs WHERE id=?',id);start('production',id,'production',j.code,u);}
  if(action==='production-complete')complete('production',id,'complete',u,'Hoàn thành lệnh và nhập kho thành phẩm');
  if(['ops:purchase','ops:material-request'].includes(action)){const p=ops('purchase',id);if(p)start('purchase',id,'purchase',p.code,u);}
  if(action==='ops:material-request-review'&&ops('purchase',id)?.state==='rejected')stop('purchase',id,u,'Đề nghị vật tư bị trả lại');
  if(action==='ops:transition'){const p=ops('purchase',id);if(p?.state==='approved')complete('purchase',id,'approve',u,'Đã duyệt mua');else if(p?.state==='rejected'){guard('purchase',id,'approve',u);stop('purchase',id,u,'Đề nghị mua bị từ chối');}else if(p?.state==='stocked')complete('purchase',id,'stock',u,'Đã nhập kho');else if(p?.state==='received')complete('purchase',id,'execute',u,'Đã nhận đủ hàng');else if(p&&instance('purchase',id))guard('purchase',id,'execute',u);}
  if(action.startsWith('ops:service-requests:')){const a=action.slice('ops:service-requests:'.length),r=ops('service-request',id);if(!r)return;if(a==='create')start('service',id,'service:'+r.type,r.code,u);else if(a==='approve'){const p=instance('service',id);if(p&&r.assigneeId){const ex=p.steps.find(s=>s.key==='execute'),person=people().find(x=>x.id===r.assigneeId);if(!eligible(person,ex))fail(400,'Người thực hiện phải thuộc đơn vị trong quy trình và đủ quyền');ex.assigneeId=person.id;ex.assigneeName=person.name;put('process-instance',p.id,p);}complete('service',id,'approve',u,'Đề nghị đã duyệt');}else if(['receive','issue','complete','accept'].includes(a)&&r.state==='completed'){const p=instance('service',id);if(p&&a==='accept'){const approver=p.steps.find(s=>s.key==='approve');if(p.state!=='running'||current(p)?.key!=='execute'||!eligible(u,approver))fail(403,'Không thuộc đơn vị duyệt nghiệm thu');if(needsReview(current(p))&&!canFinalize(p,u))fail(403,'Trưởng phòng phải rà soát kết quả trước khi nghiệm thu');advance(p,u,'Nghiệm thu hoàn thành đề nghị');}else complete('service',id,'execute',u,'Hoàn thành đề nghị');}else if(['reject','withdraw'].includes(a))stop('service',id,u,a);}
 }
 function canApproveEarly(r,u){const i=r?.steps.findIndex(s=>s.key==='approve');return u.role==='admin'&&r?.selector==='service:supply'&&r.state==='running'&&i>r.index&&ops('service-request',r.sourceId)?.state==='pending'&&r.steps.slice(r.index,i).every(s=>!s.native);}
 function prepareEarlyApproval(id,u,b){const r=instance('service',id);if(u.role!=='admin')fail(403,'Chỉ Admin được duyệt trước xác nhận');if(!canApproveEarly(r,u))fail(409,'Đề nghị không còn ở bước cho phép duyệt sớm');if(b.processVersion!==r.version)fail(409,'Quy trình đã thay đổi; tải lại trước khi duyệt');const content=note(b),i=r.steps.findIndex(s=>s.key==='approve');for(const s of r.steps.slice(r.index,i))if(!s.completedAt)s.bypassedApproval={at:now(),actorId:u.id,actor:u.name,note:content};log(r,u,'approve-early',content);delete r.correction;r.index=i;put('process-instance',r.id,r);}
 const supplyReview=require('./supply-review.cjs')({sql,fail,now});
 function serviceActions(r,u,actions){
  const p=instance('service',r.id);if(!p)return actions;
  return actions.filter(a=>{
   if(a==='withdraw')return true;if(a==='edit')return !!p.correction;
   if(p.state!=='running')return false;
   const step=current(p);
   if(['approve','reject'].includes(a))return step.key==='approve'&&(a==='approve'?canFinalize(p,u):allowed(p,u)&&routingRight(u,step,'return'));
   if(['accept','return'].includes(a))return step.key==='execute'&&!p.correction&&routingRight(u,step,a==='accept'?'confirm':'return')&&eligible(u,p.steps.find(s=>s.key==='approve'));
   return ['receive','issue','start','complete'].includes(a)&&step.key==='execute'&&(a==='start'?allowed(p,u):canFinalize(p,u));
  });
 }
 function readiness(s){const issues=[],warnings=[],department=org().departments.find(d=>d.id===s.departmentId),label=department?.name||'Chưa chọn đơn vị';if(s.admin)return {key:s.key,name:s.name,issues,warnings};if(!activeDepartment(s.departmentId))issues.push('Chọn đơn vị đang hoạt động');else{const members=people().filter(u=>u.role!=='admin'&&scope(u,s));if(!members.length){const admins=people().some(u=>u.role==='admin'&&Scope.context(sql,u).member(s.departmentId));issues.push(admins&&s.key==='approve'?'Đơn vị chỉ có tài khoản Admin; chọn “Admin — người quản trị duyệt” ở bước này':label+': chưa có tài khoản nhân sự hoạt động trong đơn vị');}else{if(!members.some(u=>eligible(u,s))){issues.push(label+': '+members.map(u=>{const missing=[];if(!AA.allows(u,s.module,s.action,false))missing.push((AA.schema[s.module]?.[0]||s.module)+' / '+(AA.labels[s.action]||s.action));if(!routingRight(u,s,'view'))missing.push('Xử lý quy trình / Xem');if(!missing.length&&!right(u,s))missing.push('phạm vi dữ liệu nghiệp vụ của bước');return u.name+': '+(missing.length?'thiếu '+missing.join(', '):'chưa đủ quyền');}).join('; '));}const heads=members.filter(u=>manage(u,s));if(!heads.length)warnings.push(label+': chưa có nhân sự ở vị trí được đánh dấu Quản lý. Tên “Trưởng phòng” hoặc “Quản đốc” không tự cấp quyền quản lý.');else if(!heads.some(u=>eligible(u,s)&&routingRight(u,s,'confirm')))warnings.push(label+': trưởng phòng chưa đủ quyền Xác nhận quy trình và quyền nghiệp vụ; Admin phải xử lý cho đến khi cấp đủ quyền.');}}
 return {key:s.key,name:s.name,issues,warnings};}
 function validate(b){if(b.receiptCompletion!==undefined&&typeof b.receiptCompletion!=='boolean')fail(400,'Chọn cách hoàn tất hợp lệ');const receiptCompletion=b.receiptCompletion??definition(b.id)?.receiptCompletion??false;const custom=/^custom-[a-f0-9-]{36}$/.test(b.id||'');const model=custom?{custom:true,name:b.name,steps:[]}:catalog().find(t=>t.id===b.id);if(custom&&(typeof b.name!=='string'||!b.name.trim()||b.name.length>160))fail(400,'Nhập tên quy trình, tối đa 160 ký tự');if(!model)fail(400,'Không có loại quy trình');if(typeof b.active!=='boolean'||!Array.isArray(b.steps)||b.steps.length<Math.max(1,model.steps.length)||b.steps.length>30)fail(400,'Thiếu bước bắt buộc hoặc vượt 30 bước');const required=b.steps.filter(x=>model.steps.some(s=>s.key===x.key));if(required.length!==model.steps.length||required.some((s,i)=>s.key!==model.steps[i].key))fail(400,'Giữ đủ và đúng thứ tự các bước nghiệp vụ');const seen=new Set();const steps=b.steps.map(x=>{if(!x||typeof x.key!=='string'||seen.has(x.key))fail(400,'Mã bước không hợp lệ hoặc bị trùng');seen.add(x.key);let s=model.steps.find(s=>s.key===x.key);if(!s){if(!/^review-[a-zA-Z0-9-]{8,80}$/.test(x.key)||typeof x.name!=='string'||!x.name.trim()||x.name.length>160||!Object.hasOwn(AA.modules,x.module))fail(400,'Bước rà soát cần tên và nghiệp vụ hợp lệ');s=manual(x.key,x.name.trim(),x.module);}if(x.admin===true&&!s.admin){if(!custom&&s.key!=='approve')fail(400,'Chỉ bước duyệt được chọn Admin');s={...s,admin:true};}if(b.id==='service:supply'&&receiptCompletion===true&&s.key==='execute')s={...s,name:'Nhập kho và hoàn tất đề nghị',module:'inventory',action:'create',receiptCompletion:true};const d=s.admin?'':typeof x.departmentId==='string'?x.departmentId:'';if(d&&!activeDepartment(d))fail(400,'Bộ phận không còn hoạt động');if(b.active&&!s.admin&&!d)fail(400,'Chọn đơn vị cho bước '+s.name);if(typeof x.instructions!=='string'||x.instructions.length>2000)fail(400,'Nội dung xử lý tối đa 2.000 ký tự');const out={...s,departmentId:d,instructions:x.instructions.trim(),routingPermissions:true,parallelWithPrevious:x.parallelWithPrevious===true};return out;});for(let i=0;i<steps.length;i++)if(steps[i].parallelWithPrevious&&(i===0||steps[i].native||steps[i].admin||steps[i-1].native||steps[i-1].admin))fail(400,'Chỉ ghép song song các bước rà soát; giữ riêng bước duyệt và chứng từ: '+steps[i].name);if(b.active){const failures=steps.map(readiness).filter(x=>x.issues.length);if(failures.length)fail(400,'Chưa thể áp dụng quy trình:\n'+failures.map(x=>x.name+': '+x.issues.join('; ')).join('\n'));}return {receiptCompletion:b.id==='service:supply'&&receiptCompletion===true,name:model.name.trim(),...(custom?{custom:true}:{}),active:b.active,steps};}
 function actionHint(r,u){const s=current(r);if(!s||r.state!=='running')return '';if(!scope(u,s))return 'Bước này thuộc bộ phận khác; bạn chỉ theo dõi.';if(!eligible(u,s))return 'Chưa đủ quyền nghiệp vụ hoặc quyền Xem quy trình của bước này. Liên hệ Admin kiểm tra bộ quyền vị trí.';if(r.correction)return 'Hồ sơ đang chờ người đề nghị điều chỉnh và gửi lại.';if(!manage(u,s)&&s.assigneeId!==u.id)return s.assigneeId?'Bước này đã giao cho '+(s.assigneeName||'nhân sự khác')+'.':'Chưa được giao xử lý. Trưởng phòng hoặc Admin cần giao bước này cho bạn. Nếu bạn là trưởng phòng, Admin cần bật Quản lý tại vị trí thuộc đúng bộ phận.';if(s.pendingReview&&!manage(u,s))return 'Đã gửi kết quả; chờ trưởng phòng rà soát và xác nhận.';if(s.native)return 'Thực hiện tại hồ sơ nghiệp vụ gốc.';if(!routingRight(u,s,needsReview(s)&&!manage(u,s)?'submit':'confirm'))return 'Thiếu quyền Trình duyệt hoặc Xác nhận quy trình; liên hệ Admin cấp đúng quyền.';return '';}
 function stepProjection(r,u){const s=current(r);return {...r,canComplete:canFinalize(r,u)&&!s.native,canSubmitReview:!r.correction&&routingRight(u,s,'submit')&&r.state==='running'&&needsReview(s)&&s.assigneeId===u.id&&eligible(u,s)&&!s.pendingReview,canReview:routingRight(u,s,'return')&&r.state==='running'&&!!s.pendingReview&&manage(u,s)&&eligible(u,s),responsibleManagers:s&&!s.admin?people().filter(p=>manage(p,s)&&p.role!=='admin').map(p=>({id:p.id,name:p.name})):[],canAssign:routingRight(u,s,'assign')&&r.state==='running'&&manage(u,s)&&!s.admin,canChangeExecutor:r.kind==='service'&&s?.key==='approve'&&allowed(r,u),candidates:r.state==='running'&&manage(u,s)?people().filter(x=>eligible(x,s)).map(x=>({id:x.id,name:x.name})):[]};}
 function projection(r,u){delete r._stepIndex;const result=stepProjection(r,u);result.activeSteps=activeIndices(r).map(i=>{selectStep(r,i);const p=stepProjection(r,u),s=current(r);return {key:s.key,index:i,actionHint:actionHint(r,u),canComplete:p.canComplete,canSubmitReview:p.canSubmitReview,canReview:p.canReview,canAssign:p.canAssign,candidates:p.candidates,responsibleManagers:p.responsibleManagers,canReturn:!r.correction&&!s.native&&manage(u,s)&&allowed(r,u)&&routingRight(u,s,'return'),canPropose:!r.correction&&allowed(r,u)&&routingRight(u,s,'propose'),canResolveProposal:!!s.proposal&&AA.allows(u,'processRouting','confirm',false)&&manage(u,s)&&eligible(u,s)&&routingRight(u,s,'confirm')};});delete r._stepIndex;result.supplyReview=r.selector==='service:supply'?supplyReview.view(r.sourceId,u):null;result.canApproveEarly=canApproveEarly(r,u);result.canResubmit=!!r.correction&&(u.role==='admin'||u.id===r.creatorId);return result;}
 async function handle({req,route,user,send}){
  if(route!=='/api/process-routing')return false;
  if(req.method==='GET'){const admin=user.role==='admin',d=org();send(200,{canConfigure:admin,availableProcesses:(admin||AA.allows(user,'processRouting','submit',false)&&AA.allows(user,'processRouting','view',false))?rows('process-definition').filter(d=>d.custom&&d.active).map(d=>({id:d.id,name:d.name})):[],definitions:admin?catalog().map(t=>{const d={...t,version:0,active:false,...definition(t.id)};return {...d,readiness:d.steps.map(readiness)};}):[],departments:d.departments.filter(x=>activeDepartment(x.id)).map(x=>({id:x.id,name:x.name,parentId:x.parentId})),instances:rows('process-instance').filter(r=>visible(r,user)).map(r=>projection(r,user))});return true;}
  if(req.method!=='POST')fail(405,'Phương thức không hỗ trợ');const b=await readBody(req,150000);
  const result=transaction(()=>{
   if(b.action==='save'){if(user.role!=='admin')fail(403,'Chỉ Admin cấu hình quy trình');const old=definition(b.id);if(b.expectedVersion!==(old?.version||0))fail(409,'Quy trình đã thay đổi; tải lại trước khi lưu');const d=validate(b);if(old)put('process-definition-history',b.id+'@'+old.version,old);const saved=put('process-definition',b.id,{...d,updated:now(),actor:user.id});audit(user,'process:configure',b.id,'v'+saved.version);return saved;}
   if(b.action==='start-custom'){
    if(user.role!=='admin'&&(!AA.allows(user,'processRouting','submit',false)||!AA.allows(user,'processRouting','view',false)))fail(403,'Cần quyền Xem và Trình duyệt quy trình');
    const d=definition(b.definitionId);if(!d?.custom||!d.active)fail(400,'Chọn quy trình riêng đang áp dụng');
    if(typeof b.title!=='string'||!b.title.trim()||b.title.length>200||typeof b.description!=='string'||b.description.length>3000)fail(400,'Nhập tên công việc (tối đa 200 ký tự) và nội dung (tối đa 3.000 ký tự)');
    if(!/^[a-f0-9-]{36}$/.test(b.requestId||''))fail(400,'Thiếu mã yêu cầu tạo công việc');
    const previous=instance('custom',b.requestId);if(previous){if(previous.creatorId!==user.id)fail(409,'Mã yêu cầu đã được sử dụng');return projection(previous,user);}
    const r=start('custom',b.requestId,d.id,b.title.trim(),user);r.description=b.description.trim();log(r,user,'create',r.description);const saved=put('process-instance',r.id,r);audit(user,'process:create',r.id,r.code);return projection(saved,user);
   }
   const r=get('process-instance',b.id);if(!r||!visible(r,user))fail(404,'Không có công việc trong phạm vi');if(b.expectedVersion!==r.version)fail(409,'Công việc đã thay đổi; tải lại trước khi xử lý');if(r.state!=='running')fail(409,'Quy trình không còn đang chạy');if(b.stepKey){const i=r.steps.findIndex(s=>s.key===b.stepKey);if(!activeIndices(r).includes(i))fail(409,'Bước không còn được xử lý; tải lại quy trình');selectStep(r,i);}const s=current(r),content=note(b);
   if(b.action==='supply-review'){
    if(r.selector!=='service:supply'||!['stock','price'].includes(s.key)||!allowed(r,user)||!routingRight(user,s,needsReview(s)&&!manage(user,s)?'submit':'confirm'))fail(403,'Không được cập nhật bước này');
    if(s.pendingReview&&!manage(user,s))fail(409,'Đang chờ trưởng phòng rà soát');supplyReview.save(r.sourceId,s.key,b,user);log(r,user,'supply-review',content);let out;if(b.finish===true){if(needsReview(s)&&s.assigneeId===user.id&&!manage(user,s))out=submitReview(r,user,content);else{if(!canFinalize(r,user))fail(403,'Chờ nhân viên gửi trưởng phòng rà soát');out=advance(r,user,content);}}else out=put('process-instance',r.id,r);audit(user,'process:supply-review',r.id,content);return projection(out,user);
   }
   if(b.action==='resubmit'){if(!r.correction||(user.role!=='admin'&&user.id!==r.creatorId))fail(403,'Chỉ người đề nghị được gửi lại hồ sơ');delete r.correction;log(r,user,'resubmit',content);const out=put('process-instance',r.id,r);notify(out);audit(user,'process:resubmit',r.id,content);return projection(out,user);}
   if(b.action==='return'){if(s.native||!manage(user,s)||!allowed(r,user)||!routingRight(user,s,'return'))fail(403,'Chưa được cấp quyền trả lại tại bước này');const start=phaseStart(r);r.correction={actor:user.name,actorId:user.id,at:now(),note:content,stepKey:s.key};log(r,user,'return',content);let end=r.index+1;while(end<r.steps.length&&r.steps[end].parallelWithPrevious)end++;for(const step of r.steps.slice(start,end)){delete step.completedAt;delete step.pendingReview;delete step.reviewedAt;delete step.reviewedBy;}r.index=start;delete r._stepIndex;const out=put('process-instance',r.id,r);notify(out);audit(user,'process:return',r.id,content);return projection(out,user);}
   if(b.action==='propose'){if(!allowed(r,user)||!routingRight(user,s,'propose'))fail(403,'Chưa được cấp quyền đề xuất điều chỉnh');if(s.proposal)fail(409,'Đề xuất trước đang chờ rà soát');s.proposal={actor:user.name,actorId:user.id,at:now(),note:content};log(r,user,'propose',content);const out=put('process-instance',r.id,r);notify(out);audit(user,'process:propose',r.id,content);return projection(out,user);}
   if(b.action==='resolve-proposal'){if(!AA.allows(user,'processRouting','confirm',false)||!s.proposal||!manage(user,s)||!eligible(user,s)||!routingRight(user,s,'confirm'))fail(403,'Chỉ trưởng phòng đủ quyền được rà soát đề xuất');if(!['accept','reject'].includes(b.decision))fail(400,'Chọn kết quả rà soát đề xuất');log(r,user,'resolve-proposal',b.decision+': '+content+' — '+s.proposal.note);delete s.proposal;delete s.pendingReview;if(b.decision==='accept'){const start=phaseStart(r);let end=r.index+1;while(end<r.steps.length&&r.steps[end].parallelWithPrevious)end++;for(const step of r.steps.slice(start,end)){delete step.completedAt;delete step.pendingReview;delete step.reviewedAt;delete step.reviewedBy;}r.correction={actor:user.name,actorId:user.id,at:now(),note:'Đề xuất đã được chấp nhận: '+content,stepKey:s.key};r.index=start;delete r._stepIndex;}const out=put('process-instance',r.id,r);notify(out);audit(user,'process:resolve-proposal',r.id,content);return projection(out,user);}

   if(b.action==='submit-review')return projection(submitReview(r,user,content),user);
   if(b.action==='return-review'){if(!routingRight(user,s,'return')||!s.pendingReview||!manage(user,s)||!eligible(user,s))fail(403,'Chỉ trưởng phòng được trả lại kết quả');delete s.pendingReview;log(r,user,'return-review',content);const out=put('process-instance',r.id,r);notify(out);return projection(out,user);}
   if(b.action==='complete'){if(s.native)fail(409,'Thực hiện và xác nhận tại hồ sơ nghiệp vụ gốc');if(!allowed(r,user))fail(403,'Không được xử lý bước này');if(needsReview(s)&&s.assigneeId===user.id&&!manage(user,s))return projection(submitReview(r,user,content),user);if(!canFinalize(r,user))fail(403,'Chờ nhân viên gửi kết quả để trưởng phòng rà soát');const out=advance(r,user,content);audit(user,'process:complete',r.id,content);return projection(out,user);}
   if(b.action==='assign'){if(!routingRight(user,s,'assign')||!manage(user,s)||s.admin)fail(403,'Chỉ quản lý đơn vị được phân công');const person=people().find(p=>p.id===b.assigneeId);if(!eligible(person,s))fail(400,'Chọn nhân sự trong đơn vị và đủ quyền nghiệp vụ');delete s.pendingReview;s.assigneeId=person.id;s.assigneeName=person.name;if(r.kind==='service'&&s.key==='execute'){const row=one("SELECT * FROM ops_records WHERE kind='service-request' AND id=?",r.sourceId),doc=JSON.parse(row.document);doc.assigneeId=person.id;doc.assigneeName=person.name;sql.prepare("UPDATE ops_records SET document=?,version=version+1 WHERE kind='service-request' AND id=?").run(JSON.stringify(doc),r.sourceId);}if(r.kind==='quote'&&['send','care'].includes(s.key)){const version=one("SELECT MAX(version) v FROM revisions WHERE id=? AND status='approved'",r.sourceId)?.v,row=one('SELECT document FROM commercial WHERE id=?',r.sourceId),d=row?JSON.parse(row.document):{},e=d.dispatches?.[version];if(!e)fail(409,'Chưa có bản chào đã duyệt để phân công');if(s.key==='send')e.senderId=person.id;else e.careOwnerId=person.id;d.version=(d.version||0)+1;sql.prepare('UPDATE commercial SET document=?,version=? WHERE id=?').run(JSON.stringify(d),d.version,r.sourceId);}if(r.kind==='quote'&&['technical','materials'].includes(s.key)){const old=one('SELECT document FROM quote_handoffs WHERE quote_id=?',r.sourceId),h=old?JSON.parse(old.document):{},w=h.work||{};h.work={...w,[s.key+'Id']:person.id,revision:(w.revision||0)+1,updated:now(),actor:user.name};sql.prepare('INSERT INTO quote_handoffs VALUES(?,?) ON CONFLICT(quote_id) DO UPDATE SET document=excluded.document').run(r.sourceId,JSON.stringify(h));}log(r,user,'assign',content+' · '+person.name);}
   else if(b.action==='executor'){if(r.kind!=='service'||s.key!=='approve'||!allowed(r,user))fail(403,'Chỉ người duyệt chỉ định đơn vị thực hiện');const ex=r.steps.find(s=>s.key==='purchase')||r.steps.find(s=>s.key==='execute');if(!activeDepartment(b.departmentId))fail(400,'Chọn đơn vị đang hoạt động');ex.departmentId=b.departmentId;delete ex.assigneeId;delete ex.assigneeName;if(!people().some(p=>p.role!=='admin'&&eligible(p,ex)))fail(400,'Đơn vị chưa có nhân sự đủ quyền thực hiện');log(r,user,'executor',content);}
   else if(b.action==='migrate'){
    if(user.role!=='admin')fail(403,'Chỉ Admin chuyển phiên bản quy trình');const d=definition(r.selector);if(!d?.active||b.definitionVersion!==d.version)fail(409,'Chọn phiên bản quy trình đang áp dụng');
    if(d.steps.length!==r.steps.length||d.steps.some((s,i)=>s.key!==r.steps[i].key))fail(409,'Các bước không tương thích');
    if(r.kind==='service'&&!!d.steps.find(s=>s.key==='execute')?.receiptCompletion!==!!r.steps.find(s=>s.key==='execute')?.receiptCompletion&&ops('service-request',r.sourceId)?.lines?.some(l=>l.issued>0||l.received>0))fail(409,'Đề nghị đã có nhập/xuất kho; không đổi cách hoàn tất');
    let from=r.index;if(activeIndices(r).length>1||phaseStart(r)!==r.index||r.steps.slice(r.index).some(s=>s.completedAt)){
     let end=r.index+1;while(end<r.steps.length&&r.steps[end].parallelWithPrevious)end++;
     const keys=['key','name','module','action','admin','native','departmentId','instructions','parallelWithPrevious','receiptCompletion'];
     if(r.steps.slice(0,end).some((s,i)=>keys.some(k=>(s[k]??false)!==(d.steps[i][k]??false))))fail(409,'Giữ nguyên nhóm đang rà soát song song; chỉ đổi các bước chưa bắt đầu');from=end;
    }
    if(from>0&&d.steps[from]?.parallelWithPrevious)fail(409,'Không ghép bước mới với nhóm đang xử lý hoặc đã hoàn thành');
    log(r,user,'migrate',content+' · v'+r.definitionVersion+' → v'+d.version);r.steps=r.steps.slice(0,from).concat(structuredClone(d.steps.slice(from)));r.definitionVersion=d.version;
   }
   else fail(400,'Thao tác không hợp lệ');const saved=put('process-instance',r.id,r);notify(saved);audit(user,'process:'+b.action,r.id,content);return projection(saved,user);
  });send(200,result);return true;
 }
 const executorCandidates=id=>{const r=instance('service',id);return r?people().filter(u=>eligible(u,r.steps.find(s=>s.key==='execute'))).map(u=>u.id):undefined;};
 return {handle,event,prepareEarlyApproval,instance,visible,executorCandidates,serviceActions,guard,start,complete,canReviewSource:(kind,id,u)=>{const r=instance(kind,id);return !!r&&!!current(r)?.pendingReview&&canFinalize(r,u);},templates:catalog};
};
