'use strict';
const {randomUUID}=require('node:crypto'),C=require('../core.js'),AA=require('../action-access.js');
// Full calculation documents stay server-side. Only technical packets are returned.
function createProductionChanges({sql,fail,readBody,transaction,audit,packet,canWork}){
 const notice=(j,actions,title,extra=[])=>{const ids=sql.prepare('SELECT * FROM users WHERE active=1 AND deleted_at IS NULL').all().filter(u=>actions.some(a=>AA.allows(u,'production',a,false))).map(u=>u.id);require('./work-notifications.cjs').notify(sql,[...ids,...extra],j.code+' · '+title,'source:production:'+j.id);};
 const one=(s,...a)=>sql.prepare(s).get(...a),all=(s,...a)=>sql.prepare(s).all(...a);
 const get=(kind,id)=>{const r=one('SELECT document FROM ops_records WHERE kind=? AND id=?',kind,id);return r?JSON.parse(r.document):null;};
 const put=(kind,id,d)=>sql.prepare('INSERT INTO ops_records VALUES(?,?,1,?) ON CONFLICT(kind,id) DO UPDATE SET version=version+1,document=excluded.document').run(kind,id,JSON.stringify(d));
 const canPrice=u=>u?.role==='admin'||AA.allows(u,'production','reviewPricing',false)&&require('./access.cjs').permissions(u).costs;
 const totals=d=>{const r=C.calculate(d);return {cost:r.total.cost,material:r.total.material,operations:r.total.ops,transport:r.total.transport,sell:r.total.sell,issues:r.errors||[]};};
 const PD=require('./production-document.cjs');
 const applySelection=(base,proposal,selection)=>PD.apply(base,proposal,selection,fail);
 const clean=(c,u)=>{const {document,impact,appliedImpact,...v}=c;return {...v,...(canPrice(u)&&impact?{...(appliedImpact?{appliedImpact}:{}),impact:{...impact,operationPrices:require('./production-operation-prices.cjs').rows(document,c.rowIds||[c.rowId]),materialPrices:C.flatten(document.quote.products).filter(n=>n.kind==='material'&&(c.rowIds||[c.rowId]).includes(n.id)).map(n=>({rowId:n.id,name:n.name,unit:n.spec?.unit||'kg',unitPrice:n.spec?.price??0}))}}:{})};};
 const confirmable=u=>u.role==='admin'||AA.allows(u,'production','confirm',u.role==='technical'&&require('./access.cjs').permissions(u).sections.includes('operations'));
 const proposeable=u=>AA.allows(u,'production','edit',canWork(u));
 function source(j){let d=get('production-source',j.id);if(d)return d;const o=one('SELECT * FROM orders WHERE id=?',j.order_id),r=one('SELECT document FROM revisions WHERE id=? AND version=?',o.quote_id,o.quote_version);d=JSON.parse(r.document);const p=d.quote.products.find(p=>p.id===j.product_id);d.quote.products=[C.copy(p)];d.quote.products[0].qty=j.quantity;d.quote.nestingPlans=[];d.quote.remnantSelections={};return d;}
 function editable(j){const p=JSON.parse(j.progress);if(j.state!=='ready'||p.operations.some(o=>o.status!=='pending'||o.output>0)||p.qc?.passed||p.qc?.rejected)fail(409,'Lệnh đã bắt đầu sản xuất hoặc QC; không thay đổi thông số của lô đang thực hiện');if(all("SELECT document FROM ops_records WHERE kind='hold'").some(r=>{const h=JSON.parse(r.document);return h.jobId===j.id&&['issued','settled'].includes(h.state);}))fail(409,'Lệnh đã cấp vật tư; cần xử lý lô đang thực hiện trước');}
 function materials(d){const catalog=one('SELECT document FROM catalog ORDER BY version DESC LIMIT 1');const rows=[...(d.materials||[]),...C.flatten(d.quote.products).filter(n=>n.spec).map(n=>n.spec),...(catalog?JSON.parse(catalog.document).materials||[]:[])];return [...new Map(rows.map(m=>[m.id,m])).values()];}
 const safeMaterial=m=>Object.fromEntries(['id','name','shape','props','stockL','stockW','substance','grade','density','massOverride','areaOverride','shapeDefinition','unit'].filter(k=>m[k]!==undefined).map(k=>[k,m[k]]));
 async function handle({req,route,user,send}){
  const editor=route.match(/^\/api\/production\/([a-f0-9-]+)\/changes\/editor$/);if(editor){if(req.method!=='GET')fail(405,'Thao tác không hợp lệ');const j=one('SELECT * FROM production_jobs WHERE id=?',editor[1]);if(!j)fail(404,'Không tìm thấy lệnh');if(!proposeable(user))fail(403,'Chưa có quyền đề nghị thay đổi');editable(j);const d=source(j);d.quote.status='draft';send(200,{jobVersion:j.version,code:j.code,manualBlanks:C.flatten(d.quote.products).filter(n=>n.productionBlank).map(n=>({rowId:n.id,blank:n.productionBlank})),document:require('../technical-core.js').project(d)});return true;}
  const m=route.match(/^\/api\/production\/([a-f0-9-]+)\/changes(?:\/([a-f0-9-]+)\/(confirm|business|pricing|approve|reject|preview))?$/);if(!m)return false;
  const j=one('SELECT * FROM production_jobs WHERE id=?',m[1]);if(!j)fail(404,'Không tìm thấy lệnh');
  if(req.method==='GET'&&!m[2]){const d=source(j),nodes=C.flatten(d.quote.products);send(200,{canPropose:proposeable(user),canConfirm:confirmable(user),canBusiness:AA.allows(user,'production','reviewBusiness',false),canPricing:AA.allows(user,'production','reviewPricing',false),canApprove:AA.allows(user,'production','approveChange',false),jobVersion:j.version,machines:all("SELECT document,id FROM ops_records WHERE kind='machine'").map(r=>({id:r.id,...JSON.parse(r.document)})).filter(x=>x.active!==false).map(x=>({id:x.id,name:x.name,code:x.code})),nodeDetails:C.flatten(require('../technical-core.js').project(d).quote.products).map(n=>({id:n.id,qty:n.qty,lineNote:n.lineNote||'',rule:n.rule,ruleSpec:n.ruleSpec,ops:n.ops.map(o=>Object.fromEntries(require('../technical-core.js').opKeys.filter(k=>o[k]!==undefined).map(k=>[k,o[k]])))})),rules:d.rules.map(r=>({id:r.id,name:r.name,shape:r.shape,length:r.length,width:r.width})),operations:packet(d).operations,products:nodes.filter(n=>n.kind==='product'||n.kind==='component').map(n=>({id:n.id,name:n.name,kind:n.kind,dims:n.dims||{},params:n.params||{}})),materials:materials(d).map(safeMaterial),rows:packet(d).materials.map(r=>{const n=nodes.find(n=>n.id===r.id),numeric=v=>Object.fromEntries(Object.entries(v||{}).filter(([,x])=>typeof x==='number'));return {...r,dims:numeric(n.dims),params:numeric(n.params)};}),changes:all("SELECT document FROM ops_records WHERE kind='production-change'").map(r=>JSON.parse(r.document)).filter(c=>c.jobId===j.id).map(c=>clean(c,user))});return true;}
  if(req.method!=='POST')fail(405,'Thao tác không hợp lệ');const b=await readBody(req,10000000);
  const out=transaction(()=>{const current=one('SELECT * FROM production_jobs WHERE id=?',j.id);if(current.version!==b.expectedVersion)fail(409,'Lệnh đã thay đổi; tải lại trước khi xử lý');
   if(!m[2]){
    if(!proposeable(user))fail(403,'Chưa có quyền đề nghị thay đổi kỹ thuật');editable(current);
    const reason=typeof b.reason==='string'?b.reason.trim():'';if(!reason||reason.length>2000)fail(400,'Nhập lý do thay đổi (tối đa 2000 ký tự)');
    if(b.rowIds!==undefined&&!Array.isArray(b.rowIds))fail(400,'Danh sách dòng không hợp lệ');let d=source(current);const originalDocument=C.copy(d),before=packet(d),items=b.technicalDocument?[]:b.items===undefined?(b.rowIds===undefined?[b.rowId]:b.rowIds).map(rowId=>({...b,rowId})):b.items;if(!Array.isArray(items)||items.some(x=>!x||typeof x!=='object'))fail(400,'Danh sách điều chỉnh không hợp lệ');let rows=items.map(x=>x.rowId),documentDiff=null;if(b.technicalDocument){d=PD.mergeDocument(d,b.technicalDocument,fail,id=>get('machine',id));if(b.blankOverrides!==undefined){if(!Array.isArray(b.blankOverrides)||b.blankOverrides.length>2000||new Set(b.blankOverrides.map(x=>x.rowId)).size!==b.blankOverrides.length)fail(400,'Danh sách khai triển không hợp lệ');for(const x of b.blankOverrides){const n=C.flatten(d.quote.products).find(n=>n.id===x.rowId&&n.kind==='material');if(!n)fail(400,'Dòng khai triển không thuộc lệnh');if(x.blank===null)delete n.productionBlank;else{const blank=x.blank;if(n.spec.shape==='piece'||!blank||!Number.isFinite(blank.length)||blank.length<=0||blank.length>1e7||n.spec.shape==='sheet'&&(!Number.isFinite(blank.width)||blank.width<=0||blank.width>1e7))fail(400,'Kích thước khai triển không hợp lệ');n.productionBlank={length:blank.length,width:n.spec.shape==='sheet'?blank.width:0};}}}documentDiff=PD.describe(originalDocument,d);rows=documentDiff.rows.map(x=>x.id);}
    if(!Array.isArray(rows)||!rows.length||rows.length>500||new Set(rows).size!==rows.length)fail(400,'Chọn từ 1 đến 500 dòng khác nhau');
    let changed=!!documentDiff?.rows.length;
    for(const b of items){const rowId=b.rowId;const n=C.flatten(d.quote.products).find(n=>n.id===rowId&&['material','product','component'].includes(n.kind));if(!n)fail(400,'Dòng vật tư không thuộc lệnh');const original=JSON.stringify(n);
    if(b.qty!==undefined){if(n.kind==='product')fail(400,'Số lượng sản phẩm của lệnh được quản lý qua chia lô');if(typeof b.qty!=='number'||!Number.isFinite(b.qty)||b.qty<=0||b.qty>1e7)fail(400,'Số lượng chi tiết phải lớn hơn 0');n.qty=b.qty;}
    if(b.lineNote!==undefined){if(typeof b.lineNote!=='string'||b.lineNote.length>2000)fail(400,'Ghi chú tối đa 2000 ký tự');n.lineNote=b.lineNote.trim();}
    if(b.ruleId!==undefined){const rule=d.rules.find(r=>r.id===b.ruleId);if(n.kind!=='material'||!rule||rule.shape!==(n.spec.shape==='sheet'?'sheet':'bar'))fail(400,'Chọn công thức phù hợp dạng phôi');n.rule=rule.id;n.ruleSpec=C.copy(rule);delete n.productionBlank;}
    if(b.formula!==undefined){if(n.kind!=='material'||n.spec.shape==='piece'||!b.formula||typeof b.formula.length!=='string'||b.formula.length.length>1000||typeof b.formula.width!=='string'||b.formula.width.length>1000)fail(400,'Công thức khai triển không hợp lệ');n.ruleSpec={...(n.ruleSpec||{}),id:n.rule||'production-rule',name:'Công thức đề nghị sản xuất',shape:n.spec.shape==='sheet'?'sheet':'bar',length:b.formula.length,width:b.formula.width};delete n.productionBlank;}
    if(n.kind!=='material'&&(b.materialId!==undefined||b.props&&Object.keys(b.props).length||b.stockL!==undefined||b.stockW!==undefined||b.blank!==undefined))fail(400,'Chỉ áp dụng thông số phôi cho dòng vật tư');
    if(b.materialId!==undefined&&b.materialId!==n.materialId){const s=materials(d).find(x=>x.id===b.materialId);if(!s||s.shape!==n.spec.shape)fail(400,'Chọn vật tư cùng hình dạng để giữ đúng quy tắc khai triển');n.materialId=s.id;n.spec=C.copy(s);n.name=s.name;}
    const numeric=(v)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>1e7)fail(400,'Thông số kích thước không hợp lệ');return v;};
    for(const [field,allowed]of [['dims',Object.keys(n.dims||{})],['params',Object.keys(n.params||{})],['props',Object.keys(n.spec?.props||{})]]){const values=b[field]||{};if(typeof values!=='object'||Array.isArray(values))fail(400,'Thông số không hợp lệ');for(const [k,v]of Object.entries(values)){if(!allowed.includes(k))fail(400,'Thông số không được hỗ trợ: '+k);(field==='props'?n.spec.props:n[field])[k]=numeric(v);}}
    if(b.unlinkDims!==undefined){if(!Array.isArray(b.unlinkDims)||b.unlinkDims.some(k=>!(Object.hasOwn(n.dims||{},k)&&Object.hasOwn(b.dims||{},k)||Object.hasOwn(n.params||{},k)&&Object.hasOwn(b.params||{},k))))fail(400,'Thông số tách liên kết không hợp lệ');for(const k of b.unlinkDims){if(n.paramLinks)delete n.paramLinks[k];if(n.dimensionLinks?.[k])n.dimensionLinks[k]={mode:'manual',value:b.dims?.[k]??b.params?.[k]};}for(const [k,v]of Object.entries(b.params||{}))C.applyParam(n,k,v);}
    for(const k of ['stockL','stockW'])if(b[k]!==undefined)n.spec[k]=numeric(b[k]);
    if(b.blank!==undefined){if(b.blank===null)delete n.productionBlank;else{if(!b.blank||typeof b.blank!=='object'||Array.isArray(b.blank)||n.spec.shape==='piece')fail(400,'Chọn vật tư có kích thước khai triển');const length=numeric(b.blank.length),width=n.spec.shape==='sheet'?numeric(b.blank.width):0;if(!length||n.spec.shape==='sheet'&&!width)fail(400,'Kích thước khai triển phải lớn hơn 0');n.productionBlank={length,width};}}
    if(b.operations!==undefined){if(!Array.isArray(b.operations)||b.operations.length>100||new Set(b.operations.map(o=>o.index)).size!==b.operations.length)fail(400,'Danh sách công đoạn không hợp lệ');for(const edit of b.operations){const op=n.ops?.[edit.index];if(!Number.isInteger(edit.index)||!op)fail(400,'Công đoạn không thuộc chi tiết');if(edit.mode!==undefined){if(!['inside','outside'].includes(edit.mode))fail(400,'Nơi thực hiện không hợp lệ');op.mode=edit.mode;}if(edit.basisMode!==undefined){if(!['auto','manual_total','manual_unit'].includes(edit.basisMode))fail(400,'Cách khai lượng không hợp lệ');op.basisMode=edit.basisMode;if(edit.basisMode==='auto'){delete op.workQuantity;delete op.quantityDeclared;}}if(edit.workQuantity!==undefined){op.workQuantity=numeric(edit.workQuantity);op.quantityDeclared=true;}if(edit.quantityUnit!==undefined){if(!['kg','tấn','m²','m³','m','lần','bộ','cái','giờ','phút','tấm','thanh'].includes(edit.quantityUnit))fail(400,'Đơn vị định mức không hợp lệ');op.quantityUnit=edit.quantityUnit;}if(edit.amount!==undefined){if(!(numeric(edit.amount)>0))fail(400,'Định mức phải lớn hơn 0');op.amount=edit.amount;}if(edit.machineId!==undefined){if(typeof edit.machineId!=='string')fail(400,'Máy không hợp lệ');const machine=edit.machineId?get('machine',edit.machineId):null;if(edit.machineId&&(!machine||machine.active===false))fail(400,'Máy đã ngừng sử dụng hoặc không tồn tại');op.machineId=edit.machineId;op.machine=machine?.name||'';}if(edit.machine!==undefined&&!edit.machineId){if(typeof edit.machine!=='string'||edit.machine.length>200)fail(400,'Tên thiết bị tối đa 200 ký tự');op.machineId='';op.machine=edit.machine.trim();}if(edit.instructions!==undefined){if(typeof edit.instructions!=='string'||edit.instructions.length>2000)fail(400,'Phương pháp tối đa 2000 ký tự');op.instructions=edit.instructions.trim();}}}
    if(JSON.stringify(n)!==original)changed=true;
    }
    if(!changed)fail(400,'Chưa có thông số thay đổi');if(!b.technicalDocument){d.quote.nestingPlans=[];d.quote.remnantSelections={};}const after=packet(d);if(after.issues.length||after.cutting.some(g=>g.error))fail(400,'Thông số đề nghị không tạo được phương án sản xuất hợp lệ');
    const reviewRows=doc=>C.flatten(doc.quote.products).map(n=>({id:n.id,name:n.name,kind:n.kind,qty:n.qty,unit:n.unit,dims:n.dims,params:n.params,lineNote:n.lineNote,notes:n.notes,requestSpecification:n.requestSpecification}));
    before.reviewRows=reviewRows(originalDocument);after.reviewRows=reviewRows(d);
    const rowReasons=Object.fromEntries(items.map(x=>{if(x.reason!==undefined&&(typeof x.reason!=='string'||x.reason.length>2000))fail(400,'Lý do từng mục tối đa 2000 ký tự');return [x.rowId,x.reason?.trim()||reason];}));
    const c={id:randomUUID(),jobId:j.id,baseVersion:j.version,rowId:rows[0],rowIds:rows,rowReasons,...(documentDiff?{items:documentDiff.rows,structural:documentDiff.structural}:{}),reason,state:'pending',at:new Date().toISOString(),actor:user.name,actorId:user.id,reference:typeof b.reference==='string'?b.reference.trim().slice(0,2000):'',before,after,impact:{before:totals(source(current)),after:totals(d)},document:d};put('production-change',c.id,c);audit(user,'production-change-proposed',j.id,reason);notice(j,['confirm','reviewBusiness','reviewPricing'],'Có bảng kiến nghị cần xem xét');return clean(c,user);
   }
   const c=get('production-change',m[2]);if(!c||c.jobId!==j.id)fail(404,'Không tìm thấy đề nghị');
   if(!['pending','confirmed'].includes(c.state))fail(409,'Đề nghị đã được xử lý');
   const action=m[3];const selected=b.rowIds===undefined?(c.rowIds||[c.rowId]):b.rowIds;if(!Array.isArray(selected)||!selected.length||new Set(selected).size!==selected.length||selected.some(id=>!(c.rowIds||[c.rowId]).includes(id)))fail(400,'Chọn các mục thuộc đề nghị');const selection=[...selected].sort();if(action==='preview'){if(!canPrice(user))fail(403,'Cần quyền xem chi phí');if(c.baseVersion!==current.version)fail(409,'Hồ sơ nguồn đã thay đổi');return {rowIds:selection,before:totals(source(current)),after:totals(applySelection(source(current),c.document,selection))};}const reviewed=v=>v&&JSON.stringify(v.rowIds||[...(c.rowIds||[c.rowId])].sort())===JSON.stringify(selection);const stamp=()=>({id:user.id,name:user.name,at:new Date().toISOString(),rowIds:selection,note:typeof b.note==='string'?b.note.trim().slice(0,2000):''});if(action==='reject'){if(!confirmable(user)&&!AA.allows(user,'production','approveChange',false))fail(403,'Chưa có quyền trả lại');if(typeof b.reason!=='string'||!b.reason.trim()||b.reason.length>2000)fail(400,'Nhập lý do trả lại');c.state='rejected';c.rejection=b.reason.trim();}
   else {editable(current);if(c.baseVersion!==current.version)fail(409,'Thông số lệnh đã đổi; lập đề nghị mới để xác nhận lại');
    if(action==='confirm'){if(!confirmable(user))fail(403,'Cần người có quyền xác nhận kỹ thuật');c.state='confirmed';c.technical=stamp();}
    if(action==='business'||action==='pricing'){if(!AA.allows(user,'production',action==='business'?'reviewBusiness':'reviewPricing',false))fail(403,'Chưa có quyền xác nhận của bộ phận này');if(typeof b.note!=='string'||!b.note.trim()||b.note.length>2000)fail(400,'Ghi kết quả làm việc với khách hoặc đánh giá chi phí và căn cứ');if(action==='pricing'&&b.prices!==undefined){if(!canPrice(user))fail(403,'Cần quyền xem giá để cập nhật giá');if(!Array.isArray(b.prices)||b.prices.length>500||new Set(b.prices.map(p=>p.rowId)).size!==b.prices.length)fail(400,'Danh sách giá không hợp lệ');const nodes=C.flatten(c.document.quote.products);for(const price of b.prices){const n=nodes.find(n=>n.id===price.rowId&&n.kind==='material');if(!n||!selection.includes(n.id)||typeof price.unitPrice!=='number'||!Number.isFinite(price.unitPrice)||price.unitPrice<0||price.unitPrice>1e12)fail(400,'Đơn giá vật tư không hợp lệ');n.spec.price=price.unitPrice;}c.impact={...c.impact,after:totals(c.document)};if(b.prices.length)delete c.business;}if(action==='pricing'&&b.operationPrices!==undefined){if(!canPrice(user))fail(403,'Cần quyền xem giá để cập nhật');require('./production-operation-prices.cjs').update(c.document,selection,b.operationPrices,fail);c.impact={...c.impact,after:totals(c.document)};if(b.operationPrices.length)delete c.business;}c[action]=stamp();}
    if(action==='approve'){if(!AA.allows(user,'production','approveChange',false))fail(403,'Chưa có quyền duyệt điều chỉnh');if(!reviewed(c.technical)||!reviewed(c.business)||!reviewed(c.pricing))fail(409,'Cần kỹ thuật, kinh doanh và bộ phận giá xác nhận cùng các mục được chọn trước khi duyệt');
     const applied=applySelection(source(current),c.document,selection);c.appliedImpact={before:totals(source(current)),after:totals(applied)};
     const data=packet(applied),old=JSON.parse(current.packet),progress=JSON.parse(current.progress);if(data.issues.length||data.cutting.some(g=>g.error))fail(409,'Phương án cần kiểm tra lại');
     const next={...old,technicalInput:data.technicalInput,product:data.products[0],materials:data.materials,operations:PD.reconcileRoute(packet(source(current)).operations,data.operations,old.operations),cutting:data.cutting,finishing:data.finishing,kerf:data.kerf,layoutBasis:'engineering-change'};
     const dossier=get('production-dossier',j.id);if(dossier){delete dossier.reviewed;dossier.reviewChecks={};dossier.confirmations={};dossier.equipment=next.operations.map(o=>({operationId:o.id,machineId:o.machineId||'',machine:o.machine||'',method:o.instructions||''}));put('production-dossier',j.id,dossier);}delete next.flowApproved;progress.materialsReady=false;progress.drawingReady=false;progress.operations=next.operations.map(o=>({...progress.operations.find(p=>p.id===o.id),id:o.id,status:'pending',output:0,machine:o.machine||'',machineId:o.machineId||'',preparationMethod:o.instructions||''}));
     // Reservations must be rechecked against the new geometry. No stock has been issued.
     for(const r of all("SELECT id,document FROM ops_records WHERE kind='hold'")){const h=JSON.parse(r.document);if(h.jobId===j.id&&h.state==='reserved')put('hold',r.id,{...h,state:'released',reason:'Thay đổi kỹ thuật '+c.id});}
     const at=new Date().toISOString();sql.prepare('UPDATE production_jobs SET packet=?,progress=?,version=version+1,updated=?,actor=? WHERE id=?').run(JSON.stringify(next),JSON.stringify(progress),at,user.id,j.id);put('production-source',j.id,applied);const routePrices=get('production-route-prices',j.id);if(routePrices)put('production-route-prices',j.id,routePrices.filter(p=>!data.operations.some(o=>o.id===p.operationId&&selection.includes(o.nodeId))));c.state='approved';c.approvedRowIds=selection;c.notAppliedRowIds=(c.rowIds||[c.rowId]).filter(id=>!selection.includes(id));c.applied= data;c.appliedVersion=current.version+1;
     sql.prepare('INSERT INTO production_events(job_id,at,actor,detail) VALUES(?,?,?,?)').run(j.id,at,user.name,'Duyệt thay đổi kỹ thuật: '+c.reason+' · xác nhận bởi '+c.technical.name);
    }
   }
   c.reviewedById=user.id;c.reviewedBy=user.name;c.reviewedAt=new Date().toISOString();put('production-change',c.id,c);audit(user,'production-change-'+action,j.id,c.reason);notice(j,['approve','reject'].includes(action)?[]:['approveChange'],'Kiến nghị: '+({confirm:'kỹ thuật đã xác nhận',business:'kinh doanh đã xác nhận',pricing:'giá đã xác nhận',approve:'đã duyệt áp dụng',reject:'đã trả lại'})[action],[c.actorId]);return clean(c,user);
  });send(200,out);return true;
 }
 return {handle};
}
module.exports={createProductionChanges};
