'use strict';
const {randomUUID}=require('node:crypto'),C=require('../core.js'),AA=require('../action-access.js');
// Full calculation documents stay server-side. Only technical packets are returned.
function createProductionChanges({sql,fail,readBody,transaction,audit,packet,canWork}){
 const one=(s,...a)=>sql.prepare(s).get(...a),all=(s,...a)=>sql.prepare(s).all(...a);
 const get=(kind,id)=>{const r=one('SELECT document FROM ops_records WHERE kind=? AND id=?',kind,id);return r?JSON.parse(r.document):null;};
 const put=(kind,id,d)=>sql.prepare('INSERT INTO ops_records VALUES(?,?,1,?) ON CONFLICT(kind,id) DO UPDATE SET version=version+1,document=excluded.document').run(kind,id,JSON.stringify(d));
 const clean=c=>{const {document,...v}=c;return v;};
 const confirmable=u=>u.role==='admin'||AA.allows(u,'production','confirm',u.role==='technical'&&require('./access.cjs').permissions(u).sections.includes('operations'));
 const proposeable=u=>AA.allows(u,'production','edit',canWork(u));
 function source(j){let d=get('production-source',j.id);if(d)return d;const o=one('SELECT * FROM orders WHERE id=?',j.order_id),r=one('SELECT document FROM revisions WHERE id=? AND version=?',o.quote_id,o.quote_version);d=JSON.parse(r.document);const p=d.quote.products.find(p=>p.id===j.product_id);d.quote.products=[C.copy(p)];d.quote.products[0].qty=j.quantity;d.quote.nestingPlans=[];d.quote.remnantSelections={};return d;}
 function editable(j){const p=JSON.parse(j.progress);if(j.state!=='ready'||p.operations.some(o=>o.status!=='pending'||o.output>0)||p.qc?.passed||p.qc?.rejected)fail(409,'Lệnh đã bắt đầu sản xuất hoặc QC; không thay đổi thông số của lô đang thực hiện');if(all("SELECT document FROM ops_records WHERE kind='hold'").some(r=>{const h=JSON.parse(r.document);return h.jobId===j.id&&['issued','settled'].includes(h.state);}))fail(409,'Lệnh đã cấp vật tư; cần xử lý lô đang thực hiện trước');}
 function materials(d){const catalog=one('SELECT document FROM catalog ORDER BY version DESC LIMIT 1');const rows=[...(d.materials||[]),...C.flatten(d.quote.products).filter(n=>n.spec).map(n=>n.spec),...(catalog?JSON.parse(catalog.document).materials||[]:[])];return [...new Map(rows.map(m=>[m.id,m])).values()];}
 const safeMaterial=m=>Object.fromEntries(['id','name','shape','props','stockL','stockW','substance','grade'].filter(k=>m[k]!==undefined).map(k=>[k,m[k]]));
 async function handle({req,route,user,send}){
  const m=route.match(/^\/api\/production\/([a-f0-9-]+)\/changes(?:\/([a-f0-9-]+)\/(confirm|business|pricing|approve|reject))?$/);if(!m)return false;
  const j=one('SELECT * FROM production_jobs WHERE id=?',m[1]);if(!j)fail(404,'Không tìm thấy lệnh');
  if(req.method==='GET'&&!m[2]){const d=source(j),nodes=C.flatten(d.quote.products);send(200,{canPropose:proposeable(user),canConfirm:confirmable(user),canBusiness:AA.allows(user,'production','reviewBusiness',false),canPricing:AA.allows(user,'production','reviewPricing',false),canApprove:AA.allows(user,'production','approveChange',false),jobVersion:j.version,machines:all("SELECT document,id FROM ops_records WHERE kind='machine'").map(r=>({id:r.id,...JSON.parse(r.document)})).filter(x=>x.active!==false).map(x=>({id:x.id,name:x.name,code:x.code})),operations:packet(d).operations,products:nodes.filter(n=>n.kind==='product'||n.kind==='component').map(n=>({id:n.id,name:n.name,kind:n.kind,dims:n.dims||{},params:n.params||{}})),materials:materials(d).map(safeMaterial),rows:packet(d).materials.map(r=>{const n=nodes.find(n=>n.id===r.id),numeric=v=>Object.fromEntries(Object.entries(v||{}).filter(([,x])=>typeof x==='number'));return {...r,dims:numeric(n.dims),params:numeric(n.params)};}),changes:all("SELECT document FROM ops_records WHERE kind='production-change'").map(r=>JSON.parse(r.document)).filter(c=>c.jobId===j.id).map(clean)});return true;}
  if(req.method!=='POST')fail(405,'Thao tác không hợp lệ');const b=await readBody(req);
  const out=transaction(()=>{const current=one('SELECT * FROM production_jobs WHERE id=?',j.id);if(current.version!==b.expectedVersion)fail(409,'Lệnh đã thay đổi; tải lại trước khi xử lý');
   if(!m[2]){
    if(!proposeable(user))fail(403,'Chưa có quyền đề nghị thay đổi kỹ thuật');editable(current);
    const reason=typeof b.reason==='string'?b.reason.trim():'';if(!reason||reason.length>2000)fail(400,'Nhập lý do thay đổi (tối đa 2000 ký tự)');
    if(b.rowIds!==undefined&&!Array.isArray(b.rowIds))fail(400,'Danh sách dòng không hợp lệ');const d=source(current),before=packet(d),items=b.items===undefined?(b.rowIds===undefined?[b.rowId]:b.rowIds).map(rowId=>({...b,rowId})):b.items;if(!Array.isArray(items)||items.some(x=>!x||typeof x!=='object'))fail(400,'Danh sách điều chỉnh không hợp lệ');const rows=items.map(x=>x.rowId);
    if(!Array.isArray(rows)||!rows.length||rows.length>500||new Set(rows).size!==rows.length)fail(400,'Chọn từ 1 đến 500 dòng khác nhau');
    let changed=false;
    for(const b of items){const rowId=b.rowId;const n=C.flatten(d.quote.products).find(n=>n.id===rowId&&['material','product','component'].includes(n.kind));if(!n)fail(400,'Dòng vật tư không thuộc lệnh');const original=JSON.stringify(n);
    if(n.kind!=='material'&&(b.materialId!==undefined||b.props&&Object.keys(b.props).length||b.stockL!==undefined||b.stockW!==undefined||b.blank!==undefined))fail(400,'Chỉ áp dụng thông số phôi cho dòng vật tư');
    if(b.materialId!==undefined&&b.materialId!==n.materialId){const s=materials(d).find(x=>x.id===b.materialId);if(!s||s.shape!==n.spec.shape)fail(400,'Chọn vật tư cùng hình dạng để giữ đúng quy tắc khai triển');n.materialId=s.id;n.spec=C.copy(s);n.name=s.name;}
    const numeric=(v)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>1e7)fail(400,'Thông số kích thước không hợp lệ');return v;};
    for(const [field,allowed]of [['dims',Object.keys(n.dims||{})],['params',Object.keys(n.params||{})],['props',Object.keys(n.spec?.props||{})]]){const values=b[field]||{};if(typeof values!=='object'||Array.isArray(values))fail(400,'Thông số không hợp lệ');for(const [k,v]of Object.entries(values)){if(!allowed.includes(k))fail(400,'Thông số không được hỗ trợ: '+k);(field==='props'?n.spec.props:n[field])[k]=numeric(v);}}
    for(const k of ['stockL','stockW'])if(b[k]!==undefined)n.spec[k]=numeric(b[k]);
    if(b.blank!==undefined){if(b.blank===null)delete n.productionBlank;else{if(!b.blank||typeof b.blank!=='object'||Array.isArray(b.blank)||n.spec.shape==='piece')fail(400,'Chọn vật tư có kích thước khai triển');const length=numeric(b.blank.length),width=n.spec.shape==='sheet'?numeric(b.blank.width):0;if(!length||n.spec.shape==='sheet'&&!width)fail(400,'Kích thước khai triển phải lớn hơn 0');n.productionBlank={length,width};}}
    if(b.operations!==undefined){if(!Array.isArray(b.operations)||b.operations.length>100||new Set(b.operations.map(o=>o.index)).size!==b.operations.length)fail(400,'Danh sách công đoạn không hợp lệ');for(const edit of b.operations){const op=n.ops?.[edit.index];if(!Number.isInteger(edit.index)||!op)fail(400,'Công đoạn không thuộc chi tiết');if(edit.amount!==undefined){if(!(numeric(edit.amount)>0))fail(400,'Định mức phải lớn hơn 0');op.amount=edit.amount;}if(edit.machineId!==undefined){if(typeof edit.machineId!=='string')fail(400,'Máy không hợp lệ');const machine=edit.machineId?get('machine',edit.machineId):null;if(edit.machineId&&(!machine||machine.active===false))fail(400,'Máy đã ngừng sử dụng hoặc không tồn tại');op.machineId=edit.machineId;op.machine=machine?.name||'';}if(edit.instructions!==undefined){if(typeof edit.instructions!=='string'||edit.instructions.length>2000)fail(400,'Phương pháp tối đa 2000 ký tự');op.instructions=edit.instructions.trim();}}}
    if(JSON.stringify(n)!==original)changed=true;
    }
    if(!changed)fail(400,'Chưa có thông số thay đổi');d.quote.nestingPlans=[];d.quote.remnantSelections={};const after=packet(d);if(after.issues.length||after.cutting.some(g=>g.error))fail(400,'Thông số đề nghị không tạo được phương án sản xuất hợp lệ');
    const c={id:randomUUID(),jobId:j.id,baseVersion:j.version,rowId:rows[0],rowIds:rows,reason,state:'pending',at:new Date().toISOString(),actor:user.name,actorId:user.id,reference:typeof b.reference==='string'?b.reference.trim().slice(0,2000):'',before,after,document:d};put('production-change',c.id,c);audit(user,'production-change-proposed',j.id,reason);return clean(c);
   }
   const c=get('production-change',m[2]);if(!c||c.jobId!==j.id)fail(404,'Không tìm thấy đề nghị');
   if(!['pending','confirmed'].includes(c.state))fail(409,'Đề nghị đã được xử lý');
   const action=m[3];const selected=b.rowIds===undefined?(c.rowIds||[c.rowId]):b.rowIds;if(!Array.isArray(selected)||!selected.length||new Set(selected).size!==selected.length||selected.some(id=>!(c.rowIds||[c.rowId]).includes(id)))fail(400,'Chọn các mục thuộc đề nghị');const selection=[...selected].sort();const reviewed=v=>v&&JSON.stringify(v.rowIds||[...(c.rowIds||[c.rowId])].sort())===JSON.stringify(selection);const stamp=()=>({id:user.id,name:user.name,at:new Date().toISOString(),rowIds:selection,note:typeof b.note==='string'?b.note.trim().slice(0,2000):''});if(action==='reject'){if(!confirmable(user)&&user.role!=='admin')fail(403,'Chưa có quyền trả lại');if(typeof b.reason!=='string'||!b.reason.trim()||b.reason.length>2000)fail(400,'Nhập lý do trả lại');c.state='rejected';c.rejection=b.reason.trim();}
   else {editable(current);if(c.baseVersion!==current.version)fail(409,'Thông số lệnh đã đổi; lập đề nghị mới để xác nhận lại');
    if(action==='confirm'){if(!confirmable(user))fail(403,'Cần người có quyền xác nhận kỹ thuật');c.state='confirmed';c.technical=stamp();}
    if(action==='business'||action==='pricing'){if(!AA.allows(user,'production',action==='business'?'reviewBusiness':'reviewPricing',false))fail(403,'Chưa có quyền xác nhận của bộ phận này');if(typeof b.note!=='string'||!b.note.trim()||b.note.length>2000)fail(400,'Ghi kết quả làm việc với khách hoặc đánh giá chi phí và căn cứ');c[action]=stamp();}
    if(action==='approve'){if(!AA.allows(user,'production','approveChange',false))fail(403,'Chưa có quyền duyệt điều chỉnh');if(!reviewed(c.technical)||!reviewed(c.business)||!reviewed(c.pricing))fail(409,'Cần kỹ thuật, kinh doanh và bộ phận giá xác nhận cùng các mục được chọn trước khi duyệt');
     const applied=source(current),nodes=C.flatten(applied.quote.products),proposed=C.flatten(c.document.quote.products);for(const id of selection){const dest=nodes.find(n=>n.id===id),src=proposed.find(n=>n.id===id);for(const key of ['name','materialId','spec','dims','params','productionBlank','ops']){if(src[key]===undefined)delete dest[key];else dest[key]=C.copy(src[key]);}}applied.quote.nestingPlans=[];applied.quote.remnantSelections={};
     const data=packet(applied),old=JSON.parse(current.packet),progress=JSON.parse(current.progress);if(data.issues.length||data.cutting.some(g=>g.error))fail(409,'Phương án cần kiểm tra lại');
     const next={...old,technicalInput:data.technicalInput,product:data.products[0],materials:data.materials,operations:[...data.operations,...old.operations.filter(o=>o.catalogId&&!o.nodeId)],cutting:data.cutting,finishing:data.finishing,kerf:data.kerf,layoutBasis:'engineering-change'};
     const dossier=get('production-dossier',j.id);if(dossier){delete dossier.reviewed;dossier.reviewChecks={};dossier.confirmations={};dossier.equipment=next.operations.map(o=>({operationId:o.id,machineId:o.machineId||'',machine:o.machine||'',method:o.instructions||''}));put('production-dossier',j.id,dossier);}delete next.flowApproved;progress.materialsReady=false;progress.drawingReady=false;progress.operations=next.operations.map(o=>({...progress.operations.find(p=>p.id===o.id),id:o.id,status:'pending',output:0,machine:o.machine||'',machineId:o.machineId||'',preparationMethod:o.instructions||''}));
     // Reservations must be rechecked against the new geometry. No stock has been issued.
     for(const r of all("SELECT id,document FROM ops_records WHERE kind='hold'")){const h=JSON.parse(r.document);if(h.jobId===j.id&&h.state==='reserved')put('hold',r.id,{...h,state:'released',reason:'Thay đổi kỹ thuật '+c.id});}
     const at=new Date().toISOString();sql.prepare('UPDATE production_jobs SET packet=?,progress=?,version=version+1,updated=?,actor=? WHERE id=?').run(JSON.stringify(next),JSON.stringify(progress),at,user.id,j.id);put('production-source',j.id,applied);c.state='approved';c.approvedRowIds=selection;c.notAppliedRowIds=(c.rowIds||[c.rowId]).filter(id=>!selection.includes(id));c.applied= data;c.appliedVersion=current.version+1;
     sql.prepare('INSERT INTO production_events(job_id,at,actor,detail) VALUES(?,?,?,?)').run(j.id,at,user.name,'Duyệt thay đổi kỹ thuật: '+c.reason+' · xác nhận bởi '+c.technical.name);
    }
   }
   c.reviewedById=user.id;c.reviewedBy=user.name;c.reviewedAt=new Date().toISOString();put('production-change',c.id,c);audit(user,'production-change-'+action,j.id,c.reason);return clean(c);
  });send(200,out);return true;
 }
 return {handle};
}
module.exports={createProductionChanges};
