'use strict';
const AA=require('../action-access.js');
module.exports=({sql,fail,now})=>{
 const row=id=>sql.prepare("SELECT * FROM ops_records WHERE kind='service-request' AND id=?").get(id);
 const list=kind=>sql.prepare('SELECT id,document FROM ops_records WHERE kind=?').all(kind).map(x=>({...JSON.parse(x.document),id:x.id}));
 function view(id,u){const r=row(id);if(!r)return null;const d=JSON.parse(r.document),holds=list('hold').filter(h=>h.state==='reserved'),lots=list('lot');const prices=AA.allows(u,'purchasing','view',false),stock=AA.allows(u,'inventory','view',false);return {version:r.version,canPrice:AA.allows(u,'purchasing','edit',false),lines:d.lines.map(l=>{const matching=lots.filter(x=>x.materialId===l.materialId&&x.unit===l.unit).map(x=>({id:x.id,warehouse:x.warehouse,quantity:x.quantity,reserved:holds.filter(h=>h.lotId===x.id).reduce((n,h)=>n+h.quantity,0),length:x.length,width:x.width,thickness:x.thickness})).map(x=>({...x,available:Math.max(0,x.quantity-x.reserved)}));return {id:l.id,materialId:l.materialId,name:l.name,unit:l.unit,quantity:l.quantity,specification:l.specification,warehouseReview:l.warehouseReview,priceReview:prices?l.priceReview:undefined,...(stock?{lots:matching,available:matching.reduce((n,x)=>n+x.available,0)}:{})};})};}
 function save(id,key,b,u){const r=row(id);if(!r||b.sourceVersion!==r.version)fail(409,'Đề nghị đã thay đổi; tải lại dữ liệu trước khi lưu');if(key==='price'&&!AA.allows(u,'purchasing','edit',false))fail(403,'Cần quyền cập nhật giá mua');if(key==='stock'&&!AA.allows(u,'inventory','view',false))fail(403,'Cần quyền xem tồn kho');const d=JSON.parse(r.document);if(d.state!=='pending')fail(409,'Đề nghị đã duyệt; không sửa dữ liệu rà soát');if(!Array.isArray(b.lines)||b.lines.length!==d.lines.length||new Set(b.lines.map(l=>l.id)).size!==d.lines.length)fail(400,'Cần khai đủ các dòng vật tư');const live=view(id,u),num=(v,max=1e9)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<0||v>max)fail(400,'Nhập số không âm hợp lệ');return v;};for(const l of d.lines){const x=b.lines.find(x=>x.id===l.id);if(!x)fail(400,'Dòng vật tư không khớp');if(key==='stock'){const proposedQuantity=num(x.proposedQuantity),supplyQuantity=num(x.supplyQuantity),available=live.lines.find(x=>x.id===l.id).available;if(supplyQuantity>proposedQuantity||supplyQuantity>available)fail(409,'Lượng kho đáp ứng vượt tồn khả dụng hoặc lượng đề xuất');if(['tấm','thanh','cái','bộ','chiếc'].includes(l.unit)&&(!Number.isInteger(proposedQuantity)||!Number.isInteger(supplyQuantity)))fail(400,'Số lượng đếm phải nguyên');if(typeof x.note!=='string'||x.note.length>1000)fail(400,'Ghi chú kho tối đa 1.000 ký tự');l.warehouseReview={proposedQuantity,supplyQuantity,purchaseQuantity:proposedQuantity-supplyQuantity,available,note:x.note,at:now(),actor:u.name};}else{const unitPrice=num(x.unitPrice,1e12);if(typeof x.supplier!=='string'||x.supplier.length>200)fail(400,'Nhà cung cấp tối đa 200 ký tự');l.priceReview={unitPrice,supplier:x.supplier,at:now(),actor:u.name};}}
 d.history.push({action:key==='stock'?'warehouse-review':'price-review',actor:u.name,at:now(),note:b.note,reviewLines:d.lines.map(l=>({id:l.id,...(key==='stock'?{warehouseReview:l.warehouseReview}:{priceReview:l.priceReview})}))});d.updated=now();sql.prepare("UPDATE ops_records SET document=?,version=version+1 WHERE kind='service-request' AND id=?").run(JSON.stringify(d),id);
 }
 return {view,save};
};
