'use strict';
const {randomUUID}=require('node:crypto'),AA=require('../action-access.js'),Scope=require('./work-scope.cjs'),F=require('../completion-core.js');
function createWorkBoard(h){
 const {sql,fail,list,get,put,notice,users,person,text,num,date,now,cas,need,allowed,quoteSummary}=h;
 const all=(s,...a)=>sql.prepare(s).all(...a),ops=k=>list(k,'ops_records');
 const scope=u=>Scope.context(sql,u),visible=(t,u)=>Scope.visible(sql,u,t),manage=(t,u,a)=>Scope.canManage(sql,u,t,a);
 const taskDepartment=t=>t.departmentId||scope({id:'',role:'none'}).personDepartments(t.assignee)[0]||'';
 const sourceRight=(u,k)=>AA.allows(u,k,'view',u.role==='admin'||k==='production'&&['technical','estimator','approver'].includes(u.role));
 function sources(u){const rows=[],push=t=>{t.sourceManaged=true;t.workflow='source';const meta=get('work-wait',t.id);t.waits=meta?.waits||[];t.waitVersion=meta?.version||0;t.version=t.version||1;t.plannedHours=t.plannedHours||0;t.startDate=t.startDate||'';t.dueDate=t.dueDate||'';t.created=t.created||'';t.departmentId=scope(u).personDepartments(t.assignee)[0]||'';if(visible(t,u))rows.push(t);};
  if(sourceRight(u,'production'))for(const j of all('SELECT * FROM production_jobs')){const p=JSON.parse(j.packet),g=JSON.parse(j.progress);for(const [index,o]of p.operations.entries()){const v=g.operations.find(v=>v.id===o.id)||{};push({id:'source:production:'+j.id+':'+o.id,name:j.code+' · '+o.name,description:o.instructions||'',creator:v.assignedBy||'',finishedAt:v.finishedAt||'',startDate:v.startedAt?.slice(0,10)||'',assignee:v.assignee||'',source:{kind:'production',id:j.id,operationId:o.id},version:j.version,jobId:j.id,state:v.status==='done'?'confirmed':v.status==='running'?'running':'pending',blocked:index>0&&g.operations[index-1]?.status!=='done',output:v.output||0,plannedOutput:o.quantity,unit:o.outputUnit||'chi tiết',hours:v.hours||0,plannedHours:['h','hour','giờ'].includes(o.unit)?o.workQuantity:0,dueDate:g.deadline||'',issue:v.issue||'',proposal:v.proposal||'',created:j.created||j.updated,updated:j.updated});}}
  if(sourceRight(u,'quotes')){
   const rights=require('./access.cjs').permissions(u);
   if(rights.technical||rights.costs)for(const q of all('SELECT * FROM quotes WHERE id NOT IN (SELECT id FROM quote_deletions)')){const s=quoteSummary(q);for(const stage of ['technical','materials']){if(stage==='materials'&&!rights.costs)continue;const owner=s.work[stage]?.id;if(!owner&&u.role!=='admin')continue;const state=s.work.tasks[stage];push({id:'source:quote:'+q.id+':'+stage,name:q.code+' · '+(stage==='technical'?'Kỹ thuật':'Nhập giá'),assignee:owner||'',source:{kind:'quote',id:q.id},version:q.version,state:state==='completed'?'confirmed':state==='cancelled'?'cancelled':state==='in-progress'?'running':'pending',created:q.updated,updated:q.updated,unit:'việc',plannedOutput:1,output:state==='completed'?1:0});}}
   if(rights.commercial)for(const c of all('SELECT * FROM commercial')){const doc=JSON.parse(c.document),q=sql.prepare('SELECT code,updated FROM quotes WHERE id=? AND id NOT IN (SELECT id FROM quote_deletions)').get(c.id);if(!q)continue;for(const [version,e]of Object.entries(doc.dispatches||{})){const latest=sql.prepare("SELECT MAX(version) v FROM revisions WHERE id=? AND status='approved'").get(c.id)?.v;if(Number(version)!==latest&&!e.sentAt)continue;push({id:'source:offer:'+c.id+':'+version+':send',name:q.code+' V'+version+' · Gửi khách',assignee:e.senderId||'',source:{kind:'offer',id:c.id,version:Number(version)},state:e.sentAt?'confirmed':'pending',version:c.version,unit:'việc',plannedOutput:1,output:e.sentAt?1:0,created:e.sentAt||q.updated,dueDate:e.dueDate||''});if(e.sentAt){const closed=!!e.careClosed;push({id:'source:offer:'+c.id+':'+version+':care',name:q.code+' V'+version+' · Chăm sóc sau gửi',assignee:e.careOwnerId||'',source:{kind:'offer',id:c.id,version:Number(version)},state:closed?'confirmed':'running',version:c.version,created:e.sentAt,dueDate:e.nextCareDate||e.dueDate||'',unit:'việc',plannedOutput:1,output:closed?1:0,issue:(e.entries||[]).filter(x=>x.kind==='issue'&&!x.resolvedAt).map(x=>x.content).join('\n')});}}}
  }
  if(sourceRight(u,'orders'))for(const o of all('SELECT * FROM orders')){const row=sql.prepare("SELECT document FROM business_records WHERE kind='order' AND id=?").get(o.id),meta=row?JSON.parse(row.document):{};push({id:'source:order:'+o.id,name:o.code+' · Phụ trách đơn hàng',assignee:meta.ownerId||'',source:{kind:'order',id:o.id},state:meta.cancelledAt?'cancelled':meta.deliveredAt?'confirmed':'pending',created:o.at,dueDate:meta.dueDate||'',unit:'đơn hàng',plannedOutput:1,output:meta.deliveredAt?1:0});}
  if(sourceRight(u,'purchasing'))for(const p of ops('purchase'))push({id:'source:purchase:'+p.id,name:p.code+' · Theo dõi mua vật tư',assignee:p.actor||'',description:'Bước hiện tại: '+({pending:'Chờ duyệt',approved:'Đã duyệt',ordered:'Đã đặt',shipping:'Đang giao',received:'Đã nhận',stocked:'Đã nhập kho',rejected:'Đã từ chối'}[p.state]||p.state),source:{kind:'purchase',id:p.id},version:p.version,jobId:p.jobId,state:p.state==='stocked'?'confirmed':p.state==='rejected'?'cancelled':p.state==='pending'?'pending':'running',created:p.created,unit:'yêu cầu',plannedOutput:1,output:p.state==='stocked'?1:0});
  return rows;
 }
 function tasks(u){return ops('task').filter(t=>visible(t,u)||t.scheduleApprovalRequired&&allowed(u,'dailyWork','approveSchedule')).concat(sources(u));}
 function find(id,u){return tasks(u).find(t=>t.id===id);}
 function enrich(t,u,reports){const r=reports.filter(r=>r.taskId===t.id),output=t.sourceManaged?(t.output||0):r.reduce((s,r)=>s+r.output,0),hours=t.sourceManaged?(t.hours||0):r.reduce((s,r)=>s+r.hours,0);return {...t,canApproveWait:manage(t,u,'approve'),canApproveSchedule:!t.sourceManaged&&allowed(u,'dailyWork','approveSchedule'),timing:require('../work-period-core.js').timing(t,['done','confirmed'].includes(t.state)?t.finishedAt||(t.events||[]).filter(e=>e.state==='done').at(-1)?.at:undefined),blocked:!!t.scheduleApprovalRequired&&!t.scheduleApprovedAt||t.blocked||!!t.predecessorId&&!['done','confirmed'].includes(get('task',t.predecessorId,'ops_records')?.state),output,hours,progress:t.plannedOutput>0?Math.min(100,100*output/t.plannedOutput):null,overdue:!!t.dueDate&&t.dueDate<F.todayVN()&&!['done','confirmed','cancelled'].includes(t.state),openIssues:r.filter(r=>r.issue&&!r.resolved).length+(t.issue?1:0),canAssign:!t.sourceManaged&&manage(t,u,'assign'),canApprove:!t.sourceManaged&&manage(t,u,'approve'),canClaim:!t.sourceManaged&&!t.assignee&&scope(u).member(t.departmentId)&&(t.eligibleIds||[]).includes(u.id)&&allowed(u,'dailyWork','edit'),canEdit:!t.sourceManaged&&(manage(t,u,'assign')||t.creator===u.id&&t.assignee===u.id&&allowed(u,'dailyWork','edit'))};}
 function productionReports(ts,u){
  const result=[],canCost=require('./access.cjs').permissions(u).costs&&allowed(u,'costs','view');
  for(const t of ts.filter(t=>t.source?.kind==='production')){
   const j=sql.prepare('SELECT progress,packet FROM production_jobs WHERE id=?').get(t.source.id),g=JSON.parse(j.progress),p=JSON.parse(j.packet),op=p.operations.find(o=>o.id===t.source.operationId),baseline=get('baseline',t.source.id,'ops_records');
   const prices=(baseline?.operations||[]).filter(o=>o.object===op.object&&o.name===op.name),price=prices.length===1&&prices[0].unit===op.unit&&Math.abs(prices[0].quantity-op.workQuantity)<1e-6?prices[0]:null;
   let output=0,hours=0;for(const [i,r] of (g.operationReports||[]).filter(r=>r.operationId===op.id).entries()){
    const quantity=Math.max(0,(Number(r.output)||0)-output),worked=Math.max(0,(Number(r.hours)||0)-hours);output=Math.max(output,Number(r.output)||0);hours=Math.max(hours,Number(r.hours)||0);
    if(!quantity&&!worked)continue;
    result.push({id:t.id+':'+i,taskId:t.id,actor:r.assignee||'',actorName:users().find(u=>u.id===r.assignee)?.name||r.actor,date:new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Ho_Chi_Minh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(r.at)),output:quantity,hours:worked,unit:t.unit,content:r.note||'',at:r.at,sourceSnapshot:true,...(canCost?{workValue:price&&op.quantity>0?quantity/op.quantity*price.cost:null}:{} )});
   }
  }return result;
 }
 function state(u){const ts=tasks(u),ids=new Set(ts.map(t=>t.id)),reports=ops('report').filter(r=>ids.has(r.taskId)).concat(productionReports(ts,u)),c=scope(u),people=users().map(p=>({...p,departmentIds:c.personDepartments(p.id),assignable:p.id===u.id||allowed(u,'dailyWork','assign')&&c.manages(p.id)}));
  return {tasks:ts.map(t=>enrich(t,u,reports)),reports:reports.map(r=>({...r,canResolve:manage(ts.find(t=>t.id===r.taskId),u,'approve')})),people,departments:c.d.departments.filter(d=>d.active!==false).map(d=>({id:d.id,name:d.name,parentId:d.parentId,assignable:allowed(u,'dailyWork','assign')&&c.managesDepartment(d.id)})),jobs:sourceRight(u,'production')?all('SELECT id,code FROM production_jobs WHERE state<>?', 'completed'):[],notices:list('notice').filter(n=>n.userId===u.id&&(!n.taskId||ids.has(n.taskId))).sort((a,b)=>b.at.localeCompare(a.at)).slice(0,100),syncedAt:now()};
 }
 function work(part,b,u){need(u,'dailyWork','view');
  if(part==='task'){
   const old=get('task',b.id,'ops_records');cas(old,b);if(old&&!visible(old,u))fail(403,'Ngoài phạm vi công việc');if(old&&['done','confirmed'].includes(old.state))fail(409,'Yêu cầu làm lại trước khi sửa việc đã hoàn thành');
   const assignee=b.assignee||'',departmentId=b.departmentId||'',c=scope(u);if(assignee)person(assignee);if(!assignee&&!departmentId)fail(400,'Chọn người nhận hoặc phòng ban nhận việc');if(departmentId&&!c.d.departments.some(d=>d.id===departmentId&&d.active!==false))fail(400,'Phòng ban không còn hoạt động');if(assignee&&departmentId&&!c.personDepartments(assignee).includes(departmentId))fail(400,'Người nhận không thuộc phòng ban đã chọn');
   if(assignee!==u.id||!assignee||old&&old.assignee!==u.id){need(u,'dailyWork','assign');if(!manage({assignee,departmentId},u,'assign')||old&&!manage(old,u,'assign'))fail(403,'Chỉ giao việc trong phạm vi phòng ban được quản lý');}else need(u,'dailyWork','edit');
   const reassignment=old&&old.assignee!==assignee;const reassignmentReason=reassignment?text(b.reassignmentReason||'',2000,true):'';if(reassignment&&(old.waits||[]).some(w=>!w.end))fail(409,'Kết thúc khoảng chờ trước khi thay người');
   const jobId=b.jobId||'',j=jobId?sql.prepare('SELECT * FROM production_jobs WHERE id=?').get(jobId):null;if(jobId&&(!j||j.state==='completed'||!sourceRight(u,'production')))fail(400,'Không có lệnh trong phạm vi');const startDate=date(b.startDate),dueDate=date(b.dueDate);if(dueDate<startDate)fail(400,'Hạn trước ngày bắt đầu');
   const parentId=b.parentId||'';if(parentId){const parent=find(parentId,u);if(!parent||['done','confirmed','cancelled'].includes(parent.state))fail(400,'Công việc cha không còn đang thực hiện');let cur=parent,seen=new Set([old?.id]);while(cur){if(seen.has(cur.id))fail(400,'Công việc cha con không được tạo vòng lặp');seen.add(cur.id);cur=cur.parentId?get('task',cur.parentId,'ops_records'):null;}}
   const predecessorId=b.predecessorId===undefined?(old?.predecessorId||''):text(b.predecessorId,200);
   if(old&&predecessorId!==(old.predecessorId||'')&&!['pending','accepted'].includes(old.state))fail(409,'Không đổi việc trước khi đã bắt đầu');
   if(predecessorId){const previous=find(predecessorId,u);if(!previous||previous.sourceManaged||previous.state==='cancelled')fail(400,'Chọn việc trước trong phạm vi được xem');}
   const previousTask=predecessorId?get('task',predecessorId,'ops_records'):null;const targetDepartment=departmentId||c.personDepartments(assignee)[0]||'';const crossDepartment=!!previousTask&&taskDepartment(previousTask)!==targetDepartment;
   const candidateId=old?.id||'new-task',graph=ops('task').filter(t=>t.id!==old?.id).concat([{id:candidateId,parentId,predecessorId}]),visited=new Set(),visiting=new Set();
   function checkCycle(id){if(visiting.has(id))fail(400,'Quan hệ công việc tạo vòng chờ nhau');if(visited.has(id))return;visiting.add(id);const t=graph.find(x=>x.id===id);if(t?.predecessorId)checkCycle(t.predecessorId);for(const child of graph.filter(x=>x.parentId===id))checkCycle(child.id);visiting.delete(id);visited.add(id);}
   for(const t of graph)checkCycle(t.id);
   const relatedIds=b.relatedIds||[];if(!Array.isArray(relatedIds)||relatedIds.length>50)fail(400,'Người liên quan không hợp lệ');for(const id of relatedIds){person(id);if(id!==u.id&&!c.manages(id))fail(403,'Người liên quan ngoài phạm vi quản lý');}
   const eligibleIds=b.eligibleIds===undefined?(old?.eligibleIds||[]):b.eligibleIds;if(!Array.isArray(eligibleIds)||eligibleIds.length>100)fail(400,'Danh sách người nhận không hợp lệ');for(const id of eligibleIds){person(id);if(!departmentId||!c.personDepartments(id).includes(departmentId))fail(400,'Người nhận dự kiến phải thuộc bộ phận');}
   const priority=b.priority||'normal';if(!['low','normal','high','urgent'].includes(priority))fail(400,'Mức ưu tiên không hợp lệ');
   const d={...old,name:text(b.name,300,true),description:text(b.description||'',3000),assignee,departmentId,eligibleIds:[...new Set(eligibleIds)],parentId,predecessorId,relatedIds:[...new Set(relatedIds)],priority,unit:text(b.unit||'việc',40,true),plannedOutput:num(b.plannedOutput||0),creator:old?.creator||u.id,workflow:'enterprise',jobId,orderId:j?.order_id||'',startDate,dueDate,plannedHours:num(b.plannedHours,100000),state:old?.assignee!==assignee?'pending':old?.state||'pending',created:old?.created||now(),updated:now()};
   if(old&&ops('report').some(r=>r.taskId===old.id)&&((old.unit||'việc')!==d.unit||old.parentId!==d.parentId&&!!old.parentId))fail(409,'Đã có báo cáo: không đổi đơn vị hoặc chuyển công việc cha');
   const scheduleChanged=!old||old.dueDate!==dueDate||old.startDate!==startDate||old.assignee!==assignee||old.departmentId!==departmentId||old.predecessorId!==predecessorId;d.scheduleApprovalRequired=crossDepartment; if(scheduleChanged){d.scheduleApprovedAt=crossDepartment&&allowed(u,'dailyWork','approveSchedule')&&assignee?now():null;d.scheduleApprovedBy=d.scheduleApprovedAt?u.id:null;}if(reassignment)d.events=[...(old.events||[]),{state:'reassigned',actor:u.id,at:now(),reason:reassignmentReason,from:old.assignee,to:assignee}];
   const r=put('task',old?.id||randomUUID(),d,(old?.version||0)+1,'ops_records');const recipients=assignee?[assignee]:users().filter(p=>c.personDepartments(p.id).includes(departmentId)&&(!eligibleIds.length||eligibleIds.includes(p.id))).map(p=>p.id);const supervisors=assignee?all('SELECT * FROM users WHERE active=1 AND deleted_at IS NULL').filter(p=>p.id!==assignee&&scope(p).manages(assignee)&&allowed(p,'dailyWork','assign')).map(p=>p.id):[];for(const id of new Set([...recipients,...relatedIds,...supervisors,...(crossDepartment&&!d.scheduleApprovedAt?all('SELECT * FROM users WHERE active=1 AND deleted_at IS NULL').filter(p=>allowed(p,'dailyWork','approveSchedule')).map(p=>p.id):[])]))notice(id,'Giao việc: '+r.name,r.id);return r;
  }
  const t=part==='schedule'&&allowed(u,'dailyWork','approveSchedule')?get('task',b.taskId||b.id,'ops_records'):find(b.taskId||b.id,u);if(!t)fail(404,'Không có công việc trong phạm vi');cas(t,b);
  if(part==='transition'){
   if(t.sourceManaged)fail(409,'Công việc liên thông cập nhật tại nghiệp vụ nguồn');const to=b.state,approval=to==='confirmed'||to==='running'&&t.state==='done';need(u,'dailyWork',approval?'approve':'edit');if(approval&&!manage(t,u,'approve'))fail(403,'Ngoài phạm vi xác nhận');
   const claim=!t.assignee&&t.departmentId&&scope(u).member(t.departmentId)&&(t.eligibleIds||[]).includes(u.id)&&to==='accepted';if(!approval&&t.assignee!==u.id&&!claim)fail(403,'Chỉ người nhận cập nhật công việc');const paths={pending:['accepted'],accepted:['running'],running:['done'],done:['confirmed','running']};if(!paths[t.state]?.includes(to))fail(409,'Bước công việc không hợp lệ');
   if(['running','done','confirmed'].includes(to)&&t.scheduleApprovalRequired&&!t.scheduleApprovedAt)fail(409,'Tiến độ/chuyển việc liên bộ phận cần admin hoặc người được ủy quyền duyệt');
   if(['running','done','confirmed'].includes(to)&&t.predecessorId&&!['done','confirmed'].includes(get('task',t.predecessorId,'ops_records')?.state))fail(409,'Chờ việc trước báo hoàn thành');
   if(to==='running'&&t.state==='done'&&ops('task').some(x=>x.predecessorId===t.id&&!['pending','accepted'].includes(x.state)))fail(409,'Việc kế tiếp đã triển khai; cần xử lý ảnh hưởng trước khi yêu cầu làm lại');
   if(['done','confirmed'].includes(to)){if(ops('task').some(c=>c.parentId===t.id&&c.state!=='confirmed'))fail(409,'Còn công việc con chưa được xác nhận');if(ops('report').some(r=>r.taskId===t.id&&r.issue&&!r.resolved))fail(409,'Còn vướng mắc chưa xử lý');const output=ops('report').filter(r=>r.taskId===t.id).reduce((s,r)=>s+r.output,0);if(t.plannedOutput>output)fail(409,'Khối lượng báo cáo chưa đủ kế hoạch');}
   if(['running','done','confirmed'].includes(to)&&(!t.assignee||!t.dueDate))fail(409,'Cần người chịu trách nhiệm và hạn hoàn thành');if(['done','confirmed'].includes(to)&&(t.waits||[]).some(w=>!w.end))fail(409,'Kết thúc thời gian chờ trước khi báo hoàn thành');
   const reason=text(b.reason||'',2000,to==='running'&&t.state==='done'),r=put('task',t.id,{...t,assignee:claim?u.id:t.assignee,state:to,updated:now(),updatedBy:u.id,transitionNote:reason,events:[...(t.events||[]),{state:to,actor:u.id,at:now(),reason}]},t.version+1,'ops_records');
   const reviewers=to==='done'?all('SELECT * FROM users WHERE active=1 AND deleted_at IS NULL').filter(x=>manage(r,x,'approve')).map(x=>x.id):[];for(const id of new Set([r.assignee,r.creator,...(r.relatedIds||[]),...reviewers]))if(id)notice(id,'Công việc '+r.name+': '+({accepted:'Đã nhận',running:'Đang làm',done:'Chờ xác nhận',confirmed:'Đã xác nhận'}[to]),r.id);
   if(to==='done')for(const next of ops('task').filter(x=>x.predecessorId===r.id&&['pending','accepted'].includes(x.state))){const recipients=next.assignee?[next.assignee]:users().filter(p=>scope(u).personDepartments(p.id).includes(next.departmentId)&&(!(next.eligibleIds||[]).length||next.eligibleIds.includes(p.id))).map(p=>p.id);for(const id of new Set([...recipients,...(next.relatedIds||[])]))notice(id,'Sẵn sàng nhận việc: '+next.name,next.id);}
   return r;
  }
  if(part==='schedule'){
   need(u,'dailyWork','approveSchedule');if(t.sourceManaged||!t.assignee||!t.dueDate)fail(409,'Cần người thực hiện và hạn hoàn thành trước khi duyệt');
   const r=put('task',t.id,{...t,scheduleApprovedAt:now(),scheduleApprovedBy:u.id,scheduleReason:text(b.reason,2000,true)},t.version+1,'ops_records');for(const id of new Set([t.creator,t.assignee]))notice(id,'Đã duyệt tiến độ phối hợp: '+t.name,t.id);return r;
  }
  if(part==='wait'){
   if(t.sourceManaged&&t.source?.kind!=='production')fail(409,'Khoảng chờ áp dụng cho công việc và công đoạn sản xuất');if(t.sourceManaged&&(b.waitVersion??0)!==t.waitVersion)fail(409,'Khoảng chờ đã thay đổi; tải lại');
   const waits=structuredClone(t.waits||[]),at=now();
   if(b.action==='start'){
    need(u,'dailyWork','edit');if(t.assignee!==u.id||!['accepted','running'].includes(t.state))fail(403,'Chỉ người thực hiện ghi nhận chờ khi đang nhận/làm việc');
    if(waits.some(w=>!w.end))fail(409,'Đang có thời gian chờ chưa kết thúc');
    if(!['materials','approval'].includes(b.kind))fail(400,'Chọn chờ vật tư hoặc chờ duyệt');
    waits.push({id:randomUUID(),kind:b.kind,start:at,reason:text(b.reason,2000,true),reference:text(b.reference,500,true),actor:u.id});
   }else{
    const w=waits.find(w=>w.id===b.waitId);if(!w)fail(404,'Không có khoảng chờ');
    if(b.action==='end'){need(u,'dailyWork','edit');if(t.assignee!==u.id&&!manage(t,u,'approve'))fail(403,'Không có quyền kết thúc chờ');if(w.end)fail(409,'Khoảng chờ đã kết thúc');w.end=at;w.endedBy=u.id;}
    else if(b.action==='approve'){need(u,'dailyWork','approve');if(!manage(t,u,'approve'))fail(403,'Chỉ người giao hoặc admin xác nhận thời gian chờ');if(!w.end||w.approvedAt)fail(409,'Khoảng chờ chưa kết thúc hoặc đã duyệt');w.approvedAt=at;w.approvedBy=u.id;}
    else fail(400,'Thao tác thời gian chờ không hợp lệ');
   }
   const r=t.sourceManaged?put('work-wait',t.id,{waits,updated:at},t.waitVersion+1):put('task',t.id,{...t,waits,updated:at},t.version+1,'ops_records');for(const id of new Set([t.creator,t.assignee]))if(id)notice(id,'Thời gian chờ: '+t.name,t.id);return r;
  }
  if(part==='report'){
   need(u,'dailyWork','edit');if(t.assignee!==u.id&&u.role!=='admin')fail(403,'Chỉ người nhận báo cáo');if(!['accepted','running'].includes(t.state))fail(409,'Nhận/bắt đầu công việc trước khi báo cáo');const day=date(b.date),hours=num(b.hours,24);if(day>F.todayVN()||t.startDate&&day<t.startDate)fail(400,'Ngày báo cáo ngoài thời gian thực hiện');if(ops('report').filter(r=>r.actor===u.id&&r.date===day).reduce((s,r)=>s+r.hours,0)+hours>24)fail(400,'Tổng giờ báo cáo vượt 24');const report=put('report',randomUUID(),{taskId:t.id,jobId:t.jobId||'',orderId:t.orderId||'',actor:u.id,actorName:u.name,date:day,hours,output:num(b.output),unit:t.unit||'việc',content:text(b.content,3000,true),issue:text(b.issue||'',3000),proposal:text(b.proposal||'',3000),nextPlan:text(b.nextPlan||'',3000),resolved:false,at:now()},1,'ops_records');if(report.issue||report.proposal)for(const manager of all('SELECT * FROM users WHERE active=1 AND deleted_at IS NULL').filter(x=>manage(t,x,'approve')))notice(manager.id,'Vướng mắc / kiến nghị: '+t.name,t.id);return report;
  }
  if(part==='resolve'){need(u,'dailyWork','approve');if(!manage(t,u,'approve'))fail(403,'Ngoài phạm vi xử lý');const r=get('report',b.reportId,'ops_records');if(!r||r.taskId!==t.id||!r.issue||r.resolved)fail(409,'Không có vướng mắc đang mở');const resolved=put('report',r.id,{...r,resolved:true,resolution:text(b.resolution,3000,true),resolvedBy:u.name,resolvedAt:now()},r.version+1,'ops_records');for(const id of new Set([t.assignee,r.actor,...(t.relatedIds||[])]))if(id)notice(id,'Đã xử lý vướng mắc: '+t.name,t.id);return resolved;}
  if(part==='read'){const n=get('notice',b.noticeId);if(!n||n.userId!==u.id)fail(404,'Không có thông báo');return put('notice',n.id,{...n,read:true},n.version+1);}
  fail(404,'Thao tác không có');
 }
 return {state,work,find};
}
module.exports={createWorkBoard};
