// Build artifact: one self-contained HTML file, usable offline or on a static host.
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=name=>fs.readFileSync(path.join(root,name),'utf8');
let html=read('index.html');
// Preserve the customer-supplied logo byte for byte, including in offline exports.
html=html.replaceAll('assets/truong-phat-logo.jpg','data:image/jpeg;base64,'+fs.readFileSync(path.join(root,'assets/truong-phat-logo.jpg')).toString('base64'));
for(const file of ['styles.css','pricing.css','intake.css','batch-one.css','rules-catalog.css','workspace-theme.css'])html=html.replace('<link rel="stylesheet" href="'+file+'">',()=>'<style>'+read(file)+'</style>');
for(const file of ['core.js','completion-core.js','source-core.js','conventions-core.js','work-core.js','manufacturing-core.js','cost-flow-core.js','group-pricing-core.js','pricing-core.js','entry-core.js','model3d.js','model3d-render.js','ux.js','remnant-ui.js','model3d-ui.js','pricing-ui.js','work-ui.js','manufacturing-ui.js','group-pricing-ui.js','cost-flow-ui.js','quotes-ui.js','xlsx.js','export-ui.js','technical-core.js','technical-ui.js','section-access.js','workspace-home-ui.js','team-sections-ui.js','team-ui.js','team-access-ui.js','quote-output-ui.js','rate-lab-ui.js','catalog-price-ui.js','completion-ui.js','source-ui.js','catalog-sync-ui.js','conventions-ui.js','rules-catalog-ui.js','declaration-review-core.js','declaration-review-ui.js','input-prices-core.js','input-prices-ui.js','factor-matrix-core.js','factor-matrix-ui.js','pricing-declarations-ui.js','quote-operation-choice-ui.js','material-estimate-ui.js','quote-logistics-ui.js','product-scope-ui.js','quote-workspace-ui.js','customer-feedback-ui.js','customer-import-core.js','customer-import-ui.js','catalog-draft-ui.js','workflow-status-ui.js','formula-access-ui.js','app.js'])html=html.replace('<script src="'+file+'"></script>',()=>'<script>'+read(file).replace(/<\/script/gi,'<\\/script')+'</script>');
for(const file of ['cost-input-core.js','offer-terms-core.js','batch-six-ui.js','tax-core.js','tax-ui.js','device-core.js','device-ui.js','batch-three-ui.js','dimension-links-core.js','batch-two-ui.js','shape-expression-core.js','definition-core.js','definition-ui.js','batch-one-core.js','customer-fields-core.js','crm-core.js','crm-ui.js','customer-fields-ui.js','notifications-ui.js','account-review-ui.js','catalog-audit-core.js','catalog-audit-ui.js','tmc-labor-ui.js','operation-table-core.js','operation-table-ui.js','package-operation-core.js','package-operation-ui.js','intake-core.js','intake-ui.js','quote-prices-ui.js','batch-one-ui.js'])html=html.replace('<script src="'+file+'"></script>',()=>'<script>'+read(file).replace(/<\/script/gi,'<\\/script')+'</script>');
const out=path.join(root,'dist');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'index.html'),html,'utf8');
console.log('Built dist/index.html ('+Buffer.byteLength(html)+' bytes), no external runtime dependencies.');
